### ISSUE TITLE
List of preferred languages grows with each OpenID login

### ISSUE THREAD

**Issue by arni-inaba** [FusionAuth/fusionauth-issues#1006]
### Description 
After updating from version 1.16.1 to 1.20.0, we have noticed that every time a user logs in via Google, their "Preferred languages" list in the FusionAuth admin interface grows.

After having signed in 5 times, my user looks like this:
<img width="265" alt="Screenshot 2020-11-24 at 09 33 21" src="https://user-images.githubusercontent.com/1704173/100109940-4853f080-2e64-11eb-85ec-34d83392b387.png">

Log in again, and now it looks like this:
<img width="320" alt="Screenshot 2020-11-24 at 14 45 34" src="https://user-images.githubusercontent.com/1704173/100109967-5275ef00-2e64-11eb-82dd-4512e340cb6c.png">

This also happens when running locally in Docker. We use the default Reconcile lambda to grab user information from Google, which happens to include `"preferredLanguages" : [ "en" ]`

This does not happen when the Reconcile lambda is disabled.
This does not happen when using email/password to log in.

### Affects versions
1.20.0, 1.20.1

### Steps to reproduce
1. Add Google as an OpenID identity provider.
2. Enable the default OpenID Reconcile lambda provided by FusionAuth.
3. Create a user with a gmail address.
4. Log in a few times.
5. Observe how the Preferred languages list grows with every login.

### Expected behavior
List of preferred languages should only show each language once.

### Workaround
Check for duplicates in the lambda. Example:

```javascript
if (jwt.locale) {
    user.preferredLanguages = user.preferredLanguages || [];
    // Replace the dash with an under score.
    var newLocale = jwt.locale.replace('-', '_');
    if (user.preferredLanguages.indexOf(newLocale) == -1) {
      user.preferredLanguages.push(newLocale);
    }
  }
```

### Platform
(Please complete the following information)
 - Device: Any
 - Environment: Docker and fusionauth.io hosting
 - Browser: Any
 - Database: PostgreSQL

### Additional context
Looking at the lambda itself, it appends whatever it finds in `jwt.locale` to `user.preferredLanguages` without checking if there are duplicates, hence the unexpected behaviour.
```javascript
  if (jwt.locale) {
    user.preferredLanguages = user.preferredLanguages || [];
    // Replace the dash with an under score.
    user.preferredLanguages.push(jwt.locale.replace('-', '_'));
  }
```

**Comment by mooreds** [comment]
One workaround right now would be to update the default reconcile lambda.

This works for me (to prevent duplicate languages):

```
if (jwt.locale) {
    user.preferredLanguages = user.preferredLanguages || [];
    // Replace the dash with an under score.
    const newLocale = jwt.locale.replace('-', '_');
    if (user.preferredLanguages.indexOf(newLocale) == -1) {
      user.preferredLanguages.push(newLocale);
    }
  }
```
