### ISSUE TITLE
Sign in with Apple failing on certain accounts

### ISSUE THREAD

**Issue by thekoding** [FusionAuth/fusionauth-issues#1010]
### Description
Trying to sign in via Apple with some accounts fails, with the following error in the Event Log:
`Request to the [https://appleid.apple.com/auth/token] endpoint failed. Status code [-1] Exception encountered. java.net.SocketTimeoutException : Message: Read timed out`

Apple login works with some accounts, but with others it fails with the message provided above. The kicker is that I don't know the specific account, since it's the one Apple uses when trying to verify an app update in the App Store.

For reference, I am running FusionAuth v1.17.4, but I haven't seen this issue referenced in the release notes.

**Comment by robotdan** [comment]
The default read timeout on the request to `https://appleid.apple.com/auth/token` is 2 seconds. This is quite a long time to wait during an interactive login. 

We can look at increasing this value, or exposing it through configuration.

**Comment by thekoding** [comment]
So I assume we don't have a way to "forcefully" change the timeout manually meanwhile, do we?

**Comment by robotdan** [comment]
No, not currently.

**Comment by robotdan** [comment]
We can try increasing the read timeout to see if that resolves the issue. We may want to look at exposing this configuration at some point.

**Comment by robotdan** [comment]
If this still occurs with 1.22.0, there is likely something else going on, let us know how it goes.
