### ISSUE TITLE
Error when creating or viewing user comment and actioning user email not set

### ISSUE THREAD

**Issue by pamcpd** [FusionAuth/fusionauth-issues#1012]
### Description 
Logged in to FusionAuth interface as primary admin user; this user does not have an email set. Adding or viewing a comment for another user causes an error. The "actioning user" is expected to have an email address.

### Affects versions
1.21.0

### Steps to reproduce
Steps to reproduce when creating a comment:
1. Login to interface as a user without an email address (or remove email address from user).
2. Navigate to another user. Add a comment.
3. User hangs, upper right action button spins on "Loading...", bottom of user profile pages shows:
![emailbug](https://user-images.githubusercontent.com/41343209/100650588-65277280-3301-11eb-92ac-07e8f3a224d1.PNG)

Steps to reproduce when viewing an existing comment:
1. Login to interface as a user without an email address (or remove email address from user).
2. Navigate to another user, History tab. View an existing comment by this user.
3. User profile pages shows:
![emailbug2](https://user-images.githubusercontent.com/41343209/100651857-593cb000-3303-11eb-985a-2c1b79d57d0d.png)

### Expected behavior
If actioning user email is expected, should be enforced when creating or editing the actioning user. If not, actioning user should reference user name if email not present.

### Platform
 - OS: Windows Server 2019
 - Database: MySQL 8

### Additional context
Workaround is to add email address for actioning user.

Stack trace
[emailbug.txt](https://github.com/FusionAuth/fusionauth-issues/files/5618025/emailbug.txt)

**Comment by robotdan** [comment]
Thanks for the report @pamcpd! Much appreciated.
