### ISSUE TITLE
Device Auth : Successfully connected device, now what?!

### ISSUE THREAD

**Issue by jerryhopper** [FusionAuth/fusionauth-issues#1015]
### Description
When the device-authorization is successfull, there is no (known) way to put some additional information on the 'Device Login: Successfully connected device' page.

One would like to display some extra instructions, or other information resources ( link/redirect to device information/manual/setupguide )  or be able to close this page/window/

Is customizing the fusionauth template the only way to present additional information on this page?

![image](https://user-images.githubusercontent.com/1160857/100733921-2f50bf80-33cf-11eb-90a3-8f9a6fb71814.png)

PS: i am aware that this info could be displayed on the device, after successful login. In my case - my device doesnt have a display, and is using 'output' via other protocols *(http/websocket)

**Comment by mooreds** [comment]
You should be able to modify the `OAuth device complete` template to add additional information after the device grant is complete. 

More here: https://fusionauth.io/docs/v1/tech/themes/

Does that resolve the issue?

**Comment by jerryhopper** [comment]
Yes, if the following bug is fixed :  #1016
