### ISSUE TITLE
Device Authorization : Programmatically authorize the device

### ISSUE THREAD

**Issue by jerryhopper** [FusionAuth/fusionauth-issues#1019]
### Description
This issue is about programatically authorize a device, for use in CI/CD.  I seem to be unable to authorize a device and get a refresh_token back.  

the docs say:  Upon validating the end-user provided user_code the typical Authorization Grant, Implicit Grant, or Password Grant flows may be followed for authentication. The OAuth endpoints that facilitate these typical OAuth flows take a user_code parameter to facilitate the Device Authorization Grant approval

Im using the password grant.

Below i describe the steps that i have been taking.

1. Request DeviceAuthorization  
    The request: POST /oauth2/device_authorize (scope=offline_access)
    The response: json with code & urls

2. Programmatically authorize the device, and this is the problem.

2.1. GET http://localhost:9011/oauth2/device/validate?client_id=CID&user_code=CODE
   Response status : 200

2.2. POST http://localhost:9011/oauth2/token  (grant_type=password + user_code=CODE)
   ( with or without setting : 'scope=offline_access')
   The response: {"access_token":"***","expires_in":3599,"token_type":"Bearer","userId":"00000000-0000-0000-0000-000000000001"}

3. Poll for DeviceAuthorization Token
   The reponse: {"access_token":"***","expires_in":3599,"token_type":"Bearer","userId":"00000000-0000-0000-0000-000000000001"}

PROBLEM:  No refresh_token?

How do one activate the device programmatically and get a refresh_token ?

**Comment by jerryhopper** [comment]
I have the following repo (https://github.com/jerryhopper/fusionauth-kickstart) where the problem occurs.
In the CI/CD workflow ( /.github/workflows/test.yml ) each step is described.

the **Manually Authorize device** step you can see that no refresh_token is returned.

**Comment by robotdan** [comment]
In your application oauth configuration, can you confirm that you have selected "Generate Refresh Tokens"? 
https://fusionauth.io/docs/v1/tech/core-concepts/applications/#oauth

**Comment by jerryhopper** [comment]
Hey @robotdan,
My live server does have the grant enabled ( see pic ), and the generate refreshtoken is enabled.

![image](https://user-images.githubusercontent.com/1160857/101159908-71c40780-362e-11eb-9f0b-ab61950cc46a.png)

And the server i launched with my kickstartserver config : 
 
"oauthConfiguration": {
            "deviceVerificationURL": "http://localhost:9111/oauth2/device?client_id=#{applicationId}&tenantId=#{defaultTenantId}",
            "generateRefreshTokens": true,
            "requireClientAuthentication": false,
            "enabledGrants": [
              "urn:ietf:params:oauth:grant-type:device_code",
              "authorization_code",
              "refresh_token",
              "password"
            ]
          }
