### ISSUE TITLE
Backup of database table fails when using MySQLWorkbench

### ISSUE THREAD

**Issue by Loketony** [FusionAuth/fusionauth-issues#1022]
**Backup of database table fails when using MySQLWorkbench**

### Description 
When trying to do a complete backup of MySQL fusionauth-tables using MySQLWorkbench it fails with the following error:

`15:45:50 Dumping fusionauth (all tables)
Running: /Applications/MySQLWorkbench.app/Contents/MacOS/mysqldump --defaults-file="/var/folders/qz/pmw15bgs0934xnf8mmt526wr0000gp/T/tmpGISsF_/extraparams.cnf"  --host=localhost --protocol=tcp --user=root --force=TRUE --port=3306 --default-character-set=utf8 --skip-triggers "fusionauth"
Error executing task: 'ascii' codec can't encode character u'\u20ac' in position 15: ordinal not in range(128)
Operation failed with exitcode -15`

### Affects versions
FusionAuth 1.22.0

### Steps to reproduce
1. Open MySQL WorkBench
2. Choose in Main Menu: Server -> Data Export
4. Click 'Export' for the FusionAuth schema
5. Select 'Dump Structure and Data'
6. I also selected 'Include Create Schema'
7. Click button 'Start Export'

### Expected behavior
A MySQL data dump to file.

### Platform
macOS Catalina 10.15.7
8.0.21 MySQL Community Server
MySQL WorkBench 8.0.22

**Comment by Loketony** [comment]
I should also mention that a workable alternative is to use mysqldump to create a backup:

`mysqldump --user=root --password='***' fusionauth > fusionauth-20201205.sql`

**Comment by voidmain** [comment]
This looks like an encoding issue. FusionAuth databases and tables must be UTF-8 encoded and it looks like your command is using an ASCII codec. I’m not familiar with MySQLWorkbench but there should be a way to use the utf8mb4 codec.

**Comment by Loketony** [comment]
@voidmain Yes you are probably right. And now when I think more about it – the error is probably in the mysqldump version used by MySQL Workbench (`/Applications/MySQLWorkbench.app/Contents/MacOS/mysqldump`), because when I use the version installed by Homebrew (see above) it works as expected.

**Comment by voidmain** [comment]
Thanks for the update. I'll close this out for now then.
