### ISSUE TITLE
Make Default Signing Key ID Available in Kickstart Templates

### ISSUE THREAD

**Issue by dan-barrett** [FusionAuth/fusionauth-issues#1026]
### Problem
I am writing a Kickstart template that creates an Application. I would like to be able to refer to the UUID of the Default Signing Key in this template, but at the moment I seem to have no way of accessing it.

### Solution
@robotdan [here](https://github.com/FusionAuth/fusionauth-issues/issues/446#issuecomment-739968296) indicates that there are analogous features to refer to default forms and default lambdas. Hopefully this can be implemented in a similar manner.

### Alternatives/workarounds
One possible workaround is creating our own key and pointing to that one instead.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks @dan-barrett !

**Comment by mooreds** [comment]
In case this wasn't clear, @dan-barrett , this was released in 1.22.1 :)

**Comment by dan-barrett** [comment]
Thank you @robotdan for the quick turnaround!
