### ISSUE TITLE
Additional FusionAuth app user roles for L1 support

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1027]
### Problem
I want to allow L1 support into the FusionAuth admin UI and limit their capability. There is a `user_manager` role today, but because this use can manage users and registrations, this mostly makes this role an `admin`. 

### Use Cases

- Allow a L1 support person to log in and manage users. 
  - Cannot delete a user
  - Cannot modify roles of an existing user
  - Cannot assign roles when adding a registration, only default roles will be assigned. 
  - Cannot create registrations for the FusionAuth application.
  - Cannot modify the `email` or `username` of an existing user. 

- Allow a L1 support person to log in and have a read only view of the users. 
  - Only view access, no edit, delete, or create capability allowed. 

### Solution
Add two new roles. 

Role 1: User Viewer
This role is a read only viewer and has no capability add, modify or delete user data. The use case for this role is a L1 observer.

Role 2: User Support
This role allows for a limited scope of user management. The use case for this role is a L1 support rep, this user should be able to manage users and assist with account management. 

This role would be allowed to perform the following tasks:

- Add a user
- Edit a user, except for any identity information that could be used to authenticate. For example, the email and username cannot be modified. 
- Add a registration, no role management. If a new registration is created it would receive the default roles only.
- Edit a registration, no role modification.  
- Delete a registration. (We could optionally move this to a user_registration_deleter role or something like that)
- View a registration
- Send a forgot password request
- Send a verify email request
- Require a password change at next login
- Lock a user account
- Unlock a user account
- Modify 2FA settings if available
- Action a user
- Add a comment to a user
- Manage group membership (This is TBD, if a group contains FusionAuth app roles, this may allow this user to become an admin, needs some investigation)
- Manage family membership
- Manage consents
- Manage sessions (refresh tokens)

This role would be restricted from the following tasks to ensure the user cannot become an admin by account takeover, account creation, or elevating their own privilege by role modification. 

- Delete a user (this requires user_deleter role)
- Adding roles to a user during a create registration.
- Modifying roles of an existing registration, roles will be read only during edit.
- Creating registrations for the FusionAuth application.
- Remove FusionAuth registration
- Modifying the email address or username of an existing user. This ensures that you cannot simply takeover an account by modifying an email address and sending a password reset request to your email address. 
  - This also means that a user with elevated privilege will be required to make email or username modifications. 
- Modify password, this would allow the user to login with any account that has FusionAuth admin and then takeover an account. 

### Update for debate
- User is a `group_manager` - can this user add the `admin` role to any group? This should probably be restricted to the `admin` role.
- User is a `user_support_manager` - can this user add any user to any group? What if this group includes an `admin` role? Should group membership management be restricted to `group_manager` or can we just limit what a `user_support_manager` can do as it pertains to membership management. Perhaps this user cannot manage group membership to any group that contains roles for the FusionAuth Application. However this can change at a later date by the admin or group manager. 

### Known Limitations with this feature.
- User with `user_support_manager` cannot modify existing users' email. 
  - There may be legitimate use cases where you want to modify the user's email. 
  - We could add this in the future, ideally we'd add additional safe guards to protect against blatant account takeover, or other social engineering vectors with allowing a L1 / CSR to modify a user's email address. 
-  User with `user_support_manager` cannot select roles when adding a registration, or modify roles when editing a registration. 
- User with `user_support_manager` cannot add a group membership to a group that contains any FusionAuth Application roles, or any Application roles designated as 'isSuperRole`. 
 

### Alternatives/workarounds
Use the API to provider L1 features and limit the scope however you wish. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by bguyza** [comment]
Re: Update for debate
- It sounds like our big concern with the ability to grant admin permission or role is a more restricted role granting themselves admin. Perhaps as a rule of thumb, only admins can grant any sort of admin roles. Thus, I would say `group_manager` should not be able to grant admin.
- I'm not sure I understand the full scope of the second bullet, "user is a user_support_manager", but I'm mostly inclined to think that if a specific user should have both, "user_support_manager" and "group_manager" if they want to address group membership?
