### ISSUE TITLE
Add link to documentation in the FusionAuth admin ui

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1031]
### Problem
I want a link to the docs, but have to go to the URL bar to type in fusionauth.io.

### Solution
Add a link to the fusionauth.io documentation in the menu bar. Under "System", add a "Documentation" link. On clicking it the user should be sent to the fusionauth technical docs (in a new tab).

### Alternatives/workarounds

Open up a new tab, type in fusionauth.io, click around.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Are you looking for a more direct link than what we have today? 

![image](https://user-images.githubusercontent.com/1148709/101722844-4d21c280-3a68-11eb-8286-d00440221d5f.png)

This goes to https://fusionauth.io/docs

**Comment by mooreds** [comment]
Ah, totally missed that. Closing.
