### ISSUE TITLE
OAuth2 login shortly redirects to HTTP even though HTTPS should be used

### ISSUE THREAD

**Issue by sigalor** [FusionAuth/fusionauth-issues#1035]
### Description
I have deployed FusionAuth on a public HTTPS server, but logging in shortly redirects the user to a HTTP page.

### Affects versions
I'm running FusionAuth version 1.21.0

###  Steps to reproduce
1. Install FusionAuth, set up OAuth2 and a respective application to be logged in to and serve it publicly via HTTPS, e.g. at `https://auth.example.com`.
2. Go to the OAuth login page of FusionAuth (`https://auth.example.com/oauth2/authorize?response_type=code&redirect_uri=[...]&scope=offline_access&client_id=[...]`) and log in with correct credentials.
3. Now the browser first does a POST to `https://auth.example.com/oauth2/authorize` with the entered credentials and various meta information in the POST body.
4. As the credentials are correct, that endpoint responds with status code 302 with `Location: http://auth.example.com/oauth2/complete-registration?client_id=[...]&[...]`. But because this is HTTP, some browsers warn the user, because data is sent in an insecure way.
5. Immediately, the HTTP page from step 4 responds with `Location: [the exact same URL of /oauth2/complete-registration, just with HTTPS]`, i.e. the connection is upgraded to HTTPS, so the login can continue normally.

### Expected behavior
Upon successful login, /oauth2/authorize should immediately redirect to the HTTPS version of /oauth2/complete-registration, if HTTPS is already used anyway, and not rely on the fact that HTTP connections are implicitly upgraded to HTTPS ones.

**Comment by sigalor** [comment]
Good catch! With the second line newly added, the nginx reverse proxy configuration now reads (the last line refers to the internal cloud service):

```
proxy_set_header X-Forwarded-Host auth.example.com;
proxy_set_header X-Forwarded-Proto https;
proxy_pass http://our-example-auth-service.default.svc.cluster.local;
```

And I could confirm that the `X-Forwarded-Proto` header actually arrives in FusionAuth:

```
POST /oauth2/authorize HTTP/1.0
X-Forwarded-Host: auth.example.com
X-Forwarded-Proto: https
Host: the-frontend-service.default.svc.cluster.local
[...]
```

Still, the problem persists. Do you have an idea what else could be the problem?

**Comment by sigalor** [comment]
We also tried setting the header `X-Forwarded-Port: 443` for FusionAuth, but that did not change anything either. For now, as a temporary solution, we just configured nginx to replace `http://` by `https://` in the Location header of the response of `POST /oauth2/authorize`.

**Comment by robotdan** [comment]
@voidmain is correct, you likely have a configuration issue with your proxy, or are missing some headers.

**Comment by mooreds** [comment]
You can see some other proxy configurations here: https://github.com/fusionauth/fusionauth-contrib

If you build an nginx proxy, please consider contributing it to that repo. The only nginx proxy in there doesn't support SSL termination.

**Comment by maksimorlovich** [comment]
I also have the same issue as @sigalor with POST to /oauth2/authorize first redirects to http, then to https. I ended up doing the same workaround with `proxy_redirect http:// https://;` in my nginx configuration.
