### ISSUE TITLE
Add a Rust client

### ISSUE THREAD

**Issue by tverghis** [FusionAuth/fusionauth-issues#1038]
### Problem
FusionAuth does not currently have a Rust client library. Development against FusionAuth in Rust is still definitely possible, but a bit more tedious than, say, in Java.

### Solution
A Rust client library is created and published to crates.io.

### Alternatives/workarounds
Using the standard FusionAuth REST APIs without a client wrapper.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@tverghis would an OpenAPI yaml file from which you could generate a rust client work for you? More details on the generator here: https://openapi-generator.tech/docs/generators/rust/

**Comment by tverghis** [comment]
@mooreds yes, that would be a great start!

Ideally, I would prefer a hand-written library, for a few reasons:
- tests can be written for the library as it's being developed
- any dependencies that are brought in (eg: HTTP client) can be reasoned about, and can be swapped out easily enough
- performance might be easier to control with a hand-written library

However, I can understand why writing individual clients is not really scalable, so an OpenAPI spec would be the next best thing 😄 

I'll continue to write my pared-down version of a FusionAuth client for now, and keep and eye out for that yaml file!

**Comment by robotdan** [comment]
@tverghis in the mean time, if you want to try your hand at building the client - all you'd need to do is provide the basic syntax and REST interface. 

Review this comment on the parts necessary to build a new client, and if it looks like something you want to try - let us know. 
https://github.com/FusionAuth/fusionauth-issues/issues/974#issuecomment-723232482

**Comment by tverghis** [comment]
@robotdan seems pretty straightforward, very interested in trying this out!

**Comment by mooreds** [comment]
At this time you should use the OpenAPI client and generate a rust SDK using the OpenAPI tools:

https://github.com/FusionAuth/fusionauth-openapi
