### ISSUE TITLE
Add java curl to the docker image 

### ISSUE THREAD

**Issue by danielporto** [FusionAuth/fusionauth-issues#1044]
### Problem
In Docker-compose/stack some workflows and monitors use healthchecks to validate the state of containers. Currently it is necessary to create a new image just to add curl and be able to run a script to check if the container is healthy.  

### Solution
Adds curl to the last container layer of fusionauth-app image solves the problem. A better solution would be adding a small script that avoids increasing the image size. For instance https://github.com/rockswang/java-curl.

### Alternatives/workarounds
Currently I build a new image just for it as mentioned in https://github.com/FusionAuth/fusionauth-containers/issues/66

### Additional context
- https://github.com/FusionAuth/fusionauth-containers/issues/66
- https://github.com/FusionAuth/fusionauth-issues/issues/2272

**Comment by robotdan** [comment]
Looks like this will add ~ 7.56MB to the image.

**Comment by robotdan** [comment]
Will handle via :
- https://github.com/FusionAuth/fusionauth-issues/issues/2272
