### ISSUE TITLE
SAML Response XML is invalid: The SAML XSD requires the Signature element to be just after the Issuer element

### ISSUE THREAD

**Issue by MrChrisRodriguez** [FusionAuth/fusionauth-issues#1047]
### Description 
The SAML response XML being generated by FusionAuth is invalid. The XSD requires that the Signature element appear immediately after the Issuer element. FusionAuth is not fulfilling this requirement, so some SPs aren't even processing the Response because it fails validation (Twilio, for example). Auth0 had [this same issue](https://github.com/auth0/node-samlp/issues/42) back in 2017, as well.

### Affects versions
v1.22.2

### Steps to reproduce
1. Set up a SAML Application
2. Turn on debugging
3. Try to authorize
4. Copy the Response XML from the log
5. Paste into an XML validator and see it fails

### Expected behavior
The Signature element should appear immediately following the issuer element.

### Screenshots
* [This image shows the FusionAuth output failing XML validation.](https://share.getcloudapp.com/ApuGvYNk)
* [This image shows it passing when I manually move the Signature element.](https://share.getcloudapp.com/GGu27Q0v)

### Platform
(Please complete the following information)
 - Device: MacBook Pro, but the instance is running on Fargate.
 - OS: Mac
 - Browser + version Chrome
 - Database: MySQL

### Additional context
N/A

**Comment by MrChrisRodriguez** [comment]
You can actually see the correct schema representation in fusionauth-samlv2 here:

[https://github.com/FusionAuth/fusionauth-samlv2/blob/master/src/main/xsd/saml-schema-assertion-2.0.xsd#L61](https://github.com/FusionAuth/fusionauth-samlv2/blob/master/src/main/xsd/saml-schema-assertion-2.0.xsd#L61)

I just started digging so I'm not sure how this fits into FusionAuth but thought it may be worth mentioning.

**Comment by robotdan** [comment]
Thanks for the report @MrChrisRodriguez !

**Comment by robotdan** [comment]
Fix included in 0.5.1 via https://github.com/FusionAuth/fusionauth-samlv2/issues/2.
