### ISSUE TITLE
FusionAuth stops randomly, but nothing in the log

### ISSUE THREAD

**Issue by gregoriopellegrino** [FusionAuth/fusionauth-issues#1048]
### Description
I use fusionauth on CentOS as an operating system service. Lately I often find that the service is up and running for a day or two, then randomly, it stops working.

The problem is that I can't find anything in the log so I don't understand what's going on.

Do you have any suggestions for identifying the problem?

**Comment by robotdan** [comment]
You could take a look at the system log. If the OOM killer ended a process due to memory constraints it will be logged there.

 https://docs.memset.com/other/linux-s-oom-process-killer

**Comment by gregoriopellegrino** [comment]
Yep, I think I got it:

```
Dec 30 12:00:38 vps kernel: Out of memory: Kill process 24404 (mysqld) score 691 or sacrifice child
Dec 30 12:00:38 vps kernel: Out of memory: Kill process 30047 (java) score 98 or sacrifice child
```

How can I manage it? How can I restart it automatically? (for MySQL I don't have stops)

**Comment by gregoriopellegrino** [comment]
It seems related to memory problems on MySQL side, can it be? Maybe if the MySQL server has problems then FusionAuth shuts down?

**Comment by robotdan** [comment]
The OOM killer will begin killing services once the kernel runs out of memory. The solution will be to allocate less memory to FusionAuth or to increase the amount of RAM available to the host OS.
