### ISSUE TITLE
CORS Vuejs Authorizaiton code flow

### ISSUE THREAD

**Issue by AnassKartit** [FusionAuth/fusionauth-issues#105]
### Description
Using a VueJS I am redirecting the user to the login page then getting the authorization code and trying to post that to the token endpoint to receive a token using javascript but I am getting a CORS issue, how can I authenticate using javascript?

**Comment by robotdan** [comment]
If I understand correctly, you're attempting to complete the Authorization Code grant using the Token endpoint in JavaScript?

**Comment by AnassKartit** [comment]
Hi,
Yes I am using an SPA and trying to login using FusionAuth and get a token, what is the best way, I am also using Fusion Auth as Containers behind an ingress controller (Nginx). Are there any libraries to support that? Thanks

**Comment by robotdan** [comment]
The link I provided above is a recommended sequence diagram for login. 
https://fusionauth.io/articles/logins/spa/oauth-authorization-code-grant-jwts-refresh-tokens-cookies

If you want to use the Implicit Grant, you could use this workflow: 
https://fusionauth.io/articles/logins/spa/oauth-implicit-grant-jwts-cookies

Here is a list of all of the  common types:
https://fusionauth.io/articles/logins/types-of-logins-authentication-workflows

**Comment by robotdan** [comment]
@AnassKartit have you been able to resolve your issue?

**Comment by AnassKartit** [comment]
Yes, Thanks
