### ISSUE TITLE
.net SDK - Prefer IDictionary over Dictionary

### ISSUE THREAD

**Issue by atrauzzi** [FusionAuth/fusionauth-issues#1050]
### Description

Taking a look at the `IFusionAuthClient` contract, I can see that all dictionary parameters being used are of the concrete, generic `Dictionary` type.  This results in ugliness like the following:

```
Argument type 'System.Collections.Generic.IDictionary<string,object>' is not assignable to parameter type 'System.Collections.Generic.Dictionary<string,object>'
```

It's considered best practice in .net to prefer the most abstract type when accepting parameters, which in this case would be the generic interface `IDictionary<,>`. The FusionAuth .net SDK is only reading the data from the dictionaries, so it doesn't need to enforce any concrete `Dictionary<,>` type.

### Additional context
I've omitted other details as this is more of a code smell issue than anything performance or environment related! :smile: 

I don't suspect a change like this would break backwards compatibility. If anything, it will improve compatibility and flexibility by allowing people to provide whatever dictionary implementations they want (ImmutableDictionary), etc...

**Comment by robotdan** [comment]
Thanks for the suggestion. I wonder if we used `Dictionary` when we first built this for compatibility with earlier versions of C# / .NET Core. Seems like this should be an easy change.

**Comment by atrauzzi** [comment]
Hmm, hard to say.  This has been a pretty common best-practice in .net since before I really got going with it full time (ca. 2014).

**Comment by robotdan** [comment]
Very possible, maybe just a pebkac on our end.
