### ISSUE TITLE
Is there a way to populate email address in SAML connections?

### ISSUE THREAD

**Issue by joseEkcit** [FusionAuth/fusionauth-issues#1053]
### Description

We have to implement a SAML connection with an external Idp that does not provide any email. Would it be possible to populate the user email using lambdas, or setting it afterwards using the API?

**Comment by mooreds** [comment]
@joseEkcit I think I already answered this question (partially) here: https://fusionauth.io/community/forum/topic/304/identity-provider-with-no-email/24

When I mentioned opening an issue, I was thinking of a feature request, where you'd explain what you wanted. This Github repo is for feature requests and bugs, not for support requests. Sorry about the miscommunication.

If you'd like to open a new feature request, please do so using this template: https://github.com/FusionAuth/fusionauth-issues/issues/new?template=feature_request.md

If you'd like to continue the conversation in the forum, please do so. If you have a support contract, please open a support ticket: https://account.fusionauth.io/account/support/

Again, sorry for the confusion! I'm going to close this issue.
