### ISSUE TITLE
Having difficulties to connect super user credentials and password to xampp mariadb on ubuntu 20.04

### ISSUE THREAD

**Issue by emiglobetrotting** [FusionAuth/fusionauth-issues#1055]
![3](https://user-images.githubusercontent.com/7821018/103660984-202cd680-4f66-11eb-90ae-ac59e2b18a68.png)

I have xamp installed on /opt/lampp on ubuntu for development. In my my.conf file I changed

    user=mysql to user=root

And in my phpmyadmin config.inc.php I set

    $cfg['Servers'][$i]['user'] = 'root';
    $cfg['Servers'][$i]['password'] = 'myrootpassword';

I also changed port number from :80 to :3306 in /usr/local/fusionauth/config/fusionauth.properties to this line of statement

    database.url=jdbc:mysql://localhost:3306/fusionauth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

Then I restarted the fusionauth-app with the following command

    sudo service fusionauth-app start

In another attempt, I created a mysql user called fusionauth and also replaced root to root and granted privileges and set password with both having the same 'myrootpassword' with the following command

    CREATE USER 'root'@'%%' IDENTIFIED BY 'myrootpassword';
    GRANT ALL PRIVILEGES ON * . * TO 'root'@'%%';
    FLUSH PRIVILEGES;
    SET PASSWORD FOR 'root'@'localhost' = PASSWORD('myrootpassword');

    CREATE USER 'fusionauth'@'%%' IDENTIFIED BY 'myrootpassword';
    GRANT ALL PRIVILEGES ON * . * TO 'fusionauth'@'%%';
    FLUSH PRIVILEGES;
    SET PASSWORD FOR 'fusionauth'@'localhost' = PASSWORD('myrootpassword');

I have done all of these, yet I can't pass through the maintenance mode and I keep receiving Access denied errors. Please I need help on how to overcome this error.

**Comment by mooreds** [comment]
Hiya @emiglobetrotting ! 

Thanks for using FusionAuth. GitHub issues is for bug reports with replication steps and feature requests.

Please use the forum for support requests: https://fusionauth.io/community/forum/

Alternatively, open a support ticket if you have a support contract: https://account.fusionauth.io/account/support/

Closing this issue since it is a support request.

**Comment by robotdan** [comment]
Side note, MariaDB is not supported. 
https://github.com/FusionAuth/fusionauth-issues/issues/367
