### ISSUE TITLE
Kickstart fails when apiKeys tenantId is a variable

### ISSUE THREAD

**Issue by rhofland** [FusionAuth/fusionauth-issues#1060]
### Description 
Used docker image (1.22.2) and tried to use the "Tenants API Keys" example on the [Kickstart](https://fusionauth.io/docs/v1/tech/installation-guide/kickstart/) page. Install fails and complains that the variable "#{secondTenantId}" is not a UUID. Looks like the variable is not being replaced with UUID from the variables section.

### Affects versions
1.22.2

### Steps to reproduce
1. use docker image fusionauth/fusionauth-app:1.22.2
2. Use environment variable FUSIONAUTH_APP_KICKSTART_FILE to point to kickstart.json
3. kickstart.json (this is the example from fusionauth website): 
```json
{
  "variables": {
    "secondTenantId": "#{UUID()}"
  },
  "apiKeys": [
    {
      "key": "4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd"
    },
    {
      "key": "0ad00c5f140c43f8bc2a155dd0edf3b7d61f5dd4011843d8a28475a0d812c033",
      "description": "Restricted API key - only for Retrieve User in Aviato",
      "permissions": {
        "endpoints": {
          "/api/user": [
            "GET"
          ]
        }
      },
      "tenantId": "#{secondTenantId}"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "/api/tenant/#{secondTenantId}",
      "body": {
        "tenant": {
          "name": "Aviato"
        }
      }
    }
  ]
}
```

5. Error: 
<pre>Invalid kickstart file, unable to parse the JSON.
fusionauth_1     | com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.UUID` from String "#{secondTenantId}": UUID has to be represented by standard 36-char representation
fusionauth_1     |  at [Source: (String)"{
fusionauth_1     |   "variables": {
fusionauth_1     |     "secondTenantId": "#{UUID()}"
fusionauth_1     |   },
fusionauth_1     |   "apiKeys": [
fusionauth_1     |     {
fusionauth_1     |       "key": "4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd"
fusionauth_1     |     },
fusionauth_1     |     {
fusionauth_1     |       "key": "0ad00c5f140c43f8bc2a155dd0edf3b7d61f5dd4011843d8a28475a0d812c033",
fusionauth_1     |       "description": "Restricted API key - only for Retrieve User in Aviato",
fusionauth_1     |       "permissions": {
fusionauth_1     |         "endpoints": {
fusionauth_1     |           "/api/user": [
fusionauth_1     |             "GET"
fusionauth_1     |           ]
fusionauth_1     |         }
fusionauth_1     |       },
fusionauth_1     |       "tenantId": "#{secondTenantId}"
fusionauth_1     |     }
fusionauth_1     |   ],
fusionauth_1     | "[truncated 185 chars]; line: 19, column: 19] (through reference chain: io.fusionauth.api.domain.KickstartRequest["apiKeys"]->java.util.ArrayList[1]->io.fusionauth.api.domain.KickstartRequest$APIKey["tenantId"])
fusionauth_1     | 	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
fusionauth_1     | 	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1679)
fusionauth_1     | 	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:935)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.std.UUIDDeserializer._badFormat(UUIDDeserializer.java:79)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.std.UUIDDeserializer._deserialize(UUIDDeserializer.java:42)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.std.UUIDDeserializer._deserialize(UUIDDeserializer.java:13)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:145)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserializeWith(SettableBeanProperty.java:560)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.impl.MergingSettableBeanProperty.deserializeAndSet(MergingSettableBeanProperty.java:80)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
fusionauth_1     | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
fusionauth_1     | 	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
fusionauth_1     | 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)
fusionauth_1     | 	at io.fusionauth.api.service.system.kickstart.DefaultKickstartService.kickstart(DefaultKickstartService.java:174)
fusionauth_1     | 	at io.fusionauth.api.service.system.KickStarter.<init>(KickStarter.java:15)
fusionauth_1     | 	at io.fusionauth.api.service.system.KickStarter$$FastClassByGuice$$7550f1f1.newInstance(<generated>)
fusionauth_1     | 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
fusionauth_1     | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
fusionauth_1     | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
fusionauth_1     | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
fusionauth_1     | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
fusionauth_1     | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
fusionauth_1     | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
fusionauth_1     | 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
fusionauth_1     | 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
fusionauth_1     | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
fusionauth_1     | 	at com.google.inject.Guice.createInjector(Guice.java:87)
fusionauth_1     | 	at com.google.inject.Guice.createInjector(Guice.java:69)
fusionauth_1     | 	at com.google.inject.Guice.createInjector(Guice.java:59)
fusionauth_1     | 	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
fusionauth_1     | 	at org.primeframework.mvc.servlet.PrimeServletContextListener.contextInitialized(PrimeServletContextListener.java:61)
fusionauth_1     | 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeServletContextListener.contextInitialized(MaintenanceModePrimeServletContextListener.java:68)
fusionauth_1     | 	at io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener.contextInitialized(FusionAuthAppPrimeServletContextListener.java:26)
fusionauth_1     | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
fusionauth_1     | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
fusionauth_1     | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fusionauth_1     | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
fusionauth_1     | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
fusionauth_1     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
fusionauth_1     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
fusionauth_1     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
fusionauth_1     | 	at java.base/java.lang.Thread.run(Thread.java:832)
</pre>

### Expected behavior
Successfully complete installation when using variable for tenantId in "apiKeys" section of kickstart.json

### Screenshots
None

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: MacOS
 - Chrome 87.0.4280.88
 - Database PostgresSQL version 11

### Additional context
None

**Comment by robotdan** [comment]
Thanks @rhofland - looks like a bug. On the first pass to de-serialize the kickstart configuration the variables have not yet been resolved, and we are failing to marshal `#{secondTenantId}` into a `UUID`.
