### ISSUE TITLE
Unable to add additional java options with spaces in the configuration file

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1065]
### Description 

If I am trying to set additional java options in the `fusionauth.properties` file and they have spaces in them, I am not able to start FusionAuth.

./catalina.sh: eval: line 476: unexpected EOF while looking for matching `''

### Affects versions

1.22.2

### Steps to reproduce
1. Stop FusionAuth
1. Edit `config/fusionauth.properties`
1. Navigate to the `fusionauth-app.additional-java-args` and change it to read `fusionauth-app.additional-java-args="-Duser.language=fr -Duser.region=FR"`
1. Start FusionAuth

You'll see 

./catalina.sh: eval: line 476: unexpected EOF while looking for matching `"'

The same behavior occurs if you try single quotes:

`fusionauth-app.additional-java-args='-Duser.language=fr -Duser.region=FR'`

### Expected behavior

The additional java args are passed to FusionAuth at startup.

Note that using an environment variable works and is a viable workaround. 

`export FUSIONAUTH_APP_ADDITIONAL_JAVA_ARGS="-Duser.language=fr -Duser.region=FR"` works fine and is picked up by the startup script.

### Platform

- `macOS`

We will want to test this on `macOS`, `Linux`, and `Windows` (`setenv.bat`) to ensure the `setenv` parsing is working in all cases.

**Comment by robotdan** [comment]
Accepted PRs against `fusionauth-app` and `fusionauth-search`. @6a61795f can you open PRs for the Windows equivalent files? Thanks.

**Comment by 6a61795f** [comment]
If I remember correctly, you did commit changes windows bat files

**Comment by 6a61795f** [comment]
commit 503e86da2cdf8b5790e62fbe0dbe5fae83994248 (origin/master, origin/HEAD)
Author: Daniel DeGroff <daniel@fusionauth.io>
Date:   Tue Feb 16 12:47:29 2021 -0700

    Fix Windows batch scripts.
    https://github.com/FusionAuth/fusionauth-issues/issues/1065

**Comment by robotdan** [comment]
Yes, you're correct - oops, forgot! Thanks!
