### ISSUE TITLE
Unable to change locale of the fusionauth admin UI

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1066]
### Description 

I want to change how the dates and numbers are formatted in the FusionAuth admin UI. 

For example, the dashboard shows recent logins but the date format is always "1/12/2021 09:28 AM MST"

If I change the locale of fusionauth, this date format should change. For example, if it is in the french locale, the date above should be 12/1/2021 (day first).

### Affects versions

1.22.2

### Steps to reproduce
1. Stop FusionAuth
1. export a new locale for Tomcat: `export FUSIONAUTH_APP_ADDITIONAL_JAVA_ARGS="-Duser.language=fr -Duser.region=FR`
1. Start FusionAuth
1. Visit the admin ui dashboard

Expected: dates shown in the french format. 

Reality: no change in the date display.

### Expected behavior

Dates and other values displayed according to the locale specified at startup.

### Platform

MacOS big sur, Firefox

### Additional context

Trying to do this to bug https://github.com/fusionauth/fusionauth-issues/issues/1065 being found.

Came out of this forum post: https://fusionauth.io/community/forum/topic/718/how-do-i-change-the-localisation-timezone-for-the-fusionauth-ui

**Comment by robotdan** [comment]
Is this a documented way to set the locale in the UI? I would not expect this to work.

**Comment by mooreds** [comment]
This is not documented. I found something about how to set the [default locale](https://knowm.org/set-tomcats-default-locale/) in tomcat and was trying to see if it would work. 

From https://www.oracle.com/technical-resources/articles/javase/locale.html :

> Second, on some Java runtime implementations, the application user can override the host's default locale by providing this information on the command line by setting the user.language, user.country, and user.variant system properties.

Looks like that is not supported by openjdk: https://bugs.openjdk.java.net/browse/JDK-4499580 

If there's a different way to set the locale in FusionAuth, would love to document that.

So this seems like more of a feature request and less of a bug. Will update the description to reflect that.

**Comment by robotdan** [comment]
Ah, ok.

The preferred locale on your user will set the locale in the UI. If you also have a preferred locale set on your FusionAuth registration that will take precedence over the value set on the user.

**Comment by mooreds** [comment]
Awesome, thanks!

Closing this.
