### ISSUE TITLE
Deployment with ssl

### ISSUE THREAD

**Issue by jsissom** [FusionAuth/fusionauth-issues#107]
### Description
I have deployed the application in docker and have an apache proxy in front of it.  For now it is using a self-signed certificate.  I added the certificate to the keystore file to make sure the app trusts it.

It seems that many things don't work because it doesn't know it's own host name.  When I try to login, I get an error about an invalid request_uri.  When I try to edit settings, I get ERR_BLOCKED_BY_XSS_AUDITOR.

Here's my apache configuration:

```
<VirtualHost *:80>
  ServerName auth.ksingle2.sissom.org

  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

<VirtualHost *:443>
  ServerName auth.ksingle2.sissom.org

  RequestHeader set X-Forwarded-Proto "https"
  RequestHeader set X-Forwarded-Host "auth.ksingle2.sissom.org"
  RequestHeader set X-Forwarded-Port "443"

  SSLEngine on
  SSLCertificateFile      /etc/httpd/ssl/wildcard.ksingle2.sissom.org.cert.pem
  SSLCertificateKeyFile   /etc/httpd/ssl/wildcard.ksingle2.sissom.org.key.pem
  SSLCertificateChainFile /etc/httpd/ssl/chain.crt

  ErrorLog logs/authapp_fusionauth_error.log
  CustomLog logs/authapp_fusionauth_access.log combined

  ProxyPass "/" "http://10.101.116.155:9011/"
  ProxyPassReverse "/" "http://10.101.116.155:9011/"
</VirtualHost>
```

Is there any place I need to specify the host name to the software?  From what I have read, I thought the X-Forwarded headers would have done it.

If I try to login with a new session, I get this error message:

```
{
  "error" : "invalid_request",
  "error_description" : "The request is missing a required parameter: redirect_uri",
  "error_reason" : "missing_redirect_uri"
}
```

But the URL is:

https://auth.ksingle2.sissom.org/oauth2/authorize?client_id=3c219e58-ed0e-4b18-ad48-f4f92793ae32&response_type=code&redirect_uri=https%3A%2F%2Fauth.ksingle2.sissom.org%2C+auth.ksingle2.sissom.org%2Flogin&state=0dtgoo9RbRHPyVYC-RhHwAjSRdsEU_3RN6AWaQfadwM

As you can see, the redirect_uri is there but the value is odd.

Thanks

**Comment by robotdan** [comment]
The reason for that error message is that the URL contains the same parameter twice. 

```
redirect_uri=https://auth.ksingle2.sissom.org, auth.ksingle2.sissom.org/login
```

This parameter should be 

```
redirect_uri=https://auth.ksingle2.sissom.org
```

Which would then make your full URL look like this (un-encoded)

```
https://auth.ksingle2.sissom.org/oauth2/authorize?client_id=3c219e58-ed0e-4b18-ad48-f4f92793ae32&response_type=code&redirect_uri=https://auth.ksingle2.sissom.org&state=0dtgoo9RbRHPyVYC-RhHwAjSRdsEU_3RN6AWaQfadwM
```

Are you building that value manually or are you using a library to integrate with FusionAuth? If you're picking the `redirect_uri` up from a hidden field on your end, perhaps you have specified the field twice in your form?

**Comment by jsissom** [comment]
This error happens when I go to FusionApp at https://auth.ksingle2.sissom.org/ (this is a local url, not one on the internet).  It's FusionApp trying to authenticate itself.  At this point, I haven't setup a master key or added an application.

Is there an easy way to tell docker I want to run version 1.4?  I thought I had this working under 1.4 but would like to test it again.

**Comment by jsissom** [comment]
To clarify:

* I have an empty postgres database
* I start FusionApp
* Go to my url that is a proxy for the app https://auth.ksingle2.sissom.org/
* I see this screen:

![Screen Shot 2019-04-08 at 3 46 09 PM](https://user-images.githubusercontent.com/393755/55752393-e38d1d80-5a15-11e9-91c9-e72c00a77d1f.png)

* I fill out this screen and get to the dashboard
* I then go to a new browser and go to my url https://auth.ksingle2.sissom.org/
* I get the error message:

![Screen Shot 2019-04-08 at 3 47 36 PM](https://user-images.githubusercontent.com/393755/55752430-fef82880-5a15-11e9-9c6f-0592d46cb1b3.png)

**Comment by jsissom** [comment]
This may be an apache problem.  The apache documentation for "RequestHeader set" says  "The response header is set, replacing any previous header with this name. The value may be a format string."

That doesn't seem to be the case.  It looks like it adds it with a comma.  So apache was sending the wrong header to fusionauth.  I removed that line from the apache config and from my first test it looks OK.  I'll keep testing.

It would still be nice to know if there is a way to get a docker image for previous versions.  I wouldn't like to be surprised my an upgrade to the application.  Those need to be tested and planned.  It would be great if the pushed image had a version number and not just "latest".

Thanks

**Comment by robotdan** [comment]
Thanks @jsissom for the update, good to hear you're making progress. 

There is a docker image for each version of FusionAuth. You can see each tagged version here: https://hub.docker.com/r/fusionauth/fusionauth-app/tags

You should be able to swap out your `latest` tag for a version instead.

**Comment by jsissom** [comment]
Thanks.  I missed the tags on the image.  That's very helpful.

I've been working with the app and it seems to be working properly now.  Thanks for your help.
