### ISSUE TITLE
Unable to localize the social sign in button text

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1071]
### Problem
You can specify what you'd like for the 'Sign in with Facebook' or other social login buttons, but it is the same for all users, regardless of locale.

### Solution
I want to be able to localize the 'sign in with XYZ' button in the same way as the rest of the hosted login pages.

### Alternatives/workarounds

None I can think of.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This is all in the themed templates, so you can localize it however you like. Currently the button is built using the value defined in the IdP, but this is all under user control. 

For example, the default Facebook button uses this macro

```
[#macro facebookButton identityProvider clientId]
 <button id="facebook-login-button" class="facebook login-button" data-permissions="${identityProvider.lookupPermissions(clientId)!''}">
   <div>
     <div class="icon">
       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 216 216">
         <path class="cls-1" d="M204.1 0H11.9C5.3 0 0 5.3 0 11.9v192.2c0 6.6 5.3 11.9 11.9 11.9h103.5v-83.6H87.2V99.8h28.1v-24c0-27.9 17-43.1 41.9-43.1 11.9 0 22.2.9 25.2 1.3v29.2h-17.3c-13.5 0-16.2 6.4-16.2 15.9v20.8h32.3l-4.2 32.6h-28V216h55c6.6 0 11.9-5.3 11.9-11.9V11.9C216 5.3 210.7 0 204.1 0z"></path>
       </svg>
     </div>
     <div class="text">${identityProvider.lookupButtonText(clientId)?trim}</div>
   </div>
 </button>
[/#macro]
```

But you could replace `<div class="text">${identityProvider.lookupButtonText(clientId)?trim}</div>` with hard coded text, or use the theme message bundle to localize the button. 

For example:

```
<div class="text">${theme.message('facebook-login')}</div>
```

And then define `facebook-login=Login with Facebook` in your themed messages.

**Comment by mooreds** [comment]
Ah, then this can either be closed or would be a good thing to document.

**Comment by mooreds** [comment]
Closing, this is documented now.
