### ISSUE TITLE
Deleting a tenant async or sync may fail due to a FK violation. 

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1075]
### Description 
When deleting a tenant that contains users w/ tenants you may encounter a failure due to a FK violation. 

### Affects versions
1.22.0 and beyond

### Steps to reproduce
1. create a tenant
2. create users
3. Create an application in the new tenant
4. register users in the new tenant for the application
5. Delete the tenant

### Workaround
Delete all users in the tenant first, either manually or using the Bulk User Delete API. 

### Expected behavior
It works.

**Comment by TanguyGiton** [comment]
Hello,

I have two tenants stuck on "Deleting...". I have applied the workaround by deleting all users but the tenants remain blocked.

The UI does not allow me to restart the deletion. Should I do it from the API?

Best regards,

**Comment by robotdan** [comment]
Do you have the fix for this? It is in 1.23.3.

**Comment by TanguyGiton** [comment]
Yes, I'm on 1.25

**Comment by robotdan** [comment]
Have you tried trying to delete using the API?

**Comment by TanguyGiton** [comment]
Yes, I have this error :
{"statusCode":400,"exception":{"fieldErrors":{"tenantId":[{"code":"[pendingDelete]tenantId","message":"You
cannot delete the tenant, a delete request has already been submitted. The
tenant is currently in a pending delete state."}]}}}

Le jeu. 22 avr. 2021 à 20:41, Daniel DeGroff ***@***.***> a
écrit :

**Comment by TanguyGiton** [comment]
Yes, I have this error :
```
{
    "statusCode": 400,
    "exception": {
        "fieldErrors": {
            "tenantId": [
                {
                    "code": "[pendingDelete]tenantId",
                    "message": "You cannot delete the tenant, a delete request has already been submitted. The tenant is currently in a pending delete state."
                }
            ]
        }
    }
}
```

**Comment by robotdan** [comment]
Not sure how we got into this state, but if you have access to a SQL shell I can give you the SQL command to flip the status so you can run the delete again. 

Are you on PostgreSQL or MySQL?

**Comment by robotdan** [comment]
This should correct the state so you can attempt the delete again. 

```
UPDATE tenants
SET data = JSONB_SET(data::JSONB, '{state}', '"Active"') WHERE (data::JSONB ->> 'state') = 'PendingDelete';
```

**Comment by TanguyGiton** [comment]
It worked, thanks !
