### ISSUE TITLE
The requested identityProviderId is invalid. Unable to complete this login request.

### ISSUE THREAD

**Issue by IgorMotorny** [FusionAuth/fusionauth-issues#1078]
I set identityProviderId to "82339786-3dff-42a6-aac6-1f1ceecb6c46" as mentioned in docs https://fusionauth.io/docs/v1/tech/apis/identity-providers/google/

but response contains errors: 
{"generalErrors":[{"code":"[InvalidIdentityProviderId]","message":"The requested identityProviderId is invalid. Unable to complete this login request."}]}

**Comment by robotdan** [comment]
Please provide a lot more detail about the issue. 

- Version of FusionAuth
- API you are calling
- Workflow you are trying to complete
- Example API requests
-

**Comment by mooreds** [comment]
This looks like a great candidate for a forum post, which I see you created, @IgorMotorny .

Let's close this issue and discuss over on the forum until we've determined this is a bug. Please provide all the info @robotdan asks for over there: https://fusionauth.io/community/forum/topic/760/the-requested-identityproviderid-is-invalid-unable-to-complete-this-login-request
