### ISSUE TITLE
Import Certificate fails silently

### ISSUE THREAD

**Issue by trevorr** [FusionAuth/fusionauth-issues#1085]
### Description 
I'm trying to import an X509 certificate for use with SAML. I click Import Certificate in the Key Master, paste the base-64 encoded certificate, and click Submit. The dialog disappears but the rest of the screen stays dimmed and the UI is unusable.

In the browser console, I see these two messages:

```
POST https://<my-fusionauth-host>/ajax/key/import 500
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at AJAXDialog._initializeDialog (AJAXDialog.js:366)
```

On the server side, I see this error in the log:

```
org.primeframework.mvc.message.l10n.MissingMessageException: Message could not be found for the URI [/ajax/key/import] and key [[invalidLength]key.certificate]
at org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider.getMessage(ResourceBundleMessageProvider.java:79)
at io.fusionauth.app.service.FrontEndSupport.addFieldError(FrontEndSupport.java:154)
```

### Affects versions
1.23.1, 1.23.3

### Steps to reproduce
1. Go to Key Master
2. Click on Import Certificate
3. Paste certificate:
```
MIICXjCCAccCBE48G6YwDQYJKoZIhvcNAQEEBQAwdjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAklM
MRAwDgYDVQQHEwdDaGljYWdvMRswGQYDVQQKExJUaGUgVml0YWxpdHkgR3JvdXAxFDASBgNVBAsT
C0RldmVsb3BtZW50MRUwEwYDVQQDEwxJZ29yIFBvbGV2b3kwHhcNMTEwODA1MTYzNDQ2WhcNMjEw
ODAyMTYzNDQ2WjB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCSUwxEDAOBgNVBAcTB0NoaWNhZ28x
GzAZBgNVBAoTElRoZSBWaXRhbGl0eSBHcm91cDEUMBIGA1UECxMLRGV2ZWxvcG1lbnQxFTATBgNV
BAMTDElnb3IgUG9sZXZveTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAmAwL/PzX5n5nWaVY
r+TkD7Rm14oHoacimCPpufyjUvdN6qqckXsX/70nj6lFFw8ypH7g/12BkuYKxwZCZu3jac28MmE9
BOQFrajsl5G0TIEw7BQg+y40Juoz0hm0vP5WQokoagEIn5IZ3MMwWrC3+12Un7T3aRSxR/on1jD6
XCMCAwEAATANBgkqhkiG9w0BAQQFAAOBgQAK8J82zHo01ozlyubht70jNT8tpfq1hAZhxdUbVQPx
3iwho4Bha+CpMPsloYdCkiK7o2Mk7dGBgBu0UG+WktK6besJbT0cflCvi0eJkxteo4jhFvUsSNXA
7NT+l1VVDvBPHS+Bknoee0qHl8fbAI3cZoey7rkWyjOK3awnvRpRsQ==
```
4. Click Submit
5. Dialog closes but screen stays dimmed and UI is unusable

### Expected behavior
Valid key to be imported successfully, or at least an error describing the issue.

### Screenshots
N/A

### Platform
Chrome 87.0.4280.141 (Official Build) (x86_64) on MacOS
FusionAuth 1.23.3 Docker image running on amzn-ami-2018.03.20201209-amazon-ecs-optimized against MySQL 5.7.26

### Additional context
Certificate appears valid using https://www.sslshopper.com/certificate-decoder.html or `openssl x509`. Surrounding with `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` (which openssl wants) also fails in FusionAuth.

**Comment by robotdan** [comment]
Looks like we are missing a translated message for that error in the front end. The API will return this message:

```
The [key.certificate] property is a valid PEM encoded certificate but the contained public key length is not supported. The key length must be 2048, 3072 or 4096 for RSA and 256, 384 or 521 for Elliptic Curve.
```

That is a `1024` bit RSA key, which is not supported, the key has to be at least `2048`.

We can use this issue correct the front end error message.

**Comment by trevorr** [comment]
@robotdan Would it be possible to support importing 1024 bit RSA keys? I realize that goes against the guidance of NIST and others, but I'm not in control of this certificate. I've asked our partner to generate a longer key, but I'm not sure if they will, since this certificate has been distributed to all of their partners as part of a SAML configuration.

**Comment by robotdan** [comment]
Yea, this is an option. Can you open a separate issue for this request?

Our parser only supports the lengths that are allowed for JWT signing & verification. But there are probably others like you - that have have some legacy SAML config that is using an old key. I think as long as we only allow it to be used for verification purposes it should be ok to allow them to be imported.
