### ISSUE TITLE
Search API add option to retrieve actual hit count when result set exceeds the default 10k results

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1086]
### Description
Elasticsearch will default to 10k hits to limit performance impact when searching. This is ok in most cases, fine for paginating through users, etc. 

But if you are performing a very specific query where you want to know the hit count to know the users matching the query, we would allow the API to ask for this detail. 

In the raw ES query, you can pass in `track_total_hits` and this can be set equal `true` to request the actual hit count be returned, or set this to a number such as `10000` which is the default, or something larger. This tells ES to stop counting hits after reaching this number. 

The query also returns a `relation` field which indicates if the query could return more results than reported by the `total`. This is in the form of a string and equal to `eq` or `gte` indicating if the number of hits are greater than or equal (`gte`) the `total` returned, or `eq` to that of the actual hits. 

We could simply add this as a top level option on the API and then report back if the number of hits returned is the actual number (`relation = "eq"`)  or if more results exist (`relation = "gte"`). 

### Workaround
You can also just query Elasticsearch directly outside of FusionAuth to get this type of data. 

### Documentation
- [ ] New configuration option to modify the default Elasticsearch 10k cap
- [ ] New API parameter to request an accurate total on the Search API, equivalent to asking Elasticsearch for `track_total_hits = true`.

**Comment by mooreds** [comment]
Seems similar to https://github.com/FusionAuth/fusionauth-issues/issues/923

**Comment by robotdan** [comment]
Ah, yes, perhaps - I wasn't sure exactly what #923 was - are you just looking for a count of users? Was confused by the "entity" thing.

**Comment by mooreds** [comment]
Ah, maybe they overlap but aren't exactly the same. I want to be able to get a count of users, but also of groups, tenants, etc, without pulling back all the data (as you have to do now). Actually, looks like when you pull groups, you don't get a count currently.
