### ISSUE TITLE
Running a PUT on a user causes their group membership to get out of sync when using elasticsearch

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1087]
### Description 

A user's group memberships, as reported by searching with the queryString `memberships.groupId:...` can get out of sync if you use the `PUT` update method for the user. Using `PATCH` does not seem to cause the issue.

### Affects versions
1.22, 1.23.0, 1.23.3

### Steps to reproduce
Steps to reproduce the behavior. All of these are via the API

1. Create a user.
2. Add the user to a group
3. flush the search engine (has no effect)
4. retrieve the user (you can verify they are in the group)
5. Search for the user using a queryString of `memberships.groupId:...`
6. You get back the user
7. Update the user using a `PUT`. Note that there's no indication or ability to `PUT` group memberships.
8. Retrieve the user by uuid. You see they are still a member of the group. Yay!
9. Search for the user using a queryString of `memberships.groupId:...`. They will no longer be there. Boo!

### Expected behavior

Querying on group memberships should return correct data.

Perhaps the re-index operation doesn't pull the full user data when a PUT happens?

### Platform

FA running ES

### Additional context

Originally reported here: https://github.com/FusionAuth/fusionauth-java-client/issues/8

PATCHing the user doesn't cause the same issue.

**Comment by mooreds** [comment]
Here are a couple of scripts I found useful. Make sure to create a group via the UI before running these, and then change the email address each time.

If you run this, you'll see that the search results will increment when you run addusertogroupthenlookforgroup.sh, but if you run search.sh afterwards, you'll see the results go down by one.

 addusertogroupthenlookforgroup.sh

```
set -e

API_KEY="SNjNZj8jz4A_5BeL07pF901nwlLxRQ3CK6shpuIFQkg"
email='user36@testgroupadd.com'
group_id=9cb98993-02d6-4b31-90da-3ede834ffa9e

echo ""
echo ""
echo "creating user"
user_id=`curl -XPOST -H "Authorization: $API_KEY" -H "Content-Type: application/json" -d '{"user": {"email": "'$email'","password":"password"}}' http://localhost:9011/api/user |jq '.user.id'`

user_id=`echo $user_id|sed 's/"//g'`

echo ""
echo ""
echo "adding user to group"
curl -XPOST -H "Authorization: $API_KEY" -H "Content-Type: application/json" -d '{ "members": { "'$group_id'": [ { "userId": "'$user_id'" } ] } }' http://localhost:9011/api/group/member

echo ""
echo ""
echo "flush search engine"
curl -XPUT -H "Authorization: $API_KEY" http://localhost:9011/api/user/search

echo ""
echo ""
echo "getting user"
curl -XGET -H "Authorization: $API_KEY" http://localhost:9011/api/user/$user_id

echo ""
echo ""
echo "search should include user"
curl -XGET -H "Authorization: $API_KEY" 'http://localhost:9011/api/user/search?queryString=memberships.groupId:'$group_id

sleep 2

echo ""
echo ""
echo "search should include user"
curl -XGET -H "Authorization: $API_KEY" 'http://localhost:9011/api/user/search?queryString=memberships.groupId:'$group_id

#echo ""
#echo ""
#echo "updating with patch"
#curl -XPATCH -H "Authorization: $API_KEY" -H "Content-Type: application/json" -d '{"user": {"firstName": "dan"}}' http://localhost:9011/api/user/$user_id


echo ""
echo ""
echo "updating with put"
curl -XPUT -H "Authorization: $API_KEY" -H "Content-Type: application/json" -d '{"user": {"email":"'$email'", "firstName": "dan"}}' http://localhost:9011/api/user/$user_id


echo ""
echo ""
echo "does user have group"
echo "getting user"
curl -XGET -H "Authorization: $API_KEY" http://localhost:9011/api/user/$user_id

```

search.sh
```
set -e

API_KEY="SNjNZj8jz4A_5BeL07pF901nwlLxRQ3CK6shpuIFQkg"

group_id=9cb98993-02d6-4b31-90da-3ede834ffa9e

#echo ""
#echo ""
#echo "flush search engine"
#curl -XPUT -H "Authorization: $API_KEY" http://localhost:9011/api/user/search

echo "search should include user"
curl -XGET -H "Authorization: $API_KEY" 'http://localhost:9011/api/user/search?queryString=memberships.groupId:'$group_id

```

**Comment by robotdan** [comment]
Dup or similar to https://github.com/FusionAuth/fusionauth-issues/issues/932 ?

**Comment by mooreds** [comment]
Hmmm. Could be similar in that both are issues where elasticsearch is out of sync with the underlying database. But the operations that are changing the underlying database is entirely different (in one case it is removing a user from a group, in the other case it is updating a user using a PUT).

**Comment by robotdan** [comment]
The API doc may be out of sync, it looks as though you can add memberships during a user create, but not an update. But the API doc does not indicate this for create or update. 

So at a min, we should update the create user doc, I think we did it this way to be consistent with registrations.

**Comment by mooreds** [comment]
OK, will update the doco.

**Comment by robotdan** [comment]
Thanks, I think there is also a bug so I'll fix under this issue.
