### ISSUE TITLE
Support import of certificates with 1024 bit RSA keys

### ISSUE THREAD

**Issue by trevorr** [FusionAuth/fusionauth-issues#1091]
### Problem
As initially described in #1085, we were given a SAML certificate by a partner that uses a 1024 bit RSA key, which FusionAuth currently refuses to import. Though we've asked them to switch to a larger key, it might be a disruptive change for them, and we don't know yet whether they will.

### Solution
Allow certificates with 1024 bit RSA keys to be imported in the Key Master. It may make sense to limit this to certificates and public keys, which are only used for verification.

### Alternatives/workarounds
I don't think we have a workaround if the partner can't/won't increase the key size.

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Fixed in 1.24.0, thanks!
https://site-local.fusionauth.io/docs/v1/tech/release-notes/#version-1-24-0
