### ISSUE TITLE
validateJWT function doesn't work in node-client

### ISSUE THREAD

**Issue by kamal-20** [FusionAuth/fusionauth-issues#1095]
### Description 
<pre>
/**
   * Validates the provided JWT (encoded JWT string) to ensure the token is valid. A valid access token is properly
   * signed and not expired.
   * This API may be used to verify the JWT as well as decode the encoded JWT into human readable identity claims.
   *
   * @param {string} encodedJWT The encoded JWT (access token).
   * @return {Promise<ClientResponse<ValidateResponse>>} A Promise for the FusionAuth call.
   */
  validateJWT: function(encodedJWT) {
    return new Promise((resolve, reject) => {
      this._startAnonymous()
          .uri('/api/jwt/validate')
          .authorization('Bearer ' + encodedJWT)
          .get()
          .go(this._responseHandler(resolve, reject));
    });
  },

</pre>

### Expected behavior
As per API Authorization header should use JWT instead of Bearer 
same issue may be there in other functions causing error..

**Comment by voidmain** [comment]
We might want to move this over to the fusionauth-node-client or fusionauth-client-builder repository.

**Comment by mooreds** [comment]
Hmmm. I took a look a bit deeper and it does look like there is a bit of difference between the documentation (which states that the authorization header should look like:

```
Authorization: JWT ...
```

and the client library code, which creates this authorization header (see https://github.com/FusionAuth/fusionauth-ruby-client/blob/master/lib/fusionauth/fusionauth_client.rb#L3021 for example) :

```
Authorization: Bearer ...
```

However, testing against 1.23.3, I see both the `Bearer` and `JWT` prefixes work.

Anyhow, I'm going to fix the client library, which looks like it's just changing this api object: https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/api/validateJWT.json

**Comment by mooreds** [comment]
OK, decided that updating the documentation made more sense: https://github.com/FusionAuth/fusionauth-site/pull/410
