### ISSUE TITLE
No refresh token is provided when using the login API

### ISSUE THREAD

**Issue by Saracaen** [FusionAuth/fusionauth-issues#1097]
### Description
I have the application set up as seen in the screenshot, and the login API actually works, but it only returns an access token and the user profile, and no refresh token. I do provide the correct applicationId when calling the login API.

![Screenshot from 2021-02-03 13-12-00](https://user-images.githubusercontent.com/72379653/106745464-6cc90780-6621-11eb-8007-8e8f4799d68b.png)

**Comment by mooreds** [comment]
What version of FusionAuth are you using?

Are you connecting using curl or a client library? If the latter, which one?

**Comment by Saracaen** [comment]
I am using version 1.22.2 of FusionAuth, and use axios from a JavaScript web application to call the login API.

![Screenshot from 2021-02-03 13-52-23](https://user-images.githubusercontent.com/72379653/106749718-2d051e80-6627-11eb-90ee-d39a9dce3ab8.png)

**Comment by mooreds** [comment]
I'm unable to replicate with curl, tried on both 1.22.2 and 1.23.3. In both cases, I have the same application config and get a refresh token as part of the response.

Can you see if this curl script works on your installation? 

```
curl -XPOST -H 'Content-type: application/json' 'http://localhost:9011/api/login' -d '{"loginId": "user@example.com", "password": "password", "applicationId" : "e607ceab-7b28-4168-ba93-c007d7525862" }'
```

That will help narrow down the issue.

**Comment by Saracaen** [comment]
The curl script only returns an object with a token and a user property, no refresh token unfortunately. Could it be a configuration somewhere else? I would expect it to work if the "Generate Refresh Tokens" setting is checked in the "Login API Settings".

I am sure the applicationId is correct, because if I change that it will return an error stating that it is incorrect.

**Comment by Saracaen** [comment]
I figured it out, I forgot to add a registration for the correct application to the user. After adding it everything works as expected!

**Comment by mooreds** [comment]
Ah, awesome, thanks!

**Comment by Saracaen** [comment]
Might I suggest adding a warning or some type of additional information when the user attempts to login with an application id that he or she does not have a registration for? Or perhaps even an error?

**Comment by mooreds** [comment]
Thanks for the suggestion. 

The status code returned is different (202 vs 200). The issue is that a user can authenticate even if they aren't authorized for an application. We have some docs around that: https://fusionauth.io/docs/v1/tech/core-concepts/authentication-authorization/ but I'll try to make that clearer in the Login API docs. 

We could change the return codes, but that'd be a breaking change so we want to be very careful with that.
