### ISSUE TITLE
Spring(boot) Rest API integration with FusionAuth

### ISSUE THREAD

**Issue by swc-kdzekov** [FusionAuth/fusionauth-issues#1098]
Hello,

Couple of days ago I started to play with FusionAuth. Regarding oAuth authorization,  except for conceptual understanding I do not have practical experience. Following your example in this tutorial: https://fusionauth.io/blog/2018/10/24/easy-integration-of-fusionauth-and-spring/ I managed to successfully authenticate myself using local previously installed and configured FusionAuth server.

However, I'm struggling to use the same approach to authorize myself into one simple Rest API service written in java Spring-boot. Having configured service (my spring boot rest api service) for oAuth (the same way as in the tutorial), I'm getting "403 Forbidden" response when I run an API call. That is understandable when the client (in my case Postman) does not use authorization option.
The problem is that, even when I fire the Api call using generated token (using oAuth2 authentication option) from FusionAuth app, I get the same "403 Forbidden" response. The end-point that I'm trying to reach out does not have any authorization restriction(s). 
I have also attached the client calls. 

![token-config](https://user-images.githubusercontent.com/54243016/106939544-b0566b00-6720-11eb-9ac4-0b86d101cc54.jpg)

![token1](https://user-images.githubusercontent.com/54243016/106939593-bfd5b400-6720-11eb-97b8-1b54e4d2ee4c.jpg)

![response](https://user-images.githubusercontent.com/54243016/106939602-c3693b00-6720-11eb-9465-33f050e4af4d.jpg)

Could you give me a hint where could be the problem ?

**Comment by swc-kdzekov** [comment]
My FusionAuth application:

![fusionauth-app](https://user-images.githubusercontent.com/54243016/106940381-c6186000-6721-11eb-80fb-639f5cd9d17e.jpg)

**Comment by swc-kdzekov** [comment]
application.properties:

# API
fusionAuth.apiKey=
fusionAuth.applicationId=22590514-5c24-4e5d-bb71-5214357da95c
fusionAuth.baseUrl=http://localhost:9011

# OpenID
fusionAuth.clientId=22590514-5c24-4e5d-bb71-5214357da95c
fusionAuth.clientSecret=AKfjOwwtKhpOx3Ae4ws9S8y1Xeh2cP_LNcPWDIoF-Rk
fusionAuth.accessTokenUri=http://localhost:9011/oauth2/token
fusionAuth.logoutUri=http://localhost:9011/oauth2/logout
fusionAuth.userAuthorizationUri=http://localhost:9011/oauth2/authorize
fusionAuth.userInfoUri=http://localhost:9011/oauth2/userinfo
fusionAuth.redirectUri=http://localhost:8090/login

**Comment by swc-kdzekov** [comment]
The rest of the configurations are the same as in the tutorial: https://fusionauth.io/blog/2018/10/24/easy-integration-of-fusionauth-and-spring/

**Comment by mooreds** [comment]
@swc-kdzekov thanks for trying out FusionAuth! 

The best place for support questions like this is the community forums. (Unless you are on a paid edition which includes support, in which case you should open a ticket from https://account.fusionauth.io/account/support/ ). 

Please post your question in the forum: https://fusionauth.io/community/forum/ 

I'm going to close this issue since the forum is the right place.
