### ISSUE TITLE
[docs] Clarify how to deactivate user.active in REST APIs POST /api/user, PUT /api/user/{userId} and PATCH /api/user/{userId}

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#1099]
### Description 
user.active field is mentioned several times in REST API of Users, including in bulk import, but not during Create and Update/Patch.

https://fusionauth.io/docs/v1/tech/apis/users/#update-a-user

### Affects versions

1.23.1

### Steps to reproduce
Documentation issue in https://fusionauth.io/docs/v1/tech/apis/users/#update-a-user

### Expected behavior

If `user.active` field is supported during Create and Update/Patch, please put it in fields list.

However if it is not supported, make a note referencing how to deactivate a user immediately during Create, or during Update.
I think it should be supported as Bulk Import supports it.

**Comment by mooreds** [comment]
Thanks for the feedback. I agree the docs could be clearer.

You can use the `delete user` operation with `hardDelete=false` (which is the default) https://fusionauth.io/docs/v1/tech/apis/users/#delete-a-user to set the `active` attribute to `false` for a user.

**Comment by mooreds** [comment]
Closed in https://github.com/FusionAuth/fusionauth-site/pull/424
