### ISSUE TITLE
mysql 5.6 issue with mysqlconnector jar 8.0.21

### ISSUE THREAD

**Issue by Thangamh** [FusionAuth/fusionauth-issues#1108]
### Description
I'm getting this error while installing fusionauth and this is coming from the docker

Installation: docker
Search: elasticsearch cluster
db: mysql 5.6

SEVERE [Catalina-startStop-1] org.apache.catalina.core.ContainerBase.startInternal A child container failed during start
	java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@5f97c773]

Need help

**Comment by robotdan** [comment]
MySQL 5.6 is not supported. 
https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements/#database
