### ISSUE TITLE
Logout endpoint fails if id_token passed in id_token_hint uses aud parameter other than string

### ISSUE THREAD

**Issue by pigletto** [FusionAuth/fusionauth-issues#1114]
### Description 
I have an **Id Token populate lambda** defined for application. It modifies the **aud** so that it is a list, not string. Something similar to _jwt.aud = [ 'foo', 'bar' ];_ suggested there on the forums: https://fusionauth.io/community/forum/topic/52/can-we-set-multiple-aud-claims-in-fusionauth?_=1613568860079

When I call logout endpoint with **id_token_hint** filled with **id_token** generated using the lambda above I get error 500 from FusionAuth. It doesn't happen when I disable the lambda. The error message (full traceback below) from FA saying that **class java.util.ArrayList cannot be cast to class java.lang.String** clearly indicates that using the list with the **aud** parameter is the issue.

Full traceback is:

`fusionauth_1            | 2021-02-17 1:27:27.699 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
fusionauth_1            | java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
fusionauth_1            |       at io.fusionauth.jwt.domain.JWT.getString(JWT.java:368)
fusionauth_1            |       at io.fusionauth.api.service.oauth2.DefaultOAuthService.validateAndResolveApplication(DefaultOAuthService.java:1129)
fusionauth_1            |       at io.fusionauth.api.service.oauth2.DefaultOAuthService.validateLogoutRequest(DefaultOAuthService.java:658)
fusionauth_1            |       at io.fusionauth.app.action.oauth2.LogoutAction.validateGet(LogoutAction.java:100)
fusionauth_1            |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
fusionauth_1            |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
fusionauth_1            |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
fusionauth_1            |       at java.base/java.lang.reflect.Method.invoke(Method.java:564)
fusionauth_1            |       at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
fusionauth_1            |       at org.primeframework.mvc.validation.DefaultValidationProcessor.validate(DefaultValidationProcessor.java:77)
fusionauth_1            |       at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:46)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:183)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:240)
fusionauth_1            |       at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)
fusionauth_1            |       at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1            |       at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
fusionauth_1            |       at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
fusionauth_1            |       at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
fusionauth_1            |       at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
fusionauth_1            |       at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
fusionauth_1            |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1            |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1            |       at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
fusionauth_1            |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1            |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1            |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
fusionauth_1            |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
fusionauth_1            |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
fusionauth_1            |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
fusionauth_1            |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
fusionauth_1            |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
fusionauth_1            |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
fusionauth_1            |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
fusionauth_1            |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
fusionauth_1            |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
fusionauth_1            |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
fusionauth_1            |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
fusionauth_1            |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
fusionauth_1            |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
fusionauth_1            |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
fusionauth_1            |       at java.base/java.lang.Thread.run(Thread.java:832)`

### Affects versions
1.24.0

### Steps to reproduce
1. Create Lambda that does the following: jwt.aud = [ 'foo', 'bar' ];
2. Assign the lambda to the application as an "Id Token populate lambda"
3. Log in to the application with **openid** scope (to get id_token) and try to log out using **id_token_hint** with logout endpoint

### Expected behavior
The user should be logged out

### Platform
 - Device: Desktop
 - OS: Linux
 - Browser + version: Chrome
 - Database PostgresSQL + Elasticsearch

**Comment by robotdan** [comment]
It is true, you can modify the `aud` claim if you wish. However, once you modify this claim, I don't know that you can expect it to work with FusionAuth directly. 

We use the `aud` claim in this endpoint to decide what you are trying to log out of. So, at a minimum, this claim has to be an `applicationId` (`client_id`). 

So, in your case, if you modify the `aud` claim, are you setting it to multiple FusionAuth Application Ids, or something else specific to your environment?

**Comment by pigletto** [comment]
I'm setting this to multiple FusionAuth Application Ids. My code is:

```
function populate(jwt, user, registration) {
  var audience = ['' + jwt.aud];
  for (var key in user.registrations){
    if (user.registrations.hasOwnProperty(key)) {
        var user_registration = user.registrations[key];
        if (audience.indexOf('' + user_registration.applicationId) == -1){
          audience.push('' + user_registration.applicationId);
        }
    }
  }
  jwt.aud = audience;
}
```

**Comment by robotdan** [comment]
Ok, thanks for that detail, we'll have to take a look at this one and see if we can support this scenario.

**Comment by robotdan** [comment]
This should work as of version `1.36.6`. Fixed via:
-  https://github.com/FusionAuth/fusionauth-issues/issues/1759
