### ISSUE TITLE
Email: Wrong TXT charset

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1122]
### Description 

The TXT version of the email is sent with charset `ANSI_X3.4-1968` causing issue on french special characters:

```
Content-Type: text/plain; charset=ANSI_X3.4-1968
Content-Transfer-Encoding: 7bit

Bonjour,

Vous faites maintenant partie des utilisateurs de Company : nous vous remercions

chaleureusement pour votre confiance et sommes tr?s heureux de vous compter parmi nos clients.

Votre compte Company test@example.com a ?t? cr?? par nos soins.

Pour finaliser son activation cliquez ici :

https://link

Besoin d?aide ?
Retrouvez toute notre doc par ici : https://docs.company.com/

Vous avez des questions ? N?h?sitez pas ? nous envoyer un mail ? support@company.com

? tr?s vite,

L??quipe Company
````

Should be UTF-8 like for the html part:

```
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
```

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Steps to reproduce
1. Send an e-mail containing special french characters (e.g. `é`).

### Expected behavior

The TXT version should be UTF-8 encoded.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

**Comment by mooreds** [comment]
@soullivaneuh 

What version of FusionAuth are you seeing this behavior in?

Is the charset the empty string? I was unclear what you meant here:

> The TXT version of the email is sent with charset `` causing issue on french special characters:

Thanks!

**Comment by soullivaneuh** [comment]
> What version of FusionAuth are you seeing this behavior in?

I am using v1.22.0.

> Is the charset the empty string?

No, the empty string is caused by a chair/keyboard interface issue. :upside_down_face: 
I updated the thread accordingly.

**Comment by robotdan** [comment]
It looks like we may not be setting the `Content-Type` for the text MIME type. It works ok in tests, so I'm assume because we don't set it manually it picks up some default encoding type from the VM or host OS.

**Comment by soullivaneuh** [comment]
> so I'm assume because we don't set it manually it picks up some default encoding type from the VM or host OS.

It is maybe a way for a workaround waiting the fix. May you elaborate this part?

**Comment by mooreds** [comment]
You could try setting the encoding for your VM to see if the correct value is picked up. Not sure which OS you are using, but I'd google around to see how to set that.

The fix appears to  be pretty easy, it is changing the Prime framework, which is open source, and doing a new release of FusionAuth (which happens about every month or so).

On this line: https://github.com/prime-framework/prime-email/blob/master/src/main/java/org/primeframework/email/service/JavaMailEmailTransportService.java#L171

Change 
```
textPart.setText(text);
```

to 

```
textPart.setText(text, "UTF-8");
```

But of course tests need to be written too. Not sure which is the right place for this, but it should be in this package: https://github.com/prime-framework/prime-email/tree/master/src/test/java/org/primeframework/email/service

That is open source and we do accept PRs :) .

**Comment by soullivaneuh** [comment]
> Not sure which OS you are using, but I'd google around to see how to set that.

I'll check that, but for your information, we use a Docker image base from the official one:

```Dockerfile
FROM fusionauth/fusionauth-app:${VERSION} as app
WORKDIR /usr/local/fusionauth
COPY --from=plugins /plugins/symfony-salted-sha512/target/fusionauth-symfony-salted-sha512-password-encryptor-0.0.0.jar plugins/
WORKDIR /usr/local/fusionauth/fusionauth-app
COPY --from=style /build/build.css web/css/theme.css
COPY images/* web/images/
```

**Comment by mooreds** [comment]
Ah, this looks helpful then: https://stackoverflow.com/questions/28405902/how-to-set-the-locale-inside-a-debian-ubuntu-docker-container (untested, from a google search).

**Comment by robotdan** [comment]
If that works, perhaps we should be setting that in our own image to keep the host OS from affecting things such as this.

**Comment by soullivaneuh** [comment]
Thanks a lot @mooreds, it works like charm with the following hack:

```Dockerfile
--- a/Dockerfile
+++ b/Dockerfile
@@ -26,6 +26,19 @@ RUN awk -F= '!a[$1]++' locales-overrides/messages.properties fusionauth-localiza
 RUN awk -F= '!a[$1]++' locales-overrides/messages_fr.properties fusionauth-localization-${VERSION}/theme/messages_fr.properties > locales/messages_fr.properties
 
 FROM fusionauth/fusionauth-app:${VERSION} as app
+# @see https://github.com/FusionAuth/fusionauth-issues/issues/1122
+# @see https://stackoverflow.com/a/28406007/1731473
+USER root
+RUN apt-get clean \
+  && apt-get update \
+  && apt-get install --yes locales \
+  && rm --recursive --force /var/lib/apt/lists/*
+ENV LANG en_US.UTF-8
+ENV LANGUAGE en_US:en
+ENV LC_ALL en_US.UTF-8
+RUN locale-gen en_US.UTF-8
+USER fusionauth
+
 WORKDIR /usr/local/fusionauth
 COPY --from=plugins /plugins/symfony-salted-sha512/target/fusionauth-symfony-salted-sha512-password-encryptor-0.0.0.jar plugins/
 WORKDIR /usr/local/fusionauth/fusionauth-app
```

> If that works, perhaps we should be setting that in our own image to keep the host OS from affecting things such as this.

Make sense as the HTML version is set to UTF-8 too and this charset cover much more languages. :+1:

**Comment by robotdan** [comment]
Great! Thanks for confirming @soullivaneuh . 

Internal note:
- Do we want to export the `LANG`, `LANGUAGE` and `LC_ALL` environment variables in our Docker image, what would be the risk?
- Need to fix the email library to ask for UTF-8 for text.

**Comment by robotdan** [comment]
I think I've got the locale issue fixed or the text MIME type. 
https://github.com/prime-framework/prime-email/commit/546aacf7db2d0dafd185644a174909fd7a11b215

This will got out in the next version of FusionAuth.
