### ISSUE TITLE
Add webhooks for when user is known to be created

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1128]
### Problem

Lots of times we'll want to modify a user just after they've been created because we want to add data to their profile.

Currently you can listen for `user.create`, however if you require this event to succeed based upon your transaction configuration, the user won't be committed in FusionAuth until your web hook responds. This means that if you want to ask FusionAuth for this user in an API call or update the user in an API call within your web hook it will not work as this new object will not yet be available to the API. 

Even if you configure your TX such that the web hook does not need to succeed, the event will still be fired during the create and the transaction may not yet be committed during your web hook runtime. 
 
 
### Solution

Fire a webhook when we absolutely are positive a user has been created, and that any API calls against this user will succeed.

In addition to the `user.create`, we could add another event for `post.user.create` or something like that - such that you can decide if you want to be called during the event so that you can optionally fail the request, or if you just want to know when the "thing" has occurred and is now available for you to process. 

This may apply for `user.update` as well. 

### Alternatives/workarounds

Some documented here: https://github.com/FusionAuth/fusionauth-site/pull/462 but none solve the problem.

### Additional context

https://github.com/FusionAuth/fusionauth-issues/issues/1129

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
How about these events (past tense) - so these would be sent after the `user.create` (and so on). These "post" events could not be transactional because the event will have already occurred. 

- `user.created`
- `user.deleted`
- `user.updated`
- `user.registration.created`
- `user.registration.deleted`
- `user.registration.updated`

**Comment by mooreds** [comment]
Hmmm. I get wanting to be consistent, but how about `user.postCreate` or even namespace them: `post.user.create`, `post.user.delete`.

My main concern with what you suggested is the difference between `user.create` and `user.created` is smaller than I'd like.

**Comment by voidmain** [comment]
If there are any sorting concerns, then `user.create.post` would sort best. Or `user.create.complete`. Or `user.create.committed`.

**Comment by robotdan** [comment]
The current design is `user.create.complete`.

**Comment by mooreds** [comment]
`user.create.complete` WFM.

**Comment by glen-84** [comment]
@mooreds Should this issue be closed? `user.create.complete` now exists.

**Comment by mooreds** [comment]
@glen-84 you are correct. I updated our [release notes](https://github.com/FusionAuth/fusionauth-site/pull/1316) and will close this out. 

Thanks!
