### ISSUE TITLE
aghem is in the preferredLanguages list but can't be saved

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1132]
### Description 

I can't add aghem to the preferredLanguages for a user

### Affects versions

1.24.0

### Steps to reproduce

1. Go to the user edit screen in the admin UI
1. Add aghem (either plain or with cameroon) to the preferredLanguages for a user
1. Save the user

Whoops, you can't!

### Expected behavior

If it is in the list, you can save a user with that language.

### Screenshots
<img width="1694" alt="Screen Shot 2021-03-03 at 10 09 44 AM" src="https://user-images.githubusercontent.com/91825/109843720-9d906280-7c08-11eb-84aa-5e1fa20092a1.png">

### Platform

See this on FF and Safari on the mac.

### Possible Related
- https://github.com/FusionAuth/fusionauth-issues/issues/978

**Comment by robfusion** [comment]
Should be fixed with recent Locale changes

**Comment by robotdan** [comment]
@robfusion do we have a test for `aghem` or is it just implicitly covered since we are now testing against all locales returned by the JDK?

**Comment by robfusion** [comment]
Yeah, it's covered by the test of all available locales
