### ISSUE TITLE
Search API changes in 1.24.0 not compatible with Elasticsearch v6

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1135]
### Description 
A change was made in version 1.24.0 to allow the Search API to request the total hit count from Elasticsearch. This change was made under https://github.com/FusionAuth/fusionauth-issues/issues/1086.

This change is not compatible with Elasticsearch version 6. If you are using ES v6 and encounter this issue, add this to your API request: `"accurateTotal" : true`. 

### Affects versions
1.24.0

### Expected behavior
It should work with ES v6.

**Comment by pendenga** [comment]
Aside from Search API usage in our apps, this is also affecting the search page on the FusionAuth admin console. It's understandably related. I just wanted to mention it. 

![Screen Shot 2021-03-04 at 4 18 20 PM](https://user-images.githubusercontent.com/29118/110044031-b0d52800-7d05-11eb-8283-4ef81ce1cc69.png)
