### ISSUE TITLE
Search Users by Tenant

### ISSUE THREAD

**Issue by MMJM** [FusionAuth/fusionauth-issues#1138]
Search Users by Tenant

### Problem
I'm frustrated when I need to find a list of users that belong to a Tenant. The users page seems to only allow searching users by email, name or role

### Solution
I don't think a UI change is needed just the ability to enter a string and have it include Tenant in the filtering.

### Additional context
We will have a large number of tenants and need to see lists of user quickly and action some of those users.

**Comment by robotdan** [comment]
Try clicking on the `Advanced` section on the User Search page and see you find what you're looking for. Or search like this `tenantId:9d92ca33-bc7b-4d13-acd7-f7dc06038396` where `9d92ca33-bc7b-4d13-acd7-f7dc06038396` is your `tenantId`.

**Comment by mooreds** [comment]
This seems like a support question, which is best suited for the forum, or, if you have a support plan, [filing a ticket](https://account.fusionauth.io/account/support/).

I've moved it to the forum; let's continue the discussion there, please: https://fusionauth.io/community/forum/topic/849/can-i-find-all-users-by-tenant 

Closing.
