### ISSUE TITLE
Unauthorized after maintenance mode wizard

### ISSUE THREAD

**Issue by plunkettscott** [FusionAuth/fusionauth-issues#114]
### Description
I've went through the maintenance mode wizard and any setting change I try to do using my administrative user results in an "Unauthorized" error message. What is there that I need to do? I had to use the SQL file from the downloads page to set this up since I do not have a user available to me with superuser permissions on PostgreSQL.

**Comment by robotdan** [comment]
Are you behind a proxy in K8s or something like that? If so, this is likely due to your proxy config. 

Sounds like the same cause as this issue. https://github.com/FusionAuth/fusionauth-issues/issues/112. See this comment https://github.com/FusionAuth/fusionauth-issues/issues/112#issuecomment-481724601

If the `X-Forwarded-` headers are not added, then you'll hit our CSRF validation and fail which is causing the Unauthorized message.

**Comment by plunkettscott** [comment]
Thanks for that, @robotdan. Does Fusion support Proxy Protocol? Because Proxy Protocol is enabled on our load balancer. I was also able to get it to show the client IP on the user logon attempts within the admin area. However, it shows both the IP of the load balancer and the client IP. This still resulted in unauthorized errors, unfortunately.

**Comment by robotdan** [comment]
Yes, FusionAuth will work behind a proxy. 

What type of load balancer are you using? Many configuration require that specific configuration be added to provide the correct headers. Perhaps I can help you find the correct configuration. 

Generally you'll want to ensure the following three headers are added:

- `X-Forwarded-Proto` 
- `X-Forwarded-Host`  
- `X-Forwarded-Port`

**Comment by plunkettscott** [comment]
Thanks for the reply @robotdan.

I'm behind DigitalOcean's Load Balancer and then running through Istio's ingressgateway in Kubernetes. I've looked at the linked comment, and it got me a step further I think. However, one thing I am seeing is that when I append the headers I get XSS errors in Chrome when doing a POST request and on the login the redirect_uri is invalid. 

```
{
  "error" : "invalid_request",
  "error_description" : "The request is missing a required parameter: redirect_uri",
  "error_reason" : "missing_redirect_uri"
}
```
The redirect_uri is provided, though it looks to have the URL generated incorrectly.

http%2Chttps%3A%2F%2Fmy-domain.io........

Noteice the http and https both being appended.

**Comment by colundrum** [comment]
> Generally you'll want to ensure the following three headers are added:
> 
> * `X-Forwarded-Proto`
> * `X-Forwarded-Host`
> * `X-Forwarded-Port`
> 
> In this comment, there is an example istio config, see `appendHeaders`. [#92 (comment)](https://github.com/FusionAuth/fusionauth-issues/issues/92#issuecomment-476667055)

Hello,

I confirm that I was with the same issue with nginx and finally, solved with the help from @robotdan 's post.

This is my nginx config :

```
server {
        client_max_body_size 8M;
        proxy_buffering off;

   location / {
        proxy_pass http://127.0.0.1:9011;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
```

Thank you @robotdan for your post, you saved my day.

Regards

**Comment by robotdan** [comment]
You're welcome. Thank you for sharing your configuration for others to see!

**Comment by plunkettscott** [comment]
Closing as original issue is resolved. Will post Istio-based configuration in the `fusionauth-containers` repo soon.
