### ISSUE TITLE
Data set on user.data with custom theme not stored on user

### ISSUE THREAD

**Issue by DaviddH** [FusionAuth/fusionauth-issues#1140]
### Description
When adding a extra field for data, we expect that when we set the name to something like 'user.data.propertyName', the data set is stored on the user profile.

Example:

Following html added to default register page:

```html
[@helpers.input id="user.data.test" type="text" name="user.data.test" required=false autofocus=false placeholder="test" /]
```

Visible on the page:
![image](https://user-images.githubusercontent.com/1622972/110171118-849bd300-7dfb-11eb-8e14-589431186b63.png)

Part of the POST body:
![image](https://user-images.githubusercontent.com/1622972/110171210-b319ae00-7dfb-11eb-8a92-43a85d36d685.png)

But nothing on the user data tab of the registered user:
![image](https://user-images.githubusercontent.com/1622972/110171259-c6c51480-7dfb-11eb-9fd9-cd95bd442649.png)

Are we doing something wrong here, or is this not supported?

FusionAuth version: 1.24

**Comment by mooreds** [comment]
Hi David,

If you are using the community edition of FusionAuth, storing arbitrary data on the user via the hosted login pages is not supported. You can store anything you want in the standard fields defined by the basic self registration.

Options:

* buy a [licensed edition](https://fusionauth.io/pricing/editions/) and use [advanced registration forms](https://fusionauth.io/features/advanced-registration-forms/).
* write your own registration forms and use the [registration](https://fusionauth.io/docs/v1/tech/apis/registrations/) and [user](https://fusionauth.io/docs/v1/tech/apis/users/) APIs. 

Hope that helps.

**Comment by DaviddH** [comment]
Hello,

Thanks for the quick response.

If we would buy a license, would it start work when using the HTML themes? By defining custom form fields and then manually setting them in the html? We actually assumed this would work already based on the macros we saw in the html related to custom fields.

My report is a simplified version of our issue but we are actually using javascript in the theme to show you a set of extra fields based on a dropdown choice, so far I can see this isn't supported using the advanced registration forms.

**Comment by mooreds** [comment]
I'm not quite sure I understand your question. Are you asking "if I buy a license, will the code above work once I enter the license, or is there more that would have to be done?"

Or are you asking: "Can I show/hide a value based on a dropdown with advanced registration forms?"

**Comment by DaviddH** [comment]
Actually both :), since i am sure we are propably going to hit a use case in the future that advanced registration forms doesnt support

**Comment by mooreds** [comment]
Fair enough!

> "if I buy a license, will the code above work once I enter the license, or is there more that would have to be done?"

Nope, you'd need to set up some forms and form fields and assign the forms to the application as a registration form (so all stuff that would need to happen in the admin UI or via the form/form field API). For as how it would mesh with your current custom theme, you'd need to test that out and make sure that the elements in the default theme were ported over to your custom theme.

There's a [guide for setting up the backend components](https://fusionauth.io/docs/v1/tech/guides/advanced-registration-forms/). 

>  "Can I show/hide a value based on a dropdown with advanced registration forms?"

This is not built into the advanced registration forms, though that would be a cool feature. However, if you made the form field optional, I see no reason why you couldn't hide it or show it during registration using client side javascript.

HTH
