### ISSUE TITLE
user.data or registration.data not updated with SAML integration

### ISSUE THREAD

**Issue by drano** [FusionAuth/fusionauth-issues#1141]
I try to get extra information from saml response. But, these data are not stored on user and not on registration.

My code:
```
function reconcile(user, registration, samlResponse) {

  // .... as default reconcile method
  
 user.data = user.data || {};
 user.data.groups = defaultIfNull(samlResponse, 'http://schemas.microsoft.com/ws/2008/06/identity/claims/groups', 'groups') || [];  
  
 registration.data = registration.data || {};  
 registration.data.groups = defaultIfNull(samlResponse, 'http://schemas.microsoft.com/ws/2008/06/identity/claims/groups', 'groups') || [];
}
```
I cannot see data when I am using /api/user api.

**Comment by mooreds** [comment]
This seems like a support question, which is best suited for the forum, or, if you have a support plan, [filing a ticket](https://account.fusionauth.io/account/support/).

It looks like you opened a related issue in the forum; let's continue the conversation there. 

Closing.
