### ISSUE TITLE
return 405 when run client.exchangeOAuthCodeForAccessTokenUsingPKCE

### ISSUE THREAD

**Issue by yamatsum** [FusionAuth/fusionauth-issues#1146]
### Description 
I did the following tutorials using fastify.
https://fusionauth.io/docs/v1/tech/5-minute-setup-guide/

The login itself is working fine, but when I run `client.exchangeOAuthCodeForAccessTokenUsingPKCE` I get a 405 error.

There is no problem if it is executed by express as in the sample, but it fails when using fastify. Is there a sample of fastify?

log
```
2021-03-18 4:26:15.120 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.oauth2.TokenAction] does not have a valid execute method for the HTTP method [GET]
```

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version chrome

**Comment by robotdan** [comment]
@yamatsum were you able to resolve this issue? If there is anything you can share from your resolution that may help someone else, please feel free to add an additional comment to this thread.

**Comment by yamatsum** [comment]
This was a problem on the fastify side!
thx!
