### ISSUE TITLE
Regular (non-admin) user's dashboard (list of available applications)

### ISSUE THREAD

**Issue by bostjan** [FusionAuth/fusionauth-issues#1153]
# Regular user's dashboard

### Problem
Maybe I am missing something obvious here, but FusionAuth does not seem to contain a regular user's dashboard, listing all applications the user has access to. That's generally really useful, as going to IdP + clicking on the app is usually faster (and streamlined) compared to going to each individual application's url first, then finding the "Login with SSO" option and working through an interface unique to each app.

### Solution
A simple dashboard listing available applications to the user. Potentially add those for which the user can self-register too. This feature may need the ability to add images when creating new applications, to make the dashboard look good (make apps simple to find). Bonus if the users can rearrange their dashboard however they want.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@bostjan you aren't missing anything, this functionality is currently on the roadmap and being tracked under https://github.com/FusionAuth/fusionauth-issues/issues/566 

It is expected to ship shortly. Note that it will be a premium feature requiring a [paid edition](https://fusionauth.io/pricing/editions/). Here's more guidance on our roadmap: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap/

Another option would be to build your own using the APIs. 

Does this address your question? 

If so, please let me know if I can close this issue.

**Comment by bostjan** [comment]
Oh, awesome. Thanks for sharing!

(Sorry for the duplication of the content, but I really could not find #566. I didn't search for "IdP initiated SSO", though, not sure why.)
