### ISSUE TITLE
Add IP address to login type events where applicable

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1162]
### Description
Verify that we are adding the IP address to any relevant login events such as Success and Failure. 

### Documentation
- [x] Add the IP address
- [x] Update Fail and Success login event to document this field

**Comment by noe-charmet** [comment]
There are two related things that lack for us in the events and that would allow us to migrate more easily.
- User-Agent
- Custom user parameters (we use it like `/oauth2/authorize?myParam=value`

These are both used for security features, and that we currently are getting from our current authentication provider.

**Comment by mooreds** [comment]
The IP address functionality was merged today, will be released this week: https://github.com/FusionAuth/fusionauth-site/pull/572

**Comment by mooreds** [comment]
@noe-charmet thanks for the feedback, that's very valuable! It seemed distinct from this issue, so I opened a new one.

https://github.com/FusionAuth/fusionauth-issues/issues/1170
