### ISSUE TITLE
Inactive applications show up in the registrations object for a user when authenticating

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1163]
### Description

This was surprising behavior for me. I would expect since an inactive application can't be authenticated against, it wouldn't show up in the user's registrations array. But it does (at least for a login API call).

Options:

* leave things be
* add documentation to make it clear that the registrations made available when you retrieve a user include registrations for inactive applications
* only return active applications in the registrations object

**Comment by robotdan** [comment]
This is working as designed, but perhaps needs to be revisited. The UI currently shows you all registration even for those that are for inactive applications. If the API doesn't return them, then we can't show them in UI either.

**Comment by mooreds** [comment]
In that case I think this is ok with a documentation tweak. I'd wait to hear from a real user before doing anything more drastic.

**Comment by mooreds** [comment]
Updated site, will be released today.
