### ISSUE TITLE
Create status endpoints for kubernetes

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1166]
### Problem

Kubernetes needs different endpoints to manage FusionAuth correctly.

* liveness: is the application running
* readiness: is the application ready for traffic
* startup: is the application started (the other two don't get called if this returns false)

### Solution

Add endpoints for these three application states. Make sure they are correct and return quickly. No other funny business.

### Alternatives/workarounds

Use `/api/status`: https://fusionauth.io/docs/v1/tech/apis/system/#retrieve-system-status  

However, this is a little heavyweight.

### Additional context

Part of the ongoing kubernetes work.

Additional info about the endpoints: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Planning to add a new endpoint that is more purpose built for a k8s health check. `/api/health`. 

This endpoint will not return a JSON body, and will only ever return `200` or `500`. 

It seems this one endpoint can account for all three states outlined above. 

- `startup` - FusionAuth APIs will not respond until the application is running. If any API returns, app is started.
- `liveness` - return `200`
- `readiness` - return `200`

So this means that this won't be that much different from `/api/status` except that it will never return a `JSON` response, and the return codes are simplified to only have two states, and fewer health checks will run, so it should cost less to make this API call.
