### ISSUE TITLE
OpenidConnect - Uncaught TypeError: Cannot read property 'getValue' of null

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#117]
Adding a Openid-connect triggers JS error.

I was trying to add paypal as openidprovider.
i used : https://www.paypalobjects.com/.well-known/openid-configuration for discovery.

When i want to login, and hit the 'login with Openid Connect' button, a javascript error occurs.
<pre>
Uncaught TypeError: Cannot read property 'getValue' of null
    at FusionAuth.IdentityProvider.OpenIdConnect._handleLoginClick (OpenIdConnect.js?version=1.5.0:48)
    at e.value (PrimeElement.js:1784)
    at e.value (PrimeElement.js:1750)
</pre>

**Comment by robotdan** [comment]
Thanks for letting us know. You're hit a known issue. This is fixed in the upcoming release. 

There is a work-around listed in the 1.6.0 release notes. https://fusionauth.io/docs/v1/tech/release-notes/

> Fixed Open ID Connect federated login. Our JavaScript code was throwing an exception due to the removal of ...

Let me know if you need more detailed instructions and I can give you a hand.

**Comment by botnyx** [comment]
Excuse me for not looking thouroughly enough in the known issues.

**Comment by robotdan** [comment]
No problem @botnyx , respond on this thread if the details in the releases notes don't get you going. 
Thanks!

**Comment by The-Funk** [comment]
FYI:

Just ran into this with 1.47.1, should have read the release notes. Thanks @robotdan
