### ISSUE TITLE
error creating user and registration in combined step

### ISSUE THREAD

**Issue by sw34** [FusionAuth/fusionauth-issues#1172]
### Description 
I am following the API docs to create a new User and register to an application in one step https://fusionauth.io/docs/v1/tech/apis/registrations/#create-a-user-and-registration-combined but getting an error that I am missing a userId

### Affects versions
1.25.0

### Steps to reproduce
1. submit following using postman (note not supplying userId in URL)
```
POST /api/user/registration
{
    "registration": {
        "applicationId": "d2fcd335-9df5-4eb2-b7aa-3a90a1c20694",
        "timezone": "America/New_York",
        "username": "username"
    },
    "sendSetPasswordEmail": false,
    "skipVerification": true,
    "user": {
        "email": "username@emailaddress.com",
        "timezone": "America/New_York",
        "twoFactorEnabled": false,
        "username": "username",
        "password": "randomPassword"
    }
}
```
2. receive following
```
{
    "fieldErrors": {
        "userId": [
            {
                "code": "[couldNotConvert]userId",
                "message": "Invalid userId on the URL [registration\n]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."
            }
        ]
    }
}
```

### Expected behavior
I would expect a user to be created and registered to the application.  The documentation shows that userId is optional

```
Request Parameters
userId [UUID] OPTIONAL
The Id to use for the new User. If you don’t specify this, FusionAuth will generate a random UUID.
```

### Screenshots
none

### Platform
 - Device: Desktop
 - OS: Windows 10
 - Browser Postman v8.1.0
 - Database PostgresSQL 13

**Comment by voidmain** [comment]
It looks like you have a newline character on your URL. If you see in the error message, it is saying:

```
Invalid userId on the URL [registration\n]
```

Notice the `\n` on the end. That is causing FusionAuth to try and convert the string `registration\n` to a user id for the `/api/user` API instead. Once you remove the `\n` it should work as expected.

**Comment by sw34** [comment]
wow, didn't see that at all!  copy and paste gets you everytime!

Thanks, guess I should have picked up on that in the error message, PostMan did indeed show the /n character in the gui but it was super faint and I only saw it because you pointed me there.

Confirmed this is working as expected.
