### ISSUE TITLE
Saw setup wizard when I started up a docker image

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1176]
### Description 

Started a fresh docker install using kickstart.

I saw the kickstart text:

```
fusionauth_1  |   - Created API key ending in [...f580]
fusionauth_1  |   - Activate License Id [...0c9a77]
fusionauth_1  |   - Completed [POST] request to [/api/application/85a03867-dccf-4882-adde-1a79aeec50df]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/0502df1e-4010-4b43-b571-d423fce978b2]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/e160cc59-a73e-4d95-8287-f82e5c541a5c]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/7fa81426-42a9-4eb2-ac09-73c044d410b1]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/c16b65a5-e6e9-4499-a7ac-ae228f8d9864]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/fa6668cb-8569-44df-b0a2-8fcd996df915]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/162b3719-3d71-4638-b9bf-f3e2093f7fe1]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/f0e9d738-c98d-45ee-b869-8636342c5158]
fusionauth_1  |   - Completed [POST] request to [/api/email/template/e6c74b53-d43d-471e-ae7e-906456d0f341]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000001]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000002]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000003]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000004]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000005]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000006]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000007]
fusionauth_1  |   - Completed [POST] request to [/api/user/registration/00000000-0000-0000-0000-000000000008]
fusionauth_1  |   - Completed [PATCH] request to [/api/tenant/30663132-6464-6665-3032-326466613934]
```

so I loaded up the page.

I saw the setup wizard (asking me to accept the license).

I then reloaded and aw the 'welcome page' (the root page).

### Affects versions

1.26.0

### Steps to reproduce

1. Set up kickstart
1. Start up a clean fresh docker install with 1.26. 
1. wait till kickstart runs, then visit localhost:9011
1. You should see the setup wizard
1. wait for another 30 seconds, reload the page
1. You see the root welcome page.

### Expected behavior

No setup wizard when kickstart is running.

### Additional context

Here's my docker files.
[issue-1176.tar.gz](https://github.com/FusionAuth/fusionauth-issues/files/6346860/issue-1176.tar.gz)

**Comment by robotdan** [comment]
If you let it sit a second did it go away after a refresh? The kickstart APIs are delayed because we have to wait for FusionAuth to fully start up before making API calls. 

So it is expect to see the setup wizard page (if you are sitting there refreshing) - but after Kickstart completes, if you refresh it should be gone. 

If it stays after kickstart is complete and you refresh the page, then it would be a bug.

**Comment by mooreds** [comment]
It does go away after a few seconds with a refresh. Closing.
