### ISSUE TITLE
Add webhook for kickstart completion

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1178]
### Problem

When I am running Kickstart in my CI/CD environment, I want to know when it is complete so that I can run my tests at that time and not before.

### Solution

Add a webhook when the Kickstart file is completed that I can listen for. I guess that would imply a `kickstart.complete` event too.

### Alternatives/workarounds

Poll for an entity that I know is at the bottom of my kickstart file.

### Additional context

Came up in this forum post: https://fusionauth.io/community/forum/topic/751/kickstart-in-ci-environment-unpredictable

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
How about `kickstart.success` - since we already have other events that end in `.success`.

**Comment by mooreds** [comment]
`kickstart.success` works great for me.

**Comment by Pyroseza** [comment]
I have a question, how exactly does one create this webhook at the time of creating the instance and what exactly do I point it to?

In my docker container I have an instance of fusionauth start up and create a few things for me via the kickstart, now in my CI/CD pipeline I have noticed the exact problems stated in the discussion thread and usually re-running everything works, annoyingly.

From what I can gather I have to create and enable the webhook, but I want to do this automatically all in the existing CI/CD pipeline I have here in github, so does that mean that I must create it using the kickstart itself?

In my case there is no long running instance to point the webhook to, as mentioned earlier in the same CI/CD pipeline for fusion auth I have the rest of my application code that builds and starts up, it's all in one place using docker-compose.

Can you please explain what is the corrected and expected use of this webhook as it's not very clear to me how it should work.

I assume something like this would go in the kickstart.json, but I'm not sure and would like some advice on how to use this correctly.

```
{
  "requests": [
    {
        "method": "POST",
        "url": "/api/webhook",
        "body": {
            "webhook": {
                "connectTimeout": 1000,
                "description": "Kickstart Sucess Webhook",
                "eventsEnabled": {
                    "kickstart.success": true
                },
                "httpAuthenticationPassword": "password",
                "httpAuthenticationUsername": "username",
                "url": "what goes here?"
            }
        }
    }
  ]
}
```

**Comment by mooreds** [comment]
@Pyroseza this is a good question for the forum: https://fusionauth.io/community/forum/

Or, if you have an Essentials or Enterprise plan, open a support ticket: https://account.fusionauth.io/account/support

**Comment by Pyroseza** [comment]
Cool will ask there and put the link here in case anyone else asks the same thing

**Comment by Pyroseza** [comment]
Done :) 
https://fusionauth.io/community/forum/topic/1525/how-should-i-be-using-the-kickstart-success-webhook
