### ISSUE TITLE
Improve database connection issue logging

### ISSUE THREAD

**Issue by atrauzzi** [FusionAuth/fusionauth-issues#1183]
### Description 

I'm getting the following error message from FusionAuth:

```
Unable to capture database lock. This indicates that the database either doesn't support locks or is misconfigured. at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.lockDatabase(JDBCMaintenanceModeDatabaseService.java:302)
```

Generally speaking, this error message doesn't tell me exactly what the issue is, it lists two possible problems which have totally different solution paths.  It would be nice if FusionAuth didn't attempt to wrap DB level connection issues so that I can better troubleshoot my setups.

**Comment by voidmain** [comment]
Hi @atrauzzi. This error message really shouldn't happen. It is basically saying that the database you are using is likely incompatible with FusionAuth. We have that in the code as a last resort when attempting to run database migrations. We could add some additional logging that would spit out the error from the database, but in some cases, the database returns no errors.

Can you provide details on your deployment, database, configuration, etc?

**Comment by andrewpai** [comment]
Closing due to lack of information.
