### ISSUE TITLE
Get notified of new FusionAuth releases

### ISSUE THREAD

**Issue by JuliusPC** [FusionAuth/fusionauth-issues#1184]
### Problem
There seems to be no RSS feed or such thing to get notified of new FusionAuth releases.

### Solution
Provide an RSS feed and link it on the [Releases page](https://fusionauth.io/docs/v1/tech/release-notes/).

### Alternatives/workarounds
Provide an JSON document or something like this with all version numbers.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
Hiya,

We've committed to updating this forum category, which has an RSS feed:

https://fusionauth.io/community/forum/category/5/release

https://fusionauth.io/community/forum/category/5.rss

Will that work for you? Or were you looking for something more structured?

**Comment by JuliusPC** [comment]
> https://fusionauth.io/community/forum/category/5.rss
> 
> Will that work for you?

The rss feed you linked misses the bugfix releases and includes spam for buying abortion pills in Saudi Arabia.

> Or were you looking for something more structured?

Ideally there would be a rss version of the Release Notes page with all the information in it. Of course, I could write a parser for the release notes page. But this is probably not the most stable way to do this.

**Comment by mooreds** [comment]
Ah man, I thought I'd deleted that spam, sorry about that!

Thanks for the feedback.

**Comment by jobannon** [comment]
As a future feature, we could also possibly add 

Under the `api/system/version` endpoint a boolean flag that was either:
- `latestVersion: "false"` 
- or `updateAvailable: "true"`
- or...

```
{ 
"version" : "1.27.0",
"techPreview" : "1.27.3, available",
"updateAvailable" : "true"
}
```

Currently, we update the version in an RSS feed from the forum(as mentioned here), but this would be a way to programmatically signal developers to update their systems.

-or-

Or possibly even enable the user to get emailed updates by submitting their email address in the UI.  A scheduled task or the like could send updates when they are published.

**Comment by JuliusPC** [comment]
Hmm, as I already wrote: The forum RSS feed misses patch releases, even the minor release 1.27 is missing.

The ingredients for an RSS feed version of the Release Notes already exists:

1. structured list of all releases at <https://license.inversoft.com/api/fusionauth/version>
2. Release Notes in a (somewhat) structured format: <https://github.com/FusionAuth/fusionauth-site/blob/master/site/docs/v1/tech/release-notes.adoc>

**Comment by jobannon** [comment]
@JuliusPC

 I have updated the second RSS source you mentioned with the latest minor release (we typically do not document patch releases there).
 
Thanks for the clarification and additional notes regarding this proposed feature!

**Comment by mooreds** [comment]
Had feedback from a customer requesting this too.

**Comment by voidmain** [comment]
Another option would be to add a feature in FusionAuth to configure a set of users to be notified of new versions along with an email template. Then we could have a scheduled task check for new releases (and optionally parses the HTML) and send  emails to the users.

**Comment by matthewhartstonge** [comment]
I would love this!
Have missed the past 2 updates.
We were expecting an email to come through via our cloud deployment, but am now fishing around to try and track it easily. 

Understandably fusionauth-app is closed source, but I noticed that [FusionAuth/fusionauth-containers](https://github.com/FusionAuth/fusionauth-containers) seem to track tags with the new versions of fusionauth.

If a Github release was performed at the same time as tagging a new version, we could easily keep track/be notified by using "github release" notifications.

**Comment by robotdan** [comment]
PSA : https://github.com/FusionAuth/fusionauth-site/pull/1440

**Comment by mooreds** [comment]
Closing because this is now live: https://fusionauth.io/docs/v1/tech/release-notes has a link to the RSS feed.
