### ISSUE TITLE
API to Create API Key

### ISSUE THREAD

**Issue by jmusyj** [FusionAuth/fusionauth-issues#1185]
## (Put feature request title here)
API to Create API Key

### Problem
We use FusionAuth as an IDM and create new tenants on the fly using the APIs. The one piece we're currently missing is the ability to create API keys on the fly. 

### Solution
An api: `/api/api-key` which takes an array of endpoint configurations which this API key would have access to - this would mimic the existing screen in the FusionAuth admin portal:

![image](https://user-images.githubusercontent.com/2378701/116133100-52d91700-a69c-11eb-9720-9a1b190c6541.png)

### Alternatives/workarounds
The only real alternative we have right now is to create an API key out of band...manually :(

**Comment by mooreds** [comment]
It's your lucky day @jmusyj . This was delivered in 1.26.1 under https://github.com/FusionAuth/fusionauth-issues/issues/887

We're currently working on documentation for it which should be delivered this week.

**Comment by jmusyj** [comment]
Oh awesome! That’s great to hear. Thanks @mooreds !

**Comment by mooreds** [comment]
Here are the docs for this, @jmusyj : https://fusionauth.io/docs/v1/tech/apis/api-keys/

Closing this. Please re-open if you don't consider the issue resolved.
