### ISSUE TITLE
Can't provide custom code in step up auth and then use send method

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1187]
### Description 

When you are using MFA and you use the `send` method after providing a `code` parameter to the `start`, the `send` method overwrites the custom code parameter.

### Affects versions

1.26.1

### Steps to reproduce

* Make sure you have a user who has email MFA enabled.
* Start the step up process like so:
```
curl -vv -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/two-factor/start' -d ' { "loginId": "dinesh@fusionauth.io", "code": "ABCDEFGHI", "state": {"foo":["bar","baz"]}}'
```
* if you look in the db you will see the code stored correctly: `ABCDEFGHI` (in external identifiers)
* then send the code using the `send` api call (making sure to use the `twoFactorId` returned above):
```
curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/two-factor/send/?twoFactorId=Edfu_jwYVCcmHMNJ6uVdpxZzIX5Ybm896PIht2FPDSY' -d ' { "methodId": "QTLC"}'
```
* If you look in the db, the code has been replaced with a 6 digit number, and that is what is emailed.

### Expected behavior

This may be a lack of understanding on my part but I would think that if I introduced a code in the `start` method, that is what would be sent using the method provided.

**Comment by mooreds** [comment]
This also appears to happen if you don't specify a custom code. If you just start then send the code changes.

**Comment by robotdan** [comment]
So, I took a look at this.. and it is "sort of" working as designed. 

There are a few use cases we are trying to support. 

*Use Case 1 - Step up, sending out of band*

1. Call Start, returns a `twoFactorId` and a one time code. 
2. Send everything out of band
3. Call Login and present the `twoFactorId` and a one time code
4. Success!

*Use Case 2 - Step up, sending in band*

1. Call Start, returns a `twoFactorId` and a one time code. 
2. Call Send to send the code to the user's email or SMS
3. Call Login and present the `twoFactorId` and a one time code
4. Success!

*Use Case 3 - Step up, use authenticator app*

1. Call Start, returns a `twoFactorId` and a one time code. 
2. Call Login and present the `twoFactorId` and a one time code generated from the authenticator app 
3. One time code returned from step one is not utilized. 
4. Success!


*Use Case 4 - normal login flow - with authenticator*

1. During login 2FA is required
2. Generate a `twoFactorId` and return `242` indicating the user must complete a two-factor login
3. The user uses an authenticator app to generate a one time code and the `twoFactorId` and presents a code and a `twoFactorId` to login
4. Success!

*Use Case 5 - normal login flow - with SMS or Email*

1. During login 2FA is required
2. Generate a `twoFactorId` and return `242` indicating the user must complete a two-factor login
3. The Two-Factor Send API is used to send a code to the user's email or mobilePhone, during this request a one time code is generated and associated with the `twoFactorId`. 
4. The user presents the `twoFactorId` and a one time code to login
5. Success!

*Use Case 5 - normal login flow - with SMS or Email, failure, multiple send requests*

1. During login 2FA is required
2. Generate a `twoFactorId` and return `242` indicating the user must complete a two-factor login
3. The Two-Factor Send API is used to send a code to the user's email or mobilePhone, during this request a one time code is generated and associated with the `twoFactorId`. 
4. The user does not get the code, or decides to use a different method such as a different phone
5. The Two-Factor Send API is used to send a code to the user's email or mobile phone, during this request a one time code is generated and associated with the `twoFactorId` - the previous code is gone once we generate this new value. 
6. The user presents the `twoFactorId` and a one time code to login
7. Success!

*Summary*
1. Ideally I would not generate a code on the Start API if we know we don't need it, but during this request we don't know yet if we will use the Send API, and we also want to support sending this out of band. This means I likely need to continue to generate a code on the Start API - and it will just not be used if we end up using an authenticator app.
2. In the re-send option I need to generate a new code, so perhaps I need to know the difference between calling Send right after a Start, and calling Send more than once so I can know when to overwrite the existing OTP. 

This last item, number 2 is probably where the fix needs to occur. Maybe we can walk this through to make sure I am not missing any other use cases you are trying to test.

**Comment by bguyza** [comment]
> This last item, number 2 is probably where the fix needs to occur.
I do believe that is correct!

Also, thanks for laying out these use-cases.  As you mention in the comments, the code gets kind of "gnarly" and this is helpful.

**Comment by robotdan** [comment]
Switching tag to "documentation", I think that is where we landed on this one. Let me know if I am mistaken.

**Comment by mooreds** [comment]
Yes, and this documentation has landed, closing.
