### ISSUE TITLE
Client library function which allows to query the version of FusionAuth

### ISSUE THREAD

**Issue by jegger** [FusionAuth/fusionauth-issues#1193]
# Client library function which allows to query the version of FusionAuth

### Problem
As the internals of FusionAuth change over versions, some of the API endpoints need different arguments / body. E.g. a new page samlv2logout in the theme. It is required in v1.25 during patch-theme() but not in v1.24. It can be done by calling /api/status. However that endpoint is subject to change (told to me by Joshua). Besides from that: The endpoint is not available in the client libraries (e.g. Python). 

### Solution
The client libraries should include a function which returns the version of FusionAuth.

### Alternatives/workarounds
Call /api/status directly by a REST client. (hint: you need to be authenticated to get the "version" key in the response).

### Additional context
-

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for opening the request @jegger  - this should be super easy to get into the next release.

**Comment by robotdan** [comment]
New API `/api/system/version` available in the client libraries, doc forthcoming, but the API does not require any args. We could look at adding additional detail to this API response in the future such as "latest available version".
