### ISSUE TITLE
There is no default Email MFA template provided

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1195]
### Description 

No default email MFA template is shipped.

### Affects versions

1.26.1

### Steps to reproduce

1. Go to the fusionauth dashboard
2. navigate to customizations -> email templates
3. See no default email MFA template

### Expected behavior

Would be great to have one. Also need to document it in https://fusionauth.io/docs/v1/tech/email-templates/

### Additional context

We ship with a SMS template, probably could just copy that text.

**Comment by robotdan** [comment]
We should have a default template, it gets created after you exit the setup wizard. It is not migrated for existing instances, so perhaps that is why did not see it. 

We no longer ship email templates in the db, so we don't really have a way to migrate templates into an existing instance. We should defiantly document the default template though! 

https://github.com/FusionAuth/fusionauth-app/tree/master/src/main/resources/emails

https://github.com/orgs/FusionAuth/projects/2#card-60461802

**Comment by mooreds** [comment]
Great, closing!
