### ISSUE TITLE
See openid connect exception in logs when provider isn't available

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1197]
### Affects versions

1.26, 1.27 (I see this starting around Feb 13 2021, so possibly other versions).

### Steps to reproduce

1. Stand up a separate FusionAuth instance (I called it local2.fusionauth.io)
2. create an OIDC Identity Provider for it
3. Shut down the separate FusionAuth instance

You'll see an error message in the logs every minute or so.

### Expected behavior

Not sure if we should be checking forever for this or if we should timeout and add an event to the Event Logs.

### Additional context

Here's the error message:

```
2021-05-05 2:29:03.393 PM ERROR io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderHelper - Unable to resolve OpenID Connect endpoints at [https://local2.fusionauth.io/.well-known/openid-configuration]. Status code [503]
2021-05-05 2:29:03.393 PM ERROR io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderHelper - 	 Error message: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
```

**Comment by voidmain** [comment]
It looks like this code has been the same since mid last year. This happens when the OIDC endpoint cache is reloaded, which happens every few minutes, and the OIDC provider is down.

We could change this to not log the ERROR or to log to the event log instead, but currently this is working as designed.

**Comment by robotdan** [comment]
I’d we aren’t creating an event log we could do that.

The only other alternative would be to make the request and then cache it, but if we do that, how long do we cache it? I don’t that OIDC suggests a mechanism to indicate when a discovery document has changed. I suppose it may be possible that we could read cache headers to understand how long we can cache the response before asking again. 

If we can’t connect , it means the system is down and thus is no longer a valid IdP so I think error if in some fashion is correct.

**Comment by mooreds** [comment]
I think it'd be nice to have it logged to the 'event log' but seems super low priority, since when operating FusionAuth you should be looking at both the event log and the system log for errors. 

(If any community member reading this has different opinions, please chime in.)

Will leave this open but, again, seems very low priority to make the logging change.

**Comment by robotdan** [comment]
This code path only creates event logs, so it appears as though we have deleted this logging so you will not see this noise in the logs.
