### ISSUE TITLE
User Email Shows as Verified (even when not really)

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1198]
### Description 
User email is possibly incorrectly recorded as verified, when it should not be.

### Affects versions
1.27.0 - with reactor lic.

### Steps to reproduce
1. Enable both email and registration gates (make both gated)
2. Navigate to `Applications > 🔍 view > copy the registration url`
3. Register a new user
4. As expected, see the dialogue "we need to verify some things notice"
5. BUT!  Before clicking on the verification email, take a look at the newly minted user in the admin UI (under 'source').
6. The user will show as email verified (but I have not clicked on any verification emails yet).

<details><summary>newly registered user - verification link not clicked</summary>
<p>

```json
{
  "active" : true,
  "connectorId" : "e3306678-a53a-4964-9040-1c96f36dda72",
  "email" : "bob@bob.com",
  "encryptionScheme" : "xxxxxxxxxxxxxxxxxxxxxxxxxx",
  "id" : "e263d340-c13b-4617-9e45-c68097e5a659",
  "insertInstant" : 1620248444475,
  "lastLoginInstant" : 1620248444576,
  "lastUpdateInstant" : 1620248444475,
  "passwordChangeRequired" : false,
  "passwordLastUpdateInstant" : 1620248444504,
  "registrations" : [ {
    "applicationId" : "01ed959b-1de8-4b04-9653-82059d3c9d44",
    "id" : "fa1e027d-0782-45c9-8e6f-3ddf5cbfc8c3",
    "insertInstant" : 1620248444576,
    "lastLoginInstant" : 1620248444576,
    "lastUpdateInstant" : 1620248444576,
    "usernameStatus" : "ACTIVE",
    "verified" : false
  } ],
  "tenantId" : "904a4bbe-8521-4623-97c4-e61f36ba52ae",
  "twoFactor" : { },
  "usernameStatus" : "ACTIVE",
  "verified" : true
}
```

</p>
</details>

<details><summary>after clicking the verification link - registrations.verified changes as expected</summary>
<p>

```json
{
  "active" : true,
  "connectorId" : "e3306678-a53a-4964-9040-1c96f36dda72",
  "email" : "bob@bob.com",
  "encryptionScheme" : "salted-pbkdf2-hmac-sha256",
  "id" : "e263d340-c13b-4617-9e45-c68097e5a659",
  "insertInstant" : 1620248444475,
  "lastLoginInstant" : 1620248444576,
  "lastUpdateInstant" : 1620248444475,
  "passwordChangeRequired" : false,
  "passwordLastUpdateInstant" : 1620248444504,
  "registrations" : [ {
    "applicationId" : "01ed959b-1de8-4b04-9653-82059d3c9d44",
    "id" : "fa1e027d-0782-45c9-8e6f-3ddf5cbfc8c3",
    "insertInstant" : 1620248444576,
    "lastLoginInstant" : 1620248444576,
    "lastUpdateInstant" : 1620248444576,
    "usernameStatus" : "ACTIVE",
    "verified" : true
  } ],
  "tenantId" : "904a4bbe-8521-4623-97c4-e61f36ba52ae",
  "twoFactor" : { },
  "usernameStatus" : "ACTIVE",
  "verified" : true
}

```

</p>
</details>

### Expected behavior
My assumption is that I should have 
- `"verified" : false` under both user and registration objects until I click on the verification link. 
- ie - `user.verified: false` until I click on the link that was emailed for verification purposes

### Platform
(Please complete the following information)
MacOS, brave, safari.

**Comment by robotdan** [comment]
Thanks for the feedback @jobannon - we'll make this a big more intuitive. We'll still only send one email, but we will leave both the user and registration un-verified until the completion of the registration verification.
