### ISSUE TITLE
Enable Email Verification on Self Service (and possibly Admin UI)

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1199]
### Description 
Enable email verification when using the self-service account management portal and updating user email.  Current behavior may be expected behavior.

### Affects versions
1.27.0 - with reactor lic.

### Steps to reproduce
1. Enable email gate(make gated)
2. Enable sub-option / toggle of `Verify email when changed`
3. With a registered user, log in to the account from the `Account URL` (enable self service account management forms)
4. Click on the edit button self service account management index page.
5. Update the user's email address and save

### Expected behavior
I would expect that the email address would not update until the user clicks on a verification link confirming that they own the new email address being designated in the self service account management index page.

Like I mentioned, may be expected behavior, as the user would be verified (they did log in after all).  However, asking to confirm new email address ownership may be an additional layer of security.  

### Screenshots
![image](https://user-images.githubusercontent.com/16090626/117213365-c1af2200-adb8-11eb-8bf7-210d72dd0681.png)

### Platform
(Please complete the following information)
MacOS, brave, safari.

**Comment by voidmain** [comment]
This is currently working as designed. The handling you are referring to here is covered by issue #1 and is on the roadmap for 2021.
