### ISSUE TITLE
Python Client Library

### ISSUE THREAD

**Issue by colundrum** [FusionAuth/fusionauth-issues#12]
**Problem**
Developers building applications natively in Python. Currently because there is not a native library for Python, developers will need to use a third party REST client.

**Solution**
Provide a FusionAuth client library written in Python to provide native bindings for Python/Flask developers.

**Comment by robotdan** [comment]
Hi @colundrum thanks for the request. 

We do have a Python library in development, it just needs a bit of testing. I'll follow up with you on this thread when it is available. 

Thanks!

**Comment by robotdan** [comment]
@colundrum Would you be able to use this library if it was built in Python3? Or would you require it to be compatible with Python2?

**Comment by tyduptyler13** [comment]
Hi, we have our [python client](https://github.com/FusionAuth/fusionauth-python-client) nearly ready. We will publish and document it soon.

**Comment by robotdan** [comment]
https://fusionauth.io/docs/v1/tech/client-libraries/python
https://github.com/FusionAuth/fusionauth-python-client
https://pypi.org/project/fusionauth-client/

Please open any issues you find with the client library here https://github.com/FusionAuth/fusionauth-python-client/issues

Thanks.
