### ISSUE TITLE
Unable to add new registrations to a user

### ISSUE THREAD

**Issue by jrpedrianes** [FusionAuth/fusionauth-issues#1201]
### Description 
When we are trying to add a new registration to a user we get an error and the "Add" button doesn't appear.

### Affects versions
1.27.0

### Steps to reproduce
1. Go to 'Users'
2. Click on 'Manage in any user.
3. See an error

### Screenshots
<img width="426" src="https://user-images.githubusercontent.com/1927286/117274116-a98ce080-ae54-11eb-8cef-bbfde634529f.png">

### Platform
 - Device: Desktop
 - OS: macOS
 - Browser + version: Chrome 90.0.4430.93
 - Database: PostgresSQL 13.1

**Comment by jrpedrianes** [comment]
The problem was a migration that was done incorrectly, I don't know why

**Comment by mooreds** [comment]
Hmmm. So you were able to get it resolved? @jrpedrianes ?

**Comment by jrpedrianes** [comment]
Yes yes, I don’t know why, but the migration from 1.25 to 1.26 didn’t  complete correctly,  this migration we did it manually and maybe wrong. 

Thanks
