### ISSUE TITLE
Feature: Steam Identity Provider

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1208]
### Problem
I want to log into Steam from my application. 

### Solution
Create a new IdP type for Steam.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by jerryhopper** [comment]
Regarding this option, i see it is implemented - yet i have a question about it.
![image](https://user-images.githubusercontent.com/1160857/124295254-ea555d00-db58-11eb-94ef-011cb56ecaf5.png)

The api-key is obtainable via : https://steamcommunity.com/dev
But the client-id remains a mystery to me.

What is not clear to me is what is that client Id.   Is that a clientid provided by steam?  or is this a clientid from a fusionauth app?

If its from Steam,  where in heavens name can i find/get this clientid?

**Comment by robotdan** [comment]
>  yet i have a question about it.

You are not allowed to ask questions. 😆 

Ha, ok, just kidding. 

Some of these IdPs are tricky to configure and more difficult to collect all of the details. Looking at the Steam doc ( https://partner.steamgames.com/doc/webapi_overview/oauth ) it says the Client ID will be obtained from Valve. 

You may even have to open a ticket with Steam/Valve to ask for it. I'd have to review how we set up our dev account to be sure. I can ask the team how they set this one up.

**Comment by jerryhopper** [comment]
hey dan, i understand you close this.   
Valve isnt that fast with answers, but i forwarded the question to Valve.  Got a reply that they didnt understand the question. so i added more details.  When i finally get a response with the answer i will share the details here.

**Comment by robotdan** [comment]
If you want to share your reply we may be able to help decode - @brettwp did the initial integration with Steam and may be able to assist.
