### ISSUE TITLE
Support cloudfront-forwarded-proto header

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1218]
### Problem

This was a request from a user mentioned during an interview.

I want to be able to have FusionAuth fronted by a CDN like Cloudfront and interpret headers correctly.

"This is to use the FusionAuth Admin UI - when we try to log into those it would fail per default with a CSRF error - because it thinks that the request is not done with https but the request was done with https. Cloudfront handles ssl termination for us and appends `cloudfront-forwarded-proto=https`. For FusionAuth to work in this case we have a custom MiddleWare in Traefik just to set `x-forwarded-proto` to `https` all the time (because there cannot be unauthenticated requests anyway).

It took a lot of time to figure this out.

### Solution

Have FusionAuth accept/honor the `cloudfront-forwarded-proto` the same way it does `x-forwarded-proto`. Since this header appears to be cloudfront specific, maybe allow a configuration in the system with the name of the protocol forwarding header?

### Alternatives/workarounds

Document this clearly. Probably in a proxy guide.

### Additional context

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-cloudfront-headers.html

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
I don't think it would make sense for FusionAuth to handle product specific headers. 

Assuming you could either configure CloudFront to use the header we recognize, or pass it through a proxy and re-write the header. Assuming you can do that with a cloud front lambda of some sort.

**Comment by mooreds** [comment]
Closing this as wontfix. Will add notes about this to the 'to-be-written' proxy guide.
