### ISSUE TITLE
LDAP Connector - don't replace registrations and memberships after initial user creation

### ISSUE THREAD

**Issue by sw34** [FusionAuth/fusionauth-issues#1220]
LDAP Connector - don't replace registrations and memberships after initial user creation

### Problem
I am using the LDAP connecter to connect my users with Active Directory.  Currently, in the Lambda you needs to specify registrations and memberships for the users.  If once the user is created you add a registration using the api or admin console it is reverted to whatever is set in the lambda.  In my applications I have many groups/roles so I need to set a large switch statement so the users are given the correct permissions.  While this is fine for an initial setup, as I add applications I need to manage roles, groups and registrations in the lambda instead of the api or admin console.  You can use the "Migrate User" but then you no longer use LDAP for the password verification, which breaks the SSO that this feature gets you.

### Solution
Either have a way to add registrations if they don't exist, or to only sync the parameters that are set in the lambda.

### Alternatives/workarounds
Have a setting that a migrated user still uses LDAP to verify password and does not sync any settings at all.

### Additional context
none

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@sw34 can you please share your lambda code (or the relevant part of it)?

**Comment by sw34** [comment]
This is from my test environment, in production I would end up with about 10 different case scenarios and about 40 users.  Not exactly the easiest way to manage groups and registrations.  Each case scenario will have different app registrations and groups.

```
// Using the response from an LDAP connector, reconcile the User.
function reconcile(user, userAttributes) {
  user.email = userAttributes.userPrincipalName;
  user.firstName = userAttributes.givenName;
  user.lastName  = userAttributes.sn;
  user.active    = true;
  user.verified = true;

  user.username = userAttributes.sAMAccountName;

  var wec3 = {};
  wec3.applicationId = "4ecdb067-0fc8-4d15-91b6-c2a4f6b1d070";
  wec3.username = userAttributes.sAMAccountName;
  wec3.verified = true;
  
  var sfc = {};
  sfc.applicationId = "ba9969d4-8480-44f9-8be6-2ff7830074f7";
  sfc.username = userAttributes.sAMAccountName;
  sfc.verified = true;
  
  var superUser = {};
  superUser.groupId = "e2cb1e4d-c563-46a0-bb87-115ef4034672";
  
  switch (userAttributes.sAMAccountName) {
    case "test":
      sfc.roles = ["Admin", "Supervisor"];
      user.registrations = [sfc];
      user.memberships = [superUser];
      break;
    case "userB": case "userC":
      //wec3.roles = ["Purchasing-Approver"];
      user.registrations = [wec3, sfc];
      user.memberships = [superUser];
      break;
  }
   
  //user.id = FusionAuth.ActiveDirectory.b64GuidToString(userAttributes['objectGuid;binary']);
  user.id = guidToString(userAttributes['objectGUID;binary']);
}
```

Note, in testing ways to make my life a bit easier I tried to use groups in this example, but when I login as "test" using the POST api/login call the token that is returned did not have any of the roles for sfc application, even though they roles show up in the admin console gui.  That is why I added the ```sfc.roles = ["Admin", "Supervisor"];``` to that user, as I need test some other pieces while working out how this connector works!

**Comment by mooreds** [comment]
Rather than resetting the registrations or roles, can you add to them if needed? Would that solve your problem?

```
 switch (userAttributes.sAMAccountName) {
    case "test":
      sfc.roles = ["Admin", "Supervisor"];
      user.registrations.indexOf(sfc) === -1 ? user.registrations.push(sfc) : null;
      ...
      break;
```

**Comment by sw34** [comment]
the user object is empty at the start of the lambda, appears that it not resolved to a user until after the lambda executes. 

```
console.debug("user reg before: " + user.registrations.length);
user.registrations = [wec3, sfc];
console.debug("user reg after: " + user.registrations.length);
```
results in the following output:

```
user reg before: 0
user reg after: 2
```

**Comment by mooreds** [comment]
Hmmm. My suggestion was meant to alleviate this issue: "If once the user is created you add a registration using the api or admin console it is reverted to whatever is set in the lambda."

Is that the main issue you are trying to solve? Maybe I misunderstand.

**Comment by sw34** [comment]
Yes.

Step 1: user logs in first time, LDAP connector/lambda creates user, sets initial registrations/roles/memberships 
Step 2: in gui or using api add a role, registration or membership to user
Step 3: user logs in second time. user is updated with registrations/roles/memberships from lambda, and removes all the changes added in step 2

To avoid this, any changes to registrations/roles/memberships I want to make I need to do in the lambda.  That works fine, just not and ideal place to make these changes.

**Comment by sw34** [comment]
that doesn't work though because every call to the lambda the user.registrations is an empty array, it is not populated with what the user already has set.  Even if you don't set it to anything and add a registration using the gui, that registration is removed on the very next login.

I added this code to debug:
```
  console.debug("index of reg sfc: " + user.registrations.indexOf(sfc));
  console.debug("index of membership superUser: " + user.memberships.indexOf(superUser));
```
the output was -1 so its always replaced with what is set on the lambda:
```
index of reg sfc: -1
index of membership superUser: -1
```

Still if I add a registration to another app using the gui, it is removed on the very next login.

Lets go super simple:

1) set lambda to most basic user from your documentation:
```
function reconcile(user, userAttributes) {
  user.email = userAttributes.userPrincipalName;
  user.firstName = userAttributes.givenName;
  user.lastName  = userAttributes.sn;
  user.active    = true;

  //user.id = FusionAuth.ActiveDirectory.b64GuidToString(userAttributes['objectGuid;binary']);
  user.id = guidToString(userAttributes['objectGUID;binary']);
}
```
2) login using api/login as a user
3) add a registration to user
4) have user login again - registration is now gone - all registrations and memberships must be set in lambda

**Comment by mooreds** [comment]
Thanks for the detailed repro steps @sw34 !

What version of FusionAuth are you running?

**Comment by sw34** [comment]
1.27.2

**Comment by mooreds** [comment]
Thanks, I've raised the issue internally.

**Comment by sw34** [comment]
any update on this issue?  I migrated to the paid version to use the AD login, but the current workaround is too much of a burden and will revert back to the previous methods using Azure AD and OpenId.

**Comment by robotdan** [comment]
I'll have to dig into this one a bit further. The behavior sounds like it is working as designed. If you don't configure the connector to migrate users, we just sync what is provided from the connector which includes the work done in the lambda. 

If I understand correctly, you want to use the LDAP connector as the source of record for a set of users, but then you want to manage their group membership and registration in FusionAuth. 

When we first wrote this feature, we didn't want to deal with merging data from another source of record, that can get really complicated. However, in order to cover your use case we would need to add a bunch more configuration to the connector to know what to sync, what not to sync, what to create on the first time we see the user, but what not to sync on subsequent logins. 

If you want to just use the connector for auth, but not for synchronizing the user state, you should probably be using a FusionAuth IdP. However, we do not have an LDAP IdP at the moment. But it could be that connectors don't really fit your use case, at least not how we initially envisioned them to work. 

Let me know if I am properly understanding your use case, and please clarify if I missed it.

**Comment by sw34** [comment]
If this is working as designed I can find another way to do what I am looking for.  I originally setup an OpenId Connect login for Azure AD.  I thought the LDAP connector would work better for what I wanted/needed but because it was designed more as a migration and not just as an authentication method I have a different method I can use.

Thanks for the assistance, I will close this case and open a new one if I have trouble with something else.

**Comment by robotdan** [comment]
Great, thanks for the update @sw34 hopefully the OIDC IdP will work a bit better for you. If you do have other questions, please feel free to start a thread on the FusionAuth user forum. 

Thanks!

**Comment by robotdan** [comment]
@bguyza can you confirm you were able to reproduce?

**Comment by robotdan** [comment]
Hm... I may have this mixed up with https://github.com/FusionAuth/fusionauth-issues/issues/1432.
