### ISSUE TITLE
Documented recovery codes API nonexistent

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#1224]
### Description 
The API endpoint for recovery codes [generation](https://fusionauth.io/docs/v1/tech/apis/two-factor/#generate-recovery-codes) and [retrieval](https://fusionauth.io/docs/v1/tech/apis/two-factor/#retrieve-recovery-codes) that are present in the documentation are actually non existent. To be more precise, I'm writing about the following requests:
```
POST /api/recovery-codes/{userId}
GET /api/recovery-codes/{userId}
```

The endpoint cannot be enabled in API key configuration, and requests made with _super key_ results in `404`.

The API methods are also no present in python client, and since clients are generated, other clients are probably affected too.

### Affects versions
1.27.2

### Steps to reproduce
1. Attempt to utilize mentioned APIs
2. Receive `404` error.

### Expected behavior
Recovery code APIs works as documented.

### Platform
Experienced with FA 1.27.2 docker image.

**Comment by mooreds** [comment]
Thanks for the report @mgetka , the correct path is `/api/user/two-factor/recovery-code/`. We'll get that fixed ASAP. Sorry about that!

**Comment by mooreds** [comment]
Okay, this should be fixed in the public doco: https://fusionauth.io/docs/v1/tech/apis/two-factor/#generate-recovery-codes

Thanks again for the bug report!
