### ISSUE TITLE
Update Java version to next LTS (targeting 17)

### ISSUE THREAD

**Issue by anuradha-w** [FusionAuth/fusionauth-issues#1227]
### Description 
FusionAuth uses Java 14 currently.  Support and updates for this version of Java [ended in September, 2020](https://en.wikipedia.org/wiki/Java_version_history). FusionAuth should update to a newer version of Java that will receive updates and maintenance from the maintainers (including security fixes).

There are a few considerations with upgrading Java:

* FusionAuth currently uses Nashorn which has been removed from Java in version 15. We need to use the new Nashorn library or switch JavaScript engines (#571)
* The new LTS version of Java is 17 and is schedule for release in September 2021
* Ensuring all of our libraries and frameworks are compatible with Java 17 will require time. We use some low level libraries and they often lag in terms of support for new JDKs.

### Affects versions
All FusionAuth versions including and after 1.16, according to issue #481.

### Steps to determine Java version
1. `mkdir fusionauth`
2. `cd fusionauth/`
3. `wget https://files.fusionauth.io/products/fusionauth/1.27.2/fusionauth-app-1.27.2.zip`
4. `unzip fusionauth-app-1.27.2.zip`
5. `./bin/startup.sh`
6. `./bin/shutdown.sh`
7. `./java/current/bin/java -version`
8. Java version is displayed as `14.0.1+7` from AdoptOpenJDK.

### Plans
Our plan is to update FusionAuth to the next LTS version of Java. This is version 17 and is scheduled for release in September of 2021. Using an LTS will allow us to receive updates from the Java maintainers for many years.

In order to complete this work, #571 must be completed first and blocks this feature request.

### Additional context
Running an unsupported version of Java may compromise security, and result in failed security audits.

**Comment by voidmain** [comment]
Hi @anuradha-w. Thanks for open a ticket regarding the version of Java FusionAuth is using. I updated the main overview of the ticket to better describe our plans for Java.

**Comment by robotdan** [comment]
Resolved via https://github.com/FusionAuth/fusionauth-issues/issues/1489. 

GH issue https://github.com/FusionAuth/fusionauth-issues/issues/571 is not yet resolved because Nashorn is available as a jar now that is compatible with JDK 17.
