### ISSUE TITLE
The "Email verification required" and " Verify registration required" theme templates don't parse in the editor

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-issues#1228]
### Description 
The problem is twofold. Since version 1.26? there are 2 new theme templates: **Email verification required** and **Verify registration required**.

1. After an upgrade from 1.25 the Admin UI tells me to upgrade my custom theme and shows which templates I need to fill with content. I can choose to copy content over from the default theme, but this doesn't work for the above mentioned templates. The content field is very small and the button does not copy anything. I can however add content to the field manually and save to continue with my theme.

2. When editing a theme (original FusionAuth and custom) the editor is not loading for the above mentioned templates. The content field is 1 line high and there is no code parsing in the content field. There is also a Javascript error in the console:
```
ExpandableTable.js?version=1.27.2:25 Uncaught TypeError: Cannot read property 'getDataAttribute' of null
    at new FusionAuth.UI.ExpandableTable (ExpandableTable.js?version=1.27.2:25)
    at new FusionAuth.Admin.ThemeForm (ThemeForm.js?version=1.27.2:55)
    at 75a068fd-e94b-451a-9aeb-3ddb9a3b5987:131
    at HTMLDocument.value (PrimeDocument.js:377)
```

### Affects versions
Version 1.27.2

### Steps to reproduce
1. Edit any theme in the Admin UI.

### Expected behavior
Templates should "parse" properly.

### Screenshots
<img width="943" alt="Screen Shot 2021-05-17 at 12 17 05" src="https://user-images.githubusercontent.com/1012764/118522610-416ab400-b70a-11eb-8cff-bc14588753c4.png">

<img width="1153" alt="Screen Shot 2021-05-17 at 12 18 15" src="https://user-images.githubusercontent.com/1012764/118522619-43cd0e00-b70a-11eb-8c25-b677c1840d21.png">

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: MacOS
 - Browser + version: Chrome 90.0.4430.212
 - Database: MySQL 5.7.33

**Comment by robotdan** [comment]
Thanks for the report Felix, we'll take a look. I was thinking this was fixed in 1.27.2, but perhaps not. If you are on 1.27.2, is it possible you are editing a theme created on 1.27.0 or 1.27.1?

**Comment by flangfeldt** [comment]
Nope, I have the theme since v1.0 ;-) Went straight from 1.25.0 to 1.27.2.

**Comment by robotdan** [comment]
@jobannon can you try a recreate?

**Comment by flangfeldt** [comment]
Update: I'm also seeing this issue with the **OAuth two-factor methods** template.

**Comment by jobannon** [comment]
Can confirm the same behavior.  
Except, strangely no `js` error on **OAuth two-factor methods** template.
On local dev `1.27.3`

### OAuth two factor
<img width="1192" alt="Screen Shot 2021-05-18 at 5 05 33 PM" src="https://user-images.githubusercontent.com/16090626/118734397-87ec0b80-b7fb-11eb-8a6f-29b2954e25a3.png">
<img width="1192" alt="Screen Shot 2021-05-18 at 5 05 30 PM" src="https://user-images.githubusercontent.com/16090626/118734402-8a4e6580-b7fb-11eb-8119-90fc7115e20c.png">
### Email Verificiation 
<img width="1192" alt="Screen Shot 2021-05-18 at 5 04 47 PM" src="https://user-images.githubusercontent.com/16090626/118734404-8b7f9280-b7fb-11eb-865c-c7c5c4a639f5.png">

**Comment by robotdan** [comment]
Thanks @jobannon - I'm unable to replicate your results. Can you post your recreate steps, no need for screenshots. Thanks!

**Comment by jobannon** [comment]
Perfect!  Recreated using docker and local dev setup.  

# Using Docker
1. Get latest version of docker
```
docker pull fusionauth/fusionauth-app:latest
```
3. Copy over the fastpath docker scripts
```
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml && curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env && docker-compose up
```
4. System Should boot and reflect `1.27.2`
5. Create a FusionAuth account
6. Navigate to `Customizations` -> `Themes` -> `OAuth two-factor methods` 
Should see the behavior there as well 
7. Navigate to `Customizations` -> `Themes` -> `Email Verfiication Required` 
Should see the behavior there as well 

# Using Local Dev Setup 
1. Update all
2. Build/Integrate
3. System Should boot and reflect `1.27.3`
4. Login to account using admin
5. Navigate to `Customizations` -> `Themes` -> `OAuth two-factor methods` 
Should see the behavior there.  
6. Navigate to `Customizations` -> `Themes` -> `Email Verfiication Required` 
Should see the behavior there as well.

I did a cursory dive through the codebase and checked linters, but could not locate anything immediately.

Also ran docker on my home ubuntu machine and had a similar issue. 

...
