### ISSUE TITLE
Providing a license id in kickstart.json doesn't actually enable the reactor

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1230]
### Description 

I added a license id to my kickstart file, but it doesn't seem to be picked up. 

### Affects versions

1.27.2

### Steps to reproduce

* add a license id to a kickstart file
* start it up (I use docker)
* See that the license id is picked up: `Activate License Id` appears in the log file
* Login
* Go to http://localhost:9011/admin/reactor/

Still need to enter license key. If I enter the same license key as in the kickstart file, reactor activates just fine. I can login with my kickstarted user as well, so non licensed functionality doesn't seem degraded.

### Expected behavior

License key provided in kickstart starts up ok.

### Platform
- Docker
- postgresql
- ES

### Additional context

I didn't use a developer license key, not sure if that was the issue.

Here's my kickstart.json file:

```
{
  "variables": {
    "adminEmail": "admin@fusionauth.io",
    "password": "password",
    "defaultTenantId": "30663132-6464-6665-3032-326466613934"
  },
  "apiKeys": [
    {
      "key": "REDACTED",
      "description": "Standard development API key"
    }
  ],
  "licenseId": "REDACTED",
  "requests": [
    {
      "method": "POST",
      "url": "/api/user/registration/00000000-0000-0000-0000-000000000002",
      "body": {
        "user": {
          "email": "jared@fusionauth.io",
          "firstName": "Jared",
          "lastName": "Dunn",
          "password": "#{password}",
          "data": {
            "Company": "PiedPiper"
          },
          "imageUrl": "https://local.fusionauth.io/images/doc-profile-pictures/photo-jared.png"
        },
        "registration": {
          "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
          "roles": [
            "admin"
          ]
        }
      }
    }
  ]
}
```

**Comment by robotdan** [comment]
Recreated, not sure what the deal is yet. During kickstart we end up getting a `404` from the license server, but it seems to work ok after startup. Perhaps some sort of timing issue. 

I should be able to get this one resolved tonight, just need to stare at it a few more minutes.

**Comment by robotdan** [comment]
The root issue is that with the recent licensing changes we must activate an instance prior to activating the license. During kickstart we try to load the license which looks locally, and then attempts to download it second. 

To download a license, you must have a valid license and a valid instance (previously activated). In this case, we have not yet activated the instance, so it fails to activate the license. 

The original reason for "activating" the instance last during kickstart is that you have the option to opt-in to mailing list (at least in the UI activation work flow). So we want to see if you create any users during kickstart that should be used with activation. 

The other benefit to activating last is that kickstart may fail, so doing this last allows us to ensure everything went well first. 

We'll need to review this workflow to decide how to best handle this workflow. The current work-around is to activate the license after the system has started up.

**Comment by robotdan** [comment]
Should be fixed in just a few minutes. Fix will be made to the license server.

**Comment by mooreds** [comment]
Thanks, this works great now!
