### ISSUE TITLE
Add lambda for Entity management

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1233]
### Problem

I love lambdas and want to be able to apply them to the JWTs created during entity management. But I can't.

### Solution

Have a lambda applied during the client credentials grant. Probably need a new lambda type.

### Alternatives/workarounds

Not too many, I suppose you could proxy the JWT and create a new one with an external service.

### Additional context

This came up on a call with a potential customer.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by voidmain** [comment]
It would be great to have some examples of what this type of lambda would do. 

Is the idea to pull additional details from the two Entities that are part of the client credentials grant? And would the signature look like this?

```
function populateJWT(jwt, recipient, target) {
...
}
```

**Comment by voidmain** [comment]
This is available as a tech preview in version `1.28.0`. Feel free to leave comments here on this new lambda or open new issues for any bugs found.
