### ISSUE TITLE
FusionAuth leaks mysql connections

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1236]
### Description 

FusionAuth spawns a bunch of mysql connections and when shut down doesn't clean them up. Eventually this leads to a `SQLSTATE[HY000] [1040] Too many connections` error.

### Affects versions

1.27.0, installed as a zip file.

### Steps to reproduce

* Install mysql and fusionauth
* Start fusionauth
* login to the mysql console and run `show processlist`. You'll see a number of connections.
* stop fusionauth
* run `show processlist` again. 

There's a decrease in the number, but it doesn't go to zero.

```
mysql> show processlist;
+-----+-----------------+-----------------+------------+---------+------+------------------------+------------------+
| Id  | User            | Host            | db         | Command | Time | State                  | Info             |
+-----+-----------------+-----------------+------------+---------+------+------------------------+------------------+
|   5 | event_scheduler | localhost       | NULL       | Daemon  |  676 | Waiting on empty queue | NULL             |
|  28 | fusionauth      | localhost:60031 | fusionauth | Sleep   |  639 |                        | NULL             |
|  39 | fusionauth      | localhost:60054 | fusionauth | Sleep   |  616 |                        | NULL             |
|  40 | fusionauth      | localhost:60056 | fusionauth | Sleep   |  615 |                        | NULL             |
|  41 | fusionauth      | localhost:60057 | fusionauth | Sleep   |  614 |                        | NULL             |
|  42 | fusionauth      | localhost:60059 | fusionauth | Sleep   |  612 |                        | NULL             |
|  43 | fusionauth      | localhost:60064 | fusionauth | Sleep   |  611 |                        | NULL             |
|  44 | fusionauth      | localhost:60065 | fusionauth | Sleep   |  610 |                        | NULL             |
|  45 | fusionauth      | localhost:60066 | fusionauth | Sleep   |  608 |                        | NULL             |

```

I've also seen the number of connections grow over time without stopping fusionauth.

The workaround to fix this is to restart mysql once you get the error (around 150 connections by default).

### Expected behavior

I'd expect it to work fine with mysql without restarting the database periodically. :) 

https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements/ lists this version of mysql as supported.

### Platform
(Please complete the following information)
 - Device: desktop
 - OS: macos 11.3
 - Database: mysql 8.0.23 installed via homebrew, using the mysql-connector-java-8.0.18.jar jar file.

### Additional context

I didn't tweak the fusionauth.properties file at all and this is an old config file (started from 1.16, I think), so the database.* properties are not set.

No relevant error messages in the logs.

Looked in the hikariCP issues list and didn't see anything relevant: https://github.com/brettwooldridge/HikariCP

**Comment by robotdan** [comment]
Interesting. Did you go through maintenance mode during this test, or were you sitting in maintenance mode? I think that is the only time we may attempt to make a JDBC connection outside of using the HikariCP.

**Comment by mooreds** [comment]
Nope, I was just starting and stopping this via bin/startup.sh and bin/shutdown.sh .

I do use docker as well, but all those images were stopped at this time, and they use internal postgresql, not mysql.

**Comment by voidmain** [comment]
I've never seen a leak like that before from Hikari or our code when you shutdown FusionAuth. I would have expected that the JVM would terminate all Sockets during a shutdown.

Can you ZIP up your deployment and send it to one of us? I'd like to see if I can reproduce that locally.

**Comment by mooreds** [comment]
Will share privately.

**Comment by mooreds** [comment]
Just ran into this again on 1.28.

**Comment by andrewpai** [comment]
Closing as this seems to no longer be an issue.

**Comment by mooreds** [comment]
@andrewpai did you test this out, or how do we know this is no longer an issue?

**Comment by andrewpai** [comment]
Yes, tested with FusionAuth 1.50.1 and MySQL 8.3.
