### ISSUE TITLE
The "method" variable is not set in the /oauth2/two-factor theme page

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-issues#1237]
### Description 
According to the documentation (https://fusionauth.io/docs/v1/tech/themes/#oauth-two-factor) the `/oauth2/two-factor` theme page has the `method` variable. But this variable is always empty, regardless of the choice that has been made in the `/oauth2/two-factor-methods`. Also if a method has been chosen previously and is set as "Last used" it is still emtpy.

### Affects versions
I see this problem in v1.27.2.

### Steps to reproduce
1. Edit the `/oauth2/two-factor` page in a custom theme.
2. Add the line `[@helpers.hidden name="method"/]` somewhere in the page.
3. Login as a user with 2 MFA methods.
4. View the source of the `/oauth2/two-factor` page. The hidden field's value is always empty.

### Expected behavior
According to the documentation the `method` variable should be a string with possible values of `authenticator`, `email` or `sms`.

### Screenshots
<img width="932" alt="Screen Shot 2021-05-24 at 18 39 24" src="https://user-images.githubusercontent.com/1012764/119415381-7e611880-bcbf-11eb-84db-d6dbe6f90538.png">

<img width="802" alt="Screen Shot 2021-05-24 at 18 39 52" src="https://user-images.githubusercontent.com/1012764/119415387-80c37280-bcbf-11eb-8e44-906a9eb34d23.png">

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version Google Chrome 90.0.4430.212
 - Database: MySQL

**Comment by robotdan** [comment]
Thanks for reporting @flangfeldt .

That is a bug/typo in the template. We will remove the `[#-- @ftlvariable name="method" type="java.lang.String" --]` implicit variable declaration. 

@jobannon can you ensure the documentation is correct? You may need to test it to be certain how it is set up. But I believe only the `methodId` is available, the `method` reference is an artifact of an earlier prototype.  The `user` object is listed on the two-factor themed page, but I do not believe it is available.

@flangfeldt is this something you stumbled upon, or did you want to get the corresponding configured method from the `methodId`? It looks like aren't exposing the `user` object to this template, but we are in the `/oauth2/two-factor-methods`, we could probably also expose it here if it would be helpful.

**Comment by robotdan** [comment]
We'll take a look, I don't think we are currently exposing the method object, but we could either expose the user so that you can look it up or expose the two factor method directly.

**Comment by robotdan** [comment]
@jobannon - ignore the change the doc, let's update this to have that variable, but it will not be a string, it will be a method object. Once we ship the change we can update doc.

**Comment by robotdan** [comment]
This should be available in 1.28.0, let us know how it goes.

**Comment by flangfeldt** [comment]
I see the new new variable declaration `[#-- @ftlvariable name="method" type="io.fusionauth.domain.TwoFactorMethod" --]` in the theme page, but the documentation is not yet updated. See https://fusionauth.io/docs/v1/tech/themes/#oauth-two-factor. It's still saying that `method` is a string with 3 possible values.

<img width="872" alt="Screen Shot 2021-06-14 at 18 15 05" src="https://user-images.githubusercontent.com/1012764/121966493-c57d7f00-cd3c-11eb-9383-744d2ecd7bf6.png">

**Comment by robotdan** [comment]
Thanks @flangfeldt - updated.
