### ISSUE TITLE
Bad salt length error when using Bcrypt per User Import API

### ISSUE THREAD

**Issue by bmeloski** [FusionAuth/fusionauth-issues#1238]
### Description 
The Bcrypt passwords have stored salt in their own hash, yet imported users get unexpected error when trying to log in. There is "Bad salt length" error in the FA logs. 
### Affects versions
1.25
### Steps to reproduce
1. Create Bcrypt hashed password (you can use online bcrypt generators) using 4 rounds
2. Make request to Fusion Auth Import API

`{
    "users": [
        {
            "username": "username",
            "active": true,
            "password": "generatedhash",
            "salt": "",
            "encryptionScheme": "bcrypt",
            "email": "test@gmail.com",
            "factor": 4,
            "verified": true,
            "registrations": [
                {
                    "applicationId": "id"
                }
            ]
        }
    ]
}`

3. Get status 200
4. Try to login with imported user into the application
5. Receive unexpected error when trying to login(only with this user). Logs say "bad salt length". User is visible via FA admin, after changing his password via the dashboard his login works

### Expected behavior
Salt should not be needed using Bcrypt

### Platform
-  Env: image: fusionauth/fusionauth-app:latest
 - Database: postgres:11.9-alpine

**Comment by robotdan** [comment]
You'll need to separate out the hash and the salt on the Import API. 

For example `$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy` would be split out to the fields:

```
factor: 10
salt:  N9qo8uLOickgx2ZMRZoMye
password: IjZAgcfl7p92ldGxad68LJZdL17lhWy
```

The Import API does not parts this value and separate it out for you. Here is an example import script in Ruby. https://github.com/FusionAuth/fusionauth-import-scripts/blob/b8bac780b1f30291f3c7cf782d1f8dbfc3daa2d2/auth0/import.rb#L47

**Comment by mooreds** [comment]
@bmeloski will add a note to the docs.

Internal note: 

Not quite sure where the right place to do this. We could put it here https://fusionauth.io/docs/v1/tech/reference/password-encryptors/ where we mention bcrypt. We could also add a note to https://fusionauth.io/docs/v1/tech/apis/users/#import-users or add a section to the troubleshooting doc (for importing users). The latter probably makes the most sense.

**Comment by voidmain** [comment]
My vote would be to document it on: https://fusionauth.io/docs/v1/tech/apis/users/#import-users

This would be a note under the field definition for `users[x].password`. It would say something like:

```
NOTE: this field should not contain the Crypt/Shadow password format (i.e. `$5a$foobarbaz$728348sehalkoiew90u32970`). This should only contain the hash of the password itself (i.e. `728348sehalkoiew90u32970` from the previous example.
```

**Comment by mooreds** [comment]
Addressed in https://github.com/FusionAuth/fusionauth-site/pull/719

**Comment by mooreds** [comment]
Closing, as this is done.
