### ISSUE TITLE
/api/jwt/public-key?app..  Result in 404 while JWT enabled for application

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#124]
### Description 
For a JWTenabled app, i fail to retrieve the public key.

### Steps to reproduce
1. create app, enable jwt.
2. call /api/jwt/public-key endpoint
3. see no results..

### Expected behavior
A public key should be returned.

**Comment by robotdan** [comment]
The public key API will only return a public RSA or EC key. Is it possible you have left the default HMAC signing algorithm? 

Any RSA or EC public keys configured will be published by both of these APIs:
https://fusionauth.io/docs/v1/tech/oauth/endpoints#json-web-key-set-jwks
https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-public-keys

The latter will return a PEM encoded public key, and the former uses the JWKS standard.
