### ISSUE TITLE
Nits with FusionAuth admin user experience

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1241]
## Admin UX thoughts

This is a feature request from a user, thanks @trevorr! 

### Problem
"The FusionAuth UI is a bit dated looking and not always intuitive or ergonomic. For example, most of the useful operations on a table view involve tiny buttons on the right edge."

Other issues (of varying degrees of painfulness) that have popped up:

* the way to add redirect urls is not copy and paste friendly
* there's no way to link to a specific tab on an admin screen
* not super mobile friendly
* the escape key doesn't close modal windows

### Solution

Would be nice to overhaul the UX to help with some or all of the above issues.

### Alternatives/workarounds

Use the API :).

### Additional context

Initial issue in quotes came out of a user interview. Other issues are based on my personal experience.

### Related issues

https://github.com/FusionAuth/fusionauth-issues/issues/903

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
> the way to add redirect urls is not copy and paste friendly

This should work. Can you provide more detail why this doesn't work very well? 

> there's no way to link to a specific tab on an admin screen

This should work. We don't provide an option to copy a link to it... but each tab has an Id and you can add that to the end of the URL such as `#email` if the tab id is `email`. 

> not super mobile friendly

Can you provide examples? We do quite a bit of testing on mobile. Do you find tables overflowing, or are you looking for more touch friendly controls, etc? What size of mobile do you use? (phone, screen size etc)

> the escape key doesn't close modal window

We've discussed this and would like to add this. If we deliver this we will likely put dialogs into two buckets, one for confirmation dialogs or info dialogs, and the other for forms with controls that have a submit button. For the latter, we will likely not use the escape button as to not accidentally dismiss the dialog when tabbing or navigating the form with the keyboard.

**Comment by mooreds** [comment]
> Can you provide more detail why this doesn't work very well?

Please see uploaded video. With safari 14.1, I can paste a url, but if I click off, the URL is not saved. I have to paste the URL, then edit it slightly, then click on the blue box, before it is added.

https://user-images.githubusercontent.com/91825/119981237-a039f400-bf7a-11eb-886b-fe60dd754650.mov

> but each tab has an Id

This is awesome! I didn't know that.

> Can you provide examples [of mobile issues]? 

Great question. I don't recall any specific instances, more of a general feel, but will keep an eye out and either add comments or open issues. So consider that nit moot until I can come up with more specifics.

> We've discussed this and would like to add [the escape key closing modals].

Yup, here's the tracking issue: https://github.com/FusionAuth/fusionauth-issues/issues/903

**Comment by andrewpai** [comment]
Closing, as each of these items has been addressed in one way or another.
