### ISSUE TITLE
why is there a "pi" link on bottom left of "/"  page with URL https://thepraetorians.net/ ?

### ISSUE THREAD

**Issue by konvergence** [FusionAuth/fusionauth-issues#1242]
With the last release 1.27.2 I can see a link to URL https://thepraetorians.net/
Why ?

**Comment by robotdan** [comment]
This is an Easter egg. :-) 

If you view the theme editor for that page you'll see this:


```
[#--
    Feel free to remove this, it is just a stupid easter egg. Enjoy.
    Escape is impossible when you're caught in the net https://www.imdb.com/title/tt0113957/  --]
 <div style="position:fixed; left:0; bottom: 0; margin-bottom: 7px; margin-left: 10px;">
   <a style="color: inherit;" href="https://thepraetorians.net" title="Escape is impossible when you're caught in the net.">π</a>
 </div>
 ```

**Comment by konvergence** [comment]
hum... 
This is not very reassuring, for an authentication solution

**Comment by robotdan** [comment]
Developers usually have a great sense of humor! Sorry you don't like the joke.

**Comment by konvergence** [comment]
Thanks, for your feeback, the most important for me is that there no risk at all.
Regards

**Comment by soullivaneuh** [comment]
> Developers usually have a great sense of humor! Sorry you don't like the joke.

It may be fun if the template override is not too overkill. If we want to remove that joke, we have to copy the full template. :-/

The impact is however limited as this default template have to be rewritten in any case.

Also, the referenced link is not existing anymore.

**Comment by nhorton** [comment]
Yeah - this joke now goes to a scammy website. This is not really a dev-cute thing; when you get a security product directing to a scam website, that is scary.

**Comment by mooreds** [comment]
Thanks @nhorton . Perhaps we should consider removing this link. Appreciate the feedback!

For recent versions of FusionAuth the link is https://the-praetorians.net/
