### ISSUE TITLE
FusionAuth crashes when connecting to managed database service like DigitalOcean

### ISSUE THREAD

**Issue by DomPatmore-SAE** [FusionAuth/fusionauth-issues#1244]
### Description 
I'm using a managed database on DigitalOcean. I've noticed that if I leave the superuser fields blank, after about 12 hours the connection will drop. @mooreds sent me a workaround by inserting dummy information for the super user, but fusionauth is unable to connect. I'm able to connect externally to the database.

### Affects versions
Using a managed Postgresql 13 database on DigitalOcean

### Steps to reproduce
1. Create a 1GB droplet on DigitalOcean
2. Create a postgresql DB on DigitalOcean and create a database for fusionauth.
3. Following the steps to connect fusionauth with the database, but do not complete superuser fields
4. Wait 12 hours
5. Attempt to log back into fusion auth

Here's the error message:

```
Cause: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3397ms.
```

### Expected behavior
Able to login to fusionauth repeatedly

### Screenshots
![Screenshot 2021-05-27 at 16 44 04](https://user-images.githubusercontent.com/60002614/119858315-426ec300-bf0c-11eb-9459-42459fb07613.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Linux droplet
 - Firefox
 - Postgres 13

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by jobannon** [comment]
@DomPatmore-SAE 

Thanks for the report! 

After some discussion with @mooreds, it would seem we have two issues here.

______
1. The first issue is that you were getting a `hikari transient exception error` after the initial setup of FusionAuth
2. After some time, you are attempting to set up again and cannot.  In other words, you can't connect to the DB or get past the maintenance mode screens to reset FusionAuth.
______

### Regarding Issue # 2
To confirm, you are able to connect using a SQL shell with your previously created credentials (from issue # 1 steps/procedure), but putting in those same credentials in the maintenance mode screen does not allow a connection?

If this is true, it  would be most helpful to have confirmation that you:
- Connected to your db via shell using `super user credentials`
- Connected to your db via shell using `regular user credentials`
- A copy (you can redact any sensitive information if needed) of the SQL connection string

### Regarding Issue # 1
- If I understand correctly, did this error happen right away, or was there any delay?

&nbsp;

Any other information around steps taken when the error occurred, would be helpful to our dev team if this a bug.  Additionally, based on your feedback, it may make sense to split this issue into two issues for clarity.

Thanks and let us know.  We appreciate it!

**Comment by DomPatmore-SAE** [comment]
Hello!

*Issue #1:*
    This started after initial setup.Looking through the logs, it's a
couple hours initialization where the following occurs:

2021-05-25 4:47:54.104 PM ERROR org.primeframework.mvc.servlet.PrimeFilter
- Error encountered
org.apache.catalina.connector.ClientAbortException: java.io.IOException:
Broken pipe


*Issue #2:*
    I can confirm I'm able to connect via shell to the DB both with super
and regular user credentials. The connection string is
db-postgresql-XXX1-do-user-XXX-0.b.db.ondigitalocean.com

Let me know if this helps

**Comment by jobannon** [comment]
Thanks, @DomPatmore-SAE!  

 I will run this by the team and see what we can deduce.  Will be in touch as needed.  
 
 I appreciate you offering this feedback and information.
 
 Thanks,
Josh

**Comment by jobannon** [comment]
After discussing with the team, I have a few more questions:

&nbsp;
- Are you through all the setup and maintenance screens, have FusionAuth fully initialized, wait some time (seems like a few hours), and have errors (from issue # 1)?
     **-or-** 
- Are you on the setup and maintenance mode screen (FusionAuth is not fully initialized, stay on this screen), wait some time (seems like a few hours), and have errors (from issue # 1)?
&nbsp;
- Do you have any more error logs or system logs that you can provide?
    - the error logs are located at `/usr/local/fusionauth/logs/fusionauth-app.log
/usr/local/fusionauth/logs/fusionauth-search.log`
- Any more specifics, around procedures taken or errors received.
- What type of droplet did you create? I am relatively new to DigitalOcean, but it seems like I can create a Ubuntu 20.4 and many other flavors.  
- Are you running on more than one node in DigitalOcean (sounds like maybe, no?)?
- Likewise, there seem to be a few more options with the type of managed database you can create.  Any other details here? 
    - I also notice that you have to allow `trusted sources` to access your database.  Perhaps you enabled shell access, but you have not enabled the IP/location of the node running FusionAuth? 

Tracking down this type of bug can be complex.  A number of ancillary factors could cause/effect this bug (a few of which may not be related directly to FusionAuth as a software package) including if you are behind a corporate firewall, have a proxy running, your network/cloud configuration, or lost network connectivity unexpectedly--to name a few. 

I say all of this to give a little more context to the comprehensive task of bug hunting 🙂 .  If you have more information, we would certainly review it. 

Thanks!
Josh

**Comment by DomPatmore-SAE** [comment]
@jobannon on a brand new droplet, I go through the setup and maintenance screens, then wait a few ours. When I try to reinstall by dropping the db and rerunning the maintenance mode, it gets stuck.

With regards to droplet, I created this one:  1 GB Memory / 25 GB Disk / LON1 - NodeJS 12.18.0 on Ubuntu 20.04  When I didn't allow trusted sources, I wasn't able to get a database connection. Adding the IP resolved the issue, but it still crashed.

I've got multiple droplets, but fusionauth is the only thing running on that particular one.

Finally I've got these as some of the errors:

2021-05-25 5:35:48.308 PM ERROR com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.system.NodeManager] failed but will be re-run.
org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3397ms.
### The error may exist in io/fusionauth/api/domain/FusionAuthNodeMapper.xml
### The error may involve io.fusionauth.api.domain.FusionAuthNodeMapper.retrieveAll
### The error occurred while executing a query
### Cause: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3397ms.

Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3397ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:139)
        at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        ... 25 common frames omitted
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:865)
        at org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1647)
        at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:552)
        at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:168)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
        ... 37 common frames omitted

I appreciate this is tricky to debug. I'm curious what droplet size others chose and if they had s similar problem

**Comment by jobannon** [comment]
@DomPatmore-SAE Thanks for the additional info.  If you are stateside, I hope that you had a great 3 day weekend!

I will dig in this week and see what I can find out if anything. I know that quite a few others are running FusionAuth on multiple cloud providers (included Digital Ocean) so I would imagine this is related to a bug or set up config.  

I will see if I can replicate it.  Along those lines, do you have a specific way that you have connected to the managed DB from the droplet?  Some of DB clustering is new to me (to be transparent), so if you had a specific connection procedure, that might be helpful to know.

**Comment by DomPatmore-SAE** [comment]
Hi @jobannon.
   I'm in the UK and we also have a holiday here, which as nice, though
still spent a good chunk of it working!

  I haven't done anything special to connect to the DB-I just followed the
instructions. Let me know if I can be of anymore help.

**Comment by jobannon** [comment]
@DomPatmore-SAE, 

I ran two tests within Digital Ocean.  One test I ran connecting my local laptop installation of FusionAuth to a DB cluster in Digital Ocean.  The second test was from a droplet to a DB cluster.

I ran both for about 18 hours and then tried connecting again from the FusionAuth App (port 9011).  From my local installation, things went smoothly.  From the droplet, I did have to refresh my browser twice, but eventually, I was able to connect. 

I reviewed logs after, and it would appear that there are no anomalous errors from the FusionAuth app.  The slow start-up on the droplet (test two) could be related to how Digital Ocean is provisioning those virtual CPUs and how they become available (or not) after some time idling.  

Since I cannot see anything directly related to how FusionAuth is functioning, and some evidence is pointing me to how the hosting service is managing idle vCPU's, my inclination would be to close out this ticket.  If you find any errors related to how FusionAuth is running, we can certainly review them again. 

Thanks,
Josh

**Comment by dompatmore** [comment]
@jobannon Thanks for that update! Can I ask the size droplet that was used? I'll try to copy your experiment.

**Comment by jobannon** [comment]
@dompatmore Sure.  I was using the left-most values, due to cost.

![image](https://user-images.githubusercontent.com/16090626/121947025-d0231e80-cd12-11eb-8787-6fa8b45dbe17.png)

**Comment by jobannon** [comment]
Same values go for the distributed db as well.  I was using the cheapest possible.
