### ISSUE TITLE
Complete registration flow does not update user.username and does not respect email gate

### ISSUE THREAD

**Issue by lliu-20200701** [FusionAuth/fusionauth-issues#1246]
### Description 
Having a custom form with user.username being a required field. Import a user without user.username. After login, the user is in the complete registration flow. At this point, the user's email has not been verified. The user is imported under a tenant that has an email gate. The following 2 bugs are observed in the following process:
1. After a successful login with this user's imported credential, the user is prompted to enter user.username. On submit, observed user.username is posted back to Fusion; however, checking the user's details using Fusion's dashboard, user.username for the said user remains missing.   
2. After a successful login with this user's imported credential, the browser goes directly to the specified redirectUri even though the email gate is on and this user's email has not been verified.

### Affects versions
1.27.2

### Steps to reproduce
Please see description.

### Expected behavior
For bug 1, user.username is updated.
For bug2, the email gate is presented.

### Screenshots
N/A

### Platform
(Please complete the following information)
 - Device: MacBook Pro
 - OS: macOS
 - Browser: chrome 81.0.4044.122 (Official Build) (64-bit)
 - Database: MySQL 8.0.15

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lliu-20200701** [comment]
we are using user.username

**Comment by bguyza** [comment]
We were able to successfully recreate this issue and working to resolve.  Updates to come.
