### ISSUE TITLE
Magnifying glass button for event logs is not working

### ISSUE THREAD

**Issue by DavidHaerer** [FusionAuth/fusionauth-issues#1249]
### Description 
When clicking on the magnifying glass to view the contents of an event log, only the background goes dark, but no pop-over appears with the entry details.

### Affects versions
1.27.2

### Steps to reproduce
1. Go to 'System -> Event Log'
2. Click on 'View Event Log' (green magnifying glass)
3. See that the page goes dark, but the event log does not show up

### Expected behavior
When clicking on the magnifying glass, I see the details of the  selected event log.

### Platform
 - Device: [Desktop]
 - OS: [Windows 10]
 - Browser + version [Brave Version 1.25.68 Chromium: 91.0.4472.77]

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
This is likely a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/961. Try disabling the Brave Shield and see it if works. See notes and work arounds in the the linked issue.

**Comment by DavidHaerer** [comment]
Hi @robotdan, yes that indeed solved it :) Thanks!
