### ISSUE TITLE
Gated User Registration Fails with Consents

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1255]
### Description 
If you add consents to a custom advanced registration form, your registration will fail.

### Affects versions
1.28

### Steps to reproduce

See https://fusionauth.io/community/forum/topic/1076/unable-to-invoke-validationmethod-on-the-class-class-io-fusionauth-app-action-oauth2-completeregistrationaction/4

```
At the tenant level:

Set the email verification settings on the tenant to clickable link, and the unverified behavior to gated
Set a password policy
Turn on user.registration.verified and user.email.verified webhooks
At the system level:

Create a single value consent
Create a custom registration form:
Username field (user.username)
Email (user.email)
Password (user.password)
Country (This is a select field with 2 string options stored on user.data.country)
Terms of use (This is a consent)
At the application level:

Create an application
Set generate refresh token
Set Authorization Code, Password, and Refresh Token grants
Set require registration to on
Set the templates for email verification (the default ones in this case)
Verification strategy same as tenant (this is probably unnecessary but I did it just to see if it made a difference)
Enable self-service registration
Set the custom registration form
```
### Expected behavior
The user will be able to log in via OAuth2 protocol

### Platform
Local dev and docker (for customer)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

3 things stand out
- My single value consent is 
`e3d4bea3-e6c8-4903-be16-ebb57398a7a2`
- When the login/authorize action on OAuth fails, it fails due to the validator.  Somehow a few digits are getting chopped off.

`Caused by: org.primeframework.mvc.parameter.el.InvalidExpressionException: The expression string [4bea3-e6c8-4903-be16-ebb57398a7a2']] is invalid.`

`2021-06-08 4:31:29.797 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.primeframework.mvc.PrimeException: Unable to invoke @ValidationMethod on the class [class io.fusionauth.app.action.oauth2.CompleteRegistrationAction]`

also - the registration form field does not have validators in place like other forms such as `self service user`
![image](https://user-images.githubusercontent.com/16090626/121269244-b8641a00-c87c-11eb-9c44-0215439ce37c.png)
![image](https://user-images.githubusercontent.com/16090626/121269279-ca45bd00-c87c-11eb-9416-ba0082130bcf.png)

**Comment by robotdan** [comment]
Ended up breaking this up into sub-issues. When reviewing this bug, some additional issues were found and recorded. See:

https://github.com/FusionAuth/fusionauth-issues/issues/1258
https://github.com/FusionAuth/fusionauth-issues/issues/1259
https://github.com/FusionAuth/fusionauth-issues/issues/1260
https://github.com/FusionAuth/fusionauth-issues/issues/1261
