### ISSUE TITLE
Login with known devices

### ISSUE THREAD

**Issue by anbraten** [FusionAuth/fusionauth-issues#126]
### Problem
Entering secure passwords takes some time. 

For example, when logging into a new device and you have a very long password you may have to look up your password in a password manager. 

### Solution
1. Start login process with a new device by entering username or email
2. Send notification to already authorized devices (normally something like your mobile) by some kind of serviceworker
3. Open notification on your known device and redirect to fusionauth webpage
4. Show user some details of the new device (ip, user agent, ...) and ask user to allow or deny access to the new device
5. The new device should now be automatically logged in

### Additional Context
For example, this is what Google does when you sign into a new device. They may require a username and password, but they sort of force a two factor by sending a notification to your phone that says "do you recognize this device". (IP address and geo-location, etc)

### Alternatives/workarounds
1. Some kind of qr code login like Wh..tsa...Web uses it.
2. Passwordless login - magic link login. This is available in FusionAuth version 1.5.0

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by plunkettscott** [comment]
How would this work exactly? Would a mobile app have to be maintained for this? How do you safely decide if a device is the same device? Cookies can be moved from one browser to another and IP addresses can be recycled. Is there something else that I’m not aware of?

**Comment by Garogat** [comment]
I thought of something working like Auth0 Guardian https://auth0.com/multifactor-authentication. They are using an extra app for this. Wouldn't it be possible to use a webapp instead. You register your phone once, which would save a token to your localstorage. This lets your phone being signed in. Cookies could be copied, but why would that be a security issue. Maybe the token could be using webauthn additionally, so that you have to authenticate on your phone each time a new request comes from a new device, before you are able to press allowed.

**Comment by robotdan** [comment]
Closing this one out. I don't know that it would make sense to implement anything that is not part of a well known or supported spec such as TOTP, WebAuthN, etc. 

We plan to be partnering with a few passwordless providers in 2021/2022 to provide additional, and we will also be delivering WebAuthN. This should provide plenty of options for "device" based auth, or using a trusted device to provide auth. 

If I am missing a use case, or spec that you'd like to see here, please do re-open and clarify the requirement.
