### ISSUE TITLE
Integration with Redash

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#127]
Redash is an amazing tool that can allow us to build dashboard based or many data source. Redash is probably the most famous tool to create custom dashboard or run queries in data teams.

That could be cool if FusionAuth could be integrated with redash, it would allow us to group all our stats / dashboards.

Since it is open source, we can create our own data source (https://discuss.redash.io/t/creating-a-new-query-runner-data-source-in-redash/347) and submit the pull request (https://github.com/getredash/redash/pulls).

**Comment by plunkettscott** [comment]
While there is no integration for FusionAuth, you could very easily create dashboards from your database since you have full access to the PostgreSQL database of FusionAuth.

**Comment by blanchonvincent** [comment]
yes definitely, it is easily doable now but it can have some issues:
- a bridge with the API that is documented will avoid us to understand you internal logic
- people that do not host their own product, they should not have full access to the PostgreSQL?

Anyway, I will close it soon since it is doable now.

Thank you

**Comment by robotdan** [comment]
@blanchonvincent we do have the report APIs so that you could consume the JSON response and then feed it into Redash. 

https://fusionauth.io/docs/v1/tech/apis/reports

Are there any additional reports that would help you with this use case?
