### ISSUE TITLE
Incorrect response to GET /api/group when there are no groups

### ISSUE THREAD

**Issue by dhait** [FusionAuth/fusionauth-issues#1275]
### Description 
When there are no groups, GET /api/group returns an empty object.  It should return
   `{ "groups" : [] }` 

### Affects versions
1.28.0

### Steps to reproduce
Perform GET /api/group when there are no groups

### Expected behavior
 `{ "groups" : [] }` 

### Actual behavior
`{}`

### Platform
All

**Comment by jobannon** [comment]
Thanks for the feedback @dhait! 

Team note:  if we were to fully consider this issue, we could have to review making changes to many of our APIs (`consents` or `webhooks` for instance).

**Comment by voidmain** [comment]
I believe that this is a limitation of Jackson and how we have configured it. We have it set to trim all empty lists and since `groups` is empty, it gets removed. If we change that behavior, it could have a large impact to the overall codebase.

**Comment by dhait** [comment]
If it can't be changed for technical reasons, it should at least be documented for every API call affected.

**Comment by jobannon** [comment]
@dhait noted for consideration in our documentation process. Thanks for the feedback; it really helps to improve the overall product experience!

https://github.com/FusionAuth/fusionauth-site/issues/789

**Comment by robotdan** [comment]
As @voidmain mentioned, we are configuring Jackson with the following serialization feature which causes the symptom you observed. 

```
.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false)
```
( https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/SerializationFeature.html#WRITE_EMPTY_JSON_ARRAYS ) 

This is primarily for legacy reasons. I would like to remove this config, it is mainly just a dev/test effort to fix a $@#! ton of tests that assert on JSON responses.

**Comment by robotdan** [comment]
We are now serializing empty arrays, so the response will now be:

```
{
  "groups" : []  
}
```
