### ISSUE TITLE
Query users by external provider ids (eg: Facebook)

### ISSUE THREAD

**Issue by derTuca** [FusionAuth/fusionauth-issues#1277]
### Problem
I am trying to implement Facebook login in an app using FusionAuth and I need to implement a data deletion callback in order to submit it for review. I cannot, however, find a way to query a user by their Facebook id so I can identify and delete them accordingly.

### Solution
I see two solutions:
1. Having an endpoint to query the user by their Facebook (or another IdP) id
2. Having an endpoint specifically designed for the Facebook data deletion implementation.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@derTuca 

What version of FusionAuth are you using?

Can you tell us more about what Facebook gives you in this callback? They provide just the Facebook id?

One way you could work around this is you could, when someone first logs in using Facebook, use the Facebook token returned (either in `user.registrations[x].tokens` under the Facebook identity provider key or in the https://fusionauth.io/docs/v1/tech/apis/identity-providers/links/ if you are using 1.28 or greater) to get the facebook id. Then store that in the `user.data` field. This is then searchable using the user search API when the deletion event occurs.

Does that make sense?

**Comment by robotdan** [comment]
The work around that @mooreds mentioned could work, if you were to add this value to the user data somewhere. This may not work great if you are also using the Link API to remove links. Then the de-normalized `user.data.` field would get out of sync. 

We could add the option to retrieve a link by IdP Id + IdP unique User Id, or add this info to the search index in some fashion so you could easily query all users to find the user that is linked to a Facebook user by Id.

**Comment by robotdan** [comment]
In the upcoming release, we will be enhancing the Link API to allow you to retrieve a "link" by IdP Id and the IdP unique userId. This means that with the Facebook IdP Id (this is fixed in FusionAuth), and the Facebook user unique Id, you can ask FusionAuth for the linked User which will return a FusionAuth `userId` - at which point you can delete the user.

**Comment by robotdan** [comment]
Think should work in 1.29.0 using the Link API `GET` method. Let us know if we missed a use case.
