### ISSUE TITLE
Webhook Failure on Registration Screen causes FusionAuth to Fallback to default theme

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1279]
### Description 

If the user has a themed registration page. 

If they have a webhook fail (and the settings are such that a failure means the registration event will not be committed) when the user is re-routed to the register page they fall back to the default theme.

### Affects versions
1.28.1

### Steps to reproduce
1. Configure a webhook for an application
2. Make the webhook fail (force 400 error code return)
3. Make `user.registration.create` contingent on webhook success
4. Go to the applications register link
5. Try and register
6. Get webhook error (b/c we forced it to error)
7. BUT - see that our URL has changed and we are now on the default theme.

### Expected behavior
The registration theme for the tenant to remain, despite webhook failures.

### Screenshots

`https://local.fusionauth.io/oauth2/register?client_id=fb7f1cc1-27f7-414a-9585-42a7676a8b76&response_type=code&redirect_uri=http%3A%2F%2Fwww.piedpiper.com`
![image](https://user-images.githubusercontent.com/16090626/123181492-a7093900-d44a-11eb-9882-31a4f151e722.png)
 <p align="center">⬇️ ⬇️ ⬇️ </p>  
 
`https://local.fusionauth.io/oauth2/register`
![image](https://user-images.githubusercontent.com/16090626/123181566-c2744400-d44a-11eb-8e13-0feedb458280.png)

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

#### Login/Authorize Does Not seem to be affected.
https://local.fusionauth.io/oauth2/authorize?client_id=fb7f1cc1-27f7-414a-9585-42a7676a8b76&response_type=code&redirect_uri=http%3A%2F%2Fwww.piedpiper.com 
⬇️ 
https://local.fusionauth.io/oauth2/authorize
but still keeps the theme.

**Comment by t2gp-jordan** [comment]
Just wanted to say this works great now, thank you so much!!
