### ISSUE TITLE
Allow stopping login based on lambda result

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1282]
## Allow stopping login based on lambda result

This came up on a customer call.

### Problem

I want to control who can login with some complicated business logic. (Is the user a member of this group, but not that one.)

### Solution

Add another lambda that exists at the moment of login. Provide the same info as the jwt populate lambda, but accept a return value. If the return value is true, the login process continues. If the return value is false, the login fails. I think you'd want that failure to be hidden from the end user, but available to the developer/theme designer, so if they wanted to display the reason, they could.

I suppose you could also signal a failed login with an exception; that's an implementation detail.

### Alternatives/workarounds

Don't use the hosted login pages.

Use the populate JWT lambda to set a custom claim and then do a check in your application code for it.

Use a webhook and transactions; return a non 2xx status code on the login.success event. This blocks login, but has some UX issues. See https://github.com/FusionAuth/fusionauth-issues/issues/166 for more on that.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/952
- https://github.com/FusionAuth/fusionauth-issues/issues/1318

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by alexeev** [comment]
We are currently evaluating various IAM solutions including FusionAuth. The use-cases described in [this comment](https://github.com/FusionAuth/fusionauth-issues/issues/952#issuecomment-903439171) are also relevant (and critical) for our solution. It would be very helpful to get a rough time horizon for this feature being available in your commercial offering.

**Comment by mooreds** [comment]
@alexeev the best way to get a time horizon for this issue is to engage with our sales team, who can discuss options (up to and including contractual obligations for feature delivery). Please reach out to them via this form: https://fusionauth.io/contact and I promise they'll be in touch :) .

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/512
