### ISSUE TITLE
Minor Theme API doc issues

### ISSUE THREAD

**Issue by elliotdickison** [FusionAuth/fusionauth-issues#1283]
### Description 
* The [Theme API documentation](https://fusionauth.io/docs/v1/tech/apis/themes/) omits any references to the `theme.templates.index` field which can be used to read/write the Freemarker template for FusionAuth's index page.
* The ["Update a Theme documentation"](https://fusionauth.io/docs/v1/tech/apis/themes/#update-a-theme) states "You must specify all of the properties of the Theme when calling this API. This API does not merge the existing Theme and your new data. It replaces the existing Theme with your new data.", but this is not quite accurate - the PATCH method can be used to merge new data with the existing theme data.

### Affects versions
I'm seeing this on the current doc site.

### Steps to reproduce
N/A

### Expected behavior
Updated/accurate docs

### Screenshots
N/A

### Platform
N/A

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Thanks for an amazing product! Your feature set, APIs, and documentation are first-class.

**Comment by mooreds** [comment]
Thanks for the suggestions, @elliotdickison !

**Comment by mooreds** [comment]
This should be resolved by https://github.com/FusionAuth/fusionauth-site/pull/886

**Comment by mooreds** [comment]
Closing, as this doc was added a bit ago and released just now.
