### ISSUE TITLE
Device activate flow ends up at device complete page with missing client_id

### ISSUE THREAD

**Issue by lliu-20200701** [FusionAuth/fusionauth-issues#1286]
### Description 
At the last step of device activation flow, met with missing client_id error as attached.

### Affects versions
1.28.1

### Steps to reproduce
1. Start device activation flow
2. Enter the user code and login 
3. See error

### Expected behavior
The device complete page is rendered.

### Screenshots
![image](https://user-images.githubusercontent.com/67760333/123714715-ba8e1880-d82b-11eb-9fc4-2a7d54b4866f.png)

### Platform
(Please complete the following information)
 - Device: MacBook
 - OS: macOS
 - Browser + version: chrome
 - Database: MySQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Looking at the debug `.har` file, the final redirect to `/oauth2/device` which should end up redirecting to `/oauth2/device-complete` has an invalid `state` parameter. 

Here is the redirect that is shown in the `.har` file, line breaks added for readability. 

```
https://{redacted}/oauth2/device?
  code=aiInuQ6oVS9dm2dLN_ROOybAihUh9anU0NlQ_U05w6k&
  locale=en_US&
  state=Y2xpZW50X2lkPTJiNTRiZTFiLTJkYzktNDM1My05MGQyLWQ2NjA4ODlmZWY3Mw%2CY2xpZW50X2lkPTJiNTRiZTFiLTJkYzktNDM1My05MGQyLWQ2NjA4ODlmZWY3Mw
  &userState=Authenticated
```

The correct `state` value is `Y2xpZW50X2lkPTJiNTRiZTFiLTJkYzktNDM1My05MGQyLWQ2NjA4ODlmZWY3Mw` which is a base64 encoded `client_id=2b54be1b-2dc9-4353-90d2-d660889fef73`.

But what I see is that value duplicated, separated by `%2C` which is the URL encoded `,`. This means the `state` parameter is being duplicated in one of the forms along the way. Can you review any modifications you've made to the stock templates to ensure the hidden `state` field has not been duplicated anywhere?

**Comment by mooreds** [comment]
Per conversation with @lliu-20200701 , closing this.
