### ISSUE TITLE
Need to auto login when presented with an already linked 1st part account

### ISSUE THREAD

**Issue by lliu-20200701** [FusionAuth/fusionauth-issues#1289]
### Description 
When a device activate flow is started with a 1st party account that is already linked, the user should have been logged in automatically with entering username and password.  

### Affects versions
1.28.1

### Steps to reproduce
1. Start the device activate flow with a linked 1st account
2. Enter the user code
3. See error (should not see sing in/up pages)

### Expected behavior
Automatic login

### Platform
(Please complete the following information)
 - Device: MacBook
 - OS: iOS
 - Browser + version: chrome
 - Database: MySQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
This is working for me, do you have any other details you can provide. Which IdP are you using for the 1st link?

**Comment by mooreds** [comment]
Per discussion with @lliu-20200701 , closing.
