### ISSUE TITLE
Breached password detection doesn't work as it used to

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1297]
### Description 

When you enable breached password detection, you used to get warnings even when an admin changed the password. Now you don't.

### Affects versions

1.28.0
master

### Steps to reproduce

1. Enable the reactor with a license key
2. Turn on breached password at the tenant level (Tenants -> Your Tenant -> Password). Enable match mode of `high` and force the user to change their password at login (or record the result, same effect).
3. Edit a user
4. Change their password to `password`

### Expected behavior

You are not allowed to change the password (as specified here: https://fusionauth.io/docs/v1/tech/guides/breached-password-detection/ Search for "Below, you can see an administrative user has received an error message because they attempted to update a password to a compromised value:"

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Also tried registering a user to an application using self service registration.

Tried two different license keys on two different instances.

The breached password statistics increment once on the reactor overview page, but you never see 'action required' and the search for breached password users `_exists_:breachedPasswordStatus AND NOT (breachedPasswordStatus:None)` always returns 0 users.

**Comment by robotdan** [comment]
Strange, this works for me. 

Create a user:
1. Log into demo system
2. Create a new user with password `password`
3. Fails indicating password is too common. 

Change a user:
1. Log into demo system
2. Create a new user with a good password
3. Change the user's password to `password`
4. Fails indicating password is too common

**Comment by mooreds** [comment]
Hmmm. Now it does work as I expect and I'm unable to, for example, register a user with an invalid password. Let me see if I can replicate.

**Comment by robotdan** [comment]
When you initially saw the symptom had you just recently activated the license? 

There can be a brief delay from activation in order for reactor to pick up the new encryption keys.

**Comment by mooreds** [comment]
That is correct. I had just activated the license. Perhaps that was the cause.

**Comment by mooreds** [comment]
Documented this in https://github.com/FusionAuth/fusionauth-site/pull/817 

Closing.
