### ISSUE TITLE
Self registration verification email always causes "The request contains an invalid or expired verification Id."

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#1298]
### Description 
We did setup an application, in the application we defined "Registration verification settings"
![image](https://user-images.githubusercontent.com/12079732/124669234-57972400-deb2-11eb-90f0-5b129128f1f4.png)

When using the URL sent via email, it will always cause the error "Sorry. The request contains an invalid or expired verification Id. You may need to request another verification to be sent."
![image](https://user-images.githubusercontent.com/12079732/124668921-d9d31880-deb1-11eb-9466-da3a83da8f6e.png)
When adding the email in to this form requesting a new verification email and clicking on the link of the new email it works, the url looks exactly the same by side the encoded bytes string

these are the tenant email verification settings:
![image](https://user-images.githubusercontent.com/12079732/124669390-975e0b80-deb2-11eb-8ee2-f01e66f074c1.png)
![image](https://user-images.githubusercontent.com/12079732/124669486-be1c4200-deb2-11eb-8d09-2d2b6537cfbe.png)

### Affects versions
FusionAuth™ version 1.28.1

### Expected behavior
When the user registers the first verificatoin email sent should work and i dont need to require to request a second email.

### Platform
- Kuberenetes Deployment
- Database: PostgresSQL 9.6
- Search: elasticsearch 7.11.2

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Are you trying to do Email Verification or Registration Verification? 

It looks like you are using the Email Verification template for Registration Verification. Can you try selecting the Registration Verification template in your configuration?

**Comment by Aaron-Ritter** [comment]
uff.. sorry.. jup this was it. so does a "Registration Verification" do more then just verifying the email because it looks like the email is verified too when using this template?

**Comment by robotdan** [comment]
Registration verification ends up verifying the email as well if it is un-verified. But the intention of this feature is to allow you to require a confirmation that user signed up for access to a new application. 

In most cases, what you want is email verification, not registration verification.
