### ISSUE TITLE
Int instead of UUID?

### ISSUE THREAD

**Issue by f0rever-johnson** [FusionAuth/fusionauth-issues#13]
Is the insertInstant type supposed to be an INT or UUID for add user to group response API?

https://fusionauth.io/docs/v1/tech/apis/groups

![screen shot 2018-10-26 at 12 35 20 pm](https://user-images.githubusercontent.com/21150708/47580260-6d3fa780-d91c-11e8-9f58-cba5656475da.png)

**Comment by robotdan** [comment]
Damn @f0rever-johnson you are good. You are on the money, thanks for the find! Fixed!
