### ISSUE TITLE
Fusion Auth events indicating password reset flow

### ISSUE THREAD

**Issue by adoliver** [FusionAuth/fusionauth-issues#1308]
### Problem
Alerting on unusual user behavior around login is an early warning sign for our security team. A spike in resets could provide an early indication of malicious activity. Unverified resets could indicate a blast across many emails and a lack of successes could warn us of issues on the reset page.

Currently there is no way to track events:
* User initiating a password reset
* User loading password reset url
* User successfully changing their password

### Solution
We would like an set of events similar to user.login.success
* user.password.reset.sent (email sent)
* user.password.reset.verified (email link clicked)
* user.password.reset.success (reset success)

### Alternatives/workarounds
We can add tracking on each template page in the flow, but that relies on an untrustworthy client. The reset links need to be customized to identify a success flow for each user. And there are significant complications and complexity around users clicking on expired reset links and page reloads. Ultimately the client shouldn't be trusted for data used in security telemetry. An event for each user for each step of the flow would allow us to use typical usage to identify outliers and have our threat and response team respond.

**Comment by robotdan** [comment]
Related to https://github.com/FusionAuth/fusionauth-issues/issues/905, we may be able to add some of these events / emails under this feature.

**Comment by robotdan** [comment]
Here is what I'm thinking:

- `user.password.updated` - Sent when the User API modifies a password (not using the reset flow)
- `user.password.reset.started` - Forgot Password API was called / User initiated a reset workflow
- `user.password.reset.sent` - Email sent with a link or code (if using FusionAuth for email)
- `user.password.reset.success` - Password has been updated using the one time code

Would this work for you, or do you have any feedback on this proposal? I think it is pretty close to what you suggested.

**Comment by adoliver** [comment]
>     * Password has been updated using the one time code

That looks great. My only change would be I would still a expect user.password.reset.sent event if an external SMPT is set-up and that call received a 200 response. As an end-user I would need additional logging on the SMPT server to discover any failures or successes after the FA hands the email over to the SMTP server. (I think your description implied FA directly sending an email without a separate SMTP server)

**Comment by adoliver** [comment]
> Here is what I'm thinking:
> 
>     * `user.password.updated` - Sent when the User API modifies a password (not using the reset flow)
> 
>     * `user.password.reset.started` - Forgot Password API was called / User initiated a reset workflow
> 
>     * `user.password.reset.sent` - Email sent with a link or code (if using FusionAuth for email)
> 
>     * `user.password.reset.success` - Password has been updated using the one time code
> 
> 
> Would this work for you, or do you have any feedback on this proposal? I think it is pretty close to what you suggested.

That looks great. My only change would be I would still a expect user.password.reset.sent event if an external SMPT is set-up and that call received a 200 response. As an end-user I would need additional logging on the SMPT server to discover any failures or successes after the FA hands the email over to the SMTP server. (I think your description implied FA directly sending an email without a separate SMTP server)

**Comment by adoliver** [comment]
I lied, one more possible change.
For the sake of good user experience it would be useful to be able to identify any unusual drop-off between users clicking on the email or arriving on the password reset page and users who complete the password change form.
Not directly a security issue, but if user's ability to complete the flow changes its important to quickly identify where the problem is to keep up-time high. e.g. There may be a malfunctioning script(runtime error) or CSS(hiding form elements) added via template customization preventing a user from completing the form.

Maybe this event already exists in FA?

* `user.password.updated` - Sent when the User API modifies a password (not using the reset flow)
* `user.password.reset.started` - Forgot Password API was called / User initiated a reset workflow
* `user.password.reset.sent` - Email sent with a link or code (FA triggers email delivery)
* `user.password.reset.landed` - User arrives on reset password page. Or FA receives the reset token from the user. i.e. clicked on the email link.
* `user.password.reset.success` - Password has been updated using the one time code

**Comment by robotdan** [comment]
`user.password.reset.landed` this event may be tricky because it occurs as a result of a `GET` request generally. 

So if you refresh your page, the browser pre-fetches the request, or you go through a proxy that performs pre-checks like Cloud Flare, or M$ Safe links, the request may be pre-fetched before the actual user sees the page. This may lead to a bunch of emails unless we throttle it or keep track of how many times we send this during what we could guess is a "single" browser request. 

I suppose we could just keep track of the first time we do it to provide feedback that the user seemingly clicked on something. We can discuss it internally.
