### ISSUE TITLE
Unable to Retrieve Refresh Tokens issued to a User

### ISSUE THREAD

**Issue by f0rever-johnson** [FusionAuth/fusionauth-issues#1311]
My workflow is 
    1: Login User
    2: User Chooses Desired Application
    3: Get Correct RefreshToken/JWT for Application Chosen in step 2.

When I call the Retrieve Refresh Tokens API, I am receiving a response code of 200 but a blank body.

**Comment by jobannon** [comment]
@f0rever-johnson, 

Sorry to hear that you are having issues.  

> 3: Get Correct RefreshToken/JWT for Application Chosen in step 2.

> When I call the Retrieve Refresh Tokens API, I am receiving a response code of 200 but a blank body.

Can you confirm the API endpoint that you are attempting to hit?

I assume that it's one of the APIs outlined below, but specifics may be helpful.

https://fusionauth.io/docs/v1/tech/apis/jwt/

For instance,

```
DELETE /api/jwt/refresh?token={token}
``` 
returns a 200 code, with no response body.  I assume that you are not using this, but it would be helpful to confirm the endpoint that you are in fact touching.

> 1: Login User

Are you using the login endpoints for this?  Do you have the exact endpoint and data that you are using?

> 2: User Chooses Desired Application

What mechanism are you using to accomplish this? 

In general, more specifics may help us assist better.  Are you following any other guides on our website to create your application?  I will post back if I think of anything else.

**Comment by f0rever-johnson** [comment]
Currently I am testing functionality using Postman. I am not following any guides, just using the api endpoints as I see fit. Also I am using the swift client library which I wrote. 

> Can you confirm the API endpoint that you are attempting to hit?

I am attempting to hit GET /api/jwt/refresh using JWT Authentication. It returns a 200 code but with no response body. 
I am expecting to get a response with the the refresh token specific to the application so that I can refresh jwt tokens. 

> Are you using the login endpoints for this? Do you have the exact endpoint and data that you are using?

I am using the POST /api/login endpoint to login user. However I am not specifying an application as the user will be choosing which application to login into after successful authentication with fusionauth. 

> What mechanism are you using to accomplish this?
Not sure what you mean here. 
In the app:
     Once the user logs in, they are presented with a list of applications they have access to. 
     They then click on which one they want to use
     The app then loads the correct data based on the chosen application

**Comment by robotdan** [comment]
You must specify an applicationId on the Login API if you want a refresh tokens. 

Refresh tokens are always app specific. 

Also, by default the login API will not produce refresh tokens. You can enable this function in the UI by navigating to the security tab in application edit panel. 

Ensure “Generate refresh tokens” is enabled.

**Comment by f0rever-johnson** [comment]
So there isn't a way to get a refresh token outside of using the Login API?

**Comment by robotdan** [comment]
The refresh token is generated by the login API. You can retrieve existing tokens using the refresh token API.

**Comment by mooreds** [comment]
This feels like further discussion should take place on our forum https://fusionauth.io/community/forum/ (or, if you have a support contract, via a support ticket: https://account.fusionauth.io/account/support )

since this feels like a support discussion rather than a bug or feature request.

Closing.
