### ISSUE TITLE
In recent version of FusionAuth, Last login timestamp set as Created timestamp on user creation.

### ISSUE THREAD

**Issue by amanWebin** [FusionAuth/fusionauth-issues#1312]
### Description 
In Earlier version "1.6.1" when we created an user in FusionAuth then last login didn't set. it set when created user logged into system.
Now In "1.25.0" version, FusionAuth setting the last login timestamp same as created timestamp while creating the user. However, user still didn't verify his email and login. Which is giving the wrong impression in reporting.
Could you please resolve this issue ASAP.

### Affects versions
"1.25.0"

### Steps to reproduce
1. Go to FusionAuth Dashboard.
2. Go to users tab and create a new User.
3. Open the created user profile.
4. You can see the last login same as created date.

### Expected behavior
Last login should not be set. Attaching earlier version screenshot.

### Screenshots
![qa14-new-fusionAuth](https://user-images.githubusercontent.com/87710621/126343457-d2c75b26-d7d1-4888-b589-fe9714ff2fb1.png)
![qa8-old-fusionAuth](https://user-images.githubusercontent.com/87710621/126343464-e0c24fa2-821b-44b1-9272-b00bb4aad887.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: All
 - Browser + version All
 - Database Mysql

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
This is working as designed, it is a change from version 1.6.1 which you are comparing. 

When a user is created we count this as a login event because we create a JWT and collect credentials. This allows an integrator to collect credentials, create a user and log the user in automatically w/out prompting the user again.

**Comment by joeyenfield-verint** [comment]
Hey @robotdan  - Just on this issue, we have come across this issue too. We are trying to see how we can identify if a user has not logged in yet, as the last login is always set to some date - is there any other way to identify if a user has not logged in yet?

**Comment by mooreds** [comment]
@joeyenfield-verint 

We don't regularly monitor closed GH issues. The best way to ask questions like this is to reach out through the appropriate support channel.

If you are on an plan with support: https://account.fusionauth.io/account/support

If you have community support: https://fusionauth.io/community/forum/

Feel free to reference the GH issue if that's helpful. Thanks!
