### ISSUE TITLE
Login lambda

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1318]
### Problem

I want more granular control over whether a user is able to login or not based on current profile info, things like age, MFA enabled, etc.

### Solution

Create a new lambda (maybe a 'login processor') which runs before the JWT is populated and must succeed for a login to complete. If the lambda fails, render the login failure screen. Perhaps even make the return value of the lambda two items:

* success/failure
* a message key for display to the end user (actual value pulled from the theme messages file)

### Alternatives/workarounds

Here's the current best alternative, where you push the values to the JWT and check in the application: https://fusionauth.io/community/forum/topic/1159/enforcing-attributes-on-a-user

If I throw an exception from the `user.login.success` webhook handler and have the appropriate transaction settings, I block login, but the error message isn't customizable.

### Additional context

Would be really powerful when combined with https://github.com/FusionAuth/fusionauth-issues/issues/267

### Related
* https://github.com/FusionAuth/fusionauth-issues/issues/969
* https://github.com/FusionAuth/fusionauth-issues/issues/1282
* https://github.com/FusionAuth/fusionauth-issues/issues/1781
* https://github.com/FusionAuth/fusionauth-issues/issues/1914

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
Had a customer mention this would be useful in the context of an IdP (stopping a login based on external information, obtained by an API call from https://github.com/FusionAuth/fusionauth-issues/issues/267 ).

**Comment by LasseJacobs** [comment]
@mooreds for us (we are FusionAuth customers) this would also be helpful. We are mainly interested in having the ability to block the login process during JWT token populate lambda. But if an alternative flow is available as you mention here that would also be OK.

Feel free to reach out if you want more details on our use-case.

**Comment by mooreds** [comment]
Thank you @LasseJacobs . Happy to hear about your use case. If you'd like to drop details here, that's preferable. 

Otherwise, feel free to send me an email (dan at fusionauth.io) and I'll make sure it is routed to the engineering team.

**Comment by robotdan** [comment]
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1282? Seems essentially identical.

**Comment by mooreds** [comment]
Yes, not sure why I filed this 2x.

Closing, thanks.
