### ISSUE TITLE
Allow Verify Email API to verify a user w/out a verificationId

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1319]
### Problem
There is not a way to mark a user as having a verified email w/out making the user go through the email verification process. In general this is preferred, but in some cases an admin may wish to mark a user as having a verified email. 

### Solution
We should add this option to the existing API and then add this action to the admin UI. 

### Alternatives/workarounds
Make the user verify their email. 

Edit the database value directly and re-index if using elasticsearch (not recommended).

### Additional context
N/A

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/285
- https://github.com/FusionAuth/fusionauth-issues/issues/801
- https://github.com/FusionAuth/fusionauth-issues/issues/821
- https://github.com/FusionAuth/fusionauth-issues/issues/1689
- https://github.com/FusionAuth/fusionauth-issues/issues/1690

### Docs
- [ ] Admin UI "Verify email address" option on User page
- [x] `POST /api/user/verify-email` new `userId` request option
- [x] Update `user_support_manager` special role description/permissions on [Roles](https://fusionauth.io/docs/v1/tech/core-concepts/roles) page

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by jobannon** [comment]
related: https://fusionauth.io/community/forum/topic/1158/mark-email-as-verified

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-client-builder/pull/45
- https://github.com/FusionAuth/fusionauth-java-client/pull/30
- https://github.com/FusionAuth/fusionauth-api/pull/53
- https://github.com/FusionAuth/fusionauth-app/pull/119

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-client-builder/pull/45
- https://github.com/FusionAuth/fusionauth-java-client/pull/30
- https://github.com/FusionAuth/fusionauth-api/pull/53
- https://github.com/FusionAuth/fusionauth-app/pull/119

**Comment by alex-fusionauth** [comment]
Reopened as this has not solved
