### ISSUE TITLE
Should an identity provider be associated with an application

### ISSUE THREAD

**Issue by scopendo** [FusionAuth/fusionauth-issues#132]
### Description
When adding a new identity provider within FusionAuth, we specify the client id and secret allocated by the identity provider, which feels like it would be application-specific.  Given that, would it make sense to be able to associate the FA identity provider with the FA application that it is set up for?

**Comment by scopendo** [comment]
Closing as this was my misunderstanding of how the setup worked.

**Comment by robotdan** [comment]
Thanks for opening the question @scopendo. It looks like you've worked this out already. 

Each Identity Provider configuration has a global configuration that can be used for any application that wishes to use it. Then each application has the option to override some or all of the IDP settings. 

In the case of OpenID Connect, you could either create a new IDP configuration for each use case that is tied to an application, or create a single configuration and override the client Id and client secret per application. 

https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect

Hope that makes sense, feel free to ask any additional questions about how these are configured. Thanks!
