### ISSUE TITLE
Login with Github as IdP fails due to redirect URI mismatch

### ISSUE THREAD

**Issue by scopendo** [FusionAuth/fusionauth-issues#134]
### Description
An OpenID Connect identity provider has been added for logging in with Github and enabled for my application (running on localhost).  After authenticating with Github, a redirect URI mismatch error occurs.

This appears to be because I added an OAuth2 application within Github with redirect URI:

http://localhost:8080/login/xxx

But when FusionAuth redirects to Github, it passes the redirect URI as:

http%3A%2F%2Flocalhost%3A8080%2Flogin%2Fxxx

I have verified that Github authentication works fine if I invoke it directly from my app (Spring OAuth2) rather than going via FusionAuth.  In this case the redirect URI is passed unencoded.

Not sure whether this is an issue with FusionAuth or for Github with how they match the URI.  Unfortunately, Github requires the redirect URI to be specified.

**Comment by robotdan** [comment]
The redirect you'll want to register with GitHub will be FusionAuth, not your own application. The correct redirect is `http://localhost:9011/oauth2/callback` - assuming that FusionAuth is running at `http://localhost:9011`. 

However, as far as I know, GitHub does not support OpenID Connect, they have their own custom OAuth2/OIDC like implementation. 

For this reason, I think the only way this will work is for FusionAuth to support an OAuth2 Identity Provider, or implement a GitHub typed IDP.  ([Login with GitHub Feature #33](https://github.com/FusionAuth/fusionauth-issues/issues/33))

Their "OAuth" token response does not default to JSON, so it looks like our OpenID Connect code would need a little work to play nicely with GitHub.

**Comment by robotdan** [comment]
With a few hacks to our OIDC IDP I got GitHub to nearly complete the authentication request. However, using the claims they return on the `https://api.github.com/user` endpoint I do not see an email address regardless of the scope I request. 


Without an email address we cannot complete login. GitHub is just too far out of spec to make it work using OIDC.

**Comment by scopendo** [comment]
That's fair enough, thank you for checking. It was only for testing an
OAuth2 flow in my test app versus configured as an IDP in FusionAuth.

Good to see the proper redirect Uri, which I didn't see in the
documentation, but may have overlooked. Might be worth showing on the IDP
screen.

**Comment by robotdan** [comment]
>  Might be worth showing on the IDP screen.

This is an excellent idea. In the next release of FusionAuth we'll be adding these "integration" fields wherever we can to make it simpler to understand what values to put where. 

Here is an example screenshot of an OIDC config for the upcoming release. 

![image](https://user-images.githubusercontent.com/1148709/56459193-3edfd980-634d-11e9-880d-89e34635c534.png)

**Comment by robotdan** [comment]
I got GitHub working with our OpenID Connect IdP using a Lambda. This will be available in version 1.6.0. 

I'll document my configuration once this is available.

**Comment by robotdan** [comment]
This will work now in FusionAuth 1.6.0, let me know if you run into issues. The user logging in will need to have their email public for this to work. 

You can use the Lambda for OpenID Connect reconcile if you want to do anything custom with the user object returned by GitHub. 

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

**Comment by gmpreussner** [comment]
@robotdan Is this documented yet? I've tried to get it to work today with just a regular OpenID provider configured. It almost works all the way through, but fails in the end after GitHub redirects to FusionAuth, the latter of which shows a 404 not found.

How did you make this work with a lambda?

**Comment by robotdan** [comment]
Hi @gmpreussner  - not documented yet... hopefully soon.  

Here is my config (minus the client id and secret)

![image](https://user-images.githubusercontent.com/1148709/59323072-56c14300-8c96-11e9-8631-0d15b42faa5e.png)

You only need to use a lambda if you want to pull anything else out of the GitHub user than the email address.  https://developer.github.com/v3/users/

If you want help with that let me know. 

When you say you see a `404` do you mean the GitHub 404 page like this? 
![image](https://user-images.githubusercontent.com/1148709/59323116-88d2a500-8c96-11e9-9b47-0376857d7a9e.png)

I don't know why this happens exactly, but I've seen it before with GitHub. When I have seen it, I reset my client secret in the GitHub Developer settings and then it works again. 

`GitHub --> Developer Settings --> OAuth Apps --> Reset client secret`

Let me know if that gets you up and going.

**Comment by gmpreussner** [comment]
@robotdan Thanks for the quick response! That is the same configuration I have. I'm actually getting a 404 in my application (Phabricator), not in FusionAuth - sorry for the confusion. Other OAuth2 providers I've tried work fine, but GitHub doesn't. I'll debug this some more. For now, let's assume that this is not a FusionAuth issue. I'll keep you posted.

**Comment by robotdan** [comment]
Ok, sounds good. If you want a hand with any of it - feel free to join the FusionAuth Slack channel. (see link on https://fusionauth.io/ )

GitHub is a bit non-standard -so it could have something to do with how we build the user from the details returned by GitHub. If you can narrow it down to what is or isn't in the FusionAuth user that may be causing a problem in your application I can help you with a Lambda to fix that. 

Feel free to jump on slack or open a separate GitHub issue if there is anything else we can help with.

**Comment by gmpreussner** [comment]
I resolved the issue on my end. As expected, it had nothing to do with FusionAuth.

My application had two problems: 1) it generated an incorrect callback URL, which caused the 404 in the application, 2) it requested user information by sending the auth token via an 'access_token' query parameter instead of an 'Authorization: Bearer xxxxx' HTTP parameter that FusionAuth expected. After fixing these, authentication works as expected.

**Comment by Hurtak** [comment]
For anyone encountering this issues this comment helped me https://github.com/MomenSherif/react-oauth/issues/12#issuecomment-1231202620
You put `redirect_uri: "postmessage"` to the fusion auth login url `/api/identity-provider/login`

**Comment by robotdan** [comment]
Thanks @Hurtak for the contribution!!
