### ISSUE TITLE
Apple Sign In

### ISSUE THREAD

**Issue by Ivona221** [FusionAuth/fusionauth-issues#1340]
### Description
I have an issue getting a authentication token when trying to sign in with apple. I have the following configuration in the fusion auth:
<img width="1017" alt="AppleKey" src="https://user-images.githubusercontent.com/29552039/128887500-5d063a44-7f0d-443f-bcac-be5377c8e218.png">
<img width="850" alt="CORS" src="https://user-images.githubusercontent.com/29552039/128887502-c4ed7a5f-1b00-41f0-9810-c30a65c74949.png">
<img width="1114" alt="FusionAuthApple" src="https://user-images.githubusercontent.com/29552039/128887505-7d0f6a39-49c0-4c00-9ec2-91bfa5726e55.png">

I am sending the following request to fusion auth and I am constantly getting this error:
![image](https://user-images.githubusercontent.com/29552039/128888384-f8a165d1-115a-4aae-a3e3-de191a054bd2.png)

Any idea what the issue could be? Thank you in advance for your help.

**Comment by jobannon** [comment]
@Ivona221  I can attempt a recreate.  In the meantime, you may want to review our existing documentation for the Apple identity provider type (if you have not already).

https://fusionauth.io/docs/v1/tech/identity-providers/apple/
https://fusionauth.io/docs/v1/tech/apis/identity-providers/apple/#overview

The first link will be using the admin UI, so things may be slightly different than via API.  However, the procedural steps should remain the same.

**Comment by robotdan** [comment]
If there is additional discussion required we should move it to the community forum.

**Comment by mooreds** [comment]
Here's the link for the community forum: https://fusionauth.io/community/forum/

Please feel free to continue discussion there.

Closing.
