### ISSUE TITLE
Certain users are having their changePasswordId's expiring prematurely and their assigned password not working

### ISSUE THREAD

**Issue by Jlintonjr** [FusionAuth/fusionauth-issues#1343]
### Description 
We are seeing a couple hundred users who are experiencing this same issue. We create users via the FusionAuth .NET client, and give the users a valid temporary password. We then generate a forgot password link (via the `changePasswordId` from the `ForgotPasswordAsync` method) which we email out to the user allowing them to click the link, change their password, and log into our system.

This has been working for most users, but we have a handful of users who it isn't working for. Both their temporary password does not work and the url for the changePasswordId expires before its 30 day expiration date which we set in the tenant settings. We do not know of any consistency in how quickly they expire, but we've seen it expire within an hour or two.

We are currently not able to see if there is any correlation between these users in how we input them with FusionAuth's api - it seems random as we will have a batch with 500 created and 3 users experience this. 

There is a common trait among these users in the FusionAuth ecosystem. In the manage user's page under source, they are missing the `passwordChangeReason` variable. This variable is returned when you fetch the user via the API, and the value is `Administrative`. This variable is present under the source section for users who are OK.

### Affects versions
1.29.3

### Steps to reproduce
We are not able to reproduce this at this time as the instances seem random, but the number of these cases are growing steadily. There are commonalities in the data between these users as mentioned above.

### Expected behavior
That the assigned passwords would work and the forgot password links would not expire before they are supposed to

### Screenshots
Problem User:
![image](https://user-images.githubusercontent.com/11423675/129075266-e2593439-93d7-4e76-8169-4d17b21f0444.png)

OK User:
![image](https://user-images.githubusercontent.com/11423675/129075151-0632a1bb-bf92-4aaa-8137-7c276badaf48.png)

### Platform
Any browser, any device.

**Comment by robotdan** [comment]
Do you know how you got a user into a state where they have a `passwordChangeReason` value defined and `passwordChangeRequired` is `false`? 

I think the only way to get that to work is to import a user with `passwordChangeReason = "Administrative"` and `passwordChangeRequired = false`. I don't know that it should matter, but it looks like we should be setting the reason to `null` during import unless `passwordChangeRequired = true`.

**Comment by Jlintonjr** [comment]
During our data import we would set the `passwordChangeRequired` based on some criteria, but we had never set the `passwordChangeReason` value, that was always omitted. 
We have also seen a few of these cases where we are setting the `passwordChangeRequired` to be true (during import or user creation), but the value is false when we look at the source json. I am not aware of any other process that was updating these users that could have changed that from the outside. Are there any conditions internally that could flip that back to being false?

**Comment by robotdan** [comment]
A few release ago we updated the import API to set the `passwordChangeReason` to `Administrative` if it was not otherwise provided on the Import Request. 

But prior to that you are correct, if it was omitted, it would remain `null`. 

We do set `passwordChangeRequired` equal to `false` when the user changes their password, in this case we also delete any outstanding tokens that could be used as the `changePasswordId`.  

But from your description, the user has not set their password and simply cannot log in with a previously set password, and their `changePasswordId` that was sent in an email does not work (seemingly prior to the configured timeout). 

What is your configured timeout?

**Comment by robotdan** [comment]
Thanks @Jlintonjr I opened a support ticket on your behalf and we can discuss there.

**Comment by robotdan** [comment]
I believe this was resolved via the support ticket. Please re-open if this is still an outstanding issue.
