### ISSUE TITLE
Self service registration form is breaking the user's current password

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-issues#1344]
### Description 
When self service registration is enabled for an application and the user is missing a required field, the users password is "invalid" after the self service form has been submitted. 

### Affects versions
v1.28.0 - v1.29.2

### Steps to reproduce
1. Use a user with a valid password and the mobile phone field empty.
2. Create an application with self service registration enabled and a mobile phone as a required field.
3. Log into the application with the user.
4. Enter the missing mobile phone number in the self service registration form.
5. Submit the form.
6. Log out of the application.
7. Log back in, you will receive an "invalid login" error. This happens wil all other applications as well.
8. Only way to remedy this situation is a password reset.

### Expected behavior
Submitting the self registration form should not impact the user's password.

### Screenshots
<img width="459" alt="Screen Shot 2021-08-11 at 22 34 30" src="https://user-images.githubusercontent.com/1012764/129129827-e1d10012-167e-4b4e-bd6d-90f68df08f99.png">

<img width="417" alt="Screen Shot 2021-08-11 at 22 45 22" src="https://user-images.githubusercontent.com/1012764/129130735-5cb66bac-fde4-4fd1-b2c9-edf38a8680d6.png">

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Chrome 92.0.4515.131
 - Database: MySQL 5.7.33

### Additional context
I believe this used to work fine in FusionAuth v1.29.0

This issue only occurs when the self registration form is submitted. In case all required fields are already filled the form is skipped, the user is registered to the application and all works as intended.

I tested with a custom theme and with the build-in theme, there was no difference in behavior.

**Comment by robotdan** [comment]
I have been unable to recreate. Are there any other details you can provide? 

Here is what I did:

1. Create a user with email and password only. 
2. Enable self-service registration with first name, last name and mobile phone fields enabled. Only mobile phone is marked as required. 
3. Log in with user created in step 1. 
4. Stop in complete-registration and enter first name, last name and mobile phone. 
5. Login completes.
6. Log out
7. Log back in with known password

I tried this with basic and advanced registration forms, both worked. I also wrote a test to replicate this workflow and it worked at 1.29.2 and 1.30.0 (pre-release). 

If you are using your own theme, can you try to recreate with the "stock" theme and see if the same symptom occurs?

**Comment by robotdan** [comment]
Thanks @flangfeldt - I think I have a recreate.

**Comment by robotdan** [comment]
1.29.4 is out with this fix, let me know if that solves it for you. Thanks for reporting.

**Comment by flangfeldt** [comment]
Hi @robotdan, I can confirm that 1.30.0 fixes the issue. I have not tested 1.29.4, but if you want me to I can still do it.

**Comment by robotdan** [comment]
Thanks for confirming. No need to test 1.29.4, I was able to confirm with a test.
