### ISSUE TITLE
startup.bat doesn't start FusionAuth

### ISSUE THREAD

**Issue by yujiberra** [FusionAuth/fusionauth-issues#1345]
### Description 
Running startup.bat, either from a CMD window or Windows Explorer, makes a CMD window pop up shortly and then disappear.

### Affects versions
1.29.3 
It might be a good idea to add an easy way to tell what version of FusionAuth you have without being able to run it. If I wasn't able to work around this issue I would have had no idea how to figure out the version number.

### Steps to reproduce
Per the instructions in the [5-Minute Setup Guide](https://fusionauth.io/docs/v1/tech/5-minute-setup-guide/), install FusionAuth with `. { iwr -useb https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.ps1 } | iex; install` and then run `startup.bat`.

### Expected behavior
FusionAuth would start

### Platform
(Please complete the following information)
 - Device: PC
 - OS: Windows 10
 - Browser N/A
 - Database N/A

### Additional context
I was eventually able to work around this issue and figure out which Java installation to run with what command-line arguments in order to start FusionAuth, and in that process I was able to figure out some of the problems with `statup.bat`:

- `FUSIONAUTH_JAVA_DIR` is set but is never used, so even if the batch file worked catalina.bat would just use the system's version of Java
- The `%~dp0` in `Powershell.exe -executionpolicy ByPass -File %~dp0..\fusionauth-app\apache-tomcat\bin\install_java.ps1` doesn't get parsed correctly by Powershell, even if you run this command in CMD.

That's not all (I think there are additional issues with the `START "fusionauth-app" /D %~dp0..\fusionauth-app\apache-tomcat\bin catalina.bat start` line) but hopefully that helps.

**Comment by robotdan** [comment]
I think this may be resolved by https://github.com/FusionAuth/fusionauth-issues/issues/1624. 
https://github.com/FusionAuth/fusionauth-issues/issues/1624#issuecomment-1076778930

Can you confirm you still see this problem with the latest version and the changed suggested in the above links?

**Comment by robotdan** [comment]
Assuming this is resolved vi #1624 . Please re-open if it is not.
