### ISSUE TITLE
Possible change to Existing Google IdP login

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1347]
### Description

From a Forum User:
> Received a notification from Google that they're discontinuing Google Sign-In JavaScript Platform Library for web > (https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html). They provided us "a list of your client ID(s) that use the legacy Google Sign-In web solution" and the only item was the client id we set up for FusionAuth's Google identity provider.

> Will this affect the Google identity provider in FusionAuth, and if so, is it on the roadmap to be updated?

see post 
https://fusionauth.io/community/forum/topic/1208/does-deprecation-of-javascript-google-platform-library-affect-fusionauth-google-identity-provider

👉🏻  **_Review to see if we are using associated JS libraries and migrate if we are_**

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
The preferred integration is using the auth code grant ( mode = redirect) in our config. This method does not use JS.

**Comment by wodka** [comment]
is there a way to use the auth code when logging in through an api request?

**Comment by mooreds** [comment]
@wodka please post in the [community forum](https://fusionauth.io/community/forum/) with your question, or opening a [support ticket](https://account.fusionauth.io/account/support/) if you have a plan with support.
