### ISSUE TITLE
Can't delete keys in Key Master

### ISSUE THREAD

**Issue by DavidHaerer** [FusionAuth/fusionauth-issues#1351]
### Description 
If I create a signing key in the Key Master, I am unable to delete that key.

### Affects versions
* Version 1.27.2

### Steps to reproduce
1. Go to 'Settings > Key Master'
2. Click on 'Generate Elliptic' to create a new key.
3. Click on 'Delete' for the new key
4. Click on 'Submit' to confirm the delete.
5. See error 'FusionAuth encountered an unexpected error. Please review the troubleshooting guide found in the documentation for assistance and the available support channels.'

### Expected behavior
Clicking submit for the delete action should remove the key.

### Screenshots
![FusionAuth Key Master 1](https://user-images.githubusercontent.com/85242556/129870426-f598bb15-5169-48b5-9c92-a7136cd140ac.PNG)
![FusionAuth Key Master 2](https://user-images.githubusercontent.com/85242556/129870464-e8c4fadf-706a-4299-96e6-65b3dfe69b07.PNG)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows
 - Browser + version Brave Version 1.28.105 Chromium: 92.0.4515.131

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
FusionAuth is running in the Cloud (not self-hosted).

**Comment by robotdan** [comment]
Thanks for the report. To cause is because the key is in use by an entity type. If you remove the entity type configuration for this key, then you will be able to delete it. 

We'll fix the message in the upcoming patch release.

**Comment by DavidHaerer** [comment]
Thanks, deleting the entity type solved the issue :)
