### ISSUE TITLE
Lambda Tagged with "Client Credentials JWT Populate" Not Appearing in Application JWT Section

### ISSUE THREAD

**Issue by browniefed** [FusionAuth/fusionauth-issues#1353]
### Description 
When creating a a lambda to populate custom claims into a token selecting `Client Credentials JWT Populate` does not cause it to appear when trying to select it when creating/editing an Application JWT Section

### Affects versions

1.30.0
--

### Steps to reproduce
1. Go create a lambda with `Client Credentials JWT Populate`
2. Go create an application and enable JWT
3.  Try and add a lambda to populate claims.

### Expected behavior
I'd expect to be able to select the Lambda to populate my cliams.

### Screenshots

<img width="1587" alt="Screen Shot 2021-08-19 at 4 31 06 PM" src="https://user-images.githubusercontent.com/1714673/130156972-5548e0d1-04e0-4e9a-886a-2186556368ea.png">
<img width="1562" alt="Screen Shot 2021-08-19 at 4 30 38 PM" src="https://user-images.githubusercontent.com/1714673/130156975-ee61d041-ec0b-4200-aab6-dbe0e8feb2cf.png">

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Chrome Version 92.0.4515.159 (Official Build) (x86_64)
 - Database PostgresSQL 12

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by browniefed** [comment]
If I edit the `Select` when creating it to be tagged as `JWT populate` instead it will appear correctly in the list.

**Comment by robotdan** [comment]
This is working as designed. The client credentials lambda is only for use by the client credentials grant. 

The client credentials grant is implemented using entities.

See entity management and client credentials grant doc. 

https://fusionauth.io/docs/v1/tech/oauth/endpoints/

https://fusionauth.io/docs/v1/tech/core-concepts/entity-management/

**Comment by browniefed** [comment]
@robotdan but then there is no JWT Populate option. There is only the client credentials jwt populate.

There is no way to add a lambda that will appear on the application jwt section as described in all the documentation

**Comment by browniefed** [comment]
Don't mind me, I am just so wrong. Apologies. I didn't see it in the list and now I do.

**Comment by browniefed** [comment]
@robotdan thank you, apologies for filing a bad bug report.

**Comment by robotdan** [comment]
Ha.. no problem @browniefed thanks for using FusionAuth!
