### ISSUE TITLE
Cannot set user.username from Google reconciliation lambda

### ISSUE THREAD

**Issue by alapins** [FusionAuth/fusionauth-issues#1356]
### Description 
Cannot set user.username from Google reconciliation lambda

### Affects versions
1.29.0 

### Steps to reproduce
1. add user.username = user.firstName+user.lastName; to the default Google reconciliation lambda
3. log in using a google account where that google account has not logged in before, and no user in fusionauth exists for that google account
4. check the new user through the UI; no username is set

### Expected behavior
the username should be set to the concatenation of firstname and lastname

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
I should be able to set the username.  I've also tried setting user.userName (although that's not what the docs say it should be).  I'm assuming that the user.username will carry through to the user.registration.username and that if the username is already in use, it will add a number per the specification I've set in the application.  Additionally, although I've turned on debugging, I am not seeing anything put into the logs, though I've uncommented console.info.  here's the full lambda:

// This is the default Google reconcile, modify this to your liking.
function reconcile(user, registration, idToken) {

  // Un-comment this line to see the idToken object printed to the event log
  // console.info(JSON.stringify(idToken, null, 2));

  // The idToken is the response from the tokeninfo endpoint
  // https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint
  console.info('Google User Object-------------------------');
  console.info(JSON.stringify(idToken, null, 2));
  user.firstName = idToken.given_name;
  user.lastName = idToken.family_name;
  user.fullName = idToken.name+"(really)";
  user.username = user.firstName;
  user.userName = user.lastName;
  user.imageUrl = idToken.picture;
  console.info('User Object-------------------------');
  console.info(JSON.stringify(user, null, 2));
  console.info('Registration Object-------------------------');
  console.info(JSON.stringify(registration, null, 2));

}

**Comment by jobannon** [comment]
Hi @alapins 

We can continue this conversation in the forum post as the forum is more conductive to integration issues such as this.
https://fusionauth.io/community/forum/topic/1230/cannot-set-user-username-from-google-reconciliation-lambda

### The short version
> The user.email field on the user will be ignored if modified by the lambda function. This is to protect the integrity of the email claim returned by the identity provider.

> The user.username field on the user will be ignored if modified by the lambda function. This is to mitigate the risks of an account takeover due to a non globally unique identifier.

_from_ https://fusionauth.io/docs/v1/tech/lambdas/google-reconcile/#limitations
