### ISSUE TITLE
Test events for webhooks don't match real events

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1360]
### Description 

The real events FusionAuth sends don't match the test events completely.

### Affects versions

1.30

### Steps to reproduce

* Navigate to home -> settings -> webhooks in the admin ui
* Add a webhook (doesn't matter what it does)
* Go back to the webhook list view
* Click the 'test' button
* Scroll through the list of events. Some (audit log being one) don't match up with the docs listed in https://github.com/FusionAuth/fusionauth-site/pull/890

### Expected behavior

Test events match documentation.

### Platform
n/a

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Relevant doc PR: https://github.com/FusionAuth/fusionauth-site/pull/890

Internal slack convo: https://inversoft.slack.com/archives/C0407G6V5/p1629734183005200

**Comment by robotdan** [comment]
Is this a doc issue?

**Comment by mooreds** [comment]
No, the test events (in the admin ui) are out of sync with reality (as defined by fusionauth-java-client). After https://github.com/FusionAuth/fusionauth-site/pull/890 is reviewed and merged, the docs should be up to date.

**Comment by robotdan** [comment]
Hmm.. ok. I guess I'll have to take a look, not sure how that is possible. The test events in the UI are serialized versions of the Java objects. 

If that is the case, there must be a bug in the code where we are serializing the wrong event for a particular example.

**Comment by mooreds** [comment]
Here's an example. This is the audit log entry from sandbox.fusionauth.io when I test a webhook.

```
{
  "event" : {
    "auditLog" : {
      "data" : { },
      "insertInstant" : 1629904919002,
      "insertUser" : "user@fusionauth.io",
      "message" : "Audit Log "
    },
    "createInstant" : 1629904919002,
    "id" : "0dacf4f0-e93f-4efe-ad32-87f93de16946",
    "info" : {
      "ipAddress" : "73.14.174.244",
      "userAgent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
    },
    "tenantId" : "bafb4319-b7ca-ed27-fa2f-bbdba9d8ec06",
    "type" : "audit-log.create"
  }
}
```

There is no `newValue` or `oldValue` in this, but those are attributes here: https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/java/io/fusionauth/domain/AuditLog.java

**Comment by bguyza** [comment]
@robotdan , @mooreds 
The test webhooks events are indeed serialized versions of the java objects, but in most (if not all cases), using a minimal set of attributes defined.  

Here is a PR that updates the `Audit Log Create` test event to include mock data simulating a User update event:
https://github.com/FusionAuth/fusionauth-app/pull/87

For this issue, do we want to review all events (38 of them I think) and add more data where appropriate? 

As these are intended for testing only, I don't think the level of work necessary to do that is necessary.  Thoughts?

**Comment by mooreds** [comment]
Hmm. So you are saying that the JSON we provide in the UI for testing isn't going to be a complete object and may be missing fields that are documented and will be present in the real events? 

Cause that is the 'testing' I'm concerned about: the user facing JSON shown in the UI. I see your PR references automated tests, but that isn't what this bug is about. Sorry if I was unclear.

**Comment by robotdan** [comment]
> Hmm. So you are saying that the JSON we provide in the UI for testing isn't going to be a complete object and may be missing fields that are documented and will be present in the real events?

Sort of - it looks like @bguyza has a PR to add the `oldValue` and `newValue` to this particular event. 

But the `oldValue` and `newValue` are optional fields, and may or may not be present in any particular audit log. The values are also free form, so when FusionAuth creates an Audit Log, it may contain an application or user, but it could contain just about anything. 

So I wouldn't say they are not not complete, they are not required fields. The audit log example in this Tester is complete, and valid, but it is possible it could contain additional fields. This would be true for most any event, each event may contain a user, application, or eventInfo, and depending upon the event at runtime, the user, application or event info may contain different values.

Does that help, or am I missing something yet?

**Comment by mooreds** [comment]
I think it helps. From my perspective, I want the test events that I as a user can use to exercise the webhook I might be writing to be as close to the real event as possible. I understand we can't offer every possible permutation but it seems we could offer as much as the sample json in the docs do. Or at least try to offer the important facets of each event.
