### ISSUE TITLE
Distinguish in doc, API error and admin messages between functionality for different licenses

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1365]
### Description 

We used to have two levels of licensing:

* community edition
* everything else

As of 1.30, we now have three levels of licensing

* community edition
* developer/premium
* enterprise

Since advanced threat detection is only for enterprise edition licenses.

### Affects versions
1.30

### Steps to reproduce

* get a developer edition license
* try to enable a 'user.password.update' webhook
* you'll receive an error stating that you need a reactor license

### Expected behavior

We should document:
* in the doc
* in the API error messages
* in the admin UX

either:
* this feature is not licensed for your edition
* you need 'X' edition for this feature

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1555

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

https://fusionauth.io/community/forum/topic/1235/how-to-enable-user-password-update-webhook

**Comment by robotdan** [comment]
I think this was resolved via https://github.com/FusionAuth/fusionauth-issues/issues/1555 ?

The product doesn't know about "editions", so the best we can really say is "not licensed" or "not licensed for feature x". We may be able to enhance this in the future if we start returning the edition meta data in the license.  We could keep this open to track that future feature and then the ability to provide better messaging in context of the license metadata.

**Comment by mooreds** [comment]
As long as we have 'not licensed for feature X', I'm okay with closing this issue, since folks can go to this page https://fusionauth.io/docs/v1/tech/core-concepts/editions-features and see the list of features and what edition or plan they need to be on.

**Comment by robotdan** [comment]
Ok. If you're ok with the current messaging, let's close this. I'd actually prefer not to have the messaging know anything about the license tier/edition because that provides us the option to move features between tiers over time if we want to graduate features down into low editions w/out worrying about error messages or product code.

**Comment by robotdan** [comment]
Closed by https://github.com/FusionAuth/fusionauth-issues/issues/1555
