### ISSUE TITLE
"activate" field is not updated via the user update API

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#137]
### Description 
we are trying to lock a user from the user API

<img width="980" alt="Screen Shot 2019-04-21 at 3 36 24 PM" src="https://user-images.githubusercontent.com/1580512/56469483-7a60cd80-644b-11e9-9215-ae52f44bdcf7.png">

as you can see, if we send `active: false`, the API will return `active: true`.

Is it the correct way to lock a user from the API?

**Comment by robotdan** [comment]
To make a user "inactive" is to soft delete the user. The UI calls this locking the account. 

https://fusionauth.io/docs/v1/tech/apis/users#delete-a-user

You want to use the delete API which by default will soft delete.

**Comment by blanchonvincent** [comment]
Thank you for the answer.
By the way, what is `active` field if it is not the lock?
Also, the PHP client does not have any method to soft-delete, any chance to add it?

**Comment by robotdan** [comment]
I apologize if I confused you, the `user.active` value does indicate the user is locked. However you cannot modify it using the Update User API. 

The PHP library does already have these methods, here are the ones you're looking for.


```
  /**
   * Deactivates the user with the given Id.
   *
   * @param string $userId The Id of the user to deactivate.
   *
   * @return ClientResponse The ClientResponse.
   * @throws \Exception
   */
  public function deactivateUser($userId)

  /**
   * Reactivates the user with the given Id.
   *
   * @param string $userId The Id of the user to reactivate.
   *
   * @return ClientResponse The ClientResponse.
   * @throws \Exception
   */
  public function reactivateUser($userId)
```

- `deactivateUser` - Lock user (change `active` value from `true` to `false`
- `reactivateUser` - Unlock user (change `active` value from `false` to `true`

This is equivalent to locking and unlocking the user in the UI.

**Comment by blanchonvincent** [comment]
ok everything make sense now.

Thank you!
