### ISSUE TITLE
How do I get my technical tutorials to be published

### ISSUE THREAD

**Issue by Newton-cyber** [FusionAuth/fusionauth-issues#1384]
Please consider posting your question on the [FusionAuth forum](https://fusionauth.io/community/forum/).

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
@Newton-cyber can you give us more details? Are you looking to write technical blog posts for FusionAuth?

**Comment by Newton-cyber** [comment]
@mooreds 
Am a full stack developer with background experience in technical writing, for knowledge enhancement and for software solutions. I would like to write technical blogs for you to help the community members adversely. I am looking forward to working with you through the entire process of editing. Thank you in advance

**Comment by Newton-cyber** [comment]
Thanks. Looking forward to working you
