### ISSUE TITLE
ApplicationId may be missing from a login record after completing a SAML v2 Login via SSO

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1387]
### Description 
It is unclear if this has anything to do with SAMLv2, etc - but the symptom was observed that after an SSO login via SAML v2 the login record was missing the `applicationId`. 

Workflow:
1. Start at FusionAuth, click "login with SAML v2" button
2. Login via FusionAuth SAML v2 IdP (separate FusionAuth instance than step 1).
3. Redirect and complete login to FusionAuth. 
4. View login records on the FusionAuth instance owning the SAML v2 IdP config from step 2 and we see a login record is missing the `applicationId`. 

It is possible this is related to the performance work done in `1.30.1`. In this release we moved the processing of the login records to an async processor. We would ensure we are not losing the `applicationId` along the way, and verify the business logic of determining if we need to record the `applicationId` on the login record.  

### Affects versions
TBD.

### Expected behavior
We should always have an `applicationId` in the login record when completing login via SAML v2 / OAuth2.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
I think this is working as designed. If you are not registered for an app, we will complete authentication as "Authentication Not Registered". In this case, we will record a login record w/out an applicationId. 

I think this is the correct behavior.

**Comment by poostwoud** [comment]
Hi @robotdan, 

We encountered the same using OAuth. Does this mean logins for an application for which the user is not registered should actually not allow returing an access token?

Cheers,

Peter

**Comment by mooreds** [comment]
@poostwoud This is a great question for the community forum or slack. We don't regularly monitor closed issues for comments.

https://fusionauth.io/community/forum/

https://fusionauth.slack.com
