### ISSUE TITLE
API Keys of length 4 or less do not render correctly

### ISSUE THREAD

**Issue by miaucl** [FusionAuth/fusionauth-issues#1397]
### Description 
**Disclaimer:** I know you should use longer api keys, but it was to test my new setup using `1234` as omnipotent api key.

In production mode I used a kickstart file creating my admin user and an api key.
```json
{
  "variables": {
    "adminApiKey": "#{ENV.MY_FUSIONAUTH_ADMIN_API_KEY}",
    "adminEmail": "email@address.com",
    "adminPassword": "#{ENV.MY_FUSIONAUTH_ADMIN_PASSWORD}",
    "adminFirstName": "First",
    "adminLastName": "Last"
  },
  "apiKeys": [
    {
      "key": "#{adminApiKey}",
      "description": "Initial setup key, not to be used afterwards."
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "/api/user/registration",
      "body": {
        "user": {
          "email": "#{adminEmail}",
          "password": "#{adminPassword}",
          "firstName": "#{adminFirstName}",
          "lastName": "#{adminLastName}"
        },
        "registration": {
          "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
          "roles": [
            "admin"
          ]
        }
      }
    }
  ]
}
```
with `export MY_FUSIONAUTH_ADMIN_API_KEY=1234`.

The api key works, I can use it to interact with the api, but when I try to edit it, I get a 500 error response from the fusionauth client.

### Affects versions
v1.30.1

### Steps to reproduce
1. Create kickstart file with an api key of 4 characters
2. Start it
3. Got to Settings/Api Keys
4. Edit the key
5. See error

### Expected behavior
It should not do that :) In the event logs I see it is probably a FreeMarker error which does not expect the api key to be so small. Imo, either this should be formatted correctly, _or_ the kickstart (and other ways of creating api keys) should enforce minimal length on api keys. (ex. length `8` works)

### Screenshots
List of Api Keys:
<img width="1021" alt="Bildschirmfoto 2021-09-16 um 10 33 41" src="https://user-images.githubusercontent.com/7894569/133580691-d31d7e04-fd18-4b8f-a832-53313b37c30d.png">
_(First: key=1234, Second: [created by fusionauth and is no problem])_

Event Log:
<img width="817" alt="Bildschirmfoto 2021-09-16 um 10 34 07" src="https://user-images.githubusercontent.com/7894569/133580712-12e0041b-f9ab-4ca1-b429-4228825178ba.png">

### Platform
 - Device: Desktop
 - macOS
 - FF
 - Database PostgresSQL & 11

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Using a longer key solves this bug, therefore not that critical, but still wanted to report it ;)

**Comment by robotdan** [comment]
Thanks for the great detail @miaucl !

I thought we were enforcing a min length during create. This is probably a bug in kickstart because we don’t use the API to create the API key for obvious reasons. 

We’ll need to enforce the min. length properly.

**Comment by miaucl** [comment]
Haha, your welcome. That's what I thought as I saw that the definition of the api key data in the kickstart and the api differ and short api keys are not allowed via the api or the front end.
