### ISSUE TITLE
Issue a JWT in APIs

### ISSUE THREAD

**Issue by RLefteris** [FusionAuth/fusionauth-issues#14]
Hi , i used Postman to take the new token (with **URL** -> localhost:9011/api/jwt/issue?applicationId={myApp's Id}) , in **Parameters** i placed applicationId with its value , and in **Headers** i placed  Authorization with the value i got from cookie (access_token value) ,and  Content-Type with application/json.. As a result i get a '_Could not get any response_' .... Where is the problem??

Thanks for your time

**Comment by robotdan** [comment]
Hi @RLefteris 

What HTTP Method are you using for this request in Postman? What status code is returned when you make this request?

**Comment by RLefteris** [comment]
Well the HTTP Method i used was _GET_ . Now , in return i got **no status code** but the message i wrote before _('Could not get any response')_ with the URL i used next to it...

**Comment by robotdan** [comment]
Thanks for the update. FusionAuth will always return a status code, so perhaps Postman is not connecting correctly to the API? 

Can you try making a `GET` request to the following API to verify the connection? 

`[GET] /api/status`, this should return a `200` status code. 

Could you provide a screenshot of your configuration in Postman? I've attached an example in Postman for calling the `/api/jwt/issue` API for you to review as well. 

<img width="1292" alt="screen shot 2018-10-29 at 11 58 32 am" src="https://user-images.githubusercontent.com/1148709/47670339-893c8680-db72-11e8-8c6b-2837ebb3f056.png">

**Comment by robotdan** [comment]
Ah, ok. Postman is indicating it cannot connect at all. 

You will need to change `localhost:9011` to `http://localhost:9011` so that Postman can complete the HTTP connection.

**Comment by RLefteris** [comment]
I changed the `localhost:9011` to `http://localhost:9011` like you said but i got the same message..... I don't get it
![capture](https://user-images.githubusercontent.com/44565746/47768951-c32c9a80-dce2-11e8-97ec-37cf33ec3f48.PNG)

**Comment by robotdan** [comment]
Are you sure FusionAuth is running?
Can you access the UI at `http://localhost:9011`?

**Comment by RLefteris** [comment]
I always have the UI running in google chrome when i make these requests.. With the other APIs i didn't have any problem except this one.

**Comment by robotdan** [comment]
Strange, I'm sorry you're having this problem. So the other APIs are working fine, and just this one is having an issue? 

Are there any exceptions on the console? Or if you're running as a service, in the log? `logs/fusionauth-app.log` ?  If so, can you attach any parts of the log that look interesting? 

I'll attempt to recreate.

**Comment by RLefteris** [comment]
Well . i found the solution... It was a **copy-paste bug**...... Thanks for your time and all your help my friend!

**Comment by robotdan** [comment]
Glad to hear you resolved the issue. Thanks for the update.

Happy to help.
