### ISSUE TITLE
Setup Wizard may be shown in a multi-node environment after setup wizard has completed

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1402]
### Description 
There is a timing issue where the setup wizard may still be displayed in a multi-node configuration after it has been completed. 

### Affects versions
Unknown

### Expected behavior
Once a single node has completed setup-wizard, all other nodes should exit as well. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Workaround: complete the setup wizard with any form field values and you'll be sent to the admin UI.
