### ISSUE TITLE
Key master import HMAC action has Key Identifier field

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1408]
### Description 

Key master import HMAC action has Key Identifier field. As far as I can tell, this is not used (since key identifiers are, as far as I know, only used when we publish keys, and we'd never publish a symmetric key). It is optional, but why have it at all?

### Affects versions

1.30.1

### Steps to reproduce

Navigate to Key master, import an HMAC. 

### Expected behavior
The field isn't present on the UX.

### Screenshots
<img width="800" alt="import-hmac-secret" src="https://user-images.githubusercontent.com/91825/134435812-91072b0d-d317-48c8-a2a6-667fda83fc22.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
The `kid` or "key identifier" is used for HMAC. When we sign a JWT using an HMAC key, we must write the `kid` to the JWT header so the consumer of the JWT knows how to verify the signature.

**Comment by mooreds** [comment]
Awesome, seems like this isn't a bug. Closing.
