### ISSUE TITLE
Breaking change in SAML reconcile lambda

### ISSUE THREAD

**Issue by epbensimpson** [FusionAuth/fusionauth-issues#1409]
### Description
After upgrading to 1.30.1 our SAML reconcile lambda stopped working with ` Lambda invocation exception. Id: 0e6188ae-e43d-4acb-931c-3434fb90e994 Name: ReconcileSAMLIdentifier TypeError: Cannot read property "id" from undefined in <eval> at line number 6`

I added some debug and it looks like `samlResponse.assertion.subject.nameID` has changed to an array named `nameIDs` at some point:

```json
{
    "nameIDs": [
        {
            "format": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
            "id": "<snip>"
        }
    ],
    "subjectConfirmation": {
        "inResponseTo": "id49b62721f2a148f0a8dec6104c1f29c3",
        "method": "Bearer",
        "notOnOrAfter": 1632351070112,
        "recipient": "<snip>"
    }
}
```

I couldn't find this documented in any release notes, and it's not reflected in [this documentation](https://fusionauth.io/docs/v1/tech/lambdas/samlv2-response-reconcile/). 

Edit: the lambda:
```javascript
function reconcile(user, registration, samlResponse) {
    console.debug(JSON.stringify(samlResponse.assertion.subject));
    // Add an identifier to help with EP reconciliation
    user.data.ssoIdentifier = samlResponse.assertion.subject.nameID.id;
    user.data.ssoIssuer = samlResponse.issuer;
}
```

**Comment by robotdan** [comment]
@lyleschemmerling can you check if we broke something that needs to be documented in release notes or something like that?

**Comment by lyleschemmerling** [comment]
Internal:
 - https://github.com/FusionAuth/fusionauth-site/pull/1884
