### ISSUE TITLE
Google connect black square logo

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1410]
### Description 

With the Google Connect option, we have a black square instead of the Google Connect logo on the oauth login page.

### Affects versions

1.30.1

### Steps to reproduce
1. Activate the google connect provider
2. Go to the login page using this provider

### Expected behavior

A Google Logo, not a black square. :upside_down_face: 

### Screenshots

I extracted the svg code directly from your `_helpers.ftl`.

You can copy/paste this HTML code to reproduce the problem easily.

```html
<!DOCTYPE html>
<html>
  <body>
    <svg version="1.1" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
      <g>
        <path class="cls-1" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
        <path class="cls-2" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
        <path class="cls-3" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
        <path class="cls-4" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
        <path class="cls-5" d="M0 0h48v48H0z"></path>
      </g>
    </svg>
</body>
</html>
```

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by soullivaneuh** [comment]
Hmm it looks like the svg itself did not change since many releases. Try with 1.22.0, got the same svg code and the same issue.

Do you have any clue about this issue? :thinking:

**Comment by soullivaneuh** [comment]
Workaround: Override the helpers to put a valid SVG logo. For example, this one: https://upload.wikimedia.org/wikipedia/commons/8/8b/Google_2015_logo_colorless_mourning_period.svg

**Comment by jobannon** [comment]
@soullivaneuh closing this issue as it appears resolved and stale.  Please let us know if this is not the case.

**Comment by soullivaneuh** [comment]
> appears resolved and stale

I don't know, you tel me? I applied the workaround I described to get my own working SVG file, but if yours is still the same, I would say no, the issue is not resolved.

It became stale because it got not any answer since its opening.
