### ISSUE TITLE
Can't set key identifier when generating HMAC secret

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1411]
### Description 

Can't set key identifier when generating HMAC secret using key master UI.

### Affects versions

1.30.1

### Steps to reproduce

Go to key master, generate an HMAC key. I can't specify the key identifier.

### Expected behavior

Can specify the key identifier when having FusionAuth generate a HMAC secret.

### Screenshots
<img width="800" alt="generate-hmac-secret" src="https://user-images.githubusercontent.com/91825/134524526-b77ccf45-7499-4f42-af86-cfeef26ddad5.png">

Compare with the import HMAC, where you can specify the key identifier.

![Screen Shot 2021-10-29 at 9 24 32 AM](https://user-images.githubusercontent.com/91825/139461376-928a5105-87c5-4dda-91a6-e907483f1d7f.png)

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
This is a very minor bug.

Related: https://github.com/FusionAuth/fusionauth-issues/issues/1408

**Comment by bguyza** [comment]
This is working as designed.  We generate a `kid` on creation and is reflected accurately in the documentation.  Unless someone has a technical reason to change this, we will leave it as intended.

**Comment by mooreds** [comment]
What if someone wants to specify a specific key identifier for a generate HMAC key, perhaps to conform to an internal standard?

@bguyza 

Anyway, we can keep this closed unilt (if) we hear from a customer. It just seemed weird to have the ability to specify a kid for all the other key types and not HMAC.
