### ISSUE TITLE
Password retention on form during self service registration

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1412]
### Problem

I want to use self service registration. When there is a validation error, my prospective user's password (or passwords, if there is confirmation) disappear from registration form.

### Solution

I want to use self service registration. When there is a validation error, I want my user's passwords to be retained on the registration form without any effort on my part.

### Alternatives/workarounds

Add my own custom password remembering code in theme JS, I guess.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This is working as designed. Any form field you set to type `password` will not be preserved. 

I don't think I've ever seen a web form work like this, we'd need to override the default behavior of a `password` field in a form. This seems like a huge security risk to return the user's password in plain text to the client.
