### ISSUE TITLE
Add event log message when 'discover endpoints' fails

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1417]
### Problem

I'm setting up an OIDC identity provider. I am using 'discover endpoints'. I have verified that the document at https://hostname/.well-known/openid-configuration looks good.

But I am getting this error message (in the UI, nowhere else): `Invalid oauth issuer. Failed to discover the well known OpenID configuration. Try disabling discover endpoints.`

There is nothing in the event log or system logs to help me debug further. 

### Solution

Add an event log entry with details when discover endpoints fails.

### Alternatives/workarounds

n/a

### Additional context

Sidenote: I suspect this is because I'm running in two different docker containers and the network path isn't set up for FusionAuth to internally resolve the different hostnames. But that isn't relevant to the bug.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
>  Invalid oauth issuer. Failed to discover the well known OpenID configuration. Try disabling discover endpoints.

This should only be returned on the API when creating or updating an IdP. Is this where you are seeing the message, or do you configure it - and then find out it is not working at runtime?

**Comment by mooreds** [comment]
Sorry if this was unclear. I'm creating a new OpenID Connect Identity Provider using the admin UI and the `issuer` host is unavailable to my FusionAuth instance (no network path to it).

**Comment by robotdan** [comment]
When you do that, don't you get a UI validation error for that field?

**Comment by mooreds** [comment]
> When you do that, don't you get a UI validation error for that field?

Yes. That is the message: 'Invalid oauth issuer. Failed to discover the well known OpenID configuration. Try disabling discover endpoints.'

However, it would be nice to know how the discovery failed. There are a couple of possible ways:

* couldn't connect to the `issuer` server
* found `issuer` server, but no resource at the expected URL
* resource at the expected URL but wasn't valid (not JSON, not formatted correctly)

That's the kind of information that would have been helpful to me in debugging this issue and I would like logged to the event log.
