### ISSUE TITLE
Need ability to duplicate email templates within and between tenants

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#142]
### Problem
To simplify the creation of multiple email templates.

### Solution
When I'm creating a series of email templates it would be very useful to duplicate one that I'm already happy with to use as the basis for the next.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
How is this? 

![image](https://user-images.githubusercontent.com/1148709/56674033-9300fb80-6676-11e9-8b2f-93cac18957e0.png)

**Comment by davidmw** [comment]
Sorry for the delayed response - looks great!

**Comment by robotdan** [comment]
@davidmw you made the release notes! https://fusionauth.io/blog/2019/05/01/fusionauth-update-saml
