### ISSUE TITLE
Docker image fails due to log file permissions

### ISSUE THREAD

**Issue by elliotdickison** [FusionAuth/fusionauth-issues#1423]
### Description 
I'm self-hosting FusionAuth on [Fly.io](https://fly.io). It has been working great until very recently when it started failing at startup. The only message I get is:

```
/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh: line 401: /usr/local/fusionauth/fusionauth-app/apache-tomcat/../../logs/fusionauth-app.log: Permission denied
```

This is confusing because according to the docs FusionAuth is not supposed to log to a file when run via a container. Is the issue that FusionAuth doesn't realize it's being run in a container, so it attempts to log and fails?

Fly does do some magic to [convert the Docker image to a Firecracker microVM](https://fly.io/docs/reference/architecture/#microvms), is it possible a change they made recently could trick FusionAuth into thinking it's not running in a container? How is FusionAuth detecting that it's run via a container?  Thanks for any help!

### Affects versions
1.30.1

### Steps to reproduce
Deploy the fusionauth/fusionauth-app:1.30.1 image to Fly.io.

### Expected behavior
I would expect FusionAuth not to attempt writing any logs, and to still startup if it failed to do so.

### Platform
(Please complete the following information)
 - Device: Fly.io VM
 - OS: Firecracker
 - Browser + version: N/A
 - Database: postgres 12.5

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Can you recreate on vanilla docker? This would narrow it down to something with fly.io. 

In theory the Docker image should log everything to `stdout` because of how we start Tomcat. See 
https://github.com/FusionAuth/fusionauth-containers/blob/11e432d19fb602d4bfffe8017247f1fab1baa5c6/docker/fusionauth/fusionauth-app/Dockerfile#L83

Did this work with fly.io with an earlier version of FusionAuth?

**Comment by elliotdickison** [comment]
Turns out it _was_ attempting to log to stdout, the [symbolic link to stdout from a logfile threw me off](https://github.com/FusionAuth/fusionauth-containers/blob/11e432d19fb602d4bfffe8017247f1fab1baa5c6/docker/fusionauth/fusionauth-app/Dockerfile#L73). Seems to be an issue with permissions to write to stdout on Fly's end. Thanks for the response!
