### ISSUE TITLE
Add managed domains option to SAML v2 Idp Initiated

### ISSUE THREAD

**Issue by SloEddy** [FusionAuth/fusionauth-issues#1427]
### Problem
The SAML v2 IdP Initiated identity provider does not have an ability to limit the "managed domains" when being configured. This prevents us from setting up third parties that we only trust within a certain domain and thus makes it unusable when permitting third parties as we cannot prevent them from impersonating other users.

### Solution
Add a managed domains section to the identity provider configuration, and only permit the Idp Initiated authentication to succeed when a matching domain user connects to fusion auth.

### Alternatives/workarounds
The workaround in my case would be to have a non-idp initiated guide on your page for Okta, so a just saml v2 guide for configuring Okta. The guide used for Okta configuration was https://fusionauth.io/docs/v1/tech/identity-providers/samlv2-idp-initiated/okta/ which uncovered this issue.

### Additional context
The Idp Initiated section where the managed domains option is expected and desired
![image](https://user-images.githubusercontent.com/1764938/136541977-d9a68c89-be95-4ff2-9389-7eccbacd90b9.png)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
I think this is working as designed. 

The Managed Domains in the SAML IdP config does not limit what users can login, but rather it helps us direct users to the correct IdP from the login page. 

For example, if you add a managed domain of `acme.com` to the SAML IdP config, then on the login screen we will ask for the email address first, and then if a user enters `bob@acme.com` we will forward the user to the SAML IdP.

We don't have any control over what email address the user logged in with once they are in the 3rd party IdP workflow. We could redirect the user if they enter `bob@acme.com` (per the prior example), and then when that user gets to the SAML IdP they could enter `fred@gmail.com`. 

Additionally, the only thing we know about the user after that is what the IdP sends us in the SAML AuthN response. The IdP is not obligated to tell us how the user signed in, they only send us assertions about the user which may or may not contain an email address - which may or may not be the email address they used to sign in. The user may not have even used an email address to sign in.

**Comment by SloEddy** [comment]
> > The workaround in my case would be to have a non-idp initiated guide on your page for Okta, so a just saml v2 guide for configuring Okta.
> 
> You should be able to configure Okta using the standard SAML Identity Provider as well. Though there is no guide, the process should be much the same.
> 
> Have you tried configuring the standard SAML Identity Provider and run into particular roadblocks or issues?

The process is "mostly" the same @mooreds but just for clarity a guide would still be handy, it's a bit odd to send someone to "follow that guide but don't do IdP initiated". Not the greatest challenge, I know, but sometimes a surprisingly non tech user is setting this up on the Okta side which complicates things when no direct guide is available. 


> I think to properly implement a feature such as this we'd have to add additional configuration or a lambda function to inspect the assertions returned from the IdP and tell us if we should allow login to continue.

Thanks for your explanation @robotdan, I believe you are correct and a method to inspect the returned assertions and then either permit or reject them based on specific configuration (email domain) in the IdP would be immensely helpful and is indeed the better/proper way to address what I am looking for. It's not always guaranteed that we can fully trust an IdP for 'all' email domains when we are reconciling users based on email, if a bad or compromised IdP started issuing valid sessions for what would be a 'fake' email they could hijack a different user. This is extremely unlikely using large/well known IdPs but you can't always trust third parties after all. Put it plainly, if I send a user to @gmail.com IdP providder and anything but @gmail.com comes back then something funny is going on and I don't want to trust it.

**Comment by mooreds** [comment]
Thanks for your feedback, @SloEddy ! 

> According to what you are saying and the "it is only used to manage the initial redirect" the sentence in bold is confusing me a bit, as I was under the impression this is already happening post-return from the IdP.

I believe what @robotdan was saying is that there is no security around managed domains; it doesn't lock a user into going to a saml provider, since they could simply edit the URL and circumvent it. What it offers is convenience and a workflow in the hosted login pages: we'll take an email address from the user, get the domain, and if the domain matches an existing configured SAML identity provider, forward the user on, skipping the page where they'd normally see the username and password fields.

Does that make sense? (And, @robotdan , feel free to correct me if I got it wrong.)

**Comment by SloEddy** [comment]
Thanks @mooreds, I do understand that the managed domains section is there for convenience only, I am just pointing out that the wording of the section on the frontend is a bit misleading, as depending on how you read it, it could mean that it either is, or is not, actually going to apply restrictions. I will close this issue and make another to request that post-return lamba, I did like that idea 😄

**Comment by mooreds** [comment]
thanks @SloEddy . I'll open another issue to clarify the wording.
