### ISSUE TITLE
Group memberships may be not be updated during an LDAP reconcile lambda once user already exists

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1432]
### Description 
When a user is first created as the result of an LDAP connection, if the Lambda provides group memberships, they memberships are created successfully. 

On subsequent logins, any changes in membership from the connector should be reflected, and it appears they may not always be updated. Needs investigation. 

### Affects versions
TBD

### Steps to reproduce
1. Configure an LDAP connector
2. Build memberships in the lambda
3. Review newly created user has memberships
4. Modify group memberships defined in the lambda
5. See if user has changed memberships

### Expected behavior
Memberships should be kept in sync according to the LDAP reconcile lambda. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
So far I've been unable to recreate. May need additional information or details on a recreate.

**Comment by robotdan** [comment]
@bguyza please re-open if you can confirm you have reproduced.

**Comment by bguyza** [comment]
Was able to reproduce and re-opened.  Hoping for a fix soon.
