### ISSUE TITLE
Add support for tokens obtained from the client credentials grant on the introspection endpoint

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1434]
### Problem
Currently,  if you obtain a token via client credentials grant, and submit that token to the introspection endpoint, no meaningful data is returned (in fact, the token is recognized a non-valid)

https://fusionauth.io/docs/v1/tech/oauth/endpoints/#introspect

### Solution
Add support for any token obtained through the client credentials grant to also be submitted to the introspect endpoint.  Responses should fall in spec with the current OAuth2 protocols.

FusionAuth may need to identify a way to understand this is a token issued from a client credentials grant such that it can properly perform client authentication. 

### Alternatives/workarounds
1. Use a library to inspect any token obtained through the client credentials grant.
2. Use the JWT Validate endpoint. https://fusionauth.io/docs/v1/tech/apis/jwt/#validate-a-jwt

### Additional context
https://fusionauth.io/community/forum/topic/1303/client-credentials-introspection

### Related issues
- https://github.com/FusionAuth/fusionauth-issues/issues/1100
- https://github.com/FusionAuth/fusionauth-issues/issues/2218

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Documentation
- [x] Review Introspect endpoint doc to see if it mentions anything specific about the types of tokens it will accept.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/256
