### ISSUE TITLE
User registration does not match with creation date

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#144]
### Description
Here the profile of our user:

<img width="1271" alt="Screen Shot 2019-04-24 at 2 54 05 PM" src="https://user-images.githubusercontent.com/1580512/56654409-10416600-66a1-11e9-9952-8167e33274c2.png">

As you can see, the user has been created in 2014 and the app registered in 2014... but when I go the Registration report, it is empty for 2014 and it looks like that all the registration are recorded the day where the API has received the user instead of the day of the creation date.

Why is the report not based on the creation date that we can see in the profile of the user?

**Comment by robotdan** [comment]
Thanks for reporting this issue @blanchonvincent . 

To clarify the issue, you have used the Import API to import existing users w/ registrations. When you view the Manage User page, the registration create date and the user create date are correct. When you view the Registration report, it does not show any registrations in 2014? 

This is working as designed, when we bulk import users we use the current time. This may not be the best way to do this, let me review with the team and see if this is something we can correct.

**Comment by blanchonvincent** [comment]
`you have used the Import API`
=> yes because as I said in this ticket https://github.com/FusionAuth/fusionauth-issues/issues/23, import user is the only API able to register the app at the same time.

`This is working as designed`
=> what is the point to get the possibility to change the `insertDate` if it useless? Also, someone that import users, it obviously means it is users created in the past. So, it does not make sense to use the current time.

`it does not show any registrations in 2014?`
Yes it shows there are thousands users registered the day of the release... and If we import our users deleted years ago, it will display them registered in 2019... so there is no point for us to import our deleted users and it is sad :/

**Comment by robotdan** [comment]
We do preserve the `insertInstant` on the User and Registration during import. Currently it is just not utilized when we increment the registration count. 

This is likely something we can fix, I'll follow up when I know more.
