### ISSUE TITLE
Unable to register user right after creating an application

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#1452]
### Description
Using FusionAuth version `1.30.2` we are getting an unexpected error when we register a new tenant, application, roles and then attempt to register a new user using one of the roles. We are getting a bad request error (`404`) indicating that the given `role` does not exist. 

### Steps to reproduce
1. Use FusionAuth version `1.30.2`
2. Create a new `tenant`
3. Create a new `application`
4. Create a new `application` `role` (e.g. `admin`) 
4. Register a new `user` with the new`role`
5. Returns the following error:
```js
{
  'registration.roles': [{
      code: '[invalid]registration.roles',
      message: 'The role [admin] does not exist in the Application indicated by the [registration.applicationId] property.'
    }]
}
```

And if we check `fusionauth` (dashboard) we can see that the new `application` `role` exists.

**Comment by nunovieira220** [comment]
@robotdan sorry, I know this issue is closed and it is supposed to be solved on the version `1.31` but we are still dealing with the same error on the version `1.32.1`.

**Comment by mooreds** [comment]
@nunovieira220 can you please provide repro steps like @johnmaia did?

**Comment by nunovieira220** [comment]
@mooreds they are the exact same but using `1.32.1` version instead of `1.30.2`.

**Comment by mooreds** [comment]
Thanks. Just so I'm clear, I wanted to confirm that you've run the curl scripts in this comment: https://github.com/FusionAuth/fusionauth-issues/issues/1452#issuecomment-949658134 and seen the issue described in this bug?

@nunovieira220

**Comment by nunovieira220** [comment]
@mooreds sorry I didn't run the curl script before and I can not reproduce the issue when running it, so it seems it is working properly. In fact, and I apologized for not being more expliciti beforehand, the problem is more related with the role changing process

```
API_KEY=... # valid, cross tenant API key
HOST_URL=http://localhost:9011

#Create a new tenant
#Create a new application
#Create a new application role (e.g. admin)
#Register a new user with the newrole

tid=`curl -XPOST -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/tenant/' -d '{ "tenant" : { "sourceTenantId" : "30663132-6464-6665-3032-326466613934", "name":"test'$$'" }}' |jq '.tenant.id'|sed 's/"//g'`

aid=`curl -XPOST -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/application/' -d '{ "application" : { "name":"testapp'$$'" }}' |jq '.application.id'|sed 's/"//g'`

uid=`curl -XPOST -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/user/' -d '{ "user" : { "email":"foo'$$'@example.com","password":"password" }}' |jq '.user.id'|sed 's/"//g'`

rid=`curl -XPOST -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/application/'$aid'/role' -d '{ "role" : { "name":"admin" }}' |jq '.role.id'|sed 's/"//g'`
rid2=`curl -XPOST -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/application/'$aid'/role' -d '{ "role" : { "name":"owner" }}' |jq '.role.id'|sed 's/"//g'`

curl -XPOST -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/user/registration/'$uid -d '{ "registration" : { "applicationId":"'$aid'", "roles":["owner"] }}'

#curl -XPATCH -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/application/'$aid -d '{}'

curl -XPUT -H 'X-FusionAuth-TenantId: '$tid -H'Content-type: application/json' -H "Authorization: $API_KEY" $HOST_URL'/api/user/registration/'$uid'/'$aid -d '{ "registration" : { "applicationId":"'$aid'", "roles":["admin"] }}'
```

The bash script above is returning the error we are looking for but if we uncomment the penultimate curl request, everything works just fine.

**Comment by robotdan** [comment]
Perhaps same issue described here https://github.com/FusionAuth/fusionauth-issues/issues/1575 - will review.
