### ISSUE TITLE
SMTP password does not copy when duplicating tenant

### ISSUE THREAD

**Issue by ktorii** [FusionAuth/fusionauth-issues#1469]
### Description 
When duplicating a tenant, the SMTP password in the Email tab does not copy. The thing is there is no notice of this, and since we thought duplicating the tenant would just copy all properties of the duplicated tenant, this made us not realize emails were not working for awhile on production.

### Affects versions
1.27.2

### Steps to reproduce
1. Go to Tenants in the sidebar
2. Click on duplicate tenant button
3. Click save
4. Send test email. Notice no email sent and SMTP password is not set.
5. Edit smtp password setting
6. Test email, now works.

### Expected behavior
At step 4, expected the email to send because SMTP should be duplicated when duplicating tenant.

### Screenshots
N/A

### Platform
 - Device: Desktop
 - OS: MacOS
 - Browser + version: Chrome 95.0.4638.54
 - Database N/A

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
I think not copying the SMTP password is probably the correct choice here. 


However, perhaps the correct behavior is if you click on duplicate tenant and try to save the form, should we fail validation and force you to enter the password for the SMTP configuration? 

This would make it much clearer that this value was not copied.

**Comment by mark-robustelli** [comment]
Updated documentation in commit 43518f0a5279514c124c1002192a13cd1c8030e0 from fusionauth-site

**Comment by mooreds** [comment]
@mark-robustelli please add the PR which fixes this, rather than the commit.

**Comment by mark-robustelli** [comment]
fixed in PR: https://github.com/FusionAuth/fusionauth-site/pull/2299
