### ISSUE TITLE
"Login today" in the dashboard is not smart

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#147]
In our dashboard we have this number:

<img width="276" alt="Screen Shot 2019-04-28 at 10 30 25 AM" src="https://user-images.githubusercontent.com/1580512/56859780-bf7f8500-69a0-11e9-9320-85d8fbc00d33.png">

It shows that we have -78% logins. But it is comparing a full day with a day where it is 10 am only.

It has two issues:

- We should compare the number of logins today at 10 am VS yesterday 10 am
- We should compare the same day the previous week (monday VS monday - tuesday VS tuesday, etc). Because obviously comparing the first day of the week and the last day of the week end is not really accurate

The only way to have accurate numbers is to check this number everyday at 11pm when we know the day is done and no users will login anymore

**Comment by robotdan** [comment]
Internal, need to review calculation to see if we have a bug.
