### ISSUE TITLE
Self-service Enable Two Factor forms broken

### ISSUE THREAD

**Issue by jasonaowen** [FusionAuth/fusionauth-issues#1470]
### Description 
On the Enable Two-factor self service page, the email and SMS "Send a one-time code" forms have an empty hidden `method` element. Instead of sending the code to the entered address or number, the page reloads with the method field highlighted in red.

### Affects versions
A hosted instance of FusionAuth 1.30.2, running with a non-production Developer license

### Steps to reproduce
1. Go to an application's [account self service page](https://fusionauth.io/docs/v1/tech/account-management/), and sign in with a valid user
2. Click on the "Add two-factor" button to be taken to `/account/two-factor/enable`
3. Enter an email address, and click the corresponding "Send a one-time code" button
4. See missing method error, and no email sent
5. Enter a phone number, and click the SMS "Send a one-time code" button
6. See missing method error, and no text message sent

To workaround:
Open the browser dev tools, edit the hidden `method` field to set the value to `email` or `sms`, and click the button. The message is sent, and the MFA option can be enabled.

### Expected behavior
I expected the buttons to cause a one-time code to be sent, so that SMS or email could be enabled as a MFA option.

### Screenshots
This is what I see in the inspector tab of the Firefox dev tools when I examine the SMS form:

![Browser dev tools, showing the hidden fields of the SMS form](https://user-images.githubusercontent.com/1494855/140004384-868a6ce2-c976-496b-90b3-11f0a660d35d.png)

The key thing to notice is that the value for `method` is an empty string.

(Note that I used the developer tools to censor the application ID and secret values; this is a test account in a test instance, but better safe than sorry.)

After attempting to send a one time code, the method field is shown in an error state:

![Beginning of the rendered form, with the text around the method field in red](https://user-images.githubusercontent.com/1494855/140004011-2581e307-da9c-4b82-95a3-15e059c00a31.png)

### Platform
(Please complete the following information)
 - Device: desktop
 - OS: Ubuntu 18.04
 - Browser + version: Firefox 93.0 (64-bit)
 - Database: hosted

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
@bguyza can you take a look and see if we can recreate in a test? Thanks.

**Comment by bguyza** [comment]
@jasonaowen 
Thanks for submitting this report.  

I haven't been able to recreate this successfully on my initial attempt. However, the behavior you're experiencing leads me to believe that the javascript that should be running on this page is not setting the `method` value.  Specifically, `js/account/EnableTwoFactor.js?version=1.30.3`.

Could you verify whether or not you have any javascript errors and/or if javascript is disabled?

**Comment by jasonaowen** [comment]
I am getting a JavaScript error:

```
Uncaught Error: code length overflow. (1564>1056)
    createData qrcode-min-0.1.js:1
    makeImpl qrcode-min-0.1.js:1
    getBestMaskPattern qrcode-min-0.1.js:1
    make qrcode-min-0.1.js:1
    makeCode qrcode-min-0.1.js:1
    QRCode qrcode-min-0.1.js:1
    EnableTwoFactor EnableTwoFactor.js:22
    <anonymous> enable:82
    value PrimeDocument.js:377
    value PrimeDocument.js:193
    Prime Overlay.js:110
    <anonymous> prime-es6-1.5.3.js:10306
qrcode-min-0.1.js:1:5199
```

Which, relatedly, the TOTP QR code is not loading:

![Screen Shot 2021-11-04 at 10 43 36](https://user-images.githubusercontent.com/1494855/140391622-df95289c-2cf6-4cd3-881b-f70e13fa2f9b.png)

That is the only error I see in the console, though.

**Comment by jasonaowen** [comment]
I was able to reproduce this error on a different browser: Chromium Version 94.0.4606.81 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit).

**Comment by bguyza** [comment]
Thanks a ton for confirming @jasonaowen!

It looks like you uncovered a bug with the QR code library.  Here is one of the many open issues on the github repository for your reference: https://github.com/davidshimjs/qrcodejs/issues/78.

Unfortunately, this JavaScript error prevents the event handler from initializing so that `method` is correctly set on load or when selecting a new value. 

I will be looking to get this bug rectified in our code in the next patch release.

**Comment by jasonaowen** [comment]
Ah, yep, I can confirm: disabling TOTP authentication in the tenant MFA settings causes that page to render correctly. That's also a viable workaround for me in the meantime, although we do want to enable TOTP auth soon. Thanks, @bguyza!
