### ISSUE TITLE
Email Template for setup password broken

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1476]
### Description 
When completing a registration/new user - when setting `sendSetPasswordEmail: true`, the email that generates from the shipped email template causes errors.

### Affects versions
1.30.2

### Steps to reproduce
0. Create a new user and registration
1. Get a set password email (notice this includes `client_id`)
2. Get an error about a redirect URI/URL missing from an OAuth flow

### Expected behavior
The set password email to work as shipped with FusionAuth

### Screenshots
![image](https://user-images.githubusercontent.com/16090626/140243259-7d0cefd4-c34a-4d86-ab86-079fb652aaf9.png)

### Platform
dev setup

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Workaround -- remove `client_id` from the email template.  The drawback is that you will have the tenant scoped theme and not an application-level theme at the page the user lands on.

**Comment by robotdan** [comment]
Internal notes, we could re-think the usage here, and perhaps just allow `client_id` and if we can't re-constitute an OAuth2 flow just don't fail and allow it.
