### ISSUE TITLE
Entities don't support the use of special characters (`:`) in permissions

### ISSUE THREAD

**Issue by matthewhartstonge** [FusionAuth/fusionauth-issues#1480]
### Description 
For our API Consumers, we currently use URNs for our scopes to avoid namespacing issues between backend resources.

For example, as a selection, we have:
- `urn:hero:schools:schools`
- `urn:hero:schools:schools:read`
- `urn:hero:schools:schools:delete`

I could easily load these permissions into FusionAuth, but upon trying to request the specific permission via the API, `invalid_scope` is returned.

```json
{
    "error": "invalid_scope",
    "error_description": "Invalid target-entity scope. The permission names [urn] are invalid.",
    "error_reason": "invalid_entity_permission_scope"
}
```

### Affects versions
`v1.30.X`

### Steps to reproduce
1. Go to 'Entity Management > Entity Types'
2. Click on 'Add'
3. Enter Name: 'Test Type'
4. Click on 'Add Permission'
5. Enter `urn:test:scope` as the name
6. Click 'Save'
7. Go to 'Entity Management > Entities'
8. Click on 'Add'
9. Enter Name: 'Test Entity'
10. Choose the 'Default' Tenant
11. Enter Client ID: `b8cdfa71-6578-49ce-aa99-203e3fda83eb`
11. Choose the 'Test Type'
12. Click 'Save'
13. Send a Client Credentials grant token request via the API with scope `target-entity:b8cdfa71-6578-49ce-aa99-203e3fda83eb:urn:test:scope`
14. Receive API Error

### Expected behavior
Parsing the resultant scopes should be delimited by space and URNs should be considered valid scopes.

### Screenshots
A test list of permissions added:
![image](https://user-images.githubusercontent.com/6119549/140436268-6ab83b5b-7825-4691-ba47-138cd9f7f0e0.png)

### Platform
 - Device: Desktop
 - OS: Windows
 - Browser + version: Postman
 - Database: FA Cloud Deployment

**Comment by mooreds** [comment]
Options to consider:

* provide a way to escape `:`
* only split on the first two `:`s, then take whatever is after the second `:` as the permission.
* provide configuration for the separator character in scopes (so you could set the separator to `#` and have the scope requested be `target-entity#b8cdfa71-6578-49ce-aa99-203e3fda83eb#urn:test:scope` for example)

**Comment by matthewhartstonge** [comment]
May be good to note - I tested this with URL Encoding, which doesn't work either:

```json
{
    "error": "invalid_scope",
    "error_description": "Invalid target-entity scope. The permission names [urn%3Atest%3Ascope] are invalid.",
    "error_reason": "invalid_entity_permission_scope"
}
```

**Comment by robotdan** [comment]
Thanks for opening the issue @matthewhartstonge. This has been resolved and will be available in the upcoming release.
