### ISSUE TITLE
Review Timestamps within SAML configuration.  

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1486]
### Description 
SAML timestamps come back invalid.  

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Steps to reproduce
See SAML integration in https://fusionauth.io/community/forum/topic/1328/saml-invalid-timestamp

### Expected behavior
Additional arguments should not be needed, possibly

### Platform
(1.27.2)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

https://fusionauth.io/community/forum/topic/1328/saml-invalid-timestamp

**Comment by robotdan** [comment]
Not sure I understand what this one is describing. Closing, please re-open if there are some more specifics.

**Comment by mooreds** [comment]
@robotdan did you look at the forum post referenced?

> Then I realized that the event logs in the FA server shows a different time (UTC) from ours (CEST).

It looks like our code uses the default server timezone, even though SAML stuff should all be in UTC.

The forum post has a workaround, but you also mention this might be a bug.

**Comment by robotdan** [comment]
I did, I’ve corrected the event logs to use UTC. However, the timezone used to print the event log is only cosmetic and would not affect runtime SAML validation. 

I reviewed all other SAML validation to ensure we are always using UTC. So there is nothing else to do as far as I can tell unless there is a more concrete way to recreate a failure.

**Comment by mooreds** [comment]
Okay. Let me ping the forum participant to see if they have any more info before we close, please.

**Comment by mooreds** [comment]
Closing, looks like we don't have repro steps: https://fusionauth.io/community/forum/topic/1328/saml-invalid-timestamp/4
