### ISSUE TITLE
Remove SAML login page presented to end-user

### ISSUE THREAD

**Issue by mjw913** [FusionAuth/fusionauth-issues#1488]
### Problem
We use FusionAuth to handle single signon in our app.  When we connect to a customer's IDP via SAML, we are always presented with a screen where the user must press an additional button.  They also receive a login and password prompt which confuses them
'
### Solution
If a tenant is saml, go right to the customer's IDP

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
You want the `idp_hint` parameter. 

```
Adding this request parameter will cause the FusionAuth login page to be skipped, and instead a 302 will be returned with a Location header of the IdP login URL. The end result is functionally equivalent to the end user clicking on the "Login with Pied Piper" button, or entering their email address when using the IdP configuration with managed domains. 
```

More here: https://fusionauth.io/docs/v1/tech/oauth/endpoints/

If that solves your issue, please close this out.

**Comment by jobannon** [comment]
Closing this out as this was likely resolved with the comment above.  Please reopen if the core of this issue is not addressed.
