### ISSUE TITLE
Kickstart json include eats escaped newlines in imported json

### ISSUE THREAD

**Issue by lingwooc** [FusionAuth/fusionauth-issues#1492]
### Description 
I'm putting my theme file in another file and using your json import to include it in the kickstart. This has the unwanted side effect of _appearing_ to remove _some_ instances of \n. If I check the config maps and the files themselves in the container everything is in order. The same json applies to your api without issue. The theme json I'm trying to import is created by your rest api so should be strictly valid in any case.

As an example the failing body is reported as
```
Request body:
{
  "theme" : {
    "name" : "xxxxx",
    "defaultMessages" : "#\n# Copyright (c) 2019-2021, FusionAuth, All Rights Reserved## Licensed under the Apache License, Version 2.0 (the License);# you may not use this file except in compliance with the License.# You may obtain a copy of the License at##   http://www.apache.org/licenses/LICENSE-2.0## Unless requ
```
The first new line survives, you'll see the following ones do not. This causes lots of errors like this as it abjectly fails to parse:
```
2021-11-18 9:02:32.662 AM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Error response:
{
  "fieldErrors" : {
    "theme.defaultMessages" : [ {
      "code" : "[invalid]theme.defaultMessages",
      "message" : "You must specify all of the required keys in the [theme.defaultMessages] property. It is missing these keys: cancel, pending-link-login-to-complete, [mismatch]mobilePhone, {description}recovery-codes-1, loginId, parentEmail, {description}recovery-codes-2, authenticator-enable-step-1, listSeparator, authenticator-enable-step-2, completed-links, [couldNotConvert]user.birthDate, [inactive]user.username, multi-factor-configuration, cancel-go-back, [ExternalAuthenticationException]OpenIDConnectUserinfo, two-factor-use-one-of-n-recover-codes, [ExternalAuthenticationException]SAMLResponseAudienceVerificationFailed, password, ...
    } ],
```
The above is truncated because its MASSIVE.

I'm assuming its the json import that is eating those \n before the REST is called. As I'm unable to create a large enough config map to inline the theme (issue with old fluxcd2) I will next attempt to use your text import a few of the large fields but that's significantly uglier.

### Affects versions
1.30.2

### Steps to reproduce
1. Create a kickstart with an external json include for a theme 

### Expected behavior
It imports cleanly respecting \n in the included json.

### Platform
 - GKE 
 - Fusion
 - Database: PostgresSQL 13

**Comment by lingwooc** [comment]
Ug, no that's not it at all. Just all `\`s in a theme must be escaped as `\\\` (including for quotes). So `\n` should be `\\\n` and `\"` should be `\\\"`. The escaping in text imports however is _quite mad_. I'm not going to try and work that one out.

**Comment by mooreds** [comment]
It may be helpful to use the include directives for these files. Here's an example: https://fusionauth.io/docs/v1/tech/installation-guide/kickstart/#include-text-files
