### ISSUE TITLE
Daily registration statistics not shown in Dashboard

### ISSUE THREAD

**Issue by MikeBroders** [FusionAuth/fusionauth-issues#1493]
### Description 
The amount of registrations in the dashboard (Registrations today) is displaying 0 

### Affects versions
1.30.2

### Steps to reproduce
1. Go to FuasionAuth Dashboard

### Expected behavior
Registrations today should show the daily registrations amount

### Screenshots
![image](https://user-images.githubusercontent.com/29118421/142405797-6ac332d5-de89-4347-920d-3151d77a6c38.png)

### Platform
(Please complete the following information)
 - Desktop
 - macOS
 - chrome Version 95.0.4638.69 (Offizieller Build) (arm64)

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1498

**Comment by robotdan** [comment]
This is most likely working as designed. 

This report will be calculated using the time zone configured in the System configuration for the report timezone. See `Settings > System > Reports`. Depending upon this configured time zone, and the timezone you're in - the report can appear delayed.

**Comment by MikeBroders** [comment]
time zone is set...
![image](https://user-images.githubusercontent.com/29118421/142608183-3f5c52c0-8df3-439f-8a0a-3c61fa4420e9.png)

but no display of daily registrations since update to 1.30.2

**Comment by MikeBroders** [comment]
any hints on this topic?

**Comment by robotdan** [comment]
Maybe related to this one https://github.com/FusionAuth/fusionauth-issues/issues/1498

**Comment by MikeBroders** [comment]
thanks for looking into it!

**Comment by robotdan** [comment]
I think we have confirmed this is caused by #1498 - and the fix should be available shortly.

**Comment by robotdan** [comment]
@MikeBroders this should be fixed in 1.32.0 which is now available. Please us know if the problem persists.

**Comment by MikeBroders** [comment]
working again:
![image](https://user-images.githubusercontent.com/29118421/146607289-94e4e52a-cf32-4f26-a9c1-515a12e9b027.png)

thx

**Comment by robotdan** [comment]
Thanks for letting us know!! Glad to hear it.
