### ISSUE TITLE
Can't use /api/jwt/reconcile with Apple IdP

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1503]
### Description 

The /api/jwt/reconcile doesn't work with Apple IdP

This specifies that you can use it with any identity provider: https://fusionauth.io/docs/v1/tech/apis/jwt/#reconcile-a-jwt

### Affects versions

?

### Steps to reproduce

* Get a token from apple
* Call /api/jwt/reconcile to get a fusionauth jwt

It fails.

### Expected behavior

Unsure if this is a doc issue or if the JWT api is incorrect.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Filed based on reviewing code and this forum post https://fusionauth.io/community/forum/topic/1368/using-reconsile-api-to-get-access-token

**Comment by robotdan** [comment]
This endpoint is really only intended to work with the ExternalJWT IdP. 

In practice it is the same endpoint as `/api/identity-provider/login` so if Apple works with that one, it should work with this one, but I believe we document to use `/api/identity-provider/login` with Apple and all other IdPs. But perhaps we need to add some clarification.
