### ISSUE TITLE
Postgres: Contention on last_login_instants table

### ISSUE THREAD

**Issue by epbensimpson** [FusionAuth/fusionauth-issues#1504]
### Description
This morning we had a large spike in requests to FusionAuth. We observed FusionAuth being pegged at 100% CPU, our autoscaling kicked in and we went from 2 to 16 instances pretty rapidly:

![image](https://user-images.githubusercontent.com/67403798/143969639-0148c72d-43ca-48a1-8312-d094e73e0cea.png)

![image](https://user-images.githubusercontent.com/67403798/143971384-e5d6a676-1f51-4fda-89c2-071ce476bdcc.png)

At the same time there was a large spike in DB waits. We use AWS Aurora Postgres, the cluster is shared with other apps but it is db.r6g.2xlarge and there was almost no other load on it at the time.

Digging into the offending queries:

![image](https://user-images.githubusercontent.com/67403798/143969333-2626f2f7-e4f0-4970-a9f0-b1ae3cf2639c.png)

![image](https://user-images.githubusercontent.com/67403798/143969210-d6b06a19-0270-4d8a-88f8-ca948de4d722.png)

It looks like they all involve `last_login_instants` and there's lots of lock contention. Even the updates on other tables are joining to `last_login_instants`.

One observation here is that the DB load seems to more closely follow the number of instances running as opposed to the request load. The spike in requests was over by 20:25, however the contention on `last_login_instants` remained until scale-down finished at 20:45.

FusionAuth version is 1.30.1.

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by epbensimpson** [comment]
Well, I'm happy to report that this was not a FusionAuth issue but something funky going on with the Aurora cluster. After our DBA resolved an issue to do with replication on one of the other databases on the cluster, we are able to scale FA without seeing this contention. 

Moral of the story: don't run your FusionAuth database on a shared server.

**Comment by mooreds** [comment]
Thanks for closing the loop, @epbensimpson !
