### ISSUE TITLE
Brute force protection against non-existing accounts (prevent username / email fishing)

### ISSUE THREAD

**Issue by jegger** [FusionAuth/fusionauth-issues#1507]
### Problem
When entering the credentials in the FA login page an attacker can figure out email addresses / usernames by brute-force. If the account exists, an attacker will run into a "account locked" state for an account.

### Solution
Track the login attempts for non-existing usernames / emails as well. Display the locked state return-message also for non-existing accounts so that an attacker can not differentiate anymore between existing and non existing accounts.

### Alternatives/workarounds
Captcha or rate-limiting. While captcha is annoying to users, the rate-limiting can also lead to bas user experience (e.g. many users behind same IP)

### Additional context
-

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by pipposepsa** [comment]
Talking about security this feature is a must.

**Comment by robotdan** [comment]
FusionAuth supports adding CAPTCHA to a login form, and also supports rate limiting for failed login requests. 
Please re-open if you think there are additional features that separate from the ones mentioned.
