### ISSUE TITLE
.well-known/openid-configuration does not handled by cors filter

### ISSUE THREAD

**Issue by dmushkov** [FusionAuth/fusionauth-issues#1508]
.well-known/openid-configuration does not handled by cors filter

When try to access http://{fusionauth}/.well-known/openid-configuration from JS client you got 
Access to XMLHttpRequest at 'http://{fusionauth}/.well-known/openid-configuration' from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by robotdan** [comment]
Is this just working as designed? There is a CORS configuration in FusionAuth, so in theory you would just need to add the host to the allowed origins? Or are you suggesting that this endpoint should be handled separately from the CORS configuration?

**Comment by robotdan** [comment]
Closing as working as designed. If you have additional information or other reasons to think that we need to handle this endpoint differently please re-open. Thanks.
