### ISSUE TITLE
FusionAuth 1.31.0 - OIDC Reconcile lambdas being called multiple times, resulting in cleared registrations, on certain identity providers

### ISSUE THREAD

**Issue by Oceanswave** [FusionAuth/fusionauth-issues#1517]
FusionAuth 1.31.0 - OIDC Reconcile lambdas being called multiple times, resulting in cleared registrations, on certain identity providers

### Description 
Within four separate containerized environments (dev/uat/prod/local) in different clusters, using the FusionAuth 1.31.0 images, starting with 1.31.0 it is observed that on various identity providers, reconcile lambdas are being called twice. 

When the user already exists, the second call completely clears user registration data.

When examining the lambda debug logs, The first call contains the existing registration data, however the second call does not.

The net result is that existing users attempting to log in to 1.31.0 lose all their roles, username and other data associated with a registration.

In the same environment, a separate Identity Provider, using the same IdP and reconcile lambda but with different client id, secret, and authority did not observe to be having the lambda called twice - and registrations with that Identity Provider did not have their state cleared.

### Affects versions
1.31.0

### Steps to reproduce
1. Create an application, an OIDC Identity Provider and associate the two. Associate the Identity Provider with a oidc reconcile lambda.
2. Enable debug mode on the identity provider and the lambda
3. Log in to the application using a user coming from the identity provider
4. Set various data on the user's registration in fusionauth, for instance, setting roles, a username, and so forth.
5. Logout and log in again with the user 
6. If the stars are aligned with the idp, observe that the user's registration data is cleared
7. Also, if the stars are aligned with the idp, observe that the oidc reconcile lambda is called twice.

### Expected behavior
The user's registration data is retained after login

### Screenshots
not available

### Platform
 - Device: N/A - happens on all IdP logins on various devices
 - OS: N/A - Happens on all IdP logins on various devices
 - Browser + version: N/A - Happens on all IdP logins regardless of browser and version
 - Database [MySQL | PostgresSQL] - Postgres 10.5.3

### Additional Information

For this particular IdP, this has broken user logins - reverting to the 1.30.2 container image resolves the issue.

**Comment by robotdan** [comment]
Thanks for reporting @Oceanswave . In theory, the only time the lambda should run twice is if you modify or fabricate the email address (when linking by email) or the username (when linking by username) in the lambda. 

However, even in that case, we should not expect any data integrity issues. We'll attempt to recreate and patch as quickly as possible.

**Comment by robotdan** [comment]
@Oceanswave if you could provide me a sanitized version of your lambda function that may be helpful as well.

**Comment by robotdan** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/commit/39fd24566a706606989c6d9fd5b81db50f205b49
- https://github.com/FusionAuth/fusionauth-app/commit/b77bf5ed64f6c2c36b8a28d0aadbf8d1312b7ca8
- https://github.com/FusionAuth/fusionauth-api/commit/f4c8245a3ebc86a3c5ddeaa50973bc639b25c676

**Comment by Oceanswave** [comment]
Hey Dan, I was actually able to repro with the default oidc lambda.

The strange part is that the issue varied with the same Azure AD based IdP
(using uid as the id bind) one tenant works fine, another fails, only
difference being the clieent id, secret, authority (url)

**Comment by robotdan** [comment]
Ok, thanks @Oceanswave - I think I understand what is going on. I have a patch ready, doing some internal code reviews. Should have a patch out this weekend.

**Comment by Oceanswave** [comment]
Sounds great! Thanks for the prompt responses.

**Comment by robotdan** [comment]
So there was a bug that was causing us to invoke the lambda a second time. In theory the only time it should be invoked twice is when the user has not yet been linked, and the email or username is modified or fabricated by the first invocation. 

However, this was not the root cause. While incorrect, invoking the lambda the second time should have just been a no-op. But due to an un-expected JDBC caching behavior the user registration was being modified un-intentionally. 

Thanks for reporting @Oceanswave .

**Comment by robotdan** [comment]
Available in 1.32.1.
