### ISSUE TITLE
Jlinked VM packaged with Docker image in 1.32.0 is missing a module

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1518]
### Description 
The `jdk.logging` module is missing in the jlink'd VM and it may cause an exception on startup, or cause the `fusionauth-app` service to fail during startup. 

### Affects versions
1.32.0.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
- https://github.com/FusionAuth/fusionauth-containers/commit/111e49c119ce58e8c524190787ee008596a98819
- https://github.com/FusionAuth/fusionauth-app/commit/6230a8d26654be11abe273d5084e4304d44e6a9a
- https://github.com/FusionAuth/fusionauth-app/commit/3d94d06b22eb8a9d9f94a156a0d8c4d1fc3b0842

**Comment by robotdan** [comment]
The `1.32.0` and `latest` Docker image tags have been replaced with an updated build. If you have already pulled one of these tags, please delete your local copy and pull again.

**Comment by oottinger** [comment]
I'm not sure if this is related, but on MacOS using the install via brew I'm not able to start the v1.32.0 service.

Seeing the error in the logs:
```
Error occurred during initialization of VM
Unable to load native library:
```

I tried to execute the bundled java binary and it doesn't work:
```
/usr/local/Cellar/fusionauth-app/1.32.0/java/current/bin
>> ./java --version
Error occurred during initialization of VM
Unable to load native library
```

The bundled version of 14 works:
```
/usr/local/Cellar/fusionauth-app/1.32.0/java/jdk-14.0.1+7/Contents/Home/bin
>> ./java --version
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

If needed I can open a separate ticket.

**Comment by robotdan** [comment]
I think the homebrew thin may have been caused by the Elasticsearch service starting up first - and it was downloading JDK 14 instead of JDK 17. This has been corrected. Can you try upgrading to 1.32.1 w/ home brew and see how it goes? If you still run into an issue, please open a new issue. Thanks!
