### ISSUE TITLE
Which template is used by FusionAuth by default?

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#152]
We would like to integrate our admin area with fusion auth. In order to do that, we would like to apply the same template to our admin area.

Could we know where we can find/buy this template?

**Comment by robotdan** [comment]
Are you looking for the theme / style that we use in FusionAuth? 

The style and layout we build is part of another project called `inversoft-style`, we have not yet open sourced that, but we could. This project contains all of the example layouts, CSS, widgets etc. 

Is this what you're looking for?

**Comment by blanchonvincent** [comment]
@robotdan yes exactly :)

**Comment by robotdan** [comment]
Internal: 

- Clean up our style project, move to the FusionAuth organization and open source under Apache 2. 
- Update FusionAuth and other projects using this style artifact to use the new project location

**Comment by robotdan** [comment]
Done!

https://github.com/FusionAuth/fusionauth-style
