### ISSUE TITLE
Login with Apple may not be working with iOS 12?

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1526]
### Description 
A client reported that the login with Apple may not be working with iOS 12. 

> We have successfully enable the Sign in with Apple in case of registration and login but the feature is not working on device which have iOS 12.0. When user click on Sign in with Apple, it does not redirect to apple page for sign in.
> Can you please suggest the solution. Is it only available on iOS 13+?

We need to review the Apple documentation and identify if there are any minimum requirements or changes we may have to make to ensure compatibility. 

#### Update
The root issue is that we are using a numeric separator in our `Apple.js` JavaScript. We have a numeric literal as `3_000` which is not supported prior to mobile or desktop Safari prior to 13. 

It is not clear if this feature has reached official inclusion in an ECMA script spec, but all browsers now support it with the exception of a few older ones. 

Browser support:
❌ IE: 
✅ Edge >= 79
✅ Firefox >= 75
✅ Chrome >= 75
✅ Safari >= 13
✅ Opera >= 62
✅ Safari on iOS >= 13
❔Opera Mini
✅ Android Browser >= 96
❌ Opera Mobile
✅ Chrome for Android >= 96
✅ Firefox for Android >= 94

### Work around
On line `41` of `web/js/identityProvider/Apple.js` replace `3_000` with `3000`. 

### Affects versions
\>=  1.17.0, Login with Apple with introduced in this version. 

### Expected behavior
Working with iOS 12 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Looks like signin with apple is supported on ios 12+: https://developer.apple.com/documentation/authenticationservices 

Will see if I can get more details.

**Comment by mooreds** [comment]
More details:

* it appears in the ios simulator (you have to install a new simulator, as outlined here: https://stackoverflow.com/questions/60071160/how-install-ios-12-4-4-simulator-on-xcode11 )
* the client is testing on ios 12.2
* the client is using the hosted login pages with the apple idp
* it works fine on later versions of ios (see the support slack channel for videos)

**Comment by jobannon** [comment]
Related to -> https://caniuse.com/mdn-javascript_grammar_numeric_separators

Not being supported in 12.2.
