### ISSUE TITLE
"Sign in with Apple" configurable Redirect URI (Apple Identity Provider)

### ISSUE THREAD

**Issue by matthewhartstonge** [FusionAuth/fusionauth-issues#1527]
### Problem
When the code flow is performed, FusionAuth injects it's own server host name (understandable). This breaks as we are running a cloud based deployment behind a reverse proxy to handle the incompatibility between our current OAuth2 scopes and FusionAuth's Permissions at a different URL to where it is currently hosted/expects. (see: https://github.com/FusionAuth/fusionauth-issues/issues/1481)

The authorise flow is redirected correctly with our app URL: `https://appleid.apple.com/auth/authorize?redirect_uri=https://fusionauth.example.com/oauth2/callback&...` where "`fusionauth.example.com`" is the example domain FusionAuth is reversed proxied from.

But when the code challenge is issued, FusionAuth is sending it's hosted FQDN back, causing the following auth failure, (where "`matts-app.fusionauth.io`" is an example FusionAuth hosted domain):
```
Request to the [https://appleid.apple.com/auth/token] endpoint failed. Status code [400].

Error response is 
{
  "error" : "invalid_grant",
  "error_description" : "redirect_uri mismatch. The code was not issued to https://matts-app.fusionauth.io/oauth2/callback."
}
```

### Solution
- Provide a global configurable Redirect URL for the Apple IDP, here:
![image](https://user-images.githubusercontent.com/6119549/146482927-64f8b485-ffec-4c98-a0b3-b65db9d1db15.png)
- Provide per Application Redirect URL overrides, here:
![image](https://user-images.githubusercontent.com/6119549/146483019-9551c216-9cce-4ef2-9ae4-3e733a0343bf.png)

### Alternatives/workarounds
- Build our own custom proxied sign in implementation (what we want to avoid by using FA) that can fire the required mutated Redirect URI API calls
- Not use Apple Sign in..? 🤷‍♂️😂

### Additional context
This has come off the back of building a customised Go-based reverse proxy to handle backwards compatibility for mapping scopes to FA permissions as suggested via https://github.com/FusionAuth/fusionauth-issues/issues/1481

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@matthewhartstonge 

Are you setting these four headers in your proxy?

```
    X-Forwarded-Proto: typically this will be https. This ensures any redirects are sent with the appropriate scheme.
    X-Forwarded-Host: The original host requested by the client in the Host HTTP request header.
    X-Forwarded-For: The originating IP address of the client.
    X-Forwarded-Server: The hostname of the proxy server.
```

If so, I'm wondering if we aren't respecting them for this particular operation.

**Comment by robotdan** [comment]
Hm... allowing a configurable redirect seems like a really big security risk. Are you suggesting that you still want to redirect to FusionAuth, but just not at the URL we think we are hosted at? 

If so, perhaps this is really a duplicate of this issue? https://github.com/FusionAuth/fusionauth-issues/issues/88

**Comment by matthewhartstonge** [comment]
@mooreds can confirm, required some extra forwarding headers!

Thanks ❤️

**Comment by matthewhartstonge** [comment]
@robotdan as an FYI, I sort of came to a conclusion that it must be configurable as the [API supports it as a field](https://fusionauth.io/docs/v1/tech/apis/identity-providers/apple/#complete-the-apple-login) when manually performing the sign in step by setting `data.redirect_uri` in the request body.

**Comment by robotdan** [comment]
> @robotdan as an FYI, I sort of came to a conclusion that it must be configurable as the API supports it as a field when manually performing the sign in step by setting `data.redirect_uri` in the request body.

Ah, ok. Got it. Yes, I suppose it is configurable in a sense. When using the FusionAuth login pages with this IdP, we set this to our own callback URI, and of course it must be registered ahead of time with Apple. 

From the API perspective you can send in whatever your callback would be (if you're not using our login pages), and then as long as it is registered with Apple it should work just fine.
