### ISSUE TITLE
Add arch type to the node details on the about panel

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1531]
### Description
Since you can run FusionAuth on `amd64`, `arm64`, and other architecture types, it may be helpful to see which arch type in the about panel. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Added a commit, but currently just using Java system properties for `os.name`, `os.version` and `os.arch`. 

This may not give the most accurate info - but outside of this, not sure I can do it in a platform independent way. This may have to be good enough. If anyone else has good ideas, let me know.

**Comment by jerryhopper** [comment]
how about: 

cat /proc/cpuinfo
uname -m 

this should work on all archs, except windows :)
But i think the java props are ok.

**Comment by robotdan** [comment]
In general we don't want to do anything that is platform dependent, and we want Java to do that for us. But I could look at it, but we would only be able to to try it and it it fails, fall back to something else.
