### ISSUE TITLE
FusionAuth flows assistance

### ISSUE THREAD

**Issue by lexCerveza** [FusionAuth/fusionauth-issues#1534]
Good morning.
I'm wondering if FusionAuth solution can assist me in implementing following flows, can you please consult me in those questions ?

First scenario is login / registration of user with login as phone and password + user can reset password using SMS.
Second scenario is login / registration of user with login as phone and password + MFA with SMS code + user can also reset password using SMS.
Third one is passwordless auth using only phone with SMS code.

And also can I use generic messenger with all these flows ?

Thanks in advance and have a nice day

**Comment by mooreds** [comment]
@lexCerveza Thanks for using FusionAuth!

Unfortunately, GitHub issues is for feature requests and bugs with reproduction steps, not for support.

For support questions such as this one, you have two options.

If you have an edition with a support plan (https://fusionauth.io/pricing/ has more details including pricing) you can file a support ticket at https://account.fusionauth.io/account/support/ and the engineering team will respond.

If you do not, please post in our community forum: https://fusionauth.io/community/forum/ Community members and the FusionAuth team responds there on a best effort basis.

You can learn more about FusionAuth technical support here: https://fusionauth.io/technical-support/

Closing this issue, but hopefully I'll see you in one of the two above channels.

**Comment by mooreds** [comment]
Ah, I see you already found our forum and posted: https://fusionauth.io/community/forum/topic/1430/fusionauth-flows-assistance

Glad you made it!
