### ISSUE TITLE
Empty/Invalid JSON object returning  when calling "Retrieve all of the User Actions" api

### ISSUE THREAD

**Issue by f0rever-johnson** [FusionAuth/fusionauth-issues#1537]
##Empty/Invalid JSON object returning  when calling "Retrieve all of the User Actions" api

### Affects versions
Currently using version 1.32.0

### Steps to reproduce
Try to retrieve all of the useractions using the api when no useractions are present.

### Expected behavior
Currently there are no user actions. So I would be expecting a JSON in the following format:
```
{
  "userActions":[]
}
```

### Screenshots
<img width="1306" alt="Screen Shot 2021-12-23 at 11 57 02 AM" src="https://user-images.githubusercontent.com/21150708/147282109-043693f8-a7b1-4b95-baeb-add8bc301358.png">

### Platform
(Please complete the following information)
 - Device: [MacBook Pro]
 - OS: [macOS]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database MySQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Hmmm wonder if this is a documentation issue.

**Comment by f0rever-johnson** [comment]
More like user error; oops. I figured out the issue in my code.

**Comment by mooreds** [comment]
@f0rever-johnson okay, if this isn't a FusionAuth issue, please feel free to close.

**Comment by robotdan** [comment]
We currently configure our JSON serializer to omit empty collections. 

We have discussed changing it to return empty collections. This is likely the better choice. 

It will just mean we have to fix a few thousand tests. 😬

But it sounds like this is working as designed.

**Comment by andrewpai** [comment]
I'm closing this issue as the feature is working as designed. We can capture Daniel's empty collections not in a separate issue.
