### ISSUE TITLE
Update a user registration while retaining the authentication token

### ISSUE THREAD

**Issue by martinec** [FusionAuth/fusionauth-issues#154]
### Description
Hi. I'm currently using version `1.6.0` of fusionAuth and experimenting with the generation of authentication tokens for user registrations. The basic case is as follows:

1. Create a user registration (for an existing user) via `POST /api/user/registration/{userId}`

Request Body:
```json
{
  "generateAuthenticationToken": "true",
  "registration": {
    "applicationId": "[...]",
    "data": {
     "foo" : "bar"
    }
  }
}
```
Response (excerpt):
```json
{
  "statusCode": 200,
  "successResponse": {
    "registration": {
      "applicationId": "[...]",
      "authenticationToken": "[THE-AUTHENTICATION-TOKEN]",
      "data": {
       "foo" : "bar"
       }
      },
    }
  },
}
```
2. Update the user registration (for the same user, change `data.foo` to `"baz"`) via `PUT /api/user/registration/{userId}`

```json
{
  "registration": {
    "applicationId": "[...]",
    "data": {
     "foo" : "baz"
    }
  }
}
```
Response (excerpt):
```json
{
  "statusCode": 200,
  "successResponse": {
    "registration": {
      "applicationId": "[...]",
      "data": {
       "foo" : "baz"
       }
      },
    }
  }
}
```

At the step `2`, I would expect to update the user registration (here `data.foo`), without losing or changing `[THE-AUTHENTICATION-TOKEN]` generated at the step `1`. Is there any way to achieve this?

**Comment by robotdan** [comment]
FusionAuth doesn't currently support merging a user or registration. We do plan to support the `PATCH` HTTP method at some point to allow this type of behavior. 

See https://github.com/FusionAuth/fusionauth-issues/issues/121

For example we may have a `[PATCH] /api/user/registration/data` to allow you to only send user data to merge into the User Registration without having to send in the entire object. 

However, currently you'll need to retrieve the current registration, merge in your changes., and then call the Update API `[PUT] /api/user/registration`.

**Comment by martinec** [comment]
Thank you for the prompt reply and clarification. The Retrive-Merge-Update workaround should suffice for now!
