### ISSUE TITLE
FusionAuth does not allow array object in custom user data

### ISSUE THREAD

**Issue by ngoc199** [FusionAuth/fusionauth-issues#1544]
### Description
I am trying to add a child to a user in FusionAuth. Since I don't really need to create accounts for the children, so I would like to put them as custom user data.

I use this code

```
await axios.patch(
        `${config.iamHost}/api/user/${session.userId as string}`,
        {
          user: {
            email: session.user!.email!,
            data: {
              children: userChildren.push({
                id,
                name: req.body.name,
                dateOfBirth: req.body.dateOfBirth,
              }),
            },
          },
        },
        {
          headers: {
            "X-FusionAuth-TenantId": config.iamTenantId,
            Authorization: config.iamApiKey,
          },
        }
      );
```

The custom user data after executing that code:

![image](https://user-images.githubusercontent.com/53241275/148719696-e37607c0-c696-4b67-a02f-853567435200.png)

I don't know why the data is `children: 1`.

Maybe this is an issue or am I missing something?

**Comment by ngoc199** [comment]
Sorry. It's really my bad.

I place the `push` function, which returns a number, in the request. That's why the data type is number.

**Comment by ngoc199** [comment]
After updating the code, I still have this issue. Since it does update the `children` object, but it's just an object, not an array object.

Is there any way to create an array object as custom user data in FusionAuth?

Here is my updated code

```
await axios.patch(
        `${config.iamHost}/api/user/${session.userId as string}`,
        {
          user: {
            email: session.user!.email!,
            data: {
              children: [...userChildren],
            },
          },
        },
        {
          headers: {
            "X-FusionAuth-TenantId": config.iamTenantId,
            Authorization: config.iamApiKey,
          },
        }
      );
```

**Comment by ngoc199** [comment]
I have managed to do a workaround with `JSON.stringify` and `JSON.parse` to store the array object.

I don't know if there is still another way or this issue should be a feature request, so I will let this issue be here.

**Comment by robotdan** [comment]
We do not place any limits on the type of JSON sent to the API for `user.data`. 

Either of these should work. 

```
data: {
  children: [ {
    "name": "foo"
     "value": "bar"
  } ],
}
 ```
 
 or 
 
 ```
data: {
  children: [ "foo", "bar" ]
}
 ```

**Comment by mooreds** [comment]
Let's move this discussion to the forum since this appears to be a support request, rather than a bug. If it turns out to be a bug we can re-open this issue.

Forum post: https://fusionauth.io/community/forum/topic/1456/custom-user-data-as-array
