### ISSUE TITLE
Add an option to disable IdP linking strategies

### ISSUE THREAD

**Issue by epbensimpson** [FusionAuth/fusionauth-issues#1551]
### Problem
There is no option to disable automatic linking for an IdP

### Solution
An option should be provided to completely disable automatic linking for any given IdP. Using this strategy, if there is no existing link to a user then authentication should fail.

### Alternatives/workarounds
Use the "Create pending link" or "anonymous" strategies.

It may be possible to use a webhook on the `user.login.success` event for this, but _only_ if it will roll back the created link on a webhook failure.

### Additional context
In a single-tenant setup with a large number of IdPs configured, using the email/username linking strategies is not suitable due to the possibility of account takeover by a compromised IdP. 

We do not wish to allow anonymous logins, and we do not wish to allow users to use the pending link. We need to be able to restrict the users able to be authenticated by a particular IdP to those who have pre-existing links.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Tasks
- [x] update docs to reflect new linking strategy.

**Comment by robotdan** [comment]
I think this already works how you're describing.  Selecting one of the following linking strategies will cause the login to fail if the user does not already exist by `username` or `email` respectively. 

- `Link On Email. Do not create the user if they do not exist.` (LinkByEmailForExistingUser)
- `Link On Username. Do not create the user if they do not exist.` (LinkByEmailForExistingUser)

https://fusionauth.io/docs/v1/tech/identity-providers/#linking-strategies

Unless you are indicating you want to manually build the IdP link using the Link API, and then only allow login to succeed for that IdP for users that have been provisioned so to speak with a link to that IdP? If so, that seems like a reasonable idea. 

Please confirm.

**Comment by epbensimpson** [comment]
> Unless you are indicating you want to manually build the IdP link using the Link API, and then only allow login to succeed for that IdP for users that have been provisioned so to speak with a link to that IdP? If so, that seems like a reasonable idea.
> 
> Please confirm.

Yeah this latter bit is what we're looking at - just want to use the API to manage the links explicitly :)

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/130#pullrequestreview-988203803
