### ISSUE TITLE
Advanced registration validation not working with some regex

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#1554]
### Description 
This regex does not appear to work with advanced registration forms:

`^(?!http).+$`

**Comment by robotdan** [comment]
Click testing locally, works for self-service user edits, and advanced registration. Strange, perhaps there was a bug that got fixed. Needs more investigation.

**Comment by robotdan** [comment]
Not a bug in FusionAuth. Some config issues that I resolved.
