### ISSUE TITLE
Add config to re-hash on password change

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1557]
### Description
We currently have a config to re-hash on login. There has been some confusion about why the password is not also re-hashed on password change when this configuration is enabled. 

We should either decide to use this config to also re-hash anytime we rebuild a hash such as password change, or add an additional configuration for re-hash on change to make it explicit. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
My vote: I can't think of a reason to rehash on login and not rehash on password change (or vice versa), so I'd argue for rehashing every time the user provides a password in cleartext.

**Comment by robotdan** [comment]
Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1062
