### ISSUE TITLE
Add support for OpenSearch in addition to Elasticsearch

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1558]
### Description
FusionAuth depends upon Elasticsearch and we also use this in FusionAuth Cloud. Within FusionAuth Cloud we will likely need to move to OpenSearch, and if we do so- it may make sense to just support OpenSearch in a more general sense, and either continue to support Elasticsearch, or just document a change in supported versions with the intention to sunset Elasticsearch support. 

Please comment on this issue if you have an opinion on this direction and any concern with eventually moving away from Elasticsearch. 

### Additional Details
- https://opster.com/guides/opensearch/opensearch-basics/migrate-from-elasticsearch-to-opensearch/
- https://www.opensearch.org/blog/technical-posts/2021/10/moving-from-opensource-elasticsearch-to-opensearch/
- https://aiven.io/blog/migrate-elasticsearch-client-to-opensearch

### Related Issues
- https://github.com/FusionAuth/fusionauth-issues/issues/1256
- https://github.com/FusionAuth/fusionauth-issues/issues/1720

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
In an upcoming release, we'll add some code to try and default to v7 if we can't identify the version from Opensearch, and log the value from the `version.distribution` so we can more easily identify when we're using Opensearch.

**Comment by davelesser** [comment]
@robotdan, as dealing with Elasticsearch isn't our core competency, GPS Insight as strong interest in using OpenSearch and making it Amazon's problem. Will likely be looking into doing this in our dev environment in the very near future - and if successful, moving it to Prod by EOM.

If there's any gotchas to consider - or any collaboration you'd like to have on this - please let me know.

**Comment by robotdan** [comment]
To note, OpenSearch should work, we are running it in dev and have fixed a few minor issues to ensure it is reported correctly. 

We will plan to officially support OpenSearch alongside Elasticsearch in the near future. 

If you do wish to use OpenSearch, please do so, and let us know if you run into any issues so we can identify and resolve them.

**Comment by mooreds** [comment]
This came up on a client call today. They run an opensearch cluster for other applications and wanted to use that for their FusionAuth index as well.

**Comment by robotdan** [comment]
We are using OpenSearch internally- I would expect it to work for clients. I can add it to our min. requirements as a supported form of Elasticsearch.

**Comment by mooreds** [comment]
@robotdan I don't see this here: https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements#elasticsearch

Do we need to add a doc task or keep this open until documented?

**Comment by Aaron-Ritter** [comment]
@robotdan are you internally still using `compatibility.override_main_response_version: true` ?
