### ISSUE TITLE
Feature: Android Client Library

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#156]
### Problem
Need a native FusionAuth client for Android

### Solution
Build an Android client for FusionAuth!

### Alternatives/workarounds
Tweak the Java Client to remove Java8 features that aren't supported on Android.

### Additional context
https://github.com/FusionAuth/fusionauth-java-client/issues/2

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Bounty
This issue qualifies for the FusionAuth bounty program. If you can get an Android client library working, provide a stub and we can build the rest with out template system, see comment below.
https://fusionauth.io/write-for-fusionauth

If you are interested, please contact us using the link provided above and let us know.

**Comment by robotdan** [comment]
I've started a stub repo. 

https://github.com/FusionAuth/fusionauth-android-client

See if you can follow the instructions from the client builder repo to get started.
https://github.com/FusionAuth/fusionauth-client-builder

Here is the template for the Android client:
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/android.client.ftl

When you run the build command  `sb build-android` it will use that template to build the client library.
https://github.com/FusionAuth/fusionauth-android-client/blob/master/src/main/java/io/fusionauth/client/FusionAuthClient.java

You can start by cloning the `fusionauth-client-builder` and `fusionauth-android-client` repos and then start hacking, and then feel free to submit a PR once you've got something working. 

The Android template is just a copy from Java, so you'll essentially just need to remove any Java 8 features such as lambdas. I don't know much about the Android SDK, so if you can't use Jackson then you'll need to rip that and replace it with another JSON library.

I would say to start, just copy over a minimal set of domain objects to get it working. (such as User, Application etc). We are working on a way to build out the domain from a JSON DSL, so once that is ready we can use that to build out the Android domain objects so you don't have to do it manually. 

You can ask any questions you have here, or feel free to join the slack channel as well.

**Comment by ChakshuGautam** [comment]
Hey. Sorry for bailing out earlier. I was the only android resource in the organisation so couldn't find much time then. Can I take it up again, now that we have hired a couple more resources?

**Comment by robotdan** [comment]
Yes @ChakshuGautam that would be great!

**Comment by robotdan** [comment]
Closing this one out. 

The Java client should work already. We would be happy to accept a PR against the client builder to build a more specific version just for Android, but I don't know what that would buy us. 

We are also reviewing a move to OpenAPI which may provide us more options for targeting java clients with specific needs such as Android.
