### ISSUE TITLE
Where can I find the linkedin access token?

### ISSUE THREAD

**Issue by stellanhaglund** [FusionAuth/fusionauth-issues#1565]
On the website it says.

```
FusionAuth will also store the LinkedIn access_token returned from the login dialog in the UserRegistration object inside the tokens Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.
```
but in the UserRegistration object I can only find `linkedin.id`

**Comment by mooreds** [comment]
@stellanhaglund This seems like a support request. Please either open a support ticket https://account.fusionauth.io/account/support (if you have an edition which includes support) or post in the community forum: https://fusionauth.io/community/forum/
