### ISSUE TITLE
OpenId connect does not send client_id on the authorization request

### ISSUE THREAD

**Issue by alexrMEI** [FusionAuth/fusionauth-issues#1569]
OpenId connect does not send client_id on the authorization request

Hi, I’m using FusionAuth as a SSO and need to create an OpenID connection to Feide API so that users can login with their Feide accounts. The problem is that the authorization request sent to Feide API does not contain a client_id, even though I configured it on the Identity Providers section on my FusionAuth admin panel.

FusionAuth version: 1.32.1

### Steps to reproduce
1. Create a new Application
2. Use the react app example and point it to this new Application in order to access the login page (https://github.com/fusionauth/fusionauth-example-react)
3. Create an Identity Provider point to Feide API
4. Access the login page at the react app example and click on the button that leads to Feide authentication page

### Expected behavior
Expected behavior is FusionAuth forwards the query parameters to the IdP the user is trying to log into

Identity Provider Configuration on FusionAuth:
![image](https://user-images.githubusercontent.com/56133627/150371766-a7970c59-adf1-41b8-bfaf-65f3049f90d3.png)

Feide Configuration:
![image](https://user-images.githubusercontent.com/56133627/150372559-8ba7c99c-4c1a-492a-8340-b7b8228948f3.png)

Authorization request:
![image](https://user-images.githubusercontent.com/56133627/150372797-84d3cf9f-cc66-4ecc-8f8d-4a59681d6e5e.png)

Authorization response:
![image](https://user-images.githubusercontent.com/56133627/150372766-765785f5-c6d9-4798-8759-7d1bbc471d08.png)

### Platform
 - Device: Desktop
 - OS: Windows 10
 - Browser: chrome version 97.0.4692.71
 - Database: PostgresSQL version 14.1

### Additional context
FEIDE uses OAuth2 and OpenID Connect

### UPDATE
It seems like the problem was a misconfiguration. The "Use POST method" option should be turned off and the authorization request is successful now.

![image](https://user-images.githubusercontent.com/56133627/150653333-ee01b3da-c80e-4ab0-813c-64f8bb7eef1d.png)

**Comment by mooreds** [comment]
@alexrMEI did you resolve this?

**Comment by alexrMEI** [comment]
> @alexrMEI did you resolve this?

Yes, I did resolved it. Thanks for the reply
