### ISSUE TITLE
Cannot find "allowTokenRefresh" option in application settings

### ISSUE THREAD

**Issue by Nosherwan** [FusionAuth/fusionauth-issues#157]
### Description
I am trying to use the login api provided by fusionauth server to login users for a particular application. (/api/login)
Doing so responds back with a 'token' which I believe is `access_token(jwt)` that can be returned to the user, in addition to returning other user info.
However "refresh_token" is not being sent back.
My fusionauth version is 1.6.0.
I believe this option should be available in the fusionauth UI. However i am unable to find it:

In the documentation this field is referred as follows:
```
application.loginConfiguration.allowTokenRefresh[Boolean]OPTIONALDefaults to falseAVAILABLE SINCE 1.5.0

Indicates if a JWT may be refreshed using a Refresh Token for this application. This configuration is separate from issuing new Refresh Tokens which is controlled by the generateRefreshTokensparameter. This configuration indicates specifically if an existing Refresh Token may be used to request a new JWT using the Refresh API.If you do not intend to use the Login API, and instead will only be using the OAuth endpoints, you may leave this set to false to ensure Refresh Tokens cannot be used outside of the Refresh Token Grant.
```

**Comment by robotdan** [comment]
This is configured in the Application configuration. 

See Applications --> Security Tab.

There you will find a toggle that says Generate refresh tokens.

Let me know know if you don't see it.

**Comment by Nosherwan** [comment]
Thanks @robotdan however those two options are already on as you can see from my screenshot:
<img width="314" alt="Screen Shot 2019-05-08 at 1 28 29 pm" src="https://user-images.githubusercontent.com/138489/57347325-40a2fd00-7195-11e9-8f03-3888ebe3bf84.png">

**Comment by robotdan** [comment]
Great, ok, so you have it configured correctly. 

In order to receive a refresh token, you'll need to be logging into an application, so be sure you're passing an `applicationId` in the request body. 

For example, where `f5cd2ca4-d9d2-4006-9c80-54b13ed34b25` is your Application Id:

```
{
  "loginId": "user@example.com",
  "password": "password",
  "applicationId": "f5cd2ca4-d9d2-4006-9c80-54b13ed34b25"
}
```

https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user

**Comment by Nosherwan** [comment]
All right thanks this is working now.
