### ISSUE TITLE
User Roles May Not be Immediately Available for use in user registration

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1575]
### Description 
When creating new users roles, they are not immediately available to assign to a user registration.

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 
Local dev - 1.32.1

### Steps to reproduce
1. Make an application role
2. Immediately try and assign it to a user and registration (via API or client lib) within milliseconds of completing step 1.

### Expected behavior
Once the role is created, it should be available to assign to a user registration.

### Platform
Local dev - 1.32.1

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1452

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
https://inversoft.slack.com/archives/C02PT1ZN13R/p1642803464041800

The workaround is to add a sleep or delay after initial role creation and before assignment to that user and their registration

### Internal 
- https://github.com/FusionAuth/fusionauth-app/pull/115
- https://github.com/FusionAuth/fusionauth-api/pull/50

**Comment by SinghDivneet** [comment]
What do mean by immediately assign? 
Since I am facing a scenario where after assigning the correct roles to a user, the user doesn't have access.

**Comment by jobannon** [comment]
@SinghDivneet Likely your issue is unrelated.  This is related to the timing of role creation and then the assignment of the newly created role to user registration.

If you feel that you have another bug, please feel free to file an issue.  If you feel, rather, that your issue is related to how you are integrating your application and user roles, please feel free to post in the Forum for additional assistance.

- https://fusionauth.io/community/forum/

Thanks!

**Comment by martin-probst** [comment]
Experienced this too in 1.33.0. After adding a new role to an application via `createApplicationRole` (@fusionauth/typescript-client), I cannot immediately assign the newly created role to any user via `patchRegistration`. It gives me a field error claiming the role wouldn't exist for up to 20 seconds (!) after the initial request. Then it suddenly works without any further changes.
Retrieving the application however via `getApplication` shows the new role instantly after adding it.
