### ISSUE TITLE
Sign up users who download FusionAuth for newsletters by default

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1577]
### Problem

Currently users can check a box on maintenance mode to sign up for the monthly FusionAuth newsletter. This is to say, the user has to opt-in. 

### Solution

In order to both increase the number of newsletter subscribers and make it easier for folks to be informed of FusionAuth news, it'd be great to default users to be subscribed.

To be clear, this is changing the checkbox from unchecked by default (so users have to opt-in) to checked by default (so users must opt-out) on the initial setup wizard screen. Of course, users who sign up for the newsletter can unsubscribe at any time, as they are able to now.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/112
- This does not affect kickstart activation path.
