### ISSUE TITLE
Allow option for step-up or re-auth when changing email or password via self-service forms

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1578]
### Problem
When using the self-service forms in FusionAuth, if you configure the email address, username or password as an option for the user to change, this can be done without additional step-up or re-auth. 

### Solution
Provide some additional options for these forms such as:

1. Require MFA step up if enabled, or perhaps just a forced email step-up
2. Require a re-auth, i.e. re-login if your session is more than n seconds old. 
3. Require the user to enter their current password to change their password. This is possible via the API already, but not available in the self-service form. 

### Alternatives/workarounds
Don't let the user change their email or password, build your own form using the API. 

### Additional context
NA

### Related Issues
- https://github.com/FusionAuth/fusionauth-issues/issues/1
- https://github.com/FusionAuth/fusionauth-issues/issues/960

### Documentation
- [ ] API changes

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/232

**Comment by mooreds** [comment]
The API needs to be updated for this, the check APIs job is still failing: https://github.com/FusionAuth/fusionauth-site/actions/runs/4724597382/jobs/8382004992 (scroll to the bottom)

**Comment by mooreds** [comment]
@andrewpai the doc never was written (or at least not merged). I just did that in 2190.
