### ISSUE TITLE
Can try to assign entities in one tenant to a user in a different tenant in admin UI

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1579]
### Description 

In the user interface, I can see entities that are associated with a different tenant. If I try to assign the user the entity, I get an exception in the UI and the logs (Event Log entry attached).

### Affects versions
1.30.1, 1.32.0

### Steps to reproduce

1. Create two tenants, A and B
2. Create an entity type
3. Create an entity in tenant A, call it 'foo'.
4. Create a user in tenant B
5. Manage the user in the UI, go to the 'entity grants' tab.
6. Search for 'foo'.
7. It appears.
8. If you try to assign 'foo' to the user in tenant B, you get an exception.

### Expected behavior

You should never see entities from a different tenant when searching for them to grant to a user.

### Screenshots
![Screen Shot 2022-01-31 at 12 08 41 PM](https://user-images.githubusercontent.com/91825/151856823-1a231a6e-01d4-4b73-b6d4-2fd672c1e591.png)
[entity-exception-freemarker.txt](https://github.com/FusionAuth/fusionauth-issues/files/7973482/entity-exception-freemarker.txt)

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/118
