### ISSUE TITLE
The OAuth2 Password Grant is missing the twoFactor Method Ids required to completed 2FA

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1585]
### Description 

The Password Grant doesn't give you back enough information to complete MFA. In particular, you don't get back the `methodId`s.

Unsure about the other grants, but we should check the implicit and the device grants as well.

### Affects versions
`>= 1.26.0`

In version `1.26.0` we introduced some advanced Two-Factor options that made some adjustments to the Two-Factor APIs. This endpoint needs to return the same info that the Login API returns. 

### Steps to reproduce

1. Create an application
2. Register a user for that application
3. Enable MFA for that user
4. Enable the password grant on that application
5. Login using the password grant
6. Examine the returned values

The methodId is not returned.

Note that the twoFactorId is returned, but not documented: https://fusionauth.io/docs/v1/tech/oauth/endpoints/#resource-owner-password-credentials-grant-request

### Expected behavior

We should support returning both the methodId and the twoFactorId so the integrator can handle MFA correctly.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Raised in this forum post: https://fusionauth.io/community/forum/topic/1481/get-list-of-enabled-mfa-methods-with-methodid

Discussed further here: https://github.com/FusionAuth/fusionauth-site/issues/1210

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1704

### Documentation
- [x] Ensure the Token endpoint doc is updated for this and explains how to use it

**Comment by robotdan** [comment]
Moving doc task to https://github.com/FusionAuth/fusionauth-issues/issues/1704
