### ISSUE TITLE
Get all Tenants Not Returning All Tenants with All Tenants Super Key

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1586]
### Description 
When calling Get All Tenants, the request fails with the below message.  The API key is scoped to `all tenants` and the headers only specify `Authorization: <my_all_tenants_api_key>`

https://fusionauth.io/docs/v1/tech/apis/tenants/#retrieve-a-tenant

### Affects versions
1.30.1

### Steps to reproduce
1. Access `api/tenant` endpoint with a GET request
2. Use API auth, and use a super key with no restrictions
3. See Error Message

```
{
	"generalErrors": [
		{
			"code": "[restricted]",
			"message": "Your request is not allowed. You cannot create a tenant, or retrieve all tenants using a tenant restricted request. Omit the X-FusionAuth-TenantId HTTP header if provided, or repeat the request with an API key that it not assigned to a particular tenant."
		}
	]
}
```

### Curl Command

```
curl --request GET \
  --url http://<host>/api/tenant \
  --header 'Authorization: <key>'
```
  
### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Internal: ticket 72240

**Comment by robotdan** [comment]
Closing as unreproducible. If anyone can reproduce, please re-open and we will take a look.
