### ISSUE TITLE
Startup script doesn't have curl opts to download jdk

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1588]
### Description 

The startup script, if you install via fastpath, doesn't handle redirects.

### Affects versions

1.32.1

### Steps to reproduce

1. curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh > install.sh
2. sh install.sh
3. examine fusionauth/bin/startup.sh, it is missing options.

### Expected behavior

the startup.sh script will follow redirects, with the correct curl options.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Pulling over from here: https://github.com/FusionAuth/fusionauth-install/issues/10

Not sure where the startup.sh script is pulled from, as this one looks okay: https://github.com/FusionAuth/fusionauth-app/blob/master/src/main/bin/startup.sh

**Comment by robotdan** [comment]
If this is for the startup script inside FusionAuth, it is likely already resolved. Likely a dup of https://github.com/FusionAuth/fusionauth-issues/issues/1519 ? 

If this is a bug in the fast path script itself, you can submit a PR against https://github.com/FusionAuth/fusionauth-install/blob/master/install.sh.

**Comment by mooreds** [comment]
Sure looks like a duplicate to me.
