### ISSUE TITLE
arm64 Containers (And possibly all non-amd64) contain amd64 JRE and fail to start.

### ISSUE THREAD

**Issue by kevcube** [FusionAuth/fusionauth-issues#1590]
### Description 
Duplicate of https://github.com/FusionAuth/fusionauth-containers/issues/77

### Affects versions
fusionauth/fusionauth-app:latest arm64, possibly all arm64 releases, possibly all non-amd64 releases.

### Steps to reproduce
1. `docker run -ti --rm --user 0:0 --platform linux/arm64 fusionauth/fusionauth-app:latest bash`
2. `apt-get update; apt-get install -y file; file /opt/openjdk/bin/java` (shows x86-64 executable)
3. `/opt/openjdk/bin/java` (fails)

### Expected behavior
JRE is arm64 version, container starts.

### Screenshots
<img width="428" alt="Screen Shot 2022-02-04 at 4 21 21 PM" src="https://user-images.githubusercontent.com/716806/152619317-f4266b6d-eac7-45aa-bcf6-f01bd4d48a11.png">

### Platform
(Please complete the following information)
 - Device: m1 Mac
 - possibly all other non-amd64 images, haven't checked.

### Community guidelines
I crossposted, sorry, but I feel it's warranted by broken code in `latest`

### Additional context
Again, unsure if this affects more than just `arm64`, those should really be checked as well.

**Comment by kevcube** [comment]
checked arm/v7, that also has x86-64 JRE. I'd guess this affects every arch.

**Comment by robotdan** [comment]
Will review and resolve via https://github.com/FusionAuth/fusionauth-containers/issues/77.
