### ISSUE TITLE
Change "Rate limit" message

### ISSUE THREAD

**Issue by juansedo** [FusionAuth/fusionauth-issues#1596]
### Problem
When you configure rate limit, the following message cannot be changed:
![image](https://user-images.githubusercontent.com/52968530/153903329-273ca9de-49de-4565-b17b-806777451655.png)

It does not appear in "Messages" on the Theme Customization.

### Solution
Text variable in "Messages" on the FusionAuth theme.

**Comment by robotdan** [comment]
Have you tried adding `[RateLimitedException]=Another message` to your theme? If that works, we may just need to add the default message to the theme to make it more obvious it can be modified.

**Comment by robotdan** [comment]
@juansedo have been able to try the suggestion above?

**Comment by juansedo** [comment]
Hi @robotdan, yes.
It works so well, thanks!

**Comment by robotdan** [comment]
Great! Thanks for the update. I’ll verify we are shipping that message in our default theme.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/621
