### ISSUE TITLE
failed startup FusionAuth

### ISSUE THREAD

**Issue by gkrothammer** [FusionAuth/fusionauth-issues#1597]
Hi all,

I follow 5-Minute Setup Guide  to install in my computer.
I using Windows PowerShell to install FusionAuth with that command 

```
. { iwr -useb https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.ps1 } | iex; install
```

After installing, I try to run the following command "fusionauth/bin/startup.bat" to start FusionAuth, the start is skipping and not installed.

How can I fix it?

![image](https://user-images.githubusercontent.com/97830039/154021079-883de0b5-25f6-4e7d-ba5d-be1fdc6a8011.png)

Thanks

**Comment by robotdan** [comment]
Questions:
- What version of windows are you running?
- Are you running in PowerShell or CMD?
- Are you running the shell with elevated privilege or a normal user?

Thanks

**Comment by gkrothammer** [comment]
Hi,
 - Windows 10 pro
 - I tried via PowerShell and CMD
 - I run as administer

**Comment by gkrothammer** [comment]
@robotdan

**Comment by robotdan** [comment]
Thanks @gkrothammer 

As a work around, please edit `startup.bat` and replace `set FUSIONAUTH_JAVA_DIR=%~dp0..\java` with `set JAVA_DIR=%~dp0..\java` and see if that fixes the issue for you.

**Comment by gkrothammer** [comment]
Hi,

After edit 'startup.bat', the same error appears.
May there is another thing to do for fixing that issue?

Thanks

**Comment by James-M-Oswald** [comment]
> Thanks @gkrothammer
> 
> As a work around, please edit `startup.bat` and replace `set FUSIONAUTH_JAVA_DIR=%~dp0..\java` with `set JAVA_DIR=%~dp0..\java` and see if that fixes the issue for you.


Hi,

I have had the same issue, i have done the fix mentioned above, which bypassed this issue... However fusionauth starts, as far as powershell is concerned, but never loads into localhost so i cant access maintenance mode - any ideas?

Thankyou

**Comment by robotdan** [comment]
@James-M-Oswald that looks to be a different issue. Can you open a new issue and see if you can collect the tomcat log as well? If there is anything else interesting in there it will be `apache-tomcat/logs` I think. 

On startup, we'll attempt to bind `9010`, `9011`, ``9013` and `9019`. If those ports are in use by another service, startup will fail. If that is the case, you can change the ports in the FusionAuth config file.
