### ISSUE TITLE
Missing JWTConfiguration.js

### ISSUE THREAD

**Issue by netadvanced** [FusionAuth/fusionauth-issues#160]
### Description 
There is a 404 error for /js/admin/JWTConfiguration.js when loading the home page and others.
http://fqdn:9011/js/admin/JWTConfiguration.js?version=1.6.1
The same error seems to exist in 1.6.0, haven't tried others

### Steps to reproduce
1. Go to the homepage and any subsequent pages
2. You'll find the 404 error on the browser debugger

### Expected behavior
Not sure of the impact it has... !? So far haven't come across an error referring to that file.

### Screenshots
n/a

### Platform
 - Server: Docker swarm image
 - Client: MacOS, Chrome browser

**Comment by robotdan** [comment]
Thanks @netadvanced for reporting this issue! This is a known issue that has been resolved and will be fixed in the upcoming release. 

There is not adverse side affects of this error as far as I am aware.
