### ISSUE TITLE
Ship keycloak compatible password hashing plugin

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1604]
### Problem

People want to migrate from Keycloak to FusionAuth, but preserve user passwords.

### Solution

There's an example plugin mentioned in the guide: https://fusionauth.io/docs/v1/tech/migration-guide/keycloak but gosh it'd be great if it shipped with FusionAuth instead of requiring a custom plugin install.

### Alternatives/workarounds

Install the plugin manually.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
@mooreds this is shipped, and doc updated except for KeyCloak migration guide.
