### ISSUE TITLE
Facing issues while creating users using AWS RDS postgres 13.4

### ISSUE THREAD

**Issue by SinghDivneet** [FusionAuth/fusionauth-issues#1610]
### Description
After creating the initial superuser unable to create new users, getting the following error on the UI 

`You do not have access to that function or the FusionAuth App Application. Please contact your system administrator. You may also see this if you sat on a form too long and then tried to a submit. In these cases our CSRF protection kicks in and lands you here. If you think that is what happened, go back and retry and you'll be fine.`

I wasn't on the page for too long **neither can I find anything in pod logs** 

Environment details

EKS : 1.21
Postgres rds : 13.4

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
@SinghDivneet 

Hmmm.

Can you connect to the database using the user you created? Can you try to create the database user and tables using the SQL scripts and set up FusionAuth to connect directly? https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app#advanced-installation

**Comment by robotdan** [comment]
I don't see any evidence that this would be related to RDS or the version of Postgres. Does this same thing not happen if you use a different version of Postgres?

This error indicates you are failing CSRF validation in some fashion. If you are using a proxy of any kind, you need to be sure the appropriate `X-` headers are being added.

**Comment by andrewpai** [comment]
Closing this as it no longer seems to be an issue.
