### ISSUE TITLE
OpenID connect fails with Azure AD

### ISSUE THREAD

**Issue by gkrothammer** [FusionAuth/fusionauth-issues#1611]
Hi! Following the 1.33.0 FuisonAuth version, I'm unable to use Azure AD for authenticating. The OpenID Connect button will send me to microsoft login page, which redirects back correctly to FusionAuth, but then fails with the following message:

I'm using the FusionAuth Example: React app from: https://github.com/FusionAuth/fusionauth-example-react

"An email address was not provided for the user. This account cannot be used to login, unable to complete this login request."

![Capture](https://user-images.githubusercontent.com/97830039/155969057-f748ffdd-edac-4f39-9adf-5c1791cd6cb5.PNG)

I would expect to be authenticated successfully and redirected back to my application. Instead, I get an error about a failed request to the OpenID Connect.

**Comment by mooreds** [comment]
@gkrothammer can you please share the debug logs? If you turn on debug on the OIDC Identity Provider, you can find them at System -> Event Log. Please remove any sensitive information.

Also, if you have a reconcile lambda associated with this Identity Provider, please share that code.

Finally, what is the identity linking strategy you are using?

**Comment by jobannon** [comment]
Closing as working as designed.

**Comment by maxbeaudoin** [comment]
Using the v2.0 issuer fixed it for me.

`https://login.microsoftonline.com/{tenantId}/v2.0`
