### ISSUE TITLE
Fusionauth-localization releases sync?

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1613]
### Description

Latest release of FusionAuth is currently `v1.34.1`. However, this release does not exist on the related fusionauth-localization repository.

My setup script automatically try to fetch the french translation from that repository during the setup. Because of that, it end with a `404 Not Found` error:

```
Service 'static' failed to build : The command '/bin/sh -c wget https://github.com/FusionAuth/fusionauth-localization/archive/${VERSION}.zip --output-document locales.zip' returned a non-zero code: 1
```

Also, I see you updated some translations, for example with [`v1.33.0`](5f4cee67e7d372f989bba1c493c99c36017e8951), but without any release.

So I am not sure about how to handle that. Are the release system abandoned on that repo? Can I safely rely on master if the target release does not exists?

Thanks

**Comment by mooreds** [comment]
Hmmm. Maybe we need to uncomment release.release or otherwise add something to add a tag to the fusionauth-localization repo

https://github.com/FusionAuth/fusionauth-localization/blob/master/build.savant#L61

**Comment by mooreds** [comment]
@soullivaneuh we need to do some internal work around automating the release tags for the fusionauth-localization project. We've automated copying over the messages file, but need to set things up to release correctly. This may take some time due to other internal priorities.

**Comment by mooreds** [comment]
@robotdan I took a look at the release process and I think that all I had to do was enable the release plugin for fusionauth-localization. From what I can tell, it should be included and tagged properly in the next release. Hard to tell without doing a release, though.

**Comment by robotdan** [comment]
I had commented that out because it broke the release. I'll have to do some more work on the build to get it to work properly when we do a full release.

**Comment by mooreds** [comment]
I guess I don't know what I don't know :) .

Would you like me to comment out the change I made or is there any other way I can help diagnose this problem? 

Or is it best left in your hands?

**Comment by robotdan** [comment]
The last release broke again.. but I think I finally figured out the issue and corrected it. It should work going forward.

**Comment by robotdan** [comment]
I think is is mostly working. Anyone see any reason not to close this one out?

**Comment by mooreds** [comment]
https://github.com/FusionAuth/fusionauth-localization/tags looks good, I'll close.
