### ISSUE TITLE
Log files with Docker instance

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1614]
### Description

According to your [documentation](https://fusionauth.io/docs/v1/tech/admin-guide/monitor#log-files).

> The system log files will be placed in the logs directory under the FusionAuth installation unless you are running FusionAuth in a container. In the latter case, the log output will be sent to STDOUT. 

That's okay, but do we have any way to tell FusionAuth to store logs by file even on a dockerized instance?

If not, it would be great to have the option.

The goal is to persist the data on a volume binding system with log rotate. Also, it will allow to access the logs directly from the amin UI.

Thanks

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Hiya @soullivaneuh 

This is a docker issue. I'd suggest you set up a logging driver. From a brief look it seems like this is a runtime option.

More details: https://docs.docker.com/config/containers/logging/configure/ / https://docs.docker.com/config/containers/logging/

I am closing and suggest we continue discussion on the forum. https://fusionauth.io/community/forum/topic/1549/want-access-to-my-docker-logs
