### ISSUE TITLE
Login records download is broken

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#1616]
### Description 
On admin, go to system -> login records and click the download button (top right). It'll try to compile all records into a file, which in our case aways fails (we have millions). It doesn't respect any sort of filtering from the UI to export a smaller number.

### Affects versions
1.19.8

**Comment by robotdan** [comment]
Not much to go on here, can you add any additional detail? 

- What is the symptom in the UI?
- Is there a stack trace in the log?
- Does it work in general, but the file is not sorted how you want, and is not filtered according to the current filter on the UI?
- Does it work if you use the API?

**Comment by AlvMF1** [comment]
- None, apart from the download request failing (see attachment)
- I don't have access to logs, aside from ones provided by the admin UI.
- I was never able to download a file, even when I filter down to a day. So, I'm assuming it tries to compile a list of all records.
- I didn't now there was an API for that. Which one is it? Where talking about login records (URI ends with /admin/system/login-record).
- Can't say for sure, because we'd have to upgrade our production instances to the latest version to double-check.

<img width="247" src="https://user-images.githubusercontent.com/15204146/156673245-82f722b0-b863-4b7d-8c44-9a1cb9809724.png">

**Comment by mooreds** [comment]
I'd suggest using the API to pull down records in smaller groups. You can pull down records within a certain time period: https://fusionauth.io/docs/v1/tech/apis/login#export-login-records

**Comment by robotdan** [comment]
All of the logs are accessible though the UI. System > Logs. 

Without a trace we won’t have much to go on.

**Comment by robotdan** [comment]
@mooreds suggestion may be a work around.  It the download action in the UI is designed to work even with millions of records. I would expect it to work regardless of the number of login records.
