### ISSUE TITLE
Email registration returns error 500 when it start with @

### ISSUE THREAD

**Issue by pablomadrigal** [FusionAuth/fusionauth-issues#1617]
### Description 
When entering invalid data at email field ,  the web page displays an 500 Internal server Error.
This seems to be happening only when entering first an '@' followed by any other value

### Affects versions
FusionAuth™ version 1.30.2

### Steps to reproduce

1. Open one application with registration form 
2. Enter in the email field: "@invalid.com"
3. Submit the form

### Expected behavior
Email field should display a message indicating ‘Invalid Email’

### Screenshots
![63409ded-83a9-40ad-aeb9-82147d1e4396](https://user-images.githubusercontent.com/22465189/156632356-bf8a71b0-3b3c-4f1d-87dd-885f495d4509.png)

### Platform
Chrome Versión 98.0.4758.109

**Comment by robotdan** [comment]
Thanks for reporting @pablomadrigal . When this type of error occurs, there will be a stack trace in the logs, that trace will be super helpful to understand what occurred. 

The issue is most likely a missing message such as `[notEmail]=Invalid email`.

**Comment by pablomadrigal** [comment]
We have also found some error with the validation, and people can sing up with emails which do not contain a domain value ie ‘com, net, org’ etc…

We try to use Regex in the email form field, but it doesn't take it in count

**Comment by mooreds** [comment]
@pablomadrigal please open a separate issue with examples of regular expressions where validation fails.
