### ISSUE TITLE
How we can check If refresh token is expired?

### ISSUE THREAD

**Issue by jinalptl1993** [FusionAuth/fusionauth-issues#1622]
I am using fusionauth in my Next Js application. 

In my API, I am checking If the access token is expired or not. If the token is expired, I am generating a new token based on the refresh token.

Sometimes I am facing that while renewing access token I am getting 400 so that means refresh token is expired and my API got failed and user redirected to home page suddenly.

What I would like to check is, whenever the application gets loaded at that time check If a refresh token is valid for the next 24 hours or not. If expired then redirect to the home page else user can visit the requested page.

Thanks a lot in advance!

**Comment by jinalptl1993** [comment]
@mooreds  @voidmain @robotdan @ebahsini 
Could anyone please help me with this question?

Thanks a lot in advance!

**Comment by mooreds** [comment]
@jinalptl1993 

Thanks for using FusionAuth!

For FusionAuth, GitHub issues are not for support. They are for feature requests and bug fixes. 

If you'd like support, you have two options:

* pay for support by buying an edition with support included. This will give you access to the engineering team via a slack channel or ticketing system. You can learn more and buy this here: https://fusionauth.io/pricing
* ask a question in our community forum: https://fusionauth.io/community/forum/ 

Hope this helps.

Closing as this is better suited for the forum.
