### ISSUE TITLE
User can Sing up with a password containing white spaces

### ISSUE THREAD

**Issue by pablomadrigal** [FusionAuth/fusionauth-issues#1626]
### Description 
Users can sing up with passwords which contains white spaces like '<1        >, <1        1>, '

### Steps to reproduce
1. Open one application with registration form
2. Enter in the Password field: <1       > (Enter seven whitespaces followed by any other character)
3. Submit the form

### Expected behavior
Password field should display a message indicating ‘Invalid password’

**Comment by mooreds** [comment]
@pablomadrigal a few questions to help us with this issue:

   * why should whitespace be disabled? That is a valid character for a password typically.
   * Do you have any password validation rules enabled at the tenant level?
   * Are you using the hosted login pages or your own custom pages for the password field? 
   * What version of FusionAuth are you using?

Thanks.

**Comment by pablomadrigal** [comment]
1. We need to disabled whitespaces because it is very easy to get confused when saving the password. We prefer to make it easy for users that part
2. We have minimum and maximum length, and don't require anything more complicate
3. we are using hosted login page, with some changes on the Theme
4. Version 1.30.2

**Comment by mooreds** [comment]
You should be able to use the validation `^[^ ]*$`. Does that work?
