### ISSUE TITLE
Remove Nashorn

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1631]
### Description

Per https://github.com/FusionAuth/fusionauth-issues/issues/571 we are using a new, better JS execution engine.

This is a placeholder issue for officially marking Nashorn as deprecated, and then setting a version for complete removal.

### Related Issues
- https://github.com/FusionAuth/fusionauth-issues/issues/571
- https://github.com/FusionAuth/fusionauth-issues/issues/1828

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Duplicate
- https://github.com/FusionAuth/fusionauth-issues/issues/1828
