### ISSUE TITLE
Option to make two factor authentication mandatory

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1637]
### Problem
In order to improve our ecosystem security, we need to make two factor authentication (2FA) mandatory.

### Solution
A way to set the 2FA as mandatory for any user. Should be configurable at the application level and/or the tenant level.

### Alternatives/workarounds
No workaround possible on FusionAuth.

### Additional context

Related issues:

* https://github.com/FusionAuth/fusionauth-issues/issues/197
* https://github.com/FusionAuth/fusionauth-issues/issues/763
* https://github.com/FusionAuth/fusionauth-issues/issues/960

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
Added some related issues. You may want to review and upvote.

**Comment by shortstack** [comment]
would also love to see this. following along.

**Comment by robotdan** [comment]
Planning to deliver via https://github.com/FusionAuth/fusionauth-issues/issues/197. 

The current plan is to allow this to be set as required at the tenant, or application level. No current plan to offer more granular configuration to the user level (as an example). 

@shortstack or @soullivaneuh do you see a requirement to enforce this down to the user level, and if so, can you describe your use case and how you might want to identify a user that requires MFA during login?

Thanks!

**Comment by shortstack** [comment]
@robotdan in our use case, we would only want it at the application level. i don't think we'd need it at the user level, since we want it enforced everywhere. but i could see that being valuable in other scenarios.
