### ISSUE TITLE
FIDO U2F for multi factor auth

### ISSUE THREAD

**Issue by ghost** [FusionAuth/fusionauth-issues#164]
### Problem
Permit usage of security key (USB stick) like Google, OVH and others permit for multi factor authentication

### Solution
Implement U2F in FusionAuth

### Alternatives/workarounds
None, because OTP will be required to access account when USB doesn't work or when using mobile

### Additional context
It's also to have the possibility to use FusionAuth from September 2019 in Europe due to SCA (Strong Customer Authentication)
For example : https://stripe.com/en-fr/guides/strong-customer-authentication

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Related to https://github.com/FusionAuth/fusionauth-issues/issues/77

**Comment by robotdan** [comment]
Thanks @colundrum for opening this request! This is definitely on the roadmap, we hope to get support for FIDO U2F out this summer.

**Comment by robotdan** [comment]
A possible native integration with https://www.hypr.com may satisfy this requirement.
See similar issue https://github.com/FusionAuth/fusionauth-issues/issues/77

**Comment by robotdan** [comment]
Going to close this one out and resolve under #77 .
