### ISSUE TITLE
Invoked Lambda during the UserInfo endpiont to populate the response

### ISSUE THREAD

**Issue by themobi** [FusionAuth/fusionauth-issues#1647]
### Problem
At the moment, we can only populate JWT during the token endpoint to populate the response and it really works fine but it has a cost, it increases the size of a token while some WAF providers has limitation on header size so we can not pass that heavy sized token from client app to backend webservice.

### Solution
If there is a Lambda that can be invoked during the UserInfo endpoint to populate the response instead of only relying upon the contents of the JWT sent to the endpoint will be beneficial.

### Additional context
- https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo

### Related issues:

* https://github.com/FusionAuth/fusionauth-issues/issues/1582
* https://github.com/FusionAuth/fusionauth-issues/issues/308
* https://github.com/FusionAuth/fusionauth-issues/issues/659
* https://github.com/FusionAuth/fusionauth-issues/issues/1475
* https://github.com/FusionAuth/fusionauth-issues/issues/1582

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/400

**Comment by andrewpai** [comment]
Userinfo lambda added in 1.50.0!
