### ISSUE TITLE
Preview Functionality on Theme Pages for Account Edit Fail

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1649]
### Description 
When previewing account edit, sometimes a freemarker exception can be thrown.

### Affects versions
Lastest

### Steps to reproduce
Try and preview the Account edit page.  Sometimes the preview will fail.

This was the specific code which caused the failure

```
[#list fields as fieldKey, fieldValues]

  [#-- Section labels  --]
  [#assign sectionNumber = fieldKey + 1/]
  [#assign sectionLabel = generateSectionLabel(sectionNumber, tenantId) /]
  [#if sectionLabel?has_content]
    <legend> ${sectionLabel} </legend>
  [/#if]

  [#list fieldValues as field]
    [#if field.key == "user.password"]
      [@helpers.passwordField field/]
    [#else]
      [@helpers.customField field=field key=field.key autofocus=false placeholder=field.key label=theme.optionalMessage(field.key) leftAddon="false"/]
      [#if field.confirm]
        [@helpers.customField field "confirm.${field.key}" false "[confirm]${field.key}" /]
      [/#if]
    [/#if]
  [/#list]
[/#list]
```

### Expected behavior
Account Edit should be able to be previewed.

### Screenshots
![Screen Shot 2022-03-25 at 2 14 36 PM](https://user-images.githubusercontent.com/16090626/160190506-cf2ad861-d2cd-4e46-8607-0fec37b1d42d.png)
![Screen Shot 2022-03-25 at 2 14 10 PM](https://user-images.githubusercontent.com/16090626/160190510-79b6149c-989f-403d-bd41-30b334eefe03.png)

### Platform
(Please complete the following information)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Internal
https://inversoft.slack.com/archives/C02PT1ZN13R/p1648236200818219

**Comment by robotdan** [comment]
Internal notes:
We need to ensure we build the correct collection type for `fields` when previewing this page regardless of the application registration type.

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/212
