### ISSUE TITLE
Adding mobilePhone in User Search

### ISSUE THREAD

**Issue by petechungtuyco** [FusionAuth/fusionauth-issues#165]
### Description
In my use case, I need to check whether the mobile number has been used by another user. But when I try to search in the user using `mobilePhone:<number>` it returns 0 user. Is there any way to add the mobilePhone in the search index of Fusion Auth.

Thanks in advance!

**Comment by robotdan** [comment]
Hi @petechungtuyco thanks for making this request. 

Yes, this is something that should be in the search index, we'll get this into the upcoming release.
