### ISSUE TITLE
`email verified` email is not triggered for re-send email-verification flow.

### ISSUE THREAD

**Issue by ashutoshningot** [FusionAuth/fusionauth-issues#1651]
## (Put bug title here)
`email verified` email is not triggered for re-send email-verification flow.

### Description 
`email verified` template works perfectly for the first-time verification but if the verification link expired and the user clicks on resend email at that time after completing verification, the email is not triggered.

### Affects versions
1.31.0

### Steps to reproduce
1. Enable Email verification for application
2. Create User
3. Verification email will be sent, but do not verify. (Email verified is triggered if click/verified form first verification)
4. Click or hit resend verification email.
5. Now do click/verify.
6. Email verified email is not triggered from second verification.

### Expected behavior
`Email verified` should be sent.

### Screenshots
NA

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Ubuntu 16
 - Chrome : 97.0.4692.99
 - Database : PostgresSQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
This problem does not impact verification flow But creates ambiguity in verification flow for some users.

**Comment by andrewpai** [comment]
Shipping in 1.50.0.
