### ISSUE TITLE
Webhook custom error response

### ISSUE THREAD

**Issue by tristanbabasa** [FusionAuth/fusionauth-issues#166]
### Description
Hello Team. 

We are implementing extended validations on the user.create event via webhook.
But unfortunately we are only receiving this type of response when sending errors on webhook.

`{
    "generalErrors": [
        {
            "code": "[WebhookTransactionException]",
            "message": "One or more webhooks returned an invalid response or were unreachable. Based on your transaction configuration, your action cannot be completed."
        }
    ]
`}

Is there a way to pass a custom error code from the webhook so that we can determine from the api the type of error happened on the webhook?

**Comment by robotdan** [comment]
Thanks for taking the time to open this issue @tristanbabasa . 

Do you have more than one webhook configured to receive the event? 

One option would be to create an event log which is viewable from the UI and retrievable from an API. We may also be able to enhance this error to contain additional information.

I'll look into what the options could be to make this error more helpful.

**Comment by tristanbabasa** [comment]
@robotdan Currently we only have one webhook to have a custom check on some parameters passing through the event. So we need a way to pass some parameters on the error response to be handle by the UI.

I'll look into event logs as an interim solution.

Thanks.

**Comment by robotdan** [comment]
> I'll look into event logs as an interim solution.

In case I confused the issue, this is not available yet. This is something we could add on our end. One option you have now is to use the test feature. 

If you navigate to your Webhook configuration, you'll see a purple icon in the table of webhooks. If you click on that you can build different events to send to your webhook to ensure it responds properly. 

<img width="628" alt="Screen Shot 2019-05-22 at 12 12 52 PM" src="https://user-images.githubusercontent.com/1148709/58198118-f63c7880-7c8a-11e9-883b-82b8908d9269.png">

**Comment by tristanbabasa** [comment]
@robotdan 

Understood, Currently creating my own event logs from my webhook retrievable by my own custom registration page as an interim.

**Comment by robotdan** [comment]
This may be possible in versions `>= 1.30.0`. You can now subscribe to a `event-log.create`. 

When a webhook fails we'll create an event log, if this event is enabled, we'll send the event to all web hooks except the one that had the failure. The event log will contain the exception such as a socket timeout if it exists, a status code and any response body returned from the webhook.
