### ISSUE TITLE
theme.optionalMessage returns key, not empty string

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1661]
### Affects versions

Found on 1.35.0

### Steps to reproduce

* Edit a theme page
* Add this to the page: `${theme.optionalMessage("aaccess-denied")}` (notice the extra `a`)
* Preview the page. You'll see `aaccess-denied` instead of the empty string.

This behavior also occurs on the live page, not just in preview.

### Expected behavior

An `optionalMessage` call with a key that is not found in the messages file should return an empty string.

### Community guidelines

All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

You can workaround it with a freemarker function:

```
[#function getOptionalMessage key=""]
  [#if "${theme.optionalMessage(key)}" == "${key}"]
    [#return "" /]
  [/#if]
  [#return theme.optionalMessage(key) /]
[/#function]
```

But that's not optimal.

This behavior is specified by the java client library here: https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/java/io/fusionauth/domain/Theme.java#L198

But that javadoc says there is an internal class that overrides this method. When I look at that class `OptionalMessage`, it says `Return an optional message or empty string if not defined.`

So I wonder if there is some kind of classloading issue or if the java client is somehow overriding the proper class incorrectly.

**Comment by mooreds** [comment]
Hmmm. Should probably document it in a more prominent place than the java client library then.

**Comment by robotdan** [comment]
Yes, perhaps here https://fusionauth.io/docs/v1/tech/themes/helpers or here https://fusionauth.io/docs/v1/tech/themes/localization

**Comment by mooreds** [comment]
Documentation added via https://github.com/FusionAuth/fusionauth-site/pull/1292

**Comment by robotdan** [comment]
PR in `fusionauth-site` approved, and merged.
