### ISSUE TITLE
Alphabetize applications in drop down select boxes in UI

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1668]
### Description
When you have lots of applications, sorting them in alphabetical order seems reasonable. :-) 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Related: https://github.com/FusionAuth/fusionauth-issues/issues/374
