### ISSUE TITLE
Swap Tomcat for Netty

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1671]
### Description
Kick Tomcat to the curb and switch to Netty. This will give us a lot more control and make it easier to handle cookies since the Servlet spec tends to be slow to adopt new tech. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by kevcube** [comment]
@robotdan in the docker image `1.37.1` I still see 

```
root@c80d352ea38f:/# find . | grep tomc
./usr/local/fusionauth/fusionauth-app/tomcat
./usr/local/fusionauth/fusionauth-app/tomcat/bin
./usr/local/fusionauth/fusionauth-app/tomcat/bin/FusionAuthApp.ps1
./usr/local/fusionauth/fusionauth-app/tomcat/bin/FusionAuthApp.exe
```

are these included but unused?

**Comment by mooreds** [comment]
Thanks for reporting, opened an issue.
