### ISSUE TITLE
FusionAuth Get all users not returning all users

### ISSUE THREAD

**Issue by mohyddintash** [FusionAuth/fusionauth-issues#1677]
I am using the query below to get all users. In the fusion auth admin dashboard there are 29 users for that application_id however only 25 users come back. Note: in the response also it says "total: 29" but only 25 users are in the response.

```json
{
  "bool" : {
    "must" : [ {
      "nested" : {
        "path" : "registrations",
        "query" : {
          "bool" : {
            "must" : [ {
              "match" : {
                "registrations.applicationId" : "<my-app-id>"
              }
            } ]
          }
        }
      }
    } ]
  }
}
```

I can't really tell what is going on. Only thing I notice is that in the admin dashboard the paging shows 25 users per page, but I don't think this has to do with the problem?

**Comment by mooreds** [comment]
@mohyddintash thanks for posting. 

However this seems like a support question. Please post in the community forum: https://fusionauth.io/community/forum/ or open a support ticket if you have an account with a support contract: https://account.fusionauth.io/account/support/

GitHub is for bugs with repro steps and feature requests.

I'm going to close this issue out for now.

**Comment by mohyddintash** [comment]
@mooreds Sorry, I had the impression it was some kind of bug, but I can't give repro details due to privacy concerns. 
I will post in the community. Thanks!
