### ISSUE TITLE
The CORS documentation is not accurate

### ISSUE THREAD

**Issue by glen-84** [FusionAuth/fusionauth-issues#1678]
### Description 
The [CORS documentation](https://fusionauth.io/docs/v1/tech/reference/cors#default-configuration) states that CORS is enabled by default, but it's not.

I'm trying to use `exchangeOAuthCodeForAccessTokenUsingPKCE`, and it's failing due to CORS. I had expected that adding the origin to `Authorized request origin URLs` would automatically handle CORS, but that doesn't appear to be the case?

### Affects versions
1.36.0

### Steps to reproduce
1. Go to `/admin/system-configuration/edit` after installing with Docker.
2. Note that `CORS filter` is not enabled.

### Expected behavior
For this issue, for CORS to be enabled. However, handling it automatically based on `Authorized request origin URLs` would be better.

### Screenshots
![image](https://user-images.githubusercontent.com/261509/162970266-cba78c47-996b-4d38-baf2-bdd55c24ccb8.png)

### Platform

 - Device: Desktop
 - OS: Windows 11
 - Browser + version: Chrome 100.0.4896.88
 - Database: Default

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
n/a

**Comment by mooreds** [comment]
Thanks for filing the issue @glen-84 ! Glad you figured it out. We'll get the docs updated.

**Comment by robotdan** [comment]
This is probably working as designed. 

We have discussed automatically adding things to CORS for callbacks in SAML or OAuth2. To date, we've err'd on the side of not doing anything too magical, and just doing our best to document where possible that a CORS configuration may be required.

**Comment by glen-84** [comment]
If that's true, then this line should perhaps be changed?

> Most of the time this works as designed, you do not need to think much about CORS configuration.

CORS will always be required when connecting from the client side.

**Comment by robotdan** [comment]
@mooreds is there more doc or UI updates to make this for one, or can we close it out?

**Comment by mooreds** [comment]
Just filed a PR updating the doc, confirmed that by default, out of the box, CORS is disabled.

**Comment by robotdan** [comment]
@mooreds can I close this one out if we have updated the doc?

**Comment by mooreds** [comment]
Closing.
