### ISSUE TITLE
`Add Webhook` page UI/UX could be improved

### ISSUE THREAD

**Issue by glen-84** [FusionAuth/fusionauth-issues#1685]
### Description

On the `Add Webhook` page, all of the events are enabled by default, so if you only want one event enabled, you have to click every other event's toggle button. Please consider adding an `Enable/Disable all` toggle button.

It might also be nice to have a plain text description of the events, instead of just the "codes":

|Description|Type|Enabled|
| :--- | ------------ |------------ |
|This event is generated when a single user is created. The JSON includes the User that was created.|user.create|✅|

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
The Enabled column is clickable which is an enable all / disable all button. If you click on it once it will disable all events, and then you can click on just the ones you want enabled. 

![image](https://user-images.githubusercontent.com/1148709/163510975-365b240b-facd-4f59-b938-863ac5399e17.png)


Does that help, or are you looking for something more specific? 

We could also add some more detail next to each event to offer some better description.  Currently all events are documented here: https://fusionauth.io/docs/v1/tech/events-webhooks/events/

**Comment by glen-84** [comment]
Ah, I didn't even notice that! I'm so used to table headers being used for sorting. Thanks.

> Currently all events are documented here: https://fusionauth.io/docs/v1/tech/events-webhooks/events/

Ya, I took the description from the specific webhook page. The type or description could also link to the documentation page.

**Comment by robotdan** [comment]
Closing this out. In the latest version (1.37.0 I think), there is now a description, a column to indicate if it is a system event, and the rows are clickable in addition to the enabled column. 

If there are any other specific UX improvements you'd like to see in addition to those - please -re-open with those details. Thanks!
