### ISSUE TITLE
When a user is created in the Admin UI with the user_support_manager role always perform email verification

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1689]
### Description
When a user with the `user_support_manager` role is creating a user in the Admin UI - the email is always created as verified. 

When the user is only a `user_support_manager`, the user should always be created with an un-verified email if email verification is enabled. 

If the user has `admin` or `user_manager`, we should allow a toggle to allow the admin to choose if they want to create the user with a verified email or utilize the email verification process. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Depends on changes from #1319

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/122

**Comment by spwitt** [comment]
This will be resolved with #1319
