### ISSUE TITLE
When a user is created in the Admin UI with the user_support_manager role always use the setup password email

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1690]
### Description
When a user with the `user_support_manager` role is creating a user in the Admin UI - do not allow the user to be created with a known password. 

The user should only be created with a "Send setup password email" - and if Email is not configured, or the template is not configured to enable this workflow, then a validation error should occur indicating the user cannot be created due to the limited permissions on this role. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/123

**Comment by spwitt** [comment]
This issue will be resolved with #1319
