### ISSUE TITLE
Locale not included in User Create webhook

### ISSUE THREAD

**Issue by glen-84** [FusionAuth/fusionauth-issues#1693]
### Problem
The user's specified or selected locale is not included in the User Create webhook.

### Solution
For the user's specified or selected locale to be included in the User Create webhook.

### Alternatives/workarounds
Saving it to a hidden field. Might not always be possible (if the value is not in the query string, if the locale cookie is changed to be HTTP-only, or if custom fields are not available).

### Additional context
FusionAuth™ version 1.36.0.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
This should be present in `user.preferredLanguages`.

How are you setting the locale? Can you provide step by step repro steps, please?

**Comment by glen-84** [comment]
While testing again, I noticed a different issue – if you hit an authorize URL with `locale=th` (f.e.*) in the query string:

1. No cookie is set with this locale.
2. The links (f.e. `Create an account`) do not include the locale, so they switch back to EN.

For the latter, it can probably be solved by including the locale in the `link` macro. I'm not sure about the cookie though – is that supposed to be set?

[*] I have a Thai localization in the selected theme.

---

If I append `locale=th` to the registration URL, the resulting event is:

```php
array (
  'createInstant' => 1650563334654,
  'id' => '8f3dccdd-d31f-44e5-a278-6cac1715d222',
  'info' =>
  array (
    'deviceName' => 'Windows Chrome',
    'deviceType' => 'BROWSER',
    'ipAddress' => '172.18.0.1',
    'userAgent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
  ),
  'tenantId' => '5086fa1f-***7-4d9c-a59b-32bc0492912f',
  'type' => 'user.create',
  'user' =>
  array (
    'active' => true,
    'connectorId' => 'e3306678-a53a-4964-9040-1c96f36dda72',
    'email' => '***@gmail.com',
    'id' => '6a29570d-5472-4b95-8e48-cd6f55829dd3',
    'insertInstant' => 1650563334556,
    'lastUpdateInstant' => 1650563334556,
    'passwordChangeRequired' => false,
    'passwordLastUpdateInstant' => 1650563334621,
    'tenantId' => '5086fa1f-***7-4d9c-a59b-32bc0492912f',
    'twoFactor' =>
    array (
    ),
    'usernameStatus' => 'ACTIVE',
    'verified' => false,
  ),
)
```

No sign of the locale or preferred languages.

The new issue with maintaining the locale state is actually more important than this one, since we're using a different method to capture this information on the app side instead.

**Comment by mooreds** [comment]
Thanks @glen-84 , I filed an issue about your last comment, since that appears to be a bug.

**Comment by robotdan** [comment]
Based upon the thread and discussion here https://github.com/FusionAuth/fusionauth-issues/issues/1738 - I think we can close this issue out?

**Comment by glen-84** [comment]
@robotdan Ya, if it's included in `user.preferredLanguages` when that issue is "fixed" 😉, then this will be resolved as well. Closing.

**Comment by robotdan** [comment]
Thanks @glen-84 - yes, we'll track https://github.com/FusionAuth/fusionauth-issues/issues/1738 to closure for this fix.
