### ISSUE TITLE
Feature: Silent install and configuration using an answer file

### ISSUE THREAD

**Issue by trollr** [FusionAuth/fusionauth-issues#170]
### Problem
Code driven infrastructure needs the possibility to import and configure fusionauth on startup without any pain eg. first time configuration (admin user) via ui :( 

### Solution
Huge JSON File with all configurations (initial user, application, webhooks etc). Parse the configuration file and use the api methods to push it

- Initial User(s) and roles
- Applications and Roles
- Groups
- Webhooks
- Event configurations
- Tenant configuration
- Email template configurations
- etc

This would allow the deployment of a development or production environment in a pre-defined container or configuration file. 

### Additional context
Similiar keycloak realm.json import 
https://www.keycloak.org/docs/2.5/server_admin/topics/export-import.html

Other good ideas from https://github.com/cowlingj via https://github.com/FusionAuth/fusionauth-issues/issues/286

Working script from @trevorr to make due until this feature exists
https://github.com/trevorr/express-jwt-fusionauth/blob/master/scripts/configure.sh

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for taking the time to open this feature @trollr. This is a great idea and we've been kicking around an idea similar to this one for a while - it is definitely on the road map.

**Comment by trollr** [comment]
@robotdan Is it predictable when this feature will be implemented? Or is there a possibility to contribute? It's difficult to me to accesses if it is possible via plugins

**Comment by robotdan** [comment]
@trollr not really predictable.  We do offer professional services if you want us to write up a statement of work I could send that over. That would be one option to prioritize this effort. 

In theory the importer plugin could work, that is not really a documented feature yet. When Stormpath went out of business a few years back we built an importer plugin to allow a Stormpath clients to point and click their exported zip and be up and running in FusionAuth (then called Passport). We aren't currently shipping any importer plugins, but we may. 

> Is it possible to generate a global (internal) API Key on startup and publish it to the plugins?

Not currently, although you could accomplish this via a SQL script. If this would work for you in the short term I can help you with this. 

> Easiest solution: Give us the possibility to set a technical api key via env vars. Think it's a one liner

This could be an option.

**Comment by trollr** [comment]
>  although you could accomplish this via a SQL script

You mean sql migration script? Would be nice if you could explain it a bit more. Otherwise you could tell me the location of the fusionauth sql migrations folder (cant find it). I could do a docker volume mount with customized (new) scripts

Edge question: Are there any considerations to make fusionauth open source? :)

**Comment by robotdan** [comment]
Not a migration script, we'll only execute those based upon the package version vs. the schema version. 

But you could execute a SQL command as part of your deployment to insert an API key and the you could script these rest using the API. 

For example 

```sql
INSERT INTO authentication_keys (id, permissions) VALUES
  ('a super secret API key', NULL);
```

> Edge question: Are there any considerations to make fusionauth open source? :)

It is something we're always considering as it relates to how to make FusionAuth secure and flexible so that we can get into the hands of as many developers as possible. However, no plans at this time to change the source code licensing model.

**Comment by priyolahiri** [comment]
Is it possible to create the first user after creation of the key with the SQL query? Or is it a pre-requisite to have the first user before the API key?

**Comment by robotdan** [comment]
> Is it possible to create the first user after creation of the key with the SQL query? Or is it a pre-requisite to have the first user before the API key?


There is not a pre-requisite, in theory you can create the API key first.  However, we do not expect this scenario, so there may be some side effects. 

During startup, some final setup occurs - we determine if this is necessary based upon a user count of 0, so if you create the user first we will not perform this final setup. 

You may be able to trigger this setup by making a `GET` request to `/setup-wizard` to replicate the browser hitting this page. After this is complete, you could create the admin user using the API key.

**Comment by trollr** [comment]
If anyone is interested: I build a helm chart for fusionauth to execute sql migrations with flyway after fusionauth is healthy. After the pr is merged you can use it with kubernetes. It's easy to port it to docker or docker-compose. 

https://github.com/FusionAuth/fusionauth-containers/pull/13

**Comment by robotdan** [comment]
Thanks @trollr for the contribution!

**Comment by robotdan** [comment]
Added link to https://github.com/trevorr/express-jwt-fusionauth/blob/master/scripts/configure.sh in the main description. Thanks @trevorr.

**Comment by Trupal00p** [comment]
Howdy!

Just adding to this thread. I needed a way to export/import my settings so I could move them between instances so I wrote some python to hit the api and save the config to a json file then another to load it into an new instance. Hope someone finds this useful: https://github.com/Trupal00p/fusionauth-export-import

**Comment by robotdan** [comment]
We have a working prototype for this feature. We'll likely release it in a preview and have anyone who would like to do so -test it out and provide some feedback to make sure it is flexible enough for the various use cases.

**Comment by Raghavsalotra** [comment]
@robotdan We are in to give it a try.

**Comment by trollr** [comment]
@robotdan Where do I get the preview release? :)

**Comment by robotdan** [comment]
Hopefully it will be available today or tomorrow. I'll update this thread when it is available and with some preliminary usage documentation.

**Comment by robotdan** [comment]
Time to give it a whirl! 

https://fusionauth.io/docs/v1/tech/release-notes
https://fusionauth.io/docs/v1/tech/installation-guide/kickstart

I may have a few use cases missing from the doc, but that should give you a good place to start.
