### ISSUE TITLE
Asynchronous Tenant Delete can still get stuck in pending delete state without a retry option

### ISSUE THREAD

**Issue by robfusion** [FusionAuth/fusionauth-issues#1709]
### Description 
It's very close to this original behavior
-- https://github.com/FusionAuth/fusionauth-issues/issues/1075#issuecomment-836873452

* The fix was to allow a retry option, but there was no retry option available. 
* The UI showed the tenant in "Deleting" state.
* The Audit Log showed a message that the tenant had been deleted.
* Updating the state in the tenants database back to Active as a workaround allowed another delete attempt, but nothing happened when the delete button was clicked.
* The workaround was to call the DELETE /api/tenant/{tenantId} endpoint asynchronously. That was able to delete the tenant cleanly.

### Affects versions
1.34.1 

### Steps to reproduce
1. Go to 'Tenants'
2. Click on 'Delete'
3. Confirm 'DELETE'
4. Tenant UI shows the tenant in "Deleting" state indefinitely with no visible retry option.

### Expected behavior
A clean delete after a few seconds.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
I observed this on a client's system. The job was in the correct state, in the db but the task was not being picked up to be processed. Still working on a theory, but it seems the thread is running but is in a state such that it does not attempt to processing pending jobs.

**Comment by robotdan** [comment]
Still unclear how this occurs, however in the upcoming feature release I have made some changes to should simplify the threading - in hopes that we don't see this issue again.

**Comment by robotdan** [comment]
I think this will be resolved via https://github.com/FusionAuth/fusionauth-issues/issues/2307. This change made some significant enhancements to make this a bit more bullet proof.
