### ISSUE TITLE
Single Sign-On (SSO) Cross Domain Support

### ISSUE THREAD

**Issue by arkrozycki** [FusionAuth/fusionauth-issues#171]
### Description
The features list on fustionauth.io mentions SSO support. But I'm not sure to what extent. Looking through the documentation I'm unable to find any information related to SSO. In my use case I'm attempting to evaluate the feasibility of using FusionAuth to support cross domain SSO.

**Comment by robotdan** [comment]
SSO can be achieved in a few different ways. 

The most common way will be to utilize the Authorization Code grant. 
https://fusionauth.io/docs/v1/tech/oauth/overview#example-authorization-code-grant

In this workflow, once a user is logged into FusionAuth a session is created, and the next time you try to login using a separate application that also uses the FusionAuth login, the user will be redirected without being prompted for login. 

Each application on your end is represented by a FusionAuth application, and this is where you'll configure OAuth for each application. 
https://fusionauth.io/docs/v1/tech/tutorials/create-an-application

Let me know if I can provide some additional clarity to your question.

**Comment by arkrozycki** [comment]
Let me add some more color to the initial request. I should have added _auto-login_ requirement. We have two scenarios for auto-login. 

Consider we have the following resources:

_auth.domain.com_ (fusionauth)
_a.domain.com_
_b.domain.com_
_another-domain.com_

A. Sub-domain auto-SSO
Here the _auth.domain.com_ drops an httponly cookie to _.domain.com_ which allows the cookie to be shared between sub-domains a and b. Thus, after a successful login with _a.domain.com_, a visit to _b.domain.com_ would check for the existence of the _.domain.com_ cookie, validate with fusionauth and auto-login the user. We are working to prove that this works with fusionauth.

B. Cross domain auto-SSO
A user successfully login to _a.domain.com_ and then browses to _another-domain.com_. _another-domain.com_ does not have access to the _.domain.com_ cookie.  

I've read about using a silent iframe inside _another-domain.com_, and calling _auth.domain.com_ to check if the user is logged-in. However, cross-domain iframe access is prohibited by modern browsers, so the parent window would not be able to communicate with the embedded iframe. Additionally, fusionauth doesn't have such an endpoint that would return a _true|false_ if the user has an existing session. If this was possible, we would redirect the parent window to _auth.domain.com_ which would auto-login the user.

So it is this **B** scenario we are trying to figure out how to implement with fusionauth.

**Comment by voidmain** [comment]
Hi @arkrozycki. I'm not completely certain I understand the use case. Let me repeat back what I'm thinking and you can tell me if that is correct. I'm going to use terms like User, Browser and Server. 

Also, it might be helpful for you to review our Authentication Workflows and let me know which of them looks the closest to your needs. Those are located at https://fusionauth.io/articles/logins/types-of-logins-authentication-workflows.

Here's what I'm understanding of your use cases:

**Scenario A:**
1. User opens Browser
2. User navigates Browser to `a.domain.com`
3. User clicks login
4. User is taken to `auth.domain.com` which is FusionAuth and this is using the OAuth Authorization code grant
5. User completes login and is redirected back to `a.domain.com/oauth-return` or something like that
6. Browser requests this endpoint on the Server of `a.domain.com` which completes the OAuth workflow by calling the token endpoint
7. Later, User navigates Browser to `b.domain.com`
8. Here, the Browser needs to determine if the User is logged in and you want to accomplish this through the use of a cookie. FusionAuth doesn't drop cross-domain cookies, so I'm not certain if `b.domain.com` can automatically validate if the user is logged in here.

**Scenario B:**
1. User opens Browser
2. User navigates Browser to `a.domain.com`
3. User clicks login
4. User is taken to `auth.domain.com` which is FusionAuth and this is using the OAuth Authorization code grant
5. User completes login and is redirected back to `a.domain.com/oauth-return` or something like that
6. Browser requests this endpoint on the Server of `a.domain.com` which completes the OAuth workflow by calling the token endpoint
7. Later, User navigates Browser to `another-domain.com`
8. Here, the Browser needs to determine if the User is logged in and you want to accomplish this through the use of an iframe or some other mechanism.

If those workflows look correct, then you might be able to handle both of these using AJAX. Here's how it would work for Scenario A:

In the `b.domain.com` application, you can make an AJAX request to FusionAuth's Authorize endpoint (`https://auth.domain.com/oauth2/authorize?client_id=...`). If the user is logged in, the AJAX will get a 302 redirect from FusionAuth back to `b.domain.com/oauth-return` and AJAX will follow that. This will complete the OAuth workflow and you should be all set.

Here's how it would work for Scenario B:

In the `another-domain.com` application, you can make an AJAX request to FusionAuth's Authorize endpoint (`https://auth.domain.com/oauth2/authorize?client_id=...`). If the user is logged in, the AJAX will get a 302 redirect from FusionAuth back to `another-domain.com/oauth-return` and AJAX will follow that. This will complete the OAuth workflow and you should be all set.

Let me know if those solutions might work for your needs.

**Comment by arkrozycki** [comment]
> FusionAuth doesn't drop cross-domain cookies

Do you mean, FusionAuth which resides on `auth.domain.com` will not drop a cookie to `domain.com`?

As far as I know its impossible to have `cross-domain` cookies for security reasons, however, setting a cookie such as `Set-Cookie: name=value; domain=domain.com` will be shared across all subdomains for that domain. This would allow `a.domain.com` and `b.domain.com` to have access to the same cookie. 

One reason we are looking at this option is for legacy LAMP applications, rather than waiting for an AJAX request and forcing a reload, we could detect during the initial page request that the user has an active session with `auth.domain.com` and proceed to auto-login the user.

I'll review the flows you sent over and see if those make better sense for us to use. It might be simpler in the end to maintain one flow that works for both scenarios.

**Comment by AlvMF1** [comment]
Hey Brian. I'm working with Ark on this project and I have a couple of questions:

1 - In you last post you mentioned AJAX reqs. In our stack, after the login we have to start the user session on server side. Would the solution you posted work in this case?
2 - We're currently using the `/api/login` endpoint to authenticate users. Are you also suggesting we switch to `/oauth2` instead?

Thanks!

**Comment by voidmain** [comment]
If you are using the `/api/login` API, then you won't be creating a session inside FusionAuth. The only way to handle your use case with the `/api/login` API is via refresh tokens. That workflow is here: 

https://fusionauth.io/articles/logins/spa/native-login-form-to-fusionauth-jwts-refresh-tokens-cookies

You can also use this workflow to pass the authentication requests through your backend:

https://fusionauth.io/articles/logins/spa/native-login-form-to-application-backend-jwts-refresh-tokens-cookies

There are variations on these workflows, but the general rule is that the refresh token is used to reissue a JWT.

If you want to "auto-login" the user to new applications, then you will need to have a backend that manages that somehow. FusionAuth provides this capability using the workflow I described in my last comment, but this does require you to use OAuth. Similarly, you can implement this capability in your backend using the FusionAuth APIs if you want. You can exchange a JWT and refresh token for one application for a JWT and refresh token for another application using the `/api/jwt/issue` API.

There are a ton of ways to handle everything, so it really just depends on what type of application you are building (WebApp, SPA, Native, Mobile, Console, etc.) and how you want to present the user with a login screen. I'd be happy to jump on a call if you want to talk through this some more. Just fill out the contact form on our website and I'll respond to setup a meeting.

**Comment by AlvMF1** [comment]
Hey Brian, me again...

I'm implementing your recommended solution, but running into a CORS issue when I have to make an AJAX call from `another-domain.com` to `auth.domain.com`. Is there a config setting to allow that?

Thanks once more!

**Comment by robotdan** [comment]
Hi @AlvMF1 can you show me the error you're seeing? 

I am able to make a cross domain request to the Login API `/api/login` when I'm using the same HTTP scheme, in this case `https`. 

We may still need some tweaks to our CORS configuration. If you want to test any changes yourself, you can modify the `cors-filter` configuration in the `web/WEB-INF/web.xml` file. (If you're familiar with servlet filter configurations)

**Comment by AlvMF1** [comment]
I apologize, I didn't mentioned: the endpoint is `/oauth2/authorize`.
But it might be my HTTP scheme. Lemme do some more investigation.

**Comment by AlvMF1** [comment]
<img width="510" alt="Screen Shot 2019-06-06 at 3 00 30 PM" src="https://user-images.githubusercontent.com/15204146/59069436-f2544d00-886b-11e9-87dd-cf8104142d4c.png">

Both `auth.bstock.io` and `almo.bstock.io` are docker containers running on my local...

**Comment by voidmain** [comment]
Sorry for the delay in responding. 

Something definitely looks fishy. I tested an AJAX call from the console to a remote FusionAuth server and it worked fine. I also inspect the HTTP response headers that the remote FusionAuth server was sending back and they included `Access-Control-Allow-Origin: *`.

My AJAX code was really simple:

```
var ajax = new XMLHttpRequest();
ajax.onreadystatechange = function(event) {
  alert("Working");
};
ajax.open("GET", "https://example.fusionauth.io/oauth2/authorize?client_id=3c219e58-ed0e-4b18-ad48-f4f92793ae32&response_type=code&redirect_uri=%2Flogin&state=m0x6DCVJ6XyT7YhS9AIERN92Q3KPFtFGgOl_IvQCkTc", true);
ajax.send();
```

Can you share your JavaScript code so we can take a look?

**Comment by AlvMF1** [comment]
Tried your code with our URL: same thing. And you are right, we see the * in the config file...

This is our url, btw: `https://auth-eval.bstock.io/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fdist%2Falmo%2Fcustomer%2Faccount%2Fautologin%2F&scope=offline_access&response_type=code&client_id=b0afcda9-4798-4d88-8f1a-48d55a122494`

You think it's something else in our server config?

**Comment by voidmain** [comment]
I tried accessing your URL and it sends back a `403 Forbidden`. Probably a gateway or load-balancer config for that. I'm not sure where the problem could be, but if FusionAuth is returning the correct headers on the response, then it should just work. If you have a gateway or load-balancer in front of FusionAuth, just make sure that it isn't stripping off the headers.

Also, if you want to open up that URL, I can do some testing against it today.

**Comment by AlvMF1** [comment]
Hey Brian,

We were able to go around the CORS issue: we added `/oauth2/authorize` and `/oauth2/logout` to `cors-filter` in the `web/WEB-INF/web.xml` like Daniel mentioned.

However, now I always get the login form HTML in the response of the AJAX request, even when I'm logged in with FusionAuth. But if I open the URL in the browser, I'm redirected.

You can try [here](http://auth-eval.bstock.io:9011/oauth2/authorize?client_id=b0afcda9-4798-4d88-8f1a-48d55a122494&redirect_uri=http://localhost:8080/dist/bestbuy/customer/account/oauth/&scope=offline_access&response_type=code) with `user@domain.com` and `password`.

```
var ajax = new XMLHttpRequest()
ajax.open("GET", "http://auth-eval.bstock.io:9011/oauth2/authorize?client_id=b0afcda9-4798-4d88-8f1a-48d55a122494&redirect_uri=http://localhost:8080/dist/almo/customer/account/oauth/&scope=offline_access&response_type=code")
ajax.send()
```

**Comment by voidmain** [comment]
I finally had a bit of time to recreate the issue. AJAX by default does not send across Cookies during requests. You need to turn that on using this code:

```
ajax.withCredentials = true;
```

This will tell the browser to send across the Cookie that FusionAuth uses to track sessions. Let me know if that works for you.

**Comment by AlvMF1** [comment]
That did the trick, thanks!
I'm testing (and running into some issues with redirects) and I'll let you guys know the results.
Cheers!

**Comment by AlvMF1** [comment]
Hey, just letting you guys know this issue could be closed. We're all set! 😄

**Comment by robotdan** [comment]
Thanks for the update @AlvMF1 ! Glad to hear it. FYI, in case it will be of use to you - our next release will contain some additional CORS configuration through our UI.

**Comment by AlvMF1** [comment]
One thing that came up: using the describe flow, we'll get a new `refresh_token` every time, right? Or there's a way to always get the same one on the same device?

I'm asking this b/c I'm trying to figure out what's the best approach to revoke refresh tokens when they sign out. Any suggestions?

**Comment by robotdan** [comment]
The intended workflow will be to prefer the use of the refresh token to login. Once you can no longer get an access token with your refresh token - it is expired, and you should prompt the user to login again. 

For revoking the `refresh_token` on logout, you could use the Logout API. https://fusionauth.io/docs/v1/tech/apis/login#logout-a-user

**Comment by AlvMF1** [comment]
Yeah? I implemented the OAuth one b/c we have apps on different domains. So the cookies wouldn't be available everywhere.
If I use the logout API with `global`, will it revoke all tokens? Including from different devices?

**Comment by robotdan** [comment]
Using `global=true` will revoke all refresh tokens owned by the user. 

If you omit the `global` parameter, default is `false` and only specify a single refresh token, only that one will be revoked. 

The OAuth2 Logout endpoint `/oauth2/logout` is currently only intended to remove the SSO session. 

OIDC does have a back channel logout endpoint defined - I think this is still in draft, but it defines the logout function as follows: 

> Refresh tokens issued without the offline_access property to a session being logged out SHOULD be revoked. Refresh tokens issued with the offline_access property normally SHOULD NOT be revoked. NOTE: An open issue for the specification is whether to define an additional optional parameter in the logout token, probably as a value in the event-specific parameters JSON object, that explicitly signals that offline_access refresh tokens are also to be revoked.

https://openid.net/specs/openid-connect-backchannel-1_0.html

In our case, we don't issue refresh tokens without the `offline_access` scope and we do not tie them to an SSO session. According to this definition, we should not revoke refresh tokens as part of a normal logout request. It looks like they are still ironing out how to expose the option to request that these tokens be revoked as part of a logout request.

We built a lot of these other APIs for JWTs and Refresh Tokens because the OIDC spec doesn't always address really specific use cases - such as this one. 

If you have a use case that isn't addressed by the current Logout API(s) - please open a feature request and we can review it! Thanks.

**Comment by AlvMF1** [comment]
Hey, me again. :)

Something that just came up: when using the recommended AJAX flow, the redirect from FusionAuth always contains the header `Origin: null`. Is that how it's supposed to be? Do you guys see any issues with it?

I had to set `null` in the allow origin in order for that to work.

Thanks once more.

**Comment by robotdan** [comment]
I'll have to research that one a bit further, seems similar to this threads? May be browser specific. 

https://stackoverflow.com/a/22625354/3892636
https://bugs.chromium.org/p/chromium/issues/detail?id=154967

**Comment by ramuklihtnes** [comment]
Hi floks,

How to implement SSO Cross domain/Sub domain authentication In high level for .NET Projects  

I have angular project and .net framework project how to implement for both project in common way 
Please guide me, I didn't get proper way

**Comment by mooreds** [comment]
@ramuklihtnes This seems like a support question rather than a bug. 

If you have a paid edition with support, please open a ticket at https://account.fusionauth.io/account/support/ . If you do not, please post in our community forum: https://fusionauth.io/community/forum/
