### ISSUE TITLE
Issuer missing from JWT vend

### ISSUE THREAD

**Issue by madmod** [FusionAuth/fusionauth-issues#1714]
### Description 
Any JWT made with the [JWT API vend endpoint](https://fusionauth.io/docs/v1/tech/apis/jwt#vend-a-jwt) has no `iss` issuer. Also the documentation is outdated as the issuer is in the example request claims but is now a reserved claim according the [JWT Populate Lambda docs](https://fusionauth.io/docs/v1/tech/lambdas/jwt-populate).

There is no way that I can tell to make the issuer be present in the JWT.

### Affects versions
1.30.2

### Steps to reproduce
1. Make a the example request per the documentation, including `iss` in the claims.
2. Observe that the token has no `iss`.

### Expected behavior
The token should either have the `iss` in the claims or the `iss` of the tenant.

**Comment by robotdan** [comment]
The `iss` claim is not automatically added to the JWT produced by the Vend API, this is working as designed. The `iss` claims is not reserved in this case, you can optionally add it. 

The example request JSON is showing that you can provide any claim you like, such as `iss` and `id`. 

If you want the `iss` claim, you need to add it to the request as in the example shown in the docs:

```
{
   "claims": {
      "iss": "acme.com"
   }
}
```

If you are sending in that value and it is not working, let me know.

**Comment by madmod** [comment]
Thanks for the quick reply. I am testing this now and will let you know what I see in a few minutes.

**Comment by madmod** [comment]
It looks like this was an unrelated issue on my end. I verified that this works as you explained. Thanks for the help!
