### ISSUE TITLE
Tracking issue for client library fixes for 1.37

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1716]
## Tracking issue for client library fixes for 1.37

* https://github.com/FusionAuth/fusionauth-python-client/issues/10
* https://github.com/FusionAuth/fusionauth-python-client/issues/12

**Comment by robotdan** [comment]
@mooreds this is out - once the client libs are released - can we close this one out?

**Comment by robotdan** [comment]
Client libs are released.

**Comment by mooreds** [comment]
Closing as released.
