### ISSUE TITLE
FusionAuth Docker container not working

### ISSUE THREAD

**Issue by Kovah** [FusionAuth/fusionauth-issues#172]
### Description 
I tried to install FusionAuth using Docker, following the steps provided in the [documentation](https://fusionauth.io/docs/v1/tech/installation-guide/docker). The problem is that the fusionauth container is not running at all.

The following errors pop up shortly after the containers are started:

**Database issue**
```
db_1          | FATAL:  database "fusionauth" does not exist
db_1          | LOG:  incomplete startup packet
db_1          | LOG:  incomplete startup packet
db_1          | ERROR:  relation "version" does not exist at character 21
db_1          | STATEMENT:  select version from version
db_1          | LOG:  incomplete startup packet
```

**Logging issue**
```
ERROR in ch.qos.logback.core.FileAppender[FILE] - Failed to create parent directories for [/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../logs/importer.log]
ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../logs/importer.log,true) call failed. java.io.FileNotFoundException: /usr/local/fusionauth/fusionauth-app/apache-tomcat/../../logs/importer.log (No such file or directory)

```

**Search issue**  
```
Attempt 1 of 10. Waiting for search to become available [SERVER_DOWN]. Error [http://search:9200].
```

### Steps to reproduce
1. Copy the docker-compose.yml file from the [repo](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/docker-compose.yml).
1. Copy the .env file from the [repo](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/docker-compose.yml).
3. Run `docker-compose up`

### Expected behavior
Fusionauth should start / install properly.

### Logs
Logs are available here: [pastebin.com](https://pastebin.com/s158KBU0)

### Platform
- Ubuntu 18.04 LTS
- Docker 18.09.6, build 481bc77
- Docker compose 1.17.1

**Comment by voidmain** [comment]
Can you attach the FusionAuth log files to this issue? I'm guessing that Docker isn't performing a silent mode setup properly. Since that creates the database and everything else that FusionAuth needs, if it fails then FusionAuth won't start up.

We will also try to reproduce this locally using your versions of Ubuntu, Docker and Compose.

**Comment by Kovah** [comment]
Where can I find them? Probably not accessible via Docker if the container restarts every few seconds. :/

**Comment by robotdan** [comment]
```
fusionauth_1  | ---------------------------------------------------------------------------------------------------------
fusionauth_1  | ---------------------------------- Entering Silent Configuration Mode -----------------------------------
fusionauth_1  | ---------------------------------------------------------------------------------------------------------
fusionauth_1  |
db_1          | LOG:  incomplete startup packet
fusionauth_1  | May 25, 2019 11:37:18.351 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - Database Version [1.6.1]
fusionauth_1  | May 25, 2019 11:37:18.351 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - Latest Migration Version [1.6.0]
fusionauth_1  | May 25, 2019 11:37:18.478 AM INFO  c.inversoft.maintenance.search.ElasticsearchSilentConfigurationWorkflowTask - Attempt 1 of 10. Waiting for search to become available [SERVER_DOWN]. Error [http://search:9200].
fusionauth_1  | Killed
fusionauth_search_1 exited with code 137
```

If you start up in silent mode you'll need to ensure the search engine is available. Is Elasticsearch running in another container or is it running as an external service?

**Comment by Kovah** [comment]
Elasticsearch is already provided with the docker-compose file from the official repo so I used that. I did not change anything in the file. Probably a configuration issue?
The only thing that comes from the elasticsearch container is this:
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
```

I tried to start up the app again, the whole log can be found [here](https://pastebin.com/NVBAc81Y).

**Comment by voidmain** [comment]
I looked through your logs. It looks like Elasticsearch is failing to start. Specifically, the `fusionauth_search_1` is existing with a status code of 137. I did a bit of searching and it could be that Elasticsearch is running out of memory and not able to start-up. Perhaps the host machine is out of RAM or the virtualization system you are using is not allocated enough memory for all of the pieces to start-up properly.

Here's a thread I found on a different system but with a similar Elasticsearch error: https://github.com/moby/moby/issues/22211

**Comment by Kovah** [comment]
Uhm okay. I thought that a VPS with 1GB would be enough to run the app, as I only have a dozen users using the service, not 500 or so.
Maybe a [hint about Elasticsearch's hardware requirements](https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html) could be added to the docs. Or overall hardware requirements, at least I couldn't find some.

**Comment by voidmain** [comment]
1 GB of RAM should be fine to run Elasticsearch. We run it with 256MB or so and it runs fine. My guess is that it is something else.

I did notice that your log file had two nodes in it. One was called `search_1` and the other was called `fusionauth_search_1`. Our stock configuration doesn't appear to have nodes with those names. Did you modify the stock compose file or are you using a different set of nodes somehow?

**Comment by Kovah** [comment]
> Did you modify the stock compose file or are you using a different set of nodes somehow?

Nope. Just used the docker-compose.yml file from the repo on a plain VPS with nothing else than Docker installed. Started the containers with `docker-compose up`.

I now cloned the whole repo instead of copying from the docs and just changed the database password in the .env file. Additionally I added swap. **It is now running** but uses 400MB additional swap space. Overall resource usage is at about 1.3GB.

**Comment by voidmain** [comment]
Interesting. I wonder if Elasticsearch requires more swap because it is using memory mapped files and those are translated to swap inside the Ubuntu Docker containers. I haven't had time yet to try this on a Ubuntu 18 instance, but I'd like to try and recreate it and figure out how to update the Compose to work out of the box. Or at least update the docs. :)

**Comment by xzessmedia** [comment]
i can confirm this.. the provided instructions results in a failing docker container as it can not connect to elastic search.. can be tested without any modifications..

`usionauth_1  | Jul 11, 2019 11:14:06.537 AM ERROR com.inversoft.maintenance.search.ElasticsearchMaintenanceModeSearchService - Failed to connect to Elasticsearch.
fusionauth_1  | org.apache.http.ConnectionClosedException: Connection closed
`


im running docker V. 18.09.7 and docker-compose V 1.17.1 on Ubuntu LTS 18.04

**Comment by robotdan** [comment]
I was able to get everything up and running based on the provided `docker-compose.yml`. 

I see `fusionauth_1` in your log which isn't in the example I don't think, can you provide your `.yml` file so I can look at it? Or if you found that in an example, can you point me at it make sure we're looking at the same configuration. 

I'm running Docker on macOS, Engine 18.09.2, Compose 1.23.2, Machine 0.16.1.

**Comment by axtgr** [comment]
I confirm that the sample docker-compose configuration doesn't work with a 1GB Ubuntu VPS. Even after I fiddled with the various memory parameters, the search container kept crashing with different errors (or even without them) at different moments of time.

The thing is, I don't even need full-text search, so being able to get rid of Elasticsearch completely would be even better than making it work. Is it not possible to run FusionAuth without ES?

**Comment by robotdan** [comment]
It is not currently possible to use FusionAuth w/out Elasticsearch.  We've discussed this possibility in the future for embedded applications. 

I'd have to look as well, but I would guess there are some tutorials out there for getting Elasticsearch configured on a VPS on any particular cloud ecosystem.

**Comment by robotdan** [comment]
Can this issue be closed out?

**Comment by Kovah** [comment]
Kind of.  If FusionAuth does not run without Elastic and Elastic does not run with less RAM, you may want to update the documentation with the fixed requirement of a minimum of 1GB of RAM with additional swap.

**Comment by robotdan** [comment]
Thanks @Kovah I'll add some information to that page, the min. requirements are always tough to nail down because of the number of variables involved. 

We do have some running on very small instances, and often in a production mode Elasticsearch is run as a separate service or in a managed service environment which reduces the memory requirement of the the individual node.

**Comment by robotdan** [comment]
Added some additional doc via https://github.com/FusionAuth/fusionauth-site/commit/3609c58d87d13598ac073a344a4c605e18850299, feel free to submit a PR if there is additional information you'd like to see on the system requirements page. Thanks!

**Comment by oussamabouchareb** [comment]
I followed all the instructions to install fusion auth using docker and it always throws this error and enters maintenance mode
```
db_1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1          | 
db_1          | FATAL:  "/var/lib/postgresql/data/pgdata" is not a valid data directory
db_1          | DETAIL:  File "/var/lib/postgresql/data/pgdata/PG_VERSION" does not contain valid data.
db_1          | HINT:  You might need to initdb.

```
all I did was copy and paste the command from the documentation here:
https://fusionauth.io/download

is this issue from my side?

**Comment by robotdan** [comment]
Can you try adding this to your environment config in `docker-compose.yml`? 

```
FUSIONAUTH_RUNTIME_MODE: development
```

It looks like this example hasn't been updated for `1.16.0`. @trex is this something that you have already corrected and just haven't pushed live?

**Comment by trex** [comment]
In my updates to the reference `docker-compose` for 1.16.0 changes I had forgotten the new `FUSIONAUTH_RUNTIME_MODE` environment variable.  I apologize for the difficulty @oussamabouchareb.  I have pushed a change to add this environment variable.

**Comment by oussamabouchareb** [comment]
no need to apologize,  thanks a lot for taking your time to help me out, I appreciate it
