### ISSUE TITLE
SAML Logout with HTTP Redirect bindings may fail to validate during /samlv2/logout/complete

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1723]
### Description 
When testing with Zendesk Logout using HTTP redirect bindings, we complete logout and POST to `/samlv2/logout/complete` but we try to re-validate the request, but we'll lose the query string during the POST request. 

### Steps to reproduce
1. Set up Zendesk integration
2. Click logout in Zendesk
3. We'll call `/samlv2/logout` which renders `/samlv2/logout` which performs a `POST` to `/samlv2/logout/complete` and we'll fail during validation when using HTTP redirect bindings.

I think we need to update how we validate the POST request when using HTTP redirect bindings, or capture the query string in the POST body or something like that so we can re-constitute the request and complete the logout. 

### Duplicates
- https://github.com/FusionAuth/fusionauth-issues/issues/1727

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by bvbao** [comment]
I'm facing a similar issue when it redirects to /samlv2/logout/complete
![image](https://user-images.githubusercontent.com/13671719/169342378-61c4642c-7dd6-4653-8801-50a997f2e1bb.png)

When I try to access the link (/samlv2/logout/complete) again, then it logged out, but it shows this error:
![image](https://user-images.githubusercontent.com/13671719/169343714-d4432de6-c3dc-4cd1-b79c-c989136be19b.png)

Here is the log:
```
19 3:40:12.585 PM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.samlv2.logout.CompleteAction] does not have a valid execute method for the HTTP method [GET]
2022-05-19 3:44:50.684 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null
at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
at io.fusionauth.samlv2.util.SAMLTools.decodeAndInflate(SAMLTools.java:145)
at io.fusionauth.samlv2.service.DefaultSAMLv2Service.parseLogoutRequestRedirectBinding(DefaultSAMLv2Service.java:458)
at io.fusionauth.api.service.samlv2.DefaultSAMLv2ProviderService.parseLogoutRedirectRequest(DefaultSAMLv2ProviderService.java:319)
at io.fusionauth.app.action.samlv2.logout.CompleteAction.lambda$post$0(CompleteAction.java:44)
at io.fusionauth.app.action.samlv2.BaseSAMLAction.handleSAMLException(BaseSAMLAction.java:111)
at io.fusionauth.app.action.samlv2.logout.CompleteAction.post(CompleteAction.java:40)
```

**Comment by robotdan** [comment]
@bvbao I think I've seen that before, what version of FusionAuth are you using? And can you tell me more about your SAML v2 SP?

**Comment by bvbao** [comment]
@robotdan , I'm using community version running in docker
My SP is a SpringBoot application
Here is the configuration:
`spring:
  security:
    saml2:
      relyingparty:
        registration:
          fusion-auth:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.cer"
            identityprovider:
              entity-id: http://localhost:9011/samlv2/d2274ffe-80d7-cc3b-c232-62804b62747e
              verification.credentials:
                - certificate-location: "classpath:credentials/certificate.crt"
              singlesignon.url: http://localhost:9011/samlv2/login/d2274ffe-80d7-cc3b-c232-62804b62747e
              singlesignon.sign-request: false
#              singlesignout.url: http://localhost:9011/samlv2/logout/d2274ffe-80d7-cc3b-c232-62804b62747e
              metadata-uri: http://localhost:9011/samlv2/metadata/d2274ffe-80d7-cc3b-c232-62804b62747e`

The WebSecurityConfigurerAdapter:
`@Configuration
@Profile("saml2")
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class Saml2SecurityConfig extends WebSecurityConfigurerAdapter {
	
	@Autowired
	private RelyingPartyRegistrationRepository relyingPartyRegistrationRepository;
	
	@Override
	protected void configure(HttpSecurity http) throws Exception {

        Converter<HttpServletRequest, RelyingPartyRegistration> relyingPartyRegistrationResolver = new DefaultRelyingPartyRegistrationResolver(relyingPartyRegistrationRepository);
        Saml2MetadataFilter filter = new Saml2MetadataFilter(relyingPartyRegistrationResolver, new OpenSamlMetadataResolver());
        
        http
        .authorizeRequests(authorize -> 
            authorize.antMatchers("/", "/login**", "/saml2**", "/error**")
                     .permitAll()
                     .anyRequest()
                     .authenticated())
        .saml2Login(withDefaults())
        .saml2Logout(withDefaults())
        .authenticationManager(openSamlAuthenticationProvider())
        .addFilterBefore(filter, Saml2WebSsoAuthenticationFilter.class);
	}
	
	@SuppressWarnings("deprecation")
    private AuthenticationManager openSamlAuthenticationProvider() {
	    OpenSamlAuthenticationProvider provider = new OpenSamlAuthenticationProvider();
	    provider.setAssertionValidator(OpenSamlAuthenticationProvider.createDefaultAssertionValidator());
	    provider.setResponseAuthenticationConverter(r -> {
	        Saml2Authentication auth = OpenSamlAuthenticationProvider
	                .createDefaultResponseAuthenticationConverter()
	                .convert(r);	        
	        DefaultSaml2AuthenticatedPrincipal principal = (DefaultSaml2AuthenticatedPrincipal) auth.getPrincipal();
	        principal.getAttribute("roles");
	        List<GrantedAuthority> grantedAuthorities = new ArrayList<>();
	        for(String role: principal.<String>getAttribute("roles")) {
	            grantedAuthorities.add(new SimpleGrantedAuthority(role));	            
	        }	        
	        return new Saml2Authentication((AuthenticatedPrincipal) auth.getPrincipal(), auth.getSaml2Response(), grantedAuthorities);
	    });
	    return new ProviderManager(provider);  
	}
}`

**Comment by robotdan** [comment]
I think I've got this fixed in an upcoming branch via https://github.com/FusionAuth/fusionauth-issues/issues/1671 - need to test prior to release.

**Comment by robotdan** [comment]
Same as https://github.com/FusionAuth/fusionauth-issues/issues/1692?
