### ISSUE TITLE
POST /identity-provider/link takes a displayName property but it is never used.

### ISSUE THREAD

**Issue by robfusion** [FusionAuth/fusionauth-issues#1728]
### Description 
POST /identity-provider/link takes an IdentityProviderLinkRequest object in the body. IdentityProviderLinkRequest has a displayName property. However, the value passed as displayName is not used when the link is created. 

### Affects versions
1.36.0

### Steps to reproduce

Call the POST /identity-provider/link endpoint with the following JSON body:

```
{
  "displayName" : "@myuserdisplayname",
  "identityProviderId" : "eeab40a3-9863-403a-bfff-315e7c74202b",
  "identityProviderUserId" : "42",
  "userId" : "00000000-0000-0001-0000-000000000000"
}
```

### Expected behavior
The Identity Provider Link to be created with the displayName set to `@myuserdisplayname`

### Related
- https://github.com/FusionAuth/fusionauth-site/issues/1404

### Regression caused by changes for
- https://github.com/FusionAuth/fusionauth-issues/issues/1589

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/127
- https://github.com/FusionAuth/fusionauth-java-client/pull/32
