### ISSUE TITLE
Twitter IdP provider fails to open grant screen

### ISSUE THREAD

**Issue by atakane** [FusionAuth/fusionauth-issues#1731]
### Description 

We're having a problem implementing Twitter as an alternate identity provider on FusionAuth 1.36.4 (docker)
Login with Twitter button appears on the login page as expected. However it immediately fails when we click on it, with displaying a white page.

### Affects versions
1.36.4

### Steps to reproduce
1- Add a Twitter Identity Provider on the admin dashboard
2- Assign the provider to a Fusion App (we have several apps, 1 of them is used for dev-test)
3- Set dev-app's theme to fusion default theme to get all the latest functionality
4- Open up the browser of your choice (preferably in incognito/private mode to avoid issues)
5- Hit the login page
6- Click "Login with Twitter"

### Expected behavior
Expected behavior is to get a Twitter Grant permission dialog.

### Logs
```
fusionauth_1  | 2022-05-24 4:26:44.483 PM ERROR org.primeframework.mvc.servlet.PrimeFilter - Error encountered
fusionauth_1  | org.primeframework.mvc.PrimeException: Missing result for action class [class io.fusionauth.app.action.oauth1.RequestTokenAction] URI [/oauth1/request-token] and result code [unauthenticated]
fusionauth_1  | 	at org.primeframework.mvc.action.result.AbstractForwardResult.locateDefault(AbstractForwardResult.java:161)
fusionauth_1  | 	at org.primeframework.mvc.action.result.AbstractForwardResult.buildFullyQualifiedPath(AbstractForwardResult.java:122)
fusionauth_1  | 	at org.primeframework.mvc.action.result.AbstractForwardResult.execute(AbstractForwardResult.java:92)
fusionauth_1  | 	at org.primeframework.mvc.action.result.DefaultResultInvocationWorkflow.perform(DefaultResultInvocationWorkflow.java:108)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1  | 	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1  | 	at org.primeframework.mvc.scope.DefaultScopeStorageWorkflow.perform(DefaultScopeStorageWorkflow.java:62)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1  | 	at org.primeframework.mvc.workflow.DefaultErrorWorkflow.perform(DefaultErrorWorkflow.java:46)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
fusionauth_1  | 	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:91)
fusionauth_1  | 	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
fusionauth_1  | 	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
fusionauth_1  | 	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
fusionauth_1  | 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
fusionauth_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
fusionauth_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
fusionauth_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
fusionauth_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
fusionauth_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
fusionauth_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
fusionauth_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
fusionauth_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
fusionauth_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:881)
fusionauth_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1647)
fusionauth_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
fusionauth_1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
fusionauth_1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
fusionauth_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
fusionauth_1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Platform

 - OS: Docker
 - Database PostgresSQL 13.x

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
The error looks to be a side effect of another error that would indicate cookies are not working or perhaps have been disabled. 

Can you capture a `.har` recording of the process that results in this error?

**Comment by atakane** [comment]
This is the very first time I'm trying external identity providers with FusionAuth. 

I deleted all the cookies, and tried in incognito mode to see what happens. Attached the `.har`
[fusion-auth-har-incognito.har.zip](https://github.com/FusionAuth/fusionauth-issues/files/8767593/fusion-auth-har-incognito.har.zip)
 file and a couple of screenshots below:
 
 
<img width="1511" alt="Screen Shot 2022-05-24 at 11 08 04 PM" src="https://user-images.githubusercontent.com/3112057/170171615-5760b697-2513-4aae-8206-8fee428fdb59.png">
<img width="1624" alt="Screen Shot 2022-05-24 at 11 07 37 PM" src="https://user-images.githubusercontent.com/3112057/170171618-045476e3-ceb1-4b6d-a8d7-62241f210906.png">

**Comment by atakane** [comment]
@robotdan Do you have any suggestions, workaround etc?

**Comment by robfusion** [comment]
@atakane I'm having a little trouble reproducing this one to track it down. A couple of additional details might help:

1. Can you clarify exactly how you "Hit the login" in step 5 of your reproduction steps. What exactly is the URL you are going to. This would be the page that shows the Login with Twitter button.

2. Have there been any modifications done to the theme at all?

The root of your problem seems to be that the state.client_id parameter in your URL is invalid. It is just set to "null" in the HAR file. That value should be set to the application id of the application that is enabled to use the Twitter IdP. So the question becomes where is it not being set correctly. The most likely scenario is that either the button code in Twitter.js is not setting it in the URL or it's not being passed in to the login page URL.

**Comment by atakane** [comment]
@robfusion 
1- The usual login URL hosts FusionAuth's login page. In my case, it is, login.circleboom.com 
2- No. If we messed up the theme, I deliberately used the stock theme that comes with the setup.

Yes, I noticed that the client id is null. I previously shared that on FA forums but did not write in my OP to prevent a miss-direction if that is not the case.

**Comment by robotdan** [comment]
@atakane I see you are using a custom theme, I think what @robfusion is asking is have you tried to recreate using the stock theme to confirm that the behavior does not change.

**Comment by robfusion** [comment]
Sorry, I don't think I was clear. I was actually referring to the URL that is loading the twitter login button. I see on login.circleboom.com for instance that it is

https://login.circleboom.com/oauth2/authorize?client_id=<some GUID> ...

with what looks like a valid client_id. Can you verify that you are seeing that oauth2/authorize?client_id=<some valid id> instead of client_id=null in the environment where you are having the issue?

**Comment by robfusion** [comment]
Actually, if that client_id value was not set you would get a different error. It looks like the only way a null would be passed to the request-token URL is if the code in twitter.js is not generating the URL correctly or if this.client_id is evaluating to null. 

If you could provide me with the URL of the page having the problem then I could probably identify the issue fairly quickly.

**Comment by atakane** [comment]
Twitter IDP is enabled for a dev-app for development purposes that's why you don't see when you hit the login page directly.

You can see it at https://twitter-test.circleboom.com (there is a SVG overlay issue on the Twitter button, other than that it is the same code with FA's default theme. (I switched it to our modified theme, however they all produce the same results.)

When I check the theme code, and generated code I see clientId is successfully assigned to `data-client-id`

**Theme:**
```
  [#if identityProviders["Twitter"]?has_content]
    [#-- This is the FusionAuth clientId --]
    <script src="/js/identityProvider/Twitter.js?version=${version}" data-client-id="${clientId}"></script>
  [/#if]
```

**output**
```
<script src="[/js/identityProvider/Twitter.js?version=1.36.4](https://login.circleboom.com/js/identityProvider/Twitter.js?version=1.36.4)" data-client-id="8b7b29dc-968e-4190-acb8-185b094e5391" type="1f1fd72ed87053d231b23df5-text/javascript"></script>
```

What I see here is that part in `Twitter.js` is not functioning as expected;

```this.clientId = lastScript.getDataAttribute('clientId');```

**Comment by robotdan** [comment]
Figured it out. CloudFlare is adding some additional JavaScript to the `head` element that is causing some unexpected behavior. 

The last script tag to load is `https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194`. 

We are using a technique to identify the script element we are in at runtime in order to read a data attribute. 

```
  var scripts = document.getElementsByTagName('script');
  var lastScript = new Prime.Document.Element(scripts[scripts.length - 1]);
  this.clientId = lastScript.getDataAttribute('clientId');
 ```
 
 At runtime this element is actually `scripts.length - 2` because the last element was actually some CloudFlare JS instead of ours. So the value of `lastScript` is not `Twitter.js` and thus `this.clientId` is set to `null`. 
 
 I don't know how to fix this off hand, it looks like this technique is flawed, at least some environments such as this, so we can review options to modify how we resolve the value for `clientId`. 
 
In the mean time, you could solve it in various ways, you could modify the `Twitter.js` to pick up the `clientId` from another location, or use a different technique that does not make the same assumption we are making.

**Comment by atakane** [comment]
> Figured it out. CloudFlare is adding some additional JavaScript to the `head` element that is causing some unexpected behavior.

Just about the same time  I was updating my previous reply to point out that :) 


> I don't know how to fix this off hand, it looks like this technique is flawed, at least some environments such as this, so we can review options to modify how we resolve the value for `clientId`.
> 
> In the mean time, you could work around it in various ways, you could modify the `Twitter.js` to pick up the `clientId` from another location, or use a different technique that does not make the same assumption we are making.

I have a solution, that may work pretty straight forward.

1. Add a `Id` attribute to Twitter Script tag. ie; `jsTwitter`
```
[#-- This is the FusionAuth clientId --]
    <script id="jsTwitter" src="/js/identityProvider/Twitter.js?version=${version}" data-client-id="${clientId}"></script>
  [/#if]
```
2. Get the `data-client-id` using that id 
```
var scripts = document.getElementById('jsTwitter');
this.clientId = scripts.dataset.clientId
```

**Comment by robotdan** [comment]
You won't want to try and edit `Twitter.js` - you'd have to manage that across upgrades, and across 1 to n nodes in a multi-node configuration. 

You'll just want to copy it and modify it and then use your copy instead.

**Comment by atakane** [comment]
Do you have any updates planned to fix this on your end soon? I'd wait rather than modifying a file that will be eventually overwritten.

**Comment by robfusion** [comment]
--https://github.com/FusionAuth/fusionauth-app/pull/133
