### ISSUE TITLE
Token from login API is throwing 401 when we send the same token to validate-jwt

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#1733]
### Description 
we are using validate-jwt api to check the validity of the token, the login API returns 200 OK with access token, but the same access token if used in validate-jwt api is throwing 400 error.

### Affects versions
1.28.1 and 1.36.0

### Steps to reproduce
Here are the steps to reproduce.

1. Call Login API for an user
2. Use the token from login api to validate using validate-jwt api
3. The validate-jwt api is throwing 401 error.

### Expected behavior
The validate-jwt api should return 200 OK

### Screenshots
some nullExceptions were seen in fusionauth logs, not sure whether they are related.

### Platform
Kubernetes 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
This is affecting our production system, any quick help would be greatly appreciated.

**Comment by LohithBlaze** [comment]
We are using the fusionauth python client to call the validate_jwt api, so we are passing the jwt directly to that python function
```
def validate_jwt(encoded_jwt):
    client = FusionAuthClient(FUSIONAUTH_API_KEY, FUSIONAUTH_SVC_URL)
    response = client.validate_jwt(encoded_jwt)
    return response
```

**Comment by LohithBlaze** [comment]
the response is just 'code': 401

**Comment by mooreds** [comment]
Can you try replicating the issue in your local development environment or on the sandbox.fusionauth.io instance? I can't replicate, which means I need your help troubleshooting it.

Any additional information you can provide will be helpful.

**Comment by LohithBlaze** [comment]
The issue doesnt happen on any fresh database instance, it only happens with the database data of our current system, if we take a backup and restore fusionauth with the old data, the issue occurs again.

**Comment by mooreds** [comment]
Hmmm. That is really interesting. Other things to check to help debug this issue:

* are there any errors in the system logs?
* does this happen only for one user or all users? Are there users it doesn't happen for? What is different between the users?
* does the token have any special claims?

Also, feel free to share an example encoded token. If it is sensitive and you don't want to post it here, I think you have my email address.

**Comment by LohithBlaze** [comment]
Getting this keyCache loader issue when enabled with debug logs. I have attached the logs. 

The issue is happening for all the users. Even the admin user of fusionauth is failing now.
No, the token doesnt have any special claims.
I have sent the token in the email. If you want me to upload DB somewhere in a sandbox environment, I can do that.
[fusionauth.log](https://github.com/FusionAuth/fusionauth-issues/files/8997978/fusionauth.log)

**Comment by mooreds** [comment]
@LohithBlaze That code looks like it is processing your public keys. 

The JWTUtils class is available here: https://github.com/FusionAuth/fusionauth-jwt/ as is the Pem class.

Can you run through all the public keys in your prod system and run `WTUtils.generateJWS_x5t(pem.certificate.getEncoded()), pem.getPublicKey());` on them?

That might identify a problematic public key. 

```
// iterating all the keys in the JWKS keyset
        if (key.certificate != null) {
          try {
            PEM pem = PEM.decode(key.certificate);
            x509Keys.put(JWTUtils.generateJWS_x5t(pem.certificate.getEncoded()), pem.getPublicKey()); // this is line 117
          } catch (CertificateEncodingException ignore) {
          }
        } 
```

Please let me know what you find.

**Comment by robotdan** [comment]
Please also try and recreate with the latest version of FusionAuth.

**Comment by LohithBlaze** [comment]
@mooreds how to execute them, like I need to download all the public keys, use the library and run the above code you mentioned?

**Comment by mooreds** [comment]
Yes, that's the idea.

**Comment by LohithBlaze** [comment]
Can I send you the keys table data in fusionauth and will you be able to run it yourself? We dont have any private or public keys that are of importance to use. even the admin login is not working, not sure what the issue is.

**Comment by LohithBlaze** [comment]
@mooreds We have tried with the latest version as well and the issue still remains. Our only solution right now is to reset the database and have a clean fusionauth install.

Yes, I was not able to access admin UI as well.

**Comment by mooreds** [comment]
What was the results of running all your keys through the verification process as outlined above?

**Comment by LohithBlaze** [comment]
I will update you by tomorrow on that.

**Comment by LohithBlaze** [comment]
@mooreds Can I send you only the keys table data as I'm not able to complete this. Here key.certificate, what is the type of key and JWTUtils.generateJWS_x5t doesnt have a function definition where it can take both the encodedCert and the public key. So not sure whether the above code is right.

**Comment by avitsrimer** [comment]
is your issue happening for each access_token or sometimes? For me, it happens 1-3 times per day.

**Comment by LohithBlaze** [comment]
It's happening every time for all the users for us. Had to reset the DB of fusionauth every time this happens.

**Comment by mooreds** [comment]
@LohithBlaze are you saying you have to reset your database when the validation method starts to fail? What does that mean?

**Comment by LohithBlaze** [comment]
Yes. The issue occurs for all the users in the system. And no one would be able to login.

**Comment by mooreds** [comment]
And what does "resetting" your database entail?

**Comment by LohithBlaze** [comment]
We have delete all the tables including fusionauth and bring up new tables as fresh install

**Comment by LohithBlaze** [comment]
Issue is not happening after properly setting the publicKey with publicKey variable.

**Comment by mooreds** [comment]
Excellent. Just so I can document this if appropriate, the issue was that there was a public key mismatch?

Anything you can share would be useful (about how you fixed it or troubleshot it).

Thanks for closing the loop, @LohithBlaze !

**Comment by LohithBlaze** [comment]
We were using key management apis to create public key, but instead of using the publicKey, we were specifying it as certificate. Due to this I feel the issue was happening. After we fixed it. We haven't seen this issue at all. https://fusionauth.io/docs/v1/tech/apis/keys#import-a-key

**Comment by mooreds** [comment]
Thank you for the clarification!
