### ISSUE TITLE
Unable to automatically configure some email template id of a tenant because of the missing Reactor license

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1739]
### Description 

We have a Reactor license we put manually from our FusionAuth dashboard.

However, our FusionAuth instance is deployed then configured by a custom script using the API for a first setup.

At the setup time, the Reactor license is not set because we are on a fresh instance.

Because of that, if the script try to update the `tenant.emailConfiguration.twoFactorMethodAddEmailTemplateId`, it got the following error:

```
{"fieldErrors":{"tenant.emailConfiguration.twoFactorMethodAddEmailTemplateId":[{"code":"[notLicensed]tenant.emailConfiguration.twoFactorMethodAddEmailTemplateId","message":"You must activate the Reactor using a valid license before using this email template."}]}}
```

To resolve this issue with ease, I would suggest to allow the edition of any settings, with or without the Reactor license. Having a setting field being set does not means the feature will work, so it should not trigger any not wanted side effect. 

### Affects versions

v1.34.1

**Comment by robotdan** [comment]
This is working as designed. The license may be activated via API or kickstart so you should be able to activate the license prior to configuring these features.

**Comment by soullivaneuh** [comment]
@robotdan Well, this is very limiting, making us having to configure the reactor license key even on development environment just to make the setup script working, event if we do not need to test paid features.

I don't see what is the issue of allowing option configuration without the license, as the feature will not works in any case.

May this be reconsidered?
