### ISSUE TITLE
Can a Webhook return JWT Token in the JSON Response Object?

### ISSUE THREAD

**Issue by gorwell4891** [FusionAuth/fusionauth-issues#174]
### After a successful login by a user that generates a user.login.success event that I trigger a webhook with, can the JSON Response Object include the JWT Token?

There are a lot of other information included, but can I custom include the JWT Token?

If not, then is there a way I can call by API to FusionAuth a request to get the JWT Token of an user?

**Comment by robotdan** [comment]
Hi @gorwell4891 

We do not currently send the JWT in the login success event. If you can explain the end goal, perhaps I can recommend a better approach. 

Are you just looking to add information to the JWT FusionAuth issues to the user during login?

**Comment by gorwell4891** [comment]
There are some use cases we're looking at accomplishing. I detail this current one we are working on.

We have a client application that when logging in to FusionAuth, gets a JWT token back during the login process. However, our server back end must also at the same time get this JWT token for use by several applications and must store the JWT token in another database. Thus, it would be useful for the webhook to allow our server-side application or scripts to also fetch the JWT token.

We cannot get the JWT token with the information supplied by the JSON response object of the webhook because JWT token fetching is not supported by the FusionAuth API. This creates a problem in our workflow. 

What we need to do instead is have our client application login via a script running on our own servers to submit the login request and get the JWT token in the process. And then to shuttle that JWT to the appropriate applications and databases.

The webhook alone cannot be used in this type of workflow to get the JWT token or similar user information.

**Comment by robotdan** [comment]
Thanks @gorwell4891 for that detailed use case.

I'll have to think about this one further and review with the team to see if there would be any security risk of pushing this additional information out in a `user.login.success` event.

**Comment by gorwell4891** [comment]
@robotdan may I ask if it's a security reason why there is no regular API access to the JWT token of a user? My assumption is that this may be the case in the API design.

Even with administrator privilege only, does getting the JWT token via the API present a security risk?

We're considering another use case where we may implement FusionAuth entirely in the back-end. So it would not have any access by end-users directly. So the actual FusionAuth API and URL would be used internally only in a private network.

My suggestion is maybe by default there should be no access to these tokens via the API, but the administrator of the FusionAuth deployment can choose if that token information is accessible via API. It may be more elegant of a way than putting the token in the JSON object which would affect everyone using the `user.login.success` event.

That way, we can address use cases where running FusionAuth entirely in a highly secure back-end environment were no outside users are in contact with FusionAuth via web interface or API are allowed to more freely exchange information across an entire multi-tier system.

**Comment by robotdan** [comment]
> @robotdan may I ask if it's a security reason why there is no regular API access to the JWT token of a user? My assumption is that this may be the case in the API design.


If I understand the question, you're asking why we do not offer an API to retrieve a JWT issued to a user? 

In FusionAuth, the JWT is a portable token, and not persisted. We issue a token as a result of an authentication event, which means it represents an authentication event. 

We would have no way to send you a JWT that we have already issued, we don't have it. In this context, it wouldn't make sense for FusionAuth to send out JWTs outside of an authentication event. 

> Even with administrator privilege only, does getting the JWT token via the API present a security risk?

My initial feeling is yes - this would allow anyone with an API key to retrieve a token that should only ever be held by the user to which it was issued. While the JWT is short lived, I would equate it to allowing access via API to retrieve a user's password.  Once I have a JWT, or a password, I can gain access to an authenticated resource that trusts the credentials (JWT or password) to represent the "bearer".  As soon as more than one party can hold that token, or get a copy of it, the secure contract falls apart. 

I can think about it some more, but I'd have to reason through all of the use cases to see if there is enough benefit or valid use cases to make it worth while. 


The way you describe making a proxy to FusionAuth that you control sounds like a better way to accomplish your goal. This way you can intercept the login response from FusionAuth and do whatever you'd like with the tokens, etc.

**Comment by gorwell4891** [comment]
> In FusionAuth, the JWT is a portable token, and not persisted. We issue a token as a result of an authentication event, which means it represents an authentication event.

Ok, that makes sense. Since the token is not persisted and issued only as an authentication event.

> My initial feeling is yes - this would allow anyone with an API key to retrieve a token that should only ever be held by the user to which it was issued. While the JWT is short lived, I would equate it to allowing access via API to retrieve a user's password. Once I have a JWT, or a password, I can gain access to an authenticated resource that trusts the credentials (JWT or password) to represent the "bearer". As soon as more than one party can hold that token, or get a copy of it, the secure contract falls apart.

I see. 

And since the JWT is digitally signed, we can trust the authenticity of the payload contained in the JWT. Changing the payload would invalidate the JWT. If we must have the entire JWT at our server-side, we must have a proxy server doing the initial authentication on behalf of the client application so we can store the JWT and send that JWT back to the client.

If we want to change the payload of the JWT, then we must do that with the FusionAuth Lambda functions.

Thank you @robotdan for the discussion. I appreciate it. Also very thankful that you guys created the project and open sourced it.

**Comment by robotdan** [comment]
> If we want to change the payload of the JWT, then we must do that with the FusionAuth Lambda functions.

Correct. 

> Thank you @robotdan for the discussion. I appreciate it.

You're welcome.

**Comment by robotdan** [comment]
Closing as not planning to fix. Please re-open if anyone has a compelling use case.
