### ISSUE TITLE
500 error when calling /api/jwt/vend with form parameters

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1740]
### Description 

FusionAuth responds with a 500 error when called without the `Content-type: application/json` header when making a request against /api/jwt/vend

### Affects versions

1.36.4

### Steps to reproduce

* Stand up a FusionAuth instance
* Set up a key in key master 
* Set up an API key
* Run this curl command against it: `curl -vvv -H 'Authorization: <APIKEY>' -X POST -d '{"keyId": "<keyid>", "timeToLiveInSeconds":300, "claims":{"sub":"test","roles":["anonymous"]}}' 'https://FUSIONAUTHURL/api/jwt/vend`

Look in the system log, you'll see an error

```
java.lang.NullPointerException: Cannot read field "keyId" because "this.request" is null
	at io.fusionauth.app.action.api.jwt.VendAction.validate(VendAction.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

If you add `-H 'Content-type: application/json'` it runs fine.

### Expected behavior

Seems like it should return 400 as a bad request, as defined here: https://fusionauth.io/docs/v1/tech/apis/jwt#vend-a-jwt

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Additionally outlined here: https://fusionauth.io/community/forum/topic/2087/500-error-api-jwt-vend

**Comment by robotdan** [comment]
This is working as designed. If you don't send a `Content-Type` head of `application/json` for any of our APIs that take JSON, you'll likely get an exception. 

I think this is the same issue as described here? https://github.com/FusionAuth/fusionauth-issues/issues/604

**Comment by mooreds** [comment]
Closing this as a duplicate. 604 indeed addresses it. I'd still like to avoid a 500 error when someone forgets the content-type header, though :) .
