### ISSUE TITLE
smtp.debug=true doesn't log any output

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1743]
### Description 

Setting `smtp.debug=true` per https://fusionauth.io/docs/v1/tech/admin-guide/troubleshooting#troubleshooting-email doesn't cause any output to be logged.

### Affects versions
1.36.4 on FusionAuth Cloud (unsure if the cloud part matters, haven't tested locally).

### Steps to reproduce

* Configure an SMTP server.
* Log in to the admin panel.
* Go to Tenant -> Advanced
* scroll to the bottom.
* Add `smtp.debug=true` to `Additional properties`
* Go to the email tab
* Send a test message

### Expected behavior

This doesn't log anything to System -> Logs but it should.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Related: https://github.com/FusionAuth/fusionauth-issues/issues/1742

This occurs (or rather, nothing is logged) if you do any other email related things, such as passwordless login or triggering a forgot password flow.

**Comment by robotdan** [comment]
So it works in Docker but not in FusionAuth Cloud? Not sure how that is possible - but it sounds like that is what you observed?

**Comment by mooreds** [comment]
@robotdan yes. It mystified me too. Note I only viewed the system logs in the admin UI, not by accessing the server, so it is possible there was logging but that it wasn't visible to me. I'll try to replicate today using a different FusionAuth cloud instance.

**Comment by mooreds** [comment]
It looks like mailgun sandboxes are restricted to certain verified email addresses. My fusionauth.io email address is verified, and I was just able to send a test email to it. `smtp.debug=true` is set to true for the tenant, and yet no debug logs were published to the system logs (in either the admin UI or the filesystem). I will try one of the other system emails.

**Comment by mooreds** [comment]
Sent off a password setup email for a different user (also a verified mailgun sandbox user), no logs in the log file.

Also, @voidmain I added your user to the sandbox email list. I think once you verify, you'll be able to get emails to the address of your user.

**Comment by mooreds** [comment]
I also tested this with an existing 1.36 zip file installed version and did not see the smtp debug log.

**Comment by voidmain** [comment]
Okay. I figured this out. 😁

The correct setting for JavaMail is now `mail.debug=true`. Additionally, this logs the debug to `stdout`, which for FusionAuth Cloud is currently directed to the `systemd` output stream, which is directed to `syslog` (i.e. `/var/log/syslog`). Therefore, the debug logging won't actually appear in the FusionAuth logs.

It looks like the current version of JavaMail supports additional debugging including providing a different `PrintStream`. To make this work better, we should move the debug option to a top level property in the `EmailConfiguration` and also hook the `PrintStream` up to the `EventLog`.

I have an idea of how to make this work, but it's a bit tricky because `PrintStream` doesn't have a method that is always used to indicate a full debug message is complete. I'll try using the `flush` method and see if it works.

**Comment by mooreds** [comment]
Need to update the email troubleshooting docs.

**Comment by robotdan** [comment]
If we update docs, we'll need to indicate which version the config changed from `smtp.debug=true` to `mail.debug=true`. I would guess it would be when we moved to Jarkarta - sort of surprising they broken the API, maybe they don't consider these properties to be part of the Java Mail API. 

I think we switched to Jarkarta when we moved to Java 14.

**Comment by robotdan** [comment]
Added to milestone 1.37.0

**Comment by robotdan** [comment]
@voidmain marking this code complete, I believe that is correct.

**Comment by robotdan** [comment]
Doc tasks:

- [ ] At version `1.32.0`(I think if this was when we switched Java 17 / Jakarta ) the correct config is `mail.debug=true` - prior to that it is `smtp.debug=true`.
- [ ] At version `1.37.0` and later, no need to set any of that in the SMTP advanced settings, enabling the `debug` flag on the SMTP config will cause debug to occur and an Event Log will be produced.
