### ISSUE TITLE
Enhance passwordless login to support external email systems

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#175]
### Problem
The current implementation of the passwordless login only supports FusionAuth sending the emails to the user. This does not work for applications that use external email systems.

### Solution
To fix this, the API needs to be capable of returning the OTP for passwordless login that can be sent in the email to the user. Additionally, there needs to be a flag to instruct FusionAuth not to send the email to the user.

### Alternatives/workarounds
None currently.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by shubham-root** [comment]
Passwordless login using SMS based One Time Password seems like a very useful feature to have. Do we have a tentative timeline by when shall FusionAuth be releasing it?

**Comment by robotdan** [comment]
Thanks for the comment @shubham-root no current ETA. 

We currently support a Twilio integration for SMS support, when we ship this feature - my guess is that will still be the primary integration. We have also discussed adding AWS messaging services for SMS. 

Do you have any particular suggestion or requirement for SMS services  - if other than Twilio or AWS?

**Comment by shubham-root** [comment]
@robotdan thank you for acknowledging the request.
We are currently using an India based service called MSG91 for SMS in our solution.  
Though, I'd like to go out and suggest and would love to have a freedom to 'bring-your-own' SMS service too. It might take some work on the developers end to implement the service their solutions but this definitely will make FusionAuth a more inclusive passwordless auth service.

**Comment by Tymek** [comment]
Can't it be solved by just adding a webhook when OTP is requested and an option to disable passwordless email? Correct me if I'm wrong. In the future I'd like to send confirmation codes using chat bots.

**Comment by robotdan** [comment]
@shubham-root we could review building a plugin interface to allow you to use whatever transport you'd like to send the passwordless code or link. This is a good idea.

@Tymek this is a good idea  - we could just push a webhook that contains the code. This is certainly an option we will consider.

**Comment by joaonice** [comment]
Hi there! Can you return the passwordless `code` on the  `POST /api/passwordless/send` as a workaround?

**Comment by robotdan** [comment]
Hi @joaonice - Returning the `code` in a response body is the currently planned strategy to resolve this issue. This would be consistent with our Change Password API. 

In addition, we may review the two options suggested by @shubham-root  and @Tymek as mentioned above.

**Comment by robotdan** [comment]
A possible native integration with https://www.hypr.com may satisfy this requirement.

Related issues: https://github.com/FusionAuth/fusionauth-issues/issues/77, https://github.com/FusionAuth/fusionauth-issues/issues/164

**Comment by joaonice** [comment]
This could be a solution but there's a plan to return the `code` on `POST /api/passwordless/send` endpoint?

**Comment by robotdan** [comment]
Yes, we would still like to return the code to make it more flexible. We are also looking at an integration with Hypr to provide some additional features we do not currently have.

**Comment by robotdan** [comment]
Available in 1.11.0

**Comment by satsangswami** [comment]
Well, I couldn't find the passwordless by SMS anywhere! Can you please let me know the exact flow of using SMS auth?

**Comment by satsangswami** [comment]
Well, most of the SMS providers in India implements a plain GET HTTP API for sending SMS.
Like 
`https://api.msg91.com/api/sendhttp.php?route=4&sender=TESTIN&message=Hello! This is a test message&country=91&mobiles=Mobile no.&authkey=$authentication_key`

You, can offer a Setting for Custom SMS Gateway URL which defines placeholders 

`https://api.msg91.com/api/sendhttp.php?route=4&sender=TESTIN&message=${SMS_TEMPLATE}&country=91&mobiles=${MOBILE_NUMBER}&authkey=xxxxx`

**Comment by robotdan** [comment]
Because there are many 3rd party SMS providers, we have added the Start Passwordless API which returns the code which you can then send through any provider you'd like. 

https://fusionauth.io/docs/v1/tech/apis/passwordless#start-passwordless-login

Once the user has been sent the code the Login can be completed using the Complete API. 
https://fusionauth.io/docs/v1/tech/apis/passwordless#complete-a-passwordless-login

**Comment by satsangswami** [comment]
> Because there are many 3rd party SMS providers, we have added the Start Passwordless API which returns the code which you can then send through any provider you'd like.
> 
> https://fusionauth.io/docs/v1/tech/apis/passwordless#start-passwordless-login
> 
> Once the user has been sent the code the Login can be completed using the Complete API.
> https://fusionauth.io/docs/v1/tech/apis/passwordless#complete-a-passwordless-login

Well, the point here is, will they be able to sign in only using the Mobile phone? Like is there a prompt created in fusionauth Login screen to signup using MOBILE PHONE and then ask OTP, wait and verify the code and complete the login & auth flow? Because the Phone sign-in will be an alternate method to email login. Something similar to FireBase login.

**Comment by rishabhc32** [comment]
Is there any way to send SMS through third party SMS provider but use fusionauth's UI theme only?

**Comment by bmeloski** [comment]
I would like to bump this question and ask if there is any roadmap on implementing paswordless login via SMS within FA UI. I don't want to host multiple login pages and it is a big issue

**Comment by mooreds** [comment]
@rishabhc32 @bmeloski we track this in a different issue, as closed issues aren't reviewed very often. 

I believe https://github.com/FusionAuth/fusionauth-issues/issues/615 is what you are looking for. If so, please upvote it (that's how we aggregate community input).

If not, please open a new feature request.
