### ISSUE TITLE
How to revoke Refresh Tokens on successful login

### ISSUE THREAD

**Issue by jkatnik** [FusionAuth/fusionauth-issues#1752]
Hi,

I want to block multiple concurrent logins of the same user.
I guess, what I need to do is to revoke all previous Refresh Tokens.
I'm wondering if there is such an option somewhere in the FusionAuth admin panel, or maybe I need to register webhook and call some API method, or maybe it could be done with Lambda?

I'd appreciate any advice.

Kind Regards
  Jarek

**Comment by mooreds** [comment]
@jkatnik this appears to be a support request.

Please follow one of the support request options here: https://fusionauth.io/docs/v1/tech/admin-guide/technical-support
