### ISSUE TITLE
"Managed Domains" entries are not being saved while creating a SAML Identity Provider

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#176]
"Managed Domains" entries are not being saved while creating a SAML Identity Provider

1. Go to Settings
2. Click on Identity Provider
3. Click on Add provider
4. Select SAML v2
5. Enter required fields and managed domains.
6. Click Save
7. Everything saves except Managed Domains

### Expected behavior
Managed Domains should also be saved along with other fields.

**Comment by robotdan** [comment]
Hi @prabhakarreddy1234 thanks for letting us know. 

I think I've recreated the issue, it looks like the domains are being saved, but not displayed properly. So if you edit the SAML IDP, you'll need to re-enter them. 

I'll follow up once we have a fix, if it is easy to track down it should be available in the upcoming 1.7.0 release.

**Comment by robotdan** [comment]
Fix will be available in `1.7.0`. For now the workaround is to add the domains you want and then if you have to edit the IDP configuration again, ensure you re-add them because they will not be displayed in the UI. 

Thanks for finding this issue @prabhakarreddy1234 and taking the time to let us know.

**Comment by prabhakarreddy1234** [comment]
@robotdan I added a managed domain and saved. Expected screen with email entry field. But still taken to login page with SSO button in the bottom.  Looks like managed domain entries are not being considered when showing login page.   

any ETA on `1.7.0` release with this fix ?

**Comment by robotdan** [comment]
Hi @prabhakarreddy1234 - yes, you're correct. My workaround wasn't very good. :-) 

1.7.0 should be out in the next day or two.

**Comment by prabhakarreddy1234** [comment]
@robotdan Thanks. This is fixed in latest version.
