### ISSUE TITLE
Webhooks are not triggered

### ISSUE THREAD

**Issue by Bad-Pop** [FusionAuth/fusionauth-issues#1768]
### Description 
My Spring Boot application needs to know when a user has just created an account, in order to insert some of their information into the database. 

To do this I created a webhook with the scope `user.create.complete` which calls an endpoint of my application. When I click on test and send a test webhook my application receives the call. However, when I create an account via the FusionAuth interface no webhook is sent, yet the application is configured to use this webhook.

### Affects versions
FusinAuth version 1.36.6

### Steps to reproduce
1. Go to 'Settings -> Webhooks -> Add'
2. Enter my application URL and select `user.create.complete` scope
3. Save
4. Go to 'Users -> Add' and create a new user for my application tenant

### Expected behavior
I expected FusionAuth to call the endpoint of my application with the relevant event

### Platform
My FusionAuth instance is hosted on Raspberry Pi 4 with a 64bits Os and a Postgres 14.3
My Spring Boot application is hosted on my personal computer and is accessible from my rpi over my local network

**Comment by mooreds** [comment]
You need to enable the webhook on the tenant as well.

https://fusionauth.io/docs/v1/tech/events-webhooks/writing-a-webhook#configuration has instructions on setting up a webhook.

This video may be helpful as well: https://www.youtube.com/watch?v=peyqQggiR4o

If you have additional questions about setting up a webhook, please post in the support forum or open a support ticket (if you have a paid plan including support).

https://fusionauth.io/community/forum/

https://account.fusionauth.io/account/support

**Comment by Bad-Pop** [comment]
> You need to enable the webhook on the tenant as well.
> 
> https://fusionauth.io/docs/v1/tech/events-webhooks/writing-a-webhook#configuration has instructions on setting up a webhook.
> 
> This video may be helpful as well: https://www.youtube.com/watch?v=peyqQggiR4o
> 
> If you have additional questions about setting up a webhook, please post in the support forum or open a support ticket (if you have a paid plan including support).
> 
> https://fusionauth.io/community/forum/
> 
> https://account.fusionauth.io/account/support

Thank you very much! I'm sorry I should have read the doc better because now it works properly.

**Comment by mooreds** [comment]
Glad you got it working!
