### ISSUE TITLE
Allow password reset with the userId

### ISSUE THREAD

**Issue by davidb-e4s** [FusionAuth/fusionauth-issues#177]
### Problem
Currently we can only reset user passwords with either a passwordResetId or a LoginId which is username or email. I only pass userId between my services. We could add it as another param etc but I feel you should be able to reset password by unique userId

### Solution
Allow the reseting of passwords using userId, existing pass & new pass

### Alternatives/workarounds
Passing the email address through from the gateway, this is what we have to do now but I'd rather not have the extra param in my code. The other alternative is looking up the user details and getting the email but this is an additional call.

**Comment by robotdan** [comment]
Thanks for the request @davidb-e4s. 

I'm assuming you're referring to using the Change Password API with an API key 

![image](https://user-images.githubusercontent.com/1148709/59202801-7b180500-8b5a-11e9-8d74-c67b977fea4e.png)
https://fusionauth.io/docs/v1/tech/apis/users#change-a-users-password


If so, this is something we could get into plan, it is an easy update. 

Another option for you to would be to use the Update API, with this API you'd only need the `userId` but this API does not take the current password to perform any validation, and you'd have to retrieve the current user and then perform the update, so it would be at least two API calls.

**Comment by davidb-e4s** [comment]
Hi Dan, 

Yes thats the one thanks. 

I'm using the email as another parameter for now from our API gateway. Not a crucial feature but def a nice to have. 

Thanks

David

**Comment by robotdan** [comment]
I believe you can use this API with a `userId` when using an API key.
