### ISSUE TITLE
Revoke Refresh token by Id fails when expired

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1772]
### Description 
Unexpected behavior when revoking refresh tokens.

### Affects versions
Dev, latest

### Steps to reproduce
1. Generate a refresh token.
2. Let the token expire before it is reaped by the reaper.
3. Attempt to revoke this refresh token by Id.
4. `404` is returned.  
5. Get all tokens for the user and see that the token with that same id (step 3) remains present.  It will only be removed by the reaper.

### Expected behavior

An expired token should be effectively "useless".  So this may be a doc bug.

### Platform
dev setup

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Working as designed. I suppose we could also remove expired tokens from the retrieve request, but currently it returns all tokens that haven't been reaped.

**Comment by robotdan** [comment]
Anyone can check the expiration of a token. When you view the token in the UI we calculate the expiration and then display expired tokens in red. We could remove these from the retrieve as well if there is no benefit to returning them.

**Comment by robotdan** [comment]
> Remove them from the retrieve, and then if a configuration change was made, return them on the next select.


This may be the easiest solution, the one strange edge case would be if you were to change the TTL before the reaper runs, a token may be returned on a subsequent API call. This is probably an acceptable behavior. It is unlikely to occur.
