### ISSUE TITLE
Entity search default text incorrect

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1774]
### Description 

When you go to grant an entity permissions on another entity in the admin UI, you are presented with a search box. The default text in the search box is incorrect and confusing.

### Affects versions

1.36.7

### Steps to reproduce

1. Create an entity type
2. Create two entities
3. Go the grant screen for one of the entities

The default text for the search box says `Search on email, name or role`.

### Expected behavior

You should see an entity specific search "call to action" such as `Search on entity name`.

### Screenshots

<img width="601" alt="Screen Shot 2022-06-29 at 10 37 57 AM" src="https://user-images.githubusercontent.com/91825/176465026-e3ceb182-4847-431e-9627-2da9b145daac.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Text fixed in `master` for `1.36.8`. Additional fixes coming in `1.37.0`.
