### ISSUE TITLE
In 1.36.7, POST /api/login returns 500 [Exception] FusionAuth encountered an unexpected error

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#1777]
### Description 
In 1.36.7, POST /api/login returns 500 [Exception] FusionAuth encountered an unexpected error

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

- 1.36.7 -> affected
- 1.36.4 -> working nromally

### Steps to reproduce

This happened after upgrading from FusionAuth 1.36.4 to 1.36.7. I will try to downgrade later and update the issue.

1. Call POST /api/login with the following payload (redacted)

```json
{
  "applicationId": "5691331c-b95d-4214-9de0-7ef0fd067cf9",
  "loginId": "hendy@example.com",
  "password": "XXX"
}
```

This happens any applicationId and any loginId in FusionAuth.

### Expected behavior
Logged in

### Screenshots

<img width="807" alt="image" src="https://user-images.githubusercontent.com/24123/176582501-bca6174f-bbef-43a3-857b-aea8036e4e3c.png">

### Platform
(Please complete the following information)
 - Device: any (REST API)
 - OS: any (REST API)
 - Browser + version: Chrome, any - tested with multiple OSes
 - Database: MySQL 8.0

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Environment:

- using Docker deployment, in AWS Fargate

**Comment by ceefour** [comment]
Update: Problem was caused by MySQL database server issue. After restarting the MySQL server, problem was resolved.

**Comment by mooreds** [comment]
Glad you got it working, @ceefour !
