### ISSUE TITLE
Paste doesn't work with admin UI "Authorized redirect URLs"

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1784]
### Description 

You can't paste a redirect URI into the "Authorized redirect URLs" form field.

### Affects versions

1.36.8, and as many as I've used in 2 years.

### Steps to reproduce

1. Create an application
2. Go to the "OAuth" tab
3. copy a url like: `http://example.com` to the clipboard.
4. Try to paste it into the "Authorized redirect URLs" field.
5. Tab or click off of the field.

It doesn't paste.

### Expected behavior

Let me paste in a value.

Workaround is to paste the value, backspace and then re-enter the deleted character. Not great UX.

### Platform

Seen it on firefox in the mac and chrome in the mac.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

This came out of the stream with https://www.twitch.tv/endingwithali

### Release Notes
Enhance the widget used in multi-value select controls to accept a value when pasting. For example, you may now paste a value from the clipboard directly into the `Authorized redirect URLs` field. While previously the paste operation worked, the user would have to click the value to confirm. If you clicked off of the field, the value would not be saved.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/315
