### ISSUE TITLE
Better forgot password handling with connectors

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1786]
### Problem

Right now, if you are performing a slow migration and a user has forgotten their password, the options are not great. 

The user doesn't exist in FusionAuth, so clicking the Forgot Password link will display an error message saying "we've sent you an email" but no email will be sent.

We don't fire [this webhook](https://fusionauth.io/docs/v1/tech/events-webhooks/events/user-password-reset-start) until we have a valid user, so we can't know that this user is trying to retrieve their password.

The connector [should return a 404](https://fusionauth.io/docs/v1/tech/connectors/generic-connector#response) if the user exists with the wrong password or if the user doesn't exist.

So as far as I know, the recommended course of action is to change the forgot password error message display to say "please call customer service to reset your password" or something similar. 

### Solution

It would be great if there was some way to interface with the existing system to trigger a forgot password process from the old system. Perhaps we could have either a webhook when the forgot password flow is started, even with a user who doesn't exist in FusionAuth, or some way to submit a 'forgot password request' to an external endpoint so that the slow migration implementor could handle it in some other fashion (sending the email themselves from their old system).

### Alternatives/workarounds
A clear and concise description of any alternative solutions or workarounds you've considered.

### Additional context

Came up in a discussion in a client slack.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/895

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/895 ?

**Comment by mooreds** [comment]
Perhaps. I offer some other suggestions (letting the legacy system trigger a password reset, having a webhook for every time a forgot password flow is started, even for non-existent users), but I like the solution outlined in #895 better.

I'll close as a duplicate.
