### ISSUE TITLE
Key ending in = fails when calling JWT vend endpoint

### ISSUE THREAD

**Issue by theogravity** [FusionAuth/fusionauth-issues#1787]
### Description 

When I attempt to vend a JWT using an API super key without the key manager flag, I'll get a 401 as a response. If I use a key with key manager, I am able to successfully vend the JWT.

I should be able to vend the JWT without the key manager flag.

### Affects versions
1.36.5 (cloud hosted with FusionAuth.io)

### Steps to reproduce

1. Create an API key without the key manager flag
2. Call the Vend JWT API using the API key with a valid body
3. FusionAuth returns a 401 response.

### Expected behavior

The JWT should vend.

### Platform
 - Hosted FusionAuth via FusionAuth.io platform

### Additional context

I'd prefer to not use an API key with the key manager flag enabled if possible when vending a JWT.

**Comment by mooreds** [comment]
@theogravity I'm unable to replicate this against the sandbox environment, which is running 1.36.8. I looked at the release notes and I don't think there are any changes between 1.36.5 and 1.36.8 which would affect this.

Here's my curl script:

```
curl -XPOST -H "Authorization: 90d8fb62-6f13-47d4-8ef6-1c3e687883c6" https://sandbox.fusionauth.io/api/jwt/vend -H "Content-type: application/json" -d '{
  "claims": {
      "id": "c74aa258-3a04-4d3f-83c5-e5b20af96e7a",
          "iss": "piedpiper.com"
	    },
	      "keyId": "fd35ec37-5985-fba9-55b0-7c24caea7851",
	        "timeToLiveInSeconds": 300
		}'
```

Can you see if you can replicate the issue against the sandbox? Can you share your script which causes the issue? 

Or can you provide any more insight into what you are seeing (the kind of key you are using to sign the jwt, the claims, etc) which might help us characterize this bug?

Thanks!

**Comment by theogravity** [comment]
> @theogravity I'm unable to replicate this against the sandbox environment, which is running 1.36.8. I looked at the release notes and I don't think there are any changes between 1.36.5 and 1.36.8 which would affect this.
> 
> Here's my curl script:
> 
> ```
> curl -XPOST -H "Authorization: 90d8fb62-6f13-47d4-8ef6-1c3e687883c6" https://sandbox.fusionauth.io/api/jwt/vend -H "Content-type: application/json" -d '{
>   "claims": {
>       "id": "c74aa258-3a04-4d3f-83c5-e5b20af96e7a",
>           "iss": "piedpiper.com"
> 	    },
> 	      "keyId": "fd35ec37-5985-fba9-55b0-7c24caea7851",
> 	        "timeToLiveInSeconds": 300
> 		}'
> ```
> 
> Can you see if you can replicate the issue against the sandbox? Can you share your script which causes the issue?
> 
> Or can you provide any more insight into what you are seeing (the kind of key you are using to sign the jwt, the claims, etc) which might help us characterize this bug?
> 
> Thanks!

I created a new super key and was able to get a `200` result out of it. One thing I noticed with the `401` key I'm using is that the key has a `=` at the end of it, and the length is different compared to the other keys.

The permissions are the same for both keys, and the only difference I can determine between them is the secret format itself.

Is there an e-mail I can reach out to for someone to take a look at my instance? I can provide the instance hostname and key id.

**Comment by theogravity** [comment]
> @theogravity I'm unable to replicate this against the sandbox environment, which is running 1.36.8. I looked at the release notes and I don't think there are any changes between 1.36.5 and 1.36.8 which would affect this.
> 
> Here's my curl script:
> 
> ```
> curl -XPOST -H "Authorization: 90d8fb62-6f13-47d4-8ef6-1c3e687883c6" https://sandbox.fusionauth.io/api/jwt/vend -H "Content-type: application/json" -d '{
>   "claims": {
>       "id": "c74aa258-3a04-4d3f-83c5-e5b20af96e7a",
>           "iss": "piedpiper.com"
> 	    },
> 	      "keyId": "fd35ec37-5985-fba9-55b0-7c24caea7851",
> 	        "timeToLiveInSeconds": 300
> 		}'
> ```
> 
> Can you see if you can replicate the issue against the sandbox? Can you share your script which causes the issue?
> 
> Or can you provide any more insight into what you are seeing (the kind of key you are using to sign the jwt, the claims, etc) which might help us characterize this bug?
> 
> Thanks!

@mooreds I created a new super key and was able to get a `200` result out of it. One thing I noticed with the `401` key I'm using is that the key has a `=` at the end of it, and the length is different compared to the other keys.

The permissions are the same for both keys, and the only difference I can determine between them is the secret format itself.

Is there an e-mail I can reach out to for someone to take a look at my instance? I can provide the instance hostname and key id.

**Comment by theogravity** [comment]
@mooreds I tried the sandbox and your script. I think I realized my mistake

I've been using the secret value as part of the the `Authorization` header vs the secret id. I created an API key in the sandbox with the same secret value. When I went to use your script, something made me realize that the `Authorization` value was the key id and not the secret. Using the secret does `401`, while using the key id gave the appropriate `200`.

I think the confusion stems from the Authentication docs not specifying that the value is to be the id and not the secret itself.

https://fusionauth.io/docs/v1/tech/apis/authentication#api-key-authentication

When I use the TypeScript SDK, I've been using the secret value and not the id:

`new FusionAuthClient(FUSION_AUTH_API_KEY, FUSION_AUTH_ISSUER_URL, FUSION_AUTH_TENANT_ID);`

But I haven't had any problems doing it this way until I started using vend. So kind of confused around when the id vs secret should be used.

**Comment by theogravity** [comment]
> > One thing I noticed with the 401 key I'm using is that the key has a = at the end of it, and the length is different compared to the other keys.
> 
> Hmmm. This is really interesting. Can you recreate against the sandbox (you can specify the value of the key string when you create an API key)? If so, can you share your repro steps?

@mooreds 

I added the API key to the sandbox.

Here's the following outputs:

When using a key id:

```
curl -XPOST -H "Authorization: e9e92a11-b527-475d-a38c-79d9f3b4b5d7" https://sandbox.fusionauth.io/api/jwt/vend -H "Content-type: application/json" -d '{
    "claims": {
        "id": "c74aa258-3a04-4d3f-83c5-e5b20af96e7a",
            "iss": "piedpiper.com"
          },
            "keyId": "fd35ec37-5985-fba9-55b0-7c24caea7851",
              "timeToLiveInSeconds": 300
          }' -i
HTTP/2 401 
date: Mon, 11 Jul 2022 19:06:21 GMT
content-length: 0
cache-control: no-cache
```

When using the API secret (I'm aware this is exposed here, it's a throwaway value for me):

```
curl -XPOST -H "Authorization: sBLuOMkmjoNlC6giiJl1lq1XtStEyVsY695MyEpb8-o=" https://sandbox.fusionauth.io/api/jwt/vend -H "Content-type: application/json" -d '{
    "claims": {
        "id": "c74aa258-3a04-4d3f-83c5-e5b20af96e7a",
            "iss": "piedpiper.com"
          },
            "keyId": "fd35ec37-5985-fba9-55b0-7c24caea7851",
              "timeToLiveInSeconds": 300
          }'
{"fieldErrors":{"keyId":[{"code":"[invalid]keyId","message":"Invalid"}]}}
```

**Comment by theogravity** [comment]
When I try the 3rd case in my own hosted instance, it does not work for me. I've made sure that the `keyId` matches with one I have from the key master and that the API key to use with it is a super key with no tenant attached.

It does work with a super key. So it has to be something with my instance.

**Comment by theogravity** [comment]
I really do think it has to do with the key format that the terraform module is producing.

If I manually create a key and let the UI specify the value without the key manager flag, it works.

**Comment by theogravity** [comment]
Here's the following terraform code (I understand this is a 3rd party module):

```
terraform {
  required_providers {
    fusionauth = {
      source  = "gpsinsight/fusionauth"
      version = ">= 0.1.72"
    }
  }
}

provider "fusionauth" {
  api_key = "1XKJ1UZ6IaJpoRjQoVqExcbWMSCr0PyxfGjY2ZhY-WFYdUAgXJKmHyrx"
  host    = "https://sandbox.fusionauth.io/"
}

resource "fusionauth_api_key" "fa_api_key" {
  description = "Terraform-generated API key for Github issue 1787"
}
```

Using the key generated from the module gives the `401`:

```
curl -XPOST -H "Authorization: WR3xXdLt-zFehKk6I8MRJgHWeh47ySj3nBqTC9GblnE=" https://switchboard-dev.fusionauth.io/api/jwt/vend -H "Content-type: application/json" -i -d '{
    "claims": {
        "id": "c74aa258-3a04-4d3f-83c5-e5b20af96e7a",
            "iss": "piedpiper.com"
          },
            "keyId": "c753a44d-7f2e-48d3-bc4e-c2c16488a23b",
              "timeToLiveInSeconds": 300
          }'
```

**Comment by mooreds** [comment]
So I'm not even sure this is a terraform issue. Can you please double check the keyId and let me know?

**Comment by mooreds** [comment]
Hiya,

Thanks for the additional steps. I think this is a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1675

The issue is that when you create an API key with terraform and don't specify permissions, you get internal JSON like this:

```
{
  "apiKey": {
    "id": "e1af1178-3919-467d-9d2d-4d6a3cd7d121",
    "insertInstant": 1657567895120,
    "key": "WR3xXdLt-zFehKk6I8MRJgHWeh47ySj3nBqTC9GblnE=",
    "keyManager": false,
    "lastUpdateInstant": 1657567895120,
    "metaData": {
      "attributes": {
        "description": "Terraform-generated API key for Github issue 1787"
      }
    },
    "permissions": {}
  }
}

```

But when you do it from the UI, you get internal JSON like this:

```
{
  "apiKey": {
    "id": "9b1a2d37-ed86-45cc-8349-c24f21ec491c",
    "insertInstant": 1657520712252,
    "key": "90d8fb62-6f13-47d4-8ef6-1c3e687883c6",
    "keyManager": false,
    "lastUpdateInstant": 1657571933229,
    "metaData": {
      "attributes": {
        "description": "Sandbox API key"
      }
    }
  }
}
```

Notice in the first example, permissions are `{}`. In the second, there are no permissions set. This is a known issue with the terraform client and the workaround is specified in 1675:

> If you edit the api key in the front end and resave (no changes) the "permissions": {} part disappears and the api key starts working.

This is a bummer, but a known issue.

If you agree, please close this issue. If I've missed something, please let me know.

**Comment by mooreds** [comment]
Also, happy to accept PRs against the terraform provider to fix the root cause :)

**Comment by theogravity** [comment]
Thanks so much for looking into this. Glad we've found the root cause.

**Comment by theogravity** [comment]
Is it possible for the UI to detect that the key was created using an empty perms object and inform the user somehow?

**Comment by mooreds** [comment]
that would be a great note to put onto https://github.com/FusionAuth/fusionauth-issues/issues/1675

I'd add it, but it means more coming from a user. Can you please do so? I think some kind of UI thing would be helpful for other folks too.
