### ISSUE TITLE
Use MEDIUMTEXT instead of TEXT columns for MySQL

### ISSUE THREAD

**Issue by darkeagle1337** [FusionAuth/fusionauth-issues#1788]
### Problem
Sometimes it is necessary to store inline images in HTML email templates. But it is impossible because at the moment we can only store 64KB in a column with the type TEXT. 
It would be helpful if you could change the type to MEDIUMTEXT, then it would be 16MB, which should be enough. 

### Solution
Change the TEXT columns for templates to MEDIUMTEXT
```
ALTER TABLE email_templates MODIFY default_html_template MEDIUMTEXT;
ALTER TABLE email_templates MODIFY default_text_template MEDIUMTEXT;
ALTER TABLE email_templates MODIFY localized_html_templates MEDIUMTEXT;
ALTER TABLE email_templates MODIFY localized_text_templates MEDIUMTEXT;
```

### Fusionauth
Version: 1.35.0
Database: MySQL

Thanks
Christian

**Comment by robotdan** [comment]
Done!
