### ISSUE TITLE
Tenants have custom data but no UI for it

### ISSUE THREAD

**Issue by elliotdickison** [FusionAuth/fusionauth-issues#1789]
### Problem

Tenants let you set and retrieve custom data, but you cannot view the data in the FusionAuth UI like you can for users.

### Solution

Display the data in the UI. Edit functionality would be out of scope IMO.

### Alternatives/workarounds

You can fetch the data using the GET tenant endpoint.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1422
- https://github.com/FusionAuth/fusionauth-issues/issues/1439

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This is available in the admin UI in the view dialog. The data will only show up if defined. See attached screenshot. 

![image](https://user-images.githubusercontent.com/1148709/179338799-25cc78e7-323f-44b0-9d49-eeec43f8917e.png)
