### ISSUE TITLE
Unable to use let / optional chaining with GraalJS

### ISSUE THREAD

**Issue by theogravity** [FusionAuth/fusionauth-issues#1790]
### Description 
The editor shows errors around let / optionals.

### Affects versions
1.36.5

### Steps to reproduce
In the lambda editor, select GraalJS, and add in the following function:

```
function testFunction() {
  let a = 'a';
  
  if (a?.length > 0) {
    console.log('test');  
  }
}
```

### Expected behavior
The code should pass validation checks.

### Screenshots

<img width="728" alt="CleanShot 2022-07-13 at 11 25 42@2x" src="https://user-images.githubusercontent.com/855434/178804649-8dfb50f8-540a-4a6f-974f-251587dbf33e.png">

### Platform

Cloud-hosted FusionAuth via fusionauth.io

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Also tried this in the FusionAuth sandbox with the same result.

**Comment by mooreds** [comment]
If you upload the lambda via API, are you able to use the feature? I wonder if it is an issue with the admin UI or the underlying engine.

**Comment by theogravity** [comment]
> If you upload the lambda via API, are you able to use the feature? I wonder if it is an issue with the admin UI or the underlying engine.

I've also used Terraform to do it without success, which I'm assuming uses the API.

**Comment by theogravity** [comment]
@mooreds Still seeing the issue for version `1.38.1`:

<img width="993" alt="CleanShot 2022-09-01 at 15 20 14@2x" src="https://user-images.githubusercontent.com/855434/188022720-ea69f1a4-747d-45db-ae84-6b1f9e9d429d.png">

<img width="843" alt="CleanShot 2022-09-01 at 15 20 26@2x" src="https://user-images.githubusercontent.com/855434/188022737-17db4d44-fa98-49c1-a23f-e2c9307020d6.png">

**Comment by robotdan** [comment]
This issue was resolved in version 1.37.0.

> It does let me submit it though and it does get saved (it def did not in the prior version I was using).

This sounds like a different issue. It is just an issue with the syntax validation in the editor. Can you open a separate issue and we'll review the syntax validation in the editor.

**Comment by ebahsini** [comment]
qq, did we create separate issue for this?

**Comment by mooreds** [comment]
@ebahsini I don't see it.

@theogravity did you file one and we maybe missed it?

**Comment by theogravity** [comment]
I haven't

**Comment by ebahsini** [comment]
https://github.com/FusionAuth/fusionauth-issues/issues/1889
