### ISSUE TITLE
Enhancements to Oauth2 logout endpoint

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1792]
### Description
- Support expired id_token_hint on OAuth2 Logout endpoint
- Support POST request

### Additional Context
- https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout
- https://openid.net/specs/openid-connect-frontchannel-1_0.html

### Documentation
- [x] Update endpoint doc to indicate both the `GET` and `POST` methods are supported.
- [x] Update endpoint doc to indicate the `id_token_hint` parameter may be an expired token.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by harishreddy-m** [comment]
Fusionauth is passing JWT token as id_token_hint in logout URL. Is this the right behaviour?
