### ISSUE TITLE
Add a policy to revoke refresh tokens when a user enables MFA

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1794]
### Description
When MFA is enabled, we may want to revoke all refresh tokens. 

`Tenant > Edit > JWT > Refresh Token settings > Refresh Token revocation > On multi-factor enable`

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/158

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/2007
-
