### ISSUE TITLE
Webhooks for group create and group delete events

### ISSUE THREAD

**Issue by matthew-jump** [FusionAuth/fusionauth-issues#1803]
### Problem
When a group is created or deleted in Fusion Auth, there is no webhook that will publish these events to a consumer.

### Solution
Whenever a group is created or removed from Fusion Auth I would expect to be able to subscribe to a webhook event for said actions so that I can keep any downstream applications up to date. Similar to the user.create and user.delete webhook events, I would like to see for example a group.create and group.delete webhook event that will publish said events to a consumer.

### Alternatives/workarounds
The current workaround would be to poll the group endpoint for any changes. 

### Additional context
This becomes beneficial especially around SCIM since groups can be created/deleted via an IDP but would need to be known by the service provider. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/633

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by spwitt** [comment]
- #633

**Comment by mooreds** [comment]
@spwitt Note that #633 is for group membership changes and is currently in the eng team plan. This is a different, related webhook, for group adding/removal. (Maybe that's already obvious to you :) , but I just wanted to reiterate.)

**Comment by spwitt** [comment]
Oops. That was my bad @mooreds. I thought it was a duplicate, but I'll leave the link since the two are related. Thanks for clarifying.
