### ISSUE TITLE
Sandbox has weirdness around searching and pagination

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1808]
### Description 

Haven't seen this elsewhere, not sure what is going on. Note how the result says '12 of 72'.
![Screen Shot 2022-08-03 at 4 50 23 PM](https://user-images.githubusercontent.com/91825/182725870-2598efb5-2a53-4f8f-b311-aca8f9208171.png)

### Affects versions

1.36.8 on sandbox

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

The sandbox will be reset soon, maybe see if this issue re-appears?

**Comment by robotdan** [comment]
This is just due to how the sandbox is "abused". The search index is likely out of sync - we rebuild it regularly w/out necessarily rebuilding the index. The fix is to rebuild the index.
