### ISSUE TITLE
FusionAuth doesn't start when installed via homebrew

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1815]
### Description 

Homebrew doesn't work. See https://github.com/FusionAuth/homebrew-fusionauth/issues/8 for full details.

An examination of the homebrew install script reveals it is still referencing catalina.sh

https://github.com/FusionAuth/homebrew-fusionauth/blob/master/Formula/fusionauth-app.rb#L38

### Affects versions

1.37.0

### Steps to reproduce

Try to install 1.37 via homebrew.

Get startup error.

### Expected behavior

You can start FusionAuth 1.37 via homebrew on mac

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

First filed here: https://github.com/FusionAuth/homebrew-fusionauth/issues/8 by @ootinger

**Comment by robotdan** [comment]
Fixed via https://github.com/FusionAuth/homebrew-fusionauth/issues/8.
