### ISSUE TITLE
Can't create a new application with an unlicensed FusionAuth instance due to MFA policy error

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1817]
### Description 

When I try to save a new application with a fresh install of 1.37.0, I am unable to do so, because the multi-factor 'on login policy' can't be left in the default state, but the other two choices require a license.

### Affects versions

1.37.0

### Steps to reproduce

* Do a fresh install of 1.37.0. Do not add a license.
* Log into the admin UI
* Attempt to add an application

### Expected behavior

You can chose 'disabled' no matter the state of your license, as that is the default behavior before 1.37.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Interestingly, I can create an application via the API, but when I try to edit it in the UI, I get the same validation error w/r/t the MFA config.

```
curl -XPOST -H "Authorization: bf69486b-4733-4470-a592-f1bfce7af580" https://local.fusionauth.io/api/application -H 'Content-type: application/json' -d '{ "application": { "name": "test" } }'
```

**Comment by alf1e** [comment]
Same issue here.
