### ISSUE TITLE
Admin UI around creating user with email unverified confusing

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1819]
### Description 
I find this field name text confusing.

### Affects versions

1.37

### Steps to reproduce

* Log into the admin ui
* Add a user

If the user unchecks "Require email verification" then the user has their email verified. If they check it, the user's email is not verified, but they can verify it via any of the implicit verification methods or by using the new API to verify emails.

That label is very unintuitive in my opinion.

### Expected behavior
I would expect this form field to say something more explicit like: "Verified email address" where true means it is verified and false means it is not.

### Screenshots

![Screen Shot 2022-08-11 at 8 48 20 AM](https://user-images.githubusercontent.com/91825/184161947-8bf06d77-3e75-4568-a7fd-8bcf12435a51.png)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

https://github.com/FusionAuth/fusionauth-issues/issues/1319 is the issue this functionality was added to.

**Comment by robotdan** [comment]
Hm... perhaps the label is confusing, the the checkbox does what I expect it to do.

**Comment by mooreds** [comment]
Yes, I think it is mostly the label that is confusing.

**Comment by mooreds** [comment]
Whoops have it wrong. When this is unchecked, the user has their email automatically verified. When this is checked, the email address is marked as unverified. I think it'd be good to change the text to 'Mark email unverified' or something like that, because the 'require email to be verified' verbiage leaves out some use cases (what if I don't care if the email address is verified?). But this is lower priority now.

**Comment by robotdan** [comment]
Maybe we invert it and do this?

![image](https://user-images.githubusercontent.com/1148709/184183458-90e75018-6593-4c9e-a43b-bf460aba455b.png)
