### ISSUE TITLE
Can't see a use case for email entry page if managed domains are specified for an IdP

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#182]
If Managed domains are specified for an IdP (SAML or oAuth) then the user is being shown with email entry page. After entering the email user is being redirected to Idp Login page.

I see the email entry page here is redundant. UX would be great if user is automatically redirected to respective IdP login page if that IdP has any managed domains specified in fusionauth. 

Possible Solution:
1. Redirect user to IdP login page if there are any managed domains specified.
           OR
2. Show a checkbox beneath managed domains to select the option to choose whether to show email entry page.

**Comment by robotdan** [comment]
Hi @prabhakarreddy1234, 

The reason for this design is that until we know the user's email address we do not know if we need to collect the user's password or send them to another IdP. 

> Redirect user to IdP login page if there are any managed domains specified.

If we did this, it would mean we would not allow users to login to FusionAuth, only through an external provider. At a minimum, an admin user will have to be able to login to FusionAuth. 

The use case we usually see is that most users will log into FusionAuth, and some employees or clients that have their account in their own corporate IdP will use the external configuration based upon their domain. 

Do you have a use case in mind where all users should be redirected? 

> Show a checkbox beneath managed domains to select the option to choose whether to show email entry page.

This could be an option, the downside of this would be that it would assume that a user that can log into an external IdP - AD for example, could also log into FusionAuth. This is likely not the case, most users that are logging in via an external IdP configuration will not know their password in FusionAuth. 

Can you describe a use case where these options would be necessary? Or are you looking for a feature as described here https://github.com/FusionAuth/fusionauth-issues/issues/178?

Thanks!

**Comment by robotdan** [comment]
@prabhakarreddy1234 let me know if you have more comments on this, happy to discuss further if you have some ideas. 

I'll plan to close out this issue if there are no further comments.

**Comment by prabhakarreddy1234** [comment]
@robotdan  this is similar to #178 . Closing this one.
