### ISSUE TITLE
Docker image still has tomcat references

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1820]
In the docker image `1.37.1` I still see 

```
root@c80d352ea38f:/# find . | grep tomc
./usr/local/fusionauth/fusionauth-app/tomcat
./usr/local/fusionauth/fusionauth-app/tomcat/bin
./usr/local/fusionauth/fusionauth-app/tomcat/bin/FusionAuthApp.ps1
./usr/local/fusionauth/fusionauth-app/tomcat/bin/FusionAuthApp.exe
```

are these included but unused?

_Originally posted by @kevcube in https://github.com/FusionAuth/fusionauth-issues/issues/1671#issuecomment-1212179830_

**Comment by robotdan** [comment]
Fixed. https://github.com/FusionAuth/fusionauth-app/commit/9278d4ca88b3528cc84ceee390644a3fedea25b0
