### ISSUE TITLE
Add a config to "email user" for the failed login configuration

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1823]
### Description
When a user action is configured to "email user" the intent is that the user of that User Action decides if they wish to perform this step. 

To be correct - we should an "Email user" option in the Failed Login configuration when the User Action selected supports "Email User". 

Then we should migrate this such that if anyone has configured their User Action to email user - and they are using that as part of a Failed Login configuration - we set it to true.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1801

### Documentation
- [x] API
- [x] Tenant UI config

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/158
