### ISSUE TITLE
Account templates are not being translated to the selected language

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1829]
### Description 

The account related templates are not translated as expected.

### Affects versions

- 1.36.8
- 1.37.2 (current latest)

### Steps to reproduce

Based on this official explanation video: https://youtu.be/RWQsRXPCUVc

1. Duplicate the FusionAuth default theme
2. Go to the duplicated theme edition panel
3. Add a French translation with a copy of the [official messages set](https://raw.githubusercontent.com/FusionAuth/fusionauth-localization/master/theme/messages_fr.properties).
4. Save the theme
5. On the default tenant settings, change the theme to the duplicated one
6. Create an application relying on the default tenant
7. Register an account to that application
8. On a private navigation, go to one of the `/account/*` page with `client_id` set to the id of the created application and login with the registered user when asked
9. Select the French language on the language selector or add `locale=fr` to the current URI

### Current behavior

The page is not translated, kept in the default English language.

### Expected behavior

The page should be translated into French.

### Screenshots

<details>

![image](https://user-images.githubusercontent.com/1698357/185153615-13b18091-e8ce-451e-b289-21908f4b91ef.png)

</details>

### Platform
(Please complete the following information)
 - Device: Computer
 - OS: Linux
 - Browser + version: Firefox Developer Edition 102.0b4 (64-bit)
 - Database: PostgresSQL 12.1

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Please note that the oauth2 related pages are translated as expected, for example:

<details>

![image](https://user-images.githubusercontent.com/1698357/185154224-986577a6-349c-4def-ab6b-d24d1d87d4da.png)

</details>

**Comment by mooreds** [comment]
Thanks! This is because the keys for the account page haven't been translated into French. 

We have a script to show the list of missing translation keys for each language. Here's the French output:

https://github.com/FusionAuth/fusionauth-localization/blob/master/missing-translations/messages_fr.properties

This includes messages on the account pages you reference, as well as others.

We definitely accept PRs in that repository, if you'd like to provide a French (or other language) translation.

Does that help, @soullivaneuh ?

**Comment by soullivaneuh** [comment]
Indeed, will do. Thanks.

However, please consider https://github.com/FusionAuth/fusionauth-issues/issues/1830 for the oauth two factor method selector.
