### ISSUE TITLE
OAuth: Two factor method selection list does not use translations

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#1830]
### Description 

On the `templates/oauth2/two-factor-methods.ftl` template:

```
[#macro methodOption id method]
 <div class="form-row" >
   <label>
     <input type="radio" name="methodId" value="${id}" [#if id = methodId!'']checked[/#if]>
     [#if method.method == "email"]
       <span>Email message</span>
       <span>
        [#assign index = method.email?index_of("@")/]
        Get a code at ${method.email?substring(0, index + 2)}&hellip;
       </span>
     [#elseif method.method == "authenticator"]
       &nbsp;<span>Authenticator</span>
        <span>
         Get a code from your authenticator app
        </span>
     [#elseif method.method == "sms"]
        <span>Text message</span>
        <span>
         Get a code at (***) ***-**${method.mobilePhone?substring(method.mobilePhone?length - 2)}
        </span>
     [#else]
        ${theme.optionalMessage(method.method)}
     [/#if]
     </label>
 </div>
[/#macro]
```

Translation keys should be used here.

**Comment by mooreds** [comment]
Thanks, that's certainly a bug.

**Comment by robotdan** [comment]
We could add this to the localization by default, but this can easily be localized by the end user as well.

**Comment by soullivaneuh** [comment]
@robotdan I am not sure to follow here. Yes we can, but we have to override the whole template in order to setup the translation keys.

This is quite overkill if we just want to adjust the translation and the css. This is why the translations system exists, don't you think?

**Comment by henri9813** [comment]
@robotdan .

Some people pay to have some quality of service ( in our case, we pay a license )

This mindset is not fairfull.

So the answer is not: "we could", it's: "we must".

Best regards,

**Comment by mooreds** [comment]
@henri9813 I understand your frustration. Please keep your comments constructive.

**Comment by mooreds** [comment]
@robfusion note that I submitted a PR for this: https://github.com/FusionAuth/fusionauth-app/pull/137 Feel free to review, use or toss, whatever makes sense.

**Comment by robotdan** [comment]
@mooreds approved.

**Comment by mooreds** [comment]
Awesome, merged the fix, so it'll be picked up in the next release.
