### ISSUE TITLE
Can't load some CSS and JS after upgrade from 1.33.0 to 1.37.2 due to missing mime types

### ISSUE THREAD

**Issue by sinqinc** [FusionAuth/fusionauth-issues#1831]
Hi,

We have problem problems loading some CSS and JS after upgrading from 1.33.0 to 1.37.2.

[Error] Did not parse stylesheet at 'https://{our_url}/css/fusionauth-style.css?version=1.37.2' because non CSS MIME types are not allowed in strict mode.
[Error] Refused to execute https://{our_url}/js/prime-min-1.6.4.js?version=1.37.2 as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.

FusionAuth is running in a Kubernetes cluster behind CloudFlare and load balanced by NGINX Ingress.

As a workaround, we added a Transform rules in CloudFlare to add header "Content-Type" on all .css and .js request. We also removed  "X-Content-Type-Options" on that request.

Thank you

First reported on slack.

### Affects versions
&gt;= 1.37.0

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1834

**Comment by mooreds** [comment]
I suspect that netty is not setting mime types the way that tomcat did.

Here's the headers for the CSS in 1.30 (found using curl -I 'https://sandbox.fusionauth.io/css/fusionauth-style.css?version=1.30.1')

```
Accept-Ranges: bytes
ETag: W/"162547-1629888864000"
Last-Modified: Wed, 25 Aug 2021 10:54:24 GMT
vary: accept-encoding
Content-Encoding: gzip
Content-Type: text/css
Transfer-Encoding: chunked
Date: Wed, 17 Aug 2022 17:03:06 GMT
Keep-Alive: timeout=20
Connection: keep-alive
```

Here are the same headers against 1.37 (found using curl -I 'https://sandbox.fusionauth.io/css/fusionauth-style.css?version=1.37.2')

```
date: Wed, 17 Aug 2022 17:03:57 GMT
cache-control: public
retry-after: Wed, 24 Aug 2022 17:03:57 GMT
expires: Wed, 24 Aug 2022 17:03:57 GMT
last-modified: Thu, 11 Aug 2022 18:33:29 GMT
set-cookie: fusionauth.flash-message=; Max-Age=0; Expires=Wed, 17 Aug 2022 17:03:57 GMT; Path=/
```

**Comment by robotdan** [comment]
Fixed via https://github.com/prime-framework/prime-mvc/commit/c4b94c2af4ed1c7bc336ad19eaba4776fb849863

**Comment by Aaron-Ritter** [comment]
thanks! works!
