### ISSUE TITLE
Support Authorization Server Metadata

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1832]
### Problem

I want to be able to use metadata about FusionAuth to configure my clients and other integrations.

### Solution

Support RFC 8414.

### Alternatives/workarounds

Manually read the docs for information like the AS endpoint, etc.

### Additional context

https://www.rfc-editor.org/rfc/rfc8414.html

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1029
- https://github.com/FusionAuth/fusionauth-issues/issues/1383

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1029?

**Comment by mooreds** [comment]
100% duplicate, down to the guy who submitted it :) 

Closing.
