### ISSUE TITLE
Add lambda function for extended validation during registration

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1833]
### Problem
In order to support 3rd party validation of an email address, phone number, or any various user validation during self-service registration, we may wish to add a lambda function that can optionally utilize HTTP Connect (fetch) to call out to a 3rd party service and then optionally populate an errors object for use in form validation. 

### Solution
Add a lambda function to call during registration to provided extended verification 

1. Add a new lambda type that can be assigned to self-service registration.
2. TBD, this may require advanced self-service registration or a licensed feature.
3. The lambda function should be invoked on each form submit in a multi-step registration flow
4. The lambda function will know which step is being validated, and the current data collected from the registration form. 
5. The lambda function can then optionally return field errors or general errors that can be localized using the current theme. 

There may be a case to invoke this lambda for field validation prior to a form submit. This is not currently in scope, but could be reviewed if this is a requirement. 

### Example use cases
1. Call a 3rd party API to perform inline email verification
2. Call a 3rd party API to perform identity verification
3. Call a 3rd party API such as CleanSpeak to perform username, first name or last name profanity filtering. 

### Related requirements
- https://github.com/FusionAuth/fusionauth-issues/issues/1629

### Alternatives/workarounds
N/A

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by gnarlium** [comment]
Ideally, the lambda would be able to reference secrets stored in Key Master, instead of having secrets hardcoded into the lambda. Inclusion of this type of functionality is alluded to in https://github.com/FusionAuth/fusionauth-issues/issues/1629, though I'm not sure if that's _exactly_ what's being requested. But, if this is not feasible, hardcoding secrets could be a practical alternative.

**Comment by robotdan** [comment]
Internally
- https://github.com/FusionAuth/fusionauth-app/pull/173
