### ISSUE TITLE
When upgrading to 1.38.0 the theme stopped working

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#1834]
### Description 
We upgraded fusionauth to 1.38.0 which caused our custom theme to stop working and switching back the tenant to the default theme does not work either.

### Affects versions
&gt;= 1.37.0

### Steps to reproduce
1. have a custom theme deployed
2. upgrade to 1.38.0
3. check UI

### Expected behavior
Either updating/fixing our custom theme should work or switching to the default theme.

### Screenshots
![image](https://user-images.githubusercontent.com/12079732/185504508-9a82853e-b77e-4eac-ac25-a9622b27ad5b.png)
![image](https://user-images.githubusercontent.com/12079732/185504602-2ad38dd6-6bd0-4889-a26e-8750db6c5be6.png)

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1831

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
@Aaron-Ritter thanks for opening the issue. Which version were you upgrading from? Are there any error messages in the logs (event log, system log)?

**Comment by mooreds** [comment]
FYI you can override the theme temporarily by following these instructions: https://fusionauth.io/docs/v1/tech/themes/#troubleshooting

**Comment by Aaron-Ritter** [comment]
> @Aaron-Ritter thanks for opening the issue. Which version were you upgrading from? Are there any error messages in the logs (event log, system log)?

1.37.2

Sadly `&bypassTheme=true` does not work either. I have the feeling the default theme is broke too as I am able to switch the theme but it wont get better.

**Comment by Aaron-Ritter** [comment]
i found the following output in the browser console:

```
identity.sofo.dev/:1 Refused to apply style from 'https://identity.my.cust.domain/css/fusionauth-style.css?version=1.38.0' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
5
Refused to execute script from '<URL>' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
identity.sofo.dev/:1 Refused to execute script from 'https://identity.my.cust.domain/js/jshint-0.7.0.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
identity.sofo.dev/:1 Refused to execute script from 'https://identity.my.cust.domain/js/codemirror-min-5.17.0.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
identity.sofo.dev/:1 Refused to execute script from 'https://identity.my.cust.domain/js/Chart-2.7.1-min.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
identity.sofo.dev/:1 Refused to execute script from 'https://identity.my.cust.domain/js/handlebars.runtime.min-v4.7.6.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
identity.sofo.dev/:1 Refused to execute script from 'https://identity.my.cust.domain/js/prime-min-1.6.4.js?version=1.38.0' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
```

**Comment by mooreds** [comment]
Ah. I think this might be related to this issue: https://github.com/FusionAuth/fusionauth-issues/issues/1831

Are you using a proxy that can modify the CSS headers?

**Comment by mooreds** [comment]
Also, which browser is that?

**Comment by Aaron-Ritter** [comment]
we are using a very simple traefik proxy setup without any modifications to the content. by side the security setting `contentTypeNosniff = true` which is causing the block, but ultimately the mime type is wrong as mentioned by the browser console out:

the console error is visible in firefox as well as chrome: `was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff)`

this was working in the past, so either the css file are corrupted in the latest build, or something in delivering these css file has changed.

**Comment by mooreds** [comment]
I tried to recreate by starting up a docker instance at 1.37.2, duplicating the default theme, setting that to be the theme used by the tenant, then upgrading to 1.38.0.

I saw no issues, but was using FireFox on a mac against localhost, which might have relaxed requirements.

Can you share the browser you were using that you saw this issue in? Can you duplicate it if you run FusionAuth locally?

**Comment by Aaron-Ritter** [comment]
what is the difference between on how these non working are delivered:
https://identity.my.cust.domain/css/fusionauth-style.css?version=1.38.0
https://identity.my.cust.domain/js/prime-min-1.5.3.js?version=1.38.0

vs for example these working:
https://identity.my.cust.domain/css/font-awesome-4.7.0.min.css

**Comment by Aaron-Ritter** [comment]
i checked the logfiles of all 3 docker nodes and i dont see any error or warning either.

it is related how the content is delivered as `contentTypeNosniff = true` on our traefik is blocking the empty mime type. but why is it doing this in the first place?

**Comment by Aaron-Ritter** [comment]
what i found is if i manually replace the fusionauth-style.css content with for example the working font-awsome-4.7.0.min.css the console error is disappearing so it is about the content of the file.

**Comment by Aaron-Ritter** [comment]
> Ah. I think this might be related to this issue: #1831
> 
> Are you using a proxy that can modify the CSS headers?

It looks like we weren't on the 1.37 but 1.36 before the upgrade, 1.37 has the same problem. as mentioned in the other issue.

**Comment by robotdan** [comment]
Fixed via https://github.com/prime-framework/prime-mvc/commit/c4b94c2af4ed1c7bc336ad19eaba4776fb849863

**Comment by Aaron-Ritter** [comment]
great! thanks a lot, and sorry for the version confusion.

**Comment by Aaron-Ritter** [comment]
thanks! works!
