### ISSUE TITLE
The one-time refresh token can be used twice

### ISSUE THREAD

**Issue by avitsrimer** [FusionAuth/fusionauth-issues#1840]
### Description 
It has the same behaviour in docker from [fusionauth-containers](https://github.com/FusionAuth/fusionauth-containers)
If the browser sends the refresh request simultaneously, the browser would decide which refresh token needs to be saved and it will break the customer session once access_token expires. And it would leave unused refresh token in FA DB for a while.

### Affects versions
1.38.1, 1.36.7

### Steps to reproduce
1. Clone the fusionauth-containers
2. `cd docker/fusionauth` and Run `docker compose up`
3. Setup the FA user /  Login to FA admin
4. Create a tenant (Select `One time usage` for Refresh Token usage)
5. Create an API key (connect it to tenant)
6. Create an Application
6.1. connect it to the tenant
6.2. enable JWT
6.3. select `One time usage` for Refresh Token usage on the `JWT` tab
6.4. enable `Generate Refresh Tokens` on the `Security` tab
6.5. enable `Enable JWT refresh` on the `Security` tab
7. Copypaste APIkey, tenantId, applicationId to the script
8. Run the script (use any unique string for script `./test.sh 123` to repeat it, as that registers and additional user)
[script to run](https://gist.github.com/avitsrimer/636026ebd45b43a75caea28a01878205) ([script requers jq](https://stedolan.github.io/jq/download/))
9. See the refresh token was updated twice. The third request was rejected and it's hopefully good 🥲 

Note that the script uses `refresh & refresh & refresh` to run the commands at the same time: https://www.thegeekdiary.com/what-is-the-difference-between-ampersand-and-double-ampersand-while-executing-simultaneous-commands-on-linux/

### Expected behavior
Expecting to refresh only one time for the one-time refresh token, other should be denied as third request

### Screenshots
<img width="948" alt="Screenshot 2022-08-24 at 01 29 24" src="https://user-images.githubusercontent.com/3417941/186269819-681256d8-324a-431c-8996-36df72200762.png">

### Platform
- docker container

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1619

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

[script to run](https://gist.github.com/avitsrimer/636026ebd45b43a75caea28a01878205)
[script requers jq](https://stedolan.github.io/jq/download/)

**Comment by avitsrimer** [comment]
Hi there! Any thoughts here? It's rly easy to reproduce and wastes like 30 minutes, if you haven't containers.

**Comment by mooreds** [comment]
Thanks @avitsrimer . I was able to replicate, thanks so much for your detailed repro steps!

**Comment by avitsrimer** [comment]
hey! Is there any chance to get this done, its kind of a critical security issue at this moment 👀

**Comment by avitsrimer** [comment]
@mooreds hey any news?

**Comment by lyleschemmerling** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/284

**Comment by mooreds** [comment]
Thanks for your help @avitsrimer ! This is now resolved in 1.47.
