### ISSUE TITLE
Metadata errors for FusionAuth SP and IdP configuration

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1842]
### Description 
Metadata errors for FusionAuth SP and IdP configuration.  

We are not correctly advertising 

- the entityId.  We are missing the scheme, host for when we are SP and IdP under SAML
- the NameId policy set for the SP

### Affects versions
Latest (1.38.1)

### Steps to reproduce
- View SAML metadata and see that the entityId is missing `https://`
- Make changes to NameId format for a SAML SP and find those changes do not correspond to the metadata advertised.

### Expected behavior
Metadata to correctly reflect the configuration selected as well as the entityId per SAML spec.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
related: ticket 72760

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/138
