### ISSUE TITLE
The "Using FusionAuth on Docker" docs are now outdated

### ISSUE THREAD

**Issue by glen-84** [FusionAuth/fusionauth-issues#1844]
### Description

After the changes made [here](https://github.com/FusionAuth/fusionauth-containers/commit/ec4472ada007cc894099c64ce90cbeb6f2a05883), the docs are now outdated, and for example still link to `docker-compose.override.yml`, which is a 404.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Thank you, we'll get these updated.

**Comment by robotdan** [comment]
@mooreds is this only a doc change, or is there a reason to keep the override? Seems simpler to document just one file - but we can discuss if you want.

**Comment by mooreds** [comment]
I think it makes sense to update the docs to remove the override compose file, but these instructions are littered throughout the blog posts. I don't want to go back and update all of them. (Or forum posts or other places on the web).

So, I'd like to have the docker-compose.override.yml file continue to exist, but have it be empty (or with a comment, as in my PR). That way the curl command will succeed, but there's no support burden.

**Comment by mooreds** [comment]
Resolved the doc issue under https://github.com/FusionAuth/fusionauth-site/pull/1581
