### ISSUE TITLE
Document using Android phone as roaming Authenticator

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#1845]
An Android phone can be connected via Bluetooth and used as a WebAuthn authenticator, but there may be some extra setup required depending on the user's preferred browser and operating system.

Document the requirements and steps to enable an Android phone as a WebAuthn authenticator.
- Android 7+
- Connect via Bluetooth
- Chrome browser (maybe all Chromium browsers?)
- Allow browser to use Bluetooth in System Preferences > Security and Privacy (macOS)
- Sign in to same Google account on phone and primary machine or scan QR code to link

**Comment by robotdan** [comment]
This is really just part of https://github.com/FusionAuth/fusionauth-issues/issues/77 correct?

**Comment by spwitt** [comment]
@mooreds asked me to create an issue to document using and Android phone as a roaming authenticator. I'm fine with rolling it into #77 if you'd prefer.

**Comment by mooreds** [comment]
This feels different as it is a specific piece of documentation that may or may not be delivered with #77.

**Comment by robotdan** [comment]
I think based upon what @spwitt demo'd it is part of #77. We usually don't open up separate issues to document parts of a feature. 

I don't care really if we want to open more issues if you think that is helpful, but this will be handled and or delivered as part of #77 along with all other documentation for this feature.

**Comment by mooreds** [comment]
Okay, if we know it is going to get wrapped into that issue, fine with closing.
