### ISSUE TITLE
Support en_GB locale in Admin UI

### ISSUE THREAD

**Issue by adambowen** [FusionAuth/fusionauth-issues#1858]
### Problem
Correct date formats are important for quickly interpreting information on the admin UI, unconventional date formats are frustrating for end users and introduce significant potential for confusion. The default M/D/Y format [appears to only be widely used in the US](https://en.wikipedia.org/wiki/Date_format_by_country). Although both `en` and `en_US` locales are documented as supported, both appear to default to US date formatting. The `en_GB` locale, which would use a D/M/Y date format, is not currently supported.

### Solution
Add support for the `en_GB` locale so end users have the option of an English locale without a US date format. 

### Alternatives/workarounds
Other European locales can be selected to get the desired text format, but this can cause some other undesirable variations in formatting (in particular, the list of countries is translated and the decimal format is also affected). The Irish locale is the closest in terms of date and number formatting.

### Additional context
An alternative is to provide the ability for customers to edit or modify the locale information used by the admin UI (and [document it](https://fusionauth.io/docs/v1/tech/core-concepts/localization-and-internationalization)).

Within our own applications we prefer to use short month formatting, for example "1 Sep 2022", to remove any potential ambiguity for the end user.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks @adambowen we do try and use the correct time and date formats when possible. Not sure why we didn't ship with `en_GB`. 

```
# https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=en_GB

# Date format
date-format=d/M/yyyy
date-time-format=d/M/yyyy hh:mm a z
date-time-seconds-format=d/M/yyyy hh:mm:ss a z
```

Making this editable is a good idea.

**Comment by adambowen** [comment]
Wow, we really appreciate the quick turnaround for a minor annoyance.

Also, I'm pretty sure all our dev team will agree that ISO8601 is the only sensible date format.

**Comment by robotdan** [comment]
Welcome! 

Re: ISO 8601, does this mean you'd prefer to see the formatting for en_GB as yyyy/M/s or yyyy-M-s instead of d/M/yyyy?

**Comment by adambowen** [comment]
@robotdan d/M/yyyy is fine! I was referencing the meme in the FusionAuth newsletter :)
