### ISSUE TITLE
MySQL may not work on a fresh install for version 1.37.0 and beyond

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1862]
### Description
See related thread, but there may be some cases where a fresh install is not picking up a MySQL JDBC driver. 

- Windows is not currently going to work because we don't have a startup script. Currently you can use WSL v2, and then we'll be adding back a PowerShell option for a native startup. 
- All other installs for Linux or macOS should already work, so we should test the .deb, .rpm and .zip install paths on various systems and ensure there is not something that was missed. 

### Docker
When using the Docker image you'll need to either use PostgreSQL or build the MySQL JDBC connector into the image.

We've updated the Docker Hub description and the Docker install instructions to make this clearer.

- https://hub.docker.com/r/fusionauth/fusionauth-app
- https://fusionauth.io/docs/v1/tech/installation-guide/docker#limitations
- https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/fusionauth-app-mysql/Dockerfile

### WIndows
You'll need to use WSL v2 or wait for the update which will include a native Windows start script using PowerShell. 
- https://github.com/FusionAuth/fusionauth-issues/issues/1848

### Related
- https://fusionauth.io/community/forum/topic/2144/fusionauth-1-37-is-released/9?_=1662128026304&lang=en-US

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
@voidmain can we can ship your changes to maintenance mode here?

**Comment by sanderkooger** [comment]
> ## MySQL may not work on a fresh install for version 1.37.0 and beyond
> ### Description
> See related thread, but there may be some cases where a fresh install is not picking up a MySQL JDBC driver.
> 
> * Windows is not currently going to work because we don't have a startup script. Currently you can use WSL v2, and then we'll be adding back a PowerShell option for a native startup.
> * All other installs for Linux or macOS should already work, so we should test the .deb, .rpm and .zip install paths on various systems and ensure there is not something that was missed.
> 
> ### Docker
> When using the Docker image you'll need to either use PostgreSQL or build the MySQL JDBC connector into the image.
> 
> We've updated the Docker Hub description and the Docker install instructions to make this clearer.
> 
> * https://hub.docker.com/r/fusionauth/fusionauth-app
> * https://fusionauth.io/docs/v1/tech/installation-guide/docker#limitations
> * https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/fusionauth-app-mysql/Dockerfile
> 
> ### WIndows
> You'll need to use WSL v2 or wait for the update which will include a native Windows start script using PowerShell.
> 
> * [Enable Powershell / windows native installation method for backwards compatibility and long-term support #1848](https://github.com/FusionAuth/fusionauth-issues/issues/1848)
> 
> ### Related
> * https://fusionauth.io/community/forum/topic/2144/fusionauth-1-37-is-released/9?_=1662128026304&lang=en-US
> 
> ### Community guidelines
> All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

@robotdan we are running MySQL at the moment and would love to switch to Postgres? What is the best way to migrate everything ( settings users lamda functions) ?

**Comment by mooreds** [comment]
@sanderkooger We don't typically monitor closed issues. The best place to ask is probably the community forum or opening a support ticket (if you have a support contract).

https://fusionauth.io/community/forum/

or

https://account.fusionauth.io/account/support

Hope that helps and thanks for using FusionAuth!
