### ISSUE TITLE
Upgrading version of FA from 1.30.1 to 1.38.1

### ISSUE THREAD

**Issue by nick-kostov** [FusionAuth/fusionauth-issues#1863]
### Description 
In production mode we could not upgrade the FA application properly.
We had to manually run the scripts for the migration in order to fix the problem.

### Affects versions

1.30.1 to 1.38.1

### Steps to reproduce
Using FA in EKS we upgraded the version to 1.38.1 from 1.30.1.

### Expected behavior
We expected FA to run the migrations by itself.

### Platform
(Please complete the following information)
 - EKS 1.21
 - Database Postgresql 14.3

**Comment by robotdan** [comment]
This isn't very much to go on, do you have any additional details, errors, etc?

**Comment by jobannon** [comment]
Closing - can reopen with proper reproduction steps
