### ISSUE TITLE
Add a 'copy to clipboard' for settings

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1867]
### Problem

I'm often scrolling around the application 'view' display page and copying long values (like the client id or the login URL).

### Solution

I'd like a 'copy to clipboard' link on the details view page so I don't have to do much to copy these values.

### Alternatives/workarounds

Select and copy them.

### Additional context

Came up on a livestream.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/684
- https://github.com/FusionAuth/fusionauth-issues/issues/1301
- https://github.com/FusionAuth/fusionauth-issues/issues/1866

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
I think we have 3-4 issues open on this, can we consolidate? I think they are all duplicates.

- https://github.com/FusionAuth/fusionauth-issues/issues/684
- https://github.com/FusionAuth/fusionauth-issues/issues/1301
- https://github.com/FusionAuth/fusionauth-issues/issues/1867

**Comment by mooreds** [comment]
Closing this as a duplicate of #1301
