### ISSUE TITLE
Support `active:false` via `PUT` or `PATCH` on a SCIM user request to soft-delete a user

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1871]
### Description
`active` is part of the SCIM user schema, but the use of it is left up to the SP. The Okta SCIM client uses this attribute to de-activate a user account to keep them from logging in.

To better work with the Okta SCIM client, FusionAuth needs to either allow `active: false` to be processed by User update, or provide additional handling to process this attribute change as a soft delete `DELETE /api/user?hardDelete=false`. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1761
- https://github.com/FusionAuth/fusionauth-issues/issues/1791

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Could you catch `active: false` in the SCIM request lambda and make a call out to the `DELETE` endpoint using Lambda HTTP Connect?

**Comment by robotdan** [comment]
@mooreds that may work as an alternative work around.
