### ISSUE TITLE
Calls failing with 401 when creating a new application in a new tenant with a tenant scoped API key

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1875]
### Description 

When following the repro steps, the call to create a new application fails at random times with a 401 response code. It appears to happen within the first 5 or so times the application is created, but never on the first time.

### Affects versions

1.38.1
1.39.0

### Steps to reproduce

This was using the java client.

1. Make API call to create a tenant
2. Make API call to create an apikey for the tenant
3. Make API call to create an application using the tenant-scoped apikey

The final call is what fails.

### Expected behavior

Application should be created successfully.

### Platform

Happens in FusionAuth cloud (basic) and docker environments

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Came from a customer report.

Internal: https://inversoft.slack.com/archives/C03P8K9R69Z/p1663075709921109

No errors in the log.

Possible workaround: add a second or so of wait between each API operation.

**Comment by mooreds** [comment]
May be working as designed. Worth looking into.

**Comment by robotdan** [comment]
I think working as designed. API keys are cached. 

When an API key is created we attempt to reload the cache and request each node do the same. When using a multi-node environment it is important to ensure each node can communicate in order to minimize time to reload caches.

**Comment by mooreds** [comment]
Closing as "working as designed".

Workaround is to call the APIs with retries and backoff delays.
