### ISSUE TITLE
Java client used in IDEs missing `data` property on Application object

### ISSUE THREAD

**Issue by chimericdream** [FusionAuth/fusionauth-issues#1877]
### Description 
This is a low priority issue and only a minor annoyance, but the `Application` datatype in the client library appears to be missing the `data` property.

### Steps to reproduce
Install the FusionAuth client library in your IDE of choice (I used IntelliJ). Write up some code that uses the `application` variable in a template file.

### Expected behavior
The IDE is aware of the field and its type.

### Screenshots
![Screen Shot 2022-09-14 at 4 48 27 PM](https://user-images.githubusercontent.com/198075/190270099-4892200c-9e37-464b-ae19-a985205625f8.png)

### Platform
 - Device: MacBook
 - OS: macOS
 - Browser + version: n/a
 - Database: n/a

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
n/a

**Comment by robotdan** [comment]
That is a FreeMarker warning. For whatever reason the IDE cannot resolve the `data` property. This is a only a dev time warning and will not affect runtime. 

FreeMarker will find the `ftlVariable` markers in the `.ftl` file and attempt to resolve the properties. So for example, assuming you have this at the top of your file:

```
[#-- @ftlvariable name="application" type="io.fusionauth.domain.Application" --]
```

FreeMarker will try and resolve `io.fusionauth.domain.Application` in your class path, and if successful use it to help with IntelliSense etc when writing the `.ftl` file. 

If it is not working there is either an issue with the class path configured in the IDE, or a bug in the FreeMarker plugin.

**Comment by robotdan** [comment]
Closing since there isn't anything FusionAuth can do to change this behavior, please re-open if you have a different opinion.
