### ISSUE TITLE
Fusionauth documentation parsing bug

### ISSUE THREAD

**Issue by Jonny-Collins** [FusionAuth/fusionauth-issues#1878]
### Description 
It looks like the documentation is failing to parse values out for some fields. In particular the [SAML v2 IDP API docs](https://fusionauth.io/docs/v1/tech/apis/identity-providers/samlv2) have some parameters that aren't filled.

### Steps to reproduce
1. Go to the [SAML v2 IDP docs](https://fusionauth.io/docs/v1/tech/apis/identity-providers/samlv2). 
2. Scroll down to `identityProvider.linkingStrategy`
3. See the `OPTIONAL Defaults to {idp_linking_strategy}`

### Expected behavior
Should be populated with the corresponding value.

### Screenshots
![image](https://user-images.githubusercontent.com/69128820/190282834-08dc7f79-5e38-4305-b1a5-9ea781c1e356.png)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
oof, thanks @Jonny-Collins ! I'll take a look to see what isn't being set.

**Comment by mooreds** [comment]
closed under https://github.com/FusionAuth/fusionauth-site/pull/1605
