### ISSUE TITLE
[Bug + Feature request] Password change using loginId returns 404

### ISSUE THREAD

**Issue by timyourivh** [FusionAuth/fusionauth-issues#1880]
### Description 
Whenever I make a request to. 
```http
// with API key ofcourse
POST /api/user/change-password 
```
with body:
```json
"applicationId": "12345678-12ab-cd34-e56f-78gh9i012k34",
"loginId": "username or email",
"currentPassword": "password",
"password": "new password"
```
It keeps returning:

```php
^ FusionAuth\ClientResponse {#1503 ▼
  +errorResponse: null
  +exception: null
  +method: "POST"
  +request: array:4 [▼
    "applicationId" => "12345678-12ab-cd34-e56f-78gh9i012k34"
    "loginId" => "xxx"
    "currentPassword" => "xxx"
    "password" => "xxx"
  ]
  +successResponse: null
  +status: 404
}
```

I have tried it with and without:
- tenant id header -> 404
- applicationId -> 404
- currentPassword -> 404
- [without] loginId -> 400
  - Returns error response: "Your request is invalid. You must call the API with a valid JSON body that includes a changePasswordId, with a valid JWT in the Authorization header or with an API key."
- [without] password -> 400
  - Returns error response: "You must specify the [password] property"

### Affects versions
It occurred to me on version `1.36.4` and upgraded to `1.38` but the issue is still present.

### Steps to reproduce
1. Make request to `/api/user/change-password` using [this](https://fusionauth.io/docs/v1/tech/apis/users#request-body-13) requestbody and valid credentials.
2. Check response.
3. Notice the password is not changed either.

### Expected behavior
I expected a successful response and the password to be changed.

### Platform
 - Device: Desktop
 - OS: Windows 10 Pro
 - Mozilla Firefox Developer Edition 105.0 Beta 9 (20220908185813)
 - Database MySQL 8.0.23

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

## Feature request (or alternative)

I would like to be able to change the users' password by approaching the user by it's uuid. It would be the same as the `POST /api/user/change-password` request. 
It would require the exact same body as the [request body mentioned before](https://fusionauth.io/docs/v1/tech/apis/users#request-body-13) but it will be using a `userId` instead of `loginId`. That way I can be a 100% sure the correct password will be changed.

Let me know what you think!

**Comment by mooreds** [comment]
@timyourivh 

Re: your feature request, you should be able to use PATCH to update the user's password with an API key and the UUID:

```
userid=....
apikey=...

curl -X PATCH -d '{"user": {"password": "newnewpass"}}' https://local.fusionauth.io/api/user/$userid  -H 'Content-type: application/json' -H 'Authorization: '$apikey
```

And the change password call works for me too:

```
email=....
apikey=...

curl -vv -X POST -d '{"loginId": "'$email'", "password": "newnewpass2"}' https://local.fusionauth.io/api/user/change-password  -H 'Content-type: application/json' -H 'Authorization: '$apikey
```

Does using only the loginId and password work for you?

**Comment by timyourivh** [comment]
#### Props

First of all, thanks for the quick response!

---

#### Feature request

> Re: your feature request, you should be able to use PATCH to update the user's password with an API key and the UUID

I would like to have the user verify it's current password. 

For this I thought: It could be useful create an endpoint for confirming passwords without treating it as a login. I think this could be implemented in two ways:
1. Repurpose the `/login` endpoint by adding a param to tell FusionAuth to not treat it as a login but as a password confirmation.
2. A new endpoint on the `/api/user` as `/confirm-password`. Requiring a `loginId` or `userId` in combination with a `password`

It could be useful since you can protect any action (FA related or not) using such an endpoint. 

Let me know what you think!

---

#### 404 on change password with correct credentials

As for the `/api/user/change-password` request: manually sending out (using postman or hoppstoch) the request __DOES__ work so this issue is __not__ FusionAuth server related. Probably has something to do with the way I'm making the request from my application to the FA server and thus will be debugged within the context of my app.

__Bug status:__ not a bug, resolved.

**Comment by timyourivh** [comment]
#### Update on 404 on change password with correct credentials for people who may make the same mistake:

When not using a tenantId you are not able to change the users password by identity. So make sure you add the tenant id header to the request. This was the mistake I made.

**Comment by mooreds** [comment]
Hiya @timyourivh ,

Thanks for your response. Feel free to file a separate feature request about using a uuid as part of the change password flow. We'll see what the community thinks (by their upvotes).

> Update on 404 on change password with correct credentials for people who may make the same mistake

Thanks for that. This is due to the fact that you can have the same loginId across different tenants. I'll look at updating the doc to make that clearer.

**Comment by mooreds** [comment]
Ah, it does state that the tenantId is required:

>  When only a single tenant is configured the tenant Id can be assumed and this additional header is optional. Once more than one tenant has been configured in FusionAuth the tenant Id is required for this request because the input parameters by themselves do not indicate which tenant the request is intended.
