### ISSUE TITLE
Admin UI - Linked Accounts - Issue with certain characters in identityProviderUserIds

### ISSUE THREAD

**Issue by epbensimpson** [FusionAuth/fusionauth-issues#1882]
### Description 
:wave: me again, with something that's undisputedly a bug this time. Seems like the admin UI is not URL Encoding certain characters when calling the Link API with query strings. This either results in the UI displaying the link in the list but not being able to view/delete it, or viewing/deleting the wrong link in a certain scenario.

The .NET client seems to have similar behaviour (which is how I discovered this), I'll raise an issue (and maybe a PR) in the client repo once I investigate that a little more.

### Affects versions
1.36.8
1.39.0

### Steps to reproduce
1. Create a link with a `identityProviderUserId` of `my+id`
2. Create a link with a `identityProviderUserId` of `my&id`
3. If you try to view one of these it will tell you it cannot be found, and if you try to delete it will say it's already deleted
4. Now, create a link with a `identityProviderUserId` of `my id`
5. Now if you view or delete the one with a `+` in the identifier, it will display the one with a space instead. Ditto for deleting - the one with the space is deleted instead.

```
{
    "identityProviderLinks": [
        {
            "displayName": "my id",
            "identityProviderId": "82339786-3dff-42a6-aac6-1f1ceecb6c46",
            "identityProviderUserId": "my id",
            "insertInstant": 1663275788503,
            "lastLoginInstant": 1663275788503,
            "tenantId": "afa6c9f7-3687-5647-a9f0-e9901fcfe018",
            "userId": "d24f6b53-01a6-4184-b76b-42499c947ec8"
        },
        {
            "displayName": "my&id",
            "identityProviderId": "82339786-3dff-42a6-aac6-1f1ceecb6c46",
            "identityProviderUserId": "my&id",
            "insertInstant": 1663275798238,
            "lastLoginInstant": 1663275798238,
            "tenantId": "afa6c9f7-3687-5647-a9f0-e9901fcfe018",
            "userId": "d24f6b53-01a6-4184-b76b-42499c947ec8"
        },
        {
            "displayName": "my+id",
            "identityProviderId": "82339786-3dff-42a6-aac6-1f1ceecb6c46",
            "identityProviderUserId": "my+id",
            "insertInstant": 1663275807862,
            "lastLoginInstant": 1663275807862,
            "tenantId": "afa6c9f7-3687-5647-a9f0-e9901fcfe018",
            "userId": "d24f6b53-01a6-4184-b76b-42499c947ec8"
        }
    ]
}
```

### Expected behavior
UI should URL Encode the `identityProviderUserId` correctly.

### Platform
 - Device: Desktop
 - OS: Linux (pop_os)
 - Browser + version: Chrome 105

**Comment by robotdan** [comment]
Thanks @epbensimpson we'll see if we can recreate the issue.

**Comment by robotdan** [comment]
Thanks @epbensimpson good catch. Fixed.
