### ISSUE TITLE
OpenID Connect fails when service provider does not support HTTP Basic Authorization

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#189]
### Description
FusionAuth sends the client secret in the request body and in the HTTP Basic Authorization request header. 

An IdP must support the HTTP Basic Authorization header for a secure request to the Token endpoint according to the OAuth2 specification. 

If the IdP does not support this, FusionAuth fails to integrate with this provider. 

FusionAuth could optionally expose a toggle of some sort in the UI / API to allow the configuration to select how they wish to authenticate with the Token endpoint. This would make FusionAuth more flexible in support many potentially non-compliant IdP systems. 

See comment https://github.com/FusionAuth/fusionauth-issues/issues/181#issuecomment-503941757 and comment https://github.com/FusionAuth/fusionauth-issues/issues/181#issuecomment-504031689 in issue https://github.com/FusionAuth/fusionauth-issues/issues/181.

See the OAuth specification defined in section `2.3.1 Client Password` (https://tools.ietf.org/html/rfc6749#section-2.3.1).

> The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client password.
> ...
> Alternatively, the authorization server MAY support including the client credentials in the request-body

For compatibility with many OpenID servers, when a Client Secret is configured in your IdP configuration, it will be sent in both the `Authorization header` and the request body.

**Comment by prabhakarreddy1234** [comment]
@robotdan  as per our external OpenIDConnect provider, code needs to be sent something like this :

```
curl -X POST -H "Content-Type: application/json" -d '{
  "grant_type": "authorization_code",
  "client_id": "YOUR_CLIENT_ID",
  "client_secret": "YOUR_CLIENT_SECRET",
  "redirect_uri": "YOUR_REDIRECT_URI",
  "code": "YOUR_AUTH_CODE (JWT)"
}' "https://api.wonde.com/oauth/token"
```

**Comment by robotdan** [comment]
It is possible this is a bug in their documentation, the OAuth2 spec requires the token request be made using a `Content-Type` value of `application/x-www-form-urlencoded`.
https://docs.wonde.com/docs/api/sso#oath2-request-access-token


> 4.1.3.  Access Token Request
> The client makes a request to the token endpoint by sending the following parameters using the "application/x-www-form-urlencoded" format per Appendix B with a character encoding of UTF-8 in the HTTP request entity-body:

https://tools.ietf.org/html/rfc6749#section-4.1.3


There is no plan to break spec and change how we encode the request body sent to the Token endpoint. Assuming the Wonde Token endpoint will accept a properly encoded request.

**Comment by prabhakarreddy1234** [comment]
I think `-d` in the curl statement sets the `content-type : application/x-www-form-urlencoded`. So Token endpoint should be supporting   `application/x-www-form-urlencoded` request.

usually to post json data using curl we set `content-type:application/json` and followed by `-d` to encode it.

**Comment by robotdan** [comment]
I think this has been resolved via https://github.com/FusionAuth/fusionauth-issues/issues/445. The OpenID Connect IdP configuration now allows to select between `client_secret_basic` or `client_secret_basic`. 

Closing as resolved.
