### ISSUE TITLE
Getting only 404 error code if provided loginId or currentPassword wrong

### ISSUE THREAD

**Issue by sujkattimani** [FusionAuth/fusionauth-issues#1897]
### Description
When we provide wrong loginId or wrong currentPassword we are getting only 404 status code in response. Can we get some specific error message.
For example -
1. If wrong loginId provided - “Provided loginId is not valid”.
2. If wrong currentPassword provided - “Provided currentPassword is not valid”

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Documentation
- [x] Audit thre Change Password API

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/166
