### ISSUE TITLE
Documentation error on passwordless api

### ISSUE THREAD

**Issue by ericher4worximity** [FusionAuth/fusionauth-issues#190]
### Description
According to the documentation - see https://fusionauth.io/docs/v1/tech/apis/passwordless#complete-a-passwordless-login - the api to complete a passwordless login is a `GET`. This is wrong, it's a `POST`. There client librairies use POST to perform the call and a GERT returns a http 404.

**Comment by robotdan** [comment]
Thanks @ericher4worximity great catch.
