### ISSUE TITLE
JWT Populate lambda not executed for External JWT logins

### ISSUE THREAD

**Issue by huysentruitw** [FusionAuth/fusionauth-issues#1902]
### Description 

We have a `JWT populate`-lambda configured, which adds a custom claim to the JWT generated by FusionAuth. This works fine for normal login scenario's. However, we now have the additional requirement to use an "External JWT" provider for a certain tenant and use the `/api/identity-provider/login` endpoint to exchange the external JWT to a FusionAuth generated JWT. This also works fine, except that it seems like the `JWT populate`-lambda hasn't run on the token returned by the `/api/identity-provider/login` endpoint.

### Affects versions
1.36.4

### Steps to reproduce
1. Create a JWT populate lambda that adds a custom claim
2. Configure an external JWT provider
3. Post a valid external JWT to https://login.development-enviso.io/api/identity-provider/login
4. Check whether the returned JWT contains the custom claim defined in step 1

### Expected behavior
The JWT-populate lambda should also run for the JWT returned by the `/api/identity-provider/login` endpoint for External JWT providers.

### Platform
 - Device: Desktop
 - OS: Windows
 - Edge 105.0.1343.50

**Comment by mooreds** [comment]
@huysentruitw did this get fixed in a later version of FusionAuth, was the documentation incorrect, or was there something else going on?
