### ISSUE TITLE
Connectors restrict users to one SSO session

### ISSUE THREAD

**Issue by yuezhou1998** [FusionAuth/fusionauth-issues#1907]
**Description**
Users who sign in through an LDAP connector are restricted to having only one SSO session and refresh token active at a time. The original issue is from: https://fusionauth.io/community/forum/topic/2176/does-fusionauth-track-multiple-sso-sessions-for-ldap-users

**Affects versions**
1.28, 1.40.2

**Steps to reproduce**
1. Sign into a new browser session with an LDAP user
2. Verify using the API that there exists a single refresh token for the LDAP user
3. Verify using the FusionAuth Admin UI that there exists a single session for the LDAP user, under Users > the LDAP user from step 1) > Manage > Sessions.
4. Everything up to this point is correct. There is only one session recorded inside of FusionAuth and one refresh token in the API. 
5. Sign into a different browser with the LDAP user from step 1)
6. Verify using the API that there exists a single refresh token for the LDAP user, this is now incorrect as there should be two refresh tokens, one from step 1), another from step 5).
7. Verify using the FusionAuth Admin UI that there exists a single session for the LDAP user, under Users > the LDAP user from step 1) > Manage > Sessions. This is also incorrect as there should be two sessions for the user, one from step 1), another from step 5)
8. Verify that the SSO session from the browser on step 1) is now using a fusionauth.sso cookie that no longer correlates to an active refresh token. If the user attempts to access another application's endpoint on this browser, they will be prompted to sign in. Note that this application must not have been accessed yet until this point, since we are trying to trigger another OAuth flow.

**Expected behavior**
LDAP users should be able to maintain more than one SSO session. The session from step 1) above should still be valid.

**Workaround**
Set `tenant.jwtConfiguration.refreshTokenRevocationPolicy.onPasswordChanged` to `false`. To change via the UI, this is under the JWT tab on the Tenant, in the `Refresh Token settings` and the `Refresh Token revocation ` field. Make sure `On password change` is disabled.

### Internal
- When password hash has not changed, don't treat a change event regardless of config for "revoke refresh tokens on password change"

**Platform**
Device: Desktop
OS: Linux
Browser + version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Database: PostgresSQL 14, using spilo-14:2.1-p3

**Additional Context**
The LDAP Reconcile we are using is not setting any values related to the user's sessions.

This behavior also occurs with generic connectors where the user is not migrated.

Please let me know if there's anything else I could attach or clarify on, thanks

**Comment by jobannon** [comment]
related https://fusionauth.io/community/forum/topic/2176/does-fusionauth-track-multiple-sso-sessions-for-ldap-users/5

**Comment by mooreds** [comment]
This also apparently applies to generic connectors, as I saw the same behavior today in a test.

**Comment by robotdan** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/150
