### ISSUE TITLE
Google One Tap Sign-In

### ISSUE THREAD

**Issue by esafev** [FusionAuth/fusionauth-issues#1911]
### Problem
Hey, guys! Firstly, I want to say that we love using Fusion, but we want to ask about adding a new feature.

This feature is Google One Tap Sign-In/Sign-Up. We really want this feature because it is a simpler way to authorize users that have a Google Account, and it may also increase our retention and conversion.

### Solution
Update the Google SDK to the new version and implement functionalities for Google One Tap.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Related issues

* https://github.com/FusionAuth/fusionauth-issues/issues/1894
* https://github.com/FusionAuth/fusionauth-issues/issues/1939

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Documentation
- [ ] https://github.com/FusionAuth/fusionauth-site/issues/1984

**Comment by LucasPiffer** [comment]
Hi! I would like to know if you are needing help on this issue or if it's already under development.

**Comment by mooreds** [comment]
@LucasPiffer Thanks for your interest!

This is not currently under development, though we are planning to deliver https://github.com/FusionAuth/fusionauth-issues/issues/1894 in the next release. 

Here's our general roadmap guidance: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap/

Thanks!

**Comment by spwitt** [comment]
**UPDATE**

FusionAuth offers two login methods for the Google IdP: redirect and popup. These can be configured in _Settings > Identity Providers > Edit Google_.

If your Google IdP is configured to _Use redirect for login_, then **you are not impacted by the upcoming library deprecation**.

If your Google IdP is configured to _Use popup for login_, then prior to the March 31, 2023 deadline you must either:

1. Change your login method to _Use redirect for login_
2. Update to a new version of FusionAuth with the Google IdP client-side fixes (in progress)

![image](https://user-images.githubusercontent.com/3409780/220948851-bcb0513b-41db-4302-9bf7-ca7d0c533222.png)

_More info_

I used Google's `G_AUTH2_MIGRATION` cookie with a value of `informational` ([link](https://developers.google.com/identity/gsi/web/guides/migration#identifying_affected_code_and_testing)) to log console warnings when it detects that the client invokes deprecated JavaScript APIs. Based on this testing I found that:

* When the login method is _Use redirect for login_, nothing is logged to the console
* When the login method is _Use popup for login_, there is a message logged to the console

```
Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
```

I tested and observed the same behavior across the following browsers on macOS:
* Chrome
* Firefox
* Safari
* Brave
* Edge

**Comment by spwitt** [comment]
I wanted to make sure that everyone following these Google IdP issues knew the status of their API deprecation and how that will affect FusionAuth. Going forward, updates on the migration to Google Identity Services and Google's new API will be tracked in
- https://github.com/FusionAuth/fusionauth-issues/issues/1939

This issue will be used to track progress and provide updates on adding support for Google One Tap.

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/219
