### ISSUE TITLE
Exception Thrown when retrieving public key by applicationId

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#1918]
### Description 

When retrieveing the JWT public keys via the api endpoint `/api/jwt/public-key` the response is empty response, which I expect.

{"publicKeys":{}}

When an application id is provided the endpoint `/api/jwt/public-key?applicationId={applicationId}` the following exception is returned 

`ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.primeframework.mvc.PrimeException: The @JSONResponse field [response] in the action [class io.fusionauth.app.action.api.jwt.PublicKeyAction] is null. It cannot be null!`

### Affects versions
v1.40.2

### Expected behavior
I expect the Exception to be handled an an empty object to be returned by the API endpoint for publicKeys

### Platform
 - OS: Debian
 - FusionAuth v1.40.2

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/147
