### ISSUE TITLE
Gmail SMTP does not work

### ISSUE THREAD

**Issue by dmitri777** [FusionAuth/fusionauth-issues#1922]
### Description 
Cannot use Gmail (smtp.gmail.com), test emails fail with generic non-informative message, event if Debug is enabled

### Affects versions
 1.40.2

### Steps to reproduce
1. Go to Tenant Settings, Email Section
2. Enter any valid Gmail smtp configuration that works fine with other  SMTP clients like Thunderbird
3. Try to send test email
4. See error "Unable to send email via JavaMail / Prime Messaging Exception"

### Expected behavior
SMTP configuration must work for such a major service as Google

### Platform
(Please complete the following information)
 - Device: Ubuntu 12.12 server with FusionAuth installation at backend / Desktop at client side
 - OS: Ubuntu 12.12 server at backend / Windows 11 Home at client side
 - Chrome Version 106.0.5249.103 (Official Build) (64-bit) at client side
 -  psql (PostgreSQL) 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1) at server side

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Some consumer oriented SMTP servers have a lot of restrictions that may be out of our control. 

Can you replicate the results with something like SWAKS to ensure it is something specific to FusionAuth? 
https://jetmore.org/john/code/swaks/

**Comment by jobannon** [comment]
Likely related to this fix...
 https://fusionauth.io/community/forum/topic/1112/smtp-server-gmail-setup-error/3?_=1666277007403

**Comment by dmitri777** [comment]
@mooreds , @jobannon 

Issue reporter here. Found a way to solve it. 

You really need to use 16-char app passwords with Google SMTP, as it is suggested here https://support.google.com/accounts/answer/185833, thanks @jobannon 

It works fine then. Maybe it makes sense to add a simple checking to FusionAuth web page, like, if STMP server is "smtp.gmail.com", show alert("Hey, normal passwords does not work with Google, use app password")

**Comment by mooreds** [comment]
Thank you @dmitri777 for sharing!

**Comment by mooreds** [comment]
This is probably too implementation specific for our docs or product, but I added a forum post: https://fusionauth.io/community/forum/topic/2233/having-trouble-using-gmail-smtp-for-email-sending
