### ISSUE TITLE
Support for IdP initiated to an SP when FusionAuth is the IdP

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1927]
### Problem
FusionAuth does not currently support IdP initiated login when we are the IdP, we only offer it as an option when we are the SP. 

### Solution
Add support to initiate the login when we are the SAML v2 IdP

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1785
 
### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
This page should be updated as well as any other API documentation: https://fusionauth.io/docs/v1/tech/core-concepts/integration-points#saml-integration-options
