### ISSUE TITLE
Oauth2 login page

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#193]
Hello all. I installed FusionAuth for Windows locally on my pc and trying to connect my application (WebApi) to the FusionAuth. I created the test application and register user for it. However I didnt find any solution how to create (open existing) oauth2 login page. Any ideas?
I find the tool for customization this page
![chrome_vM93s0CwL8](https://user-images.githubusercontent.com/7276744/60034354-270d3480-96b3-11e9-8c0c-34c180eb871f.png)

**Comment by forenheith** [comment]
I`ve just tryied URL http://localhost:9011/oauth2/authorize and faced next error
![chrome_xjF5qqthDP](https://user-images.githubusercontent.com/7276744/60034460-6176d180-96b3-11e9-83da-c40c76404b8e.png)

**Comment by tyduptyler13** [comment]
Hi,

In order to call the authorize url, you need to specify `client_id`, `redirect_uri`, and `response_type`.

See https://fusionauth.io/docs/v1/tech/oauth/endpoints#authorize

**Comment by forenheith** [comment]
Thanks, I`ve checked this url: 
http://localhost:9011/oauth2/authorize?client_id=1e1a52bc-4d10-4413-81bd-c9496eee70d6&redirect_uri=http://fusionauth.io&response_type=code

Here is response
`{
  "error" : "invalid_request",
  "error_description" : "Invalid redirection uri http://fusionauth.io",
  "error_reason" : "invalid_redirect_uri"
}`

**Comment by robotdan** [comment]
Hi @forenheith can you confirm you have configured your redirect URI in FusionAuth? 

https://fusionauth.io/docs/v1/tech/oauth/overview

The Redirect URI will be the URL of your application that will handle the response from the Authorization request. If the value you send in the `redirect_uri` parameter is not registered with FusionAuth you will receive the `invalid_redirect_uri` error as you're seeing.

**Comment by forenheith** [comment]
> Hi @forenheith can you confirm you have configured your redirect URI in FusionAuth?
> 
> https://fusionauth.io/docs/v1/tech/oauth/overview
> 
> The Redirect URI will be the URL of your application that will handle the response from the Authorization request. If the value you send in the `redirect_uri` parameter is not registered with FusionAuth you will receive the `invalid_redirect_uri` error as you're seeing.

Yes, redirect_url is configured and works, however without authorization request

**Comment by robotdan** [comment]
Thanks @forenheith , I'm a little confused. 

The URL in that dialog screenshot looks correct, that is for display only and is used to help you build your Authorize request URI. When you make the Authorize request to FusionAuth, are you sending a `redirect_uri` value of `http://tut.by` URL encoded (as it is shown in the OAuth IdP login URL in the dialog?

The error you provided earlier looks like you're sending a different URL, this error shows `http://fusionauth.io`. 

```
{
  "error": "invalid_request",
  "error_description": "Invalid redirection uri http://fusionauth.io",
  "error_reason": "invalid_redirect_uri"
}
```

**Comment by forenheith** [comment]
> Thanks @forenheith , I'm a little confused.
> 
> The URL in that dialog screenshot looks correct, that is for display only and is used to help you build your Authorize request URI. When you make the Authorize request to FusionAuth, are you sending a `redirect_uri` value of `http://tut.by` URL encoded (as it is shown in the OAuth IdP login URL in the dialog?
> 
> The error you provided earlier looks like you're sending a different URL, this error shows `http://fusionauth.io`.
> 
> ```
> {
>   "error": "invalid_request",
>   "error_description": "Invalid redirection uri http://fusionauth.io",
>   "error_reason": "invalid_redirect_uri"
> }
> ```

Correct, I used the redirect_url:  fusionaut.io only for test case when url is not in redirect urls list

**Comment by forenheith** [comment]
As far as I understand OAuth IdP login URL field contains correct url to access to the authorization page. Am I right?

**Comment by robotdan** [comment]
Yes, that is correct. 

The error you showed earlier indicates you are not sending the correct `redirect_uri` as shown in the example OAuth IdP login URL.

**Comment by forenheith** [comment]
Sorry, I didn’t quite understand what do you mean, using the current settings and following url:
`http://localhost:9011/oauth2/authorize?client_id=91edba61-e159-4177-a15c-b3e6ba58162a&response_type=code&redirect_uri=http%3A%2F%2Ftut.by`
 I don’t get to the login page, instead I’ll immediately go to the redirect url

**Comment by robotdan** [comment]
> I don’t get to the login page, instead I’ll immediately go to the redirect url. AFAIU it is not expected behaviour.

This means that you are already logged in, this is the intended behavior for single sign on. Once you are logged out of FusionAuth, you will be presented with the login page before being redirected. 

For example, if you're logging into your application at `http://tut.by` with the same browser as the one you're accessing FusionAuth UI with - then FusionAuth will recognize you're already logged in and log you into your application without prompting you for credentials.  To test this, log out of FusionAuth first, and then attempt the redirect from your application.

**Comment by forenheith** [comment]
Ok, got it. What about users that has no registration to app specified? Why they have access to redirect url? Is it ok?

**Comment by robotdan** [comment]
>  What about users who do not have registration in the specified application? Why do they have access to redirect URLs? This is normal?

Yes, this is expected. The Authorization grant provides authentication. The user is authenticated if their credentials are verified or they already have an authenticated session in FusionAuth (SSO). 

Authorization is a separate step, once you complete the Authorization Grant and receive an access token and optionally and Id token in the form of a JSON Web Token, that token will contain information about the User's authorization to the requested resource. 

If the user is registered, the JWT will contain an `applicationId` and `roles`, if they are not registered these claims will not exist in the returned token. 

https://fusionauth.io/docs/v1/tech/oauth/tokens

On the redirect URL we provide a hint to your application to indicate the User's state, you will see `&userState=Authenticated` or `&userState=AuthenticatedNotRegistered` returned on the redirect. 

In your application you will need to identify if the user that has authenticated is authorized to take the requested action based upon their registration state and assigned roles.

**Comment by forenheith** [comment]
Many thanks @robotdan
