### ISSUE TITLE
Freemarker exception on tenant details page

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1932]
### Description 

Freemarker exception on tenant details page.

![webauthn-error](https://user-images.githubusercontent.com/91825/197285040-6ec190b2-0da9-4618-9465-21f9b835acd8.png)

### Affects versions

EAP 20221020

### Steps to reproduce
1. go to tenants
2. click the view button
3. scroll all the way to the bottom

### Expected behavior

No freemarker exception.

### Screenshots

See above.

### Platform

Android phone, chrome.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
This was an issue with configuration naming standards for External Identifier TTL.

Resolved in EAP branch.
