### ISSUE TITLE
Lambda populate JWT exceptions do not stop processing flow

### ISSUE THREAD

**Issue by LasseJacobs** [FusionAuth/fusionauth-issues#1933]
### Description
According to https://fusionauth.io/docs/v1/tech/lambdas/#exceptions I would expect an exception thrown in a JWT populate lambda to stop the processing of the authentication flow and report an error to the user. 

Yet this does not actually happen. Instead, the an error is logged in the 'Event Log', and a JWT token is still returned to the user (albeit potentially not enriched by the lambda depending on where the exception gets thrown.) The docs clearly state otherwise:
> _When an exception is thrown, further processing ceases. Whatever operation the lambda was part of (login, Identity Provider user reconciliation, etc) will not complete._

I looked through some of the issues and found this [issue](https://github.com/FusionAuth/fusionauth-issues/issues/1707) that seems to confirm that this is the case for reconcile lambdas but indeed not for JWT populate Lambdas. 

Is this a bug or am I misinterpreting the documentation? 

### Example
Take the following example lambda:
```
function populate(jwt, user, registration) {
    throw "Stop!";
}
```
I have it configured to run for my application in Fusion auth. I would expect every login attempt to fail because this lambda will always throw an error.
Instead, the login passes (if the creds are correct of course), and an error is logged in the system event log:
```
[ERROR] Lambda invocation exception. Id: 66e690eb-a4c3-4f5d-9f69-5b4d45de8e0a Name: enrich_id Stop! in <eval> at line number 12 at column number 2
```

**Comment by mooreds** [comment]
@LasseJacobs I believe the documentation is incorrect. We'll get it updated. Sorry for the confusion.

**Comment by mooreds** [comment]
Thanks for closing this, @LasseJacobs . You might be interested in this issue too: https://github.com/FusionAuth/fusionauth-issues/issues/1282
