### ISSUE TITLE
Zero byte single logout file downloaded every time I logout with Firefox.

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1934]
### Description 

Every time I use the logout link for an application managed by FusionAuth in FireFoex

### Affects versions

1.40.2

### Steps to reproduce

* stand up fusionauth
* stand up and configure an example app (I used https://github.com/fusionauth/fusionauth-example-node )
* log in
* log out

### Expected behavior

No file is downloaded.

### Platform

This happens on Firefox on the mac. Tested on Chrome and it doesn't occur, haven't tested it elsewhere.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Logging out of the FusionAdmin prod Admin ui doesn't trigger this, but logging out of a local FusionAuth instance does.

The file is called `single-logout`.

**Comment by robotdan** [comment]
In Firefox, the `Content-Type` is showing `octet-stream`, this is why it thinks it is supposed to download this file. 

However, we are not setting this response header, Firefox is just making this assumption for some reason. I confirmed our response does not contain a `Content-Type` or `Content-Length` header. 

The only possible issue is that we are setting the `Content-Encoding` to `gzip` even when we are not sending back a response body. Perhaps Firefox is seeing that value and assuming we are going to send back a body. 

 When I recreated I was being proxied by an ALB which is upgrading my request to HTTP2 which may also be a factor in how Firefox decides to interpret the response without a `Content-Length` or `Content-Type` header. 

However, the `Content-Encoding` only applies to the `Content-Type` - so it still seems like Firefox is the issue.  We can investigate further.

@voidmain Perhaps we should not be setting the `Content-Encoding` response header when we do not have a body? I don't know that it is incorrect to do so, but it may be confusing Firefox. 

Related
- https://httpwg.org/specs/rfc9110.html#field.content-encoding

**Comment by mooreds** [comment]
i saw this locally as well, when there was no ALB in the picture. Maybe we need to explicitly set the content type header and tomcat was doing that for us? I don't recall this behavior a few months ago.

**Comment by voidmain** [comment]
Is this still an issue with `java-http`?

**Comment by mooreds** [comment]
Great point. I just tried it on the 1.41 EAP release and I didn't see the issue.

Maybe we should keep this open until the 1.41 GA release, but if it doesn't re-appear, close it.

**Comment by robotdan** [comment]
In confirmed in the next version of FusionAuth we are always setting a `Content-Length` of `0` when we do not have a body.  So this should be resolved in the upcoming release.
