### ISSUE TITLE
Ability to associate custom domains with tenants in FusionAuth cloud

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1938]
### Problem

When I'm self-hosting FusionAuth, I can use a proxy to map domains to tenants, as [outlined here](https://fusionauth.io/docs/v1/tech/admin-guide/proxy-setup#proxies-and-tenants). I'd like the same ability in FusionAuth Cloud

### Solution

Let me map custom urls to tenants. Maybe for v1 I copy/paste in a tenantId when I add a custom domain, and that tenantId is appended across every request to that name?

### Alternatives/workarounds

* Self-host
* use cloudflare or some other proxy in front of FusionAuth cloud, but then I have to manage it.

### Additional context

Came up on a customer call.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/994?

**Comment by robotdan** [comment]
Ok, so this request is to build something specific to FusionAuth Cloud outside of the product? 

If so, I doubt we will add this feature - if we are going to build something like this, it would make more sense to do it under #994 and make it part of the product.

**Comment by mooreds** [comment]
Yup, this is a fusionauth-cloud request. We can close it out if it won't get built.

**Comment by robotdan** [comment]
Sounds good. If you think this is something that makes sense to build outside of the product, you can open an issue in the `fusionauth-cloud` repo as well and could review in context of the cloud stack.

**Comment by mooreds** [comment]
Closing this issue, as I opened an issue in fusionauth-cloud.
