### ISSUE TITLE
Login error when logging out and logging back in with SAML IdP-initiated

### ISSUE THREAD

**Issue by jon-at-advarra** [FusionAuth/fusionauth-issues#1941]
### Description
Error is presented on login screen when logging in after logging out with SAML IdP-initiated user.

Appears to be a session state issue because clearing the FA cookies fixes the issue.

### Affects versions
1.40.2

### Steps to reproduce
1. Authenticate to a FusionAuth application via SAML IdP-initated
2. Log out of the app
3. Re-log to the app via SAML IdP-initated and an "An unexpected error occurred while completing your login attempt. Please attempt the request again. " error is presented

### Expected behavior
User can re-login without error for SAML IdP-initiated user.

### Screenshots
<img width="1088" alt="Screen Shot 2022-10-27 at 3 53 35 PM" src="https://user-images.githubusercontent.com/116736293/198396038-08434e5c-20cc-4613-a3c2-bbf646e2061c.png">

### Platform
(Please complete the following information)
 - Device: Mac
 - OS: MacOS
 - Browser + version: Firefox 106
 - Database: PostgresSQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
The following error shows in the log
```
2022-10-27 08:53:31.883 PM ERROR io.fusionauth.app.action.BaseOAuthCallbackAction - Unable to call FusionAuth Token endpoint using code [QLMIiwyFHl-Q1nJK71joWoDPIDUI_RdydP4hebldkTA]. HTTP Status Code [400]. Error message: 
[{
  "error" : "invalid_request",
  "error_description" : "Invalid Authorization Code",
  "error_reason" : "auth_code_not_found"
}]
```

**Comment by robotdan** [comment]
Can you also post the error or debug Event Log that is generated when this error occurs? 

If you review `System > Event Log` just after you see this, and you see an Error event log, that will be helpful. Then if you enable `debug` for this IdP configuration, and then review `System > Event Log` there will be an event log of type `Debug` with a bunch of good details. You may need to sanitize those event logs prior to posting them here.

**Comment by jon-at-advarra** [comment]
@robotdan There are no errors in the event log. When enabling debug, it logs a successful SAML auth. Here is the end of it:
```
10/27/2022 09:03:08 PM Z User is already registered for application with Id [3c219e58-ed0e-4b18-ad48-f4f92793ae32].
10/27/2022 09:03:08 PM Z User has successfully been reconciled and logged into FusionAuth.
10/27/2022 09:03:08 PM Z Authentication type: SAMLv2IdpInitiated
10/27/2022 09:03:08 PM Z Authentication state: Authenticated
```

**Comment by robotdan** [comment]
Once delivered, we should confirm this has also resolved this linked issue, and then closed as resolves. 
- https://github.com/FusionAuth/fusionauth-issues/issues/2087

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/210
