### ISSUE TITLE
Maintenance Mode DB creation fails without message with PostgreSQL 15 on Windows 

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1944]
### Description 
On Windows Server 2022, installed postgres 15, then attempted to install FusionAuth app and search (1.40.2). When Maintenance Mode came up, entered postgres user and password, used default fusionauth user and password, and clicked submit. Page came back to Maintenance Mode screen without any error message. Log showed stack trace with

```
 Cause: org.postgresql.util.PSQLException: ERROR: permission denied for schema public
```

### Affects versions
1.40.2

### Steps to reproduce

Try to install on Windows Server 2022 with Postgresql 2015.

### Expected behavior

Installs

### Platform
(Please complete the following information)

- Windows Server 2022
- Postgresql 15

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Came from this forum post: https://fusionauth.io/community/forum/topic/2219/maintenance-mode-db-creation-fails-without-message-with-postgresql-15-on-windows

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2015

**Comment by gulecroc** [comment]
Thank you @mooreds, I connect to fusionauth database with postgres user, set the GRANT and restart the pod.

No more error.

**Comment by robotdan** [comment]
Internal:
- https://github.com/inversoft/inversoft-maintenance-mode/pull/2
