### ISSUE TITLE
Enhance SMTP test email debugging and timeout handling

### ISSUE THREAD

**Issue by ebahsini** [FusionAuth/fusionauth-issues#1949]
### Description
When an SMTP server (or perhaps FA) is misconfigured, or we are pointing to the wrong SMTP Port with a correct or incorrect Security setting (none, ssl, TLS), the FusionAuth request may timeout. We don't fail gracefully when this happens, error report to Event Log, or alert the user in anyway currently.

Internal notes: https://inversoft.slack.com/archives/C051S8N8E/p1667404241411779?thread_ts=1667402183.255409&cid=C051S8N8E

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by ebahsini** [comment]
```
{"exception":{"cause":{"cause":{"localizedMessage":"Connection timed out","message":"Connection timed out","stackTrace":[{"className":"sun.nio.ch.Net","fileName":"Net.java","lineNumber":-2,"methodName":"connect0","moduleName":"java.base","moduleVersion":"17.0.3","nativeMethod":true},{"className":"sun.nio.ch.Net","fileName":"Net.java","lineNumber":579,"methodName":"connect","moduleName":"java.base","moduleVersion":"17.0.3","nativeMethod":false},{"className":"sun.nio.ch.Net","fileName":"Net.java",
```

One example, partial response under `networking` for the `POST` request.

**Comment by robotdan** [comment]
We do have an event log, and SMTP debugging, when using these methods, are we still missing details to debug an SMTP config?
