### ISSUE TITLE
OAuth two factor template JS issue

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#195]
### Description 
Template head has the following script:
```javascript
Prime.Document.onReady(function() {
  new FusionAuth.OAuth2.TwoFactor();
});
```

However, if for some reason you decide not to add an element with id `resend-2fa`, you get an JS error in the console. That's because the file `js/oauth2/TwoFactor.js` runs `Prime.Document.queryById('resend-2fa').addEventListener('click', this._handleResendClick)` regardless.

### Steps to reproduce
1. Enable 2FA to an user
2. Login for that user
3. Wait for code to expire
4. Refresh the page, see error.

### Expected behavior
A simple **element exists** check.

### Screenshots
<img width="491" alt="Screen Shot 2019-06-24 at 5 01 03 PM" src="https://user-images.githubusercontent.com/15204146/60059658-3b950100-96a2-11e9-9e43-7bc734127448.png">

### Additional context
FusioAuth version 1.6.1.

Thanks!

**Comment by robotdan** [comment]
Thanks for the report @AlvMF1  - this is a good point, because we allow anyone to modify the HTML in the login pages we should be more defensive in our JavaScript.

**Comment by robotdan** [comment]
Closing for now. If the element with id `resend-2fa` is removed from the DOM, you should also remove this script include.
