### ISSUE TITLE
Invalid error when webhook fails at MFA-input

### ISSUE THREAD

**Issue by dirksierd** [FusionAuth/fusionauth-issues#1955]
### Description 
When MFA is enabled the login.success webhook invokes a wrong error message in the FusionAuth login UX.

When MFA is disabled the standard Webhook-error is shown. When enabled it says the MFA-token is invalid. Which is not the case, the token is valid, otherwise the login.success would not have fired.

### Affects versions
1.40.2

### Steps to reproduce
1. add a login.success webhook (that always returns a non-200 status), and make it required to succeed.
2. log in at an application, with MFA disabled. Observe the webhook error message.
3. Enable MFA
4. Log in again
5. Observe the invalid error message: invalid token

### Expected behavior
I expected the default failing webhook error message.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version Safari 16.1
 - Database postgresql. Hosted cloud instance by FA

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Posted in forum as well: https://fusionauth.io/community/forum/topic/2228/failing-webhook-on-user-login-success-gives-weird-feedback

### Release Notes
Correct the error message when a user has enabled MFA and  a webhook returns a non-200 status code for the `user.login.success` event. The message will now correctly indicate the webhook has failed instead of the previously incorrect error indicating an invalid token was used.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/305
