### ISSUE TITLE
[Question]: Remove account lockout in passwordless

### ISSUE THREAD

**Issue by Pogorzelas** [FusionAuth/fusionauth-issues#1956]
Hey,

We have implemented a mechanism to lock a user out with a user action after a few failed login attempts.
If a user has a locked account and tries to log in by passwordless flow, endpoint `POST /api/passwordless/login` returns an error with a 409 status code.

Is there any possibility to remove account lockout in the passwordless feature?

**Comment by mooreds** [comment]
Hi @Pogorzelas,

This seems like a support question. GitHub issues are for feature requests or bugs with reproduction steps.

For support, please either:

* open an ticket in your portal if you have a plan with support: https://account.fusionauth.io/account/support 
* post in the community forum if you are on a community or starter plan: https://fusionauth.io/community/forum/

Here's more about our technical support guidelines: https://fusionauth.io/docs/v1/tech/admin-guide/technical-support

I'm going to close this issue, but look forward to seeing your post in either of those two venues.

Thanks!
