### ISSUE TITLE
Add `sourceApplicationId` to the Application API to create an app from an existing to copy settings

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1957]
### Problem
It can be painful to create many applications if you want essentially the exact same configuration.

### Solution
Add `sourceApplicationId` to the Application API, similar to the Tenant API to allow a copy to easily be made from existing configuration. This would allow an application to be created as a template so to speak. 

### Alternatives/workarounds
1. Use the API and build your own template to ensure each create operation results with an application with your "default" settings. 
2. Use the `GET` method to retrieve the current settings of one application, modify the result, and then call the `POST` method to create another one based upon the first. 

### Doc
- [x] Add `sourceApplicationId` to the Application API

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/164

**Comment by bhalsey** [comment]
complete
