### ISSUE TITLE
WebAuthn authenticationType is not set in the JWT

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1959]
### Description 

`authenticationType` is a claim present in the access token.

When you login via WebAuthn using safari, the claim is set to `PASSWORD` but should be `WebAuthn`.

Here's an example JWT printed out in a JWT populate lambda, caused by a WebAuthn login:

```
{applicationId: "eafb0310-8985-4976-83fb-2af78d601abb", aud: "eafb0310-8985-4976-83fb-2af78d601abb", auth_time: 1668130635, authenticationType: "PASSWORD", email: "test@example.com", email_verified: true, exp: 1668134235, iat: 1668130635, iss: "https://userdemo.fusionauth.io", jti: "ab8130ef-60cb-48c4-9f60-6fe3a95118e2", roles: [], sub: "ce31e1bd-cd22-4fe1-a44a-d8204b9477a4", tid: "5664394d-da2b-dc6d-379e-74f5193a0a57"}
```

However, interestingly enough the `user.login.success` webhook shows the correct `authenticationType` of `"WebAuthn"` for the exact same login.

### Affects versions

1.41

### Steps to reproduce

* set up webauthn for the system
* set up webauthn for a user
* set up a lambda to log the contents of the JWT and associate it with an application, turn on debug
* reauthenticate the user
* look at the logged jwt

### Expected behavior

`authenticationType` should be `WebAuthn` in the JWT.

### Screenshots

See this video.

https://user-images.githubusercontent.com/91825/201244131-e9dab24a-bc5b-4689-b34e-4f762c055b3e.mov

### Platform

I see this with safari and chrome using macos ventura

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
so far I am unable to recreate. I'll try a few more methods.

**Comment by mooreds** [comment]
@robotdan let me know if you'd like an account on that cloud server that I'm using.

**Comment by robotdan** [comment]
@mooreds sure - just point me at the URL.

**Comment by mooreds** [comment]
userdemo.fusionauth.io

slacked you the account info.

**Comment by mooreds** [comment]
Were you ever able to reproduce this bug?

**Comment by robotdan** [comment]
unable to reproduce

**Comment by mooreds** [comment]
Closing as unreproducible.
