### ISSUE TITLE
Display the remaining login attempts a user has before their account is locked on a FusionAuth hosted login page

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#1966]
### Problem

A Tenant has been configured to lock a user out after `N` number of failed login attempts, as detailed here: https://fusionauth.io/docs/v1/tech/tutorials/gating/setting-up-user-account-lockout

When a user inputs invalid credentials on a login page, the error `Invalid login credentials.` is displayed but they do not see how many attempts they have before their account is locked. Workarounds using the `user.login.failed` Event would require complicated integration code and might not accurately reflect the remaining login attempts to a user.

### Solution

FusionAuth's hosted login page should display the number of remaining attempts a user has before their account is locked. Building this feature would require consideration of the possibility of an enumeration attack. If a malicious actor exceeded the number of login attempts, resulting in a locked account, this might allow them to establish a list of valid accounts that could be used for a brute-force attack. Enabling CAPTCHA for the login page could mitigate the risk of a bot attack but would not deter a malicious user. 

A possible list of required features that should be enabled/enforced to display this message might look like this:

- Enable a CAPTCHA
- MFA enabled
- Strong password policy under Tenant > Password tab > Password settings 

### Alternatives/workarounds
Difficult to suggest based on the security considerations mentioned above.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Closing as won't fix due to the security implications. If you anyone would like to see this built out, please add a comment with a detailed use case. Thanks!
