### ISSUE TITLE
Have a master 2FA enabled option and ask users to setup if haven't done so

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#197]
### Problem
Let's say you wanted to have 2FA enabled for all your users. I believe that would extend #51, except it won't be up to the user to decide.

### Solution
An application config setting + an UI flow. When that's on, after login users would be prompted to complete the setup if they haven't done so.

### New configuration
- Application policy indicating if 2FA is required to complete login

#### A: 2FA is NOT required for the application, user does not have 2FA enabled

1. User clicks on a login button
2. User is redirected to log into FusionAuth
3. User completes login using a password
8. User is logged in and redirected back to the application. 

#### B: 2FA is required for the application, user does NOT have 2FA enabled

1. User clicks on a login button
2. User is redirected to log into FusionAuth
3. User completes login using a password
4. The user is taking to a landing page with copy indicating 2FA is required in order to complete login.
5. The user is provided with a link to the self-service pages where they can enable one or more 2FA methods.
6. The use restarts the login flow, completes 2FA and is logged in and redirected back to the application. 

#### C: 2FA is required for the application, user has 2FA enabled

1. User clicks on a login button
2. User is redirected to log into FusionAuth
3. User completes login using a password
4. User completes the 2FA challenge
8. User is logged in and redirected back to the application. 

### Doc
- [x] New `Required` option for login policy at tenant and application level configuration in API doc
- [x] New themed pages
- [x] Login API will return `242` even when user has not yet configured two-factor methods
- [x] Provide `twoFactorId` on the Two Factor API to get a code to complete a Two Factor Login
- [x] Update MFA guide
- [x] Update core concepts images

### Alternatives/workarounds
We'd have to create the check + the UI to setup on our systems... 😢 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/51
- https://github.com/FusionAuth/fusionauth-issues/issues/1637

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @AlvMF1 this is on the roadmap for sure. 

We've kicked around a few ideas, perhaps as a tenant level, or application level policy. However we envision a common scenario where employees are forced into 2FA but customers / users are not. 

So perhaps it would make sense to use a group, or some other mechanism to decide who is required to 2FA. The other thought we've had - is that we would not necessary require the user to enable 2FA, but instead just force the workflow during login. This is very common in banking. 

For example:

1. User logs in
2. User is pushed a message via SMS or Email containing a code
3. User enters code to continue

In this way, we would not require a TOTP device or application to be configured ahead of time but we could just handle all of this in FusionAuth.

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/158

**Comment by jswinth-cd** [comment]
Fantastic upgrade.  Thanks for all the hard work FusionAuth team!

**Comment by mooreds** [comment]
I documented part of this here: https://github.com/FusionAuth/fusionauth-site/pull/1991

I updated the guide and the core concepts, not the API.

**Comment by bhalsey** [comment]
docs updated.
