### ISSUE TITLE
When I add a passkey, I should be prompted to authenticate with it the next time I try to log in

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1970]
### Problem

When I add a passkey, however I add it, I should be prompted to authenticate with it the next time I try to log in.

Right now, if I add a passkey using the account hosted login pages,  the only way I am prompted to authenticate with it is after log out, log back in with a password, then select the passkey. Then I have to log out again, then I'm prompted to use the passkey and skip the username/password form.

### Solution

I want to be able to add a passkey using the account hosted login pages, log out, and then when I login, be prompted to use my passkey, without having to login with a username and password a second time.

### Alternatives/workarounds

Use the extra steps mentioned above.

### Additional context

internal: https://inversoft.slack.com/archives/C0407FLFP/p1668688487163449?thread_ts=1668667105.881379&cid=C0407FLFP

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This is the intended behavior.

**Comment by mooreds** [comment]
More feedback from the eng team:

"Registering a passkey manually on the self-service account pages uses a general workflow because we don’t know how the user intends to use that passkey. It may be a YubiKey that they intend for bootstrap login or a second factor."

Closing.
