### ISSUE TITLE
Adjust User Facing Themes to a modern HTML5 centric approach when building forms.

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1972]
# Adjust User Facing Themes to a modern HTML5 centric approach when building forms.

### Problem
FusionAuth uses PrimeJS for some of its HTML and form building.  Change to an HTML5-centric approach where appropriate.

### Solution
Update Theme/Freemarker templates to use a more modern Form Building experience (moving away from PrimeJS)

### Alternatives/workarounds
1. Use the existing theme as is.
2. Write or modify a new theme

### Additional context
Date picker example - https://github.com/FusionAuth/fusionauth-issues/issues/561#issuecomment-1319034348

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2770

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Closing under https://github.com/FusionAuth/fusionauth-issues/issues/2770
