### ISSUE TITLE
Reset password doesn't redirect to confirmation page

### ISSUE THREAD

**Issue by sinqinc** [FusionAuth/fusionauth-issues#1975]
Hi, We have a Tenant Application that have a redirect_uri with an app handle like myapp://. The problem is when someone click on the "forgot your password" and open the mail elsewhere (like a PC) the submit button doesn't work and the user is confused because the password has changed. The Browser try to redirect him to the "redirect_uri" instead of the confirmation page. If I send a password reset within the admin console, it's working fine and the user is redirected to the confirmation page template. How to always redirect to the confirmation page whatever the user come from (Mobile App, Web, etc.) ?
I tried to modify the "link" handler template like that :
```
[#macro link url extraParameters=""]
[#if url == "/password/forgot"]
<a href="${url}?tenantId=${(tenantId)!''}">
  [#elseif url == "/password/change"]
<a href="${url}?tenantId=${(tenantId)!''}">
[#else]
<a href="${url}?tenantId=${(tenantId)!''}&client_id=${(client_id?url)!''}&nonce=${(nonce?url)!''}&pendingIdPLinkId=${(pendingIdPLinkId)!''}&redirect_uri=${(redirect_uri?url)!''}&response_mode=${(response_mode?url)!''}&response_type=${(response_type?url)!''}&scope=${(scope?url)!''}&state=${(state?url)!''}&timezone=${(timezone?url)!''}&metaData.device.name=${(metaData.device.name?url)!''}&metaData.device.type=${(metaData.device.type?url)!''}${extraParameters!''}&code_challenge=${(code_challenge?url)!''}&code_challenge_method=${(code_challenge_method?url)!''}&user_code=${(user_code?url)!''}">
[/#if]
[#nested/]
</a>
[/#macro]
```
but the "return to login" fail with "invalid request" which I think is normal since the client_id and the redirect is removed. But how to handle the situation like the "reset" password do from the admin console. Why isn't just returning to the confirmation page whatever the redirect_uri is ?

Thank you

**Comment by mooreds** [comment]
Hi @sinqinc .

This seems to be a support request. Per our [technical support guidelines](https://fusionauth.io/docs/v1/tech/admin-guide/technical-support), support questions should be asked via one of two channels:

* If you have a plan which includes support, please open a support ticket here: https://account.fusionauth.io/account/support
* If you have community support, please use the forum: https://fusionauth.io/community/forum/

I'm going to close this issue, but we look forward to digging further into your question in one of those channels.
