### ISSUE TITLE
Missing WebHookIds on the Tenant Request

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1984]
### Description 

The Tenant request json here: https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/api/updateTenant.json (for example), doesn't include all 

### Affects versions

Any version after 1.37, which is when webhookids were added to the tenant object, to address https://github.com/FusionAuth/fusionauth-issues/issues/1812

### Steps to reproduce

Try to create a tenant request with webhookids using the go client library.

### Expected behavior

This parameter should be available on all types of tenant request (create, update, retrieve).

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Originally reported by @sjauld here: https://github.com/FusionAuth/go-client/issues/70

**Comment by lyleschemmerling** [comment]
@mooreds Looks to me that the webhook ids are on all of the TenantRequest typed objects in the clients and those are used in the create and update requests so I don't think there is an actual issue here. Please double-check but I think we can close this one.

**Comment by mooreds** [comment]
Ah, I may have missed that. I thought it was top level, but there it is on the TenantRequest object.

@lyleschemmerling did you the recreate steps? Were you able to add a webhook with webhook ids using the golang client and the tenant request object?

**Comment by lyleschemmerling** [comment]
@mooreds Dan yes I did run the go client and the java client and was able to successfully create a tenant with a webhook using the webhook ids parameter. So I think that we are good!

**Comment by mooreds** [comment]
Great, thanks! Appreciate the double check.
