### ISSUE TITLE
Kafka integration doesn't check for required topic when sending test event

### ISSUE THREAD

**Issue by sixhobbits** [FusionAuth/fusionauth-issues#1985]
### Description 

When pressing "Send test event" while setting up a Kafka integration, FusionAuth attempts to send the test event even if the topic field (which is required) is blank. If the Kafka configuration is not valid, it shows a loading icon for several seconds before indicating failure.

With valid Kafka configuration, it fails a bit faster, but still shows the loading spinner for a bit.

### Affects versions

Using `fusionauth/fusionauth-app:latest` on Docker.

### Steps to reproduce
1. Go to `Settings -> Integrations'
2. Click on 'Configure' on the Kafka icon
3. Leave the topic blank
4. Put incorrect configuration (e.g. a wrong port number) for a Kafka set up
5. Press "Send test event"

### Expected behavior

The test should immediately fail and inform the user that they need to specify the Kafka topic.

### Screenshots
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/2641205/204492523-4d3d181a-4363-4172-a3de-43b0c40b7245.png">

### Platform
(Please complete the following information)
 - Device: Macbook M1 14"
 - OS: MacOS
 - Browser: Safari 16.1
 - Database Postgres

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/163
