### ISSUE TITLE
JavaScript error when navigating to application login URL

### ISSUE THREAD

**Issue by jon-at-advarra** [FusionAuth/fusionauth-issues#1986]
### Description 
We noticed a JavaScript error logged to the console:
```
Uncaught (in promise) TypeError: this.uvpaAvailable is null
 Authorize Authorize.js:37
 promise callback*FusionAuth.OAuth2.Authorize Authorize.js:37
 <anonymous> authorize:77
 value PrimeDocument.js:377
 value PrimeDocument.js:193
 Prime Overlay.js:110
 <anonymous> prime-es6-1.6.4.js:10377
 ```
 
 when navigating to an application login URL. This error is intermittent.

### Affects versions
1.41.3

### Steps to reproduce
1. Open dev tools/console
2. Navigate to app login URL
3. Notice error in console

### Expected behavior
No errors in console.

### Screenshots
![image (1)](https://user-images.githubusercontent.com/116736293/205124500-78244570-17fa-4767-b49f-3286389929ec.png)

### Platform
 - Device: Laptop
 - OS: Windows 10
 - Browser + version: Firefox 107.0 (64-bit)
 - Database: PostgresSQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/157

**Comment by spwitt** [comment]
Doc changes were completed in
- https://github.com/FusionAuth/fusionauth-site/pull/1767

Closing issue
