### ISSUE TITLE
Adding support for Elasticsearch 7

### ISSUE THREAD

**Issue by diego1q2w** [FusionAuth/fusionauth-issues#199]
### Problem
We are planning to move onto ES 7 among many reasons because of the security features that now have become free, but we've noticed some issues specifically upon the index creation.
### Solution
I don't know the implementation details, but from what I noticed looking at the logs it mainly has to do with the indexes luckily, together with the update, ES has published a great article of breaking changes with the previous version, looking specifically at the index changes [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_indices_changes), you might see what it takes to take for FS to fully support Elasticsearch.

Thanks and looking forward to seeing this in the next version!
### Alternatives/workarounds
For now, keeping version 6.7 at least

### Additional context
https://www.elastic.co/support/eol

```
Ver   | EOL date   | Maintained until
6.3.x | 2019-12-13 | 6.4.0
6.4.x | 2020-02-23 | 6.5.0
6.5.x | 2020-05-14 | 6.6.0
6.6.x | 2020-07-29 | 6.7.0
6.7.x | 2020-09-26 | 6.8.0
6.8.x | 2020-11-20 | 8.0.0
7.0.x | 2020-10-10 | 7.1.0
7.1.x | 2020-11-20 | 7.2.0
7.2.x | 2020-12-25 | 7.3.0
7.3.x | 2021-01-31 | 7.4.0
7.4.x | 2021-04-01 | 7.5.0


```

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Targeting 7.6.1 and hope to support backwards compatibility to 6.3.1.

**Comment by ceefour** [comment]
![image](https://user-images.githubusercontent.com/24123/80629958-b9255c80-8a7d-11ea-8a3e-8dd5f9cba51c.png)

(୨୧•͈ᴗ•͈)◞ᵗʱᵃᵑᵏઽ*♡

**THANK YOU SO MUCH @robotdan AND ALL THE FUSIONAUTH FOR ALL THE HARD WORK**

⁣💙💙💙💙💙💙💙💙💙💙💙💙💙💙💙
💙💛💙💙💙💛💙💛💙💛💙💛💛💛💙
💙💛💙💙💙💛💙💛💙💛💙💛💙💙💙
💙💛💙💙💙💛💙⁣💛💛💙💙💛💛💙💙
💙💛💙💙💙💛💙💛💙💛💙💛💙💙💙
💙💛💛💛💙💛💙💛💙💛💙💛💛💛💙
💙💙💙💙💙💙💙💙💙💙💙💙💙💙💙

**Comment by ceefour** [comment]
@robotdan I no longer able to see System > Reindex menu in 1.16.0-RC.1.. is it still in development?

![image](https://user-images.githubusercontent.com/24123/80632083-e7f10200-8a80-11ea-88c9-f475b4cb4bb6.png)

**Comment by robotdan** [comment]
The reindex action is not displayed when you are in database search mode. See System > About. 

The release notes and doc will be coming out shortly, but if you are starting up locally you can either modify the `fusionauth.properties` file or set the environment variable `FUSIONAUTH_SEARCH_ENGINE_TYPE=elasticsearch` so that we will expect to find Elasticsearch running and connect to it.

**Comment by ceefour** [comment]
@robotdan Wait... so elasticsearch is "optional", not mandatory? And it has to be explicitly enabled? I was under impression that FusionAuth cannot start without Elasticsearch.

**Comment by robotdan** [comment]
Starting in 1.16.0-RC.1 it is optional per this issue. 
https://github.com/FusionAuth/fusionauth-issues/issues/427

We'll now basically default to no elasticsearch to make dev setup easier. It can then be enabled via configuration or environment variable. 

For smaller installs, dev, or environments where search is not super important, you can now optionally run without elasticsearch.  You do lose some of the powerful search options - so it is a bit of a tradeoff.
