### ISSUE TITLE
Hosted Distributions Randomly Change Order As Page Refreshes Automatically

### ISSUE THREAD

**Issue by jswinth-cd** [FusionAuth/fusionauth-issues#1994]
### Description
With multiple hosted distributions on the page they randomly re-order as the page is doing background refresh.  This is problematic as it can happen just before you click the action drop-down which could result in the incorrect distribution being upgraded.  The popup prompt during upgrade makes that less likely but the page re-ordering itself is still disconcerting from a user perspective.

https://account.fusionauth.io/account/deployment/ 

Recommend some type of consistent display order.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
I can't replicate this behavior. @jswinth-cd , do you still see this random order?

**Comment by jswinth-cd** [comment]
@mooreds, I no longer see random list order when the page is presented.  I get cd-prod, cd-stage, and cd-dev in the same order each time I refresh the page now.
