### ISSUE TITLE
OpenAPI Specification requires tenant id on Create Tenant (POST /api/tenant/{tenantId})

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#1998]
### Description 
In the published OpenAPI specification the documentation for some of the POST create methods appear to require the id for the entity being created. The example here is POST /api/tenant/{tenantId} although I see this in some of the other POST create methods as well so we should audit the others to see which all are a problem.

This also follows down into the generated client code. For example in the Go client the tenant ID is required when it should be nullable.

### Affects versions
Seen on 1.42, but will affect earlier versions

### Steps to reproduce
1. Go to [Create Tenant](https://fusionauth.io/docs/v1/tech/apis/api-explorer#/default/createTenantWithId) or view the methods in the generated client code. 
2. Tenant ID is required.

### Expected behavior
Tenant Id should be optional (not required).

### Screenshots
<img width="1179" alt="Screenshot 2022-12-08 at 2 56 18 PM" src="https://user-images.githubusercontent.com/11809481/206577285-e10b4410-f49b-4a65-93ca-02beccf351ae.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
There are actually two create tenant entries. If you scroll down, you'll see one without a tenant id.

![Screenshot 2022-12-08 at 3 40 58 PM](https://user-images.githubusercontent.com/91825/206582388-7383dca5-4455-4ba5-97da-a2c258738554.png)

**Comment by lyleschemmerling** [comment]
@mooreds I just saw that about two seconds before you posted. Let me check the clients and then I may close this. Sorry!

**Comment by lyleschemmerling** [comment]
My bad. Closing.

**Comment by mooreds** [comment]
no worries, there are a lot of APIs :)
