### ISSUE TITLE
Getting JWT token for authorized users

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#200]
Hello. How can I see my JWT token after successful login, let's say through Chrome? I tried to find it in the developer’s tools, but without success.

**Comment by robotdan** [comment]
Are you using the FusionAuth login page or your own application login? The Login API will return the JWT in the response body and set a cookie, but it will be secure HTTP only and domain locked, so it may not be visible unless you're view the Chrome dev tools on the correct domain.

**Comment by forenheith** [comment]
Got it. Thanks.
