### ISSUE TITLE
Location Header redirect missing host and FusionAuth path context `/fusionauth/`when using NGINX reverse proxy

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2000]
### Description 
We have a NGINX reverse proxy that sits between our application and  FusionAuth. When we upgraded to version `1.41.0`, our Location Header no longer conatins our host server, and the `/fusionauth/` context path in the Location Header returned from FusionAuth. 

When we reverted to version `1.36.4`, the redirect Location Header had both the host and fusionauth path. 

When we make a call to FusionAuth with `curl -v https://dev-us-1/fusionauth/admin/login`, our Location Header returns `/oauth2/authorize?client_id=….` instead of `http://dev-us-1/fusionauth/oauth2/authorize?client_id=....`

### Affects versions
`1.41.0` 

### Steps to reproduce
1. Create an Nginx reverse proxy that accepts requests from a FusionAuth application
2. Configure your NGINX reverse proxy. This is our configuration: https://github.com/FusionAuth/fusionauth-contrib/blob/master/Reverse%20Proxy%20Configurations/nginx/nginx.nonrootpath.excerpt.conf
3. Install FusionAuth using a Docker Container for version `1.41.0` 
4. Register an application for the OAuth Code Grant: https://fusionauth.io/docs/v1/tech/oauth/#configure-application-oauth-settings
5. Attempt to visit the `Login URL` by clicking on `Applications > Green view icon > Login URL`. 
6. See if you are redirected to the correct URL containing the reverse proxy host name and fusionauth context path, such as `http://dev-us-1/fusionauth/oauth2/authorize?client_id=....` 

### Expected behavior
I expect FusionAuth to return the complete redirect URL for my authorize endpoint, as described above.

### Platform
(Please complete the following information)
- Device: Desktop
 - OS: macOS
 - Browser + version: Chrome + Version 108.0.5359.94 (Official Build) (arm64)
 -  PostgreSQL 13

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Is it possible there is a change to the proxy that is causing this? 

I tested at various versions all the way back to `1.27.2` and the `Location` header value is relative.  Also tested on recent versions and `1.36.6`, all relative.

**Comment by robotdan** [comment]
I tested on a bunch of various versions of FusionAuth and they all return relative paths in the `Location` header. The spec for the `Location` header allows for relative paths, and the UserAgent is supposed to be able to resolve the host if not provided on the header value. 

If the host was added to the `Location` header at one point, I believe the proxy must have been doing this.

**Comment by mooreds** [comment]
Here's the proxy config: https://github.com/FusionAuth/fusionauth-contrib/blob/master/Reverse%20Proxy%20Configurations/nginx/nginx.nonrootpath.excerpt.conf that they use.

**Comment by robotdan** [comment]
None of the versions I tested ever returned an absolute URI in the `Location` response header. 

Using the clients configuration, I was able to make the `Location` response header use an absolute URI by adding the following configuration to the proxy:

```
proxy_redirect   /          /fusionauth/;
``` 

I don't know if any user agent that will not handle a relative URI.

**Comment by robotdan** [comment]
Please re-open if this is still an issue.
