### ISSUE TITLE
source*Id is ignored on PUT requests but still accepted as a valid parameter. Update Validation on All PUT/PATCH with source*Id

### ISSUE THREAD

**Issue by Pycnomerus** [FusionAuth/fusionauth-issues#2004]
### Description 
When migrating to a new update with a template that as missing template because there is now new ones.
the theme patching api does not consolidate changes from sourceTheme.

from my understanding that is the usecase for **sourceThemeId** but as it only work on **POST** request and not on **PATCH/PUT** one we can't have that behavior on theme updates.

as of c# client 1.42.0 the sourceThemeId can be set on either call to client.CreateTheme And client.UpdateTheme but will promply be ignored in the UpdateTheme one.

### Affects versions
1.42.0

### Steps to reproduce
1. from previous version 1.42.0 or less.
2. create a new template that use sourcethemeId of FusionAuth Theme
3. migrate to 1.36.0
4. update the theme created on step 2 and pass in the sourceThemeId.
Update should fail saying there is missing free marker variables.

### Expected behavior
POST PATCH PUT should all support sourceThemeId especially since PATCH and PUT are supposed to be partial updates.

### Screenshots
![image](https://user-images.githubusercontent.com/6921684/207374570-d010c112-5a93-4436-8812-9147ecde7d68.png)

### Documentation
- [ ] Review these APIs that accept a `source*Id` and ensure we are clear when this property is accepted and when it is not. 

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 10, Docker
 - Browser + version: Any, 1.36.0 +
 - Database: PostgresSQL 12.0

**Comment by mooreds** [comment]
hiya @superrugdr ,

I'm sorry, I am not sure I understand the issue. Are you saying that when I call `PATCH` or `UPDATE` on a theme, I should be able to pass a `sourceThemeId` and have any new templates automatically added to the existing theme?

Or do I misunderstand?

**Comment by superrugdr** [comment]
yea, it's more an inconsistency that a bug i guess,

might not be the case for all client library but at least for the C# one you can pass the parameter in both POST and PUT but it's promptly ignored for the second one and ask to call the post version instead, but I don't see deleting then recreating the theme as a valid use case to update a theme after a version upgrade.

**Comment by mooreds** [comment]
Seems like we should error out if the `sourceThemeId` is present on a `PUT`. Thanks for explaining.

**Comment by robotdan** [comment]
We can add validation for the `PUT` or `PATCH` methods to ensure `source*Id` is not provided.

**Comment by jobannon** [comment]
- https://github.com/FusionAuth/fusionauth-app/pull/244
