### ISSUE TITLE
Preview of HTML email on edit is different than list

### ISSUE THREAD

**Issue by lancegliser** [FusionAuth/fusionauth-issues#2007]
### Description 
The list view of Email templates renders in a way that is either different, or just difficult to read:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/12085479/207459427-f9eeb5ed-1b28-45b7-8716-835d058b5e5e.png">

The edit email preview is rendered in a much more useful way:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/12085479/207459519-c96f541d-13f3-4787-9f89-de9f58b674e5.png">

### Affects versions
Hosted instance 1.41.3

### Steps to reproduce
1. Go to admin/email/template/
2. Click on any templates' "view" button
3. Click on any templates' "edit" button
4. Click on the "preview" button

### Expected behavior
The rendered previews should have the same HTML rendered output, and probably sufficient screen width devoted in both cases to see centering behaviors.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Mac
 - Browser + version Chrome

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Discovered while working with original issue [#1788](https://github.com/FusionAuth/fusionauth-site/issues/1788)

**Comment by mooreds** [comment]
Sure looks like the list version doesn't parse the html correctly.

**Comment by robotdan** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/168
