### ISSUE TITLE
jwt.refresh-token.revoke event not sent

### ISSUE THREAD

**Issue by yvesonline** [FusionAuth/fusionauth-issues#2012]
### Description 
I've set up the `jwt.refresh-token.revoke` webhook in the webhooks section but no matter which API endpoint is being used the event is not triggered.

### Affects versions
This is happening with the Docker container of FusionAuth in version `1.33.0`, we're running this image: `fusionauth/fusionauth-app:1.33.0`.

### Steps to reproduce
1. Go to 'Settings'
2. Go to 'Webhooks'
3. Add a webhook which has `jwt.refresh-token.revoke` enabled
4. Save
5. Now trigger a `POST /api/logout` and see no event being triggered

### Expected behavior
To see the `jwt.refresh-token.revoke` event.

### Platform
 - Docker image `fusionauth/fusionauth-app:1.33.0` running in a K8s cluster
 - Database is a `postgres:13.3` Docker image

### Additional context
- I did check #1522 and as a result upgraded to `1.33.0`
- I tried enabling all events, no effect (other events are being fired but `jwt.refresh-token.revoke` not)
- I tried limiting it to one app, no effect
- I tested the webhook via the test method and this works ✔️ 
- I checked the logs of the container, no suspicious items ✔️

I'm a bit lost as I don't have any further debug possibilities.

Any pointers on how to continue to debug this?

**Comment by yvesonline** [comment]
Oh!

It needs to be enabled separately in the tenant configuration 🤦🏻 

Issue resolved.

**Comment by mooreds** [comment]
@yvesonline glad you figured it out.
