### ISSUE TITLE
Support for multiple post logout redirect URIs per application

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#202]
### Problem
Having trouble redirecting users to a specific page after logout when dealing with multiple environments.  For e.g when logging out from localhost, redirecting user to test site since test site is registered as logout uri in fusionauth application registration.

### Solution
Support for multiple logout uris and user can choose which uri to be redirected to after successful logout. passing querystring to `oauth2/logout?client_id=xxxx&post_logout_redirect_uri=<some url which already registered in app>`

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @prabhakarreddy1234 - you can register a different logout URL per application. 

If I understand correctly, you'd like to register more than one possible logout URL per application and then let the caller decide which one to use? (similar to how we support the redirect URI on the authorize request)

**Comment by prabhakarreddy1234** [comment]
yes @robotdan . I need to register more than one logout uri per application and user can pass redirect_uri to `logout` endpoint so that user will be redirected to that uri after logout.

**Comment by nicholasbutlin** [comment]
Hello, is there any update on this? I have tried multiple ways of managing logging out in order to get around this, but it seems to be impossible.e this feature would make a huge difference.

**Comment by robotdan** [comment]
@nicholasbutlin no update yet, we're currently swamped with other work. 

While not ideal, can you manage the additional redirect on your end? For example, redirect to a common location and then perform a final redirect based upon some state that you preserve (e.g. local storage, cookie, session etc) prior to the redirect to FusionAuth.

**Comment by nicholasbutlin** [comment]
OK thanks @robotdan. 

Am I missing something, or is the oauth/logout the only way to logout?

(and must be done from the client, not any server trying to pass cookie / headers around etc... ).

**Comment by prabhakarreddy1234** [comment]
@robotdan  please confirm if this feature is released in 1.10.0.

**Comment by robotdan** [comment]
Front channel logout is available in version 1.10.0. Thanks.
https://fusionauth.io/docs/v1/tech/release-notes/
