### ISSUE TITLE
Using password reset to unlock account may not work when MFA is enabled for the user

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2032]
### Description 
When using a password reset flow to unlock a user account, the process may fail if the user has MFA enabled. 

### Affects versions
1.42.0
- https://github.com/FusionAuth/fusionauth-issues/issues/383

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/198
