### ISSUE TITLE
After password update, provide the user a means to continue their workflow

### ISSUE THREAD

**Issue by lancegliser** [FusionAuth/fusionauth-issues#2035]
### Problem
- A users visits an application
- Credentials are required and the user has none
- The user is redirected to FusionAuth
- They forgot their password, so they follow that link*
- They enter their email
- They check their email and click the reset password email*
- They fill out the form and update their password
- *They are stuck, with no way to go anywhere on screen*

### Solution
Modify the steps above noted with '*' to include the login attempt context like the application id, pkce, etc.
Use the application id to provide the user a means for going back to the login screen accessing that application using previously stored details.

### Alternatives/workarounds
Not sure there is one. The user has to know to try and access the original application manually.

### Additional context
Theme: FusionAuth
Template: Change password complete

```
[#ftl/]
[#-- @ftlvariable name="application" type="io.fusionauth.domain.Application" --]
[#-- @ftlvariable name="client_id" type="java.lang.String" --]
[#-- @ftlvariable name="currentUser" type="io.fusionauth.domain.User" --]
[#-- @ftlvariable name="tenant" type="io.fusionauth.domain.Tenant" --]
[#-- @ftlvariable name="tenantId" type="java.util.UUID" --]
[#import "../_helpers.ftl" as helpers/]

[@helpers.html]
  [@helpers.head]
    [#-- Custom <head> code goes here --]
  [/@helpers.head]
  [@helpers.body]
    [@helpers.header]
      [#-- Custom header code goes here --]
    [/@helpers.header]

    [@helpers.main title=theme.message('password-changed-title')]
      <p>
        ${theme.message('password-changed')}
      </p>
    [/@helpers.main]

    [@helpers.footer]
      [#-- Custom footer code goes here --]
    [/@helpers.footer]
  [/@helpers.body]
[/@helpers.html]
```

Visual of what a user gets, leaving them confused on the next step they should take (custom theme, but the language is the same):
<img width="496" alt="image" src="https://user-images.githubusercontent.com/12085479/210453272-543f51c1-3a6a-4dc1-a409-94d7a8846a4c.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by lancegliser** [comment]
Eating crow a bit. The screenshot above came not from the login flow that came from the application entry point. it was from something like the admin password reset. I mixed some messages. Closing, it works great. Thank you all.

**Comment by mooreds** [comment]
no worries @lancegliser ! glad you got it sorted out!
