### ISSUE TITLE
Return Error Messages As a HashMap instead of an Array

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2036]
### Problem
We currently return error messages as

```
errorMessages [Array<String>]
A list of error messages that were generated during the processing of the request.
```
https://fusionauth.io/docs/v1/tech/themes/template-variables#common-variables

It would be a nice developer experience to return these as 

```
errorMessages [Map<String, List<String>>] 
```
similar to how we return `fieldMessages`.

### Solution
Change how the front-end pages return `errorMessages`.

For example return:

```
Map<[inactive]user.email:> List: <"An account already exists for that email but is locked. Contact the administrator for assistance>"
```

Instead of just 

```
[<String> "[inactive]user.email=An account already exists for that email but is locked. Contact the administrator for assistance"
```

This would allow conditional logic that could key off of `[inactive]user.email` (instead of the whole string) in the JS/Freemarker of that page.

### Alternatives/workarounds
You can use the exiting `errorMessages` that are returned, but you have to field/parse based on the entire string value.  

### Additional context
https://inversoft.slack.com/archives/C03P8K9R69Z/p1672768268829419

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Working as designed. We could optionally update the documentation in our theming guide to provide an example of how to filter by message code.
