### ISSUE TITLE
Validate email length to 191

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2037]
### Description
Email is an indexed field, so we should validate this length in the User API. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2089

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lyleschemmerling** [comment]
I think this is a no-op. The DefaultUserService already checks both that the local portion of a user email is not longer than 64 chars and that the email address as a whole is not longer than 191 and returns the message `The [user.email] property is longer than the maximum of [191] characters.`
