### ISSUE TITLE
Allow a large number of custom URLs in FusionAuth Cloud

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2039]
### Problem
Custom URLs for HA deployments are limited to 5 per deployment. What if a customer needs thousands of custom domains?

https://fusionauth.io/docs/v1/tech/installation-guide/cloud#custom-domains

### Solution
Allow customers to add thousands of custom URLs per deployment in FusionAuth Cloud. 

### Alternatives/workarounds
Configure a reverse proxy to pass requests from thousands of custom URLs/domains to a single upstream server. 

[FusionAuth Proxy Setup](https://fusionauth.io/docs/v1/tech/admin-guide/proxy-setup)

[Reverse proxy on a Mac with NGINX](https://kirillplatonov.com/posts/simple-reverse-proxy-on-mac-with-nginx/)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines]
(https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
This is delivered in July 2023.

https://fusionauth.io/blog/introducing-unlimited-custom-domains-for-fusionauth-cloud
