### ISSUE TITLE
Help with custom MD5 password encryptor during import

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#204]
### Description
Trying to import an MD5 hash, and the shipped FusionAuth one doesn't work. 

See https://stackoverflow.com/questions/56761072/migrate-users-with-a-salted-hash-passwords/56762164

**Comment by robotdan** [comment]
@AlvMF1 re: https://stackoverflow.com/questions/56761072/migrate-users-with-a-salted-hash-passwords/56762164

Here is a working encryptor, if you want I can get you a jar, or you can build it yourself using our instructions. 

https://fusionauth.io/docs/v1/tech/plugins/password-encryptors

Test input provided by on SO:

Hash: `e0198a696980741ec49e2c56615fbc98`
Salt: `4MTVxbvk8swI0ys2Lf4saeR3swRvn0f2`
Plain text password: `password`

Here is an example PasswordEncryptor for your hash.

```
  public class CustomMD5SaltedEncryptor implements PasswordEncryptor {
    @Override
    public int defaultFactor() {
      return 1;
    }

    @Override
    public String encrypt(String password, String salt, int factor) {
      if (factor <= 0) {
        throw new IllegalArgumentException("Invalid factor value [" + factor + "]");
      }

      MessageDigest messageDigest;
      try {
        messageDigest = MessageDigest.getInstance("MD5");
      } catch (NoSuchAlgorithmException e) {
        throw new IllegalArgumentException("No such algorithm [MD5]");
      }

      byte[] digest = (salt + password).getBytes(StandardCharsets.US_ASCII);
      for (int i = 0; i < factor; i++) {
        digest = messageDigest.digest(digest);
      }

      return DatatypeConverter.printHexBinary(digest);
    }
  }
``` 

And an assertion :

```
PasswordEncryptor encryptor = new CustomMD5SaltedEncryptor();
String result = encryptor.encrypt("password", "4MTVxbvk8swI0ys2Lf4saeR3swRvn0f2", 1);
assertEquals(result, "e0198a696980741ec49e2c56615fbc98".toUpperCase());
```

So if you were to use this to import, you'd need to uppercase your hash to store in FusionAuth. Then, since this is a very weak hash, you'd want to set the hash to be upgraded during next login.

**Comment by AlvMF1** [comment]
That worked! I appreciate your time!

Two things that I've encountered:

- I didn't have to uppercase the hash
- When I login with my admin account (which doesn't use the custom encryptor), I get the following warning in the system logs: `WARN  org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider - Message could not be found for the URI [/admin/system-configuration/edit] and key [my_encryptor]`. That happens when I click **Settings -> System**.

Anything I should be doing?

**Comment by robotdan** [comment]
That log is ok, we just can't translate the name of your custom scheme. I'll look to see if there is a way to define that in your plugin.

That error happens because when you view that page we load up all of the encryptors for use in the password panel where you can select a default scheme. You should see yours on that panel in the select box.

Glad to hear it worked!! Did you have any trouble building the plugin?

**Comment by AlvMF1** [comment]
Not really. Just some issues setting up my machine to compile Java. 😆

**Comment by robotdan** [comment]
Great, need anything on this one, or should we close it out? 

In the upcoming release you will no longer se that warning message in the log regarding `my_encryptor`, I've fixed that.

**Comment by AlvMF1** [comment]
No, I'm all set. Ty!
