### ISSUE TITLE
Pagination/Search for Themes

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2058]
### Problem
It is hard to manage a large number of themes when they are all listed together.

### Solution
Add pagination and search for themes in the admin UI.

### Parent
- https://github.com/FusionAuth/fusionauth-issues/issues/374

### Related
- [x] https://github.com/FusionAuth/fusionauth-site/pull/1921

**Comment by mmanes** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/199
- https://github.com/FusionAuth/fusionauth-client-builder/pull/58

**Comment by mmanes** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/1921
