### ISSUE TITLE
Pagination/Search for Email Templates

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2064]
### Problem
It is hard to manage a large number of email templates when they are all listed together.

### Solution
Add pagination and search for email templates in the admin UI.

### Parent
- https://github.com/FusionAuth/fusionauth-issues/issues/374

### Related
- [x] https://github.com/FusionAuth/fusionauth-site/pull/1920

**Comment by mmanes** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/1920
