### ISSUE TITLE
Ways to getting JWT

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#207]
Is there any way to get JWT in the authorization process? User login is done through the login form (not API)

**Comment by forenheith** [comment]
Any ideas?

**Comment by robotdan** [comment]
What OAuth2 grant are you using, if you're using our login form it will be the Authorization Grant. 

This may be helpful as well. 
https://fusionauth.io/articles/logins/types-of-logins-authentication-workflows

If using the Authorization Grant, then you will receive the JWT at the end of the grant when calling the Token endpoint.
