### ISSUE TITLE
add duplicate button in the UI for API keys to copy permissions

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2075]
### Description
It can be error prone to manually copy permissions from one API key to another, add a duplicate button.  See Applications or Themes for examples. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by jobannon** [comment]
PR - https://github.com/FusionAuth/fusionauth-app/pull/264
