### ISSUE TITLE
Sandbox shows 70+ users, but you can only see 8

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2077]
### Description 

The user count is out of sync with the number of users displayed.

Re-indexing the users fixed the issue, but I don't know why elasticsearch would have been out of sync.

### Affects versions

1.42.1, only see on sandbox.fusionauth.io (maybe specific to setup there?)

### Steps to reproduce

Hard to do so. I'd check sandbox and see if it is out of sync. Not sure if any repro steps.

### Expected behavior

Count of users and users displayed are the same.

### Screenshots

Before the reindex.
![image](https://user-images.githubusercontent.com/91825/214626252-268aaf5d-d37e-4ca6-8bc3-5ee8721cd9a2.png)

### Platform

Sandbox.fusionauth.io

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Didn't test in other scenarios. Tweaked my query a few times and didn't see a fix. Deactivated a user, but they still show up.

**Comment by robotdan** [comment]
This is just because we rebuild this often and the ES index is out of sync.
