### ISSUE TITLE
Review CSRF cookie policy on IdP Initiated Login

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2087]
### Description 
If you complete an IdP-initiated login to the Admin UI released in feature [1915](https://github.com/FusionAuth/fusionauth-issues/issues/1915), if you complete any action requiring a POST (making a group for instance), we will fail CSRF in a short period of time.

### Affects versions
1.43.0

### Steps to reproduce

1. Setup a SAML v2-Idp-Init IdP in FusionAuth with values from an Okta application (using NGrok - this part may or may not be relevant)
2. Set the above up for FusionAuth admin UI (so that you can log into the FusionAuth Admin UI from a federated source)
3. Log in to Okta console to get the idP Initiated Login link that will let you do an AuthN response to FusionAuth (this is the app embed link [our doc reference](https://fusionauth.io/docs/v1/tech/identity-providers/samlv2-idp-initiated/okta#adding-a-user-to-the-okta-application)s)
4. Paste the Link into a browser (private or normal, this does not seem to matter)
5. Watch as the user is logged in
6. Try and immediately create a group (or anything requiring a post/“save”)
7. Get 401 (assumably CSRF) failure.

### Expected behavior
A user should not fail CSRF

### Platform
(Please complete the following information)
dev, latest. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Internal https://inversoft.slack.com/archives/C0407G6V5/p1675132635270959

**Comment by robotdan** [comment]
Guessing this is a duplicate, or will be resolved by one of these issues:

- https://github.com/FusionAuth/fusionauth-issues/issues/1941
- https://github.com/FusionAuth/fusionauth-issues/issues/1976
- - https://github.com/FusionAuth/fusionauth-issues/issues/2096
