### ISSUE TITLE
Entity name length not validated

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#2089]
### Description 
The length of entity names are not validated on the API. This allows a value that is too long for the column to be sent to the API and this causes a database exception which is not handled properly by the Action class.

### Expected behavior
The `name` column looks like it is `VARCHAR(255)` in the database so the validation in the `EntityAction` should check this length for the `name` field in the request.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2037

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by manuella14** [comment]
> ## Entity name length not validated
> 
> ### Description 
> The length of entity names are not validated on the API. This allows a value that is too long for the column to be sent to the API and this causes a database exception which is not handled properly by the Action class.
> 
> ### Expected behavior
> The `name` column looks like it is `VARCHAR(255)` in the database so the validation in the `EntityAction` should check this length for the `name` field in the request.
> 
> ### Related
> - https://github.com/FusionAuth/fusionauth-issues/issues/2037
> 
> ### Community guidelines
> All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/227
