### ISSUE TITLE
Postgresql : SCRAM-SHA-256 => impossible to connect

### ISSUE THREAD

**Issue by colundrum** [FusionAuth/fusionauth-issues#209]
## Postgresql : SCRAM-SHA-256 => impossible to connect

After a security update of the PostgreSQL configuration to force usage of SCRAM-SHA-256 in place of MD5, I can't reconnect to PostgreSQL.

Can you update your lib to permit a full secure connection to postgresql database ?

Regards

**Comment by robotdan** [comment]
Is it possible to connect if you modify the JDBC url in the config file?

https://fusionauth.io/docs/v1/tech/reference/configuration

**Comment by colundrum** [comment]
No, it depends only of the lib if SCRAM-SHA-256 implemented or not

**Comment by robotdan** [comment]
Ok, thanks for that info, we'll take a look.

**Comment by robotdan** [comment]
Looks like SCRAM was added in the connector version 42.2.0 (2018-01-17). 
If you want to try a work-around, feel free to replace the PostgreSQL connector jar in the class path with a more recent one ( <= 42.2.0 and see what happens. 

`web/WEB-INF/lib/postgresql-9.4.1212.jar`
https://jdbc.postgresql.org/download.html
