### ISSUE TITLE
Get Token without an application registration.

### ISSUE THREAD

**Issue by garsiv1932** [FusionAuth/fusionauth-issues#2092]
### Description 
If Application require registration and a user is not registered the user could still receive a token from the API.

### Affects versions
FusionAuth™ version 1.42.1

### Steps to reproduce
1. Configure a new application
2. In the application configuration, in the OAUTH tab, set "Require registration" to true.
3. Make the login via API with the application id and you will get a token.

### Expected behavior
Get an error

### Screenshots
![Screenshot from 2023-02-04 01-22-03](https://user-images.githubusercontent.com/65036539/216748281-c17d73c0-8604-471b-b83f-5a91dac05d82.png)

### Platform
(Please complete the following information)
 - Device: Docker
 - OS: Ubuntu 22.04
 
 Sory but this is a bug, if I have the registration validation by application, is a bug to get a token, getting the cookies when you are using the fusionauth forms, is the same, IMHO is an error, but you show a page saying you are not authorized, but you cant do anything and the user need to wait to the token to expires to try it again, or delete the cookie manually.

**Comment by robotdan** [comment]
This is working as designed. 

The token represents the authenticated user, so if the user provides valid credentials a token is issued. The claims found in the token will represent what the user is authorized to - and if the user is not registered, the `applicationId` and `roles` claims will be excluded. 

The "Require registration" flag causes a user to be gated in the hosted login pages when not registered, but it does not affect the APIs directly.
