### ISSUE TITLE
Allow configuring header Content-Security-Policy

### ISSUE THREAD

**Issue by MPH-DZP** [FusionAuth/fusionauth-issues#2095]
### Problem
When developing a redirect into our FA instance, rendering the FA response in an iframe is useful. However, the FA default header X-Frame-Options:DENY prevents going past the first "step" of a self-registration.

### Solution
Having support to configure a Content-Security-Policy header would override the X-Frame-Options:DENY blockage, according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
According to https://fusionauth.io/community/forum/post/1069 (and googling FA docs) this feature does not yet exist.

### Alternatives/workarounds
Postman seems not to allow setting an origin nor rendering the FA html response.

### Additional context
nil

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Duplicate:
- https://github.com/FusionAuth/fusionauth-issues/issues/1003

Related:
- https://github.com/FusionAuth/fusionauth-issues/issues/1510
