### ISSUE TITLE
Feature : Custom registration fields in the User Interface

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#21]
### Problem

If for every user registration to application `Acme` you need to add a custom data field called `company`, currently this is done via a registration workflow on the end users application side. 

Or this can also be set via an API call to the Registration API. 

I'd like to define a few required fields, or optional fields and have them available in the UI when I register a user. 

### Solution

TBD

### How to vote

Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by gregoriopellegrino** [comment]
With custom validators!

**Comment by robotdan** [comment]
It is possible we would address this issue under this feature. https://github.com/FusionAuth/fusionauth-issues/issues/680

**Comment by robotdan** [comment]
This was delivered under https://github.com/FusionAuth/fusionauth-issues/issues/753
