### ISSUE TITLE
Emails end up in the SPAM folder when sending with Mandrill

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2116]
### Description 
When using Apple SSO with iCloud Private Relay and users opt to hide their email during log-in, emails for email verification, and password reset processes, the corresponding emails may be delivered to the recipient's spam inbox. 

### Affects versions
1.40.2

### Steps to reproduce
1. Install FusionAuth 
2. Register an application, and create a user. 
3. Configure Apple IdP
4. In your mobile application, implement the OAuth 2.0 flow. This typically involves using a library or SDK to handle the OAuth interactions, such as authorization requests, token exchanges, and refreshes. Your mobile application should also be able to exchange a code for a token from the oauth2/token endpoint.
5. Configure transactional emails using Mandrill: https://mailchimp.com/help/add-or-remove-transactional-email/?utm_source=mc-kb&utm_medium=kb-site&utm_campaign=eepurl
6. When logging into a mobile application, attempt to create a new user and register them for your application
7. Select the option to hide your email when logging in with Apple
8. Confirm if the email was received in the recipient's inbox or was filtered as spam. 

### Expected behavior
We expect the email for email verification and password reset to appear in the recipient's inbox and not be filtered as spam. 

### Platform
(Please complete the following information)
- Email Provider - Gmail, Outlook, etc. 
- FusionAuth version 1.40.2

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
FusionAuth cannot control how email is filtered by 3rd parties.
