### ISSUE TITLE
Breach Password Detection Shows Breached User, but no actions available

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2119]
### Description 
Breached password detection was turned on, showing one user with a breach but was not able to find the user or not the time of the breach on the user object.

### Affects versions
reported on 

1.41.3

### Steps to reproduce
1. Turn on breached password detection under the tenant
2. set Match Mode to `high`
3. set to Only Record the result, take no action 

### Expected behavior
If I am informed that a user has a breached password, I should be able to see the user that is affected.

### Platform
(Please complete the following information)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
reported on ticket - 73178

**Comment by robotdan** [comment]
If you can recreate, please re-open.
