### ISSUE TITLE
C# FusionAuthClient ValidateJWT

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#212]
I'm trying to do something like this to check my JWT, 

`var fusionAuthClient = new FusionAuthClient(ApiKey, "http://localhost:9011");`
 
`var result = fusionAuthClient.ValidateJWT(jwt);`

but I get 401 Unauthorized in return. ApiKey is valid and configured. What am I doing wrong?

**Comment by robotdan** [comment]
Is it possible the JWT is expired? Also, the C# client will be deprecated in favor of our new .NET Core library. Have you tried this library? 

https://www.nuget.org/packages/fusionauth-netcore-client/1.7.2

**Comment by robotdan** [comment]
@forenheith let me know if you still need assistance with this one, thanks.
