### ISSUE TITLE
CSRF error when logging into admin UI with SAML v2 IdP initiated login

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2125]
### Affects versions
This is either a side effect of something we fixed in `1.43.0` or just another edge case of the same issue we fixed in version `1.43.0`, TBD.

### Steps to reproduce
1. Login to FusionAuth admin UI using SAML v2 IdP initiated login
2. Navigate to the Reactor page and get an error

Error:

```
A FreeMarker exception occurred.

Exception:
FreeMarker template error:
The following has evaluated to null or missing:
==> csrfToken  [in template "templates/admin/reactor/index.ftl" at line 49, column 81]
```

### Expected behavior
No error. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1976
- https://github.com/FusionAuth/fusionauth-issues/issues/1941
- https://github.com/FusionAuth/fusionauth-issues/issues/2096

### Documentation
- [x] Review IdP initiated documentation to ensure we document that `scope=offline_access` is required to get a refresh token, and when using with the FusionAuth admin app - it is optional since we'll add it for you. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/217
