### ISSUE TITLE
Allow Steam IdP to Select Publisher Endpoints

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2127]
### Problem
The FusionAuth Steam IdP is currently authenticating users by calling the public Steam APIs [api.steampowered.com](http://api.steampowered.com/)

This API is public and rate limits at 10,000 daily user requests

### Solution
Use the publisher partner APIs for unlimited request volume.

[partner.steam-api.com](http://partner.steam-api.com/)

These APIs are identical to the public endpoints but have no rate limits

### Alternatives/workarounds
A clear and concise description of any alternative solutions or workarounds you've considered.

### Additional context
- https://partner.steamgames.com/doc/webapi_overview/auth
- https://partner.steamgames.com/doc/webapi_overview#addresses

Internal - https://inversoft.slack.com/archives/C01TJLP2HQ8/p1677262366459459?thread_ts=1677261823.387799&cid=C01TJLP2HQ8

### Documentation
- [ ] Add `apiMode` to the API doc.
- [ ] Update configuring the Steam IdP to include this parameter in the screenshot

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/223

**Comment by robotdan** [comment]
Added `apiMode: [Public|Partner]` to the API. Setting to `Partner` will use the Partner API, public will use the Public API.
