### ISSUE TITLE
Variables attached to Tenants and Applicacations

### ISSUE THREAD

**Issue by sm-tradeboox** [FusionAuth/fusionauth-issues#213]
### Problem
It's a feature request, you've already done a great job

### Solution
Hello.

We provide a simple, cheap software for small clinics to use to mange internal operations. We're in the process moving to Fusionauth to help us better manage employee, doctor, health care professionals, service providers and patient credentials, otherwise we don't have a financially viable product.

So I'm going to write this up as pertaining to our own use case.

We have 2 primary use cases that I hope you'll consider addressing.
1. Users added in/by one tenant application accessible by other tenants
We would also like to be able to share patient login data generated by any one tenant across multiple tenants. 

2. Tenant & Application Metadata We can Use in Mailers
Each tenant (clinic) has unique properties and sometimes it's required we attach different metadata fields, like Full name, description, Internal ID, primary contact email, primary telephone number, etc. 
The same is true for any application we create for a particular tenant. It may have its own URL, descriptors, managers, system administrators, help desk contacts, etc.
I'm hoping there is some way you can generalise this requirement, like you have done with user data, and let admins assign each data field a variable name, so that the same can be used in email templates.

In our particular use case, we are inserting specific additional user data into each user record. I would like to use this information in mailers we send out. If you can do the above mentioned, the same approach could also be used to extend the user data schema.

Thanks again.

Sam

**Comment by robotdan** [comment]
Hi @sm-tradeboox thanks for the compliment! I'm glad you have found FusionAuth to be helpful! 

> Users added in/by one tenant application accessible by other tenants

This is not currently possible -as you've pointed out. If you have a need to share data between tenants, would it make more sense to think of each clinic as an application within the same tenant? 

Our litmus test is if you want `joe@example.com` to (potentially) exist separately in Clinic A and Clinic B and maintain a separate password, attributes, etc for each clinic. 

Or - if you'd like `joe@example.com` to exist once and possible have access to Clinic A and Clinic B - but always have the same login credentials, then applications within the same single tenant may be a better fit. 

So if `joe@example.com` has an account for Clinic A, and he then signs up for Clinic B, should he have to sign up again and maintain a separate account?

> Tenant & Application Metadata We can Use in Mailers

You can set custom data on a User, User Registration, Application, Group or Tenant using the `.data` field on each object respectively. Would this satisfy your requirement? 

In the scenario where each clinic is a tenant, you could store this on the tenant data `tenant.data`, and in the scenario where a clinic is an application, you could store this on the application data `application.data`.  

Thank you for your participation in the FusionAuth community!

**Comment by aakay** [comment]
Hi @robotdan , thanks for the explanation.

We're currently starting using the app for our auth needs as well and I stumbled upon this request. Your suggestion (using `.data`) is what we're thinking to manage custom data. Is there a way to see/edit the custom data on the administration ui such as tenant management views?

**Comment by robotdan** [comment]
You can see all custom data in the UI, currently it can only be modified by the API. Edit in the UI will probably in 1Q or 2Q hopefully.

**Comment by aakay** [comment]
Thanks for the explanantion and effort. Appreciate it!

**Comment by robotdan** [comment]
Is this resolved by using custom data on the app and tenant, or is there a use case that is not solved adequately with the current implementation?

**Comment by robotdan** [comment]
I think this is solved by the existing custom data options, if not please re-open and clarify. Thanks.
