### ISSUE TITLE
Add analytics to the sandbox theme

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2131]
### Description

We have no idea how many people are using the sandbox FusionAuth instance at sandbox.fusionauth.io.

Please add web analytics to the sandbox setup and reset scripts.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
@mooreds will usage stats give you what you need?

**Comment by mooreds** [comment]
I think we can close this one out.
