### ISSUE TITLE
Can't validate jwt token

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#214]
When I trying to validate my JWT I getting the following error message:

IDX10501: Signature validation failed. Unable to match keys: 
kid: '6SvdDEUeP-fREZapjd8R_Rqpzfc', 
token: '{"alg":"RS256","typ":"JWT","kid":"6SvdDEUeP-fREZapjd8R_Rqpzfc"}.{"aud":"de4b2435-a400-4343-87ee-ef3c99bea3e5","exp":1562264275,"iat":1562260675,"iss":"acme.com","sub":"78b1c80e-a1dc-4be9-a9be-34dde2996169","authenticationType":"PASSWORD","email":"some@gmail.com","email_verified":true,"preferred_username":"forenheith","applicationId":"de4b2435-a400-4343-87ee-ef3c99bea3e5","roles":[]}'.

What am I doing wrong ?

**Comment by forenheith** [comment]
For now I've deleted application specific JWT settings and got new error message: {"Invalid JWT - additional validation failed"}

**Comment by robotdan** [comment]
Can you provide me some additional detail? The `IDX10501` message is not ours, what library are you using, or technology stack?

**Comment by forenheith** [comment]
I'm using JwtSecurityTokenHandler by Microsioft. For now issue is solved. Thanks for your help.
