### ISSUE TITLE
Enabling the Idp-Init toggle on a SAMLv2 IDP hides the base ACS url in the view window

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2146]
### Description 
See the screenshots below. For IDP-init the ACS URL should `/acs/{idpId}/{applicationId}` but for SP initiated it is just `/acs`. Flipping the "Enable IdP initiated Login" toggle hides the base /samlv2/acs URL in favor of the idp-init URL in the integration details view. This may cause a problem as the admin may need the /acs URL for configuring the idp to allow sp-initied logins. We should update the view to show both URLs

### Affects versions
1.43.0

### Steps to reproduce
1. Create a new SAMLv2 IDP
2. Click on the green view button on the Identity Providers list page. See the callback url.
3. Edit the idp configuration by toggling "Enable IdP initiated login" and add an issuer.
4. Click the green view button again. The original ACS URL is gone and is replaced by the idp-init URL

### Expected behavior
We should show both URLs when idp-init is enabled

### Screenshots
<img width="1397" alt="Screenshot 2023-03-07 at 11 17 10 AM" src="https://user-images.githubusercontent.com/11809481/223516803-e8e85957-6363-4212-8574-0c88e7e76203.png">
<img width="1412" alt="Screenshot 2023-03-07 at 11 18 37 AM" src="https://user-images.githubusercontent.com/11809481/223516810-8bd502af-b723-4bda-af8c-9b9b9444c3de.png">
<img width="1458" alt="Screenshot 2023-03-07 at 11 19 07 AM" src="https://user-images.githubusercontent.com/11809481/223516823-25494a80-7062-484d-a3a2-11b97fcd1915.png">
<img width="1458" alt="Screenshot 2023-03-07 at 11 20 01 AM" src="https://user-images.githubusercontent.com/11809481/223516833-a7d27453-d402-4b41-95b0-55679b2142ce.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Doc
- [ ] Update SAMLv2 IdP doc to explain difference in URLs

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/2009
- https://github.com/FusionAuth/fusionauth-app/pull/221
