### ISSUE TITLE
Application variable not available on MFA email template

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2149]
### Description 
When completing an MFA challenge, we document that a `application` variable should be available.

### Steps to reproduce
1. Enable MFA on the user [email type]
2. Have the user log in 
3. Have the user have an MFA code emailed
4. See that if you add a ${applicaton} evaluates to null.

The same behavior happens when 
1. using the `/api/two-factor/start` API 
2. Including an `applicationId`
3. and sending a code out of band using the `api/two-factor/send` API
4. The email sent lacks an application variable

### Expected behavior
The application variable should be available. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Documentation updates
- [x] Document that `application` may not be available in MFA emails in [Email Variables](https://fusionauth.io/docs/v1/tech/email-templates/templates-replacement-variables#two-factor-authentication) doc
  - https://github.com/FusionAuth/fusionauth-site/pull/2172
- [x] new `applicationId` parameter on the `TwoFactorSendRequest` API

**Comment by robotdan** [comment]
@jobannon is this a bug? If so, please add that label, and does this affect both the add and remove MFA method templates?

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/249
