### ISSUE TITLE
Email Verification should not required an email template when Setup password email template is enabled

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2150]
### Problem
1.  When Email Verification is enabled on Tenant (Verify email)
2. The user is prompted to create `Verification template`
3. However, if you have enabled `Allow implicit verification` and 
4. You have enabled a `setup password` template on the tenant level

then, depending on your use case, the email verification template may not be needed as the user will verify their email via an implicit setup password link. 

### Solution
Change how the validation functions for email validation on the tenant level.

### Alternatives/workarounds
Create (or use the default) email verification template and have a user potentially get an additional email regarding verifying their email address (in addition to, that is, a setup password email)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by andrewpai** [comment]
Closing this issue, as there are still cases where validation email needs to be sent, such as when a user is manually created and not auto-verified.
