### ISSUE TITLE
Disable a single multi-factor method by User Id should take an `applicationId` as query parameter

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2153]
### Description 
Disable a single multi-factor method by User Id does not take an `applicationId` as a query parameter although it does accept it in the Request Body. 

### Affects versions
1.43.0 

### Steps to reproduce
1. [Send a Multi-Factor Code When Enabling MFA](https://fusionauth.io/docs/v1/tech/apis/two-factor#send-a-multi-factor-code-when-enabling-mfa) - get a code to enable MFA on a user
2. Enable Multi-Factor on a User
3. [Attempt to disable MFA on a user ](https://site-local.fusionauth.io/docs/v1/tech/apis/two-factor#send-a-multi-factor-code-when-disabling-m) - get a code to disable MFA
4. Attempt to pass an `applicationId` as a query parameter when Disable a single multi-factor method by User Id, such as https://YOUR_INSTANCE/api/user/two-factor/:userId?methodId=email&code=123&applicationId=123
5. a 500 error is returned

### Expected behavior
If disable Multi-Factor accepts an `applicationId` in the Request Body it should also accept it as a query parameter. 

### Platform
(Please complete the following information)
 - Device: [Laptop]
 - OS: [macOS]
- FusionAuth 1.43.0 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/1789
- https://github.com/FusionAuth/fusionauth-site/issues/2028

**Comment by robotdan** [comment]
I believe this is fixed in 1.44.0

**Comment by robotdan** [comment]
Updates:
- https://github.com/FusionAuth/fusionauth-site/commit/5f0e12bbb205f588d99b238fbf84a46b442d09bd
