### ISSUE TITLE
Reactor page has typo when using production license

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2155]
### Description 

When you add an enterprise license production, you see this text on the reactor page:

```
Enterprise.  Production, usage will not count towards your billable MAU. 
```

### Affects versions

1.40.2
1.43.1

### Steps to reproduce

* Create an enterprise license
* Add it to a fusionauth instance
* Wait for it to activate
* View the message.

### Expected behavior

Would expect it to say 

```
Enterprise.  Production, usage will count towards your billable MAU. 
```

### Screenshots

<img width="715" alt="Screenshot 2023-03-13 at 12 18 23 PM" src="https://user-images.githubusercontent.com/91825/224812841-f8b9e37d-8865-4a5e-9e42-6355efada9bd.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Looks like the issue is in web/templates/admin/reactor/index.ftl

**Comment by robotdan** [comment]
This was fixed a while ago. Where are you seeing this on a `1.43.1` system? (what server or hostname)

**Comment by mooreds** [comment]
Oops, I transposed the digits. I saw it on a 1.41.3 system. 

Just checked on a 1.44 system and don't see it. Closing.
