### ISSUE TITLE
On FusionAuth python client, login method return 401, while api call return correct value.

### ISSUE THREAD

**Issue by JavierMoncayo** [FusionAuth/fusionauth-issues#2156]
### Description 
With the user name and password, I am trying to login a user.

If I call the API endpoint directly, I get 213 code as expected:

    url = http://localhost:9011/api/login
    data = {
        'loginId': loginId,
        'password': password,
        'applicationId': My_App_ID
    }
    headers = {
        'Content-Type': "application/json"
    }
    response = requests.post(url, json=data, headers=headers)`

If I call the FusionAuth client then I get a 401:

    client = FusionAuthClient(api_key = MY_API_KEY,
                              base_url = MY_BASE_URL)
    #     I have tried:
    client.login(data) 
    client.login(data = {data}) 

### Affects versions
I am using: python 3.8, Flask, and FusionAuth 1.43.

### Steps to reproduce
Login user with same data but using different approach as described above.

### Expected behavior
213 response code in both cases.

**Comment by JavierMoncayo** [comment]
Intenresting enough I do not get the same result...

This is the full piece of code I am using step by step:

```
## 
## 1. Read data from request to set local variables to use in both cases: 
data = request.get_json()
    loginId = data.get('loginId')
    password = data.get('password')
    applicationId = data.get('applicationId')
    
    if not loginId or not password or not applicationId:
      return s_format_response(payload = {'message': 'Missing data'}, 
                                 status_code =  400)

  
## 
## 2. Code you shared before:  
    from fusionauth.fusionauth_client import FusionAuthClient
    client = FusionAuthClient("<MY_APY_KEY>",
                              'https://<MY_URL>')
    data = {
        'loginId': loginId,
        'password': password,
        'applicationId': applicationId
    }

    github_response = client.login(data)

## 
## Code using the api call directly:    
     url = current_app.suments.SETTINGS.get("FUSIONAUTH", "URL_LOGIN")
    data = {
        'loginId': loginId,
        'password': password,
        'applicationId': applicationId
    }
    headers = {
        'Content-Type': current_app.suments.SETTINGS.get("FUSIONAUTH", "URL_REQUEST_CONTENT_TYPE")
    }
    api_response = requests.post(url, json=data, headers=headers)
```

I have used the Flask Python debugger to print out the values:

```
print(api_response.status_code)
212
print(github_response.status)
401
```

I have noticed also that I get a 401 error code if I try to use `/api/user?email={email}`. I read it on https://fusionauth.io/docs/v1/tech/apis/users#retrieve-a-user

I wonder if there is any particular encoding / way to pass the variables? Maybe something I am using differently than you on my Python setup?

**Comment by JavierMoncayo** [comment]
Aaaaand I found the guilty guy on the API key permissions.... It did not have any "login->get" permissions. Got the clue to check from https://fusionauth.io/community/forum/topic/1442/error-401-depends-on-api-key-settings

Is it the expected behaviour?

-  But if I do send API key with restricted permissions, then do not read? (this condition seems more logical to me)
- If I do not send an API key, then read data

**Comment by robotdan** [comment]
If I understand your comment, yes if the API key does not have access to the `GET` method on the API you are calling, the expected result is a `401` w/out a response body. 

Closing. Please re-open if you think there is a still a bug in FusionAuth that is causing a behavior you do not expect.
