### ISSUE TITLE
Allow users to change passwords using the change password UI without needing to go through the forgot password flow

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#216]
### Problem
A user can change their password at anytime after login. However, there's no UI available do so on FusionAuth.

### Solution
How about making the `/password/change` form available without a reset code? Maybe pulling the username from the OAuth2 session and asking for old and new passwords?

If the user is logged in via SSO, then the user has an authentication session and the use could be prompted to enter their email, current password and new password. 

```
Email:             ________________
Current Password:  ________________
New Password:      ________________
Confirm:           ________________
```

The email and current password must match the user represented by the SSO session. 

Or if a JWT is provided a similar function could be used where the email must match the subject of the JWT, and the current password of course must also be known.

### Alternatives/workarounds
You can do it either with the forgot password flow or maintaining an UI to hook with the API.
None of 'em ideal, IMO.

### Related Issues
https://github.com/FusionAuth/fusionauth-issues/issues/508

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Great suggestion @AlvMF1 we've kicked this idea around a bit as well.

**Comment by robotdan** [comment]
Related https://github.com/FusionAuth/fusionauth-issues/issues/508

**Comment by robotdan** [comment]
This will likely be delivered as part of the "User Forms" support, related to https://github.com/FusionAuth/fusionauth-issues/issues/753.

**Comment by voidmain** [comment]
Is this complete? I think this is available in self-service, correct?

**Comment by mooreds** [comment]
Yes: https://fusionauth.io/docs/v1/tech/account-management/updating-user-data#update-user-password-user-facing

Closing.
