### ISSUE TITLE
Duplicate Application Email Template Tooltips

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2163]
### Description 
The tooltips for the following email templates under _Applications > Edit Application > Email_ are identical:
- Email update
- Login Id duplicate on create
- Login Id duplicate on update
- Two-factor method added
- Two-factor method removed

The tooltips are all displaying the message for the "Email update" template.

### Affects versions
1.44.0

### Steps to reproduce
1. Go to Applications
3. Select an Application to edit
4. Navigate to the "Email" tab
5. Compare tooltips for listed email templates

### Expected behavior
The tooltips should contain message for the related email template. Check tenant email template tooltips for correct verbiage and to ensure there are no duplicated tooltip messages there.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/229
