### ISSUE TITLE
post_logout_redirect_uri does not work with wildcard specified url

### ISSUE THREAD

**Issue by beezerk23** [FusionAuth/fusionauth-issues#2164]
### Description 
Since version 1.43.0 its possible to use wildcard urls in `Authorized redirect URLs` and `Authorized request origin URLs`. This works quite well except for the `post_logout_redirect_uri` parameter you can add to the /oauth2/logout url. I defined this in my `Authorized redirect URLs` config: http://*.example.com and set `post_logout_redirect_uri` to http://foo.example.com in my get request. However instead of redirecting me to http://foo.example.com it gives me this error:
```
{
  "error" : "invalid_request",
  "error_description" : "The post_logout_redirect_uri is invalid.",
  "error_reason" : "invalid_post_logout_redirect_uri"
}
```

### Affects versions
* 1.44.0

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2166
- https://github.com/FusionAuth/fusionauth-issues/issues/2185

### Expected behavior
Expected is the redirect after killing the session to http://foo.example.com

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/235
