### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'setValue' of null

### ISSUE THREAD

**Issue by jasondenney** [FusionAuth/fusionauth-issues#2168]
We are using an embedded web browser control within Unity in which we are hosting the login flow inside of, within the Authorize.js we have started receiving a javascript error.  When we use it with current modern browsers there is no error, the embedded unity web browser is based upon Chromium 74.0.3729.157.

Is there something with these input fields that wouldn't exist with the older browser causing the setValue to fail from null object?

```
  this.form = Prime.Document.queryFirst('form[action*="authorize"]');
  this.deviceName = this.form.queryFirst('input[name="metaData.device.name"]');
  this.deviceType = this.form.queryFirst('input[name="metaData.device.type"]');
  this.timezone = this.form.queryFirst('input[name="timezone"]');
  this.uvpaAvailable = this.form.queryFirst('input[name="userVerifyingPlatformAuthenticatorAvailable"]');
```

https://auth-internal.mythicalgames.com/js/oauth2/Authorize.js?version=1.41.3:37: Uncaught (in promise) TypeError: Cannot read property 'setValue' of null

**Comment by robotdan** [comment]
Thanks for the report. This issue has been resolved in version `1.42.0`. 

A work around is documented here:
- https://github.com/FusionAuth/fusionauth-issues/issues/1986#issuecomment-1337420353
