### ISSUE TITLE
SAMLv2 identity provider does not honor XML tag order in POST Binding mode

### ISSUE THREAD

**Issue by konvergence** [FusionAuth/fusionauth-issues#2169]
### Description 
When I use the SAMLv2 Identity Provider with the POST option for binding, 
the generated AuthnRequest does not respect XML Tag Order. 
(see http://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd)

### Affects versions
fusionauth 1.44.0

### Steps to reproduce
1. Create an Identity Provider SAMLv2, and enable Debug mod to see requests
2. choose `Use POST method` into the options
3. Associate an application to the Identity Provider
4. Make an SAML request

### Expected behavior
* use the System/Event Log to get the AuthnRequest (SAML v2 IdP AuthN Request Debug Log)

### How to check
* use https://www.samltool.com/validate_authn_req.php to validate the request

**Comment by konvergence** [comment]
A good  Binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST should respect the following order of tags:
```
<AuthnRequest>...
   <Issuer>...
   <Signature>...
   <NameIDPolicy>...
```

The bad request Binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST  generated by fusionauth is
```
<AuthnRequest>
   <Issuer>...
   <NameIDPolicy>...
   <Signature>...
```

**Comment by robotdan** [comment]
Thanks for the report @konvergence - we'll take a look at what is causing this behavior.

**Comment by konvergence** [comment]
Hi Dan
Do you have reproduce the issue ?

Regards

**Comment by konvergence** [comment]
Hi Dan,

Do you need more informations ?
Regards

**Comment by konvergence** [comment]
I found a resolve issue https://github.com/FusionAuth/fusionauth-issues/issues/2348
"Ensure a signed AuthN request always has the Signature element as the next sibling after the Issuer element"

I think that is the same issue no ?

**Comment by konvergence** [comment]
Hi,
I confirm that the order of tags is now correct.
a signed AuthN request always has the Signature element as the next sibling after the Issuer

But I still have an other is issue.
In POST Binding mode, the RelayState is optional.
Fusionauth still use RelayState in POST binding mode. But I will create a new issue for that.

Regards
