### ISSUE TITLE
API Key Authentication documentation very confusing

### ISSUE THREAD

**Issue by avwie** [FusionAuth/fusionauth-issues#2172]
Looking at https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys it implies that you need to use the GUID of the API-key, but that is not the case. You need to use the secret, not the identifier.

**Comment by mooreds** [comment]
Great, fixed under https://github.com/FusionAuth/fusionauth-site/pull/2051 and should be live in a few minutes.
