### ISSUE TITLE
Touch up React Native blog post

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2177]
### Description

Please update https://fusionauth.io/blog/2020/08/19/securing-react-native-with-oauth to make sure it works with current versions of React Native and FusionAuth.

See https://github.com/FusionAuth/fusionauth-site/blob/master/DocsDevREADME.md#blog-post-review-checklist for checklist for completion.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by ColinFrick** [comment]
I will start working on this issue.
