### ISSUE TITLE
Touch up Remix blog post

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2179]
### Description

Please update https://fusionauth.io/blog/2022/07/15/remix-demo to make sure it works with current versions of Remix and FusionAuth.

See https://github.com/FusionAuth/fusionauth-site/blob/master/DocsDevREADME.md#blog-post-review-checklist for checklist for completion.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by ColinFrick** [comment]
I will start working on this issue.

**Comment by ColinFrick** [comment]
There are some minor errors in the blog post. see https://github.com/FusionAuth/fusionauth-site/pull/2118

Additionally I have updated the Remix example repository: https://github.com/FusionAuth/fusionauth-example-remix/pull/1
