### ISSUE TITLE
Port Flask tutorial to docs

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2181]
Port https://fusionauth.io/blog/2020/09/10/building-profile-portal-with-flask-oauth-apis to the docs format, similar to https://fusionauth.io/docs/v1/tech/tutorials/integrate-java-spring

No need to create the user portal, just show how to integrate a flask app with FusionAuth using the authorization code grant.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
@mooreds is this covered by the new [python/flask quickstart](https://fusionauth.io/quickstarts/quickstart-python-flask-web)?

**Comment by mooreds** [comment]
Yup, closing this out.
