### ISSUE TITLE
bump deps

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2183]
### Description
bump deps

- [x] GraallJS `22.3.0` -> `22.3.1`
- [x] Elasticsearch client `7.10.2` -> `7.13.4`

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by trevorr** [comment]
@robotdan Could the Elasticsearch upgrade [break compatibility](https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/) with open source distributions or forks like AWS OpenSearch?

> OpenSearch aims to provide wire compatibility with open source distributions of Elasticsearch 7.10.2, the software from which it was derived. [...] Many developers who use Elasticsearch and OpenSearch in their applications also make use of the [open source client libraries maintained by Elastic](https://www.elastic.co/guide/en/elasticsearch/client/index.html), which provide convenient high-level interfaces for several popular programming languages. Over the past few weeks, Elastic added [new logic](https://github.com/elastic/elasticsearch-py/pull/1623) to several of these clients that rejects connections to OpenSearch clusters or to clusters running open source distributions of Elasticsearch 7, even those provided by Elastic themselves. While the client libraries remain open source, they now only let applications connect to Elastic’s commercial offerings.
