### ISSUE TITLE
OAuth2 Origin validation with wildcards

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2185]
### Description 
When validating the OAuth2 request origin with wildcards, a trailing `/` in either the configured value or the `Origin` header will trigger a mismatch unless the other value matches. The same is true for any mismatch in the path portion of the URI.

The validation for an exact match uses only scheme, host, and port number for validation. Trailing `/` or  path element does not trigger a validation error.

### Affects versions
1.43.0 and later

### Steps to reproduce
Reproducing this issue end-to-end in a live environment would require setting up proxy or DNS records to redirect values. The behavior was first observed when the redirect was performed via JavaScript.

The behavior can also be reproduced in a unit test with the following setup:
1. Create an application with OAuth2 configuration to Allow Wildcards for URL validation
2. Add a wildcard value to `authorizedOriginURLs`. `https://*.example.com`
3. Add a value to the application's `authorizedRedirectURLs` (without wildcard is fine)
4. Send a `GET /oauth2/authorize` request with `client_id`, `response_type`, and `redirect_uri` query string values. Include an `Origin` or `Referer` header that matches the pattern, but add a trailing `/` such as `https://auth.example.com/`
5. Response contains an `invalid_origin` error
6. Change the `authorizedOriginURLs` value to `https://auth.example.com` (without the trailing slash) to cause it to validate with exact match rules
7. No error on the response

### Expected behavior
The `Origin` header does not contain path information, so it seems that the path should not be validated for this case. That is the behavior for exact matches, and it follows that the same approach should be used when wildcards are present. The `Referer` header _may_ contain path information, but exact match validation strips the path in that case as well.

This should be confirmed against the OAuth2 spec to see how origin URLs are meant to be validated.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2164

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/235
