### ISSUE TITLE
Performance: Loading the IP location database into memory requires adequate heap

### ISSUE THREAD

**Issue by mmanes** [FusionAuth/fusionauth-issues#2195]
### Description
When running FA with ATD enabled against a MySQL database, the IP location database load process can cause MySQL's memory consumption to temporarily bloat 6GB over steady state usage. On minimally provisioned MySQL servers, this can cause an out-of-memory condition or DB restart.

### Workaround
Increase memory allocated to MySQL server.

### Possible changes
* Breakup the IP location database into smaller chunks, stored over many rows
* Stream database load from disk into MySQL
* Have each FA node load the database directly
* Use a different distribution method

### Notes

While MySQL and PostgreSQL may handle storing the binary object differently, if we can stream the file in, and out of the database, this should improve the performance regardless of which database you're using.

**Comment by robotdan** [comment]
Internal branch:
-  `*/stream-atm`

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/263

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/267
