### ISSUE TITLE
Office 365 as SMTP

### ISSUE THREAD

**Issue by JustSomeHack** [FusionAuth/fusionauth-issues#220]
## (Put bug title here)
Unable to send emails with Office 365 SMTP server

### Description 
Email is setup to use smtp.office365.com on port 587 and TLS enabled for security.

Error occurs. 

554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:0A007C85, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:531F0000, 1.36674:0E000000, 1.61250:00000000, 1.45378:581F0000, 1.44866:1A020000, 16.55847:7C100000, 17.43559:0000000004020000000000000000000000000000, 20.52176:140F19880000101066030000, 20.50032:140F1988701700000A00150C, 0.35180:6B030000, 255.23226:0A00D184, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A003086, 0.35250:0A005236, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:36000000, 1.36674:32000000, 1.61250:00000000, 1.45378:3B000000, 1.44866:02000000, 16.55847:A2000000, 17.43559:00000000E0020000000000000100000000000000, 20.52176:140F1988000070200A001C85, 20.50032:140F1988701710108E030000, 0.35180:0A00DE0E, 255.23226:0A002480, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:98030000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:9D030000, 0.38698:77090000, 0.37692:00000000, 0.37948:00000600, 5.33852:00000000534D545000363130, 4.56248:DC040000, 7.40748:010000000000010B30303A42, 7.57132:00000000000000003A616534, 1.63016:32000000, 4.39640:DC040000, 8.45434:3651201F7C4CC04B801F51DD17B54F0038006530, 5.10786:0000000031352E32302E323037332E3030303A424E38505232304D42323232373A61653463623064642D646631372D343339382D383835612D65653338616134346365303700503000000000, 255.1750:0A004067, 255.31418:CA030000, 0.22753:40000730, 255.21817:DC040000, 4.60547:DC040000, 0.21966:0A000130, 4.30158:DC040000 [Hostname=BN8PR20MB2227.namprd20.prod.outlook.com]

### Steps to reproduce
1. Do anything that requires an email being sent

### Expected behavior
Emails should be sent successfully.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Chrome 75

**Comment by robotdan** [comment]
What is the from email address in your template , and does that match the domain on your SMTP account?

**Comment by JustSomeHack** [comment]
It's no-reply@my-domain.com, it does match my domain.

**Comment by robotdan** [comment]
Is this the issuer? 
https://stackoverflow.com/questions/54784431/unable-to-send-smtp-mails-using-office365-settings

This indicates that your account (username and password used in the SMTP configuration) is not permitted to send emails for another user.

**Comment by JustSomeHack** [comment]
that was it.
