### ISSUE TITLE
Touch up Wordpress OIDC blog post

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2200]
### Description

Please update https://fusionauth.io/blog/2021/12/06/how-to-set-up-single-sign-on-between-fusionauth-wordpress to make sure it works with current versions of Wordpress and FusionAuth.

See https://github.com/FusionAuth/fusionauth-site/blob/master/DocsDevREADME.md#blog-post-review-checklist for checklist for completion.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by escii** [comment]
I'll start working on this today..
