### ISSUE TITLE
Add documentation on how to set up an express API

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2201]
## Add documentation on how to set up an express API

Create documentation on how to use FusionAuth's access tokens to protect an express API.

### Description

Content is similar to https://auth0.com/blog/add-authorization-to-sinatra-api-using-auth0/ 

* build an API
* configure an Application in FusionAuth
* have the user log in and have the access token sent to the browser as a cookie. Use an RS256 signed access token, not a symmetric signed access token.
* protect API requests by verifying the access token. make sure you validate the signature, audience and issuer. read the token from a cookie

Since this is new and not a refresh, please deliver this as documentation like https://fusionauth.io/docs/v1/tech/tutorials/integrate-ruby-rails not a a blog post. There are some fragments there that can be reused. Please use the typescript client library to configure the FusionAuth application.

You'll need to create an example express API.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by ColinFrick** [comment]
Just saw that there was a pull request created for this issue. https://github.com/FusionAuth/fusionauth-site/pull/2129

How to proceed?

**Comment by mooreds** [comment]
@ColinFrick sorry, the express.js Pr is not for an API, but rather for a web app.

Also, here's the outline for an API quickstart:

* Set up FusionAuth to set access token and refresh tokens as cookies using new hosted backend (full docs incoming, but you can see the PR here: https://github.com/FusionAuth/fusionauth-site/pull/2115
* Make sure jwt is signed with rs256 key
* Write standalone service which returns 401 if user doesn't present a correct access token.
* Service should return JSON if jwt is valid. Check signature using lib, not using validate endpoint. Also check audience, exp and issuer claims
* Small bit of js on the browser to call the API, if it gets a 401, should call the refresh endpoint.

**Comment by ColinFrick** [comment]
The default port of Express is `3000`, but the `setup.js` for typescript uses the default port `5173` of `Vite`.

Should I just define the API to use the port, or could we extend the setup.js with an environment variable for port?

**Comment by mooreds** [comment]
okay. For other tutorials, we created a separate setup script for each framework. See https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/python for example.
