### ISSUE TITLE
 Add documentation on how to use the angular SDK

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2202]
### Description

Similar to the react SDK blog post, write one for the angular SDK.

* Use the hosted back end (so this needs to wait until 1.45 is released)
* Use the angular SDK found at https://github.com/fusionauth/fusionauth-angular-sdk
* Have the app illustrate login and logout

Since this is new and not a refresh, please deliver this as documentation like https://fusionauth.io/docs/v1/tech/tutorials/integrate-ruby-rails not a a blog post. There are some fragments there that can be reused. Please use the typescript client library to configure the FusionAuth application.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Here's an example of using the react SDK: https://github.com/FusionAuth/fusionauth-site/pull/2132

I'd like the angular SDK doc to look similar. Don't think angular has a plugin.

**Comment by ColinFrick** [comment]
I'll start working on this.

**Comment by mooreds** [comment]
Closing under https://github.com/FusionAuth/fusionauth-site/pull/2327
