### ISSUE TITLE
Consider if the Self-Service pages should send verification emails on user email change.

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2210]
### Problem
0. Prerequisite - I have email verification enabled on the tenant.
1. When I change an email address on the self-service account management pages, my user is not sent an email verification code/communication.  
2. Additionally, the email they change to is automatically verified.

### Solution
if the user updates their email address, we should optionally require re-verification of the email address and send emails to this effect.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/241
