### ISSUE TITLE
Documentation Project - Expert Advice migration

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2211]
### Description
We are updating and migrating our online docs to be better aligned with our users' needs, and are simultaneously refreshing the design and moving to a more flexible tech stack.

- [x] Migrate Quickstarts landing page to Astro ([current page](https://fusionauth.io/docs/quickstarts/), keep layout and design)
- [x] Implement Expert Advice landing ([current page](https://fusionauth.io/learn/expert-advice/))
- [x] Implement Expert Advice section landing pages (see list below, [example of current page](https://fusionauth.io/learn/expert-advice/authentication/))
- [x] Implement the Article layout ([example of current page](https://fusionauth.io/learn/expert-advice/authentication/login-authentication-workflows)
- [x] Migrate article pages (see list below)
- [x] Build a github action for compiling the site

#### Expert Advice Section Landing Pages
- [x] Authentication
- [x] CIAM
- [x] Gaming and Entertainment
- [x] Identity Basics
- [x] OAuth
- [x] Security
- [x] Tokens
- [x] Dev Tools

#### Expert Advice Articles
These are the sections. Migrate all articles for each section.

Internal: you can find a list of existing articles and their URLs in [the doc rework spreadsheet](https://docs.google.com/spreadsheets/d/1ZiUs1c96oMNIywDBBdzM950-R1lC_SIb77v493SO8BU/edit#gid=707438702)
- [x] Authentication
- [x] CIAM
- [x] Gaming and Entertainment
- [x] Identity Basics
- [x] OAuth
- [x] Security
- [x] Tokens
- [x] Dev Tools

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
I wrote a script to help migrate expert advice articles: https://github.com/FusionAuth/fusionauth-site/blob/mooreds/modern-guide-to-oauth-port/src/migrate-advice-astro.sh if that is helpful.

**Comment by SeanBobby** [comment]
I've been heads down working in Tailwind/Pinegrow to wrap my head around the application, etc. I'll have UI mockups and and live samples to share on Wednesday with the team (Expert Advice).

**Comment by mooreds** [comment]
Closing, this is all done.
