### ISSUE TITLE
Backward incompatibility issue in fusionauth-java-client Tenant object

### ISSUE THREAD

**Issue by yuriy-maftiyak-verint** [FusionAuth/fusionauth-issues#2220]
### Description 
Between `1.36.0` and `1.44.0` in FusionAuth REST API it was added a bunch of new webhook event types (related to the group's feature for example). Event types for webhooks in the FusionAuth java client library are defined as Java enum `io.fusionauth.domain.event.EventType`.
When a `1.36.0` java client tries to deserialize tenant JSON into Java objects, it may fail (when calling FusionAuth API of the newer version) because the `1.36.0` client has not defined the newer event types in java enum.

### Affects versions
`1.44.0`

### Steps to reproduce
1. Enable all webhook events related to groups on tenant in the FusionAuth server of the `1.44.0` version
2. Try to retrieve tenant (`fusionAuthClient.retrieveTenant(tenantId)`) using java client of the `1.36.0` version.
3. See the exception:
```
com.inversoft.rest.JSONException: Failed to parse the HTTP response as JSON. Actual HTTP response body:
Note: Output has been truncated to the first 1024 of 8000 bytes.

{"tenant":{"accessControlConfiguration":{},"captchaConfiguration":{"captchaMethod":"GoogleRecaptchaV3","enabled":false,"threshold":0.5},"configured":true,"data":{},"emailConfiguration":{"additionalHeaders":[],"debug":false,"defaultFromEmail":"SECRET","defaultFromName":"SECRET","emailUpdateEmailTemplateId":"SECRET","forgotPasswordEmailTemplateId":"SECRET","host":"SECRET","implicitEmailVerificationAllowed":false,"password":"SECRET","port":587,"security":"TLS","setPasswordEmailTemplateId":"SECRET","unverified":{"allowEmailChangeWhenGated":false,"behavior":"Allow"},"username":"SECRET","verificationStrategy":"ClickableLink","verifyEmail":false,"verifyEmailWhenChanged":false},"eventConfig
```

### Expected behavior
No exceptions are thrown.

### Screenshots
na

### Platform
na

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
na

**Comment by robotdan** [comment]
Unfortunately this is a limitation of how we are using enums in the Java client. It is always recommended to use a client library that matches the version of FusionAuth you're running.
