### ISSUE TITLE
Wildcard for authorized origin URLs gives invalid origin error

### ISSUE THREAD

**Issue by beezerk23** [FusionAuth/fusionauth-issues#2227]
##Wildcard for authorized origin URLs gives invalid origin error

### Description 
I think the latest update may have broke something regarding the wildcard for authorized origin urls. When i have `https://*.example.com` in my authorized origin urls, a request from `https://foo.example.com` produces this: 
`Invalid origin uri https://foo.example.com/`

I know that there is a trailing slash in the origin uri but i think this should not affect this.

However if i add the full domain to the authorized origin urls it will work and does not produce any error.

### Affects versions
1.45.1

### Steps to reproduce
Should be clear from the description.

### Expected behavior
That the wildcard works as expected. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/425
- https://github.com/FusionAuth/fusionauth-issues/issues/437
- https://github.com/FusionAuth/fusionauth-issues/issues/2164
- https://github.com/FusionAuth/fusionauth-issues/issues/2166
- https://github.com/FusionAuth/fusionauth-issues/issues/2185

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/238

**Comment by robotdan** [comment]
Thanks for letting us know @beezerk23  - this is most likely occuring on a `GET` request to FusionAuth. In this case we fall back to the `Referer` header if the `Origin` is not present. 

When using wild cards we take the entire value for matching, so we need to remove any path or query parameters from this value before validating.

**Comment by beezerk23** [comment]
Hey @robotdan, can you give me any inside on when this is going to be released?

**Comment by robotdan** [comment]
Sorry for the delay, this is available in an early build, now, and the full release is coming today or tomorrow.

**Comment by robotdan** [comment]
@beezerk23 thanks for your patience. Fix is available in 14.6.0.
