### ISSUE TITLE
How to setup domain and HTTPS for Fusionauth dashboard

### ISSUE THREAD

**Issue by leksa** [FusionAuth/fusionauth-issues#223]
### Description
Hello all, 
I have a simple question about domain setting and https/ssl configuration for FusionAuth. I've read in the documentation and security preference from the blog. FusionAuth is better if works as IAM backend system behind proxy or local network access for front-end apps. 

But is it possible for development purpose, if we setup the direct domain to FusionAuth install? In our scenario we didn't need Fusionauth behind our API gateway host. Just need a direct domain in public access with https enabled. I didn't find any suggestion in documentation for this procedure, except setting domain in the SETTING > SYSTEM - GENERAL.

Thank you for any answer on this question. Really appreciate.

**Comment by robotdan** [comment]
Thanks for the question @leksa - this is not something that is configured directly in FusionAuth. 

Instead you will want to install an SSL certificate in Apache, nginx or your preferred web server to provide a secure connection to your system.  Then you can proxy `https` on port `443` to FusionAuth on port `9011`. 

The easiest way to do this is with Let's Encrypt w/ Certbot.
https://letsencrypt.org/getting-started/
https://certbot.eff.org/

Once you follow the install instructions on CertBot you'll run the command to install and configure the certificate, for example the following commands will prompt you based upon your server configuration and complete the setup.

```
sudo certbot --apache
```

or 

```
sudo certbot --nginx
```

**Comment by leksa** [comment]
Thank you for the respons @robotdan. 
We will use this suggestion.
