### ISSUE TITLE
Consider Default ES mappings for improved sorting 

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2236]
### Problem
Currently, we are using a `text` field mapping for user fields such as `fullName` and then specifying that they should be searchable via `fielddata: true`.   This strategy works for some searching, but accurate sorting will fail.

More specifically, using a `text` field means that a user is not able to complete an Exact Match type of search on a field value. 

### Solution

Consider our user index and how we are building the schema.  Consider adding multi-analyers for certain fields; especially those that will be sorting.  In other words, allow the user to search using a text field mapping or define additional field mappings for improved search results in certain circumstances.

### References
- https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-fields.html#_multi_fields_with_multiple_analyzers

### Internal
- Zendesk Ticket 2236

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/712
- https://github.com/FusionAuth/fusionauth-issues/issues/1640
- https://github.com/FusionAuth/fusionauth-issues/issues/1639

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Please add more detail to describe what doesn't work so we can decide how to address the problem.

**Comment by jobannon** [comment]
This ticket is related to the conversation on this ticket 
- https://github.com/FusionAuth/fusionauth-issues/issues/712

**Comment by robotdan** [comment]
Can we close this as a duplicate if all of the detail is in the other ticket? Or is there something specific here that is different? 

If we want to keep this issue open, please provide some use cases of things that don't work how you want, and the desired results so we have some additional detail to evaluate.

**Comment by jobannon** [comment]
Closing this as this ticket echos already open tickets.
