### ISSUE TITLE
invisible reCaptcha v2 w/ CAPTCHA fallback

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2237]
### Description
This essentially already works with Google reCAPTCHA, but it may not be obvious how to make it work with our stock theme. 

### How to enable invisible captcha prior to 1.46.0

See [Google's documentation](https://developers.google.com/recaptcha/docs/invisible) for more information.

Prerequisite:
- You must have a custom theme defined and in use for the tenant.
- You must have enabled Google reCAPTCHA v2 [see tenant settings](https://fusionauth.io/docs/v1/tech/core-concepts/tenants#captcha-settings)

Steps
1. In the Admin UI go to Customizations > Themes and select `Edit` for your custom theme.
2. Open the template for `Helpers`
3. Find the template macro `captchaScripts` (likely near the bottom).
4. Find and either comment out or delete the following tags:

```html
<script src="${request.contextPath}/js/oauth2/Captcha.js?version=${version}"></script>
<script data-captcha-method="${captchaMethod!''}" data-site-key="${siteKey!''}">
    Prime.Document.onReady(function() {
        new FusionAuth.OAuth2.Captcha();
    });
</script>
```
5. and replace them with the following:

```html
<script>
      Prime.Document.onReady(function() {
          function formSubmit(event) {
            Prime.Utils.stopEvent(event);
            grecaptcha.execute();
          }
          Prime.Document.query('input[name="captcha_token"]').each(function(input) {
            input.queryUp('form').addEventListener('submit', formSubmit);
          }.bind(this));
      });
      
      function reCaptchaV2InvisibleCallback(token) {
        const input = document.querySelector('input[name="captcha_token"]');
        input.value = token;
        input.closest('form').submit();
      }
</script>
```
6. Find the template `captchaBadge`
7. Find and either comment out or delete the following tag:

```html
[#if captchaMethod == "GoogleRecaptchaV2"]
      <div class="g-recaptcha" data-sitekey="${siteKey!''}"></div>
...
```
8. And replace with the following

```html
[#if captchaMethod == "GoogleRecaptchaV2"]
      <div class="g-recaptcha" data-sitekey="${siteKey!''}"
        data-size="invisible"
        data-callback="reCaptchaV2InvisibleCallback"
      ></div>
...
```

Now on form submit Google reCAPTCHA should be triggered even though no element was visible on the page.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1507
- https://github.com/FusionAuth/fusionauth-issues/issues/1887
- https://github.com/FusionAuth/fusionauth-issues/issues/2120
- https://github.com/FusionAuth/fusionauth-issues/issues/2246

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/243

**Comment by lyleschemmerling** [comment]
Updated the description with workaround instructions
