### ISSUE TITLE
Edit demo video

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2241]
### Description

We have a demo video. Need to edit it down.

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by escii** [comment]
Video edited: https://drive.google.com/file/d/1FfhRWfuh5jmIgIHXSWBEHO8kcfBCPPy0

**Comment by mooreds** [comment]
@escii can you please remove/blur out the label in gmail?

<img width="372" alt="Screenshot 2023-05-08 at 11 07 11 AM" src="https://user-images.githubusercontent.com/91825/236890811-9e4cecf8-b97b-42d7-a5b1-2c5bd264d3c6.png">

Other than that, looks good.

**Comment by mooreds** [comment]
Looks great, closing this issue out as I'm uploading as we speak.
