### ISSUE TITLE
Missing State Wordpress error

### ISSUE THREAD

**Issue by kitkan87** [FusionAuth/fusionauth-issues#225]
Missing State Wordpress Error

I am using OpenID Connect Client plugin for wordpress. The error I get is this.

I have no idea what is missing. All I can figure out is string(14) is missing a state.

```
object(WP_Error)#844 (2) {
  ["errors"]=>
  array(1) {
    ["missing-state"]=>
    array(1) {
      [0]=>
      string(14) "Missing state."
    }
  }
  ["error_data"]=>
  array(1) {
    ["missing-state"]=>
    array(4) {
      ["action"]=>
      string(24) "openid-connect-authorize"
      ["code"]=>
      string(43) "bICUAwWUm5jEs2VBG5xK1p409j2okpalfas7YvrLc9c"
      ["state"]=>
      string(32) "caed3c1d80c604ede2127250df9e6604"
      ["userState"]=>
      string(13) "Authenticated"
    }
  }
}
```

![Screenshot (388)](https://user-images.githubusercontent.com/27042110/61415237-0ae26900-a8e8-11e9-83bb-aaac54a6d0b2.jpg)
![Screenshot (389)](https://user-images.githubusercontent.com/27042110/61415243-0ddd5980-a8e8-11e9-8861-8235363250c0.jpg)
![Screenshot (390)](https://user-images.githubusercontent.com/27042110/61415246-103fb380-a8e8-11e9-908c-c730da9a8e67.jpg)

Any help would be appreciated.

**Comment by robotdan** [comment]
Which WP plugin are you using? We can try to recreate.

**Comment by robotdan** [comment]
Same issue as https://github.com/daggerhart/openid-connect-generic/issues/90 ? 

If this is the plugin you're using, I can try to debug.

**Comment by kitkan87** [comment]
Thanks for the tip. I can't believe I missed the thread in[ daggerhard/openid-connect-generic#90](https://github.com/daggerhart/openid-connect-generic/issues/90). I've managed to fix it. I'll post a writeup in #90 on how I fixed it.

**Comment by robotdan** [comment]
Great, thanks for the update @kitkan87 glad you've got it working now. 

For anyone else that encounters this issue @kitkan87 describes the fix in this comment https://github.com/daggerhart/openid-connect-generic/issues/90#issuecomment-512694947.
