### ISSUE TITLE
Integrate Zendesk Help Center into account app support

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2255]
The account app gives a user the ability to create a support ticket, but thereafter support interaction for that ticket occurs over email (for the user, not the agent). We are going to start using Zendesk Help Center (HC), which provides a web interface for creating and interacting with support tickets.

There are two improvements we're making as part of this effort

## Wire Help Center to the Account app
- [x] Have the `Open a support ticket` buttons in the account app open Zendesk HC to a ticket creation page, rather than opening an in-app modal. The user needs to be taken to `https://fusionauth.zendesk.com/hc/en-us/requests/new`
- [x] See if we can send Company and Plan values as parameters, so that they are pre-populated in the new ticket form
- [x] On the support page, add a `Vew support tickets` button that opens Zendesk HC to the `My requests` view. This view is at `https://fusionauth.zendesk.com/hc/en-us/requests`

## Automate addition of Zendesk user metadata
When a user clicks one of the support buttons, we want to take the opportunity to create a Zendesk organization if the user's company doesn't already exist in Zendesk as an organization, and associate the user with the organization. Doing this allows users to see all of the tickets created by people in their company.
- [x] Use the Zendesk organization API to search for an organization with an `external_id` that matches the user's company id
- [x] If the company doesn't exist in Zendesk as an organization, create it, using an `external_id` value of the entity id for the user's company in FusionAuth
- [x] If the organization already existed, use Zendesk's organization memberships API to search for the current user in that organization
- [x] If the user doesn't exist in the organization, either because the organization was just created or there is no organization membership record for the user, create an organization membership record using the API, linking the user to the organization

## Help Center theming and configuration
Verify that the following are correct with respect to our brand guidelines
- [x] Colors
- [x] Images
- [x] See if we can enable markdown instead of or in addition to rich text editing

## Documentation
- [x] https://fusionauth.io/docs/v1/tech/admin-guide/account-portal#support
- [x] https://fusionauth.io/docs/v1/tech/admin-guide/technical-support

## Relevant Zendesk APIs
* Organizations API: https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/
* Organization Memberships API: https://developer.zendesk.com/api-reference/ticketing/organizations/organization_memberships/

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/account.fusionauth.io/pull/109
