### ISSUE TITLE
Follow on video edits

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2256]
### Description

Can you please take the demo video you edited and break out the following parts:

* the login process (webauthn, google social login, magic link)
* webauthn login
* magic link login
* the lambdas
* tenants
* advanced threat detection
* applications
* users

At the end, we'll end up with 8 videos.

We can use each of these on our documentation website. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Initial video work: https://github.com/FusionAuth/fusionauth-issues/issues/2241

**Comment by escii** [comment]
I'll start working on this.

**Comment by Aaron-Ritter** [comment]
@mooreds can we close this as its not up to the standard of the recording guide?

**Comment by mooreds** [comment]
Yes, let's close this out.
