### ISSUE TITLE
FusionAuth internal webhook receives a 401 error on multi-node clusters

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2257]
### Description 
Internal webhook calls are failing when posting a `JWTRefreshTokenRevoke` event to a multi-node cluster. The errors are present in the Event Log with the message:

```
Webhook [HTTP://<IP_ADDRESS>:9011/internal/webhook] returned response code [401] when sending [JWTRefreshTokenRevoke] event with Id [<ID>] Response: null 
```

this will only affect multi-node clusters as the call to localhost for the webhook will always success.

Because there is at least one node handling the event and this only applies to tokens in the FusionAuth admin app this is mostly benign, albeit noisy in the logs.

### Affects versions
>= 1.43.0 

### Steps to reproduce
1. On a multi-node cluster revoke the JWT for a user logged in to the FusionAuth admin app
2. A event should show in the event logs with the message for a 401 on the webhook

### Expected behavior
Nothing in the logs

### Platform
(Please complete the following information)
 - FusionAuth >= 1.43.0

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/246
