### ISSUE TITLE
OIDC discovery well known endpoint has the tenant id suffix

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2259]
### Description

The open id connect discovery URL has a tenant Id on the end of it. For example: `https://sandbox.fusionauth.io/.well-known/openid-configuration/bafb4319-b7ca-ed27-fa2f-bbdba9d8ec06`

This sometimes causes issue with OIDC discovery. See here: https://github.com/oauth2-proxy/oauth2-proxy/issues/2102 for example.

Looks like AzureAD works around that by putting the tenant value before the .well/known path: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-configuration-document

> Every app registration in Azure AD is provided a publicly accessible endpoint that serves its OpenID configuration document. To determine the URI of the configuration document's endpoint for your app, append the well-known OpenID configuration path to your app registration's authority URL.

Section 4 of the OIDC spec talks about how to craft that URL: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

>  Using path components enables supporting multiple issuers per host. This is required in some multi-tenant hosting configurations. This use of .well-known is for supporting multiple issuers per host; unlike its use in [RFC 5785](https://openid.net/specs/openid-connect-discovery-1_0.html#RFC5785) [RFC5785], it does not provide general information about the host.

### Documentation
- [x] Update endpoint doc to indicate this new option. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
To do this in a backwards compatible manner, we could make this file available at both 

* https://sandbox.fusionauth.io/.well-known/openid-configuration/bafb4319-b7ca-ed27-fa2f-bbdba9d8ec06
* https://sandbox.fusionauth.io/bafb4319-b7ca-ed27-fa2f-bbdba9d8ec06/.well-known/openid-configuration
* and possibly even https://sandbox.fusionauth.io/.well-known/openid-configuration for the common case with one tenant.

**Comment by robotdan** [comment]
Was thinking we had an open issue for this, but I couldn't find it. 

We have wanted to do this for a while, it is currently a limitation in the MVC. There are probably some ways to hack this if we wanted to ship something earlier. 

To do it correctly, we have to support a URI prefix concept such that we can strip off the first segment which is `bafb4319-b7ca-ed27-fa2f-bbdba9d8ec06` and then perform the normal action mapping.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/262

**Comment by robotdan** [comment]
@mooreds I figured out a ~hack~ solution - for now to help wit this integration step. Thanks @voidmain for the assist.

**Comment by mooreds** [comment]
@robotdan 

Don't we need to update https://fusionauth.io/docs/v1/tech/oauth/endpoints#openid-configuration to include the tenant id prefix? I see that 'checked off' above, but not actually done yet? What am I missing?

**Comment by mooreds** [comment]
Also, the endpoint isn't updated in the 'view details' screen for an application.

**Comment by robotdan** [comment]
The view dialog will be fixed in the next release.

**Comment by mooreds** [comment]
@robotdan I created a separate issue for the view dialog: https://github.com/FusionAuth/fusionauth-issues/issues/2333
