### ISSUE TITLE
Validation not rendered on key import of a duplicate key

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2261]
### Description 
FusionAuth returns a 500 error on a duplicate key import.  I would expect that FusionAuth should return a validation error indicating that the key has already been imported.  Instead, we returned a 500 unexpected error in the UI and the logs. 

Seen in the wild, without repro steps.  Logging for posterity.

Internal - https://inversoft.slack.com/archives/C03DQDX1SCE/p1683741238749539

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
I just tried to replicate this with a keypair generated like so:

```
openssl genrsa -out key.pem 2048
openssl rsa -in key.pem -outform PEM -pubout -out public.pem
```

And was able to use the UI to import this RSA key twice. Had to have a different name, but no other issues.

Porbably worth digging into more details about the type of key, etc.

**Comment by robotdan** [comment]
@jobannon please update with specific recreate steps, and a stack trace.

**Comment by jobannon** [comment]
Seen in the wild only.  Closing as have no repro steps.

**Comment by robotdan** [comment]
Updated the tag. @jobannon when closing as un-repro, please update the tag.
