### ISSUE TITLE
Retrieve a single Public Key by Key Identifier always returns list of all public keys.

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#227]
### Description 
According to the documentation (https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-public-keys)
'Retrieve a single Public Key by Key Identifier'  =>  GET /api/jwt/public-key?kid={kid}

Despite setting a kid in the url parameter,  the endpoint always returns all keys.

### Steps to reproduce
1. Go to 'https://account.trustmaster.org/api/jwt/public-key'
2. See the presented list of public keys,  grab a keyid
3. try request a single key : 'https://account.trustmaster.org/api/jwt/public-key?kid={{keyid}}'
4. See the result, which should be 1 public key, but shows the complete list.

### Expected behavior
A single public key should be returned.

**Comment by robotdan** [comment]
Thanks for letting us know @botnyx - there is a version flag on this API for 1.8.0 which is not yet released. 

For now you can retrieve all of them and then select the key you want using a `kid`.
