### ISSUE TITLE
Java/Spring API integration tutorial and example app

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2270]
We need to produce a Java / Spring API integration tutorial and example app.

API Guide: https://github.com/FusionAuth/fusionauth-site/blob/master/DocsDevREADME.md#apis

**Comment by mooreds** [comment]
This is done: https://fusionauth.io/docs/v1/tech/tutorials/integrate-java-spring

**Comment by mooreds** [comment]
Whoops, this is not done, I was thinking of the wrong thing.

**Comment by andrewpai** [comment]
This was completed as part of the new quickstarts work: https://fusionauth.io/docs/quickstarts/quickstart-springboot-api
