### ISSUE TITLE
Add a feature to check the validity and expiry of `changePasswordId` through an API

### ISSUE THREAD

**Issue by emilychuah** [FusionAuth/fusionauth-issues#2276]
### Problem
Currently, there isn't a way to check the validity and expiry of the `changePasswordId` through an API. The only way for us to know whether it is invalid or expired is through the 404 response when hitting POST /api/user/change-password. However, this will be frustrating to the user as we hit that API only after the user submits a change password request. 

### Solution
It'd be great if FusionAuth could add a feature to check the validity and expiry of `changePasswordId` through an API to improve the forgot password workflow.

**Comment by benkloester** [comment]
Someone else raised this same problem on the forums way back in 2020 https://fusionauth.io/community/forum/topic/244/check-password-reset-link-expiry-or-not?lang=en-GB

As Emily mentioned, the current flow creates a bad user experience, since the user finds out they can't change their password only _after_ they've gone to the effort of coming up with a password that meets requirements and submitting it.

**Comment by jobannon** [comment]
@emilychuah @benkloester  This is currently a gap in our documentation that we can address, but it is possible to do as you describe.  

See this issue for the suggested procedure.

https://github.com/FusionAuth/fusionauth-site/issues/2010

This call will confirm if the `changepasswordId` is valid

```
GET /api/user/change-password/{changePasswordId}
```

I hope this helps!  Thanks!

**Comment by emilychuah** [comment]
Hi @jobannon,

Thank you, that'd help with checking the validity of `changePasswordId`. However, we would also need to check if the `changePasswordId` is expired (based on the document [here](https://fusionauth.io/docs/v1/tech/apis/users#change-a-users-password:~:text=The%20User%20could%20not%20be%20found%20using%20the%20changePasswordId%20or%20loginId%20value%20from%20the%20request.%20If%20using%20the%20changePasswordId%20the%20id%20is%20either%20incorrect%20or%20expired.)) to show the user that the password reset link is expired before showing them the page to change their password. Is there a way to check its expiry too?

**Comment by robotdan** [comment]
The API @jobannon mentioned will only return `200` if the value is not expired.

**Comment by robotdan** [comment]
Please re-open if you find the API does not work for you.
