### ISSUE TITLE
Article migration todos

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2278]
- [x] Search is not showing article titles, just matched text
- [x] Mobile - on mobile there is a breadcrumb nav showing One >> Two. Clicking on it either One or Two makes the left nav appear but I am unable to scroll up and down on it. Part of the categories are blocked by the logo/nav/menu.
- [x] [ux/design] Should there be a footer? Or a CTA to join the community forum or slack group? Or back and forward buttons to jump between the content?
- [x] `npm audit` shows 1 high severity vulnerability: Uncaught Exception in yaml - https://github.com/advisories/GHSA-f9xv-q969-pqx4
- [x] I see `The language "golang" doesn't exist, falling back to plaintext.` in the astro server error log when I go to http://localhost:3000/articles/tokens/tokens-microservices-boundaries
- [x] I see `The language "config" doesn't exist, falling back to plaintext.` and other messages in the astro server error log when I go to http://localhost:3000/articles/security/guide-to-user-data-security
- [x] I see an error `{:.tight}` near `What does all this math mean?` on http://localhost:3000/articles/security/math-of-password-hashing-algorithms-entropy
- [x] in astro.config.js, the site is still `'https://webauthn.wtf'`
- [x] [Dan] Convert the `Login & Authentication Workflow Articles` landing page to an internal page, remove the article links, and give `Login & Authentication Workflow Articles` a standard clickable card section landing page ( https://github.com/FusionAuth/fusionauth-site/pull/2187 )
- [x] [Dan] The article list at the bottom of the left-hand nav looks incorrect in the `Login & Authentication Workflow Articles` section 
- [x] [ux/design] I know we are all on macs, but what about those that aren't? In the search box we have a Mac specific ⌘K icon to indicate that the user can type that to have the search bar pop-up. That might be confusing to those not on Macs. See screenshot attached
- [x] When the search box pop-ups, I couldn't get out of it initially.  I had to refresh the page to get it to close/not appear. I expected to click off the window and it close.
- [x] Need redirects from all current expert advice urls
- [x] [Emily] Need SEO url/structure fixes
- [x] CTA says 'download and install FusionAuth' but takes user to the /pricing page.
- [x] [Vinicius] We don't have a 'copy' link. Compare the token under the heading `Security considerations` here: https://fusionauth.io/learn/expert-advice/tokens/building-a-secure-jwt with the token here: http://localhost:3000/articles/tokens/building-a-secure-jwt (FusionAuth/fusionauth-site#2201)
- [x] There are two identical token articles: `Components of JWTs Explained` and `Components of JWT Tokens Explained`
- [x] on http://localhost:3000/articles/tokens/pros-and-cons-of-jwts the mobile device in the first image is hidden in dark mode.
- [x] This quote looks weird `Prediction is very difficult, especially if it’s about the future. - Niehls Bohr` on http://localhost:3000/articles/oauth/differences-between-oauth-2-oauth-2-1 (the end quote is after `Bohr`)
- [x] The quote starting with `On Although the artifacts` on http://localhost:3000/articles/oauth/differences-between-oauth-2-oauth-2-1 has two quotes at the beginning and two at the end.
- [x] The h5 here: http://localhost:3000/articles/oauth/modern-guide-to-oauth titled `The Introspect endpoint`, doesn't look different than the surrounding text.
- [x] Looks like there are quotes here: `Please don’t use the Implicit grant.` but this isn't a quote: http://localhost:3000/articles/oauth/modern-guide-to-oauth Maybe the modern guide is using the wrong markup?

# SEO Edits
## Title and description are combined in the `title` tag
The new page titles appear to be combining the meta description and page title together. Separate these into <title> and <meta> tags.

### Example pages
Old: https://fusionauth.io/learn/expert-advice/authentication/developer-benefits-single-sign-on
New: https://fusionauth.dev/articles/authentication/developer-benefits-single-sign-on

The old page has `title` and `meta` tags in the head
```
<title>The Developer Benefits of Single Sign-On - FusionAuth</title>
<meta name="description" content="What is Single Sign-On and how can it help developers build successful applications?">
```

whereas the new page has a `title` tag with combined content
```
<title>The Developer Benefits of Single Sign-On - What is Single Sign-On and how can it help developers build successful applications?</title>
```
## Missing OG tags
We need to add the OG tags back in. e.g. from https://fusionauth.io/learn/expert-advice/authentication/developer-benefits-single-sign-on
```
<meta property="og:site_name" content="FusionAuth">
<meta property="og:url" content="https://fusionauth.io/learn/expert-advice/authentication/developer-benefits-single-sign-on">
<meta property="og:description" content="What is Single Sign-On and how can it help developers build successful applications?">
<meta  name="og:title" content="The Developer Benefits of Single Sign-On">
<meta property="og:type" content="website">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="https://fusionauth.io/assets/img/advice/developer-benefits-sso/developer-benefits-sso.png">
```

**Comment by vcampitelli** [comment]
Some of the language icons in the Quickstarts page don't look good in dark themes due to lack of contrast:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/1877191/4747cbc4-9315-4271-946d-67c31ab668d8)

I have two suggestions:

1. Add a CSS class to these icons (e.g. `dark-contrast`) to add a `filter: invert(1);` or something (see Express and Wordpress icons)
2. Replace `opacity-40` class with `light:opacity-40` that only adds `opacity: 0.4` when using light theme in some cases (see PHP icon)
3. 
![image](https://github.com/FusionAuth/fusionauth-issues/assets/1877191/09916483-5d95-4116-b2d8-e6a5479f0f48)

**Comment by andrewpai** [comment]
All outstanding tasks complete.
