### ISSUE TITLE
Documentation error on family APIs

### ISSUE THREAD

**Issue by ericher4worximity** [FusionAuth/fusionauth-issues#228]
(Error on the family api documentation)

Description

According to the documentation - see https://fusionauth.io/docs/v1/tech/apis/families - the api paths to the 4 actions (add user to family, retrieve a family, update a family and remove a user from a family) is wrong. We should read `/api/user/family` instead of `/api/family`

**Comment by robotdan** [comment]
Hi @ericher4worximity thanks for pointing out this error. It will be fixed shortly!

**Comment by ericher4worximity** [comment]
I'm happy to help!
