### ISSUE TITLE
`user.reactivate` Webhook is not Transactional

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2281]
### Description 
The `user.reactivate` webhook event is documented as being transactional, but the user reactivation is committed even when the webhook fails.

### Affects versions
1.0.13+

### Steps to reproduce
1. Define and apply a webhook for the `user.reactivate` event and set the the transaction type to something other than `None`
2. Set up the webhook to return a failed status code
3. Deactivate and then reactivate the user
4. The user is reactivated even though the transactional webhook should have failed the update

### Expected behavior
A user's `active` status should not be updated when a transactional webhook fails.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/254
