### ISSUE TITLE
Allow Saved Request to Replay after External Redirect

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2282]
### Problem
A saved request is not replayed after SSO login when the original request came from a redirect from another domain.

### Steps to Reproduce
1. Create two applications with SSO enabled
2. Enable self-service account on the second application
3. Sign in to the first application to create SSO cookie
4. Navigate to another domain (e.g. google.com)
5. Use JavaScript console to set `window.location.href` to perform a redirect to the second application's account management portal (e.g. `/account/edit`) with custom query string parameters
6. Observe that at the end of the OAuth flow to sign in using the SSO cookie, the user is redirected to account management index (`/account/`) _without_ the custom query string parameters

### Solution
~* Change the saved request cookie to `SameSite=Lax` instead of `SameSite=Strict`.~
~* Optionally make this behavior configurable rather than changing the value~

Update the login workflow for `/account` to handle `SameSite=Strict` cookies.

### Additional context
Before implementing this change, review for potential security impacts.

I confirmed that the cookie is not available on the second request to `/account/login` (where the authorization code is exchanged for a token) when `SameSite=Strict`, but it is available when `SameSite=Lax`.

The `Referer` header is passed all the way through the redirect chain. Tested in Chrome.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
It is possible the way we are using this cookie affects which parameters are re-constructed. Perhaps we need to pass this cookie through our meta refresh as well. 

As far as I know we do want to keep the `SameSite` attribute as is, FusionAuth should be writing the cookie, so we should be able to read it. If there is a workflow where we are unable to read this cookie due to the `SameSite` attribute, we may change the path in which we read it to ensure the browser sends the cookie correctly without changing the `SameSite` attribute. 

We can review this behavior for `/admin` and `/account` to see if the same behavior exists in both applications based upon how this cookie is configured.

**Comment by spwitt** [comment]
The cookie contains the parameters and will include them when the saved request is replayed.

This particular issue is a quirk of the SSO flow. When the user first lands on the FusionAuth domain, it is the result of a 302 redirect. The entire OAuth process in this case is a series of redirects. The user is not required to enter their credentials, and the `/oauth2/authorize` page does another 302 because it is able to authenticate the user with the SSO cookie.

Because the _entire_ chain is a series of 302s, the `Referer` header from the original request to FusionAuth is carried through to the end where it would normally read the saved request cookie. The presence of the `Referer` header means that cookies with `SameSite=Strict` are not available, so `/account/login` will redirect them to `/account/` (index).

It's interesting to me that FusionAuth is allowed to _set_ the cookie in this context but not read it. The saved request cookie still exists after the workflow has completed because it was not consumed.

Also of note: if you repeat this same workflow _without_ an SSO session, the saved request cookie _is_ used (including any extra query string parameters) because submitting the `/oauth2/authorize` form breaks the redirect chain.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/257
