### ISSUE TITLE
DigitalOcean 1-Click App fails during initial installation

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#2297]
## DigitalOcean FusionAuth 1-Click App fails during initial installation

We tried to deploy [FusionAuth ](https://marketplace.digitalocean.com/apps/fusionauth) in DigitalOcean a few times and 3 out of 4 times the installation failed. The inconsistent experience seems to originate from a resource constraint in the k8s cluster due to an imbalanced deployment. When the installation fails it complains it was so far because one of the stateful set from Elasticsearch was not able to deploy because it tried to install everything on a single k8s node.

Similar issues have been reported in https://github.com/FusionAuth/fusionauth-site/pull/2049

### Description
Here some screenshots showing the resource constraint during the 2nd deployment I tried.

#### k8s node resource consumption
![pool-5vvjkdobu-fa8jt-LimitReached](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/a33aa68a-16d1-418c-aac6-137954f28835)
Resource limit reached

![pool-5vvjkdobu-fa8jl-RessourcesAvailable](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/7b549db2-14eb-4578-a306-85ee44beba59)
Resources Available

![pool-5vvjkdobu-fa8j6-RessourcesAvailable](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/fc7a2e48-732b-4d14-aaa6-b46856c516fe)
Resources Available

#### Stateful Set resource constraint - Preemption
![StatefulSets](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/45913534-7ad2-4ceb-a379-860e3cbe3efc)
One of the Stateful Set has a problem

![search-elasticsearch-data_Preemption-issue](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/01351abc-d2ae-4414-a685-142e878193b9)
Because the Pods are pending on Preemption state

It as well complained about the PersistentVolumeClaims, but the volumes where created so i am not sure if its relevant.

I will spend some more time analyzing it today and update this issue accordingly.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by Aaron-Ritter** [comment]
I've done a few more tests with similar results. There is an even distribution of Pods across the nodes but one node constantly consumes more memory than the others.

With 8GB sized nodes / droplets the result is always 100% successful. Maybe this would be a better sizing as it would allow to run 3 instead of 1 FusionAuth process.

## 4GB Memory Sizing
With 4GB Sizing I either have a complete deployment failed like before or one-legged Elasticsearch deployments which needs manual intervention.

![4G-Failed-mjevokoyy-Deployments](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/b454ce04-d4f5-4370-8c23-38cc1c376075)
![4G-Failed-mjevokoyy-Nodes](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/c5f56777-f640-43a6-beab-9c178784ee78)
![4G-Failed-mjevokoyy-StatefulSets](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/964253be-fe6f-4fde-b5ab-c9b79d44e77d)
![4G-Failed-u9bin18pc-Deployments](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/209f15d3-980b-4384-851a-ab131e7cc653)
![4G-Failed-u9bin18pc-Nodes](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/63d7755e-4c3e-4f2c-9434-efb0d530dd49)
![4G-Failed-u9bin18pc-StatefulSets](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/4cf50e1b-22c0-47f2-b734-ccc5472cdd9f)

## 8GB Memory Sizing
With 8GB Memory Sizing I was able to constantly deploy them successful.

![8G-Successful-t07x9tqij-Deployments](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/51802529-ce44-45b1-8c3a-56e43ecd8e8f)
![8G-Successful-t07x9tqij-Nodes](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/172cfda8-84b9-4789-bcd0-8db7eed6acec)
![8G-Successful-t07x9tqij-StatefulSets](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/da61932a-ae9d-4246-bdf1-1c0243b64ce2)
![8G-Successful-s2sh3spfl-Deployments](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/be1dd48a-8695-4328-a5b8-089c8deb2ad3)
![8G-Successful-s2sh3spfl-Nodes](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/737890c8-c6c7-48c3-acff-13541206f84c)
![8G-Successful-s2sh3spfl-StatefulSets](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/3a78fa64-e4ad-4ef8-aaa6-fddd5af498e0)

**Comment by mooreds** [comment]
Any update on this? It's blocking a blog post.

**Comment by bhalsey** [comment]
worked with @mmanes submitted, who just submitted https://github.com/digitalocean/marketplace-kubernetes/pull/474

**Comment by Aaron-Ritter** [comment]
@mooreds from what I see in the PR it is reducing the complexity of the newer Elastic Search version by creating multi-role pods which will greatly help reducing the resource usage I reported the issue around and is likely solved like this consistently and permanently.

And as ES is used as a simple search backend which can be any time re-indexed. There is no problem, in a later step, to increase ES setup, if that need would ever come up.

Not sure how to fully test this without being live in the marketplace but once merged I could give a final retest with our DigitalOcean account.

**Comment by bhalsey** [comment]
Digital Ocean PR has been approved and merged.  And we updated the vendor portal page to reflect the current version and verified the resource usage.
