### ISSUE TITLE
FusionAuth Admin UI list pages open multiple dialogs

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2304]
### Description 
The FusionAuth admin UI opens multiple AJAX dialogs on certain pages.

### Observed in version
`1.45.3`

### Affects versions
`>= 1.45.0`

### Steps to reproduce
One example is on the Email Templates page.
1. Navigate to **Customizations > Email Templates**
2. Click the "View" button (magnifying glass)
3. AJAX dialog is displayed
4. Close the dialog
5. There is another AJAX dialog waiting

The "Delete" button (trash can) produces the same behavior in this case.

### Expected behavior
The buttons should open a single dialog.

### Screenshots
(note the second copy of the dialog behind the first)
![image](https://github.com/FusionAuth/fusionauth-issues/assets/3409780/3c6e9615-74c8-4def-817d-aab67129effa)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
This bug was introduced as part of adding pagination and search to many of the admin UI pages in version `1.45.0`.
- https://github.com/FusionAuth/fusionauth-issues/issues/2064

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/374
- https://github.com/FusionAuth/fusionauth-issues/issues/2064

Looking for places where the JavaScript is initialized twice.

### Release Notes
When viewing an Email Template in the FusionAuth admin UI, two dialogs open instead of one. This was the result of two event handlers being bound instead of one.

**Comment by voidmain** [comment]
This issue also causes the HTML template not to render, which is likely more of an issue than the multiple dialogs. Specifically for email templates, the top dialog doesn't properly render the HTML version of the email, but the second dialog does. We probably should get this fixed as it impacts the usability of the template preview.
