### ISSUE TITLE
External authentication providers + migration

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#232]
### Problem
Currently, FusionAuth requires that all users be migrated from legacy systems into FusionAuth to provide authentication for those users. This isn't always possible or feasible. 

### Solution
It would be useful if FusionAuth could determine that a user doesn't exist in its own database and then use an external authentication provider to authenticate the user.

Additionally, during this authentication process, the user could be migrated to FusionAuth. Or if the user already exists in FusionAuth, they could be merged. 

Lastly, there should be a configuration to determine if the user's login credentials should be migrated to FusionAuth or remain in the external authentication provider.

### Alternatives/workarounds
This can be implemented by the developer in their own backend currently. Here are the steps to implement this:

1. Call FusionAuth Login API
2. If user doesn't exist, call external authentication provider's login API
3. If user exists, add them to FusionAuth

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by picklit** [comment]
Since the password needs to be 'clear-text' for the login API, it would make sense to force an https endpoint, and maybe even allow for configuring mutual SSL authentication for improved security Additional assurances against man-in-the-middle attacks would be to support symmetric-key encryption of the password.  The shared secret key would need to be manually configured on both sides of the exchange.

**Comment by robotdan** [comment]
Thanks @picklit that is a great suggestion. I agree, it would not be a good idea to implement this via an `http` endpoint. 

However, as a general rule, we try not to enforce too many restrictions and instead document best practice. We find many test and integrate on a local workstation before moving to production and requiring https or local SSL certificates can be an additional hurdle for configuration.

The way we configure external webhooks currently is through an HTTP URL - ideally `https` and allow the configuration of HTTP Basic auth, SSL certs or arbitrary Authorization headers to ensure we can securely connect to the remote system before sending information.

**Comment by irzhywau** [comment]
do you guys have any updates on this ticket?

**Comment by robotdan** [comment]
No additional update to offer you. It is on the roadmap for 2020. 

If you have a business requirement we can provide you a cost and time estimate to deliver this to your via a professional services contract. 

Thanks for using FusionAuth!

**Comment by robotdan** [comment]
This has been delivered under FusionAuth Connectors.
