### ISSUE TITLE
Missing types in go-client

### ISSUE THREAD

**Issue by ZachBurm** [FusionAuth/fusionauth-issues#2327]
### Description 
It appears that the most recent build of the go-client added the API functions for `IntrospectClientCredentialsAccessTokenWithContext` and `IntrospectClientCredentialsAccessToken`, however, the builder didn't create the `IntrospectResponse` in the Domain file. 

The error is 
```
go run main.go
# github.com/FusionAuth/go-client/pkg/fusionauth
../../../go/pkg/mod/github.com/!fusion!auth/go-client@v0.0.0-20230614174131-661b66e6e2d0/pkg/fusionauth/Client.go:3347:83: undefined: IntrospectResponse
../../../go/pkg/mod/github.com/!fusion!auth/go-client@v0.0.0-20230614174131-661b66e6e2d0/pkg/fusionauth/Client.go:3355:115: undefined: IntrospectResponse
../../../go/pkg/mod/github.com/!fusion!auth/go-client@v0.0.0-20230614174131-661b66e6e2d0/pkg/fusionauth/Client.go:3356:11: undefined: IntrospectResponse
```

Additionally, the two available versions result in the same behavior; 
https://pkg.go.dev/github.com/FusionAuth/go-client@v0.0.0-20230614174131-661b66e6e2d0?tab=versions

It seems this type is being ignored in the builder; https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/go.domain.ftl#L105. 

I had to clone the repo and use the local version on tag `1.44.0` to get it to compile.

I attempted to follow the instructions in https://github.com/FusionAuth/fusionauth-client-builder but `sb` is failing to run with 
```
A process failed for the artifact [com.inversoft.savant.plugin:client-library:client-library:0.4.1:jar]. The original error is [Invalid AMD file. The license [Apache-2.0] is not an allowed license type. Allowable values are [ApacheV1_0, ApacheV1_1, ApacheV2_0, BSD, BSD_2_Clause, BSD_3_Clause, BSD_4_Clause, CDDLV1_0, Commercial, EclipseV1_0, GPLV1_0, GPLV2_0, GPLV2_0_CE, GPLV3_0, LGPLV2_1, LGPLV3_0, MIT, Other, OtherDistributableOpenSource, OtherNonDistributableOpenSource, Public_Domain]]
 Error occurred on line [52]
```
I also tried 1.0.2 and 1.0.3 of Savant. This could be related to my Mac which is Apple Silicon :( 

Anyway, would love to help or see this fixed as I was stoked to be using FusionAuth for my project. 

### Affects versions
`v0.0.0-20230614174131-661b66e6e2d0`

### Expected behavior
The mod should compile without type errors

### Platform
(Please complete the following information)
 - Device: MacBook Pro M1 Pro
 - OS: MacOSX 13.3.1
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by ZachBurm** [comment]
Also if I could get `sb` working, i might be able to help out 🤣

**Comment by robotdan** [comment]
Thanks for reporting @ZachBurm ! 

Fixed via commits:
- https://github.com/FusionAuth/fusionauth-client-builder/commit/fc1ce09b5bf2c28123ad04e25f2e81b58018b019
- https://github.com/FusionAuth/go-client/commit/d092248b01e4d455457f1a1e64fb4198f2820ccb

**Comment by robotdan** [comment]
Please re-open if it still doesn't work.

**Comment by RichardJECooke** [comment]
@robotdan, I'm having the "is not an allowed license type" error in fusionauth-contrib when trying to build the password hasher project so I can add a hasher for Stytch import. This issue the only search result Google finds. Any ideas on how to fix this please?

I'm building the project in a Docker Alpine Linux container on my Ubuntu host.

The [container](https://hub.docker.com/repository/docker/richardjecooke/javaimage) is:

```dockerfile
FROM alpine:latest
RUN apk add --no-cache openjdk11
RUN apk add --no-cache maven
RUN apk add --no-cache curl bash
    RUN curl -L https://repository.savantbuild.org/org/savantbuild/savant-core/1.0.0/savant-1.0.0.tar.gz -o /tmp/savant.tar.gz \
        && tar -xzf /tmp/savant.tar.gz -C /opt/ \
        && rm /tmp/savant.tar.gz
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
WORKDIR /workspace
CMD ["bash"]
```

And the error is

```bash
docker run -it --name javabox -v .:/workspace richardjecooke/javaimage
cd "Password Hashing Plugins"
mvn dependency:resolve
mvn clean install
/opt/savant-1.0.0/bin/sb build

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/opt/savant-1.0.0/lib/groovy-all-indy-2.4.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Downloaded from [https://repository.savantbuild.org/org/savantbuild/plugin/dependency/1.0.2/dependency-1.0.2.jar.amd]
...
Downloaded from [https://repository.savantbuild.org/org/aopalliance/aopalliance/1.0.0/aopalliance-1.0.0.jar.amd]
A process failed for the artifact [org.aopalliance:aopalliance:aopalliance:1.0.0:jar]. The original error is [Invalid AMD file. The license [PDDL-1.0] is not an allowed license type. Allowable values are [ApacheV1_0, ApacheV1_1, ApacheV2_0, BSD, BSD_2_Clause, BSD_3_Clause, BSD_4_Clause, CDDLV1_0, Commercial, EclipseV1_0, GPLV1_0, GPLV2_0, GPLV2_0_CE, GPLV3_0, LGPLV2_1, LGPLV3_0, MIT, Other, OtherDistributableOpenSource, OtherNonDistributableOpenSource, Public_Domain]]
 Error occurred on line [63]
```

**Comment by RichardJECooke** [comment]
Never mind, thanks. Even though Savant fails, Maven compiles without a problem

**Comment by mooreds** [comment]
@RichardJECooke FYI, we don't typically monitor closed issues. Asking via a support ticket (if you have a plan with support) or in the forum will yield better results.

I'm glad you solved the issue, though!
