### ISSUE TITLE
Locale query parameter isn't preserved on redirection

### ISSUE THREAD

**Issue by MathieuMathurin** [FusionAuth/fusionauth-issues#2328]
### Description 
On the Forgot password flow. When opening an expired link having a locale query parameter in it. We are redirected to `/password/forgot` form without the locale query parameter.

The form is then rendered in a multi-language context.
- The error message is  rendered using the locale provided in the expired link.
- The form is rendered using the defaut locale.

### Affects versions
1.45.2

### Steps to reproduce
1. With a tenant having an i18n Forgot password template
2. With a tenant having an email template for locale FR.
    2.1 The email templates includes the forgot password URL with the locale query param `locale=fr`
3. Initiate Forgot password flow with a valid user having preferred locale French
4. Wait 10 minutes for the link to be expired
5. Click the link in the email.

### Expected behavior
The locale query parameter should be included in the 302 redirect location header.

#### Translated error, but not translated form
![image](https://github.com/FusionAuth/fusionauth-issues/assets/8030752/c8bd75c0-978f-4ef9-9b3a-711e9b6031ab)

#### Request URL
![image](https://github.com/FusionAuth/fusionauth-issues/assets/8030752/23a10d17-9dd3-45ac-bd70-44b809a84f7f)

#### Response Headers
![image](https://github.com/FusionAuth/fusionauth-issues/assets/8030752/59deb81e-18dd-4efb-a98f-6d98213011eb)

#### Translated form when `locale=fr` query param is in the URL
![image](https://github.com/FusionAuth/fusionauth-issues/assets/8030752/44d9611b-87d3-42d4-81ba-87f798695806)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version Chrome 114.0.5735.106

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Release Notes
If a user starts a forgot-password flow, and clicks on a change password link in an email after the change password Id has expired, the redirect back to the original Forgot Password form will not carry along a locale parameter. This fix ensures that a locale setting, when present in the change password link, is preserved.

**Comment by andrewpai** [comment]
Internal: https://github.com/FusionAuth/fusionauth-app/pull/374
