### ISSUE TITLE
Add support for configuring SAML assertion encryption in applications

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2336]
Add support for configuring the encryption of assertions in SAML responses when FusionAuth is acting as the IdP. This configuration will happen at the application level. These options need to be added to application APIs and the admin UI.

Enums for algorithm options are defined in the `fusionauth-samlv2` library.

These configuration options will go in the `Authentication response` section.
- [ ] Add a toggle for turning on/off assertion encryption, which defaults to Off
- [ ] When assertion encryption is turned on, expose the remaining encryption options. When it is turned off, hide the remaining encryption options. 
- [ ] Allow the user to select an encryption algorithm for performing the actual assertion encryption. Supported algorithms will come from the `EncryptionAlgorithm` enum. This is required.
  - The most common option seems to be `AES256`, but not sure whether we should provide a default
- [ ] Optionally support selecting the location of the encrypted symmetric key. Values are defined in the `KeyLocation` enum
  - The SAML spec mentions it being a child of `EncryptedAssertion` and sibling of `EncryptedData`
  - The XML Encryption spec seems to prefer making it a child of the `ds:KeyInfo` element which is a child of `EncryptedData`
- [ ] Allow the user to select a key transport encryption algorithm. Values are defined in the `KeyTransportAlgorithm` enum
  - `RSAv15` is not recommended for security reasons. Hide Mask Generation Function (MGF) option when selected as it does not apply
  - `RSA_OAEP_MGF1P` implies SHA-1 for the Mask Generation Function digest algorithm. The MGF option should be hidden if this is selected ([link](https://www.w3.org/TR/xmlenc-core/#sec-RSA-OAEP))
  - `RSA_OAEP` allows selecting the message digest for RSA encryption as well as the message digest for the MGF
- [ ] Allow the user to select a certificate to use for encrypting the key that is passed in the response. This will come from Key Master. This is required and has no default value.
- [ ] Allow the user to select a message digest algorithm for RSA encryption. Values are in the `DigestAlgorithm` enum
  - `SHA256` is a good default if we want one
  - We should probably allow configuring this value
- [ ] Allow the user to select a Mask Generation Function. Values are in the `MaskGenerationFunction` enum
  - The only difference between the options is the message digest algorithm used by MGF1
  - This option should be hidden unless `RSA_OAEP` is selected for the key transport encryption algorithm, and then it is required

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/271

**Comment by robotdan** [comment]
We delivered this via #1741 didn't we? Can we close this out, or is there work to do here? 
- https://github.com/FusionAuth/fusionauth-issues/issues/1741

**Comment by robotdan** [comment]
Delivered via https://github.com/FusionAuth/fusionauth-issues/issues/1741
