### ISSUE TITLE
Ensure a signed AuthN request always has the Signature element as the next sibling after the Issuer element

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2348]
### Problem
When configuring a signed AuthN request (FusionAuth is the SP), the Signature is not located as a sibling element after the Issuer element.  Certain IdPs expect this order and will send up a validation error if the Signature element is misordered in the SAML message.  The SAML v2 specification seems to suggest the Signature element belongs after the Issuer element (as a sibling).

### Solution
Ensure when an AuthN request is signed, the Signature element is inserted in the correct location.  This seems to be after the Issuer element.

### Additional context
This was not working on AzureAD with a signed AuthN request.
![image](https://github.com/FusionAuth/fusionauth-issues/assets/16090626/78ffbddd-e1a3-4a22-97ca-aa1d601dabf7)

https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf:
From 3.2.1 Complex Type RequestAbstractType

```
The following schema fragment defines the RequestAbstractType complex type:
<complexType name="RequestAbstractType" abstract="true">
<sequence>
<element ref="saml:Issuer" minOccurs="0"/>
<element ref="ds:Signature" minOccurs="0"/>
<element ref="samlp:Extensions" minOccurs="0"/>
</sequence>
<attribute name="ID" type="ID" use="required"/>
<attribute name="Version" type="string" use="required"/>
<attribute name="IssueInstant" type="dateTime" use="required"/>
<attribute name="Destination" type="anyURI" use="optional"/>
<attribute name="Consent" type="anyURI" use="optional"/>
</complexType>
<element name="Extensions" type="samlp:ExtensionsType"/>
<complexType name="ExtensionsType">
<sequence>
<any namespace="##other" processContents="lax" maxOccurs="unbounded"/>
</sequence>
</complexType>
```

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-samlv2/pull/7
