### ISSUE TITLE
Not able to pull fusion auth image

### ISSUE THREAD

**Issue by MunishCool** [FusionAuth/fusionauth-issues#2354]
### Description
I am trying to set up fusion auth but I am unable to pull any of the docker image tags of fusion auth and getting the below error.

Pulling fusionauth (fusionauth/fusionauth-app:latest)...
ERROR: manifest for fusionauth/fusionauth-app:latest not found

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Can you try a different version: `docker pull fusionauth/fusionauth-app:1.45.0`?

Thanks.

**Comment by MunishCool** [comment]
I have tried other tags as well but no luck.

**Comment by MunishCool** [comment]
I am able to pull other images but not the various tags of fusion auth

**Comment by mooreds** [comment]
That is bizarre. Here's some troubleshooting steps: https://linuxhandbook.com/manifest-not-found-error-docker/

Any other information you can provide would be helpful (any proxies you have, any other error messages you see, etc).

**Comment by MunishCool** [comment]
That's weird on the particular VM, I am not able to pull the fusion auth image but can pull any other image like Tomcat, Postgres, etc. I tried pulling fusion auth on a different VM and it works, thank god. Thanks for your response.

**Comment by mooreds** [comment]
Spooky, wonder if it was a network config or something. Thanks for letting us know.
