### ISSUE TITLE
Navigating to last page of search results shows error

### ISSUE THREAD

**Issue by krichards** [FusionAuth/fusionauth-issues#2358]
### Description 

Navigating to last page in search results shows error page.  Tested on both hosted and local community edition.

### Affects versions
1.46.0

### Steps to reproduce

Create new tenant, create new application for that tenant.  After creating a number of users to test (10K+) in the new tenant/application when I search for users without specifying the tenant and application and try and use the >> to get to the final page then I get an error.

It appears that if I explicitly set the application/tenant the final page in search and navigation to the end page works.

### Expected behavior
Expected to see the last of the users - as with searching with application or tenant.

### Screenshots

https://github.com/FusionAuth/fusionauth-issues/assets/635632/4be6302c-bd92-4492-a935-b83896a3015f

### Platform
- Desktop
- Linux Ubuntu 20
- Chrome

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Duplicate:
- https://github.com/FusionAuth/fusionauth-issues/issues/494
