### ISSUE TITLE
SMTP test failures provide unhelpful "Prime Messaging Exception"

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-issues#2373]
### Problem
When a user is configuring smtp settings on the Edit Tenant -> Email page and then send a test email, any error comes back with the uninformative message, "Prime Messaging Exception".  Furthermore, errors don't show up in the event log.

### Solution
The displayed message should indicate what the error is.  For example, "Couldn't connect to host, port: localhost, 537; timeout 2000".  This information is in the AJAX response, but isn't rendered.

### Alternatives/workarounds
A user could open up their browser's dev tools and look inside the AJAX call network response.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/901
- https://github.com/FusionAuth/fusionauth-issues/issues/1326
- https://github.com/FusionAuth/fusionauth-issues/issues/1922
- https://github.com/FusionAuth/fusionauth-issues/issues/2008
- https://github.com/FusionAuth/fusionauth-issues/issues/2011

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Release Notes
Enhance the error messaging returned to the end user when using the Test SMTP button in the FusionAuth admin UI. This enhancement will make it easier to test your SMTP configuration.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/330
