### ISSUE TITLE
Handle partial oauth_context

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-issues#2382]
### Description 
A partial parameter for oauth_context should be properly rejected. 

### Observed in version
- `1.45.1`

### Affects versions
TBD

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal: 
- https://github.com/FusionAuth/fusionauth-app/pull/286

**Comment by robotdan** [comment]
Shipped in a patch version `1.45.4` as well.
