### ISSUE TITLE
Turn on GC logging

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-issues#2388]
### Problem
JVM Garbage Collection logs provide insight into how much memory goes into young and old tenure and how much time is spent collecting it.  Without GC logs, it's hard to monitor this.

### Solution
Turn on GC logging.

### Alternatives/workarounds
The `/api/status` endpoint exposes some heap metrics, but requires metrics collection infrastructure to make use of it.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/288
