### ISSUE TITLE
capture lambda invocation metrics

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2389]
### Problem
FusionAuth metrics output is lacking detail on lambda executions. Poorly written lambdas, or integrations with non-performant external systems can create performance impacts in FusionAuth, and we currently don't have a good way to observe this behavior.

### Solution
Capture runtime metrics for lambda execution, failure, and where possible, http-connect calls

#### Lambda invocations
* Timer: All invocations
* Timer: Invocations by lambda id
* Meter: All failures
* Meter: Failures by lambda id

#### HTTP-Connect calls
* Timer: All calls
* Timer: Calls by lambda id
* Meter: All failures (status != 200-299)
* Meter: Failures by lambda id

### Alternatives/workarounds
HTTP Connect performance can be observed from external systems.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-internal-issues/issues/288
- https://github.com/FusionAuth/fusionauth-app/pull/287
