### ISSUE TITLE
Some of the language icons in the Quickstarts page don't look good in dark themes due to lack of contrast:

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2394]
Some of the language icons in the Quickstarts page don't look good in dark themes due to lack of contrast:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/1877191/4747cbc4-9315-4271-946d-67c31ab668d8)

I have two suggestions:

1. Add a CSS class to these icons (e.g. `dark-contrast`) to add a `filter: invert(1);` or something (see Express and Wordpress icons)
2. Replace `opacity-40` class with `light:opacity-40` that only adds `opacity: 0.4` when using light theme in some cases (see PHP icon)

![image](https://github.com/FusionAuth/fusionauth-issues/assets/1877191/09916483-5d95-4116-b2d8-e6a5479f0f48)

_Originally posted by @vcampitelli in https://github.com/FusionAuth/fusionauth-issues/issues/2278#issuecomment-1642198072_

**Comment by lyleschemmerling** [comment]
We can actually use tailiwind to target svg elements if we want to that, that way they will pivot with the theme.

we could also put them on solid backgrounds

**Comment by andrewpai** [comment]
closing as these got fixed at some point.
