### ISSUE TITLE
Angular Quickstart application

### ISSUE THREAD

**Issue by ColinFrick** [FusionAuth/fusionauth-issues#2395]
### Description

Create a sample application with Angular

- use the hosted backend functionality
- use the changebank functionality, theme and look and feel, like the https://github.com/FusionAuth/fusionauth-quickstart-ruby-on-rails-web repo does

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by Aaron-Ritter** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2527
