### ISSUE TITLE
Feature: Add a button to display the refresh token in the Sessions table in the UI 

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#24]
**Is your feature request related to a problem? Please describe.**
We provide refresh token to our clients that consume our API. Our customer care have a tool to generate token from our Slack directly. But sometimes, they loose the token because they move their website to another provider, or our QA team needs to test something with their credentials, etc... It could be helpful if we could have a button in the session tab to display the refresh token.

It is not a blocker since if we run the command to generate the refresh token, it will provide the same one already generated, but it would be a nice to have in the interface.

**Describe the solution you'd like**
Same solution than login form, we could display a icon that would display the token
![unnamed](https://user-images.githubusercontent.com/1580512/48245777-f9b29580-e405-11e8-947c-f2842773f7d9.jpg)

**Describe alternatives you've considered**
The only question I am wondering is about security. Is it ok, for security reasons, to be able to display this token? Or it should be strictly not allowed to do it?

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the feature request @blanchonvincent. This would be a nice enhancement.

As you mentioned - we'll need to think about the security implications of this feature and what types of permissions the FusionAuth admin would need to view this type of information. 

How are you accessing the refresh token currently? Do you just use the Login API and retrieve the Refresh Token on the response? 
https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user

Thanks

**Comment by blanchonvincent** [comment]
`How are you accessing the refresh token currently?` => yes by using the login API

**Comment by voidmain** [comment]
Security would be my main concern with this. Currently, the Login API verifies a user's credentials and then hands back a refresh token. We assume that refresh token is securely stored on that user's device (either in the browser or in secure storage on mobile). 

If we allow anyone else to see a user's refresh token, they can become that user. The refresh token is basically the most secure piece of data that FusionAuth provides and therefore must be locked down everywhere, including the end-user's browser, device and the FusionAuth backend.

One scenario would be a rogue employee (like a customer service rep) that has user management privileges in the FusionAuth UI. They find a user they want to mess with, grab their refresh token, update their cookies, hit the application and are logged in as that user. Now they can perform any function as that user.

We would need to figure out a way to mitigate this security risk somehow.

**Comment by blanchonvincent** [comment]
Should we close this issue?
We can work without that, it is just a "nice to have"...

**Comment by robotdan** [comment]
Not sure, I have seen other sites offer this type of feature. However there seems to be risk of exposing this value. 

In the Google login example you show, that is only displaying the password to the user, not a third party. In this case if we were to display the refresh token to the FusionAuth admin we would be showing it to a third party and expecting them to use appropriate security measures when handling it or passing it along to the user. This seems risky. 

I don't know if this is feasible, but the best way would be to require the end user to complete another login and obtain a new refresh token. This way there is no middle man handling the token. 


I think I'll leave it open for now to see if there is any other interest. I may also be able to do some additional research into use cases and if there if there is a secure way to transmit this token to the end user if they lose it.

**Comment by robotdan** [comment]
I am leaning towards closing this issue. I don't know if there is a use case where an admin needs to know the actual value of a refresh token. 

If anyone has a use case that requires an admin to view the actual refresh token value, please do comment and we can revisit this option.
