### ISSUE TITLE
Quickstart: Wordpress SSO integration

### ISSUE THREAD

**Issue by escii** [FusionAuth/fusionauth-issues#2400]
Description
Single Sign-On Integration of Wordpress with FusionAuth
replaces: https://fusionauth.io/blog/2021/12/06/how-to-set-up-single-sign-on-between-fusionauth-wordpress

https://github.com/FusionAuth/fusionauth-example-template/blob/master/QUICKSTART-INSTRUCTIONS.md

Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by Aaron-Ritter** [comment]
Note on following Change Bank Application theming is important, get the same look and feel as well with the Wordpress example. If this is not deliverable in a decent timeline and consistently repeatable, adjusting the theming of FusionAuth is a secondary option. Same applies for the content if possible, if the effort is not to high in creating and maintaining.

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2635

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2577 actually.
