### ISSUE TITLE
On logout it gives error  The post_logout_redirect_uri is invalid.

### ISSUE THREAD

**Issue by kamaleshdas1997** [FusionAuth/fusionauth-issues#2406]
### Description
While logout it gives this error 

<img width="316" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/47658720/c07d38df-85bd-4a30-92ad-2d4d8500c079">

These are the application settings.

<img width="944" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/47658720/e0b15311-3e4d-43b8-b7a2-bc7f213ee0eb">

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by jobannon** [comment]
Hi @kamaleshdas1997 

This appears like an integration issue and not a bug.  I would suggest you record reproduction steps and post those to our forum for further assistance!  Thanks!

https://fusionauth.io/community/forum/
