### ISSUE TITLE
Lambda invocation failure metrics is not incremented on failure

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2408]
### Description 

The lambda metrics don't seem to increment.

Here's the output from /api/status:

```
      "lambda.[*].failures": {
        "count": 0,
        "fifteenMinuteRate": 0,
        "fiveMinuteRate": 0,
        "meanRate": 0,
        "oneMinuteRate": 0
      },
      "lambda.[696e5e51-e841-4a42-90c3-41a56614b729].failures": {
        "count": 0,
        "fifteenMinuteRate": 0,
        "fiveMinuteRate": 0,
        "meanRate": 0,
        "oneMinuteRate": 0
      },
```

### Reported in  version

`1.47.1`

### Affects versions

This feature was introduced in version `1.47.0`. 
- https://github.com/FusionAuth/fusionauth-issues/issues/2389

`>= 1.470`

### Steps to reproduce

1. Create a JWT populate lambda that throws an error or exception

```
// Using the user and registration parameters add additional values to the jwt object.
function populate(jwt, user, registration) {
  throw new Error('Parameter is not a number!');
  console.info('Hello World!');
}
```
2. assign that to your application 
3. Log a user in (make sure you register them and log them in to the application, otherwise the lambda won't fire). Do this multiple times.
```
curl -vvv -XPOST -H 'Authorization: 90d8fb62-6f13-47d4-8ef6-1c3e687883c6' -d '{"loginId":"sandbox@fusionauth.io","password":"4xDU4RTwB6Wp", "applicationId":"85a03867-dccf-4882-adde-1a79aeec50df"}' https://sandbox.fusionauth.io/api/login -H 'content-type: application/json'
```
4. Check the event log--you should see N event log entries
5. Pull the status endpoint with an API key: `curl -XGET https://sandbox.fusionauth.io/api/status -H 'Authorization: 90d8fb62-6f13-47d4-8ef6-1c3e687883c6'`. Examine the output, looking for the `lambda.[*].failures` keys. 

The keys are always zero.

### Expected behavior

I'd expect the failure count to increment.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

This functionality was added per this issue: 
- https://github.com/FusionAuth/fusionauth-issues/issues/2389

Tested against sandbox, which is a single node system.

Didn't check the connector metrics.

### Release Notes
The Lambda metrics introduced in version `1.47.0` may not always correctly increment the failed count when a lambda invocation failed. This affects the `lambda.[*].failures` and `lambda.[{webhookId}].failures` metric names.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/295
