### ISSUE TITLE
Odd `Quickstarts` and `Docs` nav links behavior when browsing quickstarts

### ISSUE THREAD

**Issue by vcampitelli** [FusionAuth/fusionauth-issues#2415]
## Odd `Quickstarts` and `Docs` nav links behavior when browsing quickstarts

When navigating to the [Quickstarts index page](https://fusionauth.io/docs/quickstarts/), the `Docs` nav link has an active class:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/1877191/c1b1e2b4-7b5e-4714-8d9c-69d85a06e2d8)

But going to an actual Quickstart (e.g. https://fusionauth.io/docs/quickstarts/quickstart-ruby-rails-web), makes both `Quickstarts` and `Docs` nav links active.

![image](https://github.com/FusionAuth/fusionauth-issues/assets/1877191/7728f4f6-e71f-4eb3-9798-0894d1fe577d)

**Comment by andrewpai** [comment]
Closing, as the nav structure has changed since this was filed.
