### ISSUE TITLE
Unable to send email via JavaMail Prime Messaging Exception in fusionauth 1.44.0 , I am using smtp.office365.com

### ISSUE THREAD

**Issue by Surendra324** [FusionAuth/fusionauth-issues#2416]
Hi Team , Recently I upgraded to fusionauth 1.44.0 , I am facing below issue with sending email through SMTP

<img width="1511" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/89303910/1e5c3138-ba1b-44f8-bff3-9f70cb9bd750">

**Comment by Surendra324** [comment]
I did SWAKS test , I am able to receive mail through this SMTP

**Comment by Surendra324** [comment]
@jobannon please suggest

**Comment by jobannon** [comment]
@Surendra324 Thanks for posting!

If there are clear reproduction steps indicating this is an error condition in FusionAuth, please post them here.  However, sending transactional emails with Gmail has historically been problematic thus suggesting this is not a bug, but rather an integration issue.

I would suggest posting this in our community support channels for further guidance.  Linking to an existing forum post as well.

- https://fusionauth.io/community/forum/
- https://fusionauth.io/community/forum/topic/2233/having-trouble-using-gmail-smtp-for-email-sending?_=1691798549245&lang=en-US

**Comment by Surendra324** [comment]
Steps to reproduce the issue:

1. login fusionauth and open any of the tenant and got to edit

**tenants>default>edit**

<img width="1174" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/89303910/53fd8fad-4cc5-4403-9ee4-13fd8c966683">

2. with above smtp : smtp.office365.com and port 587 it failing in sending test emails with above error 
![image](https://github.com/FusionAuth/fusionauth-issues/assets/89303910/1b5c0124-c973-4a07-8518-7de82345793a)

need help on above

**Comment by Surendra324** [comment]
@jobannon , please find logs here 

DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPTransport=jakarta.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=jakarta.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3Store=jakarta.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], com.sun.mail.smtp.SMTPSSLTransport=jakarta.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.imap.IMAPStore=jakarta.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3SSLStore=jakarta.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: Providers Listed By Protocol: {imap=jakarta.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtp=jakarta.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], pop3=jakarta.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], imaps=jakarta.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], smtps=jakarta.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3s=jakarta.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: setDebug: Jakarta Mail version 2.0.1
