### ISSUE TITLE
changebank.svg Render issue on other operating systems

### ISSUE THREAD

**Issue by escii** [FusionAuth/fusionauth-issues#2422]
### Description
The changebank.svg file used in the new astro-quickstarts does only work properly on macOS systems as the defined font does not exist on Windows nor on Linux, therefore it renders with some default fonts which does not fit in the defined SVG canvas space and doesn't look good.

There is two options to fix this:

The easy way would be to just add more fallback fonts
change: `font-family="HelveticaNeue-Bold, Helvetica Neue"`
to: `font-family="HelveticaNeue-Bold, Helvetica Neue, Arial, 'Open Sans', Ubuntu, sans-serif"`
Examples how this looks can be seen in the attached picture.

![ChangeBank_font_issues_and_fix](https://github.com/FusionAuth/fusionauth-issues/assets/205567/af8726fc-3685-44bf-98f4-ced878af6812)

Or if you want to have it "pixel perfect"  (or in this case "vector perfect"): 
Convert the font into vector paths, but this may require a dedicated "Web License" for the "HelveticaNeue / HelveticaNeue-Bold" font. 

What ever solution gets chosen, it will require changes to almost all the new fusionauth-quickstart-* repos, most of them have the file included in the repo, some of them get it from https://fusionauth.io/assets/img/samplethemes/changebank/changebank.svg which need to be changed as well.

**Comment by mooreds** [comment]
Let's go forward with your suggested fix. Can you please provide a new SVG and PRs against the example template, the quickstart projects and the fusionauth-site repo?

**Comment by Aaron-Ritter** [comment]
**Needs Update:**
https://github.com/FusionAuth/fusionauth-quickstart-springboot-web/blob/main/complete-application/src/main/resources/static/images/example_bank_logo.svg
https://github.com/FusionAuth/fusionauth-quickstart-ruby-on-rails-web/blob/main/complete-app/app/assets/images/example_bank_logo.svg
https://github.com/FusionAuth/fusionauth-example-react-sdk/blob/main/client/src/assets/example_bank_logo.svg
https://github.com/FusionAuth/fusionauth-quickstart-flutter-native/blob/main/complete-application/assets/example_bank_logo.svg

**Unclear:**
https://github.com/FusionAuth/fusionauth-example-rails7/issues/1

**Already Correct:**
https://github.com/FusionAuth/fusionauth-quickstart-react-native/blob/main/complete-application/assets/changebank.svg
https://github.com/FusionAuth/fusionauth-quickstart-javascript-vue-web/blob/main/complete-application/src/assets/changebank.svg
https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/blob/main/complete-application/src/assets/changebank.svg
https://github.com/FusionAuth/fusionauth-quickstart-javascript-react-web/blob/main/complete-application/src/assets/changebank.svg
https://github.com/FusionAuth/fusionauth-site/blob/master/site/assets/img/samplethemes/changebank/changebank.svg
