### ISSUE TITLE
Mandatory '/' termination of Authorized redirect URLs for application's Oath configuration

### ISSUE THREAD

**Issue by user1970869** [FusionAuth/fusionauth-issues#243]
### Description 

When configuring Oath for an application we are required to add an / (forward slash) to the "Authorized redirect URLs" in order for FusionAuth to recognize the URL and allow you to add it.

Some applications (e.g. miniOrange's "OAuth Single Sign On - SSO" plugin for WordPress) won't let you put that / (forward slash) in the redirect URI causing FusionAuth to complain:

`{
  "error" : "invalid_request",
  "error_description" : "Invalid redirection uri https://example.com",
  "error_reason" : "invalid_redirect_uri"
}
`
### Steps to reproduce

1. Add application to FusionAuth
2. Click on 'Oath' tab
3. Try adding and saving a 'Authorized redirect URLs' that doesn't end in / (forward slash)

### Expected behavior

Let a URL end with or without a / (forward slash) be saved as 'Authorized redirect URLs'

### Platform

Here's what I'm using to work with the FusionAuth admin page:

 - Device: MacBook
 - OS: Mac OS Mojave 10.14.5 (18F132)
 - Browser + version: Chrome 75.0.3770.100 (Official Build) (64-bit)

FusionAuth is running on Ubuntu 18.04 behind NGINX and secured with an SSL certificate from Let's Encrypt.

**Comment by robotdan** [comment]
Not sure if I follow, are you getting a validation error when trying to save a URL in the UI configuration for authorized redirect depending upon if the URL ends with a `/` or not? 

I am able to add URLs with and without an ending `/`. 

![image](https://user-images.githubusercontent.com/1148709/62083980-5e708300-b215-11e9-80e5-2e8d2052b2e7.png)

Can you provide me a specific example to test with?

**Comment by user1970869** [comment]
Entirely my bad. Very sorry. Ignore.
