### ISSUE TITLE
Dead-End: If I mistakenly click "Register" only to find that I already have a login, I get stuck in the process

### ISSUE THREAD

**Issue by geoalexidis** [FusionAuth/fusionauth-issues#2433]
### Description
Once I click on "Create account" and enter my email address to register, I can't get back to the login screen. Only the social logins are still available.

![image](https://github.com/FusionAuth/fusionauth-issues/assets/11179990/6c438edf-7dc5-4c2a-a9d2-d07acb1b81d1)

Expected behavior:
if I accidentally clicked on "Register" as a user, I would like to have a link available again to get to the login screen.

**Comment by geoalexidis** [comment]
Any update on that?

**Comment by mooreds** [comment]
You can modify the login page to add a 'back to login' link via our theming. Any reason that wouldn't work?

**Comment by geoalexidis** [comment]
Thx @mooreds 

How can we include a "back to login" link in theme to include all the right parameters (e.g. client_id, tenant_id etc.)

**Comment by mooreds** [comment]
Hiya, the login link is documented here (we call it the `authorize` link): https://fusionauth.io/docs/v1/tech/oauth/endpoints#authorize

You should be able to access the `client_id` variable (here's the [list of common variables](https://fusionauth.io/docs/v1/tech/themes/template-variables#common-variables) available to every page) and build a login link from that.

**Comment by geoalexidis** [comment]
Hi @mooreds 

Thx for the hint. 

It is actually much easier by just including an `[@helpers.link url="/oauth2/authorize"]`

**Comment by mooreds** [comment]
That's awesome, thanks for sharing how you worked it out!
