### ISSUE TITLE
Expand Lambda API to allow for linking a lambda to an application

### ISSUE THREAD

**Issue by sixhobbits** [FusionAuth/fusionauth-issues#2434]
### Problem

We can create, read, update, and delete lambdas with the API, but there is currently no way to link or unlink a lambda with an application except through the admin UI.

### Solution

Add additional endpoints to the Lambda AI to allow linking/unlinking.

### Alternatives/workarounds

Instruct users on how to do the link/unlink step manually, but this makes testing lambdas harder.

### Additional context

See context in a tutorial here https://github.com/FusionAuth/fusionauth-site/pull/2340/files/929d0bfa9047da8348d0aedc0f980239684ec241#r1293982397

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
You can do this via the Application API: https://fusionauth.io/docs/v1/tech/apis/applications#update-an-application

curl -H 'Authorization: APIKEY' -H 'Content-type: application/json' -XPATCH https://auth.example.com/api/application/APPID -d '{"application": {"lambdaConfiguration": {"accessTokenPopulateId" : "LAMBDAID"}}}

So if you are thinking of adding it to the node CLI, you could take an application Id (or name) and a lambda name and use this API to attach the lambda to the application.

Does this meet your needs, @sixhobbits ? If so, please close. If not, please explain your use case in more detail.

**Comment by andrewpai** [comment]
Closing this issue, assuming the solution provided by @mooreds is addressing the request.
