### ISSUE TITLE
Refresh endpoint in hosted backend API not working (400: invalid request, missing refresh token)

### ISSUE THREAD

**Issue by mrehacek** [FusionAuth/fusionauth-issues#2442]
### Description 
Refresh endpoint of Hosted Backend API is broken and not working according to docs. Instead, I need to redirect to Login endpoint to refresh auth tokens. A proper request wants refresh token in params, however, the API should be designed to accept cookies, not params. It fails with 400: invalid request, missing refresh token. Furthermore, `refresh` endpoint docs say it returns 200 on error (Table 5 response codes), and there is no mention of CORS in the endpoint's documentation which is very much needed and also confusing. 

### Affects versions
1.47.1.

### Steps to reproduce
1. Setup FA application with Generate refresh tokens and Refresh token grant enabled.
2. From SPA, redirect to Login endpoint of [Hosted Backend API](https://fusionauth.io/docs/v1/tech/apis/hosted-backend#login) (successfully authenticates, browser gets 4 cookies as described in docs, logout endpoint and redirect to login to refresh is also working).
3. From SPA, send POST request with empty body to `app/refresh/{CLIENT_ID}` and 'Content-Type': 'application/json' header.
  - Request "has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource." - working with CORS settings not mentioned in docs.
  - Setup Cors filter in FA (allow all methods, all origins (*), Allowed and Exposed headers as in [cors docs](https://fusionauth.io/docs/v1/tech/reference/cors), mainly allow Access-Control-Request-Headers, Origin, Content-type, and expose Access-Control-Allow-Origin).
  - Now it passes through CORS.
6. Request fails with 400, error `invalid_request: missing_refresh_token`.

### Expected behavior
Accept the request, respond with 200, and set new refresh cookie on the client.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 11
 - Chrome 116.0.5845.111, Firefox 116.0.3 (clean, no extensions)
 - PostgresSQL 15.4

### Additional context
I guess the request expects the refresh token send in the body, which is a bug, as this API is meant to [store tokens only in cookies](https://fusionauth.io/learn/expert-advice/oauth/oauth-token-storage#client-side-storage).

**Comment by robotdan** [comment]
If I understand the request, you want this to work w/out having to modify the CORS filter configuration? 

I believe this is working as designed, and I don't know that we have any intentions to allow these requests to bypass the CORS filter. 

You should not have to add `*` to the CORS filter however, I would assume you can add a specific origin value. Let me know if I am mistaken. 

If the `/app/refresh` documentation does not mention the CORS filter, we may need to make an update to the documentation.

**Comment by mrehacek** [comment]
No @robotdan, `app/refresh` endpoint does not work according to docs or has a bug. It responds with 400: "The request is missing a required parameter: refresh_token", even though docs do not mention this parameter, nor it should be required according to description of the functionality (should accept the `app.rt` cookie sent with the request).

I'm ok with setting up CORS - it's not a real issue here, even though I'd appreciate guidelines in the docs so I could save time and have it secure.

**Comment by mrehacek** [comment]
Ah, it is my mistake. I was using axios to send the request, but I missed the option "withCredentials", as by default the request won't send cookies. I couldn't see this in devtools. Sorry for this issue, the endpoint works as expected.

**Comment by mooreds** [comment]
Thanks @mrehacek . We updated the documentation so that others hopefully won't have the same issue.
