### ISSUE TITLE
Theme Customize not working on mobile

### ISSUE THREAD

**Issue by atazangene** [FusionAuth/fusionauth-issues#2444]
I am using the 1.46.0 version of fusion auth, and I have successfully managed to change theme of fusion auth with website editor 
it works well on desktop side, however when I switch to mobile, it is completely the same as default theme.

Desktop:
![image](https://github.com/FusionAuth/fusionauth-issues/assets/136852757/a331b0b8-01c1-4118-828f-55dab606d9c5)

Mobile:
![image](https://github.com/FusionAuth/fusionauth-issues/assets/136852757/7c0c1441-b0f7-4b2e-af9d-a12d7a30bc34)

I have manually edited the template styles here:
![image](https://github.com/FusionAuth/fusionauth-issues/assets/136852757/51fb82f1-1a67-4eae-b0b3-e4b626a035d2)

what should I do?

**Comment by mooreds** [comment]
@atazangene did you find a solution?

**Comment by atazangene** [comment]
Yes, That was my fault, I in the first line, I did not closed open { 

so that cause the problem.
