### ISSUE TITLE
SCIM filter failure

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2456]
### Description 
A client saw this exception. This looks to be a valid query string. We should review and identify if this is a valid string, and if so, correct the filter parser. 

```
Unable to parse SCIM filter request. Filter string:
emails[type eq "work"].value eq "c24b01d8-0568-485b-8626-12943db53a84"

Exception:
io.fusionauth.scim.parser.exception.InvalidStateException: Invalid state transition at [emails[type eq "work"].]
	at io.fusionauth.scim.parser.SCIMFilterParser.parse(SCIMFilterParser.java:388)
	at io.fusionauth.app.service.scim.DefaultSCIMFrontendService.parseSCIMFilter(DefaultSCIMFrontendService.java:633)
	at io.fusionauth.app.service.scim.DefaultSCIMFrontendService.userFilterToQueryString(DefaultSCIMFrontendService.java:771)
	at io.fusionauth.app.service.scim.DefaultSCIMFrontendService.searchUsers(DefaultSCIMFrontendService.java:672)
	at io.fusionauth.app.service.scim.DefaultSCIMFrontendService.searchUsers(DefaultSCIMFrontendService.java:378)
	at io.fusionauth.app.action.api.scim.resource.v2.UsersAction.get(UsersAction.java:54)
```

### Observed in version
`1.45.1`

### Affects versions
TBD

### Steps to reproduce
TBD, use the `filter` `emails[type eq "work"].value eq "c24b01d8-0568-485b-8626-12943db53a84"` and see if we can recreate.

In this specific case, the SCIM client was mapping `emails[type eq "work"].value` to an attribute. I don't know this is is important or not. The stack trace looks to be only in our own parser as we map the SCIM filter to a search query.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by spwitt** [comment]
It's been a while since SCIM filtering, but I believe this is an issue with the filter. The `[ ]` is for "complex attribute filter grouping.
```
Service providers MAY support complex filters where expressions MUST be applied to the same value of a parent attribute specified immediately before the left square bracket ("[").  The expression within square brackets ("[" and "]") MUST be a valid filter expression based upon sub-attributes of the parent attribute.  Nested expressions MAY be used.  See examples below.
```

One such example, which is also included in our testing, is
```
emails[type eq "work" and value co "@example.com"]
```

The proper way to to specify the filter from the issue description is
```
emails[type eq "work" and value eq "c24b01d8-0568-485b-8626-12943db53a84"]
```

**Comment by spwitt** [comment]
The filter syntax from the description was incorrect. In order to filter on multiple sub-attributes, the sub-attributes should all appear inside the `[ ]`.
