### ISSUE TITLE
Can't create an inactive user

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#246]
### Description 
I'm trying to create a user who's going to be inactive (or locked) at first, so we can run our own approval process. However, they're always active.

### Steps to reproduce
1. `POST /api/user` with `{ active: false }`
2. The response returns ` { active: true }`

### Expected behavior
An inactive user. Same problem happens when posting to `/api/user/registration`

### Additional context
Version 1.7.2

**Comment by robotdan** [comment]
This behavior is expected and working as designed. 

The `active` property is not a documented request parameter for the Create User API.
https://fusionauth.io/docs/v1/tech/apis/users#create-a-user

You could create the user and then immediately soft delete the user which will set `active` to `false`.

**Comment by AlvMF1** [comment]
You're right, it's not in `Request Body`, but it is in `Example Request JSON`...

**Comment by robotdan** [comment]
> You're right, it's not in Request Body, but it is in Example Request JSON...


Good catch, I'll fix that.
