### ISSUE TITLE
In TimeZones dropdown City name of Kyiv has a typo

### ISSUE THREAD

**Issue by tiksn** [FusionAuth/fusionauth-issues#2460]
### Description 
Calling city name of Kyiv, Ukraine as Kiev has an imperialistic undertone, and considered to be typo at best and belittling at worst.

### Affects versions
- 1.47.1

### Steps to reproduce
1. Go to 'Settings' sidebar menu
2. Then to 'System'
3. Select 'Reports' tab
4. Select 'Europe/Kiev' in 'Reports timezone' dropdown

### Expected behavior
Presented value if `Europe/Kyiv`

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 11
 - Browser + version: Microsoft Edge 116.0.1938.76 (Official build) (64-bit)
 - Database: MySQL 8.0.33

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

[CBC Article](https://www.cbc.ca/news/world/cbc-pronunciation-kyiv-ukraine-crisis-explainer-1.6371766)

**Comment by robotdan** [comment]
We pick up these names from the JDK using `ZoneId.getAvailableZoneIds()`. 

Once Java picks up this change, and we update to that version of Java, then it will show up in the UI correctly. 

It looks like there may be some coming changes in Java to help with this, but it is not anything that FusionAuth will modify.
- https://stackoverflow.com/questions/75656590/is-java-zoneid-guaranteed-to-parse-previously-existing-timezones
- https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#getAvailableZoneIds--
