### ISSUE TITLE
Incorrect Entity API Docs

### ISSUE THREAD

**Issue by elliotdickison** [FusionAuth/fusionauth-issues#2461]
### Description 

I found a couple issues with the entity API docs:
- The docs for creating/updating/deleting entity type permissions display `/entityType/` in the path instead of `/entity/type/` (https://fusionauth.io/docs/v1/tech/apis/entity-management/entity-types). Using `entityType` results in a 404.
- The docs for creating an entity grant via POST omit the request body even though a request body similar to the PUT endpoint is required (https://fusionauth.io/docs/v1/tech/apis/entity-management/grants). Omitting the body results in a 400.

**Comment by robotdan** [comment]
Thanks for point this out @elliotdickison appreciate it.

**Comment by mooreds** [comment]
Closing under https://github.com/FusionAuth/fusionauth-site/pull/2524
