### ISSUE TITLE
Schema files accessible via URL in FusionAuth

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2462]
### Description 
Files accessible in the class path can be resolved via URL. 

This is the intended design of the MVC. No known security risks exist. But we should revisit how the MVC performs static file resolution and consider modifying it to avoid confusion. 

These files are shipped anyway and publicly available. 

### Observed in version
`1.47.0`

### Affects versions
TBD

### Internal
- https://inversoft.slack.com/archives/C051S8N8E/p1694468128323879?thread_ts=1694463294.678289&cid=C051S8N8E

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Release Notes
Update the FusionAuth static file resolution configuration to further limit class path resolution. While no known security risks exist with the current behavior, it is not necessary.

**Comment by robotdan** [comment]
Internal:
- https://github.com/prime-framework/prime-mvc/pull/35
