### ISSUE TITLE
Password settings per application instead of global

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#247]
### Problem
We cannot have different password settings per application.

### Solution
Make password settings configurable per application.

### Alternatives/workarounds
Haven't found one...

### Additional context
We have systems that we'd like to authenticate with FusionAuth to get access tokens and make requests to private endpoints on our microservices. So we'd have an application for users and other for, say, systems.

For users, we wanted to enable password expiration, but not for systems. Currently, b/c is a global config, it's for all apps or none.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
In the upcoming release - 1.8.0, all of the password settings will be per tenant, but not per application. 

In the FusionAuth architecture using password rules per application doesn't make sense because a user and their password are not scoped to an application. In other words a user has a password and it does not change per application.

**Comment by AlvMF1** [comment]
I see. So, with that, if instead of two applications under the same tenant I have two tenants, I'd be able to have different password settings?

**Comment by robotdan** [comment]
That's correct, if you require different password rules you'll have to do that per tenant. 

If you want to then create an application per tenant then you would have different password rules for each application. 

Tenants separate users and applications into their own namespace.

**Comment by AlvMF1** [comment]
Awesome!
