### ISSUE TITLE
Audit log advanced search parameters are sending incorrect values in the Admin UI

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2470]
### Description 
When performing audit log searches the advanced search field for User is sending incorrect values which causes the searches to be in error.

The User field is sending over the user's id uuid but the audit log is typically recorded with the user's email. User search doesn't work at all.
~~Start and End are setting the date and time to UTC but sending the time zone as local time so the query is searching for hours ahead of where it is supposed to.~~
 
### Affects versions
Found in: 1.43.2
Verified in: 1.47.1

### Steps to reproduce
1. Go to the audit log search in the admin UI
2. Open advanced search.
3. Type in a user's email who is in the audit log.
4. Select the user from the dropdown.
5. Perform a search. There should be no results.

### Expected behavior
User field should return accurate audit log results.

### Screenshots
If applicab
<img width="1689" alt="Screenshot 2023-09-14 at 9 44 30 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/ba0d15c0-51b0-4eba-b631-ad6c7cd9f56f">
le, add scr
<img width="1689" alt="Screenshot 2023-09-14 at 9 45 14 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/fa879ea0-9b59-4d1b-9106-d60daff4862e">
eenshots to help explain your problem.
<img width="1689" alt="Screenshot 2023-09-14 at 9 45 40 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/455c6181-f987-4d24-b124-381e16c3fe11">
<img width="1689" alt="Screenshot 2023-09-14 at 9 46 02 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/79e1a256-e36e-4ccc-b5b2-8f0cb7bca863">
<img width="1689" alt="Screenshot 2023-09-14 at 9 46 18 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/909effba-6b3b-4887-be20-9c8a1cd2cc96">

### Platform
(Please complete the following information)
 - Macbook M2 Max
 - OS: macos 13.5.2
 - chrome 116
 - postgres

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Release Notes
Fix a JavaScript error that was preventing Audit Log searches by user from returning results.

**Comment by robotdan** [comment]
If this is a bug, please add the `bug` tag.

**Comment by spwitt** [comment]
Update: the start and end time search fields appear to be working correctly. The date picker control and results table display times in the user's current time zone, but the search field displays the selected search value as an ISO-formatted string in the UTC time zone. This discrepancy could be misleading, but the changes required to convert time zones in the date picker control are out of scope for this change.

**Comment by spwitt** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/325
