### ISSUE TITLE
Changing a users password without a two factor code while two factor is enabled

### ISSUE THREAD

**Issue by pedrodiasparente** [FusionAuth/fusionauth-issues#2471]
### Description
I am attempting to integrate two factor authentication into a project, but I'm not sure what to do when updating the change password feature. My objective is for the existing flow to appear identical to what it was without two factor, with no extra steps for the user if they have two factor enabled. That means not sending a two factor code.

My understanding is that to change a password when 2factor is enabled one must also send a trust token, which is generated when completing a two factor authentication, which in turn can only be completed with a code sent to the user.

My question is, is there a way to change the users password without sending them a code while two factor is enabled?

**Comment by mooreds** [comment]
Hi @pedrodiasparente !

Please ask this kind of support question in the community forum: https://fusionauth.io/community/forum/ 

If you have a plan which includes support, you can also ask via a support ticket: https://account.fusionauth.io/account/support

Here's more details about our technical support: https://fusionauth.io/docs/v1/tech/admin-guide/technical-support

Going to close this issue out.

Thanks!
