### ISSUE TITLE
Support Java 21

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2473]
## Support Java 21

We should support java 21, the latest LTS of java, released today.

https://openjdk.org/projects/jdk/21/

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2386
- https://github.com/FusionAuth/fusionauth-issues/issues/2659
- https://github.com/FusionAuth/fusionauth-issues/issues/2732

**Comment by robotdan** [comment]
We do plan to upgrade to Java 21. As long as all of our dependencies are compatible, this is likely something we can do before the end of the year.

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/509
