### ISSUE TITLE
Return to login from expired reset password link

### ISSUE THREAD

**Issue by beezerk23** [FusionAuth/fusionauth-issues#2481]
### Description 
If you click on an expired password link from an email you land on the "Forgot password" page to get yourself a new email. On this page you cannot use the return to login link now. It always gives you the following error:

```
{
  "error" : "invalid_request",
  "error_description" : "The request is missing a required parameter: redirect_uri",
  "error_reason" : "missing_redirect_uri"
}
```

Seems like the application does not know anymore where the user did come from. 

### Affects versions
1.46.0

### Steps to reproduce
1. Get yourself an expired password reset link
2. Click on it
3. Click on the "return to login" link

### Expected behavior
It should either return you to the initial location the user came from. 
So the user visits example.com -> gets redirect to the login page -> starts the password reset process -> uses an expired link -> click on return to login -> come back to example.com.

If this is not possible for some reason, the link should not be there.

**Comment by MiticoBerna** [comment]
I have the same issue, any updates on this?

I think there are 2 quick solutions:
- Extend the expiration timeout of the forgot password link
- Add the redirect uri (the first one for example) adding in the email template link something like this:
`[...]&redirect_uri=${application.oauthConfiguration.authorizedRedirectURLs[0]}`

But we could have more than one redirect URI, so idk if this solution works well for everyone.

Any idea?

**Comment by jobannon** [comment]
@beezerk23 Can you confirm if this is related to the hosted pages and are you navigating the user to `oauth2/authorize` to have them launch a forgot password workflow?  Or are you using the Forgot Password API to send a user a password reset link?

If the former...
Can you confirm that you have the following code to the forgot password email template?

```
  [#list state!{} as key, value][#if key != "tenantId" && value??][#assign url = url + "&" + key?url + "=" + value?url/][/#if][/#list] 
```

**Comment by beezerk23** [comment]
@jobannon The user sees the login mask on `oauth2/authorize` then clicks the "Forgot Password" link. This redirects to the `password/forgot?tenantId=?&clientId=?` page. It takes the "normal" fusionauth flow i would say. Nothing special. 

You mean **in** the forgot password email? The link in the email looks like this:
`/password/change/${changePasswordId}?tenantId=${user.tenantId}`

**Comment by andrewpai** [comment]
Closing this as it seems there was simply an email template issue. In any case, the behavior is not present in FusionAuth `1.55.1`.

**Comment by SerhiiMaksymiv** [comment]
hi, facing same issue, but `[#list state!{} as key, value][#if key != "tenantId" && key != "client_id" && value??][#assign url = url + "&" + key?url + "=" + value?url/][/#if][/#list]` - fixed it
what is list state exactly, i could find it in my email template, but somehow this condition gets executed, what is or where `state` object is coming from?

**Comment by mooreds** [comment]
@SerhiiMaksymiv this is a great question for the forum: https://fusionauth.io/community/forum/ 

We try to keep github issues for bugfixes and feature requests, as opposed to general questions.
