### ISSUE TITLE
Setting preferredLanguage as a hidden field on a basic form doesn't set preferred language on the user

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2487]
I'm on 1.47.1 and I'm adding `[@helpers.hidden name="user.preferredLanguages" value="pt_BR" /]` to the template for my registration form. I can confirm that the "user.preferredLanguages" field is being submitted with the rest of the form when a user registers, but the user's preferred language is still not being set. I'm using basic forms for simplicity even though I'm a paid user.

_Originally posted by @elliotdickison in https://github.com/FusionAuth/fusionauth-issues/issues/1738#issuecomment-1740160172_

**Comment by glen-84** [comment]
@elliotdickison Did you enable the field in the registration configuration?

![image](https://github.com/FusionAuth/fusionauth-issues/assets/261509/a1732256-5156-4a23-9217-3d932ec7c1e2)

**Comment by elliotdickison** [comment]
🤦‍♂️

@glen-84 thank you! @mooreds you can close this, user error

**Comment by mooreds** [comment]
Thank you @glen-84 for helping out.

Glad to close it out @elliotdickison .
