### ISSUE TITLE
Bcrypt $2y$ Password Hash

### ISSUE THREAD

**Issue by bkonia** [FusionAuth/fusionauth-issues#2495]
Could you please support the Bcrypt `$2y$` password hash format. This is the default format that PHP uses for its `password_hash()` function, which most PHP apps use. Therefore, supporting this format would make it much easier to migrate users from PHP applications.

**Comment by mooreds** [comment]
Will this password hash work, @bkonia ? 

https://fusionauth.io/docs/v1/tech/reference/password-hashes#salted-bcrypt

**Comment by bkonia** [comment]
I don't think so, or maybe I'm not entering it correctly during testing. For example, here's a hash for the password "test":

`$2y$10$wisIVhmjWjm/lkujDJVAXuuYDXiGU/c9HK3mMzqFbfk45PXA527ui`

I tried entering that into the database password column, with the encryption scheme set to `bcrypt` and the factor set to `10`, but it didn't work. Then, I tried removing the `$2y$10$` part, entering it as:

`wisIVhmjWjm/lkujDJVAXuuYDXiGU/c9HK3mMzqFbfk45PXA527ui`

but that didn't work either.

The hash length generated by PHP is ALWAYS 60 characters. It looks like the FusionAuth hash length is 53 characters, but if you add back the seven characters, `$2y$10$` that brings it up to 60 characters, so theoretically it should work, but no luck, so far.

**Comment by mooreds** [comment]
There's more details on how to handle bcrypt passwords here: https://fusionauth.io/docs/v1/tech/apis/users#password-hashes

Can you review and see if it meets your needs, please?

**Comment by bkonia** [comment]
Yes, it worked! That was incredibly helpful. Thank you so much!

**Comment by mooreds** [comment]
Excellent!

Thanks for using FusionAuth.

Closing this issue.
