### ISSUE TITLE
Feature: Disconnect a user from a specific app

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#25]
**Is your feature request related to a problem? Please describe.**
A JWT token should be self contained and we usually revoke the refresh token to force a user to be disconnected. In our current app, for security/maintenance purpose, we are able to disconnect a user and revoke the JWT token issued as well.
Because for one of our app, the JWT expiration is 1 hour, it is important to be able to disconnect them without waiting 60 minutes.

**Describe the solution you'd like**
Today we have a table that whitelist all tokens issued from our app.
that could be great to have a button in the user page (in the session or history tab?) that could be like « disonnect the user from a app » and we could choose the app and all JWT token issued will be revoked.
Also if we have that we could also know how much JWT tokens are currently active.

**Comment by blanchonvincent** [comment]
`and you'd then have to ask FusionAuth to validate each JWT before use` => hmm true
`This sort of breaks the value of the JWT which is that anyone can validate the signature given a public key and you do not need to ask the issuer if the token is valid.` => definitely

I will check the video, but yes, we should be able to do what we want with the hooks.
Thank you.

**Comment by botnyx** [comment]
Bump...    for compatibility's sake.. 

https://tools.ietf.org/html/rfc7009

If your Token-Provider is at least an OAuth 2.0-Provider, it has to to implement the OAuth 2.0 Token Revocation.  
The URL should be delivered by an OpenID Connect-Provider as "revocation_endpoint" in the /.well-known/openid-configuration.

openidConnect also supports 'Check session iframe'  -  that is something im missing in fusionAuth too.
https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions

**Comment by robotdan** [comment]
Thanks for the comment @botnyx there are many extensions and additions to the OAuth2 standard. I have been unable to find documentation that indicates it is required to be OAuth2 compliant. 

I could be mistaken, let me know if you have a link for that. 

That spec, if implemented says the Refresh Token revoke must be provided, and the Access Token revoke should be provided. In the OAuth2 world, the Access Token is opaque, but in practice most IdPs utilize JWTs. This means that generally speaking, unless you persist each JWT which sort of defeats the purpose of a decoupled signed token, you cannot revoke them in a traditional way. 

That is to say, we do not support Access Token (JWT) revoking - apart from the previously mentioned strategy that is documented above. We do allow you to revoke refresh tokens today. 

https://fusionauth.io/docs/v1/tech/apis/jwt#revoke-refresh-tokens

A refresh token will also be revoked if you change your password, get your account locked, logout, etc. 

Looks like the Session management is also an optional extension. These both look like good additions however, please feel free to open up feature requests.
