### ISSUE TITLE
JavaScript error: PublicKeyCredential is not defined

### ISSUE THREAD

**Issue by elliotdickison** [FusionAuth/fusionauth-issues#2500]
### Description 

The default theme for version 1.47.1 ships with the following JavaScript in the "OAuth passwordless" template:

```
const uvpaAvailableField = document.querySelector('input[name="userVerifyingPlatformAuthenticatorAvailable"]');
if (uvpaAvailableField !== null && PublicKeyCredential && PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable) {
  PublicKeyCredential
    .isUserVerifyingPlatformAuthenticatorAvailable()
    .then(result => {
      uvpaAvailableField.value = result;
      document.forms[0].submit();
    });
} else {
  document.forms[0].submit();
}
```

The check for the availability of the PublicKeyCredential API does not work as intended - if PublicKeyCredential is not defined the page will fail with `PublicKeyCredential is not defined`.

### Affects versions

1.47.1

### Steps to reproduce
1. Enable the passwordless flow for a tenant
2. Attempt to complete the passwordless sign in flow on an older browser that doesn't support the PublicKeyCredential API (e.g. iOS Safari 12, Chrome 66) or using an IP address without SSL (e.g. local development with `http://192.168.0.1` or whatever your local IP is).
3. Observe that after clicking the "Sign in" button in the passwordless email the FusionAuth passwordless page breaks with the JavaScript error `PublicKeyCredential is not defined`.

### Expected behavior

I'd expect to be able to run through the FusionAuth passwordless flow during development using my local IP address.

### Solution

Replace `&& PublicKeyCredential &&` in the snippet above with `&& typeof PublicKeyCredential !== "undefined" &&`. Yay JavaScript.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS 13.5.1
 - Browser + version: Chromium 117.0.5938.149
 - Database: Postgres

**Comment by robotdan** [comment]
Internal:

Need to recreate and review this JavaScript.

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-issues/issues/2500
