### ISSUE TITLE
FusionAuth Typescript client does not correctly create GET queries with multiple values for a single parameter

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2513]
### Description 
When the FusionAuthClient in typescript constructs the query string for a GET url if the value for the parameter is an array it will naively pass it into `encodeURIComponent` instead of creating repeated instances of the parameter. The result is, for the user search api for example:

`/api/user/search?ids=00000000-0000-0000-0000-000000000001%2C00000000-0000-0000-0000-000000000002`

When FusionAuth expects:

`/api/user/search?ids=00000000-0000-0000-0000-000000000001&ids=00000000-0000-0000-0000-000000000002`

Additionally the Search API and similar methods should probably call POST instead as the query parameter as a URL is potentially a constraint.

### Affects versions
>= 1.4.0

### Steps to reproduce
1. Attempt to call `client.searchUsersByIds(ids)` with an array with multiple values such as `["00000000-0000-0000-0000-000000000001", "00000000-0000-0000-0000-000000000002"]`.

You should see the following error:

```json
{
    "fieldErrors": {
        "ids": [
            {
                "code": "[couldNotConvert]ids",
                "message": "Invalid"
            }
        ]
    },
    "generalErrors": [
        {
            "code": "[invalid]",
            "message": "You must specify either the [ids], [queryString], or [query] property."
        }
    ]
}
```

### Expected behavior
URLs should use repeated parameters and the call should succeed

### Related
- https://github.com/FusionAuth/fusionauth-typescript-client/blob/af0d9dc85e102c8e45bd071acfefd5735c1b831b/src/DefaultRESTClient.ts#L144

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Does this affect other client libraries?

**Comment by robotdan** [comment]
Internal:
- Audit all client libraries to ensure they are handling this correctly.

**Comment by lyleschemmerling** [comment]
Internal:
 - https://github.com/FusionAuth/fusionauth-typescript-client/pull/94

All other clients were checked
