### ISSUE TITLE
MFA Object Removal Upon User Update

### ISSUE THREAD

**Issue by haseebgt** [FusionAuth/fusionauth-issues#2514]
### Problem 
When making an user update request, the MFA (Multi-Factor Authentication) object is being removed.

### Description
Currently, when using the updateUser method instead of patchUser, we encounter an unexpected behavior where the MFA settings are altered. This is contrary to our expectations, as other sub-objects such as registrations, families, and entity grants remain unaffected. MFA should be treated as a distinct entity, similar to other elements.

### Proposed Solution
Ensure that updating a user does not alter the MFA settings. This should be handled independently from other user attributes.

### Additional context
We opted for the updateUser method over patchUser due to concerns about sub-object replication. This approach worked seamlessly until the introduction of MFA. We are facing this issue on fusionauth typescript-client.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This sounds like it is working as designed. When you use the `PUT` method, all values must be provided. This is documented in the User API. 

If you are providing the values on the User API, and they are not being persisted, I would consider that a bug. 

I'm sure there is room for improvement on some of our APIs, and the current design may not best suit your needs, but it is how it works today.
