### ISSUE TITLE
Registration Verification Mail lands mostly in spam

### ISSUE THREAD

**Issue by geoalexidis** [FusionAuth/fusionauth-issues#2518]
### Description
See Title. What can you / we do against it?

**Comment by robotdan** [comment]
Thanks for the issue @geoalexidis - this is a very complex problem. A lot of this will have to do with your SMTP service provider. 

If you have concrete ideas on how the FusionAuth product can make modifications to improve this, please document them so we can consider them. 

If this is just a statement, it may be a better suited for a forum discussion.
