### ISSUE TITLE
Update docker-compose.yml examples with updated PostgreSQL version

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#2520]
### Problem
There are multiple docker-compose.yml files with image: postgres:12.9 and even older and I see two problems with it:
1. The .9 minor version is already 2.5 years old, and it probably would be better if we just mention the major version as you can upgrade minor versions without creating conflicts.
2. PostgreSQL 12 will be considered [EOL November next year](https://www.postgresql.org/support/versioning/) and the newer versions should be supported and working according to the [documentation](https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements#database) mentioning PostgreSQL 10 or newer.

### Solution
In theory for both, keeping the minor as well as the major releases up to date would be the solution. We could add dependabot docker checks to the different repositories to keep informed about releases, but updating the minor version is more effort long term. 

My suggestion would be to adjust all active repositories which contain docker-compose.yaml to the latest 16 version.

Before deciding on the major version PostgreSQL 16 needs to be tested. As there where issues discovered related to PostgreSQL 15: https://github.com/FusionAuth/fusionauth-issues/issues/2312

### Alternatives/workarounds
Upgrade to at least version 14 and add dependabot. The [DigitalOcean 1-Click App](https://github.com/FusionAuth/digitalocean-marketplace-kubernetes/blob/39e64ca2aca982d510ecbc1838c8771eeb3da668/stacks/fusionauth/deploy.sh#L40) is using 14 currently.

### Additional context
There are YAML files but as well documentation sections with older versions https://github.com/search?q=org%3AFusionAuth%20%22image%3A%20postgres%22&type=code

Side note: All thought minor upgrades are not a problem, major upgrades don't work without manual upgrade, this describes it well https://betterprogramming.pub/how-to-upgrade-your-postgresql-version-using-docker-d1e81dbbbdf9

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by Aaron-Ritter** [comment]
@mooreds is it correct that this error can be ignored and as long the FusionAuth is greater than 1.43 this error can be ignored and PostgreSQL 15 and higher is supported?

**Comment by Aaron-Ritter** [comment]
@mooreds want me to add you in each PR or is it sufficient being all linked in here?

**Comment by mooreds** [comment]
@mark-robustelli owns this, so I'll defer to him.

**Comment by mark-robustelli** [comment]
@Aaron-Ritter here is sufficient.

**Comment by mark-robustelli** [comment]
merged

**Comment by Aaron-Ritter** [comment]
Update on Dependabot: It does not check the dependencies as expected. At least for now dependabot checks `docker-compose.yml` linked `Dockerfile`s but not the `docker-compose.yml` itself for package updates. I discovered this in our own repos and my hope is that they will make it available at some point for `docker-compose.yml` as well, but this means until dependabot supports it, the `docker-compose.yml` would need to be updated manually without assistance from dependabot.
