### ISSUE TITLE
Articles Mobile Navigation Z Index 

### ISSUE THREAD

**Issue by SeanBobby** [FusionAuth/fusionauth-issues#2525]
Articles Mobile Navigation Z Index

When mobile navigation is expanded, the assets are in front of the navigation drop down. 

Current live version of fusionauth.io/articles/ - Possible issues with other backend navigation in mobile.

1. go to https://fusionauth.io/articles/
2. On mobile press the dropdown navigation and scroll down
3. On desktop compress display screen until in mobile view - follow above step
4. Icons will be in front of navigation

Expected behavior
Icons should be underneath the navigation. 

Screenshots

<img width="492" alt="Screenshot 2023-10-20 at 8 47 51 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/25776300/9e9aa153-e77f-4add-ba58-ac6bae028083">

### Platform
(Please complete the following information)
 - Device: Macbook
 - OS: Sanoma v14
 - Brave

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
This is now working as expected.
