### ISSUE TITLE
Update Documentation with safe to ignore create table test_create_table permission denied error

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#2528]
### Description
During testing Update docker-compose.yml examples with updated PostgreSQL version https://github.com/FusionAuth/fusionauth-issues/issues/2520 I spotted that v15 and 16 of PostgreSQL throws an permission denied error but the setup completes successful.

```
fusionauth-db-1  | 2023-10-20 15:10:44.739 UTC [109] LOG:  execute <unnamed>: CREATE TABLE test_create_table(id INT)
fusionauth-db-1  | 2023-10-20 15:10:44.739 UTC [109] ERROR:  permission denied for schema public at character 14
fusionauth-db-1  | 2023-10-20 15:10:44.739 UTC [109] STATEMENT:  CREATE TABLE test_create_table(id INT)
```

The documentation needs to be updated that this error can be safely ignored.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
Hi @Aaron-Ritter, this was addressed in version 1.49.1 and is related to
* https://github.com/FusionAuth/fusionauth-issues/issues/2264
