### ISSUE TITLE
First Name field missing from the user edit screen when installed on Debian with MySQL

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2529]
### Description 

When installed in certain ways, the admin UI screen doesn't have a firstname field.

### Affects versions

Only tested on 1.47.1, with the .deb installer.

### Steps to reproduce

* stand up an ubuntu server
* install fusionauth `VERSION=$(curl -fsSL https://license.fusionauth.io/api/latest-version) && curl -fsSL https://files.fusionauth.io/products/fusionauth/${VERSION}/fusionauth-app_${VERSION}-1_all.deb > fusionauth-app_${VERSION}-1_all.deb && sudo dpkg -i fusionauth-app_${VERSION}-1_all.deb && sudo systemctl start fusionauth-app`
* install mysql: `sudo apt update && sudo apt install mysql-server && sudo systemctl start mysql.service`
* update the mysql root user password: `sudo mysql` then in mysql shell, run `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';` then `\q` to quit the mysql shell. 
* Make sure you can connect as root with a password. `mysql -u root -p`
* install the mysqlj connector, [as documented](https://fusionauth.io/docs/v1/tech/installation-guide/database#install-mysql-connector). If you use the [deb file](https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j_8.1.0-1ubuntu22.04_all.deb) by `sudo dpkg -i mysql-connector-j_8.1.0-1ubuntu22.04_all.deb`, copy it over to the FusionAuth directory: `cp /usr/share/java/mysql-connector-java-8.1.0.jar /usr/local/fusionauth/fusionauth-app/lib && sudo chown fusionauth:root /usr/local/fusionauth/fusionauth-app/lib/mysql-connector-java-8.1.0.jar`
* Restart FusionAuth: `sudo systemctl stop fusionauth-app && sudo systemctl start fusionauth-app`
* login to <host>:9011 and proceed through maintenance mode and setup wizard
* go to the add new user screen.
* notice the missing field.

### Expected behavior

The 'first name' field is present on the user edit screen.

### Screenshots

See missing field:

<img width="1352" alt="Screenshot 2023-10-24 at 4 41 16 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/90aeb45e-8090-4310-8c83-1651cf09a771">

### Platform

* ubuntu 22.04
* Mysql 8.0.34
* mysql-connector-java-8.1.0.jar

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

First discovered in this forum post: https://fusionauth.io/community/forum/topic/659/editing-user-data-in-the-ui

The database definitions are slightly different between mysql and postgresql, though I'm unclear if that is an issue. (I pulled down the 1.47.1 schema.)

```
dan@mooreds 659 % diff mysql.sql postgresql.sql|grep firstN
<     (UNHEX(REPLACE(CONVERT(UUID() USING utf8mb4), '-', '')), '{"key": "user.firstName", "control": "text", "required": false, "type": "string", "data": {"leftAddon": "info"}}', FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000), FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000), 'first name'),
>     (MD5(RANDOM() :: TEXT || CLOCK_TIMESTAMP() :: TEXT) :: UUID, '{"key": "user.firstName", "control": "text", "required": false, "type": "string", "data": {"leftAddon": "info"}}', (EXTRACT(EPOCH FROM (SELECT NOW() AT TIME ZONE 'UTC'))) * 1000, (EXTRACT(EPOCH FROM (SELECT NOW() AT TIME ZONE 'UTC'))) * 1000, 'First name'),
<     (UNHEX(REPLACE(CONVERT(UUID() USING utf8mb4), '-', '')), '{"key": "user.firstName", "control": "text", "required": false, "type": "string", "data": {"leftAddon": "info"}}', FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000), FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000), '[Admin Registration :  first name'),
>     (MD5(RANDOM() :: TEXT || CLOCK_TIMESTAMP() :: TEXT) :: UUID, '{"key": "user.firstName", "control": "text", "required": false, "type": "string", "data": {"leftAddon": "info"}}', (EXTRACT(EPOCH FROM (SELECT NOW() AT TIME ZONE 'UTC'))) * 1000, (EXTRACT(EPOCH FROM (SELECT NOW() AT TIME ZONE 'UTC'))) * 1000, '[Admin User] first name'),
<     (UNHEX(REPLACE(CONVERT(UUID() USING utf8mb4), '-', '')), '{"key": "user.firstName", "control": "text", "required": false, "type": "string", "data": {"leftAddon": "info"}}', FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000), FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000), '[Self Service User] first name'),
>     (MD5(RANDOM() :: TEXT || CLOCK_TIMESTAMP() :: TEXT) :: UUID, '{"key": "user.firstName", "control": "text", "required": false, "type": "string", "data": {"leftAddon": "info"}}', (EXTRACT(EPOCH FROM (SELECT NOW() AT TIME ZONE 'UTC'))) * 1000, (EXTRACT(EPOCH FROM (SELECT NOW() AT TIME ZONE 'UTC'))) * 1000, '[Self Service User] first name'),
```

postgresql has `[Admin User] first name` and mysql has `[Admin Registration :  first name`, which is a bit weird. May be a red herring.

**Comment by robotdan** [comment]
This is the bug in the default schema for MySQL. 

> postgresql has [Admin User] first name and mysql has [Admin Registration :  first name, which is a bit weird. May be a red herring.

Yes, this is the bug. 

We are naming the `user.firstName` field `[Admin Registration :  first name` instead of `[Admin User] first name` so when we go build the default form we don't find a result because we look up the field with `WHERE name = '[Admin User] first name'`.

**Comment by andrewpai** [comment]
Internal:
https://github.com/FusionAuth/fusionauth-app/pull/373

**Comment by andrewpai** [comment]
Queued for release.

**Comment by mooreds** [comment]
Don't you need to keep this open until 1.49 ships @andrewpai ?

**Comment by andrewpai** [comment]
> Don't you need to keep this open until 1.49 ships @andrewpai ?

The new process has us closing issues as they get completed and merged for release. More or less a guarantee that it will be available in the milestone release.

**Comment by mooreds** [comment]
Ahh, oops. Thanks for letting me know.
