### ISSUE TITLE
Additional parameters get stripped of encoded characters in Oauth2

### ISSUE THREAD

**Issue by WhoAteDaCake** [FusionAuth/fusionauth-issues#253]
### Description 
Encoded characters like `%3D%3D` get stripped away from additional query parameters passed to `redirect_uri` 

### Steps to reproduce
1. Pass encoded string  as an additional parameter
2. Authenticate 
3. View the query parameters returned

### Expected behavior
When 
> state=eyJzdGF0ZV9pZCI6ICIwZjA2ODE0ZTZjNDU0OGEzOTY5ZjZhZjE0ZDk1ZmZlNSIsICJuZXh0X3VybCI6ICIifQ%3D%3D

is passed as an additional parameter, same encoded value should be returned, instead 
> state=eyJzdGF0ZV9pZCI6ICIwZjA2ODE0ZTZjNDU0OGEzOTY5ZjZhZjE0ZDk1ZmZlNSIsICJuZXh0X3VybCI6ICIifQ

is returned

### Screenshots
None

### Platform
I don't think it's platform relevant
 - OS: Linux (Ubuntu)
 - Chrome

**Comment by WhoAteDaCake** [comment]
As a workaround for the moment I use base58 encode instead of base64

**Comment by robotdan** [comment]
To clarify the issue, you're passing a state value of `eyJzdGF0ZV9pZCI6ICI4OGY4NjkyMTNkYjE0NDZkYWNhZDNhZTRiZjI0MjM5NiIsICJuZXh0X3VybCI6ICIifQ%3D%3D` and `eyJzdGF0ZV9pZCI6ICIxNmM4YTdkZGZkNjc0NDc4OTI3YTkxZThhNDA5NTVmZSIsICJuZXh0X3VybCI6ICIifQ` is returned?

**Comment by WhoAteDaCake** [comment]
Sorry, I miss typed. It's 
`eyJzdGF0ZV9pZCI6ICIwZjA2ODE0ZTZjNDU0OGEzOTY5ZjZhZjE0ZDk1ZmZlNSIsICJuZXh0X3VybCI6ICIifQ%3D%3D`

that's sent and 

`eyJzdGF0ZV9pZCI6ICIwZjA2ODE0ZTZjNDU0OGEzOTY5ZjZhZjE0ZDk1ZmZlNSIsICJuZXh0X3VybCI6ICIifQ`
is returned

**Comment by robotdan** [comment]
I am unable to recreate your result, can you give me any other context? 

Are you passing through a proxy, what browser are you using? We pass whatever is sent in the `state` parameter back verbatim, so I'm not sure what would be causing the symptom you're seeing. 

The `%3D%3D` is an encoded `==` which is often a right padded value on a Base64 encoded string.

I don't know why this would matter, but you could try Base64 encoded your state w/out padding to see if that modifies the symptom.

**Comment by WhoAteDaCake** [comment]
Hmm, it might be a problem on my end then. I just assumed it wasn't getting passed.

**For context**, I am using to authenticate to Jupyterhub by using https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/oauth2.py

If you were able to return encoded values properly, feel free to close the issue. After switching to base58, everything works completely fine, as the `==` padding is gone.

My apologies if that's a problem on my end, I should have investigated more

**Comment by robotdan** [comment]
No problem. 

That link you provided to Jupyterhub looks to be using Python `base64.urlsafe_b64encode` which is documented to preserve padding. 

> Encode string s using the URL- and filesystem-safe alphabet, which substitutes - instead of + and _ instead of / in the standard Base64 alphabet. The result can still contain =.


So perhaps another piece of code is stripping them off.
