### ISSUE TITLE
Bottom page pagination doesn't work past 10000 users in admin ui

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2544]
### Description 

In the admin UI, the bottom pagination doesn't work.

### Affects versions
1.48.1

### Steps to reproduce

* log into an instance with > 10k users
* go to admin ui
* change num results to 500
* click `>>` to go to end of results. See 9501-10000 in the bottom panel
* click the `>` to go to next page

observe you are still on same page of results.

### Expected behavior

Go to next page of results.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Was seeing this with the user manager role.

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/345
