### ISSUE TITLE
Webhook: add user email and username to event's body

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#255]
### Problem
Not in the JSON body of `jwt.refresh-token.revoke`.

### Solution
Add user email and username to the JSON body.

### Alternatives/workarounds
On our webhook we make an extra call to FusionAuth with `userId` to get their email. 😢 

### Additional context
When users logout, we revoke refresh tokens and wait for the event to fire a global logout on our apps. Our systems don't know about FusionAuth's user id, but do know about their emails, so...

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @AlvMF1 

> On our webhook we make an extra call to FusionAuth with userId to get their email. 😢

Ha.. so sad.
