### ISSUE TITLE
Handle TOC on identity provider pages more gracefully

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2554]
It appears that we aren't properly exporting our headings from any components used to build up content which contain headings. See https://fusionauth.io/docs/apis/identity-providers/google and the wall of blank text in the nav. While we could disable the TOC, I'd rather have the TOC include the markdown in the OauthIdpOperations component. It appears that markdown and mdx includes export their headings in the headings property, but I'm not sure how to get it into the toc.

Options: 
* no TOC on pages that use a component
* don't use a component with dynamic headers
* doing our own MDX parsing

**Comment by mooreds** [comment]
Okay, a manual TOC seems like the best option then.

**Comment by mooreds** [comment]
Best path forward is to refactor the src/content/docs/apis/identity-providers/_oauth-idp-operations.mdx file to pull headers up to main content file.

**Comment by vcampitelli** [comment]
Here's my attempt at fixing this: https://github.com/FusionAuth/fusionauth-site/pull/2917
