### ISSUE TITLE
Markdown Tables Formatting 

### ISSUE THREAD

**Issue by alex-fusionauth** [FusionAuth/fusionauth-issues#2556]
## Headers don't stay inline with body on site.

Example of issue, written two different ways HTML and Md.
https://github.com/FusionAuth/fusionauth-site/pull/2687

### Description 
Probably needs a CSS change so that we can still use md.

### Affects versions
Astro

### Steps to reproduce
https://github.com/FusionAuth/fusionauth-site/pull/2687#issuecomment-1819426415

### Current
<img width="848" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/139158618/9a2adde6-8164-463d-a5db-54cbad2c4f98">

### Should be
<img width="841" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/139158618/d198fae6-ffc3-4a81-bc20-71c1108f9cc0">

**Comment by lyleschemmerling** [comment]
this is fixed

**Comment by lyleschemmerling** [comment]
https://github.com/FusionAuth/fusionauth-site/pull/2731

**Comment by lyleschemmerling** [comment]
closing
