### ISSUE TITLE
OIDC end_session_endpoint on metadata endpoint

### ISSUE THREAD

**Issue by trollr** [FusionAuth/fusionauth-issues#256]
### Problem
Some libraries expecting the `end_session_endpoint` property in authority metadata

### Solution
Add the end_session_endpoint

### Additional Context
https://openid.net/specs/openid-connect-session-1_0.html
https://openid.net/specs/openid-connect-frontchannel-1_0.html
https://openid.net/specs/openid-connect-backchannel-1_0.html
https://fusionauth.io/docs/v1/tech/oauth/endpoints

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @trollr this is something we've discussed a few times in the past.

**Comment by cperrin88** [comment]
Is there anything that speaks against this? Is it hard to implement?
[oidc-client-js](https://github.com/IdentityModel/oidc-client-js) expects this in the metadata. So logout doesn't work with this library.

**Comment by robotdan** [comment]
Thanks for the feedback @cperrin88 - not too hard to implement I don't think.  

There are many draft specs and extensions to OIDC so we prioritize based upon market need and community requests. 

We do also sell service, support and pro-services, so that work takes precedence over community requests unfortunately.

**Comment by jerryhopper** [comment]
Im all for this feature.  oidc-client-js is a very widely used lib.  (im using it too, and solved logout by a custom endpoint on my api that logs the user out.)
