### ISSUE TITLE
API Documentation Error

### ISSUE THREAD

**Issue by LucasPMorris** [FusionAuth/fusionauth-issues#2562]
API Documentation Error

Description 
The following API document references `GET /api/user/{userId}`:
https://fusionauth.io/docs/apis/users#retrieve-a-user

The document indicates that `GET /api/user/{userId}` will return a `trustToken` of type String. When calling the `GET /api/user/{userId}` endpoint, with MFA/2FA set up for a user, a `trustToken` is not returned.

Affects versions
The documentation indicates this has been available since version `1.33.0`, there have been changes made to the MFA step up process with that version. Not sure when or if ever a `trustToken` has been returned when calling the `GET /api/user/{userId}` endpoint though.

1. In the FusionAuth Admin UI, enable MFA, create a user, login and complete a 2FA challenge.
2. Make a call to `GET /api/user/{userId}` with the userId of the user just created.
3. Observe the returned results.

Expected behavior
It makes sense that a trustToken would not be returned with a call to the `GET /api/user/{userId}` endpoint, however, it should not indicate that is returned in the documentation.

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2757

**Comment by mooreds** [comment]
Will be live as soon as this action completes: https://github.com/FusionAuth/fusionauth-site/actions/runs/7215020187
