### ISSUE TITLE
[bug][minor] Self-service form change password race condition

### ISSUE THREAD

**Issue by elliotdickison** [FusionAuth/fusionauth-issues#2563]
### Description 

This is a minor bug, but rapidly clicking the label above the toggle for the password field in the "Default User Self Service provided by FusionAuth" form can cause the toggle state to get out of sync (the toggle may be on but the password field is hidden or the toggle may be off but the password field is visible).

### Affects versions

Tested on 1.47.1

### Steps to reproduce

1. Enable the "Default User Self Service provided by FusionAuth" form for an application
2. Open the account URL for the application and sign in
3. Click the edit button
4. Click the "Change password" toggle label rapidly 3 times. Make sure to click on the text, not the toggle.
5. Note that the toggle is now on but the password field is hidden. Turning the toggle off shows the password field. This inverted state persists unless you click rapidly on the label an odd number of times again.

### Expected behavior

The password input should always be visible when the toggle is on and hidden when the toggle is off.

### Additional context

Someone anticipated this race condition when hooking up the toggle - it ignores extra clicks while transitioning and does not suffer from the race condition. Clicking on the toggle's label appears to bypass this protection.

**Comment by andrewpai** [comment]
We added debouncing to the toggle component in version `1.52.0`, which fixed this specific instance of the issue.
