### ISSUE TITLE
Multiple locales with same language and different country fields aren't displayed

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2568]
### Description 

If you add two sets of messages files with the same language but different country fields (`af` and `af_NA` for example), only one locale is shown on the dropdown field.

### Affects versions

Tested on 1.48.2, unknown what other versions are affected.

### Steps to reproduce

1. Create a new theme
2. Create a new messages locale for Afrikaans
3. Paste keys from an existing messages into this
4. Create a new messages locale for Afrikaans (Namibia)
5. Paste keys from an existing messages into this
6. Save the theme

Visit the login page or the account page, notice that the dropdown box for locale only includes Afrikaans.

### Expected behavior

You should be able to have two or more languages displayed that include country fields.

### Screenshots
<img width="687" alt="Screenshot 2023-12-06 at 6 59 24 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/7521b7ce-9473-4469-aa0a-a1b1ed3eb302">

<img width="1089" alt="Screenshot 2023-12-06 at 7 00 24 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/1cd31837-773e-44e7-a7b5-3e4890008eb4">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Originally filed here: https://github.com/FusionAuth/fusionauth-localization/issues/69

Locale doc: https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html

**Comment by mmanes** [comment]
Related/duplicate:
- https://github.com/FusionAuth/fusionauth-issues/issues/2346

**Comment by mooreds** [comment]
Closing as duplicate of #2346
