### ISSUE TITLE
Okta SAML Docs Missing Attribute

### ISSUE THREAD

**Issue by tomcatling-faculty** [FusionAuth/fusionauth-issues#2569]
### Description 
While following the Okta/FusionAuth SAML guide [here](https://fusionauth.io/docs/lifecycle/authenticate-users/identity-providers/enterprise/okta-samlv2-idp-initiated), the login was failing due to the SAML response missing an email attribute. 

Adding the following line to the default SAML reconcile Lambda (and enabling that lambda for the integration, which is also not explicitly mentioned) fixed the issue for me:

```
user.email = defaultIfNull(samlResponse, 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/email', 'email');
```

**Comment by mooreds** [comment]
@tomcatling-faculty any feedback on this?

**Comment by andrewpai** [comment]
Closing this issue. Please re-open if you think there is an unaddressed issue here @tomcatling-faculty.
