### ISSUE TITLE
Import user with hashed password

### ISSUE THREAD

**Issue by kitkan87** [FusionAuth/fusionauth-issues#257]
Import user with hashed password

I can successfully import a user from the external database but when I try to login to the application I get a Invalid Login Credential.

These are the details I'm using to try it out and I'm using an unsalted MD5 hash while I try to figure this out. I'm also using Python if that makes a difference.

hash 5f4dcc3b5aa765d61d8327deb882cf99 = password

Username: good
Password: 5f4dcc3b5aa765d61d8327deb882cf99
encryptionScheme: salted-md5
factor: 1
salt: (blank/none) ""

Any ideas?

**Comment by robotdan** [comment]
I'll see if I can recreate.

**Comment by robotdan** [comment]
Your hash is HEX encoded, FusionAuth expects it to be Bas64 encoded.  When you import this hash into FusionAuth you will need to modify it first. 

In your example, you have a hash of `5f4dcc3b5aa765d61d8327deb882cf99` that you want to import to FusionAuth. 

As a pre-processing step, process your hash using this psuedo code

```
String existingHexHash = "5f4dcc3b5aa765d61d8327deb882cf99";
String base64EncodedHash = base64Encode(unhexStringToBytes(existingHexHash));
```

This base64 encoded hash is what you'll want to import to FusionAuth. 

I'm not a Python expert, but something along the lines of this should work:

```
bytes =  bytes.fromhex('5f4dcc3b5aa765d61d8327deb882cf99').decode('utf-8')
base64EncodedHash = base64.b64encode(str(bytes))
```

**Comment by kitkan87** [comment]
Perfect that worked.

For Python 3 the code I used to convert was
```
import codecs
hex = "5f4dcc3b5aa765d61d8327deb882cf99"
b64 = codecs.encode(codecs.decode(hex, 'hex'), 'base64').decode()
```

**Comment by robotdan** [comment]
Awesome! Thanks for the update and code example!
