### ISSUE TITLE
Doc Landing updates

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2570]
### Description
Updates to the doc landing page post doc migration

- [ ] The doc landing page does not have a direct link to the API docs. Is this intentional? This seems it would be one of the most commonly used links. ([https://fusionauth.io/docs/](http://localhost:3000/docs/)) The only way to get to the API docs is to click on a link on the landing page, and then click on "Doc categories" from the top menu and select "APIs".  Seems like there should be an easier way. (Daniel D)
- [ ] Create direct links to the doc categories on the main page, and not just up in the `Doc Categories` nav

**Comment by mooreds** [comment]
Not intentional, should definitely have it.

**Comment by andrewpai** [comment]
Closing, as these points were all addressed one way or another.
