### ISSUE TITLE
Missing fonts on website

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2573]
## Missing fonts on website

From the linkcheck report https://github.com/FusionAuth/fusionauth-site/actions/runs/7132532431/job/19423266483

```
https://fusionauth.io/css/sharp-thin.min.css
- (1:227) url(...) => https://fusionauth.io/webfonts/fa-sharp-thin-100.woff2 (HTTP 404)
- (1:283) url(...) => https://fusionauth.io/webfonts/fa-sharp-thin-100.ttf (HTTP 404)

```

**Comment by robotdan** [comment]
I think this one is my fault. I'll take a look.

**Comment by robotdan** [comment]
- https://github.com/FusionAuth/fusionauth-site/pull/2726
