### ISSUE TITLE
Clean out old docs artifacts

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2576]
Here are some things to clean up.
- Old liquid templates in /_layouts
- ekyll-specific scripts in src
- s3_website.yml
- S3 buckets
- Any CloudFront config
- Any GitHub Actions workflows

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/2749

**Comment by mooreds** [comment]
Closing.
