### ISSUE TITLE
Misc post-migration docs updates

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2577]
Here are some things that came up after the v1 release of our astro-based docs that we will tackle at some future time.
- ~~Title is too long here: https://fusionauth.dev/docs/reference/password-hashes (but that is same as on prod, so post launch)~~
- ~~Scrolling -- See https://fusionauth.dev/docs/apis/users - if you scroll the left hand nav it happens independently of the center panel. If you scroll the center panel the left hand nav scrolls with it, and that very quickly makes the left hand nav inaccessible, especially on a long page like the user api doc. We should let the center panel scroll by itself (see next item, which is related)~~
  - This needs to happen in quickstarts, too
- ~~The center content panel seems to extend all the way to the RHS of the window, as that’s where its scrollbar shows up. What’s weird is that it’s to the right of the scrollbar for the right hand panel. ~~
- The “On this page” right side navigation has leaf nodes with > that seem like they should expand (to be consistent with left side navigation). *Not doing, design decision*
  - The TOC is shared with articles needs to be thought through
- Consider widening the grid, we still have a lot of un-used space on the left and right for wider screens. If this has already been debated, then I can keep it to myself. (Daniel D) *We made some adjustments, is now as designed
  - I think we need to widen it but has larger ramifications since all content shares the same template, except blog

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
Title of password hashing doc is fixed by Dan.

**Comment by lyleschemmerling** [comment]
Calling this closed as I believe all were addressed or deliberately not done
