### ISSUE TITLE
RSA Public Key Format

### ISSUE THREAD

**Issue by Trupal00p** [FusionAuth/fusionauth-issues#258]
Hello!

It would be great if the /api/jwt/public-key endpoint published the cert in the standard JWK format described in this RFC: [https://tools.ietf.org/html/rfc7517](https://tools.ietf.org/html/rfc7517). Or perhaps a new endpoint could be created to keep backwards compat.

This was prompted as I am trying to use fusion-auth as the jwt provider for a Hasura instance as described [here](https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html) (specifically the "jwt_url" section about halfway down the page).

Edit: fixing typos

**Comment by robotdan** [comment]
Thanks for the request @Trupal00p 

In addition to the Public Key API `/api/jwt/public-key` we do also have a JWKS endpoint. 

https://fusionauth.io/docs/v1/tech/oauth/endpoints#openid-configuration
https://fusionauth.io/docs/v1/tech/oauth/endpoints#json-web-key-set-jwks

If you're configuring Hasura, this thread may be of interest to you as well. 
https://github.com/FusionAuth/fusionauth-issues/issues/61#issuecomment-493317279

**Comment by Trupal00p** [comment]
Thanks @robotdan! Really helpful info, I think that puts me on the right track.
