### ISSUE TITLE
Search request parameters display `true` in front of API field names

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2580]
### Description
API request field names for some search APIs display a `true` prefix for all the fields such as `truename`.

Many of these search APIs use a search request component with a `parameter_prefix` attribute to allow using the same component for query string parameters on a `GET` and request body parameters on a `POST`. If there is no value given to the attribute, it is interpreted as a boolean `true` value.

Observed on the following search APIs:
* Consents
* Keys
* Groups

### Solution
Use a value of `""` when there should be no prefix.

**Comment by mooreds** [comment]
Closing, this is done.
