### ISSUE TITLE
List and paragraph text sizes differ in docs

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2583]
### Description 

Looks like the list and paragraph text sizes differ. You can see on https://fusionauth.io/docs/extend/examples/multi-tenant#why-use-multi-tenancy for example.

### Screenshots

<img width="753" alt="Screenshot 2023-12-14 at 11 30 32 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/ba7ba050-874b-49ec-b8c4-f88975391939">

### Platform
Seen on firefox and chrome.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lyleschemmerling** [comment]
minor oversight. I'll touch with Sean in a day or two and we'll look for other elements (probably need to look for span, li, quote, and such)

**Comment by lyleschemmerling** [comment]
done
