### ISSUE TITLE
Extra row on tables on login API

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2587]
### Description 

The response section of the Login API has extra rows in front.

https://fusionauth.io/docs/apis/login

Maybe the rows are created even though they are empty?

### Affects versions

n/a

### Expected behavior

No extra rows.

### Screenshots

<img width="992" alt="Screenshot 2023-12-15 at 1 47 13 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/a1244f26-3ccc-4879-b67f-7ea42e9884fc">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by lyleschemmerling** [comment]
fixed
