### ISSUE TITLE
Add the SSO cookie value into the Login API response

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2588]
### Problem

I want to use the Login API but still allow users to SSO between applications with their identity in FusionAuth as if the user had logged in using the hosted login pages.

Examples include:

* want to build my own registration flow beyond what is supported by advanced registration
* want to build my own custom login flow, but let users SSO between applications
* want to transparently log users in between a native mobile app (where the username and password are provided) and web apps delegating authentication to FusionAuth

### Solution

Have the FusionAuth SSO cookie value and any other cookie values required for single sign-on between applications returned from a successful Login API call. These should be returned as part of the body of the response.

Add another parameter to the Login API called `rememberMe` or similar. If this is `true`, then return the SSO values. The client can then store them as cookies or otherwise use them.

Then, modify the FusionAuth hosted login pages, if needed, to accept the SSO cookie values when presented as if they'd been stored by FusionAuth (as a cookie). Since these values are coming back in an API response body, the cookies set in this manner by the client receiving them can not be HTTPOnly (for a SPA).

This should be available when calling the Login API without an API key to facilitate the above use cases.

### Alternatives/workarounds

* use the FusionAuth hosted login pages
* reimplement SSO on your own

### Additional context

This was a request from a prospective customer.

Related issues: 

- https://github.com/FusionAuth/fusionauth-issues/issues/1991
- https://github.com/FusionAuth/fusionauth-issues/issues/1515

[Similar functionality from another provider](https://backstage.forgerock.com/docs/am/6.5/dev-guide/#sec-rest-authentication).

I'm not sure what cookies are required beyond `fusionauth.sso`.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
I think what you are asking for is to boot strap an SSO session outside of making the user login. But in practice the Login API will not have anything to do with SSO. 

I believe this use case is documented under the following issue:
- https://github.com/FusionAuth/fusionauth-issues/issues/1515

I don't think we would ever return an SSO token (not cookie) on the Login API response. SSO is an application, and the Login API will not likely ever know anything about it. 

But if implement #1515 the goal would be to allow an SSO session to be side-loaded or bootstrapped using an existing access token of some sort - similar to how we allow the self-service account to be bootstrapped outside of using SSO. 

I think this is essentially what you are after. If so, what aspect of this is not covered under #1515?

**Comment by mooreds** [comment]
#1515 seemed overbroad because it covers:

> Add the ability to create a valid SSO session in FusionAuth. This would probably entail:
>   The ability to create, update and delete an SSO session.
>   Document the format of the SSO cookie that would have to be set.
>    I'm sure there's other stuff.
 
When all this prospect wants to do is get access to the SSO functionality without ever touching the hosted login pages.

**Comment by robotdan** [comment]
Ok. Thanks for the clarification. But just to be clear - the intent or the purpose of https://github.com/FusionAuth/fusionauth-issues/issues/1515 is exactly this. So these are duplicate requests - but we can leave it open if you feel this is explaining a different facet of the use case.

**Comment by mooreds** [comment]
I feel like this is more tactical, narrower, and implementation focused than #1515 .

**Comment by robotdan** [comment]
Going to close out this issue. The Login API and the SSO "app" are separate things and the Login API should not have any knowledge of the SSO app. 

In practice if we solve something like this, I think we would want to be able to accept a JWT in general in the front end in order to boot strap the SSO session. We could consider side loading the SSO session using an HTTP request header like we do for self-service. 

So we could re-orient this issue, or track some sort of solution under #1515 . 
- https://github.com/FusionAuth/fusionauth-issues/issues/1515
