### ISSUE TITLE
Trust policy per app when app specific MFA is enabled is hidden when MFA policy is set to Required. 

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2593]
### Description
I think the trust policy should be shown when MFA policy is enabled or required. We should double check, and then update the UI to show this field for Enabled or Required. 

We should also review the API doc to ensure this it is documented when the trust policy is used. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/421

**Comment by andrewpai** [comment]
Scheduled for delivery in 1.50.0.
