### ISSUE TITLE
Cannot log into management UI

### ISSUE THREAD

**Issue by radekjakubowski** [FusionAuth/fusionauth-issues#2597]
### Description 
Going through docs tutorial on securing Angular SPA FusionAuth doesn't work and it has two issues:
- Postgresql public schema fail
- Admin setup wizard does not show up even if I recreate entire docker-compose with volumes (related?)

### Affects versions
The one from docs

### Steps to reproduce
1. Clone repo
2. Run SPA
3. Run docker-compose up -d
4. Go through wizard (if it shows up) and login to your account doesn't work (as DB didn't migrate at all)

### Expected behavior
Running demo, creating admin account and being able to log into Management UI.

### Platform
 - OS: Windows 11
 - 64-bit Edge 120.0.2210.91
 - Postgresql hosted in Docker - version from docs
 - Docker version 24.0.2
 - node v20.9.0

**Comment by mark-robustelli** [comment]
@radekjakubowski , are you talking about the quickstart here: [https://fusionauth.io/docs/quickstarts/quickstart-javascript-angular-web](https://fusionauth.io/docs/quickstarts/quickstart-javascript-angular-web)? Can you please try to run `docker compose down -v` from the root of the quickstart repo and then try again?

**Comment by radekjakubowski** [comment]
Yes.
All I did was cloning repo, running docker-compose and frontend. I tried lots of stuff like recreating volume, using older Postgres versions and older versions of FusionAuth.

I'll try it once again after the holidays and post an update here.

**Comment by radekjakubowski** [comment]
@mark-robustelli 
Sorry, I thought that I need to create an admin user first and then log into FusionAuth UI with my created user credentials from wizard. Using credentials provided in kickstarter I am able to login into the UI.

Now I am wiser that it's all done via kickstart file :D
Wishing you happy new year Mark - issue to be closed!
Much love for providing auth solutions to thousands,
Radek

**Comment by mark-robustelli** [comment]
Glad you were able to work through it.  It it important to note too, that the kickstart can take a minute or two to complete on the initial spin up of the image.  Also, if you were running other versions of the docker image, it can help to clear them from the downloaded images and pull all fresh ones.  Thanks for the taking the time to work through it and share with the community.
