### ISSUE TITLE
Date format should depend on the timezone

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#26]
**Describe the bug**
In my interface: `11/9/2018 05:17 PM GST`
I think only US use this format no?
I defined my timezone to Asia/Dubai, but we do not use this format here
Could we define the format according to the timezone?

**To Reproduce**
-

**Expected behavior**
2018/11/09 05:17 PM GST

**Screenshots**
<img width="637" alt="screen shot 2018-11-09 at 5 20 18 pm" src="https://user-images.githubusercontent.com/1580512/48264672-c2fb7000-e443-11e8-9e9b-06dbb6c258f4.png">

**Comment by robotdan** [comment]
Thanks for the request @blanchonvincent. Sorry about your eyes. 😄 (looks like you removed that in an edit, it was funny). 

Yes this is definitely something we want to do, we'll update this issue with the target release once we have it complete.

**Comment by blanchonvincent** [comment]
great :) thank you

**Comment by robotdan** [comment]
How's this? 

<img width="978" alt="screen shot 2018-11-11 at 6 15 52 pm" src="https://user-images.githubusercontent.com/1148709/48321192-f4a83e80-e5dd-11e8-8fc5-7cd6cd62a45e.png">

<img width="238" alt="screen shot 2018-11-11 at 6 16 29 pm" src="https://user-images.githubusercontent.com/1148709/48321191-f4a83e80-e5dd-11e8-85e1-c8d034c5ea3e.png">

**Comment by blanchonvincent** [comment]
perfect 👍
