### ISSUE TITLE
Toggle rendering is off in Firefox

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#260]
### Description 
Not sure if this is a Firefox issue, or something we can correct in CSS. 

### Expected behavior
A similar rendering to Chrome or Safari

### Screenshots

Firefox enabled 
![image](https://user-images.githubusercontent.com/1148709/62712560-50122c00-b9b8-11e9-9bae-7159096c247b.png)

Firefox disabled
![image](https://user-images.githubusercontent.com/1148709/62712568-53a5b300-b9b8-11e9-941e-db93e54fb74d.png)

Edge / Chrome enabled (good)
![image](https://user-images.githubusercontent.com/1148709/62712573-56a0a380-b9b8-11e9-98aa-b3e6af3a2b26.png)

Edge / Chrome disabled (good)
![image](https://user-images.githubusercontent.com/1148709/62712577-586a6700-b9b8-11e9-8256-d34c08cc2076.png)

**Comment by snmed** [comment]
Hi
If you add `position: absolute` to the input element, it should look fine for Firefox, Edge and Chrome.
```
.toggle input[type="checkbox"] {
height: 1px;
opacity: 0;
width: 1px;
position: absolute;
}
```
Cheers
