### ISSUE TITLE
Old 'single use' refresh tokens re-usable on login API

### ISSUE THREAD

**Issue by IdoZamir** [FusionAuth/fusionauth-issues#2610]
### Description 
When trying to use rotating refresh tokens with the login API I am finding that while a new refresh token is generated as a result of each session, the old refresh token is still valid (for at least 10-15 min from testing, have not been able to get it to stop working without revoking the entire session). 

I am new to FusionAuth so hopefully I am just missing something in my configuration or use of the endpoints. 

### Observed versions
version 1.48.3
Tested on dockerized and SaaS

### Steps to reproduce
1. Create a tenant with settings JWT -> Refresh token settings -> usage policy: One time use. The value will change each time the refresh token is used.
2. create an app that inherits JWT settings and uses security 
Require an API key ON
Generate refresh tokens ON
Enable JWT refresh ON
3. Create an API key to log users in. Default settings.
4. Create a user and register them on the app
5. Login the user with POST {{baseUrl}}/api/login
6. Use the refresh token on POST {{baseUrl}}/api/jwt/refresh
7. Get a new access and refresh token (good)
8. Repeat step 5 without changing the refresh token.
9. Get a new access and refresh token (bad)

### Expected behavior
When using a refresh token, response provides a new refresh token and the old token is invalidated as part of the same request. Using the same request body should not work a second time without updating the refresh token. 

## Screenshots
![fusionAuth](https://github.com/FusionAuth/fusionauth-issues/assets/18495648/41fc23c6-ab6f-46f5-8c82-8116032d6802)

**Comment by lyleschemmerling** [comment]
Hi @IdoZamir this is intended behavior though it can be very misleading as to what happened.

If you look at https://fusionauth.io/docs/apis/jwt#refresh-a-jwt the API will take both a `refreshToken` parameter in the POST body and a `refresh_cookie` cookie as request parameters. This line is important:

```
If the cookie refresh_token is also on the request it will take precedence over this value.
```

And if you look at the response the `refresh_token` cookie will be sent back with the new value.

Postman will honor this and send the updated token in the request, but it isn't obvious that this is what is happening. So though your request body never changes the cookie values are and the cookie is what is actually being used as the refresh token in the request. If you clear out the cookies from Postman between requests you should only get one use out of your refresh token.

Apologies for the confusion and please let us know if you have any further questions.

**Comment by IdoZamir** [comment]
You're right, omitting the cookies from the request fixes the problem, the refresh token is not actually reusable. Thanks for you for your help!
