### ISSUE TITLE
Add additional CSRF protection when FusionAuth is functioning as a SAML IdP

### ISSUE THREAD

**Issue by andrewpai** [FusionAuth/fusionauth-issues#2611]
### Description
If a SAML state contains an unregistered redirect URI in its `acs` value, override it with the first registered URI.

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Release Notes
Add additional protection against cross-site attacks when FusionAuth is acting as a SAML IdP.

**Comment by robotdan** [comment]
@andrewpai is this a bug, or an enhancement request?

**Comment by andrewpai** [comment]
Internal: https://github.com/FusionAuth/fusionauth-app/pull/366

**Comment by andrewpai** [comment]
> @andrewpai is this a bug, or an enhancement request?

Updated as an enhancement, as the implementation adds additional cross-site protection.
