### ISSUE TITLE
passwordValidationRules variable not available on change password themed page in 1.48.0

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2616]
### Description 
`passwordValidationRules` not available when redirecting a user to change their password (after a successful login typically).  This was available as a variable on version `1.36.0`

### Observed versions
`1.48.2`

### Affects versions
`>= 1.47.0`

### Steps to reproduce
0. Update the change password form to have the following on main `${passwordValidationRules}`
1. Create a new user
2. Force that user to change their password on next login
3. Have the user login
4. Observe a null error from freemarker

<img width="367" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/16090626/fd73d7b2-ea4f-4693-b821-79fba95761b8">

### Workaround
If you encounter this issue you may optionally check this value in your theme for `null` by using an if check. For example `[#if passwordValidationRules??]`. Or you may reference this object from the `tenant` - for example `tenant.passwordValidationRules`. 

### Expected behavior
No expected behavior (our default theme does a null check on this variable with conditionals) but it is not clear as to why this variable is available on one version of FusionAuth and not on another.  

### Platform
dev platform - related slack thread https://inversoft.slack.com/archives/C01TJLP2HQ8/p1705544952279809?thread_ts=1705369296.546639&cid=C01TJLP2HQ8

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2360

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
This was identified by a customer, and we also observed it internally.

**Comment by andrewpai** [comment]
Internal: fixed as part of https://github.com/FusionAuth/fusionauth-issues/issues/2443
