### ISSUE TITLE
Site: Astro 4 upgrade

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2621]
### Description
We should update the latest version of Astro.

Known Issue:
 - [ ] The blog `feed.xml` files did not generate
 - [ ] Mermaid diagrams did render styles for dark mode

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
We're on Astro 4, closing this. At some point we'll need to start talking about going to Astro 5...
