### ISSUE TITLE
Mask potentially sensitive values when writing to the audit log in the admin UI

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2623]
### Description
Ensure we are masking or removing sensitive information when writing to the audit log. 

### Related
- https://github.com/FusionAuth/fusionauth-internal-issues/issues/308

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/351

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/2859
