### ISSUE TITLE
"Getting Started" link goes nowhere

### ISSUE THREAD

**Issue by JoshTheHero** [FusionAuth/fusionauth-issues#2625]
Clicking on the "Getting Started" link on the FusionAuth landing page takes you to a 404 page. It leads to this link https://fusionauth.io/docs/getting-started 

Will likely need to redirect to https://fusionauth.io/docs/get-started/ which is the correct page for documentation 

<img width="720" alt="Screenshot 2024-01-23 at 11 52 57 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/6797347/4aaf1413-4787-4b6d-8115-ed2a0cbb9356">

<img width="849" alt="Screenshot 2024-01-23 at 11 47 37 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/6797347/d8077ccb-4835-4610-85ed-9add13b0285f">

### Release notes
Updated the links on the FusionAuth app landing page (logged out state) to have correct and/or updated values.

**Comment by mooreds** [comment]
Going to add a redirect.

**Comment by mooreds** [comment]
Internal:

* https://github.com/FusionAuth/fusionauth-site/pull/2839
* https://github.com/FusionAuth/fusionauth-app/pull/370

**Comment by lyleschemmerling** [comment]
The redirects are good but we should fix the dead urls in the fusionauth codebase as well

**Comment by mooreds** [comment]
@lyleschemmerling I grepped through the codebase and [submitted a PR](https://github.com/FusionAuth/fusionauth-app/pull/370) that was merged. If I missed something, happy to submit another.
