### ISSUE TITLE
Expose passwordValidationRules on change password form template

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#263]
### Problem
Currently the variable `passwordValidationRules` is only available when users submit a password that doesn't meet the requirements.

### Solution
Expose the variable all the time in this form. Not only on error.

### Alternatives/workarounds
Hardcode the rules, which can go out of sync with the configuration.

### Additional context
 Ideally, we'd display the rules before hand, so users know how their passwords should be.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
@AlvMF1  Thanks for the suggestion.
