### ISSUE TITLE
3 Node configuration 

### ISSUE THREAD

**Issue by muraliv21** [FusionAuth/fusionauth-issues#2633]
Hi All,
If we configure 3 node cluster if 2nodes not responding will it switches to another node ?

**Comment by robotdan** [comment]
Hi @muraliv21 thanks for the question. 

If you have a support contract, please open a ticket. If you are using Starter or the Community Edition please ask this in the public FusionAuth Slack, or post a question in the FusionAuth forum. 

Thanks!

- https://fusionauth.io/community
