### ISSUE TITLE
Fusion auth install on Azure App service 

### ISSUE THREAD

**Issue by muraliv21** [FusionAuth/fusionauth-issues#2634]
Hi Team,

We need to know, can we install Fusion auth on Azure Appservice ?

**Comment by mooreds** [comment]
@muraliv21 This seems like a [great question for our forum](https://fusionauth.io/community/forum/).

Or, if you have a plan which includes support, please [open a support ticket](https://account.fusionauth.io/account/support/).

Github issues is for bugs and feature requests.

More on our [technical support options](https://fusionauth.io/docs/operate/troubleshooting/technical-support).

I'm going to close this issue out.
