### ISSUE TITLE
License page is unreadable on mobile

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2642]
## License page is unreadable on mobile

There's margins on the outside of the content that squish it fairly aggressively. Needs a different layout, and possibly some attention to the simple markdown

<img width="562" alt="Screenshot 2024-02-07 at 8 59 39 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/c5dbc19e-81e2-4a3e-bea0-8780d5965fbf">
<img width="562" alt="Screenshot 2024-02-07 at 8 59 51 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/11809481/dfee747b-0201-4a41-b7ba-99f3f4cd7d0b">

**Comment by andrewpai** [comment]
This seems better on the production site now, closing this issue.
