### ISSUE TITLE
Populate Session Metadata from SSO session

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2646]
### Description
When we initially complete a login, we will run JS on page to populate hidden fields which will populate data such as `type` and `name` (session metadata on the refresh token)

```
input[name="metaData.device.name"]
input[name="metaData.device.type"]
```

This allows for us to persist session data in the RT and the SSO session token.  However, if a user has only a FA SSO session (no active AT or RT available), when they obtain a new RT (based on this session), we do not persist any metadata (partly because we are not running this JS from the authorize page on a form post with hidden fields).  There may be legitimate reason to not use the same metadata from an SSO session on newly minted RT, but when possible, we should consider copying the metadata from the SSO session to the RT.

<img width="526" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/16090626/49e033c8-77ce-462b-8cab-c22b8399664f">

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
We will only display meta data that is provided, so if integrations are not providing it when they request a refresh token, we won't display it. 

Can you update the issue with a workflow that results int he result that you are seeing?

Thanks!
