### ISSUE TITLE
Issue with running startup.ps1 script in Windows Powershell

### ISSUE THREAD

**Issue by kdownunder** [FusionAuth/fusionauth-issues#2654]
##Issue with running startup.ps1 script in Windows Powershell

### Description 
I have just installed successfully FusionAuth using Windows Powershell, but I am having issues running the startup.ps1 script and getting the error message as per screenshot below. It says that startup.ps1 script cannot be loaded because running scripts is disabled on this system.

### Affects versions
1.48.3

### Screenshots

![image](https://github.com/FusionAuth/fusionauth-issues/assets/160567813/5b235bbe-f1bf-40ee-a277-d9902956df99)

**Comment by mooreds** [comment]
It looks like you need to enable execution of scripts on the system.

Here's an article from stackoverflow's superuser.com site on how to do so: https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts

**Comment by andrewpai** [comment]
This issue seems resolved. @kdownunder feel free to re-open it if that isn't the case.
