### ISSUE TITLE
Pagination/Search for Identity Providers Application Options

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2657]
### Problem
It is hard to edit identity providers when you have many applications listed.  The edit page for identity providers needs to paginate many applications.

### Solution
Add pagination and search for identity providers applications in the admin UI.

<img width="2491" alt="image" src="https://github.com/FusionAuth/fusionauth-issues/assets/16090626/3c225998-de6d-4e22-a519-7a2de7936226">

### Parent
- https://github.com/FusionAuth/fusionauth-issues/issues/374

**Comment by robotdan** [comment]
Is this a duplicate of this issue?
- https://github.com/FusionAuth/fusionauth-issues/issues/767

**Comment by jobannon** [comment]
Duplicate
