### ISSUE TITLE
Missing Software License & Corporate Identity

### ISSUE THREAD

**Issue by rahardin** [FusionAuth/fusionauth-issues#266]
### Description

Please, provide and publish a software license and tell the audience who you are, especially the legal identity of or behind FusionAuth. 

The term "free" indicates a free software license. A free-software license is a notice that grants the recipient of a piece of software extensive rights to modify and redistribute that software. https://en.wikipedia.org/wiki/Free_software_license

Free software seems not to be intended as FusionAuth is not open source.

**Comment by robotdan** [comment]
Hi @rahardin You are correct, FusionAuth is not open source, but it is free. Free software is often not open source. This is why we use the wording free as in beer, not free as in speech. This is a concept often used to describe how open source is free. https://www.howtogeek.com/howto/31717/what-do-the-phrases-free-speech-vs.-free-beer-really-mean/

Parts of FusionAuth such as the domain, client libraries, and others are open source and are available on GitHub. Most of those libraries will be licensed under the Apache 2 license. 

The "FusionAuth" software license can be found here
https://fusionauth.io/license

Thanks!

**Comment by rahardin** [comment]
So, wouldn't you like to put links to the license and to the "free as in beer" explanation and to the anonymous (?) company in order to help potential customers to understand the software and service that you provide? You company isn't registered in China, is it? ;-)

**Comment by robotdan** [comment]
The link to the free as in beer is on the home page where it says 

> Web-scale identity - FREE (as in) Beer

The software is free, and does not require a license, which is why the license link is not highly promoted on the site. 

We will be launching a refreshed site shortly which will include additional information with more links etc. Thanks for the feedback. 

We are Inversoft Inc, DBA as FusionAuth in Denver CO.
