### ISSUE TITLE
Add community license support to licensing server

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2662]
### Description

This community license support will be used to enable features to the community edition that require a free account.

Use the same infrastructure as we use for paid licenses (the plan tab in account.fusionauth.io, the reactor tab in the product), but allow people to sign up for a free license.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/account.fusionauth.io/pull/189
