### ISSUE TITLE
Move passkeys/webauthn to the community licensed plan

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2663]
### Description

Move passkeys from the essential plan to the community licensed plan.

* changes to product to enable
* changes to doc site
* changes to pricing page

### Related Issues

This depends on:

- https://github.com/FusionAuth/fusionauth-issues/issues/2662

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment]
Shipping in 1.52.0

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/486
