### ISSUE TITLE
FusionAuth does not send Email Verification Complete email after the corresponding step

### ISSUE THREAD

**Issue by mou** [FusionAuth/fusionauth-issues#2672]
### Description 
If for the application the "Email Verified" template is set, it is expected that the user will receive an additional email after clicking the verification link in the "Email Verification" email.

### Observed versions
FusionAuth Cloud v1.47.1

### Steps to reproduce
1. Configure basic Email sending for tenant
2. Create a new email template for "Email Verified" case
3. Create an application and enable: email verification, self-registration
4. Assign the created template to the "Email Verified" option on the Email tab of the application configuration
5. Perform a new account registration
6. Check the email inbox and click on the "Verify" link in the email just received.

### Expected behavior
Expect to receive an additional email with the content of the template created in step 2

### Observed behavior
No such email received

### Screenshots
If applicable, add screenshots to help explain your problem. Delete this section if it is not applicable. 

### Platform
FusionAuth Cloud

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mou** [comment]
Looks like in this conditions webhook for this event also not triggered.

**Comment by mou** [comment]
Additional information is useful. Today, we upgraded the instance to the latest 1.49.1 version. Querying `/user/search` does not return `verifiedInstant` fields for user or registration. However, according to documentation, this field should be present.

**Comment by andrewpai** [comment]
Shipping in 1.50.0.
