### ISSUE TITLE
[Bug]: Very large amounts of data in the user.data field will cause indexing failures in elasticsearch

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2675]
### What happened?

Seen in a system where a bug caused an excessive amount of data to be loaded into the user data field. If too many fields are loaded into the object Elasticsearch will reject the document as it is unable to index it with the following error:

```
java.lang.IllegalArgumentException: Limit of total fields [1000] in index [fusionauth_user] has been exceeded
	at org.elasticsearch.index.mapper.MapperService.checkTotalFieldsLimit(MapperService.java:614) ~[elasticsearch-7.6.1.jar:7.6.1]
```
(from fusionauth-search.log)

If any users get into this state attempting to reindex all users will fail. We should add validation to prevent users with large amounts of data from being loaded to prevent this.

### Version

1.47.0

### Affects Versions

all

**Comment by mooreds** [comment]
how much data @lyleschemmerling ?

**Comment by lyleschemmerling** [comment]
closing in favor of https://github.com/FusionAuth/fusionauth-issues/issues/2676
