### ISSUE TITLE
Audit log does not show actions performed by users without email

### ISSUE THREAD

**Issue by shteinbookstas** [FusionAuth/fusionauth-issues#268]
### Steps to reproduce
1. Go to Users
2. Create a new user in default tenant
3. give this user registration in fusionauth app and global admin role
4. logout
5. login as newly created user and create another user
6. go to audit log
7. notice that the second user creation performed in step 5 was not added to audit log.

### Expected behavior
Expected all admin actions to be added to audit log.

### Platform
Version 1.7.2

### Workaround
Make sure the user has a non empty value in email

**Comment by robotdan** [comment]
Available in 1.7.3
