### ISSUE TITLE
After upgrade from 1.47.x to 1.49.1 FusionAuth stopped to send email via SendGrid SMPT

### ISSUE THREAD

**Issue by mou** [FusionAuth/fusionauth-issues#2680]
### Description 
Before upgrade FusionAuth Cloud was running version 1.47.x and was properly configured to send transactional email via configured SMTP server provided by SendGrid.

After upgrade event log contains next record for every attempt to send verification email:

```
Async Email Send exception occurred.

Template Id: XXX
Template Name: XXX
Tenant Id: XXX
Addressed to: <customer email>

Cause:
jakarta.mail.MessagingException : Message: Could not convert socket to TLS
```

### Observed versions
FusionAuth Cloud 1.49.1

### Affects versions
The version, or versions where this bug exists. If you do not know, please leave blank for now. 

### Steps to reproduce
1. Set up FusionAuth Cloud with a version 1.47.x
2. Configure email sending via SendGrid SMPT gate
3. Activate email verification for application
4. Register new User
5. Observe email verification letter in corresponding mailbox
6. Upgrade FusionAuth to 1.49.1
7. Register new user account
8. Observe ` Async Email Send exception occurred` in the event log

### Expected behavior
Expected emails to be sent as before upgrade

### Screenshots
If applicable, add screenshots to help explain your problem. Delete this section if it is not applicable. 

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mou** [comment]
Searching the internet shows there might be misconfiguration in Jakarta Mail. Since we do not have any control over server configuration, we are unable to solve this problem by ourselves.

**Comment by mou** [comment]
Attempt to send test email from FusionAuth admin UI renders next error message:

```
Unable to send email via JavaMail

Prime Messaging Exception
Could not convert socket to TLS
Cause: IOException: Can't verify identity of server: smtp.sendgrid.com
```

Looks like CA bundle misses some of the Root certificates. SendGrid [troubleshooting guide](https://docs.sendgrid.com/for-developers/sending-email/smtp-errors-and-troubleshooting#certificate-verification-failed-for-smtpsendgridnet)  contains information for such cases.

**Comment by mou** [comment]
The SMTP server address was specified incorrectly. It should be `sendgrid.net`, not `sendgrid.com`.  It looks like `.com` was a legacy address with an old certificate that works for the old CA bundle. After the upgrade, it is no longer valid according to the new set of roots.

**Comment by mooreds** [comment]
Thanks for sharing your resolution!
