### ISSUE TITLE
Limit administrative maximum password length configuration

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2688]
### Description

The default maximum is 256, and this seems more than reasonable for any legitimate password. So we can likely just validate that an admin cannot set this higher than 256. 

### Related
 - https://github.com/FusionAuth/fusionauth-issues/issues/2671
 - https://github.com/FusionAuth/fusionauth-issues/issues/2704

### Documentation
- [ ] Doc max length of 256 on API and UI if mentioned. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/402

**Comment by andrewpai** [comment]
Shipping in 1.50.0.
