### ISSUE TITLE
Support TOTP For email confirmation

### ISSUE THREAD

**Issue by zbruhnke** [FusionAuth/fusionauth-issues#269]
### Problem
It's becoming more and more common for users to verify their email with a TOTP in email (usually a 6-digit code or something like it) which allows the user flow to be relatively simple (no closing a tab and clicking a link in an email to re-open it in a different tab, being able to just check email on your phone and type it in on your laptop, etc.)

### Solution
A simple solution that would generate a TOTP code (probably with some parameters around how many digits (for instance default to 6-digit code but maybe others would want a 4 or 8-digit code).

Also notice in the LogDNA flow they actually generate the link as well (so you have both options, I think thats a wonderful solution!)

The flow would ideally look a lot like what LogDNA does with their login flow (see below)

![Screen Shot 2019-08-15 at 11 58 27 AM](https://user-images.githubusercontent.com/346308/63119763-b9b0ae00-bf55-11e9-822f-76c2f651239b.png)

![Screen Shot 2019-08-15 at 11 59 23 AM](https://user-images.githubusercontent.com/346308/63119772-c0d7bc00-bf55-11e9-97bc-2a6460d89b7a.png)

![Screen Shot 2019-08-15 at 11 59 31 AM](https://user-images.githubusercontent.com/346308/63119794-c7feca00-bf55-11e9-90f4-fd8ad1812831.png)

![Screen Shot 2019-08-15 at 11 59 51 AM](https://user-images.githubusercontent.com/346308/63119809-ce8d4180-bf55-11e9-9df3-4bf4e33e093d.png)

### Alternatives/workarounds
Currently FusionAuth generates a link, this is satisfactory, but also requires re-opening the app in another tab, or possibly from mobile etc which just feels more clunky

### Additional context
I think this should be pretty clear

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the excellent description @zbruhnke, I think this would be a nice addition to FusionAuth. 

Displaying the link link and the code within the email template as shown in the example above would be possible today, this would all depend upon how you style the template. 

The high entropy code we send today is long and complex on purpose - but as you point out it makes it less useful if you want a user to stay within the app or on the web page and just check their email, glance at a 4, 6 or 8 digit number and type it into a form to continue. 

So perhaps we need to add some additional configuration around this to allow you to specify how you would like to generate codes. For example to fit your use case, we could allow you to select numeric, and then specify the number of digits you'd like to generate.

**Comment by zbruhnke** [comment]
super helpful thoughts @robotdan I think having it both ways and a setting for a 4,6 or 8 digit number would be ideal.

Based on how you're describing this its not clear if this would this keep the link generated a long code and the digits just for typing in or change both?

**Comment by robotdan** [comment]
Could go either way, but I think the simpler approach would to make them the same. 

For example, today we generate a long code, and build an email using a template. That template builds a link with the code on the end of the link. When the user clicks on this link the code is consumed and verifies the users email address. 

A possible change would be allow you to configure how this code is generated. You would be able to configure this to generate a numeric code, 6 digits long. In this scenario, we generate the code, 6 digits in length, and send it in the email template. 

Once the user receives the email template, they could still click on the link if that is how you present it to them, or visually review the code and type it into a web form. 

The way the email template is rendered and what it contains is up to you, that is all within our email template system. We simply build a template by providing the user, and the code.
https://fusionauth.io/docs/v1/tech/email-templates/email-templates

For example, here is our stock email template for Verify Email


```html
To complete your email verification click on the following link.
<p>
  <a href="http://localhost:9011/email/verify/${verificationId}">
    http://localhost:9011/email/verify/${verificationId}
  </a>
</p>
- FusionAuth Admin
```

Here we just build a link, but you could modify this to say 

```html
To complete your email verification click on the following link or type the code into the form as you've been instructed
<p>
  Option 1. Click on the following link:
  <a href="http://localhost:9011/email/verify/${verificationId}">
    Click on this link to verify your email address!
  </a>

  Option 2. Type the following code into the form:
   ${verificationCode}
</p>
- FusionAuth Admin
```

**Comment by zbruhnke** [comment]
ah ok cool - yep this makes sense to me - I like it either way, I was thinking leaving the link code longer might be better just to keep people from guessing it mainly since it would be a fairly short url and there could be potential security implications with someone typing in a link that randomly "verifies" some person they do not even know and lets them into the account but maybe im being paranoid?

**Comment by masidiq** [comment]
Hallo

Is the TOTP For email confimation is ready now ?

Becuase on documentation i didnt see the TOTP verification.

Thanks

**Comment by zbruhnke** [comment]
yep! we've been using this for months! it works great, you can configure it in your Tenant settings

Just go to the advanced section and see the `External Identifier generation` section

https://go.hmb.la/j5Lu0H
