### ISSUE TITLE
back to maintenance mode

### ISSUE THREAD

**Issue by Andreasefstathiou** [FusionAuth/fusionauth-issues#2692]
while i was working on my local host and local server it pushed me back to maintenance mode and i cannot pass it through. This was after restart of my local server which is windows 2019. I have checked mysql server and its running on port 3306. I have checked connector and its in the app library directory. I have checked in logs and what i see is caused by:java.net.SocketTimeOutException 30.000 miliseconds timeout on connection http-outgoing-698 [ACTIVE]. A day before it was ok and working on http://localhost:9011
Can anyone assist?

**Comment by mooreds** [comment]
Hiya @Andreasefstathiou . Thanks for using FusionAuth!

This seems like a support request. 

If you have a support plan, please [open a ticket](https://account.fusionauth.io/account/support/).

If you do not, please post in our [community forum](https://fusionauth.io/community/forum/).

I'm going to close this issue out.
