### ISSUE TITLE
Seeing occasional server 500 when using the portal

### ISSUE THREAD

**Issue by shuurai** [FusionAuth/fusionauth-issues#270]
## url/admin/proxy-config-test fails when using the portal

Version: 1.7.2

### Description
When using the portal interface, occasionally, I see 
url/admin/proxy-config-test   POST giving 500 status code.

While the 
url/admin/proxy-config-test   GET call is always successful.

Not sure what this is for and why it fails.

**Comment by robotdan** [comment]
Thanks for letting us know, I'll look at it. The `/admin/proxy-config-test` is used to test for your proxy configuration to ensure it is correct. 

We open an iframe and post to ourselves so we can check the headers that a proxy is adding to ensure they are provided and correct.

**Comment by robotdan** [comment]
If you see a `500` can you check the logs to see if you see a stack trace?

**Comment by robotdan** [comment]
Please re-open if you see this again and capture any exceptions you find in the log. Thanks!

**Comment by ceefour** [comment]
@robotdan this shows up in 1.23.3 (Development mode), is it normal?

![image](https://user-images.githubusercontent.com/24123/107611831-754fbc80-6c77-11eb-94b7-cd97b6d983fe.png)

**Comment by mooreds** [comment]
@ceefour can you please open a new issue? I think we've seen something like this, but couldn't find an open issue.

**Comment by robotdan** [comment]
The `[object Object]` is back!? 🤯

**Comment by robotdan** [comment]
> @ceefour can you please open a new issue? I think we've seen something like this, but couldn't find an open issue.

Yes, please do - and if you can capture the HTML in the inspector.. I think I have an idea what is occurring.
