### ISSUE TITLE
Allow password minimum and maximum rules to be the same value

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2704]
### Problem

Right now, you can set up password minimum and maximum rule lengths on a tenant. However, the maximum must be greater than the minimum value. If you want to require a password to be exactly 20 characters, then you can't enforce that using these password rules. In the admin UI, you get an error message if you try to set up an exact character count. (I didn't try with the API.)

<img width="913" alt="Screenshot 2024-04-02 at 9 34 30 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/f1e6129e-1923-4fa7-b673-f585d79d5687">

From reading the code, the min value checks that the character count is greater than or equal to the value, and the max value checks that it is less than or equal to the value.

### Solution

Allow the min and max values to be the same.

### Alternatives/workarounds

Client side validation? Set the min to 20 and the max to 21?

### Additional context

This came up on a customer kickoff call.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Probably no reason not to allow this, but seems really unlikely that anyone would have a legit reason to require a password length of exactly `n`.

**Comment by mooreds** [comment]
Is there a material difference between setting it to 19 and 20 (for the min and max values) and only 20? (For example?)

**Comment by robotdan** [comment]
> Is there a material difference between setting it to 19 and 20 (for the min and max values) and only 20? (For example?)

No probably not. But that would also be a poor configuration. So we could go the other way and require a delta between the min and max. to encourage FusionAuth users to use more secure configurations. 

In practice, I see little reason to ever reduce the maximum length below the maximum allowed value. The maximum will be 256 for most algorithms, and 50 for Bcrypt.

**Comment by mooreds** [comment]
> Did client have a use case for this, or was it just an observation?

Client was sending passcodes over SMS and they were limited to exactly N characters.

Not a big deal, since they'd only send N characters and can enforce it on the front end (via JS on themes) but they were looking to lock things down on the back end as well.

**Comment by robotdan** [comment]
> Client was sending passcodes over SMS and they were limited to exactly N characters.

Ok. Perhaps we are thinking of different things. 

Is the customer thinking of the configuration for SMS one time codes? I hope nobody is sending their users plain text passwords over SMS.

**Comment by mooreds** [comment]
Ooh, good point. I may have misspoken. I reviewed notes and think it was a OTP, which is configured in an entirely different way. My bad. I think we can close this issue out.
