### ISSUE TITLE
Application roles should have "scopes" field

### ISSUE THREAD

**Issue by shuurai** [FusionAuth/fusionauth-issues#271]
### Problem
I want to use FusionAuth to create a "service user" role for an application service to call another application. Right now, it has to be hard coded in lambda.

### Solution
Create a field (list) as part of the Application Edit functionality (admin and API) so that scopes can be selectively attached to each role.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Not sure I understand this request. 

If this use case is still valid, please re-open with a use case and some additional details around how this would be used and what problem it solves. 

Thanks!
