### ISSUE TITLE
Clicking "discover endpoints" 4 times in rapid succession on the OIDC identity provider creates broken UX

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2718]
### Description 

You can break the admin UI UX by clicking rapidly on the "discover endpoints" label.

### Observed versions

1.48.3, 1.49.2

### Steps to reproduce

1. Go to Settings -> Identity Providers and create a new "OpenID Connect" provider
2. Scroll down and click on the "discover endpoints" label 4 times as fast as you can.
3. You end up with the screen shown in the screenshot.

### Expected behavior

You always see either the issuer field or the authorization/token/userinfo endpoint fields, never all or none.

### Screenshots

<img width="1370" alt="Screenshot 2024-04-18 at 11 36 32 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/8bd18eca-e949-4a1b-9d39-1db532158092">

### Workaround
Don't click so fast, or refresh the page to correct the UI state. 

### Platform

Saw this on FF/mac and Chrome/mac against sandbox.fusionauth.io and locally

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Workaround is to reload the page, which resets state. This works, but you lose everything you entered.

**Comment by robotdan** [comment]
Interesting. Generally speaking we debounce these clicks to avoid this scenario, so we are either not de-bouncing this request, or you broke our de-bouncer! 😎

**Comment by robotdan** [comment]
Can recreate. Looks like the issue is if you use the field label to toggle, we do not de-bounce that event.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/474
