### ISSUE TITLE
Bulk User Import API - Incorrect detection of Base64 encoded salt

### ISSUE THREAD

**Issue by tombeany** [FusionAuth/fusionauth-issues#272]
### Description 

We are using the [Import Users API](https://fusionauth.io/docs/v1/tech/apis/users#import-users) to transparently migrate users from one legacy application into fusion auth. This on the whole works great. However we have noticed when using a salt of 4 characters (the users username) fusion auth rejects the import with a 400 BadRequest and has an field error of "salt is invalid and must be Base64 encoded".

We have reproduced this several times and it appears to occur when the salt after being base64 encoded is padded with '=' characters. So it appears the base64 detection code is not 100% accurate

### Steps to reproduce
1. Using either Postman or C# FusionAuth client 
2. Create an [Import user request](https://fusionauth.io/docs/v1/tech/apis/users#import-users) POST /api/user/import
3. Base64 encode the word 'luke' which equals 'bHVrZQ=='
4. Set the base64 encoded value as the salt
6. Send the POST request
7. Observe a response of 400 with field error "salt is invalid and must be Base64 encoded"

### Expected behavior
Base64 encoded salt values should be valid and not return an error 400

**Comment by robotdan** [comment]
Thanks for letting us know @tombeany this looks to be a regression from a bug fixed in 1.7.0 to support the different Base64 encoding schemed used by Bcrypt. 

https://fusionauth.io/docs/v1/tech/release-notes/

If you perform a base64 encoding w/out padding you should be able to work around the issue for now, we'll get this fixed in the upcoming release.

**Comment by tombeany** [comment]
Thank you for the swift action @robotdan we will strip the padding for now and look forward to the 1.8 release 👍 Thanks for the great work and continued support
