### ISSUE TITLE
Can't login after upgrade from 1.6.1 to 1.7.3

### ISSUE THREAD

**Issue by marcpearson** [FusionAuth/fusionauth-issues#273]
Can't login after upgrade from 1.6.1 to 1.7.3

After a successful upgrade (no error reported and database migrations to 1.7.1), i can't login anymore to the fusionauth admin UI.

My credentials are accepted, the browser is redirected with a clientId but is still loading and loading forever. The admin UI is never displayed.

How can i debug the login problem? I searched in the logs folder (fusionauth-app/apache-tomcat/logs) but found nothing about the problem

The only error i see is in the browser console about a missing javascript http://localhost:9011/js/fingerprint2.min-1.5.1.js

**Comment by robotdan** [comment]
Is there anything in the log? Also, if you're using a theme, can you try bypassing it and see if that works? (it is possible a theming issue is keeping the template from rendering properly)


https://fusionauth.io/docs/v1/tech/tutorials/login-theme#handling-failures

> `&bypassTheme=true` to the end of the URL and hit the Enter key. This should render the default login page that ships with FusionAuth and allow you to log in and fix any errors you have.

**Comment by marcpearson** [comment]
Thanks Daniel

The problem has been resolved with your tip (or/and a server reboot)
