### ISSUE TITLE
Checking for user.roles if it is equal to a specific role and based on that determine the URL Forgot-Password

### ISSUE THREAD

**Issue by EssamKayal96** [FusionAuth/fusionauth-issues#2731]
I have a case where I have two websites for the same Fusionauth application

So I am trying to differentiate the Reset-Password URL based on the role 

how can I achieve such a case in the template.

I have tried this 

```
[#if user.roles?? && "client" in user.roles]
<a href="https://test.com/${changePasswordId}">
      Reset Password
    </a>
[#else]
<a href="https://test.com/${changePasswordId}">
      Reset Password
    </a>
[/#if]
```

and it refuses to render.

Any help here !

**Comment by mooreds** [comment]
hi @EssamKayal96 ! Thanks for using FusionAuth.

If you are looking for technical support, you should either use the [forum](https://fusionauth.io/community/forum/) or [open a support ticket](https://account.fusionauth.io/account/support) (if you have a plan with support).

More details here: https://fusionauth.io/docs/operate/troubleshooting/technical-support

Closing this issue.
