### ISSUE TITLE
[Bug]: Attempting to sort API keys by key value produces error in admin UI

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2738]
### What happened?

Clicking the column header to sort API keys by the key value in the admin UI produces a 500 server error.

![image](https://github.com/FusionAuth/fusionauth-issues/assets/3409780/3d5f2d7d-bc71-4af0-9bc5-eeeaa156bd6e)

![image](https://github.com/FusionAuth/fusionauth-issues/assets/3409780/7cd6011e-d3a6-4f60-9629-fbda593c81eb)

Clicking the header should sort the available API keys by the key value.

### Alternatives/Workaround

If the admin UI ends up in this state, it can be resolved by clearing cookies or deleting the `io.fusionauth.app.action.admin.apiKey.IndexAction$s` cookie.

### Version

1.50.0

### Affects Versions

\>= 1.45.0

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/461
