### ISSUE TITLE
Hosted Backend APIs to Incorporate `login_hint` and `idp_hint`

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2742]
### Problem
Our hosted pages will complete a call to the `oauth2/authorize` endpoint.  Our current implementation does not allow you to pass hinting parameters from `/app/login` which would ultimately be caught by the hosted pages (`oauth2/authorize`).  

### Solution
Ensure that the `app/login` endpoint can accept the `login_hint` and `idp_hint` parameters.

### Additional context
Customer observation on ticket - 74589

https://fusionauth.io/docs/lifecycle/authenticate-users/identity-providers/#hints

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Internal:

Allow passing `idp_hint` and `login_hint` to `/app/login` to be passed along to `/oauth2/authorize`. Same goes for `/app/register`.

**Comment by alex-fusionauth** [comment]
Some people would like additional custom params sent as well for things like Google GTM. We should be forwarding all parameters to the `/oauth2/authorize` endpoint.
