### ISSUE TITLE
[Bug]: 504 Gateway Error when loading users into FusionAuth Cloud Instance

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2750]
### What happened?

Saw this error intermittently when loading 50k users at a time into a large HA FusionAuth cloud deployment. Usually happened after the 3-4th load

```
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

Nothing showed up on the cloud watch monitoring.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-504-issues

### Version

1.50.1

**Comment by robotdan** [comment]
This seems like a performance or sizing question? If we exhaust system resources, or db resources such that the load balancer can't service the request, this will happen. But I don't know that it is a bug.

**Comment by mooreds** [comment]
Fair.
