### ISSUE TITLE
Revoke device trust for all users on device

### ISSUE THREAD

**Issue by spwitt** [FusionAuth/fusionauth-issues#2753]
### Description
Automatically revoke device trust for all users on a device in certain scenarios.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mrudatsprint** [comment]
@spwitt Would #2706 be related to this issue?

**Comment by spwitt** [comment]
The two issues are both related to the device trust token, but this one is about automatically revoking the device trust tokens rather than providing the ability to revoke them via the UI.

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/460
