### ISSUE TITLE
[Bug]: Acquisition channel data is not coming back

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2754]
### What happened?

In 1.50, we added a field asking how folks had heard about us. This should be sent off to a FusionAuth server.

Currently, we are getting data back, but not all the time, even for instances that we know are 1.50.1. I tried to skip this question when going through the setup wizard, but didn't see a way to do it.

Internal: https://inversoft.slack.com/archives/C0407G6V5/p1716307195199919

### Version

1.50.1

**Comment by robotdan** [comment]
@mooreds this is probably more of an internal issue, so my guess is that it was handled in Linear. 
@lyleschemmerling is this fixed? If so, we need to somehow link this back to a PR or a linear task.
