### ISSUE TITLE
Does calling /token with grant_type=refresh_token ever return a new refresh_token ?

### ISSUE THREAD

**Issue by badaz** [FusionAuth/fusionauth-issues#276]
### Description
I am trying to use fusionauth as an oauth server. In some implementations I have used in the past, calling /token with grant_type=refresh_token would always return a newly generated refresh_token along with the new access_token. I saw that some other implementations only return one if current refresh_token will expire sooner than the new access_token. I cannot seem to find any hint in fusionauth doc about this. So my question is : Does calling /token with grant_type=refresh_token ever return a new refresh_token ? If so, what are the conditions to get a new refresh_token?

**Comment by badaz** [comment]
Thanks for the quick answer, but maybe I was not so clear about what my problem is. When I send a post to /token with grant_type=password, I get a new access_token and a new refresh_token, but when I send a post to /token with grant_type=refresh_token,  then I only get a new access_token, and no refresh_token. Is there a way to ask for a new refresh_token with grant_type=refresh_token?

**Comment by robotdan** [comment]
Thanks for the clarification, perhaps I misunderstood the question. 

We do not currently issue a new refresh token during the `refresh_token` grant. If the refresh token you sent is valid you'll get a new `access_token` back. Once your refresh token expires, you'll need to request a new one by requiring the user to authenticate again. 

If we were to issue a new - or "refreshed" (updated expiration) each time you used the refresh token to gain a new access token using the `refresh_token` grant - that would effectively provide a sliding window session. This would allow for a perpetual use token which we do not support.

**Comment by badaz** [comment]
Not exactly perpetual since the refresh token would expire eventually if not used for a long time. I am not a security specialist however and it might be a bad practice, but I use this kind of system in a mobile app of mine in order to prevent user disconnects except if they have not used the app for a long time. Maybe I have not grasped the real purpose of fusionauth and using it to replace an app's oauth server is not what it should be used for? Or maybe my usage of oauth is not right. I am going to keep looking for the best solution. Thanks again.

**Comment by raz0r777** [comment]
Hello , when my access_token expires i get 401 Not authorized . When i get 401 i call request with grant_type=refresh_token. on /Token, but i get Bad Request Error . This gave me on response:
{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent,

Headers: {

Cache-Control: no-cache

Pragma: no-cache

Server: Microsoft-IIS/8.5 X-Powered-By: ASP.NET Date: Wed, 08 Apr 2020 17:11:41 GMT Content-Length: 25 Content-Type: application/json; charset=UTF-8 Expires: -1 }
}

**Comment by raz0r777** [comment]
I'm creating a mobile app which 
use Web Api 2
