### ISSUE TITLE
FusionAuth Setup Wizard Error

### ISSUE THREAD

**Issue by PsycloneTM** [FusionAuth/fusionauth-issues#2762]
### Description
After installing everything as it told me and adding my postgres it says I've gotten an unexpected error

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

![image](https://github.com/FusionAuth/fusionauth-issues/assets/27637025/7313d3c2-2326-443a-8ea8-0488ac63978f)
![image](https://github.com/FusionAuth/fusionauth-issues/assets/27637025/e05298a4-e7a6-481a-82d0-d8ff5ba868fd)

**Comment by robotdan** [comment]
The exception in the log would indicate you have another service running on `9012`.  You'll need to ensure that port is available to FusionAuth, or you can optionally change it using the configuration. 

See `fusionauth-app.http-local.port` in the config reference if you need to change it. 
- https://fusionauth.io/docs/reference/configuration
