### ISSUE TITLE
Kickstart not usable because of default email templates added

### ISSUE THREAD

**Issue by avwie** [FusionAuth/fusionauth-issues#2763]
##Kickstart not usable because of default email templates added

### Description 
When using a Kickstart file a few "[FusionAuth Default] Two Factor" email templates are added automatically, with randomized guids. This makes it impossible to manage these files via a Kickstart file.

### Observed versions
1.44

### Affects versions
1.44

### Steps to reproduce
1. Create basic kickstart file
2. Run FA
3. Multiple email templates are automatically added

### Expected behavior
No email templates available

**Comment by mooreds** [comment]
Thanks for filing this issue!

Does this behavior occur on the latest release (1.51.0)?

**Comment by robotdan** [comment]
In general we don't set up email templates when you are using Kickstart - or we shouldn't.  

But in version `1.42.0` we did add two email templates with the following names. 
- `[FusionAuth Default] Two Factor Authentication Method Added` 
- `[FusionAuth Default] Two Factor Authentication Method Removed` 

And it looks like these are being added regardless if you use Kickstart, so this may be a bug. Can you confirm which templates you are seeing added?

**Comment by andrewpai** [comment]
@avwie this was fixed as a side effect of other feature work in FusionAuth version `1.53.0`, and is not reproducible in versions `1.53.0` and later.
