### ISSUE TITLE
stuck on database configuration

### ISSUE THREAD

**Issue by UmangThapliyal** [FusionAuth/fusionauth-issues#277]
Hello,
I installed using fastPath and then everything works fine but by mistake the folder got deleted I installed it again and if I am trying to do database configuration it is throwing error, but the same worked first try.
![image](https://user-images.githubusercontent.com/34316267/63849958-ba632e80-c9b0-11e9-9e8b-1f9bb2a506cb.png)

**Comment by pushoo-sharma** [comment]
Your Mysql Server should be running and you must see that the password should match exactly with the
password of MySQL server. 
 
You can use this command to verify on mysql shell.

`mysql -u <rootuser> -p<password>`

**Comment by UmangThapliyal** [comment]
> Your Mysql Server should be running and you must see that the password should match exactly with the
> password of MySQL server.
> 
> You can use this command to verify on mysql shell.
> 
> `mysql -u <rootuser> -p<password>`

The password and username is correct as I am able to login from the cmd but I am not able to from fusionAuth.

I have reinstalled it and the problem is now fixed I dont know why it was behaving like that will close this issue
