### ISSUE TITLE
[Bug]: Simple Theme misses date-picker styling

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#2770]
### What happened?

When using Birthdate during sign-up the date picker is without styling.

![image](https://github.com/FusionAuth/fusionauth-issues/assets/12079732/09ec004a-276e-4eb3-b734-d103d598c60d)

### Version

1.51.0

### Affects Versions

1.51.0

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1972

**Comment by robotdan** [comment]
@lyleschemmerling we must be missing some style here, but it seems like we could or should take this opportunity and use the HTML5 data picker - ideally for both simple and advanced themes.

**Comment by andrewpai** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/454
