### ISSUE TITLE
[Bug]: Saving Simple Theme in Admin UI return 415 error

### ISSUE THREAD

**Issue by matt1hathcock** [FusionAuth/fusionauth-issues#2777]
### What happened?

When I try to save a Simple Theme in the Admin UI I get a 415 status code error.

This happens when creating a new Simple Theme from the top right button and then trying to save it as well as duplicating from the Default Simple Theme and trying to save that.

I would expect the theme in either case to save without error.

Tested on Chrome and Brave

### Version

1.51.0

### Affects Versions

1.51

_No response_

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/454
