### ISSUE TITLE
[Bug]: Custom message keys added via the simple theme editor will not persist on save

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2778]
### What happened?

If you add a key using the messages editor and save it via the UI the system will not persist the custom key value. Example `testing=test`. While this would be fine for any of the templates that we have already defined it will hinder anyone who wants to use custom registration forms with a simple theme as the will not be able to add custom message to correlate with the custom fields.

Workaround:
Uploading messages via the [Theme API](https://fusionauth.io/docs/apis/themes/simple-themes#update-a-simple-theme) will persist them. So if there are key/value pairs that you need to update to show messages on simple forms update the theme via the UI and they should persist.

### Version

1.51.0

### Affects Versions

1.51.0

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/454
