### ISSUE TITLE
[Bug]: The description for the user password reset send webhook has a typo in it

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2782]
### What happened?

It says:

```
A user has been sent an email as par of a password reset workflow
```

when it should say (note the `part`)

```
A user has been sent an email as part of a password reset workflow
```

<img width="1834" alt="Screenshot 2024-06-07 at 12 32 03 PM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/31dc9dc7-d74c-4652-a42c-965d745f1918">

### Version

1.5.10

**Comment by andrewpai** [comment]
Shipping in 1.51.1
