### ISSUE TITLE
Allow wildcards in certain redirect URLs to include all path segments

### ISSUE THREAD

**Issue by LucasPMorris** [FusionAuth/fusionauth-issues#2783]
Allow wildcard in some redirects to include all path segments

### Problem
When specifying a redirect URL (such as the Logout URL) with a wildcard it will not allow additional path segments after the wildcard. For example:

Specific URL: myappurl.com/logout/*

The following URL's will work: 
- myappurl.com/logout/link1
- myappurl.com/logout/link2
- myappurl.com/logout/whatever

These URL's will not work:
- myappurl.com/logout/link1/detail1
- myappurl.com/logout/link1/detail2

### Solution
Allow additional segments after a URL wildcard to be allowed also.

**Comment by robotdan** [comment]
This is working as designed. There are several security concerns with making wild cards behave the way you suggest. 

If a customer needs `myappurl.com/logout/link1/detail1` to be a valid Logout URL, they need to add `myappurl.com/logout/link1/detail*` as an authorized redirect.
