### ISSUE TITLE
FusionAuth TOTP verification

### ISSUE THREAD

**Issue by SaarthakGitHub** [FusionAuth/fusionauth-issues#2787]
I have to create a MFA integrated with fusionAuth
Using fusionAuth API, I have generated secret which will be used to generate QR code in nodejs

I want to know how to validate OTP enter by user so to authenticate them on fusionAuth?

**Comment by mooreds** [comment]
Thanks for using FusionAuth @SaarthakGitHub !

This seems like a support question, so please post in our forum, our slack or open a support ticket if you have a plan with support.

https://fusionauth.io/community has links to our forum and slack and https://account.fusionauth.io/account/support/ is where you'd go to file a support ticket.
