### ISSUE TITLE
[Bug]: SCIM ResourceTypes endpoint returns wrong location uris

### ISSUE THREAD

**Issue by runely** [FusionAuth/fusionauth-issues#2793]
### What happened?

The SCIM ResourceTypes endpoint (https://fusioninstance/api/scim/resource/v2/ResourceTypes) aswell as `.../User` and `.../Group` returns wrong **location** uri's

I expect that meta.location will be set to:
- _https://fusioninstance/api/scim/resource/v2/ResourceTypes/User_ for **User Account**
- _https://fusioninstance/api/scim/resource/v2/ResourceTypes/Group_ for **Group**

Instead meta.location is set to:
- _https://fusioninstance/api/scim/v2/ResourceTypes/User_ for **User Account**
- _https://fusioninstance/api/scim/v2/ResourceTypes/Group_ for **Group**

A GET request to either of the wrong location endpoints returns a `404 Not Found`

### Version

1.51.1

### Affects Versions

Greater than or equal to 1.48.3 (maybe older aswell)

**Comment by robotdan** [comment]
Thanks @runely for opening this issue! This looks to be a bug.

**Comment by robotdan** [comment]
Internal, the `ServiceProviderConfig` looks to be correct, but the `Users` and `Groups` resources are not. 

- https://github.com/FusionAuth/fusionauth-app/blob/e5f08c45f7be5aeeafc920b215dac0235b7b9e94/src/main/java/io/fusionauth/api/util/SCIMTools.java#L121
- https://github.com/FusionAuth/fusionauth-app/blob/e5f08c45f7be5aeeafc920b215dac0235b7b9e94/src/main/java/io/fusionauth/api/util/SCIMTools.java#L139
- https://github.com/FusionAuth/fusionauth-app/blob/e5f08c45f7be5aeeafc920b215dac0235b7b9e94/src/main/java/io/fusionauth/api/util/SCIMTools.java#L148

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/547
