### ISSUE TITLE
[Bug]: Simple Themes Browser preview doesn't work on Firefox

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2794]
### What happened?

To replicate:

* open up firefox on a mac
* create a new simple theme
* save it
* edit it
* go to the 'pages preview' tab
* click on 'browser preview'

Expected: you see the page as it would look

Reality: you see an unstyled page.

<img width="1834" alt="Screenshot 2024-06-20 at 9 38 15 AM" src="https://github.com/FusionAuth/fusionauth-issues/assets/91825/20bcf2e9-fee0-4b1a-92e0-fa99893fc4b0">

Note that this works fine on Safari.

### Version

1.51.1

**Comment by andrewpai** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/479
