### ISSUE TITLE
Feature: Discussion about limits and quotas

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#28]
**Is your feature request related to a problem? Please describe.**
In the future, we would like to monetize our API and also control the usage of our clients / partners.
In order to do those features, we are slowly looking at solutions to setup limit / quotas for each client.
A limit could be 30 calls per minutes when the quotas could be 50 000 calls per months.

**Describe the solution you'd like**
I was wondering if we could use the JWT validation endpoint to record this hit and we could base the limit quota on it. It does look really good since a JWT is self contained and we can validate the token without calling this endpoint.
And a hit to this endpoint does not mean there is a hit to our API....

Maybe it is designed for that right now, but since it is about the security, it is not totally illogic to have something like this in FusionAuth?
Let me know what you think.

**Describe alternatives you've considered**
We had a look to APIGee https://apigee.com that provides this kind of services.

**Comment by robotdan** [comment]
If I understand the requirement, it is to use FusionAuth to record a hit count to a particular endpoint so you can use that data to monetize or rate limit you end client?

We do have some metrics around endpoint hit counts, and these are available on the Status API or via our Prometheus endpoint. However, this status is per node, and not accumulated across all nodes in the instance, and these data is not persisted across a node restart. 

If my assumptions are correct with this requirement there are other products much better suited for this task. If I am missing a component of the requirement, or there is a good use case for containing this feature in FusionAuth, please provide some additional details. 

Thanks!
