### ISSUE TITLE
Possibility to add additional tenant_name field on login page by multi tenant approach.

### ISSUE THREAD

**Issue by unkis** [FusionAuth/fusionauth-issues#281]
### Problem
If you use a multi tenants approach in FusionAuth. For example if you have a multiple company’s (tenants), an each company has own users. It’s not possible to use FusionAuth  login page, because you don’t have a tenant_name(company name) field on login page.

### Solution
To have a possibility to add additional tenant_name field(like a company name) on login page, where the user can submit a login form with company name, user_name and password and FusionAuth can via tenant_name field choose the right tenant for authorization.

### Alternatives/workarounds
Now you need to persist the mapping application_id, tenant_id, tenant_name separately.
Build custom login page with the logic to resolve this mapping via tenant_name.

### Additional context
I want to use the FusionAuth for following use case 

https://stackoverflow.com/questions/57656971/multi-tenant-authorization-wth-fusionauth/57661739?noredirect=1#comment101833762_57661739

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
In the upcoming 1.8.0 release, the tenant name will be available in the templates as `${tenant.name}` as long as the provided `client_id` is valid, or a `tenantId` is provided as a request attribute.

**Comment by robotdan** [comment]
This should work for you in 1.8.0-RC.1.

**Comment by unkis** [comment]
hm, 
I don't understand how it should work. Can you please provide me a snippet of login form?
i mean how login form should look like if i just want to input following information:

- tenant name like "my company ltd"
- username like "bob"
- password like "my password"

thx a lot.

**Comment by robotdan** [comment]
Hi @unkis  Here is an example 

```
Tenant name: ${theme.name}
```

Review the Theme documentation for more information. https://fusionauth.io/docs/v1/tech/themes/overview. 

Thanks.

**Comment by voidmain** [comment]
I think @robotdan meant this:

```
Tenant name: ${tenant.name}
```
