### ISSUE TITLE
generateEmailVerificationId Java Client API

### ISSUE THREAD

**Issue by petechungtuyco** [FusionAuth/fusionauth-issues#282]
generateEmailVerificationId Java Client API

### Description 
I think I've encountered a bug in this specific method. It supposed to generate a verificationId without sending an email to the user. But it sends a verification email anyway. Upon further investigation, I think lies on the java client API because it adds a URL parameter **sendVerifyPasswordEmail** instead of **sendVerifyEmail** which was in the FusionAuth docs.

### Additional context
I'm currently using fusionauth-java-client version 1.6.0

**Comment by robotdan** [comment]
Thanks @petechungtuyco for letting us know! You're exactly correct. 

This will be fixed in the next release.
