### ISSUE TITLE
[Bug]: Login fails due to redirect loop after ipgrade to v1.50.x

### ISSUE THREAD

**Issue by lbarnkow** [FusionAuth/fusionauth-issues#2822]
### What happened?

We upgraded from v1.49.2 to v1.50.1 in our test environment. Database migration seemed to work out without any issues (silent mode). Login to the FusionAuth admin ui also worked as expected. However, logins for our main application stopped working.

We observed the following behavior using the "Network" tab of the firefox developer tools:
* The index page `/` for our main application redirects to itself to path `/auth/refresh`
* `/auth/refresh` redirects to the FusionAuth `/authorize` endpoint with `redirect_uri=https://test.app.domain/auth/callback`
  * Cookie `fusionauth.sso` is set and has `Max-Age=2147483647`
* After submitting credentials using the login form the `/authorize` endpoint redirects to the `/consent` endpoint; `redirect_uri` still intact with path `/auth/callback`.
* `/consent` endpoint redirects (http status 302) to `https://test.app.domain/`, however, **omitting** the path originally specified when the flow started.
* This basically takes us back to the first step again and Firefox gives up after a couple of rounds.

At first we hoped this was similar to issue #2736, however, this was not the case. The sso timeout mentioned there and in the release notes was set to 3600 (default value?). Also they described being redirect from the `/consent` endpoint back to the `/authorize` where they had to fill out the login form again.

We also tried to upgrade to v1.51.2, but still faced the same issue.

We deploy FusionAuth using the [Helm Chart](https://github.com/FusionAuth/charts). We didn't observe any errors in the logs?

Please advise on how to debug / diagnose the problem further? Also what other information can we provide to help pinpoint the issue?

### Version

1.50.1

### Affects Versions

\>= 1.50.0

**Comment by lbarnkow** [comment]
We found our issue and it's not a FusionAuth bug, but a misconfiguration on our end. The reverse proxy in front of our FusionAuth deployment only allows a handful of defined paths to be requests and we had failed to allow the `/consent` endpoint.

**Comment by mooreds** [comment]
Thanks for closing the loop, @lbarnkow
