### ISSUE TITLE
[Bug]: Simple Theme - Birth date form does not respect localization date-format

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#2823]
### What happened?

Date picker and date form field when selecting birth date do not take localization in to account. 
In addition to that the date picker and field are in a different format.

## German

![image](https://github.com/user-attachments/assets/1b791876-8c44-4805-a776-10104707e3e5)

```
date-format=d.M.yyyy
date-time-format=d.M.yyyy HH:mm z
date-time-seconds-format=d.M.yyyy HH:mm:ss z
```

## English

![image](https://github.com/user-attachments/assets/7569806f-878d-4dd1-a4b0-f599ed3669d0)

```
date-format=M/d/yyyy
date-time-format=M/d/yyyy hh:mm a z
date-time-seconds-format=M/d/yyyy hh:mm:ss a z
```

### Version

1.51.2

### Affects Versions

1.51

**Comment by Aaron-Ritter** [comment]
![image](https://github.com/user-attachments/assets/912b6674-fde9-44c4-994f-3d8e43682155)
still a issue for form field in 1.52

**Comment by robotdan** [comment]
Closing under https://github.com/FusionAuth/fusionauth-issues/issues/2770 which switched to the HTML 5 native date picker. Please re-open if you can recreate.

**Comment by Aaron-Ritter** [comment]
@robotdan I recreated it on 1.52.1, just to be very precise it's not the date picker itself but the field which does not respect the locale.

**Comment by Aaron-Ritter** [comment]
OK we did some additional tests and we agree that the issue is solved. It's the issue that my browser was English(US) and the picker and the field is based on the browser. And from what we understand it can't be overwritten by the manual language select on the login screen https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date.
