### ISSUE TITLE
fusion auth 1.7.4. Startup error

### ISSUE THREAD

**Issue by sjswami** [FusionAuth/fusionauth-issues#283]
Getting exception as following
![image](https://user-images.githubusercontent.com/47114533/64424780-9944c100-d0c7-11e9-97e0-ce41e814d4f8.png)

**Comment by robotdan** [comment]
This looks to be an upgrade or install issue. How did you install / upgrade FusionAuth to 1.7.4?

**Comment by sjswami** [comment]
I followed https://fusionauth.io/docs/v1/tech/installation-guide/upgrade, Section no 2

**Comment by robotdan** [comment]
Assuming Linux? Ensure that `./web/WEB-INF/lib` has that jar, if it doesn't there looks to be have been a failure when you unzipped the packages.

**Comment by sjswami** [comment]
The file is present, but different version. In order to workout, I changed the file name.

**Comment by robotdan** [comment]
Ah, ok. So it sounds like you upacked the new zip on top of the existing directory.

Make sure you follow the delete instructions that are part of the upgrade. 

```
# Delete or move existing installation
cd /usr/local/fusionauth
rm -rf ./fusionauth-app
```

If you deleted that directory, you would not have multiple versions of the same jar.

**Comment by sjswami** [comment]
I did the same, removed the existing folder except config
