### ISSUE TITLE
Passwordless login API verify code stage issue (/api/passwordless/login endpoint)

### ISSUE THREAD

**Issue by kevin-hv** [FusionAuth/fusionauth-issues#2832]
### Description
The /api/passwordless/login endpoint returns a 404 error even though the right code is supplied and users cannot log in.

A bit more details:

- I have an application set up with Passwordless login enabled
- I have registered a user with the help of the /api/user/registration/ endpoint
- I have started the passwordless login on the following endpoint: /api/passwordless/start
  -  With the following body: loginId: "-user's email address-" response_type: "code", scope: "openid", state: "CSRF123", client_id: "-the application id-", redirect_uri: "-the redirect uri of the app-"
- I'm sending out the magic link email with the following endpoint /api/passwordless/send
- The user gets the email with the link
- The user tries to verify the code that is there on the link in the "code" query parameter with the /api/passwordless/login to finish the login
  - With the following data in the body of the post request: code: "-The code which FusionAuth sent in the query parameter of the passwordless sign in link-" , applicationId: "-the application id-"

I have tried to follow closely the documentation I have found: https://fusionauth.io/docs/apis/passwordless

But it seems to fail at the last step, and I have no idea why, whether this is an issue with FusionAuth, or I have missed something in the process.

Thank you in advance for your time and attention.

**Comment by kevin-hv** [comment]
I have found out what I have done wrong.

The email template ([FusionAuth Default] Passwordless Login) with which the email is sent to the user is, containing the following url:

http://localhost:9011/oauth2/passwordless/${code}?tenantId=${user.tenantId}

If the user taps on this URL, and finishes login on the FusionAuth provided website, their code will already be used, and when the Authorized redirect URL will move the user to my native mobile app the code cannot be used anymore as it was already burnt.

How I have solved this is that I have created a new email template with the following:

<Authorized redirect URL>?code=${code}&tenantId=${user.tenantId}

This way the code is not burnt, my app can grab it and forward it to the /api/passwordless/login endpoint and I am able to get a token.

(extra info, the Authorized redirect URL is a universal link for my app, so that when a user has it on their phone the app opens and I can consume the code and send it back to the auth server in exchange for a JWT refresh & access token)

---------

I will leave this issue open, as I suspect I am doing something wrong here and this might not be the ideal way of doing things, maybe somebody with more experience can correct my way of thinking about how to use these APIs properly.

**Comment by mooreds** [comment]
Hi @kevin-hv ! Thanks for filing an issue. We try to keep GitHub issues for features and bug requests, and have discussion around implementation details take place on our forum: https://fusionauth.io/community/forum/ 

You might want to post your questions there.

**Comment by kevin-hv** [comment]
Thanks @mooreds , yeah I only posted here originally as I was not sure I got it wrong, or it's a bug. But I'm fairly convinced now that it is not an issue, just lack of understanding from my part. I will close the issue then and post to the forums, Thanks ^^.

**Comment by mooreds** [comment]
Thanks, appreciate it!
