### ISSUE TITLE
When Self service registration is turned off Login with google should also block registration

### ISSUE THREAD

**Issue by sjswami** [FusionAuth/fusionauth-issues#284]
### Description 
Home->Settings->Application->Edit->Registration
When self service registration is disable
![image](https://user-images.githubusercontent.com/47114533/64429812-7cfb5100-d0d4-11e9-8f0a-32305e998689.png)

And unregistered user tries to login with google in that application. It must be blocked like 
![image](https://user-images.githubusercontent.com/47114533/64429683-2aba3000-d0d4-11e9-83f3-bd368736b31e.png)

### Steps to reproduce
1. Disable Self service registration
1a. Initital state of user
![image](https://user-images.githubusercontent.com/47114533/64430222-6b667900-d0d5-11e9-96af-92616eb05d7c.png)

2. login to using fusionauth with above disable application
3. Login is successful
4. At user->registration you can see an application is added.
![image](https://user-images.githubusercontent.com/47114533/64430279-951fa000-d0d5-11e9-89f3-68fae2defb85.png)

### Expected behavior
It must show below like error. Behavior like login to the admin portal of fusion auth.
![image](https://user-images.githubusercontent.com/47114533/64429683-2aba3000-d0d4-11e9-83f3-bd368736b31e.png)

### Additional context
Version 1.7.4

**Comment by robotdan** [comment]
Hi @sjswami this is working as designed. 

Self service registration will allow the user to create their own account and register all on their own. This is a separate feature from Social Login via Google. 

When you enable Login with Google for the FusionAuth application we will show the login button. When a user logs into Google we then reconcile that User to FusionAuth, this means we create the user if they do not yet exist. 

The second step of this process is to see if they need to be registered to the application they are logging into - in this case the FusionAuth application. The FusionAuth application does not allow registration to occur through a third party login such as Google. This is why you then see this message that the user does not have permission. 

The user gets created, and then we do not register them, but once they are redirected back to FusionAuth we see that the user is not registered to FusionAuth so show that message.

**Comment by sjswami** [comment]
Thank you,

Option at Identity provider "Create Registration" Solved my purpose.

**Comment by sjswami** [comment]
One problem with this. The registration is not created by login with google. But still the redirection to application site happens. 

I want to stop access if there is no registration.

How can I achieve like fusionauth ?

**Comment by robotdan** [comment]
The user is not authorized, so this is the same as if the user is registered, but does not have the proper role to continue. 

FusionAuth returns a parameter on the redirect called `userState` which is a hint to tell you if the user is registered or not. 

For example, see 3.2 in this workflow
https://fusionauth.io/docs/v1/tech/oauth/overview

This comes back as `&userState=Authenticated` or `&userState=AuthenticatedNotRegistered`. 

This parameter is not part of any spec, we made it up to help the caller to get a hint more quickly. The only spec way to do this is to obtain the claims returned by FusionAuth. 

A normal workflow for OpenID Connect will be to complete the token exchange, and then send the access token to the Userinfo endpoint. 

The Userinfo endpoint will return claims about the user that was authenticated. 
https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo

If the user is registered, there will be an `applicationId` claim, and optionally `roles` if they have any for the application in question. 

If the user is authenticated but not registered, they will not have an `applicationId` claim.

The FusionAuth UI login does exactly this, we collect the roles returned for the user and if they do not have any, we do not complete their login and put up the error message that they do not have permission.
