### ISSUE TITLE
[Bug]: Event Log advanced search decreases start/end datetimes on every search

### ISSUE THREAD

**Issue by runely** [FusionAuth/fusionauth-issues#2843]
### What happened?

When choosing a `Start` and/or `End` datetime in the advanced section in **Event Log** and hitting **Search**, the datetimes are set back 2 hours (to compensate for UTC vs GMT (Norway) i guess).

For every subsequent searches the `Start` and/or `End` datetime is set back 2 hours which changes the timeframe for each subsequent search

### Version

1.52.1

### Affects Versions

1.52.1

**Comment by robotdan** [comment]
Thanks for reporting @rod-martens-alida - appreciate it!
