### ISSUE TITLE
API to update email verification state

### ISSUE THREAD

**Issue by gurupras** [FusionAuth/fusionauth-issues#285]
### Problem
We're migrating users into FusionAuth, and many of these users have already verified their email. Ideally, we'd like to set the`verified` field to `true` on these accounts. However, we're unable to do both during registration and via updates using `/api/user/` endpoint.

### Solution
Please provide a programmatic mechanism to update the email verification state.

### Alternatives/workarounds
No workaround AFAIK.
The closest solution seems to be `skipVerification`, but these are neither admin accounts nor internal users. Also, setting `skipVerification: true` continues to send out verification emails when performing a bulk import and also shows emails as not being verified. 

> skipVerification | Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/821
- https://github.com/FusionAuth/fusionauth-issues/issues/1319

**Comment by robotdan** [comment]
For migrating users, you'll want to use the Import API. 

https://fusionauth.io/docs/v1/tech/apis/users#import-users

It looks like we may be missing the `verified` field for this API in the documentation, but it should work. 

Can you try using the Import API and see if that works for you?

**Comment by wax213** [comment]
Hello,
In import api it works fine but what about situation when you want to migrate users with `verified=false` and after some actions(decision from another systems) update `verified` value via api?

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/118

**Comment by spwitt** [comment]
This will be resolved by #1319
