### ISSUE TITLE
Fusion auth breaks redirect url if query parameter has '@' symbol (%40).

### ISSUE THREAD

**Issue by OleksandrBasiukZap** [FusionAuth/fusionauth-issues#2852]
### Description
I'm trying to open [http://localhost:8082/accounts/create?firstName=Example&lastName=Example2&email=a%40gmail.com&phone=(111)+111-1111](http://localhost:8082/accounts/create?firstName=Example&lastName=Example2&email=a%40gmail.com&phone=(111)+111-1111)
After the auth process in the new browser tab fusion auth redirects to a broken URL
[http://localhost:8082/gmail.com&phone=(111)+111-1111)](http://localhost:8082/gmail.com&phone=(111)+111-1111)

The problem is in the email parameter and '%40' symbol. Please advise, how I can proceed with such a parameter and go ahead with a valid redirect URL?

**Comment by mooreds** [comment]
I'm not sure I understand the user case. Those don't look like FusionAuth URLs. Can you please provide more details?

**Comment by robotdan** [comment]
Please re-open if you can provide that additional detail.
