### ISSUE TITLE
have a problem with radio-button

### ISSUE THREAD

**Issue by piftai** [FusionAuth/fusionauth-issues#2854]
## (Put bug title here)

Maybe someone knows why i have a problem. I have a form and some buttons on this form. But when i use some button it brings me 500 error.

### Observed versions
List the version you are running, and any other versions you have attempted a recreated. 

### Affects versions
The version, or versions where this bug exists. If you do not know, please leave blank for now. 

### Screenshots
If applicable, add screenshots to help explain your problem. Delete this section if it is not applicable. 

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
@piftai thanks for using FusionAuth!

It looks like you are looking for some support. 

The best way to get support is to either open a support ticket or post to our forum. I'm going to close this issue out.

If you have a bug with replication steps, please feel free to re-open.

You can learn more about bugs vs support requests here: https://fusionauth.io/docs/operate/troubleshooting/technical-support
