### ISSUE TITLE
Update first time setup wizard for community licensing

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2859]
### Description
> Activating your license gives you access to everything you've purchased. You can find your license key in your [FusionAuth Account](https://account.fusionauth.io/account/plan/). If you are using the community version, just skip this step and enjoy FusionAuth!

This copy should be updated for the FusionAuth Community licensing options. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2662

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by hjaret** [comment]
@robotdan Do you simply want to update the description text on this tab to include more info about community licensing like this:

Activating your license gives you access to everything you've purchased. You can find your license key in your [FusionAuth Account](https://account.fusionauth.io/account/plan/). If you are using the community version, you may skip this step and still enjoy FusionAuth. However, completing this step enables you to access additional features and, optionally, obtain product support!

Or should the tab match the functionality of the Reactor tab where it includes this info and also gives you links to create a license, etc.?
