### ISSUE TITLE
[Bug]: FusionAuth version 1.53.0 breaks WebAuthN

### ISSUE THREAD

**Issue by alex-fusionauth** [FusionAuth/fusionauth-issues#2861]
### What happened?

When accessing the WebAuthN ajax call I am getting a 400 response in 1.53.0. If I go back to 1.52.0 I don't have this issue.

I have tried on our localhost
http://localhost:9011/oauth2/webauthn-reauth-enable
also 
https://local.fusionauth.io/oauth2/webauthn-reauth-enable
also
https://sandbox.fusionauth.io/oauth2/webauthn-reauth-enable

They all result in a 400 bad request.

This is happening in Brave, Chrome, and Safari.

### Version

1.53.0

**Comment by spwitt** [comment]
Internal
* https://linear.app/fusionauth/issue/ENG-1583/[bug]-fusionauth-version-1530-breaks-webauthn
