### ISSUE TITLE
[Bug]: Kickstart webhook in kickstart.json

### ISSUE THREAD

**Issue by alex-fusionauth** [FusionAuth/fusionauth-issues#2863]
### What happened?

I would like to be able to define a webhook in my kickstart.json file specifically for the `kickstart.success` event. It seems based on what I've read so far this is possible. I have the following kickstart config:

```json
{
  "variables": {
    "apiKey": "2fbf8fbf-32bb-456e-a71e-24830dd82866"
  },
  "apiKeys": [
    {
      "key": "#{apiKey}",
      "description": "Unrestricted API key"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "/api/webhook",
      "body": {
        "webhook": {
          "connectTimeout": 3000,
          "global": true,
          "readTimeout": 3000,
          "description": "Kickstart Sucess Webhook",
          "eventsEnabled": {
            "kickstart.success": true
          },
          "url": "https://webhook.site/bec11612-a727-4ff8-88f1-73d733b5eaca"
        }
      }
    }
  ]
}
```

When my docker container starts up I do see that the kickstart is executed:

```
---------------------------------------------------------------------------------------------------------
-------------------------------------------- Kickstarting ? --------------------------------------------
---------------------------------------------------------------------------------------------------------
2024-09-06 07:33:15.036 PM INFO  io.fusionauth.api.service.system.kickstart.KickstartRunner - Summary:
  - Created API key ending in [...2866]
  - Completed [POST] request to [/api/webhook]
```

However, the hook is never called. (If it is and there's an error I don't see that either).

Note that I have no tenants or applications at this point: just initial the API key (and I confirmed that I can call the API using this key after kickstarting completes). 

I have also set the `global: true` option in the webhook body as the documentation indicates this is required in order for the hook to get called when there're no tenants.

I can also confirm that a `curl` POST to the webhook URL from within the running FusionAuth container does reach that webhook.site URL.

Am I going about this correctly?

### Version

1.53.0

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/529
