### ISSUE TITLE
PATCH /api/user/registration calls clear out registration.data fields

### ISSUE THREAD

**Issue by JoshTheHero** [FusionAuth/fusionauth-issues#2866]
### Description 
When you make a PATCH call to update user registration, it wipes out the fields in registration.data. I only updated other fields in the call such as roles but it would clear out the registration.data 

### Observed versions
1.51.2 and 1.52.1

### Steps to reproduce
1. Make a user with a custom registration.data field, registered for an application
2. Make a PATCH api/user/registration call to update something in that user's registration such as "role"
3. The registration.data field will come back blank with no fields. 

### Expected behavior
For the registration.data fields to be unaffected after making a PATCH call that does not update them. 

### Platform
Using Insomnia for the API calls on a FA Cloud instance.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Can you please provide additional recreate steps please? For example, how are you using `PATCH` - what `Content-Type` are you using? This will be important to the behavior of the API. 

Please provide example JSON request bodies that you have used to test.
