### ISSUE TITLE
Allow for single use refresh token to be successful during mulitple refresh requuests in short window (reuser internal)

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2867]
### Problem and Solution
- I have a front end app.  
- Sometimes my App will make closely spaced calls/simultaneous calls to refresh the AT/RT tokens. Using a `one time use` refresh token policy, the first call will get a new AT/RT.  Simultaneous calls will fail (as the RT will rotate values).

### Solution 

I would like for simultaneous requests to refresh the AT using a one time usage policy (for refresh tokens) to succeed for a configurable duration (less than one minute), while my front end apps synch up a new access and refresh tokens.

### Alternatives/workarounds
- Set a cookie to have your client read before making a request to refresh the RT/AT using a `one time use` refresh token policy.
- Set a cookie with the users session expiration information, and have a more orderly refresh sequence orchestrated ahead of the actual access token expires (thus avoiding simultaneous calls).

### Additional context
- Customer Request: https://inversoft.slack.com/archives/C02Q208MSNP/p1725858307037479
- This is called `reuse_interval` in the competitors landscape.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This is working as designed. No plans to change this behavior.
