### ISSUE TITLE
[Bug]: Webhook Log Default Search Error.

### ISSUE THREAD

**Issue by alex-fusionauth** [FusionAuth/fusionauth-issues#2871]
### What happened?

When searching in the Webhook Log I ran into an issue when no event type is selected.

`Please review the troubleshooting guide found in the documentation for assistance and the available support channels.`

![image](https://github.com/user-attachments/assets/cb935aef-edf9-4d3b-9733-c4ec37c14f99)

I believe this is the error

```
2024-09-11 04:52:26.723 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.primeframework.mvc.PrimeException: org.primeframework.mvc.PrimeException: The message for the key [\] is missing and there was no default set using the [default] attribute.
```

### Workaround
Select an event type other than `User Login Failed`, or select a time window that excludes these types of events. 

### Observed in Version

1.53.1

### Affects Versions

`>= 1.53.0` when using the webhook even log viewer in the admin UI if you have events for user login failed.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/533
