### ISSUE TITLE
Client IP address not captured by Fusion login form

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#288]
Our apps redirect users to the Fusion login page. Most of our users will be clicking on a social login button like Google.

The IP address recorded for all logins appears to be one of our internal addresses on Azure. Should the OAuth Authorize template be handling the client IP address or is there another way FusionAuth can pick up the IP from the client?

**Comment by robotdan** [comment]
Closing out, let me know if you're still having issues with this one.
