### ISSUE TITLE
Add authentication to /api/status

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#289]
### Problem
Currently, anybody can make a `GET` to `/api/status`. IMO, that gives out too much info.

### Solution
Lock it down with an API auth key.

### Alternatives/workarounds
Devops would have to configure some sort of IP whitelist, which isn't the most secure option...

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @AlvMF1 . We've kicked this around quite a bit internally, I think this is a good idea. 

What we've discussed is only returning a status code when called anonymously, this will allow this endpoint to be used by load balancers etc to identify a health status. 

Then when called with an API key, we can return the JSON response body. 

We've also discussed making the response codes more granular and adding additional information to the response.

**Comment by robotdan** [comment]
Sort of related https://github.com/FusionAuth/fusionauth-issues/issues/362

**Comment by unkis** [comment]
but we need some free health check endpoint

**Comment by robotdan** [comment]
@unkis At a minimum we'll likely keep the status code returned w/out an API key to use for a health check.  And if we lock it down, we will likely provide a configuration option to lock it or not.

**Comment by robotdan** [comment]
Related https://github.com/FusionAuth/fusionauth-issues/issues/473

**Comment by robotdan** [comment]
This was resolved under #473 in 1.19.0.
