### ISSUE TITLE
`Keep me signed in` option not respected using managed domains with IdP federation

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2893]
### Description 
FusionAuth SSO session is not created when using Federated IdP's and Managed Domains

### Observed versions
1.53.0

### Affects versions
Seems to affect versions starting at 1.53.0 - with the SSO session changes that were introduced in that version

### Steps to reproduce
1. Create an OIDC/SAML SSO connection in FusionAuth
2. Setup that connection with a Managed Domain
3. Login to an FA application with that IDP enabled 
4. Select `Keep me signed in`
5. Get forwarded to your IdP, enter creds there, and be returned to FusionAuth
6. See that the user is authenticated (auth `code` is generated) but no FA SSO session was created.

### Expected behavior
If I ask to be remember, I am remembered.  An FA SSO session should be generated if I select `Keep Me Signed In`

### Screenshots
<img width="341" alt="image" src="https://github.com/user-attachments/assets/4b3c400b-0d1a-4ac1-893c-d0d2c256ad1b">

### Platform
(Please complete the following information)
dev setup

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2464
- https://github.com/FusionAuth/fusionauth-issues/issues/2472

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
There appears to be some other similar issues that have been documented previously. I linked them in the main description as well. 

- https://github.com/FusionAuth/fusionauth-issues/issues/2464
- https://github.com/FusionAuth/fusionauth-issues/issues/2472

**Comment by spwitt** [comment]
> There appears to be some other similar issues that have been documented previously. I linked them in the main description as well.
> 
> * https://github.com/FusionAuth/fusionauth-issues/issues/2464
> * https://github.com/FusionAuth/fusionauth-issues/issues/2472

The fix here also resolves the issue with always getting SSO when logging in to an external IdP. It will now follow the user's selection.

I was not able to reproduce the passwordless SSO issue.
