### ISSUE TITLE
User cannot self service register for multiple apps in same tenant

### ISSUE THREAD

**Issue by JoshTheHero** [FusionAuth/fusionauth-issues#2898]
### Description 
When a user is already registered to App 1 in Tenant 1, when they visit the registration link for App 2 in Tenant 1 and try to register they meet a "Account already exists for that email". Behaves the same for Username as well

### Observed versions
FA Cloud 1.52.0 and 1.53.2 

### Steps to reproduce
1. Create a Tenant with 2 Applications in it and enable self service registration for both
2. Create a user and register them for Application 1, either via admin UI or self service
3. Go to registration link for App 2 and attempt to use that same email for said user
4. Encounter error "Account already exists for that email"

### Expected behavior
I expect it to let the user register for App 2 if they have the right password or redirect them to login then update registration based on required registration fields in App 2. 

### Workarounds
If the user tries to log in to App 2, it will let them log in without a registration but force them update registration if there are different required fields for App 2. However directing the user to the login link instead of registration link requires knowing if they are already registered for App 1. 

Also if the user is already logged into App 1 and visits App 2 registration link within same browser, it will automatically register them for App 2(prompting for required fields if any exist). 

### Screenshots
![image](https://github.com/user-attachments/assets/85eba184-5330-43b3-a38d-72e81975ba84)

### Platform

 - Device: Laptop
 - OS: MacOS
 - Browser + version: Chrome 129.0.6668.91
 - Database: PostgreSQL 12.20

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
This is working as designed. You cannot create a use more than one time in a tenant. 

If I'm missing something, please re-open with additional detail.

**Comment by LucasPMorris** [comment]
This is working as designed. Not sure the design is something we want?

Tenant A
- App 1 -> User X self-registered.
- App2  -> User X can't self register.

Is the idea that a single user can only register for one app in a tenant?

**Comment by LucasPMorris** [comment]
I see that in the example this was tested in the "create and register at the same time" feature is being utilized vs and independant registration.
