### ISSUE TITLE
Bug: PHP client - autoload is not defined

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#29]
**Describe the bug**
Classes should loaded by composer without extra config from the app that use your library.

**To Reproduce**
-

**Expected behavior**
From `composer.json`:
```
"autoload": {
        "psr-4": { "fusionauth\\": "src/" }
    },
```
should work.

Otherwise, a simple mapping like:
```
"autoload": {
        "classmap": [
            "src/FusionAuthClient.php",
            "src/ClientResponse.php",
            "src/RESTClient.php"
        ]
    },
```

will work fine.

**Comment by robotdan** [comment]
Thanks @blanchonvincent, I appreciate you letting us know. 
Committed under a70ef84490230014c45bf7d6b676527f41dbef90.

**Comment by blanchonvincent** [comment]
I just tried the fix, it does not work better

**Comment by blanchonvincent** [comment]
since there is many classes in one file, I guess better to use static classmap

**Comment by robotdan** [comment]
I read some more about autoload, I wonder if it isn't working because we weren't following a good namespace convention. 

Do you want to see if it works properly now? 
https://github.com/FusionAuth/fusionauth-php-client/commit/77c35d63a05b1ecce005911485a9c16e90cc9407

Thanks for your help to get this right.

**Comment by blanchonvincent** [comment]
No it does not work

Since there is an existing folder `FusionAuth`, the mapping in `composer.json` should be `"FusionAuth\\": "src/FusionAuth/"`, I just tried with this configuration and it works

**Comment by blanchonvincent** [comment]
Fixed now, thank you
