### ISSUE TITLE
Better validation support for redirect and `post_logout_redirect_uri`

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2906]
### Description 
Improved validation when using wildcard rules and redirecting under oauth.

### Observed versions
1.53.2

### Affects versions
The version, or versions where this bug exists. If you do not know, please leave blank for now. 

### Screenshots
If applicable, add screenshots to help explain your problem. Delete this section if it is not applicable. 

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
https://inversoft.slack.com/archives/C03EZ5270A3/p1729786176851389

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/584
