### ISSUE TITLE
Ignore application PKCE requirements during passwordless authentication

### ISSUE THREAD

**Issue by atrauzzi** [FusionAuth/fusionauth-issues#2918]
### Description 
Many moons ago, we pioneered this technique together: https://fusionauth.io/community/forum/topic/333/passwordless-oauth

I remembered liking it because it allowed me to support any kind of server-instigated login while sticking with what was already sufficient in oauth.

Unfortunately, it looks now like this method won't work on apps where PKCE is required:

```
?error=invalid_request&error_reason=missing_code_challenge&error_description=The+request+is+missing+a+required+parameter%3A+code_challenge
```
This makes sense as the request didn't originate from the client, so PKCE is not necessarily in play.

### Steps to reproduce
Take a look at [the forum post @mooreds made some years](https://fusionauth.io/community/forum/topic/333/passwordless-oauth/2) ago :slightly_smiling_face: 

But more or less, use the [passwordless API](https://fusionauth.io/docs/apis/passwordless#start-passwordless-login) to start a passwordless login.  Then construct a URL and send a client to `/oauth2/passwordless/{passwordlesscode}` on the FusionAuth server.

### Expected behavior
Ideally I'd have expected PKCE to not be enforced because the server should know when `/oauth2/passwordless/[passwordlesscode]` is being called that it's unlikely to be client-initiated.

And of course, I don't want to have to disable PKCE for my entire application just to make this work as that would make normal browser initiated authorization flows less secure.

I think what is needed here is just something in FusionAuth to recognize when this specific technique is happening, to ignore the PKCE rule.

Of course, I'm open to other ideas, but I need to be able to do is preserve oauth compatibility with [oidc-client-ts](https://github.com/authts/oidc-client-ts).  As best as I can tell, it doesn't support having a JWT thrown at it.

### Workaround

Hhave a shadow application that is used only for passwordless login that mirrored all the settings of the main application but didn't require PKCE.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Previous title: Requiring PKCE breaks "passwordless oauth"

**Comment by mooreds** [comment]
Thanks @atrauzzi . Another option would be to have a shadow application that is used only for passwordless login that mirrored all the settings of the main application but didn't require PKCE.

**Comment by mooreds** [comment]
I'm going to modify this slightly, let me know if I don't have it correct.

**Comment by robotdan** [comment]
One of the goals of PKCE is to ensure only one party can safely exchange the auth code. So if multiple applications on a mobile phone - for example register for the same call back, each may be able to receive an auth code on a callback from FusionAuth. 

If configured to use PKCE - for reasons such as this, I don't know FusionAuth would know when it is safe to not enforce it. 

Seems super unlikely we could consider something like. I would suggest that you should not use PKCE if it causes you problems, or create a second application as @mooreds suggested. 

Are there any other vendors that have a dynamic enforcement of PKCE for cases like this?
