### ISSUE TITLE
Two Factor authentication returns a 500 error when signing in to other Applications

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-issues#292]
### Description 
I have enabled Two Factor authentication for myself and signing in works fine when going to the FusionAuth UI. But whenever I sign in using another client_id (different Application) I get a 500 error after I enter the Authentication code. This happens only when the User is not registered to the Application. The interesting thing is that I'm actually signed in. After returning to my application the OAuth endpoints return `success`.

### Steps to reproduce
1. Enable Two Factor authentication using the API.
2. Login to the FusionAuth UI. Everything is fine.
3. Create a new Application. Do not register the user to this Application.
4. Login using OAuth2 authorize with the client_id of the new Application.
5. Enter your Verification Code.
6. Observe the 500 error.

### Mitigate the problem by registering the Application to the User
1. Register the Application to the User
2. Login using OAuth2 authorize with the client_id of the new Application.
3. Enter your Verification Code.
4. Everything works as expected.

### Expected behavior
Signing in with Two Factor enabled should work regardless of the registration to the Application. It seems that the problem has to do with the redirect, because a valid session is still created.

### Screenshots
![Screen Shot 2019-09-16 at 16 09 14](https://user-images.githubusercontent.com/1012764/64989858-7d49d800-d89c-11e9-920a-b67f7404167a.png)

[stacktrace.txt](https://github.com/FusionAuth/fusionauth-issues/files/3618018/stacktrace.txt)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version: Chrome 76
- FusionAuth 1.7.2

**Comment by robotdan** [comment]
Have not been able to create on a current version. If you are able to recreate once you get on a current version let me know.

**Comment by flangfeldt** [comment]
I tried downloading the latest version (1.8.1 RC1) but the links on the Downloads page are broken:
https://storage.googleapis.com/inversoft_products_j098230498/products/fusionauth/1.8.1-RC.1/fusionauth-search-1.8.1-RC.1-1.noarch.rpm
and 
https://storage.googleapis.com/inversoft_products_j098230498/products/fusionauth/1.8.1-RC.1/fusionauth-app-1.8.1-RC.1-1.noarch.rpm

**Comment by flangfeldt** [comment]
In version 1.7.4 this is still a problem. Let me emphasize that this error is only thrown if the user signs in to an application that she is not registered to.

**Comment by robotdan** [comment]
Thanks for the heads up, looks like the way we are parsing the RC version isn't building correct links. Here you are


https://storage.googleapis.com/inversoft_products_j098230498/products/fusionauth/1.8.1-RC.1/fusionauth-search-1.8.1.RC.1-1.noarch.rpm

https://storage.googleapis.com/inversoft_products_j098230498/products/fusionauth/1.8.1-RC.1/fusionauth-app-1.8.1.RC.1-1.noarch.rpm

>  Let me emphasize that this error is only thrown if the user signs in to an application that she is not registered to.

Thanks, yes this is what I was testing as well. I have added a test to the suite, and done a manual click test and have been unable to recreate. I have not tested at 1.7.4, only at master which is roughly 1.8.1-RC.1.

**Comment by flangfeldt** [comment]
I can confirm that this issue has been resolved in v1.8.1 RC1.

**Comment by robotdan** [comment]
Great, thanks for the update @flangfeldt!!
