### ISSUE TITLE
A refresh token policy with a sliding window and a one-time use token should be mutually exclusive

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2925]
### Description 

If you have one-time use refresh token, then every time it is used, you get a new refresh token. 

If you have a refresh token with a sliding window, every time you use it, its lifetime is extended.

I don't see any way to use these together in a way that makes sense, so the UI and API should error when they are both enabled.

I would consider this a usability bug that could be worked around in documentation, but is better done in the product.

### Affects versions

Since 1.17.0, when these options were introduced.

### Steps to reproduce
1. Create an application
2. Navigate to the JWT tab
3. Navigate to Refresh token settings
4. Set the expiration policy to any sliding window value
5. Set the Usage policy to one time use

Save the application.

### Expected behavior

An error message is provided.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Internal: https://inversoft.slack.com/archives/C068UM25PNJ/p1731707833989109?thread_ts=1731704443.011479&cid=C068UM25PNJ

**Comment by robotdan** [comment]
The one time use policy says the value of the token changes on each use. This does not necessary have anything to do with how we choose to calculate the expiration. 

This appears to be as designed, and I don't know why you consider it a bug. Can you expand on the reason you think these two features are mutually exclusive?

**Comment by mooreds** [comment]
Hmmm. Sounds like you are saying that the lifetime of a refresh token is tied to the id, not to the value, including when a sliding window is enabled. But the value of the token is what is stored and used in the refresh grant (and therefore rotated when you have one-time use enabled). 

If that is the case, it would absolutely make sense to have both of these. 

So if you had a refresh token with a lifetime of 4 hours, a sliding window and one time use configured, you might end up with something like this:

* creation: id `09cfb961-291a-420f-b5cf-48c5c87a67cc`, value `RNhY5yE39t1o2FXKxgyH`, lifetime 4 hours
* when it is used 3 hours after creation: id `09cfb961-291a-420f-b5cf-48c5c87a67cc`, value `Fh95KZLfSMjMNxpR5B4c`, lifetime 4 hours
* when it is used 6 hours after creation: id `09cfb961-291a-420f-b5cf-48c5c87a67cc`, value `baHneP4s0hBHPEk88GPC`, lifetime 4 hours

Thanks for explaining. 

Closing.
