### ISSUE TITLE
unable to start fusionauth-search with the start command on ubuntu

### ISSUE THREAD

**Issue by vincentroman** [FusionAuth/fusionauth-issues#293]
## (unable to start fusionauth-search with the start command on ubuntu)

sudo service fusionauth-search start
Job for fusionauth-search.service failed because the control process exited with error code.
See "systemctl status fusionauth-search.service" and "journalctl -xe" for details.

**Comment by robotdan** [comment]
Hi @vincentroman thanks for letting us know. Unfortunately this isn't enough information for me to assist you. 

Can you provide some log output, or the output of `systemctl status fusionauth-search.service` or `journalctl -xe` as was printed on the console?

**Comment by vincentroman** [comment]
sure here you go
 fusionauth-search.service - LSB: Start FusionAuth
   Loaded: loaded (/etc/init.d/fusionauth-search; generated)
   Active: failed (Result: exit-code) since Tue 2019-09-17 09:06:51 WAT; 3h 0min
     Docs: man:systemd-sysv-generator(8)
  Process: 3695 ExecStart=/etc/init.d/fusionauth-search start (code=exited, stat

Sep 17 09:06:51 roman systemd[1]: Starting LSB: Start FusionAuth...
Sep 17 09:06:51 roman su[3716]: (to fusionauth) root on none
Sep 17 09:06:51 roman su[3716]: pam_unix(su:session): session opened for user fu
Sep 17 09:06:51 roman fusionauth-search[3695]: Starting FusionAuth Search Engine
Sep 17 09:06:51 roman fusionauth-search[3695]: /usr/local/fusionauth/fusionauth-
Sep 17 09:06:51 roman su[3716]: pam_unix(su:session): session closed for user fu
Sep 17 09:06:51 roman systemd[1]: fusionauth-search.service: Control process exi
Sep 17 09:06:51 roman systemd[1]: fusionauth-search.service: Failed with result 
Sep 17 09:06:51 roman systemd[1]: Failed to start LSB: Start FusionAuth.

**Comment by vincentroman** [comment]
ok i think i fix it the fusionauth-search was not added to the fusionauth folder in my home directory i manually moved the folder to it after i downloaded it separately for the  package download page  and it worked thanks for fusionauth.
am currenly working on a SPA social media app and hope this settles auth for me
