### ISSUE TITLE
Cannot save on Edit Email Template page even without any changes

### ISSUE THREAD

**Issue by tauinger-de** [FusionAuth/fusionauth-issues#294]
### Description 
Saving data on the edit email template page is blocked by a "null" validation message although I am only saving what is already there without any changes

### Steps to reproduce
1. Go to Settings > Email Templates
2. Click on Edit of e.g. Forgot Password template
3. Click blue Save icon at top right
4. See useless "null" validation message below mail content (in red)

### Expected behavior
Save is performed, UI shows list of templates

### Screenshots
![Screenshot from 2019-09-17 14-37-26](https://user-images.githubusercontent.com/45622761/65042248-be072700-d958-11e9-9261-b4e0b138351e.png)

### Platform
Ubuntu 19.04, Browser Chromium, Fusionauth 1.8.1 RC.1

**Comment by robotdan** [comment]
Hi @tauinger-de thanks for letting us know. This looks like a bug - for now you can remove the `?tenantId=${user.tenantId}` in the templates. 

This will be resolved in the final release. Thanks!

**Comment by tauinger-de** [comment]
Hi, that works, but isn't that parameter required in the URL?

**Comment by tauinger-de** [comment]
PS is it on purpose that every mail template has "localhost:9001" instead of the proper server URL in it? Is there a variable for actual server URL?

**Comment by robotdan** [comment]
> PS is it on purpose that every mail template has "localhost:9001" instead of the proper server URL in it?

Yes, we ship with those templates, and we don't know your server URL. `9011` is the default port FusionAuth will listen on.  

>  Is there a variable for actual server URL?

We don't currently have this - in theory we could provide a replacement variable of the IP address or hostname that comes in off of the API request when we send the email but that often will not be the correct value. This is because another service or application is making the API request on a private network. 

We may add this feature in the future that would allow you to set a static value through configuration that would make this part simpler. 

Sort of like this feature, but also adding a base URL. 
https://github.com/FusionAuth/fusionauth-issues/issues/262

**Comment by tauinger-de** [comment]
OK thx, great support!

**Comment by davidmw** [comment]
@robotdan is it possible to reset email templates to the default for the FusionAuth version? Ours migrated and based on the screenshot above, are obsolete. Unlike web templates I can't save a blank template to recover the default version.

**Comment by robotdan** [comment]
@davidmw there is not a reset option. 

The new addition of `?tenantId=${user.tenantId}` is optional and is used to help ensure we can resolve the correct theme (if one is utilized) during some edge cases such as the `verificationId` is expired and we cannot use it to resolve the user, and subsequently the tenant and theme. 

See the `Changes` section for Version 1.8.0 RC1 https://fusionauth.io/docs/v1/tech/release-notes/

> When using a theme, whenever possible provide the tenantId on the request using an HTTP request parameter. This will help ensure FusionAuth will render the page using your chosen theme. In most cases FusionAuth can identify the correct tenant and theme based upon other parameters in the request, but in some circumstances there is not enough information and FusionAuth will default to the stock theme if the tenantId is not explicitly provided.
>
> For example in each of the shipped email templates the following has been added to the generated URL ?tenantId=${tenantId}. You may wish to add this to your email templates if you’re using themes.
