### ISSUE TITLE
Spurious email template error on user registration

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#295]
V: 1.8.1.RC.1

We are getting this event log entry with every user we add via our front end thru the FusionAuth API. 

> html : freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
> ==> changePasswordId  [in nameless template at line 1, column 166]
> 
> FTL stack trace ("~" means nesting-related):
> 	- Failed at: ${changePasswordId}  [in nameless template at line 1, column 164]
> 

Email templates have been disabled and set to none for this tenant. For each user we are creating the account then setting app registration. The error is triggered on the registration step rather than during account creation. We had `skipRegistrationVerification` at the default but setting `skipRegistrationVerification = true` does not eliminate the error.  All the email templates we have access to are named so the 'nameless template' isn't known.

We have some performance problems associated with user creation and theorise that this template error isn't helping the issue.

**Comment by robotdan** [comment]
Are there any logs in addition to the recent log? And is that the whole event log?

**Comment by davidmw** [comment]
The unabridged version of the error:

```
<img width="969" alt="Screen Shot 2019-09-18 at 6 29 39 pm" src="https://user-images.githubusercontent.com/3413901/65131300-56c5a180-da42-11e9-97c2-d56312b3707c.png">
Email send failure. See reasons below.

Render Errors
---------------
html : freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> changePasswordId  [in nameless template at line 1, column 166]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${changePasswordId}  [in nameless template at line 1, column 164]
----

text : freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> changePasswordId  [in nameless template at line 1, column 159]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${changePasswordId}  [in nameless template at line 1, column 157]
----
```

I've attached a screen shot of the UI's Event Log - there are no other error types, just hundreds of these email template complaints.

**Comment by davidmw** [comment]
<img width="969" alt="Screen Shot 2019-09-18 at 6 29 39 pm" src="https://user-images.githubusercontent.com/3413901/65131690-0b5fc300-da43-11e9-9d4b-c9f1f71c205a.png">

**Comment by robotdan** [comment]
Can you provide the JSON result from a Retrieve Tenant By Id for the tenant in question? (feel free to redact any sensitive information)

I mainly want to see the email configuration. Also, a screenshot of the email templates page that will match up a template name to a template Id. 

Thanks.

**Comment by prabhakarreddy1234** [comment]
@robotdan  we get that error when we create a new user. i think create user action is triggering change password email even though it's not supposed to trigger. we didn't setup any webhooks.
```

{
    "tenant": {
        "configured": true,
        "emailConfiguration": {
            "host": "smtp.mail.net",
            "password": "gasdgasd",
            "port": 587,
            "security": "TLS",
            "username": "apikey",
            "verifyEmail": false,
            "verifyEmailWhenChanged": false
        },
        "eventConfiguration": {
            "events": {
                "user.delete": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.create": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.update": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.deactivate": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.bulk.create": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.reactivate": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "jwt.refresh-token.revoke": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "jwt.public-key.update": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.login.success": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.login.failed": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.create": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.update": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.delete": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.verified": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.email.verified": {
                    "enabled": false,
                    "transactionType": "None"
                }
            }
        },
        "externalIdentifierConfiguration": {
            "authorizationGrantIdTimeToLiveInSeconds": 30,
            "changePasswordIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "changePasswordIdTimeToLiveInSeconds": 600,
            "emailVerificationIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "emailVerificationIdTimeToLiveInSeconds": 86400,
            "oneTimePasswordTimeToLiveInSeconds": 60,
            "passwordlessLoginGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "passwordlessLoginTimeToLiveInSeconds": 180,
            "registrationVerificationIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "registrationVerificationIdTimeToLiveInSeconds": 86400,
            "setupPasswordIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "setupPasswordIdTimeToLiveInSeconds": 86400,
            "twoFactorIdTimeToLiveInSeconds": 300,
            "twoFactorTrustIdTimeToLiveInSeconds": 2592000
        },
        "failedAuthenticationConfiguration": {
            "actionDuration": 3,
            "actionDurationUnit": "MINUTES",
            "resetCountInSeconds": 60,
            "tooManyAttempts": 5
        },
        "familyConfiguration": {
            "allowChildRegistrations": true,
            "deleteOrphanedAccounts": false,
            "deleteOrphanedAccountsDays": 30,
            "enabled": false,
            "maximumChildAge": 12,
            "minimumOwnerAge": 21,
            "parentEmailRequired": false
        },
        "httpSessionMaxInactiveInterval": 3600,
        "id": "5aa453db-xxxx-xxxx-xxxx-6bacbcfac0e9",
        "issuer": "identtest.become.me",
        "jwtConfiguration": {
            "accessTokenKeyId": "760f86c4-xxxx-xxxx-xxxx-fcde4a8a1acc",
            "enabled": true,
            "idTokenKeyId": "092dbedc-3xxx-xxx9-9c61-b578f2c72f59",
            "refreshTokenTimeToLiveInMinutes": 43200,
            "timeToLiveInSeconds": 3600
        },
        "logoutURL": "https://abcd.net",
        "maximumPasswordAge": {
            "days": 180,
            "enabled": false
        },
        "minimumPasswordAge": {
            "enabled": false,
            "seconds": 30
        },
        "name": "Test",
        "passwordEncryptionConfiguration": {
            "encryptionScheme": "gdagagagadgasdg",
            "encryptionSchemeFactor": 24000,
            "modifyEncryptionSchemeOnLogin": false
        },
        "passwordValidationRules": {
            "maxLength": 256,
            "minLength": 8,
            "rememberPreviousPasswords": {
                "count": 1,
                "enabled": false
            },
            "requireMixedCase": false,
            "requireNonAlpha": false,
            "requireNumber": false
        },
        "themeId": "45xxxxxx-95e0-3xxx-5a1f-d466b647a38f"
    }
}
```

![image](https://user-images.githubusercontent.com/1984707/65175924-afe60300-da4b-11e9-939e-0d462a04ee06.png)

**Comment by robotdan** [comment]
When you call the User Create API are you using the `sendSetPasswordEmail` property? 

https://fusionauth.io/docs/v1/tech/apis/users#create-a-user

Have you modified any of your email templates?

**Comment by davidmw** [comment]
`sendSetPasswordEmail` is set to false for this user type.  Email templates had been lightly modified in 1.7.x (company name changed in signature) and these migrated to 1.8.1.  Then I noticed the plain text versions lacked the change so I updated from within 1.8.1.

**Comment by robotdan** [comment]
Ok, this is really strange. 

So whatever is causing this email to be sent, is either not setting the correct values into the template, in this case `changePasswordId` or something else has configured the `Setup Password` or `Forgot Password` to be used for a workflow it was not intended.

I'll have to dig into this a bit further to see how it is possible we could possibly be trying to send an email during this process.

**Comment by davidmw** [comment]
It turns out that the Setup Password template can't be deleted.  This happens on our original and on the cloned testing FusionAuth instance / database.  

I can duplicate the template and immediately delete the copy.

I can duplicate the template and edit all tenants to use the copy. I then can't delete the original. Something invisible is remaining linked to the template "This template cannot be deleted because it is being used."  Please look for an email with video demo.

**Comment by davidmw** [comment]
Following up on my email. In an experiment, I set all verification_email_templates_id to NULL.  The UI then let me delete the stuck email template. But our user creation process now fails during app registration.  Registration succeeds again after I recreate the email template and put that new ID in the three applications that utilised the template.

**Comment by robotdan** [comment]
Hi David, 

Here are the possible places an email template could be used which would cause the "in use" error. 

1. Applications --> Registration --> Verification template (enable Verify registrations to see the template selector)
2. Settings --> Tenants --> Email configuration (enable Verify email to see any other possible configuration)
3. Settings --> Tenants --> Family (enable family to see other configuration)
4. Settings --> Consents
5. Settings --> User actions

I wonder if it is possible that you have Verify Registration enabled and it is configured to use the wrong template? That configuration would be in Settings --> Applications --> Registrations --> Verify Registrations.

**Comment by davidmw** [comment]
Across 15 app configurations we had a couple on non-production tenants with 'verify registration' turned off but hiding the unwanted template selection. And another app had the same template with verification enabled. Once the template selections had been cleared and verify turned off everywhere - the obsolete template could be deleted and the error has stopped.  Thank you - great catch!

**Comment by robotdan** [comment]
@davidmw thanks! Good to hear you have it cleared up. 

On the ToDo list is to allow the delete validation error to report on who is using it so it is easier to track down.
