### ISSUE TITLE
Defining RelayState POST Parameter When Using FusionAuth As IdP In IdP Initiated Login

### ISSUE THREAD

**Issue by blakemckeeby** [FusionAuth/fusionauth-issues#2959]
### Observed versions
1.4.7

### Affects versions
1.4.7

### Steps to reproduce
I'm using FusionAuth as the IdP and trying to set the RelayState property sent alongside the SAMLResponse to the SP. 

Per the documentation for application.samlv2Configuration.authorizedRedirectURLs at https://fusionauth.io/docs/apis/applications I see how one can control the URL that FusionAuth ultimately causes the Browser to POST to (i.e. the ACS url). 

This, however, isn't what I'm looking for. I'm looking for the ability set the RelateState POST parameter that is sent to the ACS URL along side the SAMLResponse POST parameter. 

![CleanShot 2024-12-18 at 16 18 14@2x](https://github.com/user-attachments/assets/a530531d-1c53-432b-8089-f5d18a13e786)

**Comment by spwitt** [comment]
Thank you for bringing this up @blakemckeeby. Good news! We have an existing issue for this work that is planned for the upcoming `1.55.0` release.
- https://github.com/FusionAuth/fusionauth-issues/issues/2878
