### ISSUE TITLE
Problem to return the profile of fusionAuth to apostrophecms

### ISSUE THREAD

**Issue by carlosmbinf** [FusionAuth/fusionauth-issues#298]
good morning @robotdan , I have a problem, and they sent me a task of logging apostrophecms with oauth2 to Fusionauth, my problem is to authenticate the user, in the returned callback, the profile is undefined, you can authenticate and return me the profile? Can the scope be modified?, Example de Code:

'apostrophe-passport': {
      strategies: [
        {

          // LOGIN CON PASSPORT-OAUTH2
          // gitlab login
          // You must npm install --save this module in your project first
          // module: 'passport-oauth2',
          // options: {
          //    // Opciones para passport-gitlab2, consulte la documentación de ese módulo,
          //   // no tiene que establecer callbackURL
          //   tokenURL: 'https://sitio_con_fusion.com/oauth2/token',
          //   authorizationURL: 'https:// sitio_con_fusion .com/oauth2/authorize',
          //   clientID: '....',
          //   clientSecret: '....',
          //   callbackURL: 'http://sitio_apostrophe.net/auth/oauth2/callback',
          //   passReqToCallback: true

          // LOGIN CON PASSPORT-OAUTH
          module: 'passport-oauth2',
           match: 'email',
          options: {
            tokenURL: ' https:// sitio_con_fusion .com /oauth2/token',
            authorizationURL: ' https:// sitio_con_fusion .com /oauth2/authorize',            
            clientID: '1b554567-7af4-4be5-a006-0ca80235d9ac',
            clientSecret: '6PWiUg1sssjRfTSfuZ9RObaN1jB5m4MqYX1FiGs4HpE',
            callbackURL: 'https:// sitio_apostrophe.net/auth/oauth2/callback',
            passReqToCallback: true
          }
        }
      ],
      authenticate: {
        // minimum scopes for matching logins based on email addresses.
        // profile is absolutely required, you almost certainly want email too
        scope: [ 'offline_access' , 'profile' , 'email' ]
      },
       create: {
    // Presence of "group" means we'll add them to a group...
    group: {
      // Called "google"...
      title: 'fusion',
      // With these Apostrophe permissions (admin can do ANYTHING, so be careful)
      permissions: [ 'admin' ]
    }
  }
    },

![image](https://user-images.githubusercontent.com/53983616/65255458-eb281680-dacb-11e9-8bbb-fedef2b2c789.png)

**Comment by robotdan** [comment]
If this library is using the Userinfo endpoint, here are the documented claims that will be returned
https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo

If it is decoding the access token or id token directly, here are the documented claims
https://fusionauth.io/docs/v1/tech/oauth/tokens

It looks like it is trying to read a claim called `emails` which will not exist in our tokens. We use the `email` claim since it is a standard OIDC value. 

https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
