### ISSUE TITLE
Password encryptor plugin does not work with other tenants

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#299]
### Description 
Following up with [this issue](https://github.com/FusionAuth/fusionauth-issues/issues/204), **the problem doesn't exist when you import the user into the default tenant**.

### Steps to reproduce
1. Create a new tenant
4. Import a user specifying the new `tenantId` *or* using a tenent specific API key
5. Try to login with the imported user. See invalid creds message.

### Platform
FA v1.7.4

**Comment by robotdan** [comment]
To clarify your steps, you're doing the following? 

1. You have registered a custom password encryptor
2. Create a new tenant
3. Import a user using the Import API into the newly created tenant
4. You can view the user in the admin UI, tenant is correct as you expect. 
5. You attempt to login and it fails with invalid credentials

Questions: 

How are you logging in, with the API or the FusionAuth login panel?

**Comment by AlvMF1** [comment]
Correct, and logging in with the login panel.

**Comment by AlvMF1** [comment]
I believe I was confused. Since I was not specifying a client_id, the login panel defaults to the fusionauth app, default tenant. And because the user does not belong to this tenant, I was getting the invalid credentials. If that's the case, I apologize and you can close the issue.

**Comment by robotdan** [comment]
Yes, you do have to specify the `client_id`. 

To test this, you can view each application config and you'll see OpenID Connect Integration details, copy the `OAuth IdP login URL` into a new tab. If you can log in using the expected credentials then you're good to go. 

If you still have an issue, feel free to re-open. Thanks!
