### ISSUE TITLE
SSO with native form

### ISSUE THREAD

**Issue by chrisvoo** [FusionAuth/fusionauth-issues#302]
### Description
First of all, thanks for all the articles which clearly describe in details many use cases.
By considering the article linked in the title, I was wondering if when you write `Not provided by FusionAuth for this workflow` it means that it's not described in that docs or if it's not technically possible to do.
Basically I'm being asked to search a way to avoid [the redirection to FusionAuth login page](https://fusionauth.io/articles/logins/webapp/oauth-authorization-code-grant-jwts-refresh-tokens-cookies) (which through OAuth2 is the recommended way but the Login UI doesn't seem to be customizable) and to do everything under the hood through your API.
Is there an article which describes that or do you have any hints on how to reach that goal?
Thanks in advance.

**Comment by robotdan** [comment]
HI @chrisvoo 

The login pages are now customizable by using the FusionAuth theme feature. You can implement your own login page using our Login API or the OAuth2 Password Grant if you don't want to redirect your user. 

We have some users who have used an iframe to keep the SSO functionality but keep the login in more of a native form. This may work for you.
