### ISSUE TITLE
Forgotten password form silently fails on plus addressing

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#303]
v 1.8.1

We tend to use + email addressing during development and testing. FusionAuth allows us to create accounts using email addresses like  david+test1@mydomain.com and allows us to login with this account.  However the Forgotten Password form seems to fail silently with these accounts and the needed email isn't sent to the user.

**Comment by davidmw** [comment]
I'll likely close this issue - Fusion emails are not working for us currently.

**Comment by robotdan** [comment]
Are you still having issues here? I am unable to recreate, I can create a user with a `+test` suffix such as your example and it works as expected, I can login, and use the forgot password feature. 

Let me know if there are any other details I'm missing. Thanks.

**Comment by davidmw** [comment]
There seems to be no validation or white space trimming on password/forgot email submissions and the reply is always the same "Done - we've sent you an email ...." 

We have a federated IdP configured which results in the password field hidden until the email address is submitted.  So the likely flow is:

- user types email
- clicks next
- sees password field 
- optionally types password and submits, or goes direct to the 'forgot password' link.

The /password/forgot screen appears with the email field blank. The email has already been typed once and perhaps not carrying it forward is a security decision.  

My preference is to reduce the annoyance of typing a long address again so I put an 'email' parameter on the /password/forgot URL and the field autofills as a result. Two situations seem to be occurring:

If the email was originally typed or pasted with a whitespace character at either end then that whitespace carries into /password/forgot. The same problem that kept a kid from authenticating will keep them from receiving the password reset email.  

If the email has a + suffix on it then the autofilled version on /password/forgot replaces the + with a space so I need to handle that better.

**Comment by robotdan** [comment]
> The /password/forgot screen appears with the email field blank. The email has already been typed once and perhaps not carrying it forward is a security decision.
> 
> My preference is to reduce the annoyance of typing a long address again so I put an 'email' parameter on the /password/forgot URL and the field autofills as a result. Two situations seem to be occurring:

This is good feedback. We could probably add that if it is already in the form as a hint to the next form. I agree, anytime we can reduce the friction for the end user that is a good thing. Your workaround is just how we would do it as well. 

> If the email has a + suffix on it then the autofilled version on /password/forgot replaces the + with a space so I need to handle that better.

Yes, if you add it to the URL, you'll need to properly URL encode the value. JavaScript should be able to help you with this, if you have an example of how you're adding it I could likely assist.

**Comment by davidmw** [comment]
This is what I'm doing to add the email param to the URL. I don't have a good way to encode a Freemarker value in javascript and then make the result available to a Freemarker macro. This is such an edge case for us (use of + suffix) that I'd probably just ignore it if there isn't a simple fix.

```
<div class="form-row">
    [#if showPasswordField]
        [@helpers.button icon="key" text="Submit"/]
        <br><br><div>
            [#if loginId?has_content]
                [@helpers.link url="/password/forgot" text="Don't know your password?" extraParameters="&email="+ loginId /]
            [#else]
                [@helpers.link url="/password/forgot" text="Don't know your password?" /]
            [/#if]
        </div>
    [#else]
        [@helpers.button icon="arrow-right" text="Next"/]
    [/#if]
</div>
```

**Comment by robotdan** [comment]
If you're in FreeMarker you can encode the value by using `loginId?url` 
https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_url

**Comment by davidmw** [comment]
That certainly qualifies as simple. Thanks!

**Comment by davidmw** [comment]
Updating the forgot password link to trim and encode the email address:

```
        <div class="form-row">
          [#if showPasswordField]
            [@helpers.button icon="key" text=theme.message('submit')/]
              <br><br><div>
              [#if loginId?trim?has_content]
                [@helpers.link url="/password/forgot" text=theme.message('forgot-your-password') extraParameters="&email="+ loginId?trim?url /]
              [#else]
                  [@helpers.link url="/password/forgot" text="Don't know your password?" /]
	        [/#if]
            </div>
          [#else]
            [@helpers.button icon="arrow-right" text=theme.message('next')/]
          [/#if]
        </div>
```
