### ISSUE TITLE
Get Twitch OpenID Connect working

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#309]
## OpenId Connect with Twitch is not working

Because we do not allow the `claims` request parameter to be passed on the Authorization request we cannot get the `email` claim back from Twitch. This means we can't reconcile the user and complete login. 

We may want to support this additional `claim` parameter via the UI / API configuration of an OpenID Connect IdP in the future. See Feature https://github.com/FusionAuth/fusionauth-issues/issues/308. 

For now, we can make a small change to how we build this URL to allow the IdP configuration to contain an Authorization endpoint with request parameters to make the Twitch integration work.

**Comment by tauinger-de** [comment]
Hi @robotdan, so this temporary fix has been added to 1.10.0 release but not 1.9.3 as initially planned?

PS is it a bug that there are no release notes for 1.10.1 available here (https://fusionauth.io/docs/v1/tech/release-notes/#version-1-10-1)? Page starts with "1.10.0" for me

**Comment by robotdan** [comment]
The release notes were delayed due to a site update. They should be available now.

Thanks!!
