### ISSUE TITLE
Tenant creation new mandatory parameters

### ISSUE THREAD

**Issue by nunovieira220** [FusionAuth/fusionauth-issues#311]
### Description
We updated FusionAuth version from 1.7.3 to 1.9.2 and verified that, when creating a new tenant, there are now a lot of new mandatory parameters, most of them we would like to use default values like we were able to do on the previous version.
I highlight the `themeId` parameter that we do not use and would like to just use a default one if possible.
Is there a way to create a new tenant that allows us not to declare all the parameters needed using default values?

**Comment by johnmaia** [comment]
@robotdan Ideally fusionauth should operate without having to define any type of `template`, `themes` or `email` related settings. 

For anyone interested in simply using this as a auth solution and don't want it to send emails and don't care about what `theme` is used on the back-office.

These features should be optional when creating a new `tenant`. Something like: 
- `enableCustomTheme`: a `Boolean` value that turn every `theme` related fields required. If this value is set to `false` then it should use the `default` `fusionauth` theme.
- `enableEmailService`: a `Boolean` value that enables the `fusionauth` email management service. If this parameter was set as false, it should not be necessary to set any email template related parameters. Not that this parameter should not influence the `verify`, `forgot-password`, etc actions.

I imagine that our use case, where we programmatically generate new tenants, is an uncommon use case but you can imagine its pain to have to set this parameters with dummy values simply to use `fusionauth` as a multi-tenant auth solution.

**Comment by robotdan** [comment]
Thanks for the feedback @johnmaia and @nunovieira220 ! 

As a general rule, we do try to make as many parameters optional as possible for this exact reason. Now that the Tenant object only requires a `themeId` as a FK we could look at defaulting this to the FusionAuth them when not provided. 

The email we could also just set to some default values such as `localhost` and port `25` to limit the friction during creation. 

If we defaulted these values in addition to the TTL values for external identifiers then all that would be required would be a name! How would that be? 

https://fusionauth.io/docs/v1/tech/apis/tenants#create-a-tenant

**Comment by johnmaia** [comment]
@robotdan thanks for the fast feedback.

Those enhancements would be highly appreciated!

**Comment by johnmaia** [comment]
Don't forget to also set, if possible, the default values on the email templates. Otherwise features like `forgot-password` are disabled.

**Comment by robotdan** [comment]
@johnmaia Yes, I think we can do that as well. Email templates don't have a type, so we can't really default to the correct ones. 

I think what we'd have to do is default the email templates and the external Ids to the current values of the default tenant.

**Comment by johnmaia** [comment]
@robotdan either set them to a default value, or simply don't require a `template` id to enable features like these. 

These type of features should be enabled or disabled by a `boolean` parameter and, if we wanted to send emails via `fusionAuth` then it should be required to add a `templateId` for each feature. You could assume that only if we set a `tenant` `emailTemplateId` then we wanted to send emails via `fusionAuth`.

Somethink like (pseudo-code):
```js
// Do not send forgot-password email via fusionAuth.

{
  ...
  tenant.forgotPassword.enabled: true,
  tenant.forgotPassword.emailTemplateId: null, 
  ...
}
```

And:

```js
// Send forgot-password email via fusionAuth.

{
  ...
  tenant.forgotPassword.enabled: true,
  tenant.forgotPassword.emailTemplateId: '0fd35b75-f4de-4b4c-bc5c-66aa3c59d90f', 
  ...
}
```

**Comment by robotdan** [comment]
Most of our new features do use a `boolean` to toggle on and off, this is an older part of the code base that uses the value itself to decide if the feature is enabled. 

In the change password / forgot password case, we do support obtaining the `changePasswordId` in the API response, so you're correct in theory we could  have this feature enabled w/out an Email Template Id. This isn't true across each of the email workflows. 

I'll take your suggestion into consideration, thanks for the feedback, I appreciate it.

**Comment by johnmaia** [comment]
@robotdan I really appreciate that you take my suggestions to consideration.

If you could, it would also be incredible to have the `passwordless-login` as a feature, similar to the `change-password` and `forgot-password`, that would return the `code` to complete the  passwordless login.

**Comment by robotdan** [comment]
You're welcome @johnmaia. 

Feature request https://github.com/FusionAuth/fusionauth-issues/issues/175 .. in progress!

**Comment by robotdan** [comment]
Question for anyone interested in this feature. Would you prefer to have true defaults, or have a copy from - or both. 

For example, see the Theme API. https://fusionauth.io/docs/v1/tech/apis/themes#create-a-theme

This takes an optional `sourceThemeId` value to indicate which Theme to copy from.

So we could offer this as a copy from, or just true defaults, or both. Any opinions?

**Comment by johnmaia** [comment]
I would prefer true defaults. But I understand that in some use cases the copy from feature could be interesting. 

Probably the best idea is to have both where if I don't define a `sourceThemeId` nor any other `theme` related value, then it should use the default values. This could possibly be achieved by setting the `sourceThemeId` default value as the FusionAuth default theme.

**Comment by robotdan** [comment]
API doc should be updated in the next day or two, but the request JSON can take a `sourceTenantId` parameter. 

For example, here is a minimal API request
```
{
  "sourceTenantId": "e3695053-e403-462d-ba49-0d2f13ce1ddb",
  "tenant": {
    "name": "New tenant"
  }
}
```

We may still offer true defaults in the future, I went down that path, and I didn't like how it interacted with our UI / UX pattens. So before we add that I want to come up with a better strategy.
