### ISSUE TITLE
Can't see event logs for social login

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#312]
Can't see Event logs for social logins even though `Debug enabled` is true.

Event logs are completely idle whatever action i perform. I see below error in the server logs.
Is there anyway i can enable tracing and see all traces?

> Sep 26, 2019 10:58:54.068 AM ERROR com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.jwt.RefreshTokenReaper] failed but will be re-run.
> java.lang.NullPointerException: null
> 	at io.fusionauth.api.service.jwt.DefaultJWTService.revokeExpiredRefreshTokens(DefaultJWTService.java:220)
> 	at io.fusionauth.api.service.jwt.RefreshTokenReaper.run(RefreshTokenReaper.java:26)
> 	at com.inversoft.scheduler.InjectableRunnable.run(InjectableRunnable.java:37)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Sep 26, 2019 4:31:10.622 PM ERROR com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.jwt.RefreshTokenReaper] failed AGAIN! The service will still continue to run, but we are going to stop logging the errors.

FusionAuth : 1.9.2
Hosting: AKS

**Comment by robotdan** [comment]
That exception is a known issue and will be fixed in the upcoming patch release. That is an un-related exception to the social login debug. 

There should be an event log of type Debug for each time you login with an IdP when debug is enabled. Can you provide any additional details about your configuration?

**Comment by prabhakarreddy1234** [comment]
Below is the configuration of google setup.

![image](https://user-images.githubusercontent.com/1984707/65821588-6d80ab00-e22f-11e9-9ced-56e88685dcca.png)

![image](https://user-images.githubusercontent.com/1984707/65821604-9608a500-e22f-11e9-9ca5-b7afa19c4a8f.png)


Event logs is empty since a week. I doubt the error stacktrace. Seems like nothing is being logged since a week.

**Comment by robotdan** [comment]
is the login work, but you just aren't seeing debug event logs?

**Comment by davidmw** [comment]
Separate tenant and at the time of the report Google login was not working.

**Comment by robotdan** [comment]
Is this still an issue as of version 1.10.1 ?

**Comment by davidmw** [comment]
No longer an issue.  Getting debug messages in 1.10.1.
