### ISSUE TITLE
/oauth2/userinfo endpoint returns 401 for invalid tokens

### ISSUE THREAD

**Issue by trex** [FusionAuth/fusionauth-issues#321]
### Description 
Per [RFC 6750 - Section 3.1](https://tools.ietf.org/html/rfc6750#section-3.1), error responses for bearer token usage should return a 401 for invalid tokens.  Currently the /oauth2/userinfo endpoint implemented in FusionAuth returns a 400 for invalid tokens.

### Steps to reproduce
1. Call /oauth2/userinfo with an expired or invalid access token
2. Receive status code 400

### Expected behavior
Status code is 401

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version: chrome 77.0.3865.90

**Comment by robotdan** [comment]
@trex I think this is code complete, is that correct? Is this on master?

**Comment by robotdan** [comment]
Available in 1.11.0
