### ISSUE TITLE
External identifier generation complexity settings for "Passwordless Login" have no effect

### ISSUE THREAD

**Issue by pawpro** [FusionAuth/fusionauth-issues#322]
### Description 
Trying to reduce complexity of the paswordless external identifier to say digits of any length does not have effect while email verification does seem to produce short digits only identifiers such as:

https://fusionauth.fq.dn/email/verify/50098?tenantId=00e3f9a1-0084-003a-b6aa-0047708c0466

Paswordless does not:
https://fusionauth.fq.dn/oauth2/passwordless/oV1STlyIXhk7j-kKSnNkvYx52h7rZUt-x9ep_cB8C3Q?tenantId=00e3f9a1-0084-003a-b6aa-0047708c0466

In addition and separately I will raise a point about how a low complexity of external identifier could be managed when combined with ability to set a requirement to provide user identifier alongside the code.

### Steps to reproduce
1. Go to Admin / Home / Settings / Tenants / Advanced
2. Under External identifier generation and Passwordless Login
3. Select "Digits" and enter 4 into the input field
4. Trigger passwordless login
5. Receive long alphanumerical external identifier

### Expected behavior
An external identifier matching configured specification is expected to be generated instead

### Screenshots
Screen attached.

### Platform
Fasttrack 1.9.2, Ubuntu

<img width="544" alt="Screenshot 2019-10-03 at 19 58 36" src="https://user-images.githubusercontent.com/941786/66151950-a1394780-e618-11e9-95f7-6312902398d1.png">

**Comment by robotdan** [comment]
Thank you for reporting the issue, you're correct the Passwordless is not honoring this configuration. This will be fixed in the upcoming release.

**Comment by robotdan** [comment]
Available in 1.11.0
