### ISSUE TITLE
Access to id_token in OpenID Connect Reconcile lambda

### ISSUE THREAD

**Issue by Thammada** [FusionAuth/fusionauth-issues#323]
### Problem
LINE Login does not return email address from the userinfo endpoint. Email has to be extracted from `id_token`  when requesting for the token.
reference:
https://developers.line.biz/en/docs/line-login/web/integrate-line-login/
https://developers.line.biz/en/docs/social-api/getting-user-profiles/

This is similar to Microsoft AD issue, mentioned on this page https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/azure-ad

### Solution
Pass `id_token` to the `reconcile` lamba so email address can be extracted and used to reconcile user.

### Alternatives/workarounds
No idea how to work around this yet.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @Thammada .

The LINE integration indicates it supports OpenID Connect doesn't seem to support the full workflow. 

https://access.line.me/.well-known/openid-configuration

```
{
  "issuer": "https://access.line.me",
  "authorization_endpoint": "https://access.line.me/oauth2/v2.1/authorize",
  "token_endpoint": "https://api.line.me/oauth2/v2.1/token",
  "jwks_uri": "https://api.line.me/oauth2/v2.1/certs",
  "response_types_supported": [ "code" ],
  "subject_types_supported": [ "pairwise" ],
  "id_token_signing_alg_values_supported": [ "ES256" ]
}
```

You'll see in their discovery document they do not support the Userinfo endpoint. I am assuming that you are using the Profile endpoint in place of the Userinfo endpoint in your configuration?  For example:

![image](https://user-images.githubusercontent.com/1148709/66158911-1e969500-e5e4-11e9-9965-7be91b73952d.png)

This seems to be sort of a one off from the OpenID Connect core spec which makes it difficult to support. In theory when you provide the `email openid` scope you would then expect to receive the `email` claim back in the Userinfo response, in this case the response from the Profile endpoint. 

We could look at passing both of these tokens to the lambda, or optionally merging their claims into a single JWT passed to the lambda.

**Comment by Thammada** [comment]
Thanks for your quick response @robotdan. You are right, I'm using the Profile endpoint in place of Userinfo endpoint.

We would like to support LINE Login. Looking forward to the update, but if there is a workaround we would happily implement it.

**Comment by mKaloer** [comment]
+1 for id_token in the reconcile lambda. Azure AD returns user groups in the id_token but not in the userinfo endpoint, and i'd be happy if I could read those in the reconcile lambda.

**Comment by egism** [comment]
+1

I have raised a couple of similar questions in your Q&A regarding this. It seems there is no decent way to use Azure AD OpenID connect as an identity provider when Azure AD Application is setup as [multi-tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant). Since it uses a generic issuer url (not tenant specific) the only way to extract the tenant id is from id_token/access_token claims.

Nevertheless, great product.
