### ISSUE TITLE
Cannot log in into the admin panel after installing the packages

### ISSUE THREAD

**Issue by chrisvoo** [FusionAuth/fusionauth-issues#325]
### Description 
After having installed fusionauth through FastPath method and configured the app in the maintenance mode, I open `http://localhost:9111` and despite the correctness of my credentials, I'm not able to log in.

### Steps to reproduce
1. `sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh -s - -z"`
2. `sudo service fusionauth-search start`
3. `sudo service fusionauth-app start`
4. Opening Chrome to `http://localhost:9011`
5. Entering in Maintenance mode.
6. I had to add another user for MySQL `fusionauth@localhost`, because with the default one (with the wildcard), the client wasn't able to connect to the database.
7. I entered the details of the admin account and I got redirected to the login page.
8. Once I entered the credentials and clicked the submit button, I see a redirection of the browser from the admin page to the login page again. No errors at all. If I enter the wrong credentials on purpose, I clearly see a red error message.

The only error I'm able to see inside `fusionauth-app.log` is the following:

```
ct 09, 2019 5:32:12 PM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet [jsp] threw exception
java.lang.IllegalStateException: Cannot create a session after the response has been committed
        at org.apache.catalina.connector.Request.doGetSession(Request.java:3042)
        at org.apache.catalina.connector.Request.getSession(Request.java:2476)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)
        at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:598)
        at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:543)
        at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:137)
        at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:109)
        at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:60)
        at org.apache.jsp.default_jsp._jspService(default_jsp.java:114)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:380)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:245)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:340)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:166)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
```

### Expected behavior
To be able to log in into the admin panel.

### Platform
(Please complete the following information)
 - Device: `Desktop`
 - OS: `Ubuntu 19.04 64bit`
 - Browser + version: `Chrome 77.0.3865.90 (Official Build) (64-bit)`
 - MySQL: Ver 5.7.27-0ubuntu0.19.04.1

**Comment by wxsdion** [comment]
I have the same exact problem on a clean install of FusionAuth 1.7.4 and Postgres 10.7. 
I tried updating through every version until 1.10.1 with no success. 
Indeed the authorization seems to go through and redirect to /admin which in turns redirects back to the login page.
<img width="347" alt="Screen Shot 2019-10-10 at 2 18 48 PM" src="https://user-images.githubusercontent.com/35312899/66595826-b575cb00-eb69-11e9-859a-2e5d10d57f9c.png">

Tested with Chrome Version 77.0.3865.90 (Official Build) (64-bit) and Firefox 69.0.2 (64-bit)

**Comment by robotdan** [comment]
@chrisvoo thanks for opening an issue. Is this on a clean install that you observed this issue, or did this occur after an upgrade? 


> Opening Chrome to http://localhost:9111


The default port for the admin UI is `9011`, I am assuming the above is typo? Can you confirm?

@wxsdion can you confirm you can open a new browser or incognito tab and navigate to `http://localhost:9011` to attempt login? 

Opening that URL should redirect to `http://localhost:9011/admin/` which will redirect to the correct `http://localhost:9011/oauth2/authorize` URL to complete login. It is possible that a stale CSRF cookie or an invalid `http://localhost:9011/oauth2/authorize` can cause login to fail, ensuring you start at `http://localhost:9011` should ensure you get a clean login URL. 

If that is still not working, can you provide your entire `fusionauth-app.log` ?

**Comment by chrisvoo** [comment]
@robotdan It was a clean install. The same thing happened in Incognito mode.

**Comment by wxsdion** [comment]
After a bit more testing I think I was able to pinpoint a possible cause.

When deploying fusionauth using the helm chart (https://github.com/FusionAuth/fusionauth-containers/tree/master/helm/fusionauth), I can reproduce the issue when running with a replicaCount greater than 1.
With a single fusionauth pod running I am able to successfully log in the admin panel.

Is this the intended behavior of fusionauth or is there more configuration needed to run it on multiple pods ?

Thanks

**Comment by voidmain** [comment]
I'm not familiar with Helm, but FusionAuth uses persistent sessions on the server for our OAuth/OIDC/SAML functionality. These are pushed back to the browser as cookies and are stateful. If you have multiple nodes, is your proxy or load-balancer correctly pinning the client to a node using session pinning?

**Comment by wxsdion** [comment]
Ah, I see. Thanks for the reply. 
I had not thought of this indeed, I will have to configure my load-balancer to manage sticky sessions. 
I would say case closed, but I did kind of hijack @chrisvoo initial issue, sorry about that. Not sure we had the same problem after all, but I will work on my load-balancer and re-open an issue on my end if needed. 
Thanks

**Comment by robotdan** [comment]
Thanks for the update @wxsdion ! As @voidmain mentioned, I'm assuming this will work for you once you have enabled session pinning. 

We probably need some more documentation in this area, but we do have some layout examples. See the following URL for an example some some details about how you should configure session pinning.  https://fusionauth.io/docs/v1/tech/installation-guide/server-layout#two-servers-with-external-database

> In this scenario FusionAuth should be placed behind a load balancer to utilize both services equally. Session pinning should be utilized to support stateful sessions to FusionAuth. API connections to the FusionAuth App are stateless and do not require session pinning. All URLs beginning with /api/ will be API requests and should not be session pinned. This configuration is best suited for the following purposes:


@chrisvoo My guess is that your issue is also related to session pinning. Let me know if you need further assistance! 

Thanks!

**Comment by chrisvoo** [comment]
Even if it's related to that, how could I solve the issue, considering that I was using a fresh install in local, without a load balancer and a single instance, all on the same local machine?

**Comment by robotdan** [comment]
> Even if it's related to that, how could I solve the issue, considering that I was using a fresh install in local, without a load balancer and a single instance, all on the same local machine?

If this is a single box, then the session pinning is not the culprit. Are you still having the issue, and are there any other details you can provide?

**Comment by chrisvoo** [comment]
Sorry, I've abandoned FusionAuth in favor of something different. Anyway, I don't have further details to provide, so you can close the issue if you want.

**Comment by robotdan** [comment]
Thanks for the update @chrisvoo

**Comment by einar-lanfranco** [comment]
The same happens to me, just fresh running  with docker, i add one user and i cant login anymore using Chrome. With Firefox it works like a charm! 

![Captura de pantalla de 2020-05-20 21-52-58](https://user-images.githubusercontent.com/3857748/82511726-67a04880-9ae4-11ea-93e5-219ed4f2c822.png)

**Comment by robotdan** [comment]
@einar-lanfranco are there any errors in the chrome dev tools console?

**Comment by einar-lanfranco** [comment]
No errors, but i found the problem!!!!!
I compare both cookies, Chrome vs Firefox and the diff show me the problem: 
fusionauth.locale in Cookie, GoogleChrome auto set it as  es_419 and Firefox as es_AR. 
If you manually change this value in the Chrome console, it works fine!

**Comment by robotdan** [comment]
@einar-lanfranco thanks for the details. That is strange, perhaps there is a localization issue with those particular locale codes. We'll take a look to see if we can replicate your symptom.

**Comment by Renkon** [comment]
@robotdan I have reproduced this issue. Seems to be related to Argentinian locale. As soon as I replaced es_419 with es_AR the admin panel was accessed flawlessly.

**Comment by robotdan** [comment]
Thanks @Renkon we'll see if we can recreate. I'm going to open a separate issue so we can track a clean thread. 
https://github.com/FusionAuth/fusionauth-issues/issues/978
