### ISSUE TITLE
Modify or cancel user action doesn't work

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#328]
### Description 
With multi tenants, if we try to modify or cancel a user action, we get an error message that says `FusionAuth is unable to determine which tenant to use for this request. This error is unexpected. Contact Support.`.

### Screenshots
<img width="1066" alt="Screen Shot 2019-10-10 at 10 46 54 PM" src="https://user-images.githubusercontent.com/15204146/66627288-0ad4cb00-ebb0-11e9-92be-a00d5fe91df9.png">
<img width="418" alt="Screen Shot 2019-10-10 at 10 47 10 PM" src="https://user-images.githubusercontent.com/15204146/66627300-12946f80-ebb0-11e9-9443-abd03c86c041.png">

### Platform
FA v1.10.1

**Comment by robotdan** [comment]
Thanks for reporting @AlvMF1 - we are likely missing the `tenantId` on the URL used to build that dialog. We should be able to track it down and get it fixed in the next patch release. 

A work around would be to have only one tenant, that may or may not be applicable in your case.
