### ISSUE TITLE
Improving UX for Social login such as Google and Facebook signon when a separate dialog is opened

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#331]
### Problem
The email / password login screen is visible after Google login making it seem like the user didn't successfully authenticate.

https://www.loom.com/share/6be7553914894020ad3e72595e248319

### Solution
Replace the OAuth login screen before showing Google or other IdP screens. FusionAuth could show a message like 'processing your signin via Google' while hiding the email / password / IdP button array so that the OAuth login screen won't be visible when Google screens are dismissed.

If user cancels the IdP login then the current flow works well since the OAuth screen remains active and the user can select another login method or request a password reset. This functionality needs to be maintained or available via a link on the new proposed screen.

The flow that does not involve cancelling the IdP login is by far the more common path that new users and returning users will take.  So it seems that the unintentional redisplay of a blank OAuth login form after Google signin will be seen by most users and the experience is rather jarring.

**Comment by robotdan** [comment]
Thanks for opening this issue @davidmw, this is a great suggestion to improve the user experience.

**Comment by davidmw** [comment]
Any idea when this might be put on the roadmap?  The multiple second delay after SSO during which the Fusion login fields remain visible are causing enough FUD that we are considering explaining it in documentation / video walkthrough.

**Comment by davidmw** [comment]
Leaving the FusionAuth submit button active after successful SSO creates opportunity for impatient user to break the login flow as shown here:

https://www.loom.com/share/fa879fbe93114c1db8b48f895ea42f46

**Comment by robotdan** [comment]
Thanks for the video @davidmw that is helpful. 

I would love to get this improved, and account for a slow response time from Google, it is difficult for me to put a timeline on this effort as we are swamped with paid engagements at the moment. 

In the mean time, since all of our templates are modifiable as part of your theme, if you're handy with JavaScript this is something you can also handle on your end very easily.

**Comment by davidmw** [comment]
You mean disable or hide fields when the Google SSO button is clicked?  That might create more problems.

**Comment by robotdan** [comment]
> You mean disable or hide fields when the Google SSO button is clicked? That might create more problems.


You could do that on the Google button click, it may be a better choice to do it after the Google dialog closes. If I understand correctly, that is what you'd like us to do in the default theme?

**Comment by davidmw** [comment]
Ideally the FusionAuth login screen would disable any fields and navigation controls once a SSO button is pressed. If the login process is slow the user should see a progress indicator or wait message. If the SSO process fails or is cancelled by the user the FusionAuth screen should recover from that and let the user make another choice.

Maybe an EventListener can be set when launching the Google dialog but it might not be possible to know why the dialog closes.

**Comment by robotdan** [comment]
I agree. 

All of this can be accomplished currently in the theme using JavaScript. When we deliver this feature that is what we'll do as well.

**Comment by robotdan** [comment]
Here is an example of what we could deliver with a bit of JavaScript. This in progress indicator would show up as soon as the Google login window closes and would keep mouse events from being transmitted from the buttons. 


![image](https://user-images.githubusercontent.com/1148709/70382934-f5ff8400-1921-11ea-97a2-7732b9cfb754.png)

**Comment by davidmw** [comment]
Ah - I was over complicating it.  Thanks much.

**Comment by davidmw** [comment]
We've been upgraded to 1.12 and I've merged the template changes - the progress indicator is working well.  Thanks much!
