### ISSUE TITLE
post_logout_redirect_uri gains query components

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#332]
### Description 
Calling /oauth2/logout with post_logout_redirect_uri is resulting in a successful redirect to post_logout_redirect_uri.

However this is 'post logout' and might be a static webpage, might be the application root, or other destination.  Currently the redirect is appending `iss=` and `sid=` to the URL and this could have unintended consequences for page analytics, page caching, and CDN hits.

**Comment by robotdan** [comment]
Hi @davidmw 

They are added per the OIDC spec for the logout URLs, but in the case that you pass in a `post_logout_redirect_uri` we would not have to add them to this URL. 

I'll take a look this, thanks!

**Comment by davidmw** [comment]
Great to hear, thanks!

**Comment by robotdan** [comment]
Available in 1.11.0
