### ISSUE TITLE
Issue migrating the Database host and FA version

### ISSUE THREAD

**Issue by nicholasbutlin** [FusionAuth/fusionauth-issues#334]
### Description

I am attempting to migrate the FusionAuth app and database to another country due to some data sovereignty requirements. 

It is currently deployed on an Ubuntu EC2 as v1.6 using the .deb fast path, with the DB hosted on MySQL RDS. (prod)

I have booted up a new instance as a staging deployment, using the docker 1.10.1 and the recommended Elastic Search. 
I initially migrated to a MariDB instance (as with all our other DBs) but had some issues (probably as per https://github.com/FusionAuth/fusionauth-issues/issues/327) , so reverted to MySQL 5.7. 

The DB restores fine, and the migration appears to run without issue, but I had an issue with the Users index, which I think I found the answer to: 
https://github.com/FusionAuth/fusionauth-issues/issues/130

However, despite being the system Global admin, I am unable to REINDEX, and get an unauthorised error. In fact, I appear to be unable to make any action to modify any settings. 

I am a bit stuck as I am wary of making any changes to the existing production server in case this causes the same Unauthorised error - effectively locking me out.

I had a poke around the database, both prod (1.6) and staging (now updated to 1.10) but can't see any obvious reason this should have occurred. 

Do you have any insight? Thanks!

**Comment by nicholasbutlin** [comment]
I think I have discovered what is wrong. Thanks...

**Comment by robotdan** [comment]
For anyone else that may run into this, I believe this is a proxy configuration issue. See the following issues.

https://github.com/FusionAuth/fusionauth-issues/issues/114
https://github.com/FusionAuth/fusionauth-issues/issues/265

@nicholasbutlin let me know if this wasn't your solution.

**Comment by nicholasbutlin** [comment]
@robotdan That was exactly it - it took a while to figure out because I was coming from: 
a) Maria DB wasn't working with Docker -> used MySQL 
b) Users weren't appearing in MySQL -> Needed to Reindex 
c) Couldn't Reindex or make any changes -> had a proxy issue

**Comment by nicholasbutlin** [comment]
@robotdan It absolutely did - I just dismissed it without due attention as first as I was so convinced it was a database issue.
