### ISSUE TITLE
Unhelpful error message when Oauth2 state is incorrect

### ISSUE THREAD

**Issue by JesperWe** [FusionAuth/fusionauth-issues#338]
### Description 
I am filing this bug since better error messages could potentially help devs having issues while working on integrating with external IdP.

When using an external Oauth2 IdP, Fusionauth sends a `state` parameter to the provider, and the provider sends this parameter back to Fusionauth in the `/oauth2/callback`. The `state` contains lots of variables that Fusionauth needs to complete the login. If the `state` is somehow broken or not formatted according to Fusionauths expectations, the login will fail and an error message printed. In my case I had the message

```
{
  "error" : "invalid_client",
  "error_description" : "client_id: bece1a16-4eda-453f-9c00-ee2f1b6de36b, is not valid.",
  "error_reason" : "invalid_client_id"
}
```

This message causes much head-scratching since the displayed client id is a correct and valid id in my system, and made finding the actual error (that the `state` value had been corrupted by the IdP) much harder to find.

### Expected behavior
A clearer error message. Something like "IdP returned Oauth2 state in unrecognized format". Or if it's hard to tell exactly what's wrong, at least do not show an error message that is clearly incorrect. 

### Platform
Fusionauth 1.10.1

**Comment by robotdan** [comment]
I think the root cause of this is the issue we've discovered in this issue https://github.com/FusionAuth/fusionauth-issues/issues/335. 

Once the `state` parameter is modified we are in an unsupported configuration.

**Comment by JesperWe** [comment]
> Once the state parameter is modified we are in an unsupported configuration.

Of course. All I'm saying is the error message could be less misleading. But the sheer existence if this issue will also help, if someone else has similar problems ;-)

**Comment by robotdan** [comment]
> All I'm saying is the error message could be less misleading. 

I agree, it is just difficult to account for these types of edge cases in a meaningful way. The error that was returned to you could have been something different as well, the behavior in this state is non deterministic.
