### ISSUE TITLE
PKCE not supported with Identity Provider

### ISSUE THREAD

**Issue by TanguyGiton** [FusionAuth/fusionauth-issues#340]
### Description 
I use PKCE on a SPA during authentication, it works correctly when the user uses his FusionAuth credentials. 
However, this does not work when the user uses an Identity Provider (in my case OpenID with Azure AD). When I request a token with the `code_verifier`, I get an error 400 `auth_code_not_found`, but if I make the request without `code_verifier` it works even though I had sent `code_challenge` for the authorization code request.

The solution I have found so far is to redo an authentication request with PKCE, this allows me to get a new authorization code transparently for the user thanks to the FusionAuth session and thus redo a token request.

### Expected behavior
Maintain the same behavior when using PKCE regardless of the user's authentication method.

**Comment by robotdan** [comment]
Following up @TanguyGiton - were you able to test the work around?

**Comment by TanguyGiton** [comment]
Sorry for the late answer, I couldn't try before. I applied your fix and it works! 

Thank you @robotdan
