### ISSUE TITLE
invalid issuer in discovery document when using angular-oauth2-oidc

### ISSUE THREAD

**Issue by paulspencerwilliams** [FusionAuth/fusionauth-issues#343]
### Description
When attempting to reconfigure my code that uses angular-oauth2-oidc which works against Keycloak, to work against FusionAuth, I attempted to use the domain as the issuer url, but this generates the below error. Further, I tried disabling strict discovery documentation validation, but this is insufficient to remove the error, suggesting I need to do more configuration work. Do you have such documentation? 

#### Error:

invalid issuer in discovery document expected: http://localhost:9011 current: acme.com
ERROR Error: "Uncaught (in promise): discovery_document_validation_error"

#### Code / configuration as works with Keycloak:

`import { Component } from '@angular/core';
import { OAuthService, JwksValidationHandler, NullValidationHandler, AuthConfig } from "angular-oauth2-oidc";

const authConfig: AuthConfig = {
    issuer: 'http://localhost:8080/auth/realms/springfield',
    redirectUri: window.location.origin + '',
    clientId: "Angular 6 SPA",
    scope: 'openid profile email offline_access api',
    showDebugInformation: true,
    responseType: 'code',
    disableAtHashCheck: true // at_hash isn't required for  authentication code flow
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
    title = 'app';
    constructor(private oauthService: OAuthService) {
        this.oauthService.configure(authConfig);
        this.oauthService.tokenValidationHandler = new NullValidationHandler();
        this.oauthService.loadDiscoveryDocumentAndTryLogin();
        this.oauthService.setupAutomaticSilentRefresh();
    }
}
`

#### Reconfigured code attempting to authenticate against FusionAuth:

`import { Component } from '@angular/core';
import { OAuthService, JwksValidationHandler, NullValidationHandler, AuthConfig } from "angular-oauth2-oidc";

const authConfig: AuthConfig = {
    issuer: 'http://localhost:9011',
    redirectUri: window.location.origin + '',
    clientId: "445f871f-7e1d-462a-ba88-ffb7b91fb3a0",
    scope: 'openid profile email offline_access api',
    strictDiscoveryDocumentValidation: false,
    showDebugInformation: true,
    responseType: 'code',
    disableAtHashCheck: true // at_hash isn't required for  authentication code flow
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
    title = 'app';
    constructor(private oauthService: OAuthService) {
        this.oauthService.configure(authConfig);
        this.oauthService.tokenValidationHandler = new NullValidationHandler();
        this.oauthService.loadDiscoveryDocumentAndTryLogin();
        this.oauthService.setupAutomaticSilentRefresh();
    }
}
`

**Comment by robotdan** [comment]
From looking at the `angular-oauth2-oidc` doc and code, it looks like you could disable issuer validation using `skipIssuerCheck`.  

But if I understand the validation they are doing, it is failing because the issuer returned in the discovery document is not matching the "issuer" configured which is the root URL of `http://localhost:9011` that is being used to build the discovery URL of `http://localhost:9011/.well-known/openid-configuration`

You can change the issuer per tenant in the Tenant configuration. See `Settings --> Tenants --> Edit --> General (tab)`. This value defaults to `acme.com` which is what showed up in your error. 

> invalid issuer in discovery document expected: `http://localhost:9011` current: acme.com
ERROR Error: "Uncaught (in promise): discovery_document_validation_error"

You can try skipping the issuer check, or update the issuer value in your tenant to match the URL you're configuring.

**Comment by paulspencerwilliams** [comment]
Okay, Cheers. I updated the issuer url as recommended, and I managed to login. However, even with the above specified scopes, I'm not getting the typical claims I would expect e.g. name. Further, I noticed that I was using the NullValidationHandler rather than recommended JWTValidationHandler. When, I switched over, I now get a 
```"Array keys in jwks missing!"```

It would seem that my FusionAuth instance isn't configured to work properly.

My current `angular-oauth2-oidc` configuration: 
```import { Component } from '@angular/core';
import { OAuthService, JwksValidationHandler, NullValidationHandler, AuthConfig } from "angular-oauth2-oidc";

const authConfig: AuthConfig = {
    issuer: 'http://localhost:9011',
    redirectUri: window.location.origin + '',
    clientId: "445f871f-7e1d-462a-ba88-ffb7b91fb3a0",
    scope: 'openid profile email offline_access api name',
    showDebugInformation: true,
    responseType: 'code'
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
    title = 'app';
    constructor(private oauthService: OAuthService) {
        this.oauthService.configure(authConfig);
        this.oauthService.tokenValidationHandler = new JwksValidationHandler();
        this.oauthService.loadDiscoveryDocumentAndTryLogin();
        this.oauthService.setupAutomaticSilentRefresh();
    }
}
```

**Comment by robotdan** [comment]
Hi @paulspencerwilliams 

The JWKS endpoint is published via the OpenID Connect discovery document.
https://fusionauth.io/docs/v1/tech/oauth/endpoints#openid-configuration
https://fusionauth.io/docs/v1/tech/oauth/endpoints#json-web-key-set-jwks

If you do not have at least one RSA / ECDSA keypair configured in FusionAuth there will be no keys to return. 

Navigate to Settings --> Key Master and generate at least one keypair and then assign that as the signing key pair for the JWT configuration in the Tenant and / or Application JWT configuration.

**Comment by robotdan** [comment]
Closing, let me know if this is still an issue.
