### ISSUE TITLE
Allow user reconcile using other fields than email.

### ISSUE THREAD

**Issue by JesperWe** [FusionAuth/fusionauth-issues#346]
### Problem
Use case: An OIDC provider not using email (in our example a government entity that allows citizens to authenticate using a mobile phone 2FA app based on their social security number). 

Authentications made through this provider do not come with an email address, so FusionAuth refuses to create the user.

We can get around this by writing a Lambda that uses any of the unique fields in the resulting JWT to create an email address. But then the created user cannot have a real email address.

### Possible Solution
Let the Lambda specify other unique fields that the user match can happen on.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by JesperWe** [comment]
In Slack, @robotdan said:

This issue has come up a few times, the new “Sign in with Apple” feature is moving towards not exposing a user’s email to the OIDC SP (service provider) during login and instead just providing a unique Id.

In FusionAuth, an email is not required, a username OR email is required. This means in theory the UUID provided by your IdP could be used as the username which would meet the FusionAuth requirement.

However, currently our IdP configurations, OpenID Connect in this case, require an email address to reconcile the user back to FusionAuth. This is because a username is not globally unique, only unique to a particular IdP or application. If we were allow you to reconcile a user to FusionAuth with a username - or a unique identifier, it is not guaranteed to be globally unique. A UUID in theory should be unique, but FusionAuth can’t guarantee that when provided by a third party. If we allow a user then to be reconciled using a value that we can’t guarantee as unique we open ourselves up to account takeover scenarios.

We’ve been thinking about this problem for a while, and we do not yet have a solution.

**Comment by JesperWe** [comment]
Regarding the "guaranteed uniqueness" I'm not sure that it necessary for FusionAuth to be the one that guarantees. In our use case I am positive that the developers of the Swedish national digital Id system have that guarantee in place...

**Comment by robotdan** [comment]
> Regarding the "guaranteed uniqueness" I'm not sure that it necessary for FusionAuth to be the one that guarantees. In our use case I am positive that the developers of the Swedish national digital Id system have that guarantee in place...

@JesperWe This is probably true, in theory it still opens you up to account takeover threats.

This isn't to say we can't do this - but perhaps we just have to document the risk and let the user of FusionAuth vouch so to speak for the guaranteed unique characteristics of this value. 

For example, a Swedish National Digital Id of `123` is guaranteed to be unique in that domain. But if I were to configure another external IdP in FusionAuth that allowed for a similar unique Id to reconcile the user, and that system also used `123` then we would have a collision and the Id may or may not represent the same user. 

If we could use an external Id and lock that value to a particular IdP configuration or name them so to speak that may help make this safer.  

For example, we could build a configuration to name external Id namespaces such as `Apple Id` and `Swedish National Digital Id`. Then if were allow you to select one of these types as the unique identifier within an IdP configuration we could allow you to tell FusionAuth which domain this value is considered unique.

**Comment by pawpro** [comment]
I would imagine that an external user ID (wherever it came from) should necessarily be name-spaced and most likely at least by some identifier of the IdP which I have speculated about here https://github.com/FusionAuth/fusionauth-issues/issues/341 for instance in most aggressive (safe?) way it could be namespaced by the internal FusionAuth Identity Provider ID (UUID or whatever the admin chose). This has some drawbacks but at least during user migrations social IdP users could be stored under the right FusionAuth IdP ID (by default UUID) and so would be reconciled under the right FusionAuth user. The question remains whether it is possible to re-create IdP under a previously existing ID (when custom provided) and for some stale external user IDs to re-surface. But if this was prevented by either cascading deletes on IdP, consistency checks, IdP ID re-use prevention or denying ability to customise IdP ID this cold be mitigated.

**Comment by JesperWe** [comment]
Namespacing should certainly be done. Maybe provide a predefined function in the reconcile Lambda that takes a namespace argument and an id argument, and reconciles based on the resulting value?

**Comment by mooreds** [comment]
Can we close this? It seems to now be supported by using the Links API and linking strategies: https://fusionauth.io/docs/v1/tech/identity-providers/#linking-strategies

**Comment by robotdan** [comment]
I think @mooreds is correct.

Now that we have linking strategies, while we need an email or username to create the user, we can "link" on anything, and the best case scenario is to link on the unique Id provided by the 3rd party IdP so we maintain a link regardless of email or username changes on either end. 

I assume the linking strategies fulfill this requirement. If not, and we are missing a use-case, please re-open with details. 

Thanks!
