### ISSUE TITLE
JWT validate returns wrong exp and iat (GET /api/jwt/validate )

### ISSUE THREAD

**Issue by uncledent** [FusionAuth/fusionauth-issues#347]
### Description 
In the validation response exp and iat have the same value and are wrong.

This is how it is: 

<img width="555" alt="Bildschirmfoto 2019-10-23 um 10 18 48" src="https://user-images.githubusercontent.com/6542981/67367835-f9f86200-f57e-11e9-9b2d-f25a06a42a60.png">

and this is how it is supposed to be:

<img width="483" alt="Bildschirmfoto 2019-10-23 um 10 20 41" src="https://user-images.githubusercontent.com/6542981/67367855-04b2f700-f57f-11e9-9766-9489b3e1f6d6.png">

### Steps to reproduce
1. Make a call to  (GET /api/jwt/validate ) with a valid token

### Expected behavior
See above 

### Screenshots
See above 

### Platform
(Please complete the following information)
 - Device: macos running with docker compose
- FusionAuth™ version 1.10.1

**Comment by robotdan** [comment]
In your first screenshot the two values are not the same, but I think you mean to say they are being returned as milliseconds in seconds, it looks like there are too many digits. 

```
{
  "jwt": {
    "exp": 1571815204000
    "iat": 1571815104000,
  }
}
```

I'll take a look.

**Comment by robotdan** [comment]
The fix will available in the next patch release.
