### ISSUE TITLE
User API to update a user password the same way as import users: Hashed Password + Encryption Scheme + Factor + Salt

### ISSUE THREAD

**Issue by manolofont** [FusionAuth/fusionauth-issues#348]
### Description
Is there any way to update de user password provinding an already hashed password and the encryption scheme used?

Our users come from different sources (LDAP and DBs), and they update their passwords with certain external apps. We only can read the hashed passwords (knowing how each password is hashed) and their salts (with any flavour: Without salt, with salt in the hashed password or with the salt in another field).
We have developed a password encryptor plugin for FusionAuth to manage 3 types of password hashing and it works very well when we import new users to FusionAuth (indicating the hashed password, the encryption sheme, the factor and the salt).
If I'm right, with the User API to update a user, if we indicate the password and the encryption scheme, FusionAuth encodes de new password with the scheme (FA interprets it as a plain password). So, how can we update the hashed passwords of each user in FusionAuth when we receive them from those external sources?

Thanks!

**Comment by robotdan** [comment]
Is this so you can synchronize the password hash between systems?

**Comment by robotdan** [comment]
This is not a use case we currently support. FusionAuth is intended to be the source of truth as it relates to passwords. 

A couple of options:
1. Authenticate against FusionAuth for your LDAP use cases using the Login API
2. Manually update the database fields to synchronize the hash (not recommended, we can't guarantee this won't break in the future, but an option)
3. We could also explore adding the ability to update the the password hash on the User Update API. 

Support and services for our paid clients takes priority with dev resources. We can leave this feature here and as it gets upvoted by the community it will raise higher on the priority list. 

If you'd like to look at pricing for support or pro-services to deliver you this capability in a more timely fashion feel free to use the Contact form on fusionauth.io. 

Thanks!!

**Comment by manolofont** [comment]
We had thought about implementing the second option but, before doing that, we wanted to know if there was a more correct way to accomplish it.

Thank you!

**Comment by mruz** [comment]
I have a similar issue. If it wasn’t implemented, could we reopen it?

**Comment by mooreds** [comment]
@mruz this set of API changes are not planned. 

If you need to validate user passwords against LDAP, or perhaps migrate users from LDAP to FusionAuth, I suggest looking at [the LDAP connector docs](https://fusionauth.io/docs/lifecycle/migrate-users/connectors/ldap-connector). This is a paid feature, fyi.

**Comment by mruz** [comment]
I have a large set of users. I would like to import them into FusionAuth, then later synchronise any password hashes that changed in the meantime, and finally gradually enable FusionAuth.

**Comment by mooreds** [comment]
I think the way I'd approach this is:
* import all users into FusionAuth
* look at local database to see which password hashes had changed
* pull the user data from FusionAuth for each of these users
* delete the user
* re-import the user with the new password hash and the FusionAuth data, maintaining the same userId (if you provide the UUID, we'll use that)

I get that is an additional complexity, but hopefully that helps you with your particular issue.

If not, please open a new issue with this particular use case. I'm not sure we'd choose to update the User API to accept password hashes, etc, but it is an interesting migration related use case, and we're always interested in making that process easier.

I also posted this on the forum for future folks with the same problem: https://fusionauth.io/community/forum/topic/3100/importing-users-over-time
