### ISSUE TITLE
Authentication with nginx loadbalancer

### ISSUE THREAD

**Issue by Thangamh** [FusionAuth/fusionauth-issues#352]
Authentication with nginx loadbalancer

We are using auth2 to authenticate with fusion auth, exact issue is we are using a loadbalancer to route request to fusion auth. we need to configure it. so nginx will accept the request and pass the proxy to our application server, at the moment the application server send the auth request straight to fusion auth server and get authenticated and then the redirect request comes to loadbalancer server straight with token. What we need is now that request to send back the application server again with the token from the loadbalancer. Is there anyway to do that, please help. Really appreciate it.

**Comment by robotdan** [comment]
I would assume you could pull this off using an nginx module of some sort? 

Here is an example in Apache. 
https://github.com/FusionAuth/fusionauth-mod-authnz-external

**Comment by andrewpai** [comment]
I am going to assume that this has been solved. Please re-open the issue if you have additional comments.
