### ISSUE TITLE
Dart / Flutter client support

### ISSUE THREAD

**Issue by climberjase** [FusionAuth/fusionauth-issues#356]
### Problem
Dart and Flutter are not currently supported client libraries.

### Solution
Dart is a supported client library.

### Alternatives/workarounds
A method to wrap Swift and Kotlin native calls from Dart to provide auth.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
@climberjase thanks making this request. I am not a Flutter / Dart expert, is this something you'd be willing to assist with? 

I can stub out the project and show you how to build the templates, etc - if you can provide some expertise on how to put together the code.

**Comment by robotdan** [comment]
Nearly ready for early adopters. 

https://github.com/FusionAuth/fusionauth-dart-client
https://pub.dev/publishers/fusionauth.io/packages

Stay tuned.

**Comment by tyduptyler13** [comment]
Not sure what pub.dev is waiting for but it will be usable whenever they get around to "analysis".

Otherwise: https://pub.dev/packages/fusionauth_dart_client

**Comment by robotdan** [comment]
I'll close this issue out, if anyone has feedback or finds issues - please open them against the dart repo. https://github.com/FusionAuth/fusionauth-dart-client

Enjoy!
