### ISSUE TITLE
Delete Users by Elasticsearch query string

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#361]
### Problem
Deleting users that match a particular criteria can be difficult. Currently you can use the User Search API and use that result to turn around and use the Bulk User Delete API. 

### Solution
Support taking a search query string on the DELETE API to make this super simple. 

One downside of this approach is that it requires your Elasticsearch index to be in sync and consistent. 

- Take the `queryString` request parameter on the `GET` method
- Take `queryString` in the request body for the `POST` method

### Alternatives/workarounds
Currently you can use the User Search API and use that result to turn around and use the Bulk User Delete API. 

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by corepay** [comment]
Suggestion - would be great if we could have a bulk delete on the entities by entering the `id` as a path param with maybe a query param to identify type.  Example:

`.../api/user/bulk/818e31d7-a9c0-4e40-93c3-3236305716e3type=tenantId&hardDelete=true&dryRun=false`

`.../api/user/bulk/818e31d7-a9c0-4e40-93c3-3236305716e3type=applicationId&hardDelete=true&dryRun=false`

**Comment by corepay** [comment]
PS your docs need to updated here:  https://fusionauth.io/docs/v1/tech/apis/users#bulk-delete-users

![image](https://user-images.githubusercontent.com/48992923/69915785-66da0400-1429-11ea-84fb-860a14c0441c.png)


Notice in image the example request param shows `searchQuery` and the table descriptions shows `queryString` as request param.

**Comment by robotdan** [comment]
@trex can you verify this is resolved for the upcoming release of this feature?

**Comment by trex** [comment]
👍 @robotdan.  The docs have been updated for consistency.  The parameter will be `queryString`.  Thanks for the catch @corepay!
