### ISSUE TITLE
Support a Prometheus Status / Metrics endpoint

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#362]
### Problem
We currently offer a status endpoint `/api/status` which returns Drop Wizard metrics in JSON format.  This may not be consumable for everyone and the response format is subject to change. 

### Solution
Open a Prometheus endpoint as well. 
https://prometheus.io/docs/prometheus/latest/querying/api/

### Alternatives/workarounds
Use our current status endpoint.

### Additional context
Should we look at this while we are at it? https://github.com/FusionAuth/fusionauth-issues/issues/1142

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Duplicate here https://github.com/FusionAuth/fusionauth-issues/issues/440

**Comment by drpebcak** [comment]
Would love to have this! I think it would be cool to see application metrics and also some different usage stats. My preference would be that this endpoint is on a different port, since that makes it easy to avoid exposing it publically.
