### ISSUE TITLE
SAML Response Signature Flexibility

### ISSUE THREAD

**Issue by mikerees** [FusionAuth/fusionauth-issues#365]
### Description 
An SP I am attempting to integrate with requires the Signature be a direct child of the Response node. Currently FusionAuth can only place the Signature within the Assertion node. With regards to SAML 2.0 Core specification section 5, Signatures can optionally be placed in either location. It's unfortunate that this SP requires the Signature to be both present and in a specific location, but it's a requirement that is part of a valid SAML Response schema so I'm expected to work around it.

### Steps to reproduce
Just generate a SAML Response.

### Expected behavior
Signature can optionally be placed as a child of the Response node.

### Screenshots
I've attached some XML files with current and required formats:
[samlResponse.txt](https://github.com/FusionAuth/fusionauth-issues/files/3824097/samlResponse.txt) What is currently generated

[samlResponse-expected.txt](https://github.com/FusionAuth/fusionauth-issues/files/3824098/samlResponse-expected.txt) What is required by the SP I am trying to integrate with

### Platform
Amazon AL2 Linux AMI
FusionAuth 1.11.0

**Comment by robotdan** [comment]
@mikerees If we added a configuration option to the SAML IdP (in the application config) to allow you to select to place the signature in the assertion (as it is today) or in the response, would this solve your use case?

**Comment by robotdan** [comment]
@mikerees if you are still in a spot where you could use this feature, let us know it works out for you. Thanks!
