### ISSUE TITLE
SecurityTokenSignatureKeyNotFoundException with ASP.Net Core 3

### ISSUE THREAD

**Issue by SeanStayn** [FusionAuth/fusionauth-issues#368]
### Description
I try to get FusionAuth OpenId Connect working with an ASP.Net Core server-side Application. 
After the login in the FusionAuth form, I will be redirected to "https://localhost:44389/signin-oidc". On this page the following error message is shown:

> SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'bf499692-4847-440d-b46f-c264113890ea'.
Exceptions caught:
''. 
token: '{"alg":"HS256","typ":"JWT","kid":"bf499692-4847-440d-b46f-c264113890ea"}.{"aud":"bf499692-4847-440d-b46f-c264113890ea","exp":1573560933,"iat":1573557333,"iss":"acme.com","sub":"aff98569-eecf-4178-8555-1e4885d61bb1","authenticationType":"PASSWORD","email":"u1@users.com","email_verified":true,"at_hash":"Njn3LxGCBkXK_z4eYgkRaA","c_hash":"tN2BwONbm05hQ2hcCQGMsg","applicationId":"bf499692-4847-440d-b46f-c264113890ea","nonce":"637091541329537125.NTEwOGVlMzItZjAwMi00YzBhLWJmMWQtZWM1ZTQ5NzI0OGM0YTY4NWIxNDYtMTI1NC00ZmQ1LTgwZWMtZmRhMWZkYzE3YzA2","roles":[]}'.
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(string token, TokenValidationParameters validationParameters)
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

The kid is the application id in FusionAuth.

### Steps to reproduce
1. Create Blazor-App with Visual Studio 2019
2. Add OpenId Connect package: `Install-Package Microsoft.AspNetCore.Authentication.OpenIdConnect`
3. In Startup.cs under `public void ConfigureServices(IServiceCollection services)` add
```
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("Cookies")
            .AddOpenIdConnect("oidc", options =>
            {
                options.Authority = "https://fusionauth-app.westeurope.cloudapp.azure.com";
                options.RequireHttpsMetadata = true;
                options.ResponseType = OpenIdConnectResponseType.Code;
                options.ClientId = "bf499692-4847-440d-b46f-c264113890ea";
                options.ClientSecret = "J5ArSPqmKHBwUC-uN4YDhBxcuqQKAtbbfVD4DvYqKtU";
            });

            services.AddMvcCore(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });
```
4. In Startup.cs under `public void Configure(IApplicationBuilder app, IWebHostEnvironment env)` add `app.UseAuthentication();` 
`IdentityModelEventSource.ShowPII = true; // to get more error information`

5. Click on IIS Express in Visual Studio 2019 to start the application

### Login-Credentials: 
E-Mail: u1@users.com
Password: User1.FusionAuth

### Expected behavior
After the redirect, I want to come to the home page of the website.

### Platform
 - Device: Desktop
 - OS: Windows 10
 - Azure VMs (FusionAuth environment)
     1. FusionAuth-App (Linux, with Apache & Certbot SSL certificate to get a HTTPS endpoint)
     2. FusionAuth-Search (Linux)
     3. MySQL Database (Windows)

### Versions
- ASP.Net Core 3
- Microsoft.AspNetCore.Authentication.OpenIdConnect (version 3.0.0)
- Visual Studio 2019
- FusionAuth 1.11.0
- Apache/2.4.29 (Ubuntu)

**Comment by robotdan** [comment]
I am not very ASP.Net smart, but this looks to be an issue with `Microsoft.AspNetCore.Authentication.OpenIdConnect`. 

This issue indicates JWKS is not implemented yet which means you'll have to manually configure the keys into your configuration. 
https://github.com/aspnet/AspNetCore/issues/8067

A example solution is provided in this comment
https://github.com/aspnet/AspNetCore/issues/8067#issuecomment-469159913

The JWKS endpoint in FusionAuth is `/.well-known/jwks.json`. 
https://fusionauth.io/docs/v1/tech/oauth/endpoints#json-web-key-set-jwks

**Comment by voidmain** [comment]
@SeanStayn - I'm not sure if you work with Thomas or are Thomas, but I replied via email to him and the email server rejected it. It says his mailbox is full. It might be better to use your company email addresses rather than the `web.de` or other public systems.

**Comment by SeanStayn** [comment]
I could solve the problem.

I have added the following code after  `options.ClientSecret = "J5ArSPqmKHBwUC-uN4YDhBxcuqQKAtbbfVD4DvYqKtU";`:

```
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    IssuerSigningKeyResolver = (token, securityToken, kid, parameters) =>
                    {
                        var client = new HttpClient();
                        var response = client.GetAsync("https://fusionauth-app.westeurope.cloudapp.azure.com/.well-known/jwks.json").Result;
                        var responseString = response.Content.ReadAsStringAsync().Result;
                        var keys = JsonConvert.DeserializeObject<JwkList>(responseString);

                        return keys.Keys;
                    },
                    ValidIssuers = new List<string>
                    {
                        "https://fusionauth-app.westeurope.cloudapp.azure.com"
                    }
                };
```

where JwkList is: 
```
    public class JwkList
    {
        public List<JsonWebKey> Keys { get; set; }
    }
```

Another important step is to activate JWT in the Application Settings (Admin UI).

Thank you for your help!
