### ISSUE TITLE
Typo in upgrade Instructions

### ISSUE THREAD

**Issue by f0rever-johnson** [FusionAuth/fusionauth-issues#37]
Don't think thats the correct subtitle for this step in the upgrade process. 
<img width="1680" alt="screen shot 2018-11-16 at 12 21 00 am" src="https://user-images.githubusercontent.com/21150708/48599458-be4c2580-e935-11e8-8e11-3a82f4211734.png">

**Comment by robotdan** [comment]
Thanks @f0rever-johnson , great catch. Are you looking for a job? :-)

**Comment by robotdan** [comment]
@f0rever-johnson Feel free to submit pull requests as well. Thanks!
https://github.com/FusionAuth/fusionauth-site

**Comment by f0rever-johnson** [comment]
I am working on creating a client library for Swift 4. FusionAuth is **perfect** for use as the authentication backend for my iOS App but the lack of a swift 4 client library is really debilitating. I am creating a client library as part of my app but I am running into trouble as it is my first time creating a client library. Would you open to me publishing code & you help/revise/advise me? @robotdan

**Comment by robotdan** [comment]
I'd love to get a swift client going and I'd be happy to help. 

We build most of client libraries using a template. See the following links, I have a swift stub there, view some of the others. That template gets built using our JSON DSL. 

https://github.com/FusionAuth/fusionauth-java-client/tree/master/src/main/api


https://github.com/FusionAuth/fusionauth-java-client/tree/master/src/main/client

Feel free to share what you have so far via gist our however you want and we can collaborate.

I can also stub out the project and you can submit a PR. Whatever you prefer.
