### ISSUE TITLE
Possibility to replace ElasticSearch by Sonic

### ISSUE THREAD

**Issue by ghost** [FusionAuth/fusionauth-issues#371]
Hello,
It'll be good to be able to use [Sonic](https://github.com/valeriansaliou/sonic) instead of ElasticSearch.
Regards

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1558

**Comment by robotdan** [comment]
Not planning to implement another search engine. We do plan to support OpenSearch in addition to Elasticsearch.
