### ISSUE TITLE
Logrotate : missing configuration in packages

### ISSUE THREAD

**Issue by ghost** [FusionAuth/fusionauth-issues#372]
Hello,
When installing fusionauth-app*.deb and fusionauth-search*.deb _(need to verify with RPM packages)_, no **/etc/logrotate.d/fusionauth** file is created and this create a problem with : fusionauth-app.log
When he grows to multiple GB, it's very problematic because he has weeks and weeks inside and nothing to cleanup.

Just an idea:
```
/usr/local/fusionauth/logs/*.log {
       daily
       rotate 7
       copytruncate
       delaycompress
       compress
       notifempty
       missingok
}
```

Additional example for `fusionauth-app.log`

```
/usr/local/fusionauth/logs/fusionauth-app.log {
       compress
       copytruncate
       delaycompress
       missingok
       notifempty
       rotate 7
       size 2M
}
```

**Comment by robotdan** [comment]
We're currently using SLF4 / Logback which supports this natively. We could explore adding a log rotate config, or just use the `RollingPolicy` configuration in logback. 

http://logback.qos.ch/manual/appenders.html

**Comment by colundrum** [comment]
Actually, rotation is working only on 1 file: fusionauth-search.log but don't like I want to have about how many old log files.
It'll be good to have rotation but in case of Rolling policy, it'll be good to have possibility to change values like how many files we can keep.
Thanks a lot for improving

**Comment by robotdan** [comment]
We'll be satisfying this issue under https://github.com/FusionAuth/fusionauth-issues/issues/575.
