### ISSUE TITLE
Make the root page a landing page

### ISSUE THREAD

**Issue by prasanna10021991** [FusionAuth/fusionauth-issues#378]
### Problem
There are times when users of particular application within the default tenant accidentally access the tenant's login ending up with the error seen below

<img width="468" alt="Screenshot 2019-11-21 at 12 25 48 AM" src="https://user-images.githubusercontent.com/39335934/69313185-d811fe00-0c56-11ea-9e5e-4525ac57ad98.png">

### Solution

For the following options, we'll assume FusionAuth is available at `https://login.acme.com`. 

#### Option 1

Configure a redirect to your application. In FusionAuth, we could offer a global setting that indicates where we should redirect the user when they access `https://login.acme.com`. 

An example would be to redirect the user to `https://acme.com`. 

Then, in order for an admin to access the FusionAuth login page, they would need to access `https://login.acme.com/admin`. When the user navigates to this URL they would then be redirected through the OAuth2 login workflow and then back to the FusionAuth admin application. 

#### Option 2

Build a landing page instead of redirecting. 

For example, when the user navigates to `https://login.acme.com`, instead of being redirected to your application or to the FusionAuth admin login, instead this would be FusionAuth landing page. 

This page may have a simple FusionAuth branded page with a small button somewhere in the header that would allow the user to navigate to `https://login.acme.com/admin`. 

For users that were not attempting to access the admin UI, they would now just be at a dead end page that says FusionAuth.

 
### Alternatives/workarounds

You can configure a redirect in your own application / network to redirect users back to your application. 

> A common strategy is to redirect the base url to you app. For example, login.acme.com would redirect to acme.com. and then to access the admin login, you'd access login.acme.com/admin - @robotdan 

### Duplicates
https://github.com/FusionAuth/fusionauth-issues/issues/670

**Comment by robotdan** [comment]
Thanks for taking the time to open the issue @prasanna10021991 !

We'll review this and see when we can get it into plan.

**Comment by zbruhnke** [comment]
agreed on this – we're currently doing something similar when using the Oauth2 flow.

In our case when setting up our devs for local development we also prefer to setup a tenant with all the settings we'd want to use.

Since we cannot delete the default tenant or know the ID inherently because it gets created on startup by FA we end up with a two tenant setup locally which is less than ideal obviously.

This means we either end up configuring the tenant to match closely to our newly created tenant ID (think things like using Mailhog for SMTP setup so password resets etc work locally) or we just end up with two wholly different tenants one of which we need to know the tenant ID for (which we'll generally need anyway to get to from the front end app etc.)

In an ideal world we'd probably just have a way to dictate the tenant ID when scripting startup in that scenario and in the deployed scenario like this describes it would just auto-redirect to a user signup wheres an "admin" login would be at an admin url like what the user above describes.

**Comment by robotdan** [comment]
In 1.26.0 this root page is just a themed landing page. You can theme it, redirect users from it somewhere else, etc.

**Comment by jegger** [comment]
We face the issue that the root landing page (not bound to any tenant) can not be changed. Users can get to this page accidentally. I have the feeling that it did got even a bit more confusing for end users with your updated page (which points out help for developers integrating with FusionAuth)

Should I open a new issue for that? I see two things:
- Make the page more generic
- Make this page customizable as well

**Comment by voidmain** [comment]
Hi @jegger - the root page is themeable and you can make it contain any information you want. Or you can simply add a `meta-refresh` and redirect the browser to your homepage. You'll need to create a new Theme and then apply that Theme to all of your Tenants, including the default Tenant.

Hope that helps!

**Comment by mooreds** [comment]
@jegger are you referring to the issue that there is no way to customize the default theme root page (because the default theme is immutable) and that going to the root URL of any FusionAuth instance will send you to the default FusionAuth application, which uses that default theme?

**Comment by jegger** [comment]
@mooreds Correct. I am talking about the root url of FusionAuth. Is there a way to change that?

**Comment by jobannon** [comment]
@jegger - To change the theme, you need to copy it, update the index freemarker template, and make sure that the default tenant, and any other tenants that you would like, have that new theme selected.  Steps below.  

____________
Note: This follow the advice of @voidmain.  I believe that @mooreds had a slightly more nuanced question.  If the below steps don't offer you what you need let us know.  
____________

# Navigate to Themes
- Duplicate the Default theme.  The default theme is "unchangeable" as it is shipped with FusionAuth.  

![image](https://user-images.githubusercontent.com/16090626/123155147-f89ecd00-d424-11eb-9a33-6df86493c77d.png)

# Name your theme and click save (floppy disk icon)
- The index page is the page that will have the customizations.  We use Freemarker for theme pages.

![image](https://user-images.githubusercontent.com/16090626/123155312-2edc4c80-d425-11eb-9bd1-1688b97aaf80.png)

# Update all your Tenants to your new theme (including the default theme)
- Click on the edit box, and select a new theme.
![image](https://user-images.githubusercontent.com/16090626/123155365-43b8e000-d425-11eb-8c58-d1c9474aac81.png)

![image](https://user-images.githubusercontent.com/16090626/123155391-516e6580-d425-11eb-8dd8-4c347bd2d46b.png)

### Be sure to include the default tenant - update to new theme with new index page
![image](https://user-images.githubusercontent.com/16090626/123155573-82e73100-d425-11eb-9096-872e434e88ba.png)

# End Result
![image](https://user-images.githubusercontent.com/16090626/123155960-f5581100-d425-11eb-8b14-66e215963cee.png)

**Comment by jegger** [comment]
I was not aware that you can change the template of the default tenant. With knowing that everything makes sense and my problem is solved. Thanks!

**Comment by jobannon** [comment]
Great glad we solved it!

Further doc is available here, for the other GH users that come across this issue post.

https://fusionauth.io/docs/v1/tech/themes/
