### ISSUE TITLE
Poor login performance with Google Signin

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#380]
### Description 
I've been struggling to understand why our users see long delays after submitting Google credentials upon login. Delays of 3 - 12 seconds are not uncommon. We are running FusionAuth on an AKS based VM and login takes about 12 seconds for the first visitor after a long idle period. 

There will be other things to check but I'd like to sanity check these log entries please:

```
Google IdP Response Debug Log

11/22/2019 09:28:06 AM UTC Call the [https://www.googleapis.com/oauth2/v3/tokeninfo] endpoint.
11/22/2019 09:28:06 AM UTC Endpoint returned status code [200]
11/22/2019 09:28:06 AM UTC User to reconcile: 
{
  "encryptionScheme" : null,
...
}
11/22/2019 09:28:08 AM UTC The user with the email address [david@become.education] already exists.
11/22/2019 09:28:08 AM UTC Merge the reconciled user from the Identity Provider into the FusionAuth user.
11/22/2019 09:28:09 AM UTC User is already registered for application with Id [e9020e75-4836-4e02-a89a-fffc34efb821].
11/22/2019 09:28:09 AM UTC User has successfully been reconciled and logged into FusionAuth.
11/22/2019 09:28:09 AM UTC Authentication type: GOOGLE
11/22/2019 09:28:09 AM UTC Authentication state: Authenticated
```

The last entries seem odd, even if the responses are speedy.  Log seems to imply that my login is seen as a create user event "email address already exists", that the IdP to FusionAuth merge isn't a one time event, and that an application registration was attempted.  I've logged in using this account many times so this result might indicate that the login isn't as efficient as it could be. Or maybe the log entries are misleading.  Thoughts?

**Comment by robotdan** [comment]
>  Log seems to imply that my login is seen as a create user event "email address already exists", that the IdP to FusionAuth merge isn't a one time event, and that an application registration was attempted.

I don't know if I follow. Each time you login with Google we have to identify if you exist yet in FusionAuth, we can't know ahead of time if the user Google has authenticated exists in FusionAuth until we look them up by email address. 

The log you show looks to be a few seconds in duration, this is FusionAuth making API requests to Google, not much we can do there to increase performance. Logging in with an external provider will in most cases be slower than a local authentication against FusionAuth. 

If you have webhooks, or lambdas being invoked during the login process these things could also be elongating the login process.

**Comment by robotdan** [comment]
@davidmw Were you able to identify the cause of the slow down during login?

**Comment by davidmw** [comment]
We got additional clarity on the issue - it wasn't limited to Google SSO. Our installation on AKS was using Azure Managed PostgreSQL and we had a high rate of connection failures after about 3-4 minutes of login inactivity. PostgreSQL wasn't accepting the batch of pool connection retries that followed. We decided to host PostgreSQL in the same VM as FusionAuth to avoid the problem since solving the configuration problem wasn't an easy fix.

**Comment by robotdan** [comment]
Interesting, I wonder if you exceeded your provisioned IOPS. I think Azure provides 3 IOPS per GB on their managed PostgreSQL service so unless you scale up your DB disk size the performance can be severely limited.

**Comment by davidmw** [comment]
We upgraded the managed PostgreSQL server - it basically remained at idle. That config supports 50 connections, we bumped ulimit and FusionAuth memory settings, and deployed with Accelerated Networking. Brian's got a copy of our FusionAuth log - we made arrangements for some support hours to work the problem but did a quick comparison with a test deployment on a VM and decided to stay with that.
