### ISSUE TITLE
Fusion Auth eventually runs Out of Memory on AWS t2.micro instance

### ISSUE THREAD

**Issue by scottvelasquez** [FusionAuth/fusionauth-issues#381]
I've installed and setup Fusion App and Fusion Search to a single Ubuntu 18.04 t2.micro instance (db setup as separate RDS instance) and twice now it's failed AWS status checks after running for a day or so. This is a development environment as I'm still building the web application so user counts are 1-2 at the most.

<img width="751" alt="Screen Shot 2019-11-24 at 12 34 29 AM" src="https://user-images.githubusercontent.com/16527037/69490853-fb090180-0e52-11ea-8b5d-26ca6714b20d.png">

I've also noticed upon investigating this that the CPU also hits 100% at some point, perhaps around the same time as the issue. I'm certainly not doing anything on my end to peg the CPU (API calls to setup PostMan collection, etc).

<img width="915" alt="Screen Shot 2019-11-24 at 12 42 09 AM" src="https://user-images.githubusercontent.com/16527037/69490919-de20fe00-0e53-11ea-966f-91de63e41a84.png">

Any help would be appreciated.

**Comment by voidmain** [comment]
t2.micros are pretty small to run everything on. The default RAM settings for fusionauth-app and fusionauth-search are 256M. Have you changed those settings?

If FusionAuth is using 500-600M of RAM and the OS and any memory mapped files that Elastic Search might use are eating up the rest of it, then the server might not be able to manage. If you are also running the database on the same instance, that would eat up more RAM as well.

My guess is that Java asks for more RAM and the OS tells it that it doesn't have any. Then Java tries to clean up and then asks for more RAM again. This cycle might go on and on and that could be the cause of the CPU spike right before the crash.

We use t3.mediums as our lowest hosting offering, hence the reason they start at $75/month. These run pretty well and we have a lot of people running on those servers. I would suggest that you bump your instance size or try playing around with the RAM settings for FusionAuth. Also, if you off-load Elastic Search from the server and use AWS's hosted Elastic Search, then you will free up more memory. Elastic Search is a hog and really needs a lot of RAM and virtual space for memory mapped files and the like.

**Comment by robotdan** [comment]
In addition to what @voidmain mentioned, what type of RDS are you using? PostgreSQL, MySQL, Aurora, etc?

**Comment by scottvelasquez** [comment]
@voidmain - No, I hadn't tried configuring the RAM settings for fusionauth-app. I'll mess around with that and running fusionauth-search on another EC2 instance. Looks like there is a free tier of AWS Elastisearch so I'll look into that as well. 

@robotdan - I'm using mysql 5.7 on a separate AWS RDS.

Thanks for the feedback!

**Comment by SebastianCanonaco** [comment]
@scottvelasquez Same problem here, the CPU Utilization just fires up to 100% and my EC2 instance of FA running of ECS just resets, did you manage to resolve it?

**Comment by LucasPiffer** [comment]
Facing a similar problem. What AWS configuration do you think is best suitable for running FusionAuth in production? I have been using Postgres RDS.

**Comment by mooreds** [comment]
Hiya @LucasPiffer 

This type of question is best asked on the forum: https://fusionauth.io/community/forum/

Here's a forum post about what you can expect with t2.mediums: https://fusionauth.io/community/forum/topic/8/what-level-of-performance-can-we-expect-with-using-fusionauth-as-an-idp

Here's a forum post on loading users to test your particular scenario (which is always going to be the best way to get numbers appropriate for your system): https://fusionauth.io/community/forum/topic/631/loading-large-numbers-of-users

HTH.

**Comment by LucasPiffer** [comment]
Awesome @mooreds thanks for the answer! <3
