### ISSUE TITLE
Login after change password with JWT not providing refresh token

### ISSUE THREAD

**Issue by colingm** [FusionAuth/fusionauth-issues#382]
### Description
I am currently trying to implement the ability for a user to change their password when they are already logged in. According to the documentation for the change password API when performed using a JWT and including a current refresh token (as either param or cookie) the resulting one time password will give you a refresh token when you login using that one time password. However, following that exact process, the login API is only returning a JWT and not a refresh token as well.

**Comment by robotdan** [comment]
Can you provide the JSON request you're sending to the Change Password API? 

If you send in the `refreshToken` parameter in the request body, this should allow you to receive a Refresh Token on the login response. 

If you also have a cookie in the request this will take precedence over the value in the request body, so if you're using Insomnia, or Postman which may be holding onto cookies verify that you don't have a stale cookie that is being sent along with this request.

**Comment by colingm** [comment]
@robotdan of course, here is the JSON body

```
{
	"currentPassword": "Asdf123!",
	"password": "Asdf123!",
	"refreshToken": "GbyYBFsjCcCFFGxgUPKfKkSICMftCgY7HeErmuoHzmgfKSF6rhZ1Ww"
}
```

Here is my full cURL request for reference (minus our actual url)
```
curl -X POST \
  http://localhost:9011/api/user/change-password \
  -H 'Accept: */*' \
  -H 'Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjE1YWExMjQ4OCJ9.eyJhdWQiOiIzNjRlZThjNC04ZTAzLTU1ZTUtYTg4Yy05YzhiYjViZTExZmIiLCJleHAiOjE1NzQ3MDcyNDksImlhdCI6MTU3NDcwNjM0OSwiaXNzIjoiaHR0cHM6Ly9pbXNjcmUuY29tIiwic3ViIjoiMjhkNmIwZWYtNGVlYy00YjY4LTlkNmQtMmZjNDc1NmMzMmM3IiwiYXV0aGVudGljYXRpb25UeXBlIjoiUEFTU1dPUkQiLCJlbWFpbCI6InJvbGxzcm95Y2UwQHFzZmRldmVsb3AuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImFwcGxpY2F0aW9uSWQiOiIzNjRlZThjNC04ZTAzLTU1ZTUtYTg4Yy05YzhiYjViZTExZmIiLCJyb2xlcyI6WyJ1c2VyIl19.zHKWvL3K7wjdoHolpXVYbRmcoiQ0Y-jdjR8yfAuh-dM' \
  -H 'Content-Type: application/json' \
  -H 'X-FusionAuth-TenantId: caf78f04-ad7a-5584-8272-6ef7d818f882' \
  -d '{
	"currentPassword": "Asdf123!",
	"password": "Asdf123!",
	"refreshToken": "GbyYBFsjCcCFFGxgUPKfKkSICMftCgY7HeErmuoHzmgfKSF6rhZ1Ww"
}'
```

**Comment by colingm** [comment]
@robotdan Also of note, if I get a change password id from the forgot password flow, changing my password that way does provide a one time password that logs in and returns a refresh token

**Comment by robotdan** [comment]
Thanks for that additional context, that is helpful. I'll have to dig a bit further, but I think you've run into a bug. 

More to come.

**Comment by robotdan** [comment]
Fixed. Will be out in the next release, thanks for reporting!

**Comment by colingm** [comment]
@robotdan No problem thanks for the quick turn around!
