### ISSUE TITLE
Connect Kibana with FusionAuth Elasticsearch

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#388]
### Problem
I want to make better use of ElasticSearch indices by visualizing them in Kibana for auditing and troubleshooting purposes. This way it would be easy to monitor user activity, logs, alerts, events etc.

### Solution
Can you provide the documentation with steps to integrate Fusionauth ElasticSearch with Kibana. Which index pattern to choose? Any custom configurations needed? etc 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
There is currently only a single index called `fusionauth_user`. This is subject to change. 

You should be able to ask Elasticsearch for all of the indicies. 
```
curl http://localhost:9021/_aliases?pretty=true
```

Outside of the index names, the rest is vanilla Elasticsearch, so there shouldn't be anything specific to FusionAuth when hooking it up to Kibana.

**Comment by prabhakarreddy1234** [comment]
@robotdan  thanks.

I setup kibana now and created an index pattern for `fusionauth_user` but i see search records with only 3 fields `birthDate`, `insertInstant`, `lastLoginInstant` .

![image](https://user-images.githubusercontent.com/1984707/71017842-2e0b8180-20ef-11ea-92d6-5aa853f3350d.png)

So it does look like only those 3 fields have some data in them. Other important fields like `email`, `fullName`, `mobilePhone` etc doesn't have any value. Can you please confirm if all the fields as shown in the below screenshot are being populate with relevant data.

![image](https://user-images.githubusercontent.com/1984707/71018085-ba1da900-20ef-11ea-8152-b51ee0384c2b.png)

**Comment by robotdan** [comment]
You can look at the index in Elasticsearch directly if you like, I can't really offer you support for Kibina outside of a support contract. Thanks!
