### ISSUE TITLE
Allow Soft-Delete but denied Hard-Delete

### ISSUE THREAD

**Issue by SeanStayn** [FusionAuth/fusionauth-issues#390]
### Problem
For us it is important that users are set to inactive when deleting. With the current API it is possible to change between Soft- and Hard-Delete by appending a flag, without a stronger authorization.

### Solution
Adding another authorization level for hard deletion of users would solve the problem.
Alternatively, a tenant-wide setting to allow soft or hard deletion can be successful.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the suggestion @SeanStayn .

Are you looking to make an API key be able to soft delete, but not soft delete, and vice versa?

**Comment by SeanStayn** [comment]
Thanks for you fast response @robotdan 

> Are you looking to make an API key be able to soft delete, but not **soft** delete, and vice versa?

I'm looking to make an API key be able to soft delete, but not **hard** delete. (I think you mean the same.)

The API key that can hard delete may also support soft delete.

It is important that we have an API key that only allows soft deletion.

**Comment by robotdan** [comment]
Thanks for the clarification @SeanStayn I think I understand. 

If you have an immediate need for this issue, we do offer paid support and professional services to deliver this feature on your timeline. 

If it is not urgent, we will prioritize this feature once it makes its way to the top of the stack. Thanks!

**Comment by SeanStayn** [comment]
Thanks for the fast response @robotdan.

We are very pleased that you are able to respond to special customer requests! :)

We are currently in the evaluation phase of various authentication tools. As soon as the evaluation phase is finished I will contact you by e-mail.

Regards

**Comment by robotdan** [comment]
> We are currently in the evaluation phase of various authentication tools. As soon as the evaluation phase is finished I will contact you by e-mail.


Great, I'll re-open this issue since it may be valuable to others as well. We use open issues to allow the community upvote important features to help us prioritize resources. 

Thanks!
