### ISSUE TITLE
Using FusionAuth as proxy Service Provider with ADFS IdP

### ISSUE THREAD

**Issue by daya** [FusionAuth/fusionauth-issues#395]
## Using FusionAuth community version as Proxy Service Provider with ADFS IdP

We have bunch of apps implementing their own SAML SP logic with ADFS being the IdP (SAML) and we would like to centralize the Auth logic using FusionAuth. Such that FusionAuth acts as Proxy Service Provider in that after Authentication with IdP and redirect to FusionAuth (proxy serivce) it will redirect to the actual service. So from the actual service point of view FusionAuth acts as an IdP Proxy which delegates to ADFS IdP.

Is this possible ?

**Comment by robotdan** [comment]
@daya have you reviewed the IdP configuration options? 

https://fusionauth.io/docs/v1/tech/identity-providers/

These can also be integrated using an API if you want to make it all seamless to your end users. 

https://fusionauth.io/docs/v1/tech/apis/identity-providers/

**Comment by daya** [comment]
> @daya have you reviewed the IdP configuration options? 
> 
> https://fusionauth.io/docs/v1/tech/identity-providers/
> 
> These can also be integrated using an API if you want to make it all seamless to your end users. 
> 
> https://fusionauth.io/docs/v1/tech/apis/identity-providers/

Thanks I did not know that

**Comment by robotdan** [comment]
Great, I'll close this issue out for now, if you find a gap in our feature set for your use case, feel free to open a feature request. 

Thanks for using FusionAuth!
