### ISSUE TITLE
Which Java is compatible ?

### ISSUE THREAD

**Issue by colundrum** [FusionAuth/fusionauth-issues#396]
Hello,

I try to standardize Java versions and I need to know which Java version I can use with FusionAuth.

I've AdoptJDK with Atlassian products (hotspot mode) so can I use the same version or another ?

Thanks

**Comment by robotdan** [comment]
FusionAuth packages and uses its own Java 8 runtime.

https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements

**Comment by colundrum** [comment]
Sorry but the last time, deb package wasn't with Java included

**Comment by robotdan** [comment]
> Sorry but the last time, deb package wasn't with Java included



That is correct. Due to the licensing model of Java, we are somewhat careful in how we distribute it with FusionAuth. 

When using the deb, RPM or zip file, on first start up we download the JRE if necessary. This way we can keep our packages small, and re-use the same JRE if you also download the `fusionauth-search` bundle as well.

**Comment by colundrum** [comment]
Ow ok, it's automatically downloaded. Perfect, thanks
Otherwise, I needed to install it manually.
Is it the same with tar archive? Your deb package force install inside /usr/local so it can become a little problem about partitioning schema

**Comment by robotdan** [comment]
Yes, the zip archive will do the same thing. On first start it will download Java. 

If you want to install somewhere other than `/usr/local/fusionauth` the zip will be a good choice. You can also use the fast path install to do the download and unzip etc all in one step. 

```
sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh -s - -z"
```

**Comment by colundrum** [comment]
I can't use the fast path install because I need to do it with possible audit.

Yes, I use zip but for Java, so I can use the automatic download otherwise I need to install the same strict version ?
Is it possible to use AdoptJDK ?

**Comment by robotdan** [comment]
> Is it possible to use AdoptJDK ?

In theory, we have not tested it.
