### ISSUE TITLE
Feature: Inverted multi-tenancy

### ISSUE THREAD

**Issue by dseller** [FusionAuth/fusionauth-issues#4]
**Is your feature request related to a problem? Please describe.**
My application uses a multi-tenant architecture. However, compared to FusionAuth, it's "inverted". This means that in my situation, users are not part of a tenant, but rather, one single user can be part of multiple tenants simultaneously.

In the pre-FusionAuth situation, the tenant ID was part of the JWT. When a user switched to a different tenant, they would receive a new JWT with the new tenant ID (and the JWT would be resigned and valid). Subsequent API calls are therefore automatically executed in the context of the (new) tenant.

**Describe the solution you'd like**
I would like to be able to add a single existing user to one or more tenants ("inverting" the relationship between tenants and users, compared to the current implementation). I would also like the option to query the API for tenants that the currently logged in user belongs to, so I can show a list of available tenants to my users.

**Describe alternatives you've considered**
I have been toying with using groups as a workaround, and I came quite far with this approach. However, there is no way to add a custom claim to the JWT in which I can place the "current tenant ID". A solution for this could be to add an option to the JWT settings, which would cause the JWT generator to insert the user data object to the JWT. I could then use the user data object to store the "current tenant ID".

**Additional context**
None.

**Comment by robotdan** [comment]
Hi @dseller , thanks for the request. 

What you're describing is how we think about Applications in FusionAuth.  In FusionAuth you can have one-to-many Applications, each application represents an authenticated resource. 

When a JWT is issued by FusionAuth, the `applicationId` will be provided in the JWT payload.  
https://fusionauth.io/docs/v1/tech/tutorials/json-web-tokens#jwt-payload

The Getting Started page has an overview of the User and Applications concepts in FusionAuth.
https://fusionauth.io/docs/v1/tech/getting-started/
https://fusionauth.io/docs/v1/tech/tutorials/create-an-application

Similar to how you describe the JWT and switching to a new "tenant" and receiving a new JWT, this also fits into how we see Applications. A JWT is issued to a user per application, once you have a valid JWT you can either use our OAuth login to receive a new JWT for another Application, or use our JWT APIs to issue yourself a new JWT for another Application from a valid JWT.

https://fusionauth.io/docs/v1/tech/apis/jwt#issue-a-jwt

Regarding to query by tenant, the User Search API allows you to use criteria such as Application Id, Tenant Id, Group Id and others to allow you to narrow your result set. 

https://fusionauth.io/docs/v1/tech/apis/users#search-for-users

Let me know if you'd like a hand with any of these APIs, or if I can provide you additional information.

**Comment by dseller** [comment]
Thanks for your elaborate response. I have implemented the solution using Applications as "tenants". In order to present the user with a list of available applications, I simply use the registrations array on the User object. Perfect!
