### ISSUE TITLE
Windows : The search engine appears to be down or failing to respond to the search query.

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#40]
### Description
When running on Windows, even though the search engine is running, I receive a message such as 

<img width="834" alt="screen shot 2018-11-21 at 2 51 12 pm" src="https://user-images.githubusercontent.com/1148709/48870158-f374cf80-ed9c-11e8-9115-e778437e2a4a.png">

> The search engine appears to be down or failing to respond to the search query.

The search engine service is running, but the message indicates otherwise.

**Comment by robotdan** [comment]
If the search engine is indeed running, and the FusionAuth configuration has the correct URL and port, the default is `http://localhost:9021` - then it is likely a Windows Firewall configuration issue. 

Ensure that the java process running FusionAuth App is allowed to access the network. 

1. Allow java.exe through the Windows Firewall
 - `Control Panel > System and Security > Windows Firewall > Allow an app or feature through Windows Firewall`
2. Select `Allow another app...`
3. Navigate to the location where you installed FusionAuth App.
 - For example `C:\users\administrator\fusionauth\java\jre1.8.0_171\bin\java.exe`
4. Allow this process `private` network access to allow it to communicate with the Elasticsearch process

> ![windows_firewall_config](https://user-images.githubusercontent.com/1148709/48870477-413e0780-ed9e-11e8-9ea6-c72a8a12fe38.png)


As an alternative troubleshooting technique, you may also enable Windows Firewall notifications and then restart both processes to ensure your firewall is configured for FusionAuth. 

To enable Windows Firewall notifications

1. Navigate to the Firewall settings
- `Control Panel > System and Security > Windows Firewall > Change notification settings`
2. There you'll see an option `Notify me when Windows Firewall blocks a new app`
- Enable this option for `private` network 
3. Restart the FusionAuth services and see if you are notified


Once you have allow the FusionAuth java process access, you may disable the notification settings if you'd like.

**Comment by robotdan** [comment]
Pending update to Windows installation doc, perhaps the troubleshooting section, and we could optionally add a warning to the `install.ps` install script to let the user know they need to allow the java process on the private network. We will know the install path so we could output the entire path to the `java.exe` on the command output.

**Comment by tyduptyler13** [comment]
We may want to see if we can pop up a dialog to allow java on private networks. I assume there is a way to do this in powershell.
