### ISSUE TITLE
Webhook not getting triggered.

### ISSUE THREAD

**Issue by Raghavsalotra** [FusionAuth/fusionauth-issues#403]
### Description 
I am using v1.9.0 and wanted to use webhook as an when user is updated. I did configure as it is described in the documentation but it does not seem to be working.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Ubuntu
 - Browser + version chrome

**Comment by robotdan** [comment]
Can you show your configuration for the webhook, and the tenant events TX levels?

**Comment by robotdan** [comment]
Closing this out, if you're still having issues let us know.
