### ISSUE TITLE
Scaling fusionauth pods causing login failures

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#405]
### Description 
When FusionAuth pods are scaled to more than 1 replica then Admins are unable to login. I don't see any logs related to this issue.

### Steps to reproduce
If FusionAuth is hosted in Kubernetes then just scale the replicaset to more than 1 and try to login to admin UI.

### Expected behavior
All users should be able to login just how they used to login when there was single pod.

### Screenshots
![image](https://user-images.githubusercontent.com/1984707/70866500-6f225b00-1f62-11ea-9512-7c52b7d77367.png)

### Platform
 - Device: Desktop
 -  Hosting : AKS, 2 replicas
 - FusionAuth :  1.12.0

**Comment by robotdan** [comment]
You'll need to session pin with more than one node.

https://fusionauth.io/docs/v1/tech/installation-guide/server-layout
