### ISSUE TITLE
User is not returned after creation when using queryString

### ISSUE THREAD

**Issue by uncledent** [FusionAuth/fusionauth-issues#407]
### Description 
After creating a user via api, i am trying to retrieve all users for the tenant:

```    const res = await this.client.searchUsersByQueryString({
      search: {
        queryString: `tenantId:${tenantId}`,
        numberOfResults: limit,
        startRow,
        sortFields: [
          {
            name: 'fullName',
            order: Sort.asc,
          },
        ],
      },
    });
```
It does not return the new user right after creation, user appears only after some time, usually less then a second. But this is a problem, because the application needs this uses with the users call right after creation.

### Steps to reproduce
1. Create a user via rest call (register)
2. Get users list with the query for a tenant

### Expected behavior
Expected: new user there, but no new user there

### Additional context
Fusion auth 1.10.0

**Comment by robotdan** [comment]
The is working as designed. Your making a query against the elasticsearch index, the insert into the index is async.

If you find you need to retrieve a user from the search index immediately following an insert you can flush the index after each insert. This isn't recommended for performance reasons.

https://fusionauth.io/docs/v1/tech/apis/users#flush-the-search-engine

**Comment by uncledent** [comment]
@robotdan thanks for the quick reply. So there is no way to get users list of a tenant another way?

**Comment by robotdan** [comment]
@uncledent Your methodology is correct, but the design of the search engine is async, so the state of the search index is not immediately in sync with the database.  

If you need to retrieve a list of users in a tenant synchronously after a create user request, you'll either need to add a wait, or flush the search engine before you make the search request. 

What you're describing is usually a development time issue, do you have a use case like this in production as well?

**Comment by uncledent** [comment]
@robotdan It is a productive flow as well. We have multiple organizations, that can only see this organization users. After a user creation you are being redirected to the user list, which loads the users automatically. So we need somehow to be able to show newly created users. Waiting for search engine to update would be ok, the problem is that we have no information how long to wait, so i need some way to determine that the index was updated.

**Comment by robotdan** [comment]
Ok, got it. 

I think the default `refresh_interval` is `1s` according to the Elasticsearch documentation. 
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/tune-for-indexing-speed.html

You could tune this to be lower, but that will impact the performance of Elasticsearch I'm sure. 

You could also add a note to the user in the UI that newly created users may not immediately be viewable , perform an AJAX refresh, or just wait a second or two after creation to reload the list of users. 

Hope that helps. 




I would recommend you add a note to the user in the UI that newly created users may not immediately be viewable , perform an AJAX refresh, or just wait a second or two after creation to reload the list of users.

**Comment by uncledent** [comment]
@robotdan  thank you for help, i think i will wait a second before update
