### ISSUE TITLE
Add the JTI claim

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#409]
### Problem
The optional JTI claim is not provided. 

### Solution
Add the JTI claim. 

### Alternatives/workarounds
Use a lambda. 

### Additional context
https://tools.ietf.org/html/rfc7519#section-4.1.7

https://stackoverflow.com/questions/9407892/how-to-generate-random-sha1-hash-to-use-as-id-in-node-js/14869745#14869745

https://bitbucket.org/atlassianlabs/jwt-authentication/pull-requests/7/feat-add-required-jti-claim-when/diff

https://github.com/bshaffer/oauth2-server-php/issues/265#issuecomment-30558014

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mv4208** [comment]
@robotdan - we want this feature as part of our internal security process to blacklist tokens when warranted
