### ISSUE TITLE
Grant Prompt Screen in OAuth Login Workflow

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#411]
### Problem
I want to provide a prompt to the user to indicate what permissions my application is requesting based upon the scopes on the request. 

### Solution
Provide some configuration to allow a scope / prompt configuration and definition. 

### Alternatives/workarounds
N/A

### Additional context
N/A

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/275
- https://github.com/FusionAuth/fusionauth-issues/issues/308
- https://github.com/FusionAuth/fusionauth-issues/issues/1475
- https://github.com/FusionAuth/fusionauth-issues/issues/1582

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by SeanStayn** [comment]
**It's a very important feature for us.** 

We have several websites that integrate OIDC through FusionAuth. However, each website requires different information from the user. 

It would be great if the grant prompt screen had mandatory fields like email and username, but also optional fields like favorite color or birthday. 

We will use information from FusionAuth (email / username / ..), as well as information from a custom API (favorite color / ..).

For this reason, it would be ideal if the grant prompt screen would allow us to request custom information such as favorite color, even though the information itself is not stored in FusionAuth.

If it is possible to implement the requirements, it would be helpful if the information released by the user could be stored as a Boolean in the UserInfo endpoint.

For example:
`grants: 
{
   "favorite color" : true
}`

Many regards & thanks for the nice product!
Sean

**Comment by robotdan** [comment]
Thanks for the feedback @SeanStayn!

I can't provide any timeline for you on community requested items, but the up-votes do helps us prioritize our resources. 

If you have a more immediate business requirement for this feature we can deliver this through professional services or a paid contract of some sort. If that is of interest, contact us on the main website and we can provide you with a proposal. 

Thanks for using FusionAuth!

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/400

**Comment by andrewpai** [comment]
Shipping in 1.50.0.
