### ISSUE TITLE
Possibility of knowing multiple concurrent logins of same user

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#419]
### Description
if a user is logged into an app in laptop/pc/mobile then he shouldn't be able to login to other devices with same account.

Does FusionAuth keeps track of user session (login and logout)? Is it possible to identify if a user's session is active? 

Not sure if we can rely on `lastLoginInstant` property to identify if the user session is recently established.

**Comment by robotdan** [comment]
This is not possible in FusionAuth, if you want to limit logins per device you would need to enforce this on your end. 

If you have a Refresh Token per device, you could enforce this by removing the login option if the user already has a Refresh Token for a particular application, or upon a successful login remove other Refresh Tokens which would kick them out of the other devices. 

Or you could track this on your end however you'd like to limit device logins.
