### ISSUE TITLE
Trouble completing login via external IDP (ADFS)

### ISSUE THREAD

**Issue by prasanna10021991** [FusionAuth/fusionauth-issues#422]
Description
FusionAuth is not able to reconcile with the response from the ADFS IdP.

Steps to reproduce
We have added a test ADFS as an external IdP. These appear on our FusionLogin screen and clicking it takes the user to the IdP. It authenticates and redirects back to FusionAuth with token. But the response is not reconciled in FA login, instead throws an error. We've followed the documentation for ADFS setup and configuring FusionAuth but not able to successfully complete login on this instance. We'll be able to provide access to the test ADFS environment that is setup if that would help debug the issue.
These errors are very much the same as it's mentioned in this issue [here](https://github.com/FusionAuth/fusionauth-issues/issues/181). Though our version of FA is updated and should contain the fix applied for this bug.

We get these errors:
In UI with SAML - FusionAuth encountered an unexpected error. Please contact support for assistance.
:
<img width="466" alt="Screenshot 2019-12-20 at 2 51 54 PM" src="https://user-images.githubusercontent.com/39335934/71799510-8644fc00-307b-11ea-830c-9731875737d2.png">

Error Logs:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/39335934/71799550-9d83e980-307b-11ea-8f0d-eb57eacac6a8.png)

Platform
FusionAuth version: 1.10

**Comment by prasanna10021991** [comment]
@robotdan ..as suggested opened an issue on this !

**Comment by robotdan** [comment]
That exception looks like something we fixed in 1.11.0.  Can you try upgrading and see if you can still recreate?

**Comment by prasanna10021991** [comment]
@robotdan ...thank you, updating the FA did solve the error.  Another error ensued though, after authentication, no matter which application I try to hit and login, a extra "2" gets appended to client id somehow and throws the following error post login on ADFS (after returning to ACS url):

Error JSON
{
  "error" : "invalid_client",
  "error_description" : "client_id: 2b4d833b-8819-463c-b543-cac17a7909112 is not valid.",
  "error_reason" : "invalid_client_id"
}

Actual Client ID here is just "2b4d833b-8819-463c-b543-cac17a790911", 
This happens even if I try with a different client/application too.

<img width="435" alt="Screenshot 2020-01-07 at 3 02 21 PM" src="https://user-images.githubusercontent.com/39335934/71884655-bca77780-315e-11ea-91fd-d1796b8d7e9d.png">

Actual Application IDs:

<img width="671" alt="Screenshot 2020-01-07 at 2 30 55 PM" src="https://user-images.githubusercontent.com/39335934/71884540-8ec23300-315e-11ea-9578-123d2042a9e5.png">

We've checked all the configurations made, we haven't been able to figure out where this extra "2" gets appended from as we don't configure particular client-IDs in the ADFS IdP setup. Would you please help us debug this, should I raise a new issue for this one.

**Comment by robotdan** [comment]
Closing as fixed, please re-open if you still encounter this error.
