### ISSUE TITLE
JavaScript method definitions are not supported in IE11

### ISSUE THREAD

**Issue by downagain** [FusionAuth/fusionauth-issues#423]
JavaScript [method definitions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) defined as:

`const obj = {
  foo() {
    /* code */
  },
  bar() {
    /* code */
  }
}
`

inside an object, are only valid in ES2015 and do not work in IE11.
To be IE11 compatible, I believe these should be defined as follows:

`const obj = {
  foo: function() {
    /* code */
  },
  bar: function() {
    /* code */
  }
}`

This causes an issue when trying to log in using SAML. The SAML button doesn't work.
In the console you see the message: 
`SCRIPT1003: Expected ‘:’ error` in file helper.js (js/identityProvider/helper.js)

I manually changed the helper.js file on my server as a workaround as follows:

`captureState(additionalFields) {`
to
`captureState: function(additionalFields) {`

Can this be fixed? Or is IE11 not supported?

I also saw the same issue in js/ui/AutoComplete.js (and possible also others), but this does not affect endusers, and FusionAuth admins can use chrome/firefox.

**Comment by robotdan** [comment]
@downagain I don't think we are using the `const` modifier in any of our JavaScript. We should be shipping IE11 friendly JavaScript for the most part. 

What version of FusionAuth are you running? Can you provide the JavaScript console output?

**Comment by downagain** [comment]
I'm currently running version 1.13.2

In the JavaScript console in IE I get:
`SCRIPT1003: Expected ':'
Helper.js (10,15)`

**Comment by robotdan** [comment]
Thanks @downagain! I see the issue. We'll correct this in the upcoming release. Also found the issue with `AutoComplete.js`.
