### ISSUE TITLE
HTTP PATCH doesn't merge all fields

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#424]
### Description 
When we added support for the HTTP `PUT` method to allow the API to merge in changes we made a decision to not fully merge a few fields because it would be difficult for users to remove values. 

This decision may not have been the best option, and we should revisit this to see if we should support a full merge on all fields. 

Fields affected
- User.preferredLanguages
- User.memberships
- User.registrations
- User.data
- UserRegistration.data
- UserRegistration.preferredLanguages
- UserRegistration.roles
- Application.data

### Steps to reproduce

Attempt to merge custom data on the User object.

For example: (user object is not complete, only a boiler plate is represented)

Existing User:
```
{
  "user": {
     "data": {
         "foo": "bar"
     }
   }
}
```

Merge request using `PATCH`

```
{
  "user": {
     "data": {
         "baz": "bar"
     }
   }
}
```

User expected result:

```
{
  "user": {
     "data": {
         "baz": "bar",
         "foo": "bar"
     }
   }
}
```

Actual result:

```
{
  "user": {
     "data": {
         "baz": "bar"
     }
   }
}
```

### Expected behavior
See above.

### Screenshots
N/A

### Additional context
N/A

**Comment by ericsopa** [comment]
@robotdan Thank you for adding this issue! I definitely want PATCH to merge User.data. But probably want merge for all the others as well. PUT should always overwrite the resource, in this case, the JSON object "data". For the key-value deletion use case, perhaps you can use the DELETE method? If you add DELETE on a per key-value pair basis, we can selectively delete a single KV pair or if we specify all the KV pairs and the resulting object is empty, you can just delete it?

**Comment by robotdan** [comment]
Some limitations still are present with doing full merges on these properties. See https://github.com/FusionAuth/fusionauth-issues/issues/441 for more info.
