### ISSUE TITLE
OAuth app options to allow any redirect URI

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#425]
### Problem

As a developer, I have multiple application using oauth and having address like `http://localhost:12345` (the port is randomly added by Docker).

Because of the dynamic port attribution, I regularly have to add new redirect URI to the authorization list of my FusionAuth app.

### Solution

Have a "dev mode" options to allow any given redirect URI. Or even simpler: Do not complain about the URI if it contains `localhost` or a private IP.

### Alternatives/workarounds

None AFAIK.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/437

**Comment by robotdan** [comment]
@soullivaneuh would a regex pattern work for your scenario or would you need a "dev" mode to essentially allow you to turn off this validation during development? 

Here is our open feature for a regex pattern based redirect configuratio. 
https://github.com/FusionAuth/fusionauth-issues/issues/437

**Comment by soullivaneuh** [comment]
Yes, I think this should fit my need.

**Comment by mooreds** [comment]
@soullivaneuh make sure you vote on issue #437 if you feel it'd be helpful. Thumbsup votes are how we incorporate community feedback for future roadmap discussions.

**Comment by robotdan** [comment]
Closing as handled via https://github.com/FusionAuth/fusionauth-issues/issues/437
