### ISSUE TITLE
Allow to manage theme with files directly

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#430]
### Problem

In order to increase FustionAuth deploy automation with CI, I would like to automatically setup/update some part like the theme.

Unfortunately, the theme templates seems to be managed by the interface or the API only. The usage of the API is currently not possible on deploy because FA is on "install wizard mode" at the first time. Plus, this is not an ideal solution for developer.

### Solution

Add the possibility to put our theme template on a dedicated folder with a way to select it on the admin later.

Or even simpler, allow to override the default theme by adding/replacing the files.

### Alternatives/workarounds

If you have only one theme to manage, direct file override on setup seems to work.

Here is an example with a `Dockerfile`:

```Dockerfile
FROM fusionauth/fusionauth-app:1.13.2
COPY templates /usr/local/fusionauth/fusionauth-app/web/WEB-INF/templates
```

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This may be covered by this feature. 
https://github.com/FusionAuth/fusionauth-issues/issues/170

**Comment by soullivaneuh** [comment]
Thanks, it may be covered indeed. That's fun, I was willing to open an issue similar to #170. :-)

**Comment by robotdan** [comment]
Great, once an early version of that feature is available I'll post on that issue if you want to try it out.

**Comment by soullivaneuh** [comment]
@robotdan So I tried your Kickstart solution, but it does not fit all of my needs.

I opened a more general issue here: https://github.com/FusionAuth/fusionauth-issues/issues/1379

**Comment by robotdan** [comment]
I think we can close this one out as it is covered by #1379?

**Comment by soullivaneuh** [comment]
Indeed.
