### ISSUE TITLE
post_logout_redirect_uri is invalid.

### ISSUE THREAD

**Issue by jerryhopper** [FusionAuth/fusionauth-issues#433]
### Description 
If a client uses post_logout_redirect_uri instead of logout_redirect_uri, fusioauth gives an error.

### Steps to reproduce
1. A client creates a logout url like  this :  'https://fusionauth/oauth2/logout?id_token_hint=TOKENHINT&post_logout_redirect_uri=https%3A%2F%2Fwww.wordpress.ext%2Fwp-login.php%3Floggedout%3Dtrue%26wp_lang%3Den_US'
2. Fusionauth Error occurs :  The post_logout_redirect_uri is invalid. (invalid_post_logout_redirect_uri)

### Expected behavior
A redirect to the post_logout_redirect_uri should occur.

### Additional context
i cant find a field inside fusionauth where i should enter the post_redirect_uri to correct this problem ( if any is required ).

**Comment by robotdan** [comment]
The logout URI does need to be configured prior in the OAuth config as an authorized redirect.

https://fusionauth.io/docs/v1/tech/oauth/endpoints#logout

**Comment by jerryhopper** [comment]
Ah, this confused me.   I was using the "Logout Url" field for this.

Instead, i should use the "Authorized redirect URLs"  for the application.

**Comment by jerryhopper** [comment]
**There is still an issue.**

the post_logout_redirect_uri contains parameters that can change.

The generated redirect uri contains dynamic values which i can set in the admin backend for each language (but its not very flexible)

https://www.wordpress.ext/wp-login.php?loggedout=true&wp_lang=nl_NL

As you see, the wp_lang variable is dynamic, which raises the invalid_post_logout_redirect_uri error.

**Comment by robotdan** [comment]
The specification isn't completely concrete on this topic, but in general it implies the URI needs to be registered ahead of time and then validated. 

> post_logout_redirect_uri
>
>OPTIONAL. URL to which the RP is requesting that the End-User's User Agent be redirected after a logout has been performed. The value MUST have been previously registered with the OP, either using the post_logout_redirect_uris Registration parameter or via another mechanism. If supplied, the OP SHOULD honor this request following the logout.

In any case, the behavior you're seeing is working as designed. 

I've opened feature request to discuss the possibility of adding some flexibility into the redirect URI configuration. 

https://github.com/FusionAuth/fusionauth-issues/issues/437

Add some comments on that ticket if you like! Thanks.
