### ISSUE TITLE
URLs with a slash produce strange errors

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#434]
### Description 
When calling URLs in FusionAuth such as `/api/login/` the error message is cryptic and doesn't tell the caller how to fix it. This specific URL produces this error message:

```
{
    "fieldErrors": {
        "userId": [
            {
                "code": "[couldNotConvert]userId",
                "message": "Invalid userId on the URL [index]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."
            }
        ]
    }
} 
```

My guess is that this is an issue in Prime MVC with the ActionMapper code. We add `index` in some cases to resolve actions for `/` but we also handle URL parameters (as segments) so this logic is likely getting confused.

### Steps to reproduce
1. Call the Login API normally, but add a slash to the URL with a `POST`

**Comment by robotdan** [comment]
What would you expect the behavior to be? I would assume we should just fail as if the URL is not mapped by prime?

**Comment by voidmain** [comment]
That's what I was thinking. The `index` is only used to resolve the action and shouldn't be used for resolving URL parameters. If we manage it like that somehow, then what will happen is we will find `/api/login/` and use these steps:

1. Look for `api.login.IndexAction`(fail)
2. Look for `api.LoginAction` (success)
3. Pull additional segments from `/api/login/` (null)
4. Set URL parameters (null)

This will make it work actually since `userId` would just be null. 

Then we have to ensure these cases still work as expected:

**Index action with parameter**
```
@Action("{foo}")
public class IndexAction {
  public String foo;
}
```

**Index action without parameter**
```
@Action
public class IndexAction {
  public String foo;
}
```


**Login action with parameter**
```
@Action("{foo}")
public class LoginAction {
  public String foo;
}
```

**Login action without parameter**
```
@Action
public class LoginAction {
  public String foo;
}
```

This handling should make the error messages more correct since empty String will become `null` and then result in no error for the `POST` and the correct error for `PUT` on `[missing]userId`.

**Comment by robotdan** [comment]
Fixed in prime-mvc.
