### ISSUE TITLE
Server Layout Question

### ISSUE THREAD

**Issue by gorwell4891** [FusionAuth/fusionauth-issues#435]
### Description

In the following diagram, it is suggested that FusionAuth Search and FusionAuth App can be put on separate servers. What does FusionAuth Search and FusionAuth App actually do?

![Horizontally Scaled](https://fusionauth.io/assets/img/docs/n-servers-external-db.png "Horizontally Scaled")

https://fusionauth.io/docs/v1/tech/installation-guide/server-layout

For FusionAuth Search: 

> The 9020 port is utilized by Elasticsearch for internal communication including clustering. The 9021 port is the HTTP port utilized by FusionAuth App to make requests to the search index.

For FusionAuth App:

> To access the FusionAuth UI you’ll need to open port 9011. If you have more than one instance of FusionAuth installed you will need to ensure that each instance of FusionAuth Backend can communicate on port 9011.

If I want to scale up FusionAuth API services, such as requesting JWT tokens, do I add more FusionAuth Search servers? 

If I don't need web UI login for users/administrators, I can have fewer FusionAuth Apps?

I'm trying to understand or find more details about what the `Search` and `App` do.

**Comment by robotdan** [comment]
This page may help. https://fusionauth.io/docs/v1/tech/installation-guide/packages

Generally speaking you don't need to scale the app and search services at the same rate, it depends. If you don't have millions of users, and are primarily just scaling login (password hashing) and jwt signing and verification which means you just need more CPU, then scaling just the app service is fine.

**Comment by gorwell4891** [comment]
I see. Thank you for the insight. That helps.

Very much appreciated.
