### ISSUE TITLE
Unable to add webhook events using fusionauth-netcore-client

### ISSUE THREAD

**Issue by GraafG** [FusionAuth/fusionauth-issues#438]
### Description 
Using the fusionauth-netcore-client it is not possible to successfully add a webhook with events.

### Steps to reproduce
Steps to reproduce the behavior using fusionauth-netcore-client:
1. Make a new webhook via the API and enable some events.
2. Read the webhook via the API or web interface.

### Expected behavior
Events added to the newly created webhook.

### Screenshots
[Screenshot locals vs2019](https://imgur.com/a/oFecaK4)

### Platform
fusionauth-netcore-client
version: 1.13.2

### Additional context
Using postman I have no problem adding the events.
[Screenshot postman](https://imgur.com/a/QuAezC5)

**Comment by robotdan** [comment]
Are you getting a `400` status code back with A JSON response?

**Comment by GraafG** [comment]
> Are you getting a `400` status code back with A JSON response?

No it's a 200 OK status code.

**Comment by GraafG** [comment]
@robotdan did you find the cause for this behavior?

**Comment by robotdan** [comment]
@GraafG I have not. 

It is strange that you're getting a `200` back if it is not working. 

Can you post the equivalent JSON request body - and if that works via Postman, Insomnia or other RESET client, also post your code that you're sending to create the webhook. 

Perhaps there is an issue with the way this client is serializing the request.

**Comment by GraafG** [comment]
I can add an event via postman but I can't using .net core package.

The code:
`            const string defaultWebhookUrl = "http://redacted";
            var webhookRequest = new WebhookRequest
            {
                webhook = new Webhook
                {
                    url = _fusionAuthOptions.Value.WebhookUrl ?? defaultWebhookUrl,
                    description = "Fenix webhook (automatically created)",
                    data = new WebhookData
                    {
                        eventsEnabled = new Dictionary<EventType, bool>
                        {
                            { EventType.UserCreate, true }
                        }
                    },
                    applicationIds = new List<Guid>
                    {
                        _fusionAuthOptions.Value.ApplicationId
                    },
                    connectTimeout = 1000,
                    readTimeout = 2000
                }
            };`

**Comment by rdvanbuuren** [comment]
Should be fixed by the following pull request:
https://github.com/FusionAuth/fusionauth-netcore-client/pull/8

**Comment by robotdan** [comment]
Accepted FusionAuth/fusionauth-netcore-client#8 - the root issue is the domain builder for this library, it will be fixed in the upcoming feature release, likely 1.5.0.
