### ISSUE TITLE
Better support for JSON Patch via RFC 6902 or RFC 7396

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#441]
### Description
FusionAuth supports the HTTP `PATCH` method but this has some limitations. Merging, replacing or moving values is difficult.

#### Array Merges

Initial State
```
{
  "data': {
     "foo": [ "bar "] 
  }
}
```

PATCH Request
```
{
  "data': {
     "foo": [ "bar ", "baz" ] 
  }
}
```

Result
```
{
  "data': {
     "foo": [ "bar ", "bar", "baz" ] 
  }
}
```

This result may be what you want, or it may not be, the incoming request does not tell us enough to identify if the values should be replaced or appended. Because the data structure represented here is assumed to be an Array, duplicates are allowed and the incoming values are appended. This means that you cannot remove values without multiple API calls. You could use a `GET` and `PUT` or make two `PATCH` calls to clear using `null` and then set again. 

### Solution

The JSON Patch RFC attempts to solve this problem by providing syntax for the intended operations. Ideally we'd find a library that implements RFC 6902 with Jackson and can be added transparently to our existing serialization / de-serialization strategy. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/441  (this)
- https://github.com/FusionAuth/fusionauth-issues/issues/534
- https://github.com/FusionAuth/fusionauth-issues/issues/667
- https://github.com/FusionAuth/fusionauth-issues/issues/706
- https://github.com/FusionAuth/fusionauth-issues/issues/956
- https://github.com/FusionAuth/fusionauth-issues/issues/982
- https://fusionauth.io/community/forum/topic/939/lambda-reconcile-does-not-remove-role-from-registration/8

### Additional Context

http://jsonpatch.com/
https://tools.ietf.org/html/rfc6902

*Java libs that implement RFC 6902*
https://github.com/ebay/bsonpatch
https://github.com/java-json-tools/json-patch

Per comment https://github.com/FusionAuth/fusionauth-issues/issues/441#issuecomment-639092237, RFC 7396 maybe adequate. https://tools.ietf.org/html/rfc7396
- Jackson plugin supporting RFC 7396 https://github.com/jeffnelson/jackson-merge-patch

**Comment by matthew-altman** [comment]
May be able to implement merge-patch in Prime https://tools.ietf.org/html/rfc7396
Or can just use existing Jackson behavior to make the deep merge and array replacement work as expected.

**Comment by rdvanbuuren** [comment]
Is there any description available on how to use these PATCH function(s)?

Not sure if I should add this issue here, but when calling a method like PatchApplication from the Netcore client, the JSON isn't wrapped correctly with `application { }`. 
According to the API (https://fusionauth.io/docs/v1/tech/apis/applications#update-an-application), it should be the same like the PUT request:
> When using the PATCH method, use the same request body documentation that is provided for the PUT request.

The client code only passes the keys/values, but doesn't wrap it in the correct request body:
```csharp
public ClientResponse<ApplicationResponse> PatchApplication(Guid? applicationId, Dictionary<string, object> request) {
      return buildClient()
          .withUri("/api/application")
          .withUriSegment(applicationId)
          .withJSONBody(request)
          .withMethod("Patch")
          .go<ApplicationResponse>();
    }
```

**Comment by robotdan** [comment]
The JSON does need to look just like the normal PUT or POST requests, so your properties need to be in the "application" object. 

Will this work for you? 

```
var request = new Dictionary<string, object> {
  { 
   "application": { 
       "passwordlessConfiguration": { "enabled":  false },
       "registrationConfiguration": { "enabled":  true }
   }
};
client.PatchApplication(applicationId, request);
```

**Comment by trevorr** [comment]
FWIW, I think something as simple as RFC 7396 Merge Patch is adequate most of the time and causes the least surprise (e.g. overwriting as opposed to appending to arrays). RFC 6902 JSON Patch is nice to have, but I've rarely seen it used in practice.

**Comment by robotdan** [comment]
Thanks for that feedback @trevorr that is helpful.

**Comment by robotdan** [comment]
I stubbed out a test to prove the algorithm in RFC 7396 using the pseudocode provided. This seems to pass for the test cases they provide. 

This is just a test, but if it works, we should be able to use this in the `JacksonContentHandler` to handle a `Content-Type` of `application/merge-patch+json`.  https://github.com/prime-framework/prime-mvc/commit/94f562331bf92662431f06e7d78784f238f98b19

**Comment by darwinshameran** [comment]
Would love to see support for JSON PATCH in FA!

**Comment by mooreds** [comment]
@darwinshameran please vote the issue up (with a 'thumbs up'), as that is how we determine community support.

More here: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap/

**Comment by robotdan** [comment]
Planning to support both RFC 6902 or RFC 7396 and still preserve backwards compatibility. 

Setting `Content-Type` will yield:
- `application/json` - current behavior which works but is kinda busted for arrays.
- `application/json-patch+json` - use JSON Patch syntax per RFC 6902
- `application/merge-patch+json` - use JSON Patch syntax per RFC 7396

**Comment by robotdan** [comment]
Internal:

- Can we still use `@JsonMerge(OptBoolean.FALSE)` on arrays. 
- Should we switch our client libraries to use `application/merge-patch+json`
