### ISSUE TITLE
ES runs in privileged mode

### ISSUE THREAD

**Issue by PGQW** [FusionAuth/fusionauth-issues#444]
### Description
The ElasticSearch container for FusionAuth-Search currently is set to run in Privileged mode.  Is this necessary, and if not... What changes need to be made to the DockerFile/Deployment to remove it?

**Comment by robotdan** [comment]
Can you provide any additional context to the question? 

Are you using our FusionAuth Search Docker image or a vanilla Elastic image? And by privileged do you mean it is running under a root user?

**Comment by tyduptyler13** [comment]
The kubernetes configuration uses privileged mode for search.

https://github.com/FusionAuth/fusionauth-containers/blob/master/kubernetes/deployments/search-deployment.yaml#L29

**Comment by robotdan** [comment]
Thanks @tyduptyler13 - got it. 

That was a contributed example for K8s, and in order for Elasticsearch to run in "production mode" it has to have a the ulimit set to a number higher than the default on most Linux images. 

https://www.elastic.co/guide/en/elasticsearch/reference/6.3/setting-system-settings.html

I believe this is necessary to configure the host to run Elasticsearch. As far as I know (I am not a k8s expert) - this privileged mode is only for the command in the specified in that block. 

This seems to be the prescribed way to get this to run, here are some similar examples. 

https://portworx.com/run-ha-elasticsearch-elk-ibm-cloud-kubernetes-service/
https://github.com/pires/kubernetes-elasticsearch-cluster/issues/85

The actual "container" for elastic search does not have the privileged configuration set.

```yaml
containers:
        - name: cluster.name
          value: fusionauth
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
        name: search
```

**Comment by michael-burt** [comment]
Just to add some color here, a lot of on-prem clients have hard rules about not letting any containers, init or otherwise, run in privileged mode. This presents a challenge to using FusionAuth for on-prem deployments in these secure environments.

**Comment by robotdan** [comment]
@michael-burt good feedback. Connecting to an existing managed Elastic service may be an option in this case. 

Or perhaps there are hosts pre-configured to run an Elastic containers so the container definition does not need to run these privileges commands at startup. 

We also have an open feature request to remove the requirement for Elasticsearch in exchange for a reduced search capability. This may be a good solution for smaller deployments with restrictions on these types of privileged init requirements. 

See https://github.com/FusionAuth/fusionauth-issues/issues/427 for additional information. 

Thanks for using FusionAuth!
