### ISSUE TITLE
Identity provider OpenID invalid client_id from Microsoft ADFS 

### ISSUE THREAD

**Issue by ovrdoz** [FusionAuth/fusionauth-issues#445]
### Description
I'm configuration OpenId to add Identity provider and I try to connect LDAP athwart Microsoft AD FS, but every time before authenticated in AD FS portal, retrieves the message:
```
{
  "error" : "invalid_client",
  "error_description" : "client_id: 3c219e58-ed0e-4b18-ad48-f4f92793ae32,IRkY6ekOxO9-252rS8wz19f4bM7Rc-ddhG81V4ou2g0 is not valid.",
  "error_reason" : "invalid_client_id"
}
```
In this case in logs of fusionauth not show's the root cause or some idea about it. I am think that Information error is obvious, but the data is checked.

I'm suspect of incompatibility with Microsoft ADFS, because I' read about the problems with azure and other problems same #338, #335

### Platform
FusionAuth 1.14.1 Docker, Chrome

**Comment by voidmain** [comment]
Your `client_id` looks like it has two values in it separated with a comma. The correct value should be `3c219e58-ed0e-4b18-ad48-f4f92793ae32` but your value is `3c219e58-ed0e-4b18-ad48-f4f92793ae32,IRkY6ekOxO9-252rS8wz19f4bM7Rc-ddhG81V4ou2g0`.

Are you certain that ADFS is configured properly?

**Comment by ovrdoz** [comment]
Hello, I came back on this topic, today I performed new tests and adjustment of settings of ADFS.

I added the domain of my users in the option "Managed domains" and it seems to have improved the scenario, but I was not able to complete the flow that I will give more details.

This was the adjustment in my manager domains:

<img width="1022" alt="Screen Shot 2020-01-31 at 14 08 52" src="https://user-images.githubusercontent.com/3878754/73559135-416e7400-4433-11ea-8050-1ea0aaf5e227.png">

However, after logging into the ADFS portal I captured this message in the Event Logs of fusion:

```
Request to the [https://adfs.local.domain.com/adfs/oauth2/token/] endpoint failed.Status code [400]

Error response is 
{
  "error" : "invalid_request",
  "error_description" : "MSIS9631: Received invalid OAuth request. Multiple client authentication methods were attempted."
}
```
When I research "MSIS9631" I see many Issues about the client's bug for communication exclusive AD FS.

But I think is one problem of configuration, so I don't know what's happening...

**Comment by robotdan** [comment]
This is happening because we are sending the `client_secret` in the request body and as part of a Basic Authorization header. 

We did this to support a few IdPs such as Discord that only accept the `client_secret` in the request body, even though the OAuth2 spec says that at a minimum you have to support HTTP Basic Authorization. 

To solve this and support other IdPs that require it to be one or the other, we'll have to expose some additional configuration to allow the IdP configuration to specify which mode to utilize, `client_secret_basic` or `client_secret_basic`.

**Comment by MaxDiOrio** [comment]
@ovrdoz What settings did you adjust in ADFS to get past the invalid client_id.  We're having the exact same issue.

**Comment by robotdan** [comment]
@MaxDiOrio in version 1.15.3 you can specify which mode to use for client authentication. If you haven't yet upgrade to 1.15.3 you should do that first and see if that resolves the issue.

If you're already on 1.15.3 and you're seeing this error or a similar error please open a separate issue . Thanks!

**Comment by ovrdoz** [comment]
@MaxDiOrio sorry for the long delay in responding, in fact, I had no control over the client_id to adjust, because on the ADFS side I had configured everything as recommended, I understand that it was something implicit in the response. As my client was in a hurry I changed the solution to Saml2 and it worked perfectly, but I haven't tested the solution for openid yet, but I intend to test it soon.

Following the @robotdan recommendation by upgrading the fusion version to1.15.3 and please post it to us if you are successful. Thanks
