### ISSUE TITLE
FusionAuth 1.14 migration not executed?

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#447]
### Description

According to [your release notes](https://fusionauth.io/docs/v1/tech/release-notes), v1.14 need a database migration.

According to [your guide](https://fusionauth.io/docs/v1/tech/installation-guide/upgrade#database), the database should be upgraded by the maintenance mode after user ask before use connection (Wordpress like I assume).

So I changed my Dockerfile to use `1.14.0` and up again my project. Two issues:

- Nothing special happen, no migration wizard on connection, but the app seems to works correctly.
- I created an account to fusionauth.io in order to get SQL migration file and take a look. But I can't find anything like that.

Is your database migration up to date? Maybe the migration is now done silently?

Regards

N.B. : Having the FusionAuth app directly on github (like the other sub-projects) would be a great addition to find and analyse file that may cause trouble and/or answer user questions.

**Comment by robotdan** [comment]
You can query the `version` table to see if the migration was applied. 

`SELECT * FROM version` - this should yield `1.14.0` if the migration ran successfully. 

If you have configured Silent Configuration mode ( https://fusionauth.io/docs/v1/tech/installation-guide/docker#silent-configuration ) then you will not be prompted for a schema update. In your startup logs you'll see something like 

```
Database Version [1.13.0]
Latest Migration Version [1.14.0]
```

**Comment by soullivaneuh** [comment]
Indeed:

```
fusionauth=# select * from version;
 version 
---------
 1.13.2
(1 row)
```

After docker update:

```
fusionauth=# select * from version;
 version 
---------
 1.14.0
(1 row)
```

The silent configuration do the stuff: 

```
Jan 30, 2020 9:28:19.522 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - Database Version [1.13.2]
Jan 30, 2020 9:28:19.523 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - Latest Migration Version [1.14.0]
```

Thanks!

You may add a note about it on this page: https://fusionauth.io/docs/v1/tech/installation-guide/upgrade#database

Because it's the first page you link from your release note.

Regards.
