### ISSUE TITLE
URL not accepted in Application "authorized redirect URL"

### ISSUE THREAD

**Issue by ictcorebiz** [FusionAuth/fusionauth-issues#452]
### Description 
When I create an application on a domainname _a.b.server.nl_, I can add that in my application definition under "Authorized request origin", but it is not allowed to fill the redirect URL with http://a.b.server.nl/login/generic_oauth.

### Steps to reproduce
1. Go to Application
2. Click on Edit Application
3. Scroll down to Authorized redirect URL
4. Add "http://a.b.server.nl/login/generic_oauth" to authorized request origin
5. press save

### Expected behavior
Expectation to save the url, and redirect the application logic during signin

**Comment by robotdan** [comment]
Are you seeing any logs? This seems to work ok for me, what version of FusionAuth are you running? 

![image](https://user-images.githubusercontent.com/1148709/73381707-70de7e80-4283-11ea-80f2-61010c12ccf2.png)

**Comment by ictcorebiz** [comment]
I'm running 1.13.2

**Comment by ictcorebiz** [comment]
Sorry, I simplified my example too much; please try:
http://dc2.console_new.server.nl/login/generic_oauth

**Comment by ictcorebiz** [comment]
I see my problem ...

an underscore is not an officially allowed character in a domain name, I should use a dash instead...

A dash is indeed accepted

You are doing it right, I'm doing it wrong :(
