### ISSUE TITLE
RedirectUri adds locale and userState with missing ?

### ISSUE THREAD

**Issue by mreschke** [FusionAuth/fusionauth-issues#453]
### Description
When FA redirects back to my app the url looks like this `https://example.com/login&locale=en_US&userState=Authenticated`.  Notice the missing ? before the query parameters.

### Additional context
When using basic `Implicit` grant, the redirect urls do NOT get added this `locale=en_US&userState=Authenticated` query params.  But I am switching to Code + PCKE so grants are now `Authorization Code` and `Refresh Token`.  Now my redirect url has these 2 new params, which I really need...but the url is missing the ? so my app sees this as an invalid url.

**Comment by robotdan** [comment]
Can you provide a list of steps to recreate? Which grant you're using, and all of the request parameters you're adding when you redirect to `/oauth2/authorize` ? 

Thanks!

**Comment by mreschke** [comment]
FusionAuth new Application
* Require auth: No
* Generate refresh tokens: Yes
* Authorized redirect URLs: https://example.com/login
* Authorized request origin URLs: blank
* Loguot URL: blank
* Logout behavior: All applications
* Enabled Grants:
 * Authorize Code
 * Refresh Token
* JWT enabled as all default (which makes its on JWT, all working on that front)
* No other tabs in app modified

I am using https://manfredsteyer.github.io/angular-oauth2-oidc/docs/index.html for my Angular application. 

For the last month I have been using Implicit flow.  So FA uses grant=Implicit and no `Generate refresh tokens`.  When using implicit, FA redirects back to my site WITHOUT any of those `locale=en_US&userState=Authenticated`, just plain old https://example.com/login.  Only when I switched the angular-oauth2-oidc plugin to Code + PKCE and setup FA as above did I notice `locale=en_US&userState=Authenticated` on the /login url now.

angular-oauth2-oidc takes care of all the OIDC stuff, so I am not handling manually.  Here is the `/oauth2/authorize` url from that plugin

```
https://auth.example.com/oauth2/authorize?response_type=code&client_id=0f1592c2-f1bb-4b1c-a279-8ed351311e03&state=CV24feu18XS5rlPIW2fH0scR8EwAG3JLJRt5OJilMFWxQ&redirect_uri=https%3A%2F%2Fadmin-local.sunfinity.com%2Flogin&scope=openid%20profile%20email%20offline_access&code_challenge=WIcbMXNdnz2Dsd4yWmgPGNqhatHPZ1COrLlQML-b1ro&code_challenge_method=S256&nonce=CV24feu18XS5rlPIW2fH0scR8EwAG3JLJRt5OJilMFWxQ
```

The angular config I have for the oidc looks like so
```
  // Angular OAuth2 OpenID Connect Plugin Configs
  oauth2: {
    // Url of FusionAuth Identity Provider
    issuer: 'https://auth.example.com',

    // URL of the Angular App to redirect the user to after login
    redirectUri: window.location.origin + '/login',

    // Angular App FusionAuth Application ID
    clientId: 'xyz',

    // Try Code Flow + PCKE
    responseType: 'code',

    // Oauth2 scopes (in relation to OpenID Connect login)
    scope: 'openid profile email offline_access',
  }
```

On login, redirected to that `/oauth2/authorize` url, I login, then it redirects back to `https://example.com/login&locale=en_US&userState=Authenticated` without a ?

I have tried adding a ? in my Authorized redirect URLs in FA and in the plugin redirectUri: window.location.origin + '/login?' config but it doesn't help, always no ? before params.

**Comment by trex** [comment]
@mreschke  I was able to recreate using your setup steps and the [manfredsteyer/angular-oauth2-oidc sample app](https://github.com/manfredsteyer/angular-oauth2-oidc).  

Inspecting the network calls from the browser, I was able to see FusionAuth redirect back to the app with a properly formatted query string and the expected query parameter `?code=`.  I put in some break points and see that the url is being rewritten by angular-oauth2-oidc in `oauth-service.tryLoginCodeFlow`.  This code is naively truncating some query string parameters and is not preserving the `?` on for the first parameter.  Here is the code block where this is occurring https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/projects/lib/src/oauth-service.ts#L1405-L1409

Please let me know if you need any other assistance on this issue.

**Comment by mreschke** [comment]
Thanks for digging into the issue.  I have opened a ticket with `angular-oauth2-oidc` about the issue here https://github.com/manfredsteyer/angular-oauth2-oidc/issues/725

**Comment by trex** [comment]
@mreschke you are welcome!  And thank you for opening up that related issue on the manfred/angular-oauth2-oidc project.  I am going to close out this issue.
