### ISSUE TITLE
Refresh token working after the expected expiration date

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#454]
### Description 
Using FusionAuth version `1.11.0` we've changed (for debugging purpose) an application's `jwt` expiration date to 30 seconds and the `refreshToken` expiration to 2 minutes. As expected, the `jwt` properly expires 30 seconds after it was created but the `refreshToken` still works after 3 minutes.

To note that the application in question originally had a much larger expiration time for both `jwt` and `refreshToken` and a few days ago we've decreased both, (for debugging purpose) and they both expired at the expected time. We've then updated back to the original expiration time and they worked as expected. But today we've changed both expiration times to the values mentioned above and it broke the `refreshToken` expiration time.

Also note that we've first changed the expiration times on the `application` level, and after noticing this weird behavior we've also changed the expiration times on the `tenant` level but the issue persisted. 

### Steps to reproduce
1. Use FusionAuth version `1.11.0`
2. Create a new `tenant`
3. Create a new `application`
4. Register a new `user`
5. Decrease `application` `jwt` and `refreshToken` expiration time
6. Increase `application` `jwt`  and `refreshToken` expiration time
7. Decrease `application` `jwt`  and `refreshToken` expiration time
8. Login `user`
9. Wait until the `refreshToken` supposedly expires
10. Ask for a new `jwt` using the expired `refreshToken`

### Expected behavior
The `refreshToken` should have expired on the expected time.

### Screenshots
<img width="1565" alt="screen_shot_2020-01-29_at_18 38 23" src="https://user-images.githubusercontent.com/6815911/73387469-8d50da00-42c8-11ea-989b-34a83b7b4542.png">

Also note that when we attempt to remove an `refreshToken` from FusionAuth web ui we've the following error message:

<img width="401" alt="screen_shot_2020-01-29_at_18 30 08" src="https://user-images.githubusercontent.com/6815911/73389015-36003900-42cb-11ea-87de-42dd737a5ffe.png">

### Platform
`FusionAuth` version `1.11.0` running on docker environment

### Additional context
This is happening in a environment where there's around 1.8k `tenants` and `applications`.

**Comment by robotdan** [comment]
If you use the Refresh Grant on the `/oauth2/token` endpoint the expiration should be correct, there looks to be a small window on the `/api/jwt/refresh` API where a refresh token is honored before it is reaped from the database. 

We'll correct this in the upcoming release. 

The error you see on the delete confirmation looks to be a tenant issue that we can also correct .
