### ISSUE TITLE
Where the default email templates are stored?

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#456]
### Description

In order to setup custom email templates on CI deploy, I want to fetch the default templates. The goal is to edit them to feet my needs.

I download this: https://storage.googleapis.com/inversoft_products_j098230498/products/fusionauth/1.14.0/fusionauth-app-1.14.0.zip

The zip contains all the website templates, but I can't find anything about the mails.

**Comment by robotdan** [comment]
We load them from the jar at runtime, probably easier to just write them from scratch, our default templates are fairly simple. Or you can copy them from a running system if you want to have a starting point.

**Comment by soullivaneuh** [comment]
> We load them from the jar at runtime

Can we consider later to have them on the zip file like it's done for web template? I don't really get why the mail template are here.

> Or you can copy them from a running system if you want to have a starting point.

I'm not sure of what are you talking about, could you please give me a sample?

Regards

**Comment by robotdan** [comment]
I have added the stock templates in the documentation for reference. Hope this helps!

Thanks. 
https://fusionauth.io/docs/v1/tech/email-templates/email-templates#templates-replacement-variables
