### ISSUE TITLE
Support key generation with id in Kickstart

### ISSUE THREAD

**Issue by mKaloer** [FusionAuth/fusionauth-issues#458]
### Problem
When using Kickstart to generate FusionAuth configurations, it is currently not possible to generate keys and refer to them later. This is however necessary to e.g. customize JWT signing in tenants.

The main issue is that the key generation API endpoint is a bit inconsistent from other APIs in that it is not possible to specify a UUID in `/api/generate`

### Solution
I see two solutions:
1) Allow to specify the key id in `/api/generate` (i.e. `/api/generate/{keyid}`)
2) Support "output variables" in Kickstart so it is possible to store the id of the created key in a variable

### Alternatives/workarounds
Using custom POST requests instead of Kickstart

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
It looks like this is just a bug in our doc, you can specify an Id on the `/api/key/generate` request. 

For example, this should work

```
    {
      "method": "POST",
      "url": "/api/key/generate/94577534-62bb-4277-b918-a0b518894734",
      "body": {
        "key": {
          "algorithm": "RS256",
          "name": "My RSA Key pair",
          "length": 2048
        }
      }
    }
```

And then you can use `94577534-62bb-4277-b918-a0b518894734` as the value for `accessTokenKeyId` or `idTokenKeyId`.

**Comment by mKaloer** [comment]
Oh, that’s awesome. Easy “fix” I guess :) Thanks for the the update.

**Comment by robotdan** [comment]
If that doesn't work for you, you can re-open the issue.
