### ISSUE TITLE
Allow to set defaultThemeId via kickstart.json

### ISSUE THREAD

**Issue by trollr** [FusionAuth/fusionauth-issues#459]
### Problem
Can't set sourceThemeId on a new theme if the default theme has a random uuid

### Solution
Add defaultThemeId like defaultTenantId

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
The default theme has a fixed Id of `75a068fd-e94b-451a-9aeb-3ddb9a3b5987`, so you can always use that if you'd like. 

You can also use the `sourceTenantId` when you create a new tenant which will cause a new tenant to have the same `themeId` as the default tenant, and then use a `PATCH` request to change any values you'd like on the new tenant. 

For example, this will create a new tenant as a copy of the default tenant

```
{
  "method": "POST",
  "url": "/api/tenant",
  "body": {
    "sourceTenantId": "#{FUSIONAUTH_TENANT_ID}",
    "tenant": {
      "name": "My Cool New Tenant"
    }
  }
}
```

Or create a new tenant with all the properties set you want and hard code the `themeId` to `75a068fd-e94b-451a-9aeb-3ddb9a3b5987`, this is just an example and would require more values to be set if you don't use the `sourceTenantId` field. 

```
{
  "method": "POST",
  "url": "/api/tenant",
  "body": {
    "tenant": {
      "name": "My Cool New Tenant with a theme",
       "themeId": "75a068fd-e94b-451a-9aeb-3ddb9a3b5987"
    }
  }
}
```

**Comment by trollr** [comment]
At the moment I use the default theme ID and create a completely new tenant. However it would be nice to set the default theme id instead of working with magic ids

**Comment by robotdan** [comment]
> Can't set sourceThemeId on a new theme if the default theme has a random uuid

The default theme is not random, it is always `75a068fd-e94b-451a-9aeb-3ddb9a3b5987`. 

Perhaps I am not understanding what you want to do.

**Comment by trollr** [comment]
However it's a magic number and I can't be sure it won't change in a further release. I would be much happier if it's possible to set it in the kickstarter file ;)

**Comment by robotdan** [comment]
I this solved already? You can set the default tenantId.

**Comment by pigletto** [comment]
I think this (and other hardcoded uuid-s) should be documented in the kickstart docs. I've just had the same issue - fortunately found this thread

**Comment by robotdan** [comment]
This should be documented already here: https://fusionauth.io/docs/v1/tech/installation-guide/kickstart#reference

If there is anything missing there that would have helped you let us know and we'll update it. Thanks!

**Comment by pigletto** [comment]
There is no information regarding the use of theme id: "75a068fd-e94b-451a-9aeb-3ddb9a3b5987" and other uids like this.

**Comment by robotdan** [comment]
Thanks, I'll get that one added. You mentioned other UUIDs, are there others that you think are missing?

**Comment by pigletto** [comment]
I don't know if there are other uids like this but if there are then I'd love to have it listed. I've found that it would be useful to be able to update default email templates, like "Forgot password" but seems UID of these templates are dynamic (so the only way to modify these with kickstart is to create new ones).

**Comment by robotdan** [comment]
Kickstart doesn't have any default email templates, you have to create your own.

**Comment by robotdan** [comment]
@jobannon can you review this issue and see if we need to add any clarification to the doc. Once that is complete we can close this one out.

**Comment by mooreds** [comment]
Should be fixed by https://github.com/FusionAuth/fusionauth-site/pull/969 when that is reviewed and merged.

**Comment by mooreds** [comment]
Closing this out since https://github.com/FusionAuth/fusionauth-site/pull/969 is merged.
