### ISSUE TITLE
UI Grid Sorting Resets to Descending

### ISSUE THREAD

**Issue by mreschke** [FusionAuth/fusionauth-issues#461]
### Description 
Using the latest FA 1.14.0.  On most pages when you sort a grid by ascending, then click away and back it keeps reseting the sort order to descending.  It does remember the column I sorted, just forces descending every time.  Happens on most grids I tested, except the users grid.

### Steps to reproduce
1. Login to FA UI
2. Click on `Applications` for example
3. Sort any column by ascending
4. Click away or just click `Applications` again
5.  Notice it remembers the sorted column, but always changes the sort direction to descending.

**Comment by robotdan** [comment]
We should be preserving the sort preferences in local storage. I can confirm the local storage is being set, we must not be reading it correctly on page load.
