### ISSUE TITLE
Email using smtp email id instead of email id mentioned in email template

### ISSUE THREAD

**Issue by MrKanthaliya** [FusionAuth/fusionauth-issues#466]
### Description
Receiving Email from SMTP username instead of default from Email id mentioned in email templates.

### Expected
On Email it should show default from email id mentioned in email templates.

**Comment by robotdan** [comment]
Is this answered by this comment https://github.com/FusionAuth/fusionauth-issues/issues/262#issuecomment-582033782 ?

**Comment by robotdan** [comment]
Closing. I believe this is an SMTP server side issue. Please re-open if you think there is a defect in FusionAuth.
