### ISSUE TITLE
Enhance /api/status to return multiple status codes or more information

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#473]
### Problem
Today the status endpoint returns `200` or `500` and if you use this endpoint as a health check for a LB or other node manager, the node may get killed prematurely. 

A `500` generally indicates one of our metrics has exceeded a prescribed threshold, most commonly a db connection wait, or similar issue. 

This can simply mean the box is under heavy load, and not necessarily that the box is sick. 

### Solution
Either provide some configuration as to what the status endpoint returns or reserve `500` for a more catastrophic error - and provide some varying degrees of status so it functions better as a health check for a LB or other node manager.

### Alternatives/workarounds
If the `/api/status` endpoint is causing you trouble as a health check endpoint, you can also make an API call such as `/api/login` with a known user + password w/out an `applicationId` - as a health check. 

### Additional context
N/A

### Related
https://github.com/FusionAuth/fusionauth-issues/issues/362

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by chrishare08** [comment]
An alternative would be to provide an alternative health check such as /healthz which only returns a 200.  This way we can get a very quick response and save /api.status for when more detailed information is needed about the overall operational status, especially since the cost of running /api.status is not free.
