### ISSUE TITLE
Lambda JTW Populate Function not executed for all login endpoints.

### ISSUE THREAD

**Issue by stefan1968** [FusionAuth/fusionauth-issues#474]
### Description 
The JWT populate function only seems to be called on the normal login endpoint. TwoFactor login and identity-provider/login don't call it.

### Steps to reproduce
Simple call the indentity-provider/login or the twofactor login.
The system logs show that the lambda function isn't called.

### Expected behavior
The lambda function to populate jwt claims should be called on all login endpoints.

### Platform
(Please complete the following information)
 - Device: [Any]
 - OS: [Ubuntu]

**Comment by robotdan** [comment]
Thanks for the issue @stefan1968 - this is a known current limitation and is working as designed. 

If you'd like to re-open we can use this track this limitation. It is something we'd like to resolve at some point, but we need to work through some additional edge cases.

**Comment by robotdan** [comment]
I take back my previous comment. :-) This should work, I verified we have tests that cover this scenario. I'd have to know a bit more about your configuration to understand why it would be not be executed.

**Comment by stefan1968** [comment]
Hi Guys, this does indeed work. I'll close this.

Not 100% sure what my problem was.
