### ISSUE TITLE
Specify a tenant in "create application"?

### ISSUE THREAD

**Issue by dhait** [FusionAuth/fusionauth-issues#475]
### Description
According to the documents, there is no parameter in the "Create an Application" API to represent the desired tenant.

**Comment by robotdan** [comment]
The `tenantId` is provided in a header called `X-FusionAuth-TenantId` or provided by an API key if locked to a specific tenant. 

https://fusionauth.io/docs/v1/tech/apis/authentication#making-an-api-request-using-a-tenant-id
