### ISSUE TITLE
CreateUser api doesn't use user.tenantId field in body

### ISSUE THREAD

**Issue by bhenderson** [FusionAuth/fusionauth-issues#478]
## (Put bug title here)
CreateUser doesn't use user.tenantId field in body

### Description 
When making a request like:

```
curl -d '{"user": { "tenantId": "123" }}' /api/user
```

I get an error message like `A Tenant Id is required to complete this request`. Right now tenantId is required to be supplied either in the `X-FusionAuth-TenantId` header or associated with the api key.

### Expected behavior
I am expecting the API to use the tenantId supplied in the body.

### Additional context
We're using version 1.14.0

**Comment by robotdan** [comment]
This is working as designed. There are two ways to make tenant scoped API calls such as Create User, one is to use the HTTP header as you mentioned, the other is to use an API key assigned to one tenant. 

Hope that helps!
https://fusionauth.io/docs/v1/tech/apis/authentication#making-an-api-request-using-a-tenant-id
