### ISSUE TITLE
Add company name to user data

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#485]
Add Company Name to user data

### Problem
Some of my users are corporate, and it would helpful to be able to keep track of which company 
/ organization they work for.

### Solution
Add a new optional "Company" (or "Organization") field to the Add / Manage User forms.

### Alternatives/workarounds
I believe we can attach this data through the API, but it would require us to build a custom user management interface.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Related Issues
https://github.com/FusionAuth/fusionauth-issues/issues/213

**Comment by robotdan** [comment]
We do have plans to allow editing of custom data in the UI. A similar issue has been brought up via this issue https://github.com/FusionAuth/fusionauth-issues/issues/213. 

In addition to editing custom data in the UI, I think what you're asking for is to select one or more values from custom data and add it to the main dashboard of user data so it is plainly visible next to the birthdate, email, first name etc. Does that sound like it would fit your requirement?

**Comment by sedough** [comment]
That will work.  Thanks!

**Comment by robotdan** [comment]
Thanks is available when using Custom Forms.
