### ISSUE TITLE
Show Group Membership

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#486]
### Problem
This is no way to list members of a group.

### Solution
Make groups visible and searchable on the users list page.   Add a users list on the group page.

### Alternatives/workarounds
It should be possible to script this through the API.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by sedough** [comment]
I just noticed there is a collapsed-by-default "Advanced" panel that includes Group search.

**Comment by mooreds** [comment]
@sedough seems like this is resolved, so I'm closing. If I'm wrong, please reopen.
