### ISSUE TITLE
Theme: Custom Style Sheet (CSS) escapes child combinator selectors

### ISSUE THREAD

**Issue by snmed** [FusionAuth/fusionauth-issues#489]
### Description 
CSS child combinator selectors in theme styles sheets, will be rendered in a escaped form. 

### Steps to reproduce
1. Go to 'Themes'
2. Click on 'Edit'
3. Select 'Stylesheet (CSS)'
4. Enter some css style definitions with css child combinator selectors
5. Load a page (ex. Login Page) and inspect the rendered style tag

### Expected behavior
![grafik](https://user-images.githubusercontent.com/5249768/75232662-e6bd0380-57b7-11ea-9443-2bca53d0bb9d.png)

### Screenshots
![grafik](https://user-images.githubusercontent.com/5249768/75232708-fc322d80-57b7-11ea-80fb-82c5289bb5e3.png)

### Platform
 - FusionAuth 1.15.2 (Docker) 
 - Device: Desktop
 - OS: Windows 10
 - All Browsers

**Comment by robotdan** [comment]
Thanks for letting us know @snmed . Is this causing any runtime issues on save, or it is just an error in the display?

**Comment by snmed** [comment]
@robotdan The style sheet can be saved without any problems and in the template editor it's rendered correctly. But on the pages ex. Login Page, it will be rendered in the style tag with escaped selectors and therefore CSS rules won't be applied correctly. This primarily affects only the visual appearance of the web pages, but breaks the corporate design of our customer.

**Comment by robotdan** [comment]
Ok, thanks @snmed we'll get this fixed.

**Comment by robotdan** [comment]
A workaround will be to modify your themed `Helpers` template to add `?no_esc` to your stylesheet output. 

```
<style>
${theme.stylesheet()?no_esc}
</style>
```

This opens you to a risk that if anyone adds an end style tag`</style>` to your stylesheet then JavaScript could be added to your stylesheet and it would be executed. 

In the upcoming release we will default the theme stylesheet to use `?no_esc` and be validated to not contain `</style>`.

**Comment by snmed** [comment]
@robotdan Thanks nice to known, that will solve my problem for the moment. Security isn't an issue at the moment, because only a few IT related people has access to the backend.
