### ISSUE TITLE
Kickstart Variable Substitution Doesn't Work on API Key

### ISSUE THREAD

**Issue by tst-dhudlow** [FusionAuth/fusionauth-issues#493]
### Description
Using the kickstart example from the docs below will create an API key with a value of "#{apiKey}" instead of doing variable substitution.
```
{
  "variables":{
    "apiKey": "4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd"
  }
  "apiKeys": [{
    "key": "#{apiKey}"
  }]
}
```

### Steps to reproduce
1. Follow this guide https://fusionauth.io/docs/v1/tech/installation-guide/kickstart to start FusionAuth with a kickstart.json
2. Use variable substitution in the API key in the kickstart.json as mentioned in the guide at step 2.2 Using Variables
3. Start FusionAuth and go through setup
4. Go to Settings -> API Keys in the console

### Expected behavior
API Key should be set up using value given by `apiKey` variable

### Actual behavior
API Key value is literally #{apiKey}

### Platform
 - Device: GKE (Google Kubernetes Engine)
 - OS: Docker container 
 - Firefox

**Comment by robotdan** [comment]
Hi @tst-dhudlow thanks for letting us know! This will be fixed in the upcoming patch release. 

As a work around, make the first API key not use a variable. 

```
{
  "variables": {
    "apiKey": "4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd"
  },
  "apiKeys": [
    {
      "key": "first!"
    },
    {
      "key": "#{apiKey}"
    }
  ]
}
```
