### ISSUE TITLE
Saving an Application in the admin UI removes the 'data' property 

### ISSUE THREAD

**Issue by dseller** [FusionAuth/fusionauth-issues#5]
**Describe the bug**
When saving an Application in the administration area, it removes the 'data' property from the Application entity.

**To Reproduce**
1. Add user data to an Application object using the API.
2. Edit the Application using the interface (e.g. change the name)
3. Query the API for the Application object
4. See that the 'data' property is missing

**Expected behavior**
The administration interface should merge the changes with the existing entity.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 69.0.3497.100

**Comment by robotdan** [comment]
Hi @dseller - thanks for letting us know. This is indeed a bug. 

The same issue exists for Applications, Groups and Tenants, this will be fixed in the next release which should be `1.0.15`. I'll update this issue once a fix is released.

**Comment by robotdan** [comment]
Fixed in `1.0.16`. 
https://fusionauth.io/docs/v1/tech/release-notes/#version-1-0-16

**Comment by dseller** [comment]
Perfect, thanks!
