### ISSUE TITLE
Swagger Tools

### ISSUE THREAD

**Issue by f0rever-johnson** [FusionAuth/fusionauth-issues#50]
Would it be possible to get the FusionAuth API written with swagger tools?  https://swagger.io  is the website. It's the best way I have seen a developer convey a web api for public consumption

**Comment by robotdan** [comment]
Thanks for the suggestion @f0rever-johnson. 

Having a well documented API is a high priority for us, we have looked at many API documentation tools in the past and have never found one that worked the way we'd like. 

I hope to be able to revisit Swagger and some others in the future to see if we can improve upon the quality and usability of our API doc. 

Are there any particular features that Swagger provides that you'd like to see in the FusionAuth API documentation?

**Comment by f0rever-johnson** [comment]
Apart from it being more visually appealing, it does allow you to create client code at the click of a button.

**Comment by voidmain** [comment]
Is there a specific language that you were hoping to have a client for that we don't have implemented yet?

**Comment by robotdan** [comment]
Closing for now. 

We continue to look for ways to improve our documentation and add good code examples. We have a significant investment in our templates and style across not only API documentation but technical tutorials etc.  There are not current plans to change our documentation platform. 

Thank you for the suggestion.
