### ISSUE TITLE
SAML-enabled login broken after logout

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#503]
### Description 
Authentication is working correctly for both local and SAML users.   However, when I perform a logout in my application, subsequent SAML-enabled logins fail with an "auth_code_not_found" error.   I verified that the redirect_uri fields match on the auth and token calls, and that the code being presented to the token endpoint matches the response from the auth redirect.

This doesn't appear to be an issue when the second login is performed using a local user.  Additionally, things appear to work when using the SAML login button as opposed to the "managed domains" feature.

### Steps to reproduce
1. Login into an application using Fusionauth.
2. Click on application logout button, which calls Fusionauth logout endpoint.
3. Login into an application using FusionAuth using a SAML-enabled user this time.
4. Receive an error when the application calls the token endpoint

### Expected behavior
Token endpoint should return a token.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome

**Comment by sedough** [comment]
Following up:  This doesn't appear related to logout at all.   On login, when users are redirected to their IdP (ADFS in my case) and have to enter their credentials, the call to the FA /token endpoint always fails and they're left a broken application.  When the user manually refreshes the page, it works correctly and they get in.

This issue doesn't manifest itself if:
1.  The user is already logged into ADFS before attempting to access my application
2.  I disable the managed domains feature in FusionAuth and the user presses the button to login.

I double-checked that the redirect_uri parameters are the same between the /authorize and the /token calls.   The code presented in the /token call also looks correct.





When users

**Comment by matthew-altman** [comment]
@sedough Can you please confirm which version of FusionAuth you are using?
Also, are you using PKCE?

**Comment by sedough** [comment]
Matthew,

I'm running version FusionAuth 1.15.3.   Yes, I'm using PKCE with the
authorization code flow from an Angular SPA  (using the angular-oauth2-oidc
library).

Sean

**Comment by robotdan** [comment]
@sedough I think this is fixed in version `1.15.6`. 

There were a few PKCE parameters that were getting lost in the state capture prior to redirecting to a SAML login which was fixed recently. 

Upgrade to `1.15.7` and see if you can recreate. Thanks!

**Comment by sedough** [comment]
I can confirm this is working correctly in v1.15.7.

Thanks!
