### ISSUE TITLE
User Interface for user profile

### ISSUE THREAD

**Issue by gregoriopellegrino** [FusionAuth/fusionauth-issues#508]
### Problem
At the moment the user data can only be changed via API.

### Solution
A graphical interface to allow the user to modify their data (name, surname, etc.).

### Related / Similar Issues
https://github.com/FusionAuth/fusionauth-issues/issues/216

**Comment by mooreds** [comment]
This is delivered in the user account management system, as documented here: https://fusionauth.io/docs/v1/tech/account-management/

Closing.
