### ISSUE TITLE
Hasura JWT Mode - Error fetching JWK

### ISSUE THREAD

**Issue by beatthesharps** [FusionAuth/fusionauth-issues#515]
### Description
First off, I'm pretty new to FusionAuth so I'd like to say thanks for all the hard work thus far. The setup/install was easy as could be, the UI seems to work really well so far, and documentation has been great so all the contributors deserve a lot of credit!

Anyway, I'm running into an issue when trying to secure a Hasura instance with FusionAuth. So far, I've followed along with an earlier thread ([Issue #61](https://github.com/FusionAuth/fusionauth-issues/issues/61)) and the Lambda portion of the thread is working as expected - I can see the console.log output in the logs and I can see the claims added after login.

The engine is being run in a Docker container, as part of a docker-compose file. I was able to confirm the Lambda is operational by **not** including the following line in the "environment" settings of the container:

`HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","jwk_url": "http://127.0.0.1:9011/.well-known/jwks", "issuer":"localhost", "audience": "[redacted_application_id]"}'`

However, this means that Hasura is not running in JWT mode so there isn't any actual authentication occurring without this setting. 

The error that is thrown appears as soon as the Hasura engine attempts to start, the console can never even be loaded. The error is as follows:

> Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 16>: does not exist (Connection refused)

I'm not really sure how else to continue to debug this issue to find a resolution. If anyone could find time to point me in a direction as to where to look, I'd really appreciate it.

Thanks!

**Comment by beatthesharps** [comment]
sorry, realized I posted this in the wrong GitHub 👎 

However if anyone has a suggestion here, I'd still really appreciate the input.

**Comment by robotdan** [comment]
> sorry, realized I posted this in the wrong GitHub 👎

While perhaps not related to FusionAuth directly, there may be someone that can lend a hand.  I'm no expert in Hasura, so perhaps @jakobrosenberg , @nraibaud  or @davidb-e4s can assist if I'm not of any help. :-) 

I'm assuming you're trying to let Hasura know where the JWKS endpoint in FusionAuth is at?

If you could post your docker-compose (or whatever you're using) configuration - I believe the FusionAuth service will be exposed through a named value and port mapped. This means accessing the `jwks` endpoint over `127.0.0.1` likely won't work. 


As an example - in this docker compose example ( https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/docker-compose.yml ) the URL would be `fusionauth:9011`  if referenced by another service.

**Comment by beatthesharps** [comment]
Thanks for the prompt reply regardless of my mistake.

I did use the Docker compose example you suggested so my configuration doesn't look much different:

`  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
      - search
    environment:
      DATABASE_URL: ${DB_URL}
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
      TZ: America/New_York
    networks:
     - db
     - search
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config`

You are correct in your assumption that I was trying to let Hasura know where the JWKS endpoint is at and as it turns out, your suggestion about the IP address was correct! I thought I'd tried using the `fusionauth:9011` previously but I must have either not done so OR not restarted my services in Docker to verify.

Thanks so much for your help, you even answered fast enough to prevent me from opening an issue in the correct GitHub repo. 🥇

**Comment by robotdan** [comment]
You're welcome! Hope you enjoy FusionAuth!
