### ISSUE TITLE
Cannot update user from api, /api/user

### ISSUE THREAD

**Issue by Thangamh** [FusionAuth/fusionauth-issues#516]
I was trying to update a user object using the api call,
PATCH /api/user/{userId} and it returns a 500 response

Please refer the user object below,

`{
	"user": {
		"active": true,
		 "email": "test.test@test.com",
		 "expiry": 3571786483322,
		 "firstName": "test",
		 "fullName": "test test",
		 "id": "85dd8ddc-375f-4683-b1aa-88b97ea45cb4",
		 "imageUrl": "",
		 "insertInstant": 1573804770774,
		 "lastLoginInstant": 1581584345647,
		 "lastName": "",
		 "middleName": "",
		 "passwordChangeRequired": false,
		 "passwordLastUpdateInstant": 1581584090322,
		 "registrations": [{"applicationId": "",
		                    "data": {"birthplace": ""},
		                    "id": "",
		                    "insertInstant": 1573804770774,
		                    "lastLoginInstant": 1581584345647,
		                    "preferredLanguages": ["en"],
		                    "roles": ["Customer"],
		                    "username": "test.test@test.com",
		                    "usernameStatus": "ACTIVE",
		                    "verified": true}],
		 "tenantId": "",
		 "timezone": "Europe/London",
		 "twoFactorDelivery": "None",
		 "twoFactorEnabled": false,
		 "username": "test.test@test.com",
		 "usernameStatus": "ACTIVE",
		 "verified": true
	}
}`

I checked the fusion auth application logs and it says,

`Error in custom provider, java.lang.IllegalArgumentException: No enum constant org.primeframework.mvc.servlet.HTTPMethod.PATCH`

`Caused by: java.lang.IllegalArgumentException: No enum constant org.primeframework.mvc.servlet.HTTPMethod.PATCH`

Anyone have any idea about this?

**Comment by Thangamh** [comment]
Can anyone help me on this please

**Comment by robotdan** [comment]
Can you please provide some additional information about your environment? 

- Version of FusionAuth
- Version of FusionAuth Java Client if you're using our REST client
- Specific example of how you're calling this API

Thanks.

**Comment by Thangamh** [comment]
FusionAuth Version : 1.10.1

I wanted to update the user by, fusion_client.update_user(fusion_id, user)
I will be using the fusionclient python module and the update_user method

**Comment by robotdan** [comment]
Patch is not available until 1.12.0.
https://fusionauth.io/docs/v1/tech/apis/users#update-a-user
