### ISSUE TITLE
500 Error in UI when attempting to add Tenant

### ISSUE THREAD

**Issue by vburghelea** [FusionAuth/fusionauth-issues#517]
### Description 
When going into the Tenant section of the UI to add a new one, the page shows a 500 Error context with no information.

### Steps to reproduce
1. Go to any page
2. Click on 'Tenants' in the menu
3. Click on the + button

### Expected behavior
The Tenant Add form should appear.

### Screenshots
<img width="1015" alt="Screenshot 2020-03-12 at 12 17 21" src="https://user-images.githubusercontent.com/1913582/76516977-b6828f80-645c-11ea-8632-27974bdb872d.png">

### Platform
(Please complete the following information)
 - Device: Macbook Pro 13''
 - OS: macOS
 - Browser + version: Chrome 80.0.3987.132 (Official Build) (64-bit)
--

**Comment by robotdan** [comment]
Unable to recreate, but I think I understand how this could happen.

**Comment by vburghelea** [comment]
Issue got fixed after you logged into our instance - not sure how but closing since it's no longer relevant.

**Comment by robotdan** [comment]
There is a potential issue here that I did fix for the upcoming release. I think the issue arrises when you try to add a new tenant when you've never edited the default tenant yet. 

So it could happen, we'll make this more defensive. 

A workaround for anyone who may run into this is to edit the default tenant (no changes necessary, just edit and save) and then try to add a new tenant.
