### ISSUE TITLE
Cannot save Claims Mapping in External JWT identity provider

### ISSUE THREAD

**Issue by irzhywau** [FusionAuth/fusionauth-issues#518]
### Description 
It seems we cannot add anything on Claims mapping section when configuring an External JWT Identity provider
it just pointing to http://localhost:9011/ajax/identity-provider/claim/add then nothing more

### Steps to reproduce
1. Go to 'Settings > Identity Providers'
2. Create a new one, choose "External JWT"
3. Got to JWT tab and try to add a claim
4. Fill the form and submit
5. Blank page on /ajax/identity-provider/claim/add

### Expected behavior
New claim added

### Screenshots
https://www.loom.com/share/f67a5a147abf44f88095769c1d331ca7

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Linux/Ubuntu
 - Browser + Chrome 80

### Additional context
The instance is running on docker container
FusionAuth version 1.15.3

**Comment by robotdan** [comment]
Fixed, introduced in version 1.15.3, work around is to use the API.
