### ISSUE TITLE
Third party keys are returned from JWKS URL

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#519]
### Description
My application is using the FusionAuth JWKS URI to get a RSA public key for JWT validation.   Unfortunately, even though I only defined a single RSA signing key in FusionAuth, the JWKS endpoint is returning two of them, and my application has no idea which one to use.

I originally assumed there would be a single key, and I was confused because validation was failing.  I had to hard-code my application to use the second key in the set to get validation to work.

It turns out the first key in the set belongs to my ADFS instance that I have configured as a SAML identity provider.   I wouldn't expect this key to be returned in the set.  If this actually is correct behavior, I would expect a "kid" field in the JWT to indicate which key to validate against.

### Steps to reproduce
1. From an empty FusionAuth instance, define a SAML identity provider and import its key
2. From the Key Master, create a new RSA signing key
3. Navigate to /.well-known/jwks.json and see two RSA keys in the response

### Expected behavior
I would only expect to the the FusionAuth RSA signing key in the JWKS response.

### Platform
N/A

**Comment by robotdan** [comment]
When you go to validate a JWT you should be able to take the `kid` and match that up with the `kid` returned from the JWKS endpoint to validate the token. 

Currently all signing pairs will have their public key returned on the JWKS endpoint. The `kid` will be unique can be used to validate a token. 

As far as I know this sounds like it is working as designed. Are you currently using the `kid` in the JWT to identify how to validate the token?

**Comment by sedough** [comment]
That's the problem -- there is no "kid" field in the JWT identity or access tokens.

Also, I can see reason for returning all signing *pairs*, but what's the rationale for returning public key of a foreign identity provider's certificate when FusionAuth doesn't have the corresponding private key?

**Comment by sedough** [comment]
Disregard my comment about not seeing the "kid" field.   My library was showing all the other fields but wasn't printing that one out for some reason.   I see it when I decode manually.

As for JWKS, I still don't like the idea of return my customers' public keys.    But I guess I  can just firewall off that endpoint and not worry about it.

I have what I need now to validate JWTs.   Thanks!

**Comment by robotdan** [comment]
Public keys are public, so there should not be any security concern for returning all public keys we have in our possession. 

In theory we could limit the response to include keys we know we are using to sign JWTs, but it is possible that JWTs are still in the wild for keys that are no longer configured by a particular tenant or application to sign a JWT. 

For this reason we just return all keys that could have been used to sign a token or sign anything that we may have produced.

**Comment by sedough** [comment]
I don't necessarily want to reopen this ticket, but here's the security concern:

Since a third-party's keys are in the JWKS response, my application now trusts that third party directly.  They can issue their own JWTs and bypass any of the validation / reconciling done by FusionAuth.

**Comment by voidmain** [comment]
@sedough while this is true, it did require that you load the trusted public key into FusionAuth at some point. This usually means that you are delegating trust to FusionAuth for the third-party on your behalf. If you don’t trust the third-party, you can revoke the public key from FusionAuth at anytime. 

If you have a detailed threat vector, feel free to provide it step-by-step and we can discuss the implications.

**Comment by robotdan** [comment]
@sedough If you'd like to open a feature request to optionally mark a public key in Key Master as "do not publish" we review the request further. 

As @voidmain mentioned, in general I don't see a concern with publishing a public key from anyone. But perhaps there are some additional vectors we have not considered.
