### ISSUE TITLE
Import users validation error for empty array in request body

### ISSUE THREAD

**Issue by smcoll** [FusionAuth/fusionauth-issues#520]
Of course, sending an empty array to `/api/user/import` amounts to user error, but the validation error is not helpful:

```json
{
  "generalErrors": [
    {
      "code": "[ImportRequestFailed]",
      "message": "An error occurred during the import request. This is most likely due to a unique key constraint which would indicate one or more of the users in the import request already exist in FusionAuth. Re-attempt the request with additional validation by using the [validateDbConstraints] property. If you have already enabled the additional validation and you still receive this error, please open a bug report."
    }
  ]
}
```

Something to the effect of an empty array not being valid would have helped me debug my script.

**Comment by robotdan** [comment]
Thanks for the feedback. Can you provide your exact request JSON?

**Comment by smcoll** [comment]
i used the python client for this one, so i'm only assuming it was something like:

```json
{
  "users": []
}
```

Python request would have been the equivalent to this:

```python
client.set_tenant_id(TENANT_ID)
client.import_users({"users": []})  # same with "validateConstraints": True
```

**Comment by robotdan** [comment]
Fixed, here is the error message you should have received. 

```
{
  "fieldErrors": {
    "users": [
      {
        "code": "[missing]users",
        "message": "Your request is missing the import User information as JSON in the entity-body."
      }
    ]
  }
}

```

Thanks for letting us know!

**Comment by anilaj000** [comment]
i got the same issue will you please explain how to resolve this

**Comment by mooreds** [comment]
@anilaj000 please either post in the community forum or open a support ticket (if you have a plan which includes support).

https://fusionauth.io/community/forum/ is the forum

https://account.fusionauth.io/account/support/ is the link to open a support ticket

Thanks for using FusionAuth!
