### ISSUE TITLE
Adding support for integrating SAML SPs which support the urn:oasis:names:tc:SAML:2.0:nameid-format:persistent NameIDPolicy

### ISSUE THREAD

**Issue by GianvitoBono** [FusionAuth/fusionauth-issues#522]
### Problem
Slack support only `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` as NameID format and at the moment is not supported in FusionAuth SAML IdP.

FusionAuth Event Log 

```
The SAML AuthnRequest was invalid and/or did not pass validation. The error code is [InvalidNameIDPolicy] and the error message is [The AuthnRequest contained an invalid NameId policy. FusionAuth only supports the [urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress] or [urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified] policy]
```

### Solution
The solution would be integrating the support for `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` NameID format with POST bindings

### Alternatives/workarounds
None

### Additional context
Here a link to the official KB for Custom SAML Integration: https://slack.com/intl/en-it/help/articles/205168057-Custom-SAML-single-sign-on

This is also an issue with Elasticsearch/Kibana: https://fusionauth.io/community/forum/topic/776/integrate-fusionauth-with-elastic-cloud?_=1612312567770

### Related Issues
https://github.com/FusionAuth/fusionauth-issues/issues/643

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
From https://github.com/FusionAuth/fusionauth-samlv2/blob/master/src/main/java/io/fusionauth/samlv2/domain/NameIDFormat.java it looks like `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` is now supported.

**Comment by robotdan** [comment]
Our SAML library does, but I think issue is that when FusionAuth is the SAML IdP we hard code the NameID format to `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` in the SAML response to the SP. 

Slack requires this value to be `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` instead.

**Comment by mooreds** [comment]
FusionAuth now supports POST bindings: https://github.com/FusionAuth/fusionauth-issues/issues/845

**Comment by robotdan** [comment]
This should work in 1.28.0, I tested with our Slack account.

**Comment by mooreds** [comment]
Closing.
