### ISSUE TITLE
AWS Set-Cookie invalid format warnings

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#527]
## AWS Set-Cookie invalid format errors

AWS, perhaps others it appears use a cookie expiration value that is not strictly correct which causes a warning in the FusionAuth log. 

### Description 

Unsure if this is caused by Tomcat, or the Apache HTTP client which may be in use by a few of our dependencies such as the Elasticsearch REST client. 

Example warning found in the log

```
2020-03-18T23:33:40.972Z WARNING: Invalid cookie header: "Set-Cookie: AWSALBCORS=<redacted>; Expires=Wed, 25 Mar 2020 23:33:40 GMT; Path=/; SameSite=None; Secure". Invalid 'expires' attribute: Wed, 25 Mar 2020 23:33:40 GMT
2020-03-18T23:33:41.077Z Mar 18, 2020 11:33:41 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
```

This doesn't appear to be a bug in FusionAuth, however it may be that we could be more permissive in the expiration format, or turn off this log if it is just noise. 

### Additional context
Similar issues found:
https://issues.redhat.com/browse/KEYCLOAK-6066
https://issues.apache.org/jira/browse/AMQ-6571
https://issues.apache.org/jira/browse/HTTPCLIENT-1640
https://issues.apache.org/jira/browse/HTTPCLIENT-1763
https://issues.apache.org/jira/browse/HTTPCLIENT-1077
https://stackoverflow.com/questions/36473478

**Comment by robotdan** [comment]
I'm going to close this out. If AWS or anyone is sending an invalid cookie header, I don't know what we can do about it other than turn off the warning log. 

If anyone has an idea, or can provide additional insight here, I'd take any feedback. Thanks!

It is also possible this has been resolved in a more recent version of FusionAuth due to an upgrade of Apache Tomcat.

**Comment by devchan4188** [comment]
Is there any progress on this issue?
