### ISSUE TITLE
Password required on User Create when setting sendSetPasswordEmail

### ISSUE THREAD

**Issue by jakehallas** [FusionAuth/fusionauth-issues#529]
## sendSetPasswordEmail not sending Set Password Email when creating a user

I'm wanting to create a user without specifying the password and have FusionAuth send the Setup Password email. I'm using the PHP client library, and while I can create a user the email is not been sent. However manually dispatching a Reset Password email is delivered successfully. 

I've configured the SMTP settings to use my Mailgun account. 

Here's what I'm sending via the client;

```
$this->authClient->createUser(null, [
            'user' => [
                'active'               => true,
                'sendSetPasswordEmail' => true,
                'birthDate'            => '01/01/1990',
                'email'                => 'a.valid@email.co.uk',
                'firstName'            => 'John',
                'fullName'             => 'John Doe',
                'lastName'             => 'Doe',
                'middleName'           => '',
                'mobilePhone'          => +447777777777,
                'password'             => 'ForSomeReasonThisNEEDStoBeSet',
                'data'                 => [
                    'identifier' => $someIdentifier
                ],
                'memberships'          => [
                    ['groupId' => $myGroupId]
                ],
                'preferredLanguages'   => ['en'],
                'timezone'             => 'Europe/London',
                'twoFactorEnabled'     => false,
                'usernameStatus'       => 'ACTIVE',
                'username'             => $username,
                'verified'             => true
            ]
        ]);
```

Even when I'm passing the `sendSetPasswordEmail` the `password` field is still required, however the docs suggest this shouldn't be the case;

> This field is optional only if sendSetPasswordEmail is set to true. By default sendSetPasswordEmail is false, and then this field will be required.

I've checked the Event Logs and they're empty. I've also confirmed that the template is assigned correctly under the Tenant. Currently the version of FusionAuth installed is 1.15.3

How can I get the Password Setup email to be sent when creating a user? Thanks in advance

**Comment by robotdan** [comment]
Thanks for opening the issue. There may be a bug in the validation logic, the `password` should be optional. 

The `sendSetPasswordEmail` is a top level value, you have it inside of the `user` - so it is being ignored on the request. If you pull it out of the user and make it a sibling to the `user` object it should work for you. 

We can use this issue to fix the validation issue that you're seeing.

**Comment by matthew-altman** [comment]
Wrote some additional tests to confirm that when the `sendSetPasswordEmail` is set at the top level both of the reported issues go away.

**Comment by robotdan** [comment]
@jakehallas @matthew-altman was unable to recreate the issue. We validated that the validation logic is correct, and your initial symptom looks to be caused by the `sendSetPasswordEmail` value not being in the correct location in your JSON request. 

Once you moved `sendSetPasswordEmail` to the top level, did the API behave as expected and allow you to omit the `password` field from the request?

**Comment by jakehallas** [comment]
@robotdan apologies, yes once moved to the top level I could omit the password field.
