### ISSUE TITLE
No email templates after kickstart with admin user

### ISSUE THREAD

**Issue by media-square** [FusionAuth/fusionauth-issues#532]
### Description 
Building a new docker container based on [this docker compose](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/docker-compose.yml) example with a kickstart json with at least one admin user will result in having no e-mail templates. I think this might happen due to the skipped initial setup

### Steps to reproduce
1. Create an .env file
```
FUSIONAUTH_ADMIN_EMAIL: user@example.com
FUSIONAUTH_ADMIN_PASSWORD: shhsecret
FUSIONAUTH_ADMIN_API_KEY: somerandomkeyxxx
```
2. Create a kickstart.json with the following contents
```
{
   "apiKeys":[
      {
         "key":"#{ENV.FUSIONAUTH_ADMIN_API_KEY}"
      }
   ],
   "requests":[
      {
         "method":"POST",
         "url":"/api/user/registration",
         "body":{
            "user":{
               "email":"#{ENV.FUSIONAUTH_ADMIN_EMAIL}",
               "password":"#{ENV.FUSIONAUTH_ADMIN_PASSWORD}"
            },
            "registration":{
               "applicationId":"#{FUSIONAUTH_APPLICATION_ID}",
               "roles":[
                  "admin"
               ]
            }
         }
      }
   ]
}
```
3. Build the docker containers with a kickstart.json as env var (FUSIONAUTH_KICKSTART)
4. Log files indicates kickstart has been initiated with no errors 
```
 io.fusionauth.api.service.system.kickstart.KickstartRunner - Summary:
  - Created API key ending in [...xxx]
  - Completed [POST] request to [/api/user/registration]
```
5. login in fusionauth admin 
6. Go to settings -> email templates
7. empty list 

removing the admin user in the kickstart request will result in having e-mail templates

### Expected behavior
When using kickstart, all default e-mail templates should be created in the same way as going through the initial setup interface

### Platform
- FusionAuth 1.15.3
- Postgres DB 

### Work Around
Temp solution:
Providing all email templates as request in kickstart but this would not be future proof

**Comment by robotdan** [comment]
This is working as designed. When using kickstart you must create templates of you want them as part of your configuration. 

Even if we provided the default templates you'd have to update them to modify the text and links. For this reason we assume when you're using kickstart that you will build whatever you need for your initial setup including templates. 

There are some examples of email templates in kickstart on our GitHub repo. 
https://github.com/FusionAuth/fusionauth-example-kickstart

**Comment by media-square** [comment]
makes sense, thnx for the quick response
I'll add the templates as suggested in the above link
