### ISSUE TITLE
Unable to alter FusionAuth application via PATCH API request

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#534]
### Description 
FusionAuth application has redirect and logout urls set to values that does not conform validation rules for any other application. Because of that, any attempt to alter application attributes results in validation error, Of course, I am referring to the attributes set that is available to change via GUI, ie. name, lambdas and JWT configuration overrides.

### Steps to reproduce
1. Attempt ot alter FusionAuth application attribute via PATH API call
2. See redirect and logout URLs validation error

### Expected behavior
Attributes that can be changed via GUI are also alterable via API.

### Platform
 - Device: Desktop
 - OS: 18.04.1-Ubuntu x64
 - Docker: 19.03.6, build 369ce74a3c
 - Image: `fusionauth/fusionauth-app:1.15.5`

### Additional context
```
$ curl -sX PATCH http://localhost:9011/api/application/3c219e58-ed0e-4b18-ad48-f4f92793ae32 -H "Authorization: **REDACTED**" -H "Content-Type: application/json" -d '{"application": {"name": "test"}}' | jq
{
  "fieldErrors": {
    "application.oauthConfiguration.authorizedRedirectURLs": [
      {
        "code": "[invalidURL]application.oauthConfiguration.authorizedRedirectURLs",
        "message": "Invalid URL [/login] for property [application.oauthConfiguration.authorizedRedirectURLs]."
      }
    ],
    "application.oauthConfiguration.logoutURL": [
      {
        "code": "[invalidURL]application.oauthConfiguration.logoutURL",
        "message": "Invalid URL [/] for property [application.oauthConfiguration.logoutURL]."
      }
    ]
  }
}

```

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/441  
- https://github.com/FusionAuth/fusionauth-issues/issues/534 (this)
- https://github.com/FusionAuth/fusionauth-issues/issues/667
- https://github.com/FusionAuth/fusionauth-issues/issues/956

**Comment by robotdan** [comment]
Would prefer to fix this under https://github.com/FusionAuth/fusionauth-issues/issues/441 when adding support for RFC 7396.

**Comment by robotdan** [comment]
I incorrectly assumed this one was related to the PATCH handling for arrays. This was fixed under https://github.com/FusionAuth/fusionauth-issues/issues/1110.
