### ISSUE TITLE
Lambda can't set roles on dynamic registration via SAML

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#536]
### Description 
I'm trying to use a SAML v2 Reconcile lambda to set roles on a registration, as is shown in the documentation here:  https://fusionauth.io/docs/v1/tech/lambdas/samlv2-response-reconcile.    

The roles seem to get set if the user already has a registration.  However,  if the registration is dynamically created via the "Create Registration" option under Identity Providers, no roles are set until the user authenticates for the second time.

### Steps to reproduce
1. Create a SAML identity provider and an application.
2. Enable "Create Registration" for the application under the SAML settings
3. Configure the provider to use the reconcile lambda shown below.
4. Have a user perform a SAML login and look at their User Profile.   They will have a registration, but no roles will be set.
5. Have the user logout and log back in again.   Now their registration will have the correct roles.

### Expected behavior
The roles should be set on the initial login when the registration is created.

### Platform
 - FusionAuth 1.15.3

### Additional context
Here's my reconcile lambda.,  The application is configured with the role.

```
function reconcile(user, registration, samlResponse) {
  registration.roles = ['test-role'];
}
```

**Comment by robotdan** [comment]
In reviewing this code, this appears to be working as designed. I need to do some further investigation if this is the correct behavior.

**Comment by robotdan** [comment]
I think we originally made this architecture decision because we were worried about the threat vector this introduces. 

I think as long as we document the risks so that those developing lambdas are fully aware of the danger of modifying roles we could lift this restriction.

**Comment by robotdan** [comment]
A workaround is to use a JWT Populate Lambda and set the `roles` claim. This limitation will be lifted in an upcoming patch or feature release.
