### ISSUE TITLE
Cookie SameSite Configuration or default behavior

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#537]
### Description 

Chrome and other browsers are starting to require cookies contain the `SameSite` attribute. 
This is not currently available in the Java Servlet 3.1 or 4.0 specification. 

This only affects cookies that are not marked as secure which means the connection is not using TLS. 

> Deprecate and remove the use of cookies with the SameSite=None attribute but without the Secure attribute. Any cookie that requests SameSite=None but is not marked Secure will be rejected.

https://www.chromestatus.com/feature/5633521622188032

More recent versions of Apache Tomcat do seem to have some support for this capability. 

It is also possible to manually write the `Set-Cookie` header, but this has a bunch of problems as well. 

### Additional context
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

This PR may contain what we need, we'll see if we can pick this up without moving to Tomcat 9 or 10. 
https://github.com/apache/tomcat/pull/162

https://security.stackexchange.com/a/187671/188227

https://www.chromestatus.com/feature/5088147346030592

**Comment by jon-at-advarra** [comment]
@robotdan Just an FYI that Firefox is starting to warn for unsecure cookies w/o `SameSite` set:
![image (2)](https://user-images.githubusercontent.com/116736293/205754346-ab4d0c0e-51fb-460a-860e-5203c1d3fe30.png)
