### ISSUE TITLE
Add SMTP Test button

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#539]
### Problem
Testing the SMTP server configuration is really only done by sending an email currently. 

### Solution
Add a test button to allow the configuration to be tested before saving, or at any point. 

### Alternatives/workarounds
Send an email to see if works, and check the event log. 

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Are there any errors on the JavaScript console ?

**Comment by ArnoBuschmann** [comment]
There are no errors in the JavaScript console. After about two minutes I get just this:

"Unable to send email via JavaMailCould not connect to SMTP host: sslout.df.eu, port: 465"

The SMTP settings are desecribed here: https://www.df.eu/blog/sslin-df-eu-sslout-df-eu/ so port should be 465, host sslout.df.eu, security SSL... nod idea what could be wrong

**Comment by robotdan** [comment]
If you're running in Docker, it may be related to this issue. https://github.com/FusionAuth/fusionauth-issues/issues/622

If in docker, pull the latest image again and then retry.

If that doesn't work, I would commend trying to connect with swaks ( http://www.jetmore.org/john/code/swaks/ ) and if that works then we know it is something to do with FusionAuth.

**Comment by ArnoBuschmann** [comment]
It has not been running on Docker but directly. Now Swaks was great to find out, that the SMTP port was blocked by the hoster. Problem solved, works now :) Thanks for your help!

**Comment by robotdan** [comment]
Awesome, thanks for the update. Yeah, SWAKS is awesome, that is my "go to" for debugging SMTP connections.
