### ISSUE TITLE
Add system log viewer to the UI

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#540]
### Problem
If an exception occurs FusionAuth support may request the system logs. If you don't have access to the console, this is not possible. 

If you do have access to the console, it requires some instruction if you are not familiar with unix systems. 

### Solution
Add the ability to read a portion of the log in the UI and to download it to your computer. 

### Alternatives/workarounds
View the log on the server running FusionAuth. 

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by prabhakarreddy1234** [comment]
Also, It would be much useful if the log data is stored and indexed in elastic search. We can setup alerts and custom dashboards.
