### ISSUE TITLE
Pin the HTTP method header columns on the API key pages

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#541]
### Problem
When you scroll on the add or edit API key page the table header columns go off the page and you have to keep scrolling up to see which column you want to select. 

### Solution
If the table headers were pinned this would be helpful. 

### Alternatives/workarounds
Scroll up and down like an idiot. 

### Additional context
Thanks to @mooreds for the suggestion. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by andrewpai** [comment]
This was fixed back in a release in mid-2020.
