### ISSUE TITLE
Unable to start the server due to intermittent database connection setup

### ISSUE THREAD

**Issue by sanjuam** [FusionAuth/fusionauth-issues#543]
### Description 
 - When I try to run docker-compose up using docker-compose.yml sometimes is will run smoothly
sometimes I will encounter an error message stating:

fusionauth_1_7c80ab36b9eb |   Unable to start the server. Here's why: 
fusionauth_1_7c80ab36b9eb | 
fusionauth_1_7c80ab36b9eb | 
fusionauth_1_7c80ab36b9eb | [Error injecting constructor, java.lang.IllegalArgumentException: Your Fusionauth configuration file [/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../config/fusionauth.properties] is invalid. Here are the errors:
fusionauth_1_7c80ab36b9eb | 
fusionauth_1_7c80ab36b9eb |   - You must provide a value for the [database.url] setting.
fusionauth_1_7c80ab36b9eb |   - You must provide a value for the [database.username] setting.
fusionauth_1_7c80ab36b9eb |   - You must provide a value for the [database.password] setting.

### Steps to reproduce
1. Download docker-compose.yml
2. Download .env 
3. Uncomment port numbers for postgres and search
4. Increase vm.max_map_count as advised: 262144
5. added this line in search service - discovery.type=single-node
6. updated this line in .env ES_JAVA_OPTS=-Xms1g -Xmx1g

### Expected behavior
docker-compose should start properly

### Platform
(Please complete the following information)
 - Device: Dell Latitude
 - OS: Ubuntu 19.10
 - Mozilla Firefox

**Comment by sanjuam** [comment]
![Screenshot from 2020-04-02 15-38-30](https://user-images.githubusercontent.com/31019551/78222769-57161d80-74f8-11ea-9946-bf8a3036b304.png)

**Comment by sanjuam** [comment]
my docker-compose.yml

version: '3'

services:
  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  search:
    # image: fusionauth/fusionauth-search:latest
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - discovery.type=single-node
    # Un-comment to access the search service directly
    ports:
      - 9200:9200
    networks:
      - search
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
      - search
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://localhost:9200
      FUSIONAUTH_URL: http://fusionauth:9011
    networks:
     - db
     - search
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

networks:
  db:
    driver: bridge
  search:
    driver: bridge

volumes:
  db_data:
  es_data:
  fa_config:

**Comment by sanjuam** [comment]
.env

POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
DATABASE_USER=fusionauth
DATABASE_PASSWORD=hkaLBM3RVnyYeYeqE3WI1w2e4Avpy0Wd5O3s3

ES_JAVA_OPTS=-Xms1g -Xmx1g

FUSIONAUTH_MEMORY=256M

**Comment by robotdan** [comment]
Have you modified the configuration in `/usr/local/fusionauth/config` ? The error is correct, those fields must be defined, even if they are overridden by the environment values.

**Comment by sanjuam** [comment]
please take note, I'm running them via docker-compose. I tried finding /usr/local/fusionauth/config to no avail. Screenshot to follow.

**Comment by sanjuam** [comment]
![Screenshot from 2020-04-03 06-19-26](https://user-images.githubusercontent.com/31019551/78305299-232c0e00-7573-11ea-98d0-f7f907dd42db.png)

**Comment by sanjuam** [comment]
I'm closing this issue. PEBKAC. 

Thanks!
