### ISSUE TITLE
Identity Provider Hinting

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#544]
### Problem
It's not a really a problem, but it would be nice if FusionAuth could redirect to a third-party identity provider without requiring the user to enter an email address.

### Solution
As an alternative to the "managed domains" feature under Identity Providers, it would be useful if an application could provide a "hint" in the authorization redirect to tell FusionAuth which identity provider to use.

That would make the login process more seamless because users can be provided a link to https://customer-name.mycompany.com and get access without have to enter their email address.   My application could parse the "customer-name" host name from the URL and provided it to FusionAuth as a hint.

### Alternatives/workarounds
It's more a management hassle, but it's also possible to configure multiple applications in FA and give each one its own identity provider.

The managed domains feature works pretty well, so I wouldn't consider this a high priority.

**Comment by robotdan** [comment]
I think this is a duplicate request, if we're missing any details covered here please add a comment to Issue #178 .

Thanks! 

https://github.com/FusionAuth/fusionauth-issues/issues/178
