### ISSUE TITLE
Unhandled exception on /oauth2/token request w/o redirect_url

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#546]
### Description 
When final request of the authorization_code flow misses `redirect_url` parameter, FusionAuth encounters unhandled exception.

### Steps to reproduce
1. Send 
    ```
    POST /oauth2/token HTTP/1.1
    Host: localhost:9011
    Authorization: Basic  [...]
    Content-Type: application/x-www-form-urlencoded
  
    grant_type=authorization_code&code=adsaa
    ```
    with valid authorization.
2. Observer unhandled exception in FusionAuth logs.

### Expected behavior
`invalid_request` response is disposed to the client by FusionAuth.

### Platform
 - Device: Desktop
 - OS: 18.04.1-Ubuntu x64
 - Docker: 19.03.6, build 369ce74a3c
 - Image: `fusionauth/fusionauth-app:1.15.6`

### Additional context
```
curl -sX POST  http://localhost:9011/oauth2/token  -H 'authorization: Basic **REDACTED**' 'content-type: application/x-www-form-urlencoded' -d 'grant_type=authorization_code&code=foo' | jq   
{
  "generalErrors": [
    {
      "code": "[Exception]",
      "message": "FusionAuth encountered an unexpected error. Please contact support for assistance."
    }
  ]
}
```

**Comment by robotdan** [comment]
Thanks for the report @mgetka we'll take a look.

**Comment by robotdan** [comment]
Fixed, will be in the next release. Thanks for reporting!

**Comment by mgetka** [comment]
BTW, during my fiddling around with FusionAuth, I have sent many malformed requests to the API. And there were other occurrences where unhandled exception occurred instead of `400 Bad Request` response. I decided to post this specific issue, since [authlib](https://docs.authlib.org/en/latest/) library for python may send such requests in response to some odd, but possible, user behavior and handling of such case without proper OAuth2 error response looks like code smell in my project. Other situations were less likely to occur in environment other than development one. Finally, the question is, are you interested in receiving the feedback also on those less "real world" cases?

**Comment by robotdan** [comment]
Thanks for the note @mgetka yes - if you have other scenarios where you are not getting a proper error let us know. 

APIs should be bullet proof. :-) Feel free to open a separate issue and outline any use cases you found that don't give you the response that you expect.
