### ISSUE TITLE
Do not overwrite User details when authenticating via identity provider

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#547]
### Problem
When authenticating an User with an identity provider, if the this user already exists and already has a `firstName`, `lastName`, `imageUrl`, etc. these parameters are overwritten by those retrieved from the identity provider token.

### Solution
Add an option to disable this behavior. Example: 
- `identityProvider.overwriteUserDetails` 
  - `boolean`: default: `true`- So that it won't result in a breaking change
- `identityProvider.applicationConfiguration[applicationId].overwriteUserDetails`
  - `boolean`: default: `true` - Same as above

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the issue @johnmaia, this would be a nice enhancement.

**Comment by johnmaia** [comment]
@robotdan this is no longer an issue thanks to the introduction of lambda functions on each identity provider (version `1.17.0`).
