### ISSUE TITLE
Oauth Logout Template (Theme) does not apply to other tenants. Still uses the FusionAuth Theme

### ISSUE THREAD

**Issue by materia2021** [FusionAuth/fusionauth-issues#549]
### Description 
Created a new tenant and applied a new theme for the newly created tenant.
Tried changing the Login and Logout Template of the new theme but the modifications reflects only on Login. The logout template still uses the FusionAuth's theme.

### Steps to reproduce
1. Create tenant.
2. Create theme.
3. Apply Changes to Logout Template. (Try removing the footer)
4. Change tenant's theme.
5. Login then logout.

### Expected behavior
Changes on the Logout template should reflect also in other tenants.
The footer "Powered by FusionAuth" should be removed.

### Screenshots
![Screenshot from 2020-04-06 16-11-46](https://user-images.githubusercontent.com/8675872/78537883-bfc80780-7822-11ea-99a3-37ea0e110804.png)

### Platform
(Please complete the following information)
 - Device: any
 - OS: Ubuntu 18
 - Firefox 72.0.2 (64-bit)

**Comment by robotdan** [comment]
@materia2021 each tenant will have a theme configured. Are you certain you have assigned the modified to all tenants?

**Comment by materia2021** [comment]
> @materia2021 each tenant will have a theme configured. Are you certain you have assigned the modified to all tenants?

As I have said, I assigned a new theme based on the default theme for my newly created tenant.
Modified the Login and Logout template (removed the footer). The changes applies to Login but not in Logout. It still uses the default's Logout template.

**Comment by robotdan** [comment]
When you use the logout action from your angular app, are you only passing in the `id_token_hint`? If so, can you try adding the `client_id` to the URL? If adding the `client_id` fixes the issue, I believe I understand what is happening.

**Comment by materia2021** [comment]
> When you use the logout action from your angular app, are you only passing in the `id_token_hint`? If so, can you try adding the `client_id` to the URL? If adding the `client_id` fixes the issue, I believe I understand what is happening.

I set the client_id in the url and it works.
btw I'm using angular-oauth2-oidc
I guess ill just open an issue on lib side.

Thanks

**Comment by robotdan** [comment]
Actually, this is a good place for the issue. The root issue is that we are not identifying the tenant related to the `id_token_hint` early enough to select the correct theme for the logout panel. 

The `client_id` is optional, but to get the correct theme you'll need to provide the `tenantId` request parameter. 

https://fusionauth.io/docs/v1/tech/oauth/endpoints#logout

The `tenantId` id a required parameter. I believe the behavior you're seeing is working as designed.  Adding the `tenantId` to the request should fix your issue.

**Comment by materia2021** [comment]
> Actually, this is a good place for the issue, it is not related to the angular client. The root issue is that we are not identifying the tenant related to the `id_token_hint` early enough to select the correct theme for the logout panel.
> 
> The `client_id` is optional, but to get the correct theme you'll need to provide the `tenantId` request parameter.
> 
> https://fusionauth.io/docs/v1/tech/oauth/endpoints#logout
> 
> The `tenantId` id a required parameter. I believe the behavior you're seeing is working as designed. Adding the `tenantId` to the request should fix your issue.

yeah I missed the tenantId. thank you!
