### ISSUE TITLE
Support to customize the passwordless code generated with start passwordless login call

### ISSUE THREAD

**Issue by bhavyalatha26** [FusionAuth/fusionauth-issues#551]
### Problem
Right now the passwordless code generated is a 43 length alpha numeric value(as per docs). While this looks good when code is sent through email , it looks way too lengthy when sent over sms (phone authentication).

### Solution
A setting can be provided in the fusion auth console , that allows the user to customize the length and type of code(alphanumeric/only numeric/only alphabet) to be generated whenever passwordless feature is used.

### Alternatives/workarounds
No

### Additional context
No

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
@bhavyalatha26 have you reviewed the advanced settings in the tenant configuration? 

https://fusionauth.io/docs/v1/tech/core-concepts/tenants#advanced

**Comment by bhavyalatha26** [comment]
@robotdan my bad , I missed this ! Thank you for pointing me to the required docs.

A relavent question , does fusion auth support login with mobile number as well ? I could see only login using email/username , so just curious to know if the support is already available and need to check some advanced settings similar to above.

If not available is there any possibility of adding that support in near future ?

**Comment by robotdan** [comment]
This is on the roadmap, but is not currently available. 

Some related issues to login with phone:
https://github.com/FusionAuth/fusionauth-issues/issues/1
https://github.com/FusionAuth/fusionauth-issues/issues/336
https://github.com/FusionAuth/fusionauth-issues/issues/341
https://github.com/FusionAuth/fusionauth-issues/issues/346
