### ISSUE TITLE
`Unable to Base64 decode state returned from callback` with idp in login UI

### ISSUE THREAD

**Issue by ulybu** [FusionAuth/fusionauth-issues#553]
### Description 

Hi.
When using fusionauth as an oauth provider the full authorization code grant works (using node + passport).
Now I’ve activated and configured social provider for the login UI. And for both google and facebook I get a `missing_redirect_uri` error. This happen after I’ve granted access with the social provider’ UI.
As the flow works fine without social login, I assume it's not a configuration issue on my end (like my redirect_uri actualy being missing in my application config).

At the same moment, I get an error in the Event Log
```
Unable to Base64 decode state returned from callback.
Returned state:
client_id=0f9dbf49-2e14-4457-915c-cba199733129&code_challenge=&code_challenge_method=&metaData.device.name=Mac%20Chrome&metaData.device.type=BROWSER&nonce=&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fauth%2Ffusionauth%2Fcallback&response_mode=&response_type=code&scope=offline_access&state=&tenantId=db507f75-2f84-2e46-5f8c-bc9913a3880b&timezone=Europe%2FParis&user_code=
```

Unable to Base64 decode state returned from callback

### Steps to reproduce
1. Go to the login UI with idp activated. link:
``` 
https://swift-tech.fusionauth.io/oauth2/authorize?client_id=0f9dbf49-2e14-4457-915c-cba199733129&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fauth%2Ffusionauth%2Fcallback
```
2. click google or facebook's button
2. authenticate yourself to the social provider
2. accept grant
2. you'll get redirected to the fusionauth `/oauth2/callback` endpoint and an error is displayed. link:
```
https://swift-tech.fusionauth.io/oauth2/callback?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZmY2Y0MTMyMjQ3NjUxNTZiNDg3NjhhNDJmYWMwNjQ5NmEzMGZmNWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiNDI4NjM4ODc1OTE0LWRuczA5N2RpNzZtMzBjNHRmOW5lODVnMXQyaXVzbHI3LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiNDI4NjM4ODc1OTE0LWRuczA5N2RpNzZtMzBjNHRmOW5lODVnMXQyaXVzbHI3LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAwMjQ1MzMxNDc0NjAwMTYyNTU3IiwiZW1haWwiOiJ1bHlidS5kZXZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiI4azNsemROYmRpWWhGeDRPZzl5dkRnIiwibmFtZSI6InVseXNzZSBQcnlnaWVsIiwicGljdHVyZSI6Imh0dHBzOi8vbGg2Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tLXVseUNnck9ZZW8vQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQUFLV0pKT3dqZHp1WHdMMGdvU05YMjN3NlRrMjZzMWNmUS9zOTYtYy9waG90by5qcGciLCJnaXZlbl9uYW1lIjoidWx5c3NlIiwiZmFtaWx5X25hbWUiOiJQcnlnaWVsIiwibG9jYWxlIjoiZnIiLCJpYXQiOjE1ODY1MzI5NDUsImV4cCI6MTU4NjUzNjU0NSwianRpIjoiMjc2MmIxMDIwZDg3YTkwZGI3YmU3ZTYzY2RmMzcxOGFkNDBhOTIzMCJ9.0S19DECt686tLfH3AW4me0u5RC9XX3tz-UIkwpPMEAg1pYs0vpmpNfs2Y_vue81IDXny2VJXz6fkrwpoiJI9A3wo4FS9hpI2OWNRw7FKXUVdUFiKkiE6yeyBtzECsFfmmLli0mIhd_oaYlGSWhvVV69zx3_KvZNM7mSstQPDdU0u69SXJ8QUNP5vNXRt9vek71Q_zIgBoUAZVsOolci-f38TXaNpvOXdTt12bHXo-InR_C_InEyFBCPApA5fjrKrRV8YdN08QHFlC46RJnuaXk3UEn6p0ftqE4QG3JmGkMDIxgxur6_Pu0dqElFmUL9BSyd9GNoS-lWUP60gEwsxwg&identityProviderId=82339786-3dff-42a6-aac6-1f1ceecb6c46&state=client_id%3D0f9dbf49-2e14-4457-915c-cba199733129%26code_challenge%3D%26code_challenge_method%3D%26metaData.device.name%3DMac%2520Chrome%26metaData.device.type%3DBROWSER%26nonce%3D%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5000%252Fauth%252Ffusionauth%252Fcallback%26response_mode%3D%26response_type%3Dcode%26scope%3D%26state%3D%26tenantId%3Ddb507f75-2f84-2e46-5f8c-bc9913a3880b%26timezone%3DEurope%252FParis%26user_code%3D
```
6. user has not been created

watch in video: https://share.getcloudapp.com/8LujGJQD

### Expected behavior
I get redirected to my setup  redirect_uri and the user has been created and registered 

### Screenshots
![image](https://user-images.githubusercontent.com/2479249/79003205-67f70c80-7b52-11ea-8562-b7566632502e.png)

![image](https://user-images.githubusercontent.com/2479249/79003261-86f59e80-7b52-11ea-8a28-193f2809bb19.png)

### Platform
(Please complete the following information)
 - fusionauth: cloud hosted `https://swift-tech.fusionauth.io`, version 1.15.7
 - OS: Mac os Catalina 10.15.4
 - Browser + version Chrome Version 80.0.3987.149 (Official Build) (64-bit)

### Additional context
Does the same with Facebook, been said on slack to look like a [bug fixed on 1.15.7](https://fusionauth.io/docs/v1/tech/release-notes#version-1-15-7), but it's the version I'm running

**Comment by robotdan** [comment]
Thanks for opening this @ulybu  - I think I have it nailed down.  Fix coming soon.
