### ISSUE TITLE
incorrect handling of redirect_uri with query string parameters

### ISSUE THREAD

**Issue by zvainer** [FusionAuth/fusionauth-issues#56]
### Description 
when application's 'Authorized redirect URL' contains query string parameters, the redirect url (location header value) returned by oauth2/authorize endpoint is illegal.

### Steps to reproduce
1. define an 'Authorized redirect URL' with query string for some application, e.g. http://some-domain/oauth/redirect?a=b
2. log in to the application using fusionauth login page
3. check the url the browser is redirected to after successful log in

### Expected behavior
the browser is redirected to http://some-domain/oauth/redirect?a=b&code=some-cod&userState=Authenticated

### Actual behavior
the actual redirect url is http://some-domain/oauth/redirect?a=b?code=some-cod&userState=Authenticated

**Comment by robotdan** [comment]
Duplicate of #55

**Comment by robotdan** [comment]
Hi @zvainer thanks for taking the time to report this issue. 

We had already opened an issue for this bug, so this will be a duplicate. The bug has been fixed and it should be available in a release today or tomorrow. 

Thanks!

**Comment by robotdan** [comment]
Fixed via #55. Closing.
