### ISSUE TITLE
Send "username" in /oauth2/userinfo

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#562]
### Problem
`/oauth2/userinfo` (https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo) doesn't include `username`, making it impossible to sync usernames from application.

### Solution
* Include "username" in /oauth2/userinfo
* Include "user.data" in /oauth2/userinfo

### Alternatives/workarounds
-

### Additional context
Integration with Rocket.Chat: https://rocket.chat/docs/administrator-guides/authentication/oauth/keycloak/

Rocket.Chat can support `username` sync but not given by FusionAuth.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
If the user has a `username` defined - it should be coming back. The claim will be called `preferred_username` which is the standard OpenID Connect  name. 

https://fusionauth.io/docs/v1/tech/oauth/tokens
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

You can also use a lambda to add additional claims to the JWT using the JWT populate lambda, and claims added to the JWT using that lambda will also be returned on the Userinfo endpoint.

**Comment by ceefour** [comment]
@robotdan Really it's already in `/oauth2/userinfo`? Wow that's good news.

So it seems the documentation is not so clear on this feature. I'm not sure yet how to test the OAuth. So in `/oauth2/userinfo` there is already a `preferred_username` field that Rocket.Chat can use?

**Comment by mooreds** [comment]
This issue should be resolved once https://github.com/FusionAuth/fusionauth-site/pull/938 is reviewed and deployed.
