### ISSUE TITLE
Bump Handlebars to Address High Severity Security Vulnerability

### ISSUE THREAD

**Issue by michael-burt** [FusionAuth/fusionauth-issues#564]
### Description
There is a high severity vulnerability in the version of Handlebars used in FusionAuth. See report here: https://snyk.io/vuln/SNYK-JS-HANDLEBARS-534988

Log into FusionAuth admin dashboard and view source: `<script src="/js/handlebars-v4.0.10.js"></script>`

This vulnerability is present in v4 - v4.5.2

**Comment by robotdan** [comment]
Upgrading to 4.7.6 pending any incompatibility issues.
