### ISSUE TITLE
Unhandled exception on malformed semi-form-url-encoded request

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#570]
### Description 
Performing request (POST/PUT/UPDATE ...) to _any_ url with the `content-type` header of the following structure
```
content-type: application/x-www-form-urlencoded[SUFFIX]
```
where `[SUFFIX]` is any string except all white-spaces and with request body invalid in the terms of `application/x-www-form-urlencoded` content type syntax results in unhandled exception.

### Steps to reproduce
1. Send request with features described in description, eg.
   ```
   POST / HTTP/1.1
   Host: localhost:9011
   content-type: application/x-www-form-urlencoded-mgetka
   Content-Length: 3
   
   foo
   ```
2. Observer unhandled exception in FusionAuth logs.

### Expected behavior

Appropriate 4xx HTTP error code is returned

### Platform
 - Device: Desktop
 - OS: 18.04.1-Ubuntu x64
 - Docker: 19.03.8, build afacb8b7f0
 - Image: fusionauth/fusionauth-app:1.15.8

### Additional context
```
curl -v http://localhost:9011 -H 'content-type: application/x-www-form-urlencoded-foo' -d "bar"
* Rebuilt URL to: http://localhost:9011/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9011 (#0)
> POST / HTTP/1.1
> Host: localhost:9011
> User-Agent: curl/7.58.0
> Accept: */*
> content-type: application/x-www-form-urlencoded-foo
> Content-Length: 3
> 
* upload completely sent off: 3 out of 3 bytes
< HTTP/1.1 500 
< Set-Cookie: JSESSIONID=74441E3EC2DFB203EDE2935D41244D59; Path=/; HttpOnly; SameSite=Lax
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Tue, 21 Apr 2020 18:52:05 GMT
< Connection: close
<
[...]
```

```
curl -vX UPDATE http://localhost:9011/foo/bar -H 'content-type: application/x-www-form-urlencoded-baz' -d "qux"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9011 (#0)
> UPDATE /foo/bar HTTP/1.1
> Host: localhost:9011
> User-Agent: curl/7.58.0
> Accept: */*
> content-type: application/x-www-form-urlencoded-baz
> Content-Length: 3
> 
* upload completely sent off: 3 out of 3 bytes
< HTTP/1.1 500 
< Set-Cookie: JSESSIONID=FB948B2348A309C4140F9E315BDC9F0E; Path=/; HttpOnly; SameSite=Lax
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Tue, 21 Apr 2020 18:57:09 GMT
< Connection: close
< 
[...]
```

**Comment by robotdan** [comment]
Not sure I follow for certain. The issue is that you're sending accidentally or otherwise, an invalid `Content-Type` header to FusionAuth? 

In most cases, I would expect this to cause a `500` status code and throw an exception. In theory we could optionally not log an exception, but a `500` is a reasonable status code from my perspective. 

We usually return a `400` if your input is invalid. But without a correctly formatted `Content-Type` header, the MVC cannot consume the request to understand if the request is valid or not. This failure occurs very early in the request mapping workflow.

Are you concerned about the exception in the log, or what is the primary concern with this error?

**Comment by mgetka** [comment]
This case is one of less real-world issues I have mentioned in one of previous posts. It's just a matter of HTTP codes semantics. Of course, the request payload should be treated as user input. But HTTP headers and cookies are user input as well - since they come from the client side. In the typical everyday use case, normal user doesn't alter cookie jar contents, nor modify request headers in the web browsers. But from the security perspective, any malformed data can be present in any part of the HTTP request. Thus all user input: payload, headers, cookies should be sanitized before further processing.

Referring to RFC 7231

> The first digit of the status-code defines the class of response. The last two digits do not have any categorization role. There are five values for the first digit:
> -   1xx (Informational): The request was received, continuing process
> -   2xx (Successful): The request was successfully received, understood, and accepted
> -   3xx (Redirection): Further action needs to be taken in order to complete the request
> -   4xx (Client Error): The request contains bad syntax or cannot be fulfilled
> -   5xx (Server Error): The server failed to fulfill an apparently valid request

In this case it's hard to say that the request is _apparently valid_. It's obviously invalid, and thus 4xx would be more appropriate.

Semantics are always a hot potato. But IMHO, responding with 500 status code suggests that stopping the request on the early stage looks more like happy coincidence rather than designed behavior.

I'm not much of a pentester, so my malicious usage of this feature may not be of much relevance. But I can imagine that malicious user will try to hide some other malicious attempts by flooding the logs with unhandled exception entries and thus triggering logrotate configured to restrain combined logs file size. Also, since we have #372, one could attempt on DOS attack by filling up host disk. But still, silencing the log entry, would be more of a symptomatic treatment.

**Comment by robotdan** [comment]
Thanks @mgetka I appreciate your thoughtful input. I'll review what it would take to return a `400` instead.

**Comment by robotdan** [comment]
Internal:
Let's review, triage and try to recreate. If there is a bug in the form body parser that is not spec compliant, let's fix.

**Comment by robotdan** [comment]
I did some testing, and this should now work as you expect. We've made some changes to the underlying body handles in the last year. 

You should be getting a `400` and a JSON response body that looks like this:

```
{
  "fieldErrors": {},
  "generalErrors": [
    {
      "code": "[UnsupportedContentType]",
      "message": "Unsupported [Content-Type] HTTP request header value of [application/x-www-form-urlencoded-baz]."
    }
  ]
}```
