### ISSUE TITLE
Require PKCE for the authorization code grant

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#572]
### Problem
To be prepared for OAuth 2.1, it'd be great to be require PKCE for the authorization code grant. https://fusionauth.io/blog/2020/04/15/whats-new-in-oauth-2-1

### Solution
Provide additional configuration in the Application OAuth config to optionally require PKCE during the Authorization Code grant. 

This may be done using a `Enable OAuth 2.1 mode` or simply a a `Require PKCE` toggle. 

### Alternatives/workarounds
You can currently use PKCE , but it is not enforceable as required. Currently it is up to the caller to add the additional request parameters `code_challenge` and `code_challenge_method ` to the Authorization request. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/942
- https://github.com/FusionAuth/fusionauth-issues/issues/968
- https://github.com/FusionAuth/fusionauth-issues/issues/1152

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Can we close this one out @mooreds now that https://github.com/FusionAuth/fusionauth-issues/issues/1152 is delivered?

**Comment by mooreds** [comment]
Agreed, this has been delivered.
