### ISSUE TITLE
Support Refresh Token configuration for one time use

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#573]
## Support configuration for one time refresh tokens or sign them

Due to the sensitive nature of the refresh token, ensuring it is stored correctly is critical to securing the token correctly. 

One way in which FusionAuth can help secure the refresh token is to allow the refresh token to be configured as a one time use value. 

In preparation for OAuth 2.1, we could allow configuration to allow only one time refresh tokens or optionally sign them using mutual TLS or OAuth token binding. 

https://fusionauth.io/blog/2020/04/15/whats-new-in-oauth-2-1

### Related Issues
[Refresh Token Rotation Issue #394](https://github.com/FusionAuth/fusionauth-issues/issues/394)

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This was delivered in milestone 1.17.0 under issue https://github.com/FusionAuth/fusionauth-issues/issues/394. 

The feature allows you to configure a refresh token usage policy and select one time use, or re-use.
