### ISSUE TITLE
Logs can fill up disk

### ISSUE THREAD

**Issue by oottinger** [FusionAuth/fusionauth-issues#575]
### Description
I notice from time to time that the logs directory will consume a significant amount of space in my development environment.  This usually seems to occur when i do a `brew upgrade` on Mac and forget to stop the previous services.  This part I can do better to manage.

Is there support for limiting log file size or performing log rotation?  I don't see any setting in the administration portal to configure this.

**Comment by robotdan** [comment]
Related issue: https://github.com/FusionAuth/fusionauth-issues/issues/372

**Comment by robotdan** [comment]
New logging strategy slated for 1.19.0. The updated logback config and docker logging strategy should satisfy this requirement.

**Comment by voidmain** [comment]
Version 1.19.0 now uses a log rotate strategy by default. It will only write to the fusionauth-app.log file until that is 100MB. After which, that file is rolled. There are a total of 10 rolls. Once the files are Gzipped, it is likely that they will only take up 200-300MB total disk space.
