### ISSUE TITLE
Create terraform provider for FusionAuth

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#576]
### Problem
It would be nice to manage FusionAuth configuration with an industry standard IaC tool.

### Solution
Create a custom provider: https://www.terraform.io/docs/extend/writing-custom-providers.html

### Alternatives/workarounds
You can get partway with the kickstart: https://fusionauth.io/docs/v1/tech/installation-guide/kickstart . See also https://github.com/FusionAuth/fusionauth-issues/issues/560 for another way to approach this with kickstarts. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by voidmain** [comment]
We have TF files for FusionAuth being deployed into AWS currently. However, they use our internal Chef scripts to configure the EC2 instances. We could start from those files and tweak them to not use Chef.

**Comment by mooreds** [comment]
I was thinking of something a bit different. Not so much for setting up FusionAuth (which is what the chef recipes are for, I believe), but for managing it. 

For instance, you could use Terraform to add or remove groups or applications. An example of what I was thinking was the Auth0 terraform provider: https://www.terraform.io/docs/providers/auth0/index.html

This would integrate nicely into companies who already manage their infrastructure with Terraform, as they could use the same change control procedures.

**Comment by voidmain** [comment]
Ah. That makes sense and seems like a great idea.

**Comment by hongkongkiwi** [comment]
I would also like this!

**Comment by robotdan** [comment]
We have a client that has built a provider, and they are working to open source it. Stay tuned.

**Comment by robotdan** [comment]
https://github.com/gpsinsight/terraform-provider-fusionauth

**Comment by mooreds** [comment]
Closing this issue as this apache licensed provider is available now.

**Comment by MCBrandenburg** [comment]
Here is the provider link in the registry: https://registry.terraform.io/providers/gpsinsight/fusionauth/latest
