### ISSUE TITLE
fusionauth-app.zip not found while building docker file for version 1.16.0-RC.2

### ISSUE THREAD

**Issue by NikhilP97** [FusionAuth/fusionauth-issues#577]
### Description
I'm trying to install fusionauth using the docker file available [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile).
When I run the command `docker build -t fusionauth/fusionauth-app:latest .` ,
it throws an error saying,
`unzip:  cannot find zipfile directory in one of fusionauth-app.zip or
        fusionauth-app.zip.zip, and cannot find fusionauth-app.zip.ZIP, period.` 

### Steps to reproduce
1. Create Dockerfile from [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile)
2. Build the image by running this command `docker build -t fusionauth/fusionauth-app:latest .`
3. Steps 1 to 3 execute properly.
4. See an error in step 4.

### Expected behavior
All 12 steps should get executed properly and build the image.

### Screenshots
PFA the screenshot of the error
![Screenshot from 2020-04-23 21-50-01](https://user-images.githubusercontent.com/37612539/80123365-6e52a300-85ac-11ea-84bb-78f1eadcf284.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Ubuntu 18.04 LTS
 - Browser + version [chrome]

### Additional context
I did hard code the FUSIONAUTH_VERSION as '1.16.0-RC.2' and it still threw the same error

**Comment by NikhilP97** [comment]
Please note: I temporarily resolved this issue by changing the value of FUSIONAUTH_VERSION=1.16.0-RC.1

**Comment by tyduptyler13** [comment]
1.16.0-RC.2 hasn't been released yet and it is our policy to keep master ready for the next release. If you would like the docker file for any given release, check out the corresponding tag or see dockerhub for prebuilt images.

**Comment by NikhilP97** [comment]
@tyduptyler13 I also tried pulling the image for the version - [1.16.0-RC.2](https://hub.docker.com/layers/fusionauth/fusionauth-app/1.16.0-RC.1/images/sha256-38f4f8a9896a59225b6ae8ceb6fe8e6c330642123c00a577fa6e0c55777671c9?context=explore).
When I run it I get this error mentioned [here](https://github.com/FusionAuth/fusionauth-issues/issues/581). Could you please help me resolve this. I'm under a hard deadline and require to deploy fusionauth using docker

**Comment by NikhilP97** [comment]
@tyduptyler13 Thanks for changing the fusionauth version in the Dockerfile, closing this issue.
