### ISSUE TITLE
Unable to upload certificate with small number of key bits

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#578]
### Description 
I am unable to upload a certificate I created to FusionAuth if the key has only 512 bits.

### Steps to reproduce
1. Generate a key with only 512 bits: ` openssl req -x509 -newkey rsa:512 -keyout key.pem -out cert.pem -days 365`
2. Go to http://localhost:9011/admin/key/
3. Click on 'import certificate'
4. Screen remains gray.

Note that if you generate a key with 4096 bits, the upload works just fine.

### Expected behavior
Rather than the screen remaining gray and an error on the console, should tell the end user that the key is too small.

Also suggest updating the documentation: https://fusionauth.io/docs/v1/tech/apis/keys#import-a-key 

### Screenshots
![image](https://user-images.githubusercontent.com/91825/80124787-01a8bb80-854e-11ea-85ac-809c739f3996.png)

### Platform
Windows
FusionAuth 1.15.5
FireFox 75.0 and Chrome 81.0.4044.113

**Comment by robotdan** [comment]
This is not a supported key size for FusionAuth. Perhaps the JavaScript is not handling the validation error.

**Comment by mooreds** [comment]
I think the js received a 500 error from the server. 

I see the key length as a API parameter here: https://fusionauth.io/docs/v1/tech/apis/keys but no docs about the limits.
