### ISSUE TITLE
fusionauth/fusionauth-java, repository does not exist while doing docker build

### ISSUE THREAD

**Issue by NikhilP97** [FusionAuth/fusionauth-issues#579]
### Description 
I'm trying to install fusionauth using the docker file available [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile).
When I run the command `docker build -t fusionauth/fusionauth-app:latest .` ,
it throws an error saying,
`unzip:  cannot find zipfile directory in one of fusionauth-app.zip or
        fusionauth-app.zip.zip, and cannot find fusionauth-app.zip.ZIP, period.` 

### Steps to reproduce
1. Create Dockerfile from [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile)
2. Build the image by running this command `docker build -t fusionauth/fusionauth-app:latest .`
3. Steps 1 to 4 execute properly.
4. See an error in step 5.

### Expected behavior
All 12 steps should get executed properly and build the image.

### Screenshots
PFA the screenshot of the error.
![Screenshot from 2020-04-23 21-59-27](https://user-images.githubusercontent.com/37612539/80124333-c1792580-85ad-11ea-8c93-3ee0681a3603.png)

### Platform
- Device: Desktop
- OS: Ubuntu 18.04 LTS
- Browser + version [chrome]

### Additional context
I temporarily resolved this issue by downloading the Dockerfile from [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-java/Dockerfile). Build the image on my PC and pushed it to[ docker hub](https://hub.docker.com/repository/docker/nikhiljpinto/fusionauth-java). I then edited the fusionauth-app dockerfile and ran it. Finally, it built the image. Please find below the updated Dockerfile

[Dockerfile.txt](https://github.com/FusionAuth/fusionauth-issues/files/4523922/Dockerfile.txt)

**Comment by tyduptyler13** [comment]
Hi,

We decided to avoid deploying our java image to dockerhub as it is custom tailored to run only FusionAuth (we stripped out much of the standard library that we weren't using to minimize our docker image size). In order to avoid confusion it made sense to make that a local image only.

As for not being able to find the zip, see #577

**Comment by NikhilP97** [comment]
@tyduptyler13 Okay got it. So from what I understand, we do not need this line 

> FROM fusionauth/fusionauth-java:14-jdk-alpine3.11.5

in the fusionauth-app [docker file](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile) right? 

About the zip file, I've noticed you changed the version, thank you!

**Comment by tyduptyler13** [comment]
You still need the java image, but you'll have to build it yourself. The java image is available in the same repo under `docker/fusionauth/fusionauth-java`.

I would recommend just using the images we publish to dockerhub though because it has the java already built in.

**Comment by NikhilP97** [comment]
@tyduptyler13 I tried removing this line in the Dockerfile

> FROM fusionauth/fusionauth-java:14-jdk-alpine3.11.5

and tried to build it but it threw this error
![Screenshot from 2020-04-24 00-05-31](https://user-images.githubusercontent.com/37612539/80136472-5e908a00-85bf-11ea-938f-5b1847ec7e6c.png)

So I used my earlier solution by replacing that line with this

> FROM nikhiljpinto/fusionauth-java:v1

and it built and it's running perfectly. Thank you for your help!
Could you please look into this line and correct the Dockerfile

**Comment by robotdan** [comment]
No plan to modify our Docker files, you're welcome to use them - but your mileage may vary as they are intended to be used in our build processes. 

Thanks!
