### ISSUE TITLE
curl: not found error while doing docker run for fusionauth/fusionauth-app Dockerfile

### ISSUE THREAD

**Issue by NikhilP97** [FusionAuth/fusionauth-issues#581]
## When I try to run the fusionauth/fusionauth-app image it throws an error 

> /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh: /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: line 59: curl: not found

### Description 
After I'm trying to install fusionauth using the docker file available [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile).
After building the file on my PC when I try to run it using this command
`docker run -p 9011:9011 -it fusionauth/fusionauth-app`
it throws an error saying,
`/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh: /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: line 59: curl: not found` 

### Steps to reproduce
1. Create Dockerfile from [here](https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile)
2. Build the image by running this command `docker build -t fusionauth/fusionauth-app:latest .`
3. Run the image `docker run -p 9011:9011 -it fusionauth/fusionauth-app`
4. See an error

### Expected behavior
The fusionauth app should work on port 9011.

### Screenshots
PFA the screenshot error.
![Screenshot from 2020-04-23 22-20-23](https://user-images.githubusercontent.com/37612539/80126424-b378d400-85b0-11ea-9aec-a8d70a51db5e.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Ubuntu 18.04 LTS
 - Browser + version [chrome]

**Comment by tyduptyler13** [comment]
Hi,

The only place in setenv that uses curl is to download java. This means that that our skip java download environment variable wasn't present during setenv.

We intentionally kept curl out of the docker build in order to detect problems with the image as the image already contains the java image we want to use.

**Comment by NikhilP97** [comment]
@tyduptyler13 How do I resolve this issue, could you please give me some next steps to follow. Really appreciate the quick reply!

**Comment by tyduptyler13** [comment]
After looking at the dockerfile it appears we aren't setting the required variable. I will add this and prove that it works. (That variable didn't seem to make it out of the test dockerfile)

**Comment by tyduptyler13** [comment]
Added the missing variable. Thank you for reporting this.
