### ISSUE TITLE
API: Unhandled exception while creating membership for a non-existent group.

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#584]
### Description 
Unhandled exception occurs when an attempt is made on creating membership for a non-existent group via API.

### Steps to reproduce
1. Send API request to create user membership for non-existent group.
2. Observer unhandled exception in FusionAuth logs.

### Expected behavior
code 400 response with error description is returned.

### Platform
 - Device: Desktop
 - OS: 18.04.1-Ubuntu x64
 - Docker: 19.03.8, build afacb8b7f0
 - Image: fusionauth/fusionauth-app:1.15.8

### Additional context
```
curl -sX POST http://localhost:9011/api/group/member -H 'authorization: **REDACTED**' -H 'content-type: application/json' -d '{"members": {"2a850b94-68be-455c-986f-3ef4bef26106": [{}]}}' | jq                 
{
  "generalErrors": [
    {
      "code": "[Exception]",
      "message": "FusionAuth encountered an unexpected error. Please contact support for assistance."
    }
  ]
}
```

**Comment by andrewpai** [comment]
Closing, as this is no longer an issue with current versions of FusionAuth.
