### ISSUE TITLE
Postgres database and database user not created automatically with v1.16.0-RC.1

### ISSUE THREAD

**Issue by zadigus** [FusionAuth/fusionauth-issues#587]
### Description 
When I run fusionauth v1.15.8, the database and the database user are created automatically in my postgres server. My problem is that I cannot use v1.15.8, because I am not able to install elasticsearch. None of the installation procedures seem to be working. Therefore, because elasticsearch is optional with fusionauth v1.16.0-RC.1, I am trying to install that version. Unfortunately, I am getting the following logs:

[logs-from-chart-in-fusionauth-chart-5bc477b676-dzm87.txt](https://github.com/FusionAuth/fusionauth-issues/files/4533338/logs-from-chart-in-fusionauth-chart-5bc477b676-dzm87.txt)

Of particular importance is the line
```
Apr 25, 2020 3:18:15.459 PM INFO  io.fusionauth.app.maintenance.FusionAuthMaintenanceModeWorkflow - Determine database status : ORDINARY_USER_CANNOT_CONNECT [FATAL: password authentication failed for user "auth"]
```
The user does not exist yet in the database, for that reason it can't login. It works perfectly with version v1.15.8 ! With that version, I must just provide my database hostname and fusionauth creates the necessary user and database.

Maybe I have to create all that beforehand with the new fusionauth version. In that case, where is it documented how I should create the relevant database?

### Steps to reproduce

1. Deploy fusionauth 1.16.0-RC.1 docker image with the database credentials

### Expected behavior

The database and the database user are created by fusionauth.

### Platform
 - Device: kubernetes cluster
 - OS: fusionauth docker image

**Comment by robotdan** [comment]
This is an old ticket. Please re-open if you can recreate on a recent version.
