### ISSUE TITLE
Elastricsearch 7.6.2 Types Error

### ISSUE THREAD

**Issue by firrae** [FusionAuth/fusionauth-issues#589]
### Description 
It seems FusionAuth does sends user search queries to Elasticsearch with "types" leading to Elasticsearch returning an error and no results.

### Steps to reproduce
1. Start a ES 7.6.2 server
2. Start an instance of FusionAuth without FA-Search
3. Connect the 2 in the initial setup (this will work fine)
4. Open the "Users" page
5. See uninformative error modal on screen (error is in logs though)

### Expected behavior
The query should return a list of users.

### Platform
 - Device: All?
 - OS: FA server OS is CentOS 8, Elasticsearch OS is CentOS 7
 - Chrome 81

### Additional context
I haven't had a chance to run this with a non-latest (current) release at this point as it took a bit to find the root cause as I thought I messed up my ES install twice, but it seems it was likely this. Using FA-Search works fine, but I'd prefer to use a full ES node/cluster to allow my apps to use it as well.

![image](https://user-images.githubusercontent.com/6454839/80299962-b0274900-8766-11ea-82d7-c7acc53a3fd8.png)

**Comment by robotdan** [comment]
We should be modifying that query based upon the version of Elasticsearch. We must think we are connected to version 6. 

What is the output of a `curl` command to `/` on your elasticsearch service? 

For example :


```
> curl http://localhost:9021/               
{
  ... 
  "version" : {
    "number" : "7.6.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "aa751e09be0a5072e8570670309b1f12348f023b",
    "build_date" : "2020-02-29T00:15:25.529771Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Also, have you tried re-building the index? In the UI System > Reindex.

**Comment by firrae** [comment]
The result I get is:
```
curl http://192.168.2.20:9200                                                                                                                                                              took  22s  2.3.0 at  23:06:48
{
  "name" : "localhost.localdomain",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "VcghSbyxT1uJ_U55hpE4ug",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by trex** [comment]
@firrae What version of FusionAuth are you running?

**Comment by firrae** [comment]
Sorry for the delay, things got hectic around here.

@trex I was using the version provided by the Linux RPM install script here: https://fusionauth.io/docs/v1/tech/5-minute-setup-guide as it was 16 days ago. I haven't had a chance to try again since then.

**Comment by trex** [comment]
@firrae can you please pull the latest fusionauth-app Docker image?
```
docker pull fusionauth/fusionauth-app
```

FusionAuth versions `> 1.16.0` are compatible with Elasticsearch `7.6.x` and you may have been running with an older image.

**Comment by firrae** [comment]
@trex I can try it this weekend maybe. I'm flat out on most other fronts currently. Also I was gonna try the newest version anyways due to it no longer requiring Elasticsearch so that might have just invalidated my need for this ticket, but I'll see if I can update to at least verify.

**Comment by trex** [comment]
Sounds good @firrae.  Please let me know how it goes.

**Comment by firrae** [comment]
It seems fine now. Sorry for the delay. I'll likely play with it more in the future, I'm just flat out at the moment.

**Comment by robotdan** [comment]
Looks like this one is resolved, please re-open if there is still something that needs attention. Thanks!
