### ISSUE TITLE
Using a access token for a lock account

### ISSUE THREAD

**Issue by StanislavKD** [FusionAuth/fusionauth-issues#59]
### Description 
I use oauth2 client for user authentication in the fusionauth. I receive a token for the user. I make a request in userinfo using curl. All is well. Then in the UI fusionauth (through another user and browser) I lock the first user (and change his password). But nothing changes in his session, he can still get a new assess token and he can still make a request in userinfo. In UI fusionauth, I see all the new logins in the recent logins section. Is there a mechanism for managing user sessions through the UI (in the session section there can only be refresh tokens)? Is it possible to terminate a user session if the login / password or token is compromised? Thank you for your help.

**Comment by robotdan** [comment]
Hi @StanislavKD 

Thanks for taking the time to describe your issue. 

> Is there a mechanism for managing user sessions through the UI (in the session section there can only be refresh tokens)?

The 'Sessions' in the Manage User UI is a refresh token, there is not currently a way to directly manage the HTTP sessions that exist to support SSO in FusionAuth. 

> Is it possible to terminate a user session if the login / password or token is compromised? 

This is not currently possible in the FusionAuth UI. 

I'll review the current behavior and follow up with you to let you know if I can provide a recommended approach, or if we modify the current design to better support this scenario. 

Thanks!

**Comment by StanislavKD** [comment]
Hello @robotdan.
Thank you for your reply. I think that it can be solved by oauth2 client (with offline mode). In the oauth2 client after authenticating the user, insert user's refresh/access token and date of the expiration of the access token into the sql database. When a access token has expired, make a request to the fusionauth to obtain new refresh and access tokens using the refresh token from sql. If everything is good in the fusionauth (the refresh token is not revoked and the user is not locked), then a new pair of tokens is issued. Not sure that it is a correct and beautiful solution (to store the refresh token), but it should work. P.S. I could not find a single sign-on mechanism in the documentation on fusionauth.io. Is it possible to organize this through api or your client libraries (via the fusionauth authorization page without using third-party oauth2 libraries)? Thanks again for the help. Happy New Year holidays.

**Comment by robotdan** [comment]
Here are the use cases I can think of off the top of my head:

1. User logs into SSO, user is soft deleted (deactivated), SSO session will be invalidated
2. User logs into SSO, user is expired, SSO session will be invalidated
3. User logs into SSO, user is actioned that prevents login, session will be invalidated
4. User logs into SSO, changes password (or admin changes password of the user), session will be invalidated.

**Comment by robotdan** [comment]
Fixed in version 1.4.0.
https://fusionauth.io/docs/v1/tech/release-notes/
