### ISSUE TITLE
ftl templates need the client_id and possibly other variables

### ISSUE THREAD

**Issue by gordody** [FusionAuth/fusionauth-issues#591]
### Problem
Often it becomes necessary to direct the user back to the original login page or the application where the login started.
Use cases:
- Remembered Password
- Expired Password Reset code - need to got back to Login Page resend email
- Expired Registration code - need to got back to Login Page resend email

### Solution
If the client_id is available, it's possible to navigate back to the "Authorize" page. 

If the page addresses are available in variables, the links can be properly filled out, for example going from Forgot password to Authorize is not trivial given that forgot password is under /password/forgot and authorize is under /oauth2/authorize (and it might change)

### Alternatives/workarounds
Hard code variable names and paths, put variables in LocalStore and cookies on the login page, store things in `state`.

**Comment by robotdan** [comment]
The `client_id` and corresponding `application` or `application.id` should always be available in the templates. 
Please re-open if this is not the case for any pages.
