### ISSUE TITLE
Implement registration_endpoint in .well-known/openid-configuration

### ISSUE THREAD

**Issue by gordody** [FusionAuth/fusionauth-issues#592]
### Problem
If a backend needs to direct to the correct endpoint based on a url parameter, currently it either replaces the /oauth2/authorize with /oauth2/register or we redirect in /oauth2/authorize.

### Solution
Implement registration_endpoint in .well-known/openid-configuration and point it to /oauth2/register

### Alternatives/workarounds
String replace /oauth2/authorize with /oauth2/register

**Comment by robotdan** [comment]
I don't know that the OIDC spec outlines this type of endpoint. The `registration_endpoint` found in the OIDC discovery spec is for dynamic client registration. This allows a relying party to perform dynamic registration. 



> https://openid.net/specs/openid-connect-discovery-1_0.html
> 
> registration_endpoint
>   * RECOMMENDED. URL of the OP's Dynamic Client Registration Endpoint [OpenID.Registration].
> 
> https://openid.net/specs/openid-connect-registration-1_0.html

I believe what you're looking for is is the end user registration endpoint.  In the case of FusionAuth, `/oauth2/register`.
