### ISSUE TITLE
Docker image tagging strategy: `latest` tag should only be used for latest stable releases

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#596]
## Docker image tagging strategy: `latest` tag should only be used for latest stable releases

Pre-release versions may contain unresolved bugs, e.g. https://github.com/FusionAuth/fusionauth-issues/issues/595 . While depending on `latest` always has risks (and therefore need periodic backup etc. to mitigate), having latest only point to stable release significantly reduces this risk for users.

### Description
Per comment by @robotdan in https://github.com/FusionAuth/fusionauth-issues/issues/563#issuecomment-622023986 , `latest` should only be used for latest stable releases.

If pre-release versions are needed, we can use `develop` tag.

**Comment by robotdan** [comment]
Thanks for opening this issue @ceefour .
