### ISSUE TITLE
Enhancement: Make the Elasticsearch index update during authentication completely async

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#599]
### Description
If Elasticsearch is having perform issues of some sort it can cause login to be slow. If Elasticsearch is down all together it can cause a login to take up to 30 seconds perhaps. It is likely this length of the time is the connection timeout to the Elasticsearch service. 

Original description:
> We're experiencing some really slow logins and we've found out that its because the`PUT` call to elasticsearch, during a user authentication on fusionauth, is delaying the login process. And in the event of elasticsearch being down the login process takes 30s which I imagine is your timeout for the `PUT` call .

### Solutions

During the authentication code path, the request to Elasticsearch to update the index could be made entirely async in a separate process. 

### Comments & Background

We do something similar to this during authentication to record the login record. We place the login record on a queue and it is handled asynchronously by another job. The problem with doing this with Elasticsearch is that we need most of the user object to index and keeping all of this in memory is a risk for heap explosion. 

And in general we have assumed Elasticsearch to be another data store, just like a relational database. If we view it in this context, then Elasticsearch is critical to operation and it must be running and operational to function. 

Taking all possible steps to ensure login completes fast and correct is paramount, but there is a line at which point we must have underlying infrastructure available to function properly. Specifically the PostgreSQL or MySQL relational database, and Elasticsearch if configured. 

### Risks
If Elasticsearch is down and we queue up the change, we'll have to toss it eventually if Elasticsearch does not come back online. This means we have a risk of the search index being out of sync. This is not a huge risk in that the source of truth is the database and we can always re-index, or upon next login, or touch we will re-index the user anyway. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
We can review this suggestion, we would like to move this to be completely async.

If Elasticsearch is working well and sized appropriately I would not expect this to elongate the authentication request noticeably. 


What type of login times are you seeing?

**Comment by johnmaia** [comment]
Sorry for the long delay.

So, we had our Elasticsearch engine a bit unstable and during that period one in every five login requests took around four to five seconds. If the Elasticsearch crashed the logins would take 30 seconds (as I mentioned above, the supposed timeout).

With the Elasticsearch running without any issues the login requests are fairly fast.

Nonetheless, If the call to the Elasticsearch engine was asynchronous we wouldn't experience any delay on the login requests.

**Comment by robotdan** [comment]
Thanks for the additional info @johnmaia . I'll convert this to an enhancement request to make the Elasticsearch index request completely async the authentication path.

**Comment by robotdan** [comment]
Forgot we had this one open, but we did do this. I believe in version 1.30.2. 
https://fusionauth.io/docs/v1/tech/release-notes#version-1-30-2

@johnmaia  I'll close this out, but re-open if you see any issues after upgrading to 1.30.2 or later.
