### ISSUE TITLE
Username field can't be reliably queried using the query param against the User Search resource

### ISSUE THREAD

**Issue by patrickvalle** [FusionAuth/fusionauth-issues#602]
### Description
FusionAuth allows for usernames with spaces, but the `username` field is setup in ElasticSearch as a `text` field using the standard analyzer. In short, [the standard analyzer tokenizes strings using the space character](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html).

This means that I can add a user with the username **tiger king** into the system, but I won't be able to do any exact match lookups of **tiger king** using the `query` param as documented in the [User Search API docs](https://fusionauth.io/docs/v1/tech/apis/users#search-for-users).

Is this an intentional decision? What's a prescribed, reliable way for developers to look up multiple users via the `username`?

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/712
- https://github.com/FusionAuth/fusionauth-issues/issues/2455

**Comment by trex** [comment]
@patrickvalle that is correct, given that the `username` field is mapped as a `text` field, the `username` field cannot reliably be matched.

Therefor a query string `username:'tiger king'` may return users with the username **tiger king** and **tiger kong** (and other close matches).

Under the current mapping, you would need to make your search request by username to the User Search API, then filter the results in a post-processing operation.

**Comment by patrickvalle-transloc** [comment]
Thanks for the timely answer @trex, that is helpful information. Does this seem like something that would be changed at some point in the future (in order to support exact matches)? I say this out of ignorance, but it _feels_ like the username _should_ allow for exact matching.

**Comment by robotdan** [comment]
I think you guys are correct, it seems like we should support exact match on this field. 


Does this query work for you? `username:"tiger king"` (instead of `username:'tiger king'`)

We'll need to do some additional investigation on our end if that is not working for you. 

For now you could optionally use the User API and retrieve by Login Id which would allow for an exact match lookup by email or username. 

Or write a more sophisticated query like `username:'tiger king' AND username:'tiger' AND username:'king'`.

**Comment by robotdan** [comment]
Under this issue https://github.com/FusionAuth/fusionauth-issues/issues/2455 - we'll be adding a sub field for `username` to do exact matching.

**Comment by andrewpai** [comment]
Note that in 1.49.0, we will support username.exact and fullName.exact fields for more precise searching of these properties.
