### ISSUE TITLE
Add a C++ client library

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#603]
### Problem
C++ is a popular language, by some measures top 10: https://redmonk.com/sogrady/2020/02/28/language-rankings-1-20/

### Solution
It'd be nice to have a C++ client library.

### Alternatives/workarounds
Using an API library like https://github.com/jgaa/restc-cpp against the FusionAuth API: https://fusionauth.io/docs/v1/tech/apis/

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

If you would like to see a C++ client library, in addition to adding a thumbs up, please comment with your use case how you would intend to use a C++ client library for the FusionAuth APIs.

**Comment by bditt** [comment]
Any update on this? Could really use a good C++ library for this.

**Comment by mooreds** [comment]
@bditt No progress, but thanks for voting on this! We'd welcome a contribution. If you want to learn more about that, here's a relevant comment: https://github.com/FusionAuth/fusionauth-issues/issues/974#issuecomment-723232482

**Comment by bditt** [comment]
I see, sadly not very confident in my ability to do this, so I'll just continue waiting until a C++ library comes out. That way I can stop using Auth.gg.

**Comment by mooreds** [comment]
At this time you should use the OpenAPI spec and tooling to generate a C++ SDK.

https://github.com/FusionAuth/fusionauth-openapi
