### ISSUE TITLE
Bulk Addition of Users

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [FusionAuth/fusionauth-issues#609]
### Problem
Is there a way to add users in Bulk?

### Solution
An excel / csv based upload to create users will help
Alternatively, a curl command to create a user

**Comment by trex** [comment]
@VinayaSathyanarayana You may use the [Import Users API](https://fusionauth.io/docs/v1/tech/apis/users#import-users) to bulk import users.

There are a couple of reference example scripts in our https://github.com/FusionAuth/fusionauth-import-scripts repository that you can use as a starting point.  Please feel free to make a PR to this repository to add our import script if you think it could be useful for others!

**Comment by trex** [comment]
I have copied this thread over to the [FusionAuth Community Forum](https://fusionauth.io/community/forum/) so that we may preserve it and make it easily searchable for other users.  You may find it here https://fusionauth.io/community/forum/topic/58/is-there-a-way-to-add-users-in-bulk
