### ISSUE TITLE
Feature: Support custom claims in the JWT

### ISSUE THREAD

**Issue by jakobrosenberg** [FusionAuth/fusionauth-issues#61]
## Original Request
> How do I add a custom claim to the JWT?

### Problem
For many reasons users will want to encode custom claims into the JWT issued by FusionAuth. 

#### Example: Integration with Hasura
  https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html
  This integration requires some specific claims name spaced under `https://hasura.io/jwt/claims` -see example below:

```
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  }
}
```

### Solution
Allow configuration to add custom claims, optionally name-spaced - most likely per application configuration will be required. 

### Alternatives/workarounds
None.

### Additional context
The OpenID Connect spec defines a common set of claims but users will always have unique use cases or one-off requirements. 

We may also wish to allow registered claims to be enabled / disabled. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Hi @jakobrosenberg currently we do not support adding custom claims to the JWT that is issued by FusionAuth. 

This feature is on the roadmap. 

Is there a particular claim you're looking for? Perhaps I can recommend an alternate strategy or temporary work around for you. 

Thanks.

**Comment by jakobrosenberg** [comment]
Hi @robotdan. Thanks for your interest.

I'm looking to use Fusionauth with Hasura. So far I haven't had much luck. Hasura requires certain claims to be present in the JWT. An alternative might be a webhook instead. Would that cause more roundtrips? 

Example JWT claim
https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html
```json
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  }
}
```

**Comment by robotdan** [comment]
Thanks for the additional info, that is helpful. 

If I'm reading the Hasura doc correctly, the JWT must have these Hasura specific claims in the namespace `https://hasura.io/jwt/claims` - this is not currently possible with FusionAuth.

Adding custom claims will be fairly straight forward, however we are still working on the best way to allow the end user to configure this through the user interface. 

I'll change this issue to a Feature Request so we can get this into plan so allow FusionAuth to be compatible with Hasura. 

Thanks for taking the time to contact us.

**Comment by davidb-e4s** [comment]
Adding my 2 pence.

My use case is inputing part of the UserData object into the JWT as a custom claim (Not the whole thing) Currently I use spring security and have to do calls to get the information I need which isn't ideal. I can do some local caching etc but we run microservices so it's still quite limited. I could do a distributed cache etc but it's another point of failure from a critical path!

Auth0 offer this functionality (which is what we are switching from). I use an ID I store in the userdata as part of every database call I do so it's required pretty much all the time (We have a multi-tenant system) (not tenant like FA tenants).

**Comment by robotdan** [comment]
Thanks for that additional information @davidb-e4s . If you want to send me a note we can discuss your use case further so I can potentially offer you a timeline. ( daniel | at | fusionauth | io )

**Comment by colundrum** [comment]
Hello

I'm in the same situation with Hasura and JWT

> If I'm reading the Hasura doc correctly, the JWT must have these Hasura specific claims in the namespace `https://hasura.io/jwt/claims` - this is not currently possible with FusionAuth.

In reality, it's possible to configure the namespace : https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#claims-namespace

I hope to see this new feature soon ;)

Do you build test package (deb/rpm) ?

Regards

**Comment by robotdan** [comment]
Hi @colundrum - this will be out in `1.6.0`.  Hopefully early this week - this feature is code complete, but the release has been held up due to SAML IdP testing. :-( SAML sucks. 

> Do you build test package (deb/rpm) ?
 
We don't - we have discussed publishing release candidates, so that once particular features are ready we could provide early access.  This may come in the future.

**Comment by robotdan** [comment]
A little taste...  https://twitter.com/robotdan220/status/1120719050764455937

**Comment by robotdan** [comment]
This should be available in 1.6.0. The doc is coming shortly. 
https://fusionauth.io/docs/v1/tech/lambdas/jwt-populate

I should also be able to provide you an example here for your use case with Hasura if that is helpful. Let me know.

**Comment by robotdan** [comment]
@jakobrosenberg and @colundrum were you able to get this to work with Hasura using the Lambda?

**Comment by nraibaud** [comment]
Hi,
I called FusionAuth api/login, the token checked from jwt.io does not contains :

```
jwt["https://hasura.io/jwt/claims"] = {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  };

```

The lambda is not called.
But if i use FUSION AUTH by a third party using OAUTH2, the lambda is called.

1) Is the lambda working for API LOGIN?
2) Is there another issue like the jwt object modified from the lambda is the one that is a returned to create the JWT and not a cloned one.

**Comment by robotdan** [comment]
How are you calling the Login API? If you omit the `applicationId` parameter, it will not execute the Lambda because the Lambda is application specific. 

https://fusionauth.io/docs/v1/tech/apis/login

```
{
  "loginId": "example@fusionauth.io",
  "password": "password",
  "applicationId": "10000000-0000-0002-0000-000000000001"
}
```

If you are passing an `applicationId` on the Login API, the Lambda should be executed. Also ensure the Lambda is configured the application in question. See the `JWT` tab in the application configuration, and ensure the lambda is selected for the correct token.

If you're doing all of that and it still does not seem to be executed, check the event log, and let me know if you see anything there. `System --> Event Log`.

**Comment by nraibaud** [comment]
Hi @robotdan ,
I used the REST API 

1) the applicationId is correctly passed
2) the applicationId is the good one.
3) the applicationId and lambda is correctly assigned in fusion auth
4) Event log show datas! when i pressed reset, it was not there... COOL

But hazura say that the bearer does not contains claims informations.

**Comment by robotdan** [comment]
To clarify, was there an exception in the event log? 

Can you attach a screenshot of your application JWT configuration screen, and the lambda function you've defined?

**Comment by nraibaud** [comment]
@robotdan 

![image](https://user-images.githubusercontent.com/2615311/57898153-2aadd000-7858-11e9-9772-2aedb08255b0.png)
![image](https://user-images.githubusercontent.com/2615311/57898158-313c4780-7858-11e9-8f6a-9f9ef98fd1e2.png)

**Comment by robotdan** [comment]
Can you send the actual Lambda function you coded, I'll try to recreate.

**Comment by nraibaud** [comment]
`// Using the user and registration parameters add additional values to the jwt object.
function populate(jwt, user, registration) {
  //  When writing a lambda we've added a few helpers to make life easier.
  //  console.info('Hello World');         # This will create an EventLog of type Information
  //  console.error('Not good.');          # This will create an EventLog of type Error
  //  console.debug('Step 42 completed.'); # This will create an EventLog of type Debug
  //  
  //  To dump an entire object to the EventLog you can use JSON.stringify, for example: 
  //  console.info(JSON.stringify(user)); 

  // Happy coding! Populate your JWT here.
  
  jwt["https://hasura.io/jwt/claims"] = {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": user.id,
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  };
  console.log(JSON.stringify(jwt));
  console.log(JSON.stringify(user));
}`

**Comment by nraibaud** [comment]
@robotdan just to precise, on my jwt log, i can see jwt["https://hasura.io/jwt/claims"]

**Comment by robotdan** [comment]
Ok, thanks. I'll see if I can recreate.

**Comment by robotdan** [comment]
So I haven't been able to recreate yet. 

Here is my Lambda:

```
function populate(jwt, user, registration) {
 jwt["https://hasura.io/jwt/claims"] = {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": user.id,
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  };
  console.log(JSON.stringify(jwt, null, 2));
  console.log(JSON.stringify(user, null, 2));
}
```

These `console.log` statements will produce an event log which contains the following output:

```
Lambda invocation result.

Id: 41d0f7a9-bf3e-4304-9120-40899529acb0
Name: test

{
  "authenticationType": "PASSWORD",
  "email": "admin@fusionauth.io",
  "email_verified": true,
  "exp": 1558070199,
  "iat": 1558066599,
  "iss": "acme.com",
  "sub": "3666fa9e-a08b-47dc-aa19-149112aa59f1",
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "editor",
      "user",
      "mod"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "3666fa9e-a08b-47dc-aa19-149112aa59f1",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  }
}


{
  "active": true,
  "email": "admin@fusionauth.io",
  "id": "3666fa9e-a08b-47dc-aa19-149112aa59f1",
  "insertInstant": 1557788563564,
  "lastLoginInstant": 1558066440805,
  "passwordChangeRequired": false,
  "passwordLastUpdateInstant": 1557788563649,
  "registrations": [
    {
      "applicationId": "3c219e58-ed0e-4b18-ad48-f4f92793ae32",
      "id": "5958e0bc-6928-4582-9edc-16cad1cb2968",
      "insertInstant": 1557788563763,
      "lastLoginInstant": 1558066440805,
      "roles": [
        "admin"
      ],
      "usernameStatus": "ACTIVE",
      "verified": true
    }
  ],
  "tenantId": "30393163-3665-3331-6363-636535386536",
  "twoFactorDelivery": "None",
  "twoFactorEnabled": false,
  "usernameStatus": "ACTIVE",
  "verified": true
}
```

Then the following JWT is produced by calling the Login API:


```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijg3ZmMwYjNiNTQifQ.eyJhdWQiOiI0ZGIxOTg3ZC1lOGEyLTRkYzktOTljNS00OWFkYTkxZGU3MjYiLCJleHAiOjE1NTgwNzEzMDAsImlhdCI6MTU1ODA2NzcwMCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiIzNjY2ZmE5ZS1hMDhiLTQ3ZGMtYWExOS0xNDkxMTJhYTU5ZjEiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoiYWRtaW5AZnVzaW9uYXV0aC5pbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhcHBsaWNhdGlvbklkIjoiNGRiMTk4N2QtZThhMi00ZGM5LTk5YzUtNDlhZGE5MWRlNzI2Iiwicm9sZXMiOltdLCJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsiZWRpdG9yIiwidXNlciIsIm1vZCJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJ1c2VyIiwieC1oYXN1cmEtdXNlci1pZCI6IjM2NjZmYTllLWEwOGItNDdkYy1hYTE5LTE0OTExMmFhNTlmMSIsIngtaGFzdXJhLW9yZy1pZCI6IjEyMyIsIngtaGFzdXJhLWN1c3RvbSI6ImN1c3RvbS12YWx1ZSJ9fQ.hyWsmeOlraQOIUYS0Z3vp9__Ok6W_tYRiqCo2RyU8S4
```

This JWT decoded contains the following JSON body

```
{
  "aud": "4db1987d-e8a2-4dc9-99c5-49ada91de726",
  "exp": 1558071300,
  "iat": 1558067700,
  "iss": "acme.com",
  "sub": "3666fa9e-a08b-47dc-aa19-149112aa59f1",
  "authenticationType": "PASSWORD",
  "email": "admin@fusionauth.io",
  "email_verified": true,
  "applicationId": "4db1987d-e8a2-4dc9-99c5-49ada91de726",
  "roles": [],
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "editor",
      "user",
      "mod"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "3666fa9e-a08b-47dc-aa19-149112aa59f1",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  }
}
```

![image](https://user-images.githubusercontent.com/1148709/57903539-b2c9b080-782b-11e9-9678-b6c1cc13f2ce.png)


Are there any other details you can provide that may help me recreate your symptoms?

**Comment by nraibaud** [comment]
@robotdan oh.. it works!
Many thanks...
But the lambda should be applied to ID for JWT no?

**Comment by robotdan** [comment]
The Id Token is part of the OpenID Connect spec, so it will only be returned by an OAuth2 grant when the `openid` scope is requested. 

The Login API is separate from the OAuth2 grants, this API only returns an access token (JWT). 

So, you can certainly apply the lambda to either the id token or access token, but you'll only receive an access token on the Login API. If you were to use the OAuth2 Password Grant with the `openid` scope, you'll receive an access token and id token in the response. 

Hope that helps!

**Comment by davidb-e4s** [comment]
Thank you so much for rolling this feature out guys it's made my life a lot easier and reduced a bunch of complexity in our code. Simple to use and works perfectly. FA continues to impress!!

**Comment by deividaspetraitis** [comment]
> 
> ![image](https://user-images.githubusercontent.com/1148709/57903539-b2c9b080-782b-11e9-9678-b6c1cc13f2ce.png)
> 
> Are there any other details you can provide that may help me recreate your symptoms?

It might useful to add somewhere in documentation about requirement to assign lambda to application since it is not noticed here: https://fusionauth.io/docs/v1/tech/lambdas/
Also I think I would be nice to have capability assign multiple lambdas.

**Comment by robotdan** [comment]
@deividaspetraitis thanks for the feedback. We'll add some text somewhere on that page to indicate this requirement. 

https://fusionauth.io/docs/v1/tech/core-concepts/applications#jwt

**Comment by robotdan** [comment]
Added a section called `Assigning the lambda` to the JWT Populate doc. 
https://fusionauth.io/docs/v1/tech/lambdas/jwt-populate
