### ISSUE TITLE
Open ID connect with google is failing

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#616]
### Description 
fusion auth is failing to login with google open id connect with following error.
fusionauth_1  | May 09, 2020 1:43:19.057 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
fusionauth_1  | org.primeframework.mvc.parameter.el.MissingPropertyExpressionException: While evaluating the expression [prompt]. The property/field [prompt] does not exist in the class [class io.fusionauth.app.action.oauth2.CallbackAction]
fusionauth_1  | 	at org.primeframework.mvc.parameter.el.MemberAccessor.<init>(MemberAccessor.java:84)
fusionauth_1  | 	at org.primeframework.mvc.parameter.el.Expression.next(Expression.java:147)
fusionauth_1  | 	at org.primeframework.mvc.parameter.el.Expression.traverseToEndForSet(Expression.java:113)
fusionauth_1  | 	at org.primeframework.mvc.parameter.el.DefaultExpressionEvaluator.setValue(DefaultExpressionEvaluator.java:131)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultParameterHandler.setValues(DefaultParameterHandler.java:201)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultParameterHandler.handle(DefaultParameterHandler.java:119)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:54)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:165)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:291)
fusionauth_1  | 	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:252)
fusionauth_1  | 	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:50)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
fusionauth_1  | 	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
fusionauth_1  | 	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
fusionauth_1  | 	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:82)
fusionauth_1  | 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
fusionauth_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
fusionauth_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
fusionauth_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
fusionauth_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
fusionauth_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
fusionauth_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
fusionauth_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
fusionauth_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
fusionauth_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
fusionauth_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
fusionauth_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
fusionauth_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
fusionauth_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
fusionauth_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
fusionauth_1  | 	at java.base/java.lang.Thread.run(Thread.java:832)

### Steps to reproduce
1. setup google open ID connect configuration
2. Login with google
3. see the error

### Expected behavior
Login with google should be successfully

**Comment by LohithBlaze** [comment]
Even when I use the google identity provider, with client ID and secret, after I login,  and the UI reloading, the login doesnt work out.

**Comment by robotdan** [comment]
Looks like a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/595.

**Comment by LohithBlaze** [comment]
Any work around for this.? Even the Google Auth identity provider is not working. After successfull authentication, the UI loads and doesn't login the user, it just stays in the same login page.

**Comment by robotdan** [comment]
Did you look at the linked issue? Are you running 1.16.0-RC.1?

**Comment by LohithBlaze** [comment]
yes, we are using 1.16.0-RC.1 version and still seeing this issue, trying to understand the google identity provider auth, in the documentation,  there is no mention of setting any redirect uri in the google oauth client api in fusionauth documentation, can you please mention what is the authorized redirect URI that we need to set in the google oauth2 client page for fusionauth to receive the access token once it is authenticated?
![export](https://user-images.githubusercontent.com/5206749/81527877-fbea0d00-9378-11ea-8701-0c4e537bf98f.png)

**Comment by LohithBlaze** [comment]
Here is the event log error message for google idp, 
Request to the [https://www.googleapis.com/oauth2/v3/tokeninfo] endpoint failed. Status code [-1]

Exception encountered.

javax.net.ssl.SSLHandshakeException : Message: Received fatal alert: handshake_failure

Seems like we needs https for google oauth to be successfull?

**Comment by mooreds** [comment]
You shouldn't need to set the Authorized Redirect URIs in the google cloud platform oauht2 client page. You do need to ensure that the authorized javascript origins value is set to the domain name of your client application. Make sure it includes both the protocol and the domain name: `https://www.piedpiper.com`. As I recall, the google UI for adding it is a bit unintuitive, so make sure it is set.

I'm sure you've seen this, but I'll link it for future readers: https://fusionauth.io/docs/v1/tech/identity-providers/google

**Comment by robotdan** [comment]
I think this is a duplicate , or rather this ( https://github.com/FusionAuth/fusionauth-issues/issues/621 and https://github.com/FusionAuth/fusionauth-issues/issues/617 ) are duplicates of this one. 

The docker image has been updated if you want to retry.

**Comment by LohithBlaze** [comment]
Thank you, its working!!!
