### ISSUE TITLE
1.16.0 kickstart does not recognise "https://accounts.google.com" as a valid url for OpenID Connect automatic discovery

### ISSUE THREAD

**Issue by arni-inaba** [FusionAuth/fusionauth-issues#621]
### Description 
When running the `fusionauth/fusionauth-app:1.16.0` docker image, my kickstart.json fails with a 400 response to a POST to `/api/identity-provider`.

The error response has the following error message:
> `"Invalid value for property [identityProvider.oauth2.issuer]. The value must be a valid URL and reachable by FusionAuth to resolve the OpenID Connect endpoints."`

The identity provider is defined as such in kickstart.json:

```json
{
      "method": "POST",
      "url": "/api/identity-provider",
      "body": {
        "identityProvider": {
          "applicationConfiguration": {
            "#{applicationId}": {
              "createRegistration": false,
              "enabled": true,
              "oauth2": {}
            },
            "#{FUSIONAUTH_APPLICATION_ID}": {
              "createRegistration": false,
              "enabled": true,
              "oauth2": {}
            }
          },
          "buttonImageURL": "/images/identityProviders/google.svg",
          "buttonText": "Login with Google",
          "debug": false,
          "enabled": true,
          "lambdaConfiguration": {},
          "name": "Google OpenID",
          "oauth2": {
            "clientAuthenticationMethod": "client_secret_basic",
            "client_id": "#{ENV.GOOGLE_CLIENT_ID}",
            "client_secret": "#{ENV.GOOGLE_CLIENT_SECRET}",
            "issuer": "https://accounts.google.com",
            "scope": "email profile openid"
          },
          "type": "OpenIDConnect"
        }
      }
    }
```

This configuration works fine in 1.15.8

As far as I can see, https://accounts.google.com/.well-known/openid-configuration is working correctly. When I point this url towards a dummy server, I can see the request in the access logs so it is clear that my FusionAuth container can access the internet.

### Steps to reproduce
1. Add the json blob above to kickstart.json (the existence of the env variables does not seem to matter)
2. Start the container
3. Tail the docker log

### Expected behavior
FusionAuth should be able to discover the Google endpoints.

### Platform
 - Docker for Desktop
 - OS: OS X
 - Browser: N/A 

### Additional context
Note: We're using the `OpenIDConnect` identity provider type instead of the `Google` type to avoid the pop-up window.

**Comment by robotdan** [comment]
This may actually be the same root issue as this one https://github.com/FusionAuth/fusionauth-issues/issues/617.

The problem I think is that we are slimming down the JDK in the docker image using `jlink` to remove un-needed modules in the JVM. The image was missing the `jdk.crypto.ec` module which is required to generate EC key pairs as noted in the linked issue, as well as establish a TLS connection to a URL such as `https://accounts.google.com/.well-known/openid-configuration`. 

I have updated the docker images, if you want to pull the latest image and attempt a recreate that would be great.

**Comment by arni-inaba** [comment]
I pulled `fusionauth/fusionauth-app:1.16.0` again and can confirm that it works now, thanks!

**Comment by robotdan** [comment]
Great, thanks for the update!
