### ISSUE TITLE
GUI: Locales input fields doesn't recognize any language other than English

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#622]
### Description 
Locales input fields (for eg. in user edit view) doesn't recognize any language other than English. Ie it won't display any other language, nor will it allow one to make an input other than English. The behavior is a regresion in 1.16 line - the feature worked fine in 1.15.

### Steps to reproduce
1. Go to any GUI view featuring locale input field, eg. user edit.
2. Try to input locale different than english.

### Expected behavior
All valid locales can be seen and set in the locale input fields.

### Screenshots
Both screenshots are taken with the same database state - other preferred languages present in the user details were inserted via API.

![Zrzut ekranu z 2020-05-11 20-12-17](https://user-images.githubusercontent.com/26625348/81599450-d684ef80-93c8-11ea-97aa-a2f2b942a961.png)

### Platform
 - Device: Desktop
 - OS: 18.04.2-Ubuntu x64
 - Docker: 19.03.8, build afacb8b7f0
 - Image: fusionauth/fusionauth-app:1.16.0

**Comment by robotdan** [comment]
Likely related to the Java we are building into Docker, will investigate.

**Comment by robotdan** [comment]
I can confirm it is related to the JDK packaged in the Docker image. We'll update the docker image shortly. Thanks for reporting.

**Comment by robotdan** [comment]
Related https://github.com/FusionAuth/fusionauth-issues/issues/617

**Comment by robotdan** [comment]
Docker images updated, the locale options should now come through. The Docker image was missing module `jdk.localedata`.

**Comment by mgetka** [comment]
The issue reappeared in 1.16.1.

**Comment by robotdan** [comment]
@mgetka thanks for letting us know. I believe I've resolved the issue, and updated the 1.16.1 Docker images.
