### ISSUE TITLE
Error missing_redirect_uri when switching languages using DomainBasedIdentityProvider

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-issues#623]
### Description 
When a domain based identity Provider is enabled and non-matching email address is used to login the locale selector will fail on the next (password) page.

### Steps to reproduce
1. Enable an Identity Provider with a domain name selector.
2. Add a second locale to the theme.
3. Go to the FA login page and enter an email address that is NOT in the domain.
4. Switch the language on the next page where you are supposed to enter your password.
5. See error `missing_redirect_uri`

### Expected behavior
The languages should be changed, nothing else. It seems that all localeSelector javascript is relying too much on the URL parameters that exist on all pages except the 2nd login page (authorize).

### Platform
 - Device: Desktop
 - OS: macOS
 - Chrome 81.0.4044.129, Firefox 76.0.1

**Comment by yrammos** [comment]
I think the bug is more generalized, occurring whenever authentication credentials are rejected for whatever reason.

**Comment by flangfeldt** [comment]
@yrammos , correct, I have seen this behavior also after getting an authentication error.

**Comment by robotdan** [comment]
I have a fix for this, plan to release it as part of 1.17.0.
