### ISSUE TITLE
Passwordless link in default email template doesn't work for a user with 2fa enabled

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#624]
### Description 
When using passwordless authentication, the default email template works fine. If you turn on 2fa, the following parameters are not passed along. 

### Steps to reproduce
1. Create an application
1. Turn on passwordless auth for the application
1. Create a user with an email address and password.
1. Associate a user with the new application
1. Set up a mail server using mailcatcher (unless you have mail set up already)
1. Start up a web server on port 3000 (if you don't have one running already)
1. Add the value `http://localhost:3000` to the authorized redirects for this application.
1. Open an incognito window.
1. Go to http://localhost:9011/oauth2/authorize?client_id=APPLICATION_CLIENT_ID&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000
1. Click on the 'Login with a magic link' button
1. Enter the new user's email address
1. Go to your mail client.
1. Click on the link
1. You are signed in. (this is the happy path)
1. Close the incognito window.
1. Turn on two factor authentication for the user ('edit user' in the user edit screen)
1. Capture the 2fa code in a tool like Google Authenticator
1. Open an incognito window.
1. Go to http://localhost:9011/oauth2/authorize?client_id=APPLICATION_CLIENT_ID&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000
1. Click on the 'Login with a magic link' button
1. Enter the new user's email address
1. Go to your mail client.
1. Click on the link
1. Enter your 2fa code

You see an error message:

```
{
  "error" : "invalid_request",
  "error_description" : "The request is missing a required parameter: redirect_uri",
  "error_reason" : "missing_redirect_uri"
}
```

### Expected behavior

You'd be logged in the same way with both paths.

Workaround: You can manually add the three parameters to the URL in the template and this works just fine.

### Platform
- Device: Desktop
- Windows
- Firefox
- FusionAuth 1.15.5

### Additional context

May not be that big an issue because the template is usually going be modified anyway, but wasn't sure if it should be documented.

**Comment by robotdan** [comment]
@bguyza it is possible this was resolved under issue https://github.com/FusionAuth/fusionauth-issues/issues/468 which came out in 1.15.8. 

We can test with the old version of the template to confirm. 

This is the "old" version of the template

```
  <a href="http://localhost:9011/oauth2/passwordless/${code}?tenantId=${user.tenantId}">
    http://localhost:9011/oauth2/passwordless/${code}?tenantId=${user.tenantId}
  </a>
```

**Comment by bguyza** [comment]
Yep, I was able to recreate the error when using the old template.  It looks like this is no longer an issue as of this commit:
https://github.com/FusionAuth/fusionauth-app/commit/6ddde2e93e73a69c3cd7a2cfc119f0f769e02b9d
