### ISSUE TITLE
refresh token isnt returned after a user is registered.

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#626]
### Description 
After we register a new user with fusionauth, only access_token is returned but not the refresh token, the login api provides the setting to return both the access and refresh token but the registration api doesnt have that setting to return refresh token.

### Steps to reproduce
1. Use user registration api to register a user
2. the response from the api is only the token, no refresh token returned 
3. refresh token should we returned as well.

### Expected behavior
The api should return refresh token as well

### Platform
Using the latest fusionauth docker image

**Comment by robotdan** [comment]
This is working as we intended. We can review this behavior however to see if we want to modify it to be have identical to the login API.
