### ISSUE TITLE
Refresh token not returned from fusionauth login API

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#627]
### Description 
When using the fusionauth login API to login the user, the fusionauth isnt returning a refresh token as a response even if the  generate refresh token is enabled in the application ID to return a refresh token once user logs in.
### Steps to reproduce
1. Use loginAPI to login the user with loginId and password
2. the login API doesnt return refresh token as part of the response

### Expected behavior
The response should contain refresh token

### Platform
using fusionauth latest docker image

**Comment by mooreds** [comment]
Hi. I was unable to replicate this with a fresh docker install:

```
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
docker-compose up
```

I added an application, a user, registered the user with the application and an API key which had permissions for `/api/login`. I also configured the "Login API settings" on the security tab of the new application to ensure that "Generate refresh tokens" was set to true.

Then I ran this curl script:

```
API_KEY=REDACTED

curl -vvvv -H "Content-type: application/json" -H "Authorization: $API_KEY" http://localhost:9011/api/login -d '{"applicationId" : "cd09e351-6a46-4a82-b733-52c34f7b26f5", "loginId":"forlogin@example.com", "password" : "REDACTED" }'
```

And I received this response:

```
{"refreshToken":"El8Bj818UDyWyDAJdj5ABZ3wFqbtiGY1YGQ9X7KlZ5do61mKkuOxRQ","token":"...","user":{"active":true,"email":"forlogin@example.com","id":"f2d2d6dc-00ea-41b8-a34f-c0fc61982ae8","insertInstant":1589464228493,"lastLoginInstant":1589464391010,"passwordChangeRequired":false,"passwordLastUpdateInstant":1589464228549,"registrations":[{"applicationId":"cd09e351-6a46-4a82-b733-52c34f7b26f5","id":"b0020d90-33f2-4072-a8ec-c06ac664617d","insertInstant":1589464234902,"lastLoginInstant":1589464391010,"usernameStatus":"ACTIVE","verified":true}],"tenantId":"e080e860-3270-8a75-5361-5c0dc7de8659","twoFactorDelivery":"None","twoFactorEnabled":false,"usernameStatus":"ACTIVE","verified":true}}
```

This has the refresh token in it. 

Can you please share more information about the call to `/api/login` and your application and user configuration?

**Comment by robotdan** [comment]
@LohithBlaze My guess is you are missing the `applicationId` on the login API request. A refresh token is per user per application. 

We can make this a bit clearer in the API doc.

**Comment by LohithBlaze** [comment]
Yes was missing the applicationId.

**Comment by mooreds** [comment]
Awesome, thanks! I moved this over to the forum as I bet other users are running into this issue as well: https://fusionauth.io/community/forum/topic/86/i-am-using-the-login-api-but-i-m-not-getting-a-refresh-token-wh
