### ISSUE TITLE
Allow custom email headers

### ISSUE THREAD

**Issue by arni-inaba** [FusionAuth/fusionauth-issues#628]
### Problem
I use AWS SES as the SMTP mail server for sending FusionAuth emails. In order to enable tracking of these emails, I have to use what AWS calls a "configuration set". The configuration set can only be enabled by setting the `X-SES-CONFIGURATION-SET` email header.

As FusionAuth does not allow me to specify custom email headers, I cannot track the open rate of my invites/etc.

### Solution
A configuration option (e.g. in the Edit Tenant/Email dialog) where I can specify keys and values for optional extra email headers.

### Alternatives/workarounds
I can switch email providers, but I would prefer to avoid that.

### Documentation tasks
- [x] New Tenant API fields
   - https://fusionauth.io/docs/v1/tech/apis/tenants/
- [x] Update tenant UI field descriptions
   - https://fusionauth.io/docs/v1/tech/core-concepts/tenants/#email
- [x] Update SMTP config
   - https://fusionauth.io/docs/v1/tech/email-templates/configure-email/ 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Initial plan is to support this at the tenant email configuration. This means any additional headers configured will be added to all outgoing email for this tenant. 

We discussed adding this config per template as an override or augmentation, but the plan is to wait until we see if there is a need or desire for this type of capability. One issue with configuring these headers at a template level is that a template may be used between tenants, so it may always make sense to only have the tenant configuration. 

But if anyone has a use case that we are missing, please us know!

**Comment by robotdan** [comment]
Overview of email headers https://fusionauth.io/blog/2021/12/15/announcing-fusionauth-1-32/. 

Let us know what you think, and if this hits the mark! Thanks!
