### ISSUE TITLE
Missing jar after upgrade to 1.31 - fusionauth-plugin-api-1.3.0.jar (No such file or directory)

### ISSUE THREAD

**Issue by ERPG** [FusionAuth/fusionauth-issues#63]
### GRAVE: Servlet.service() para servlet [default] lanzó excepción
java.lang.IllegalStateException: java.io.FileNotFoundException: /Users/ernesto.parra/Desktop/workspace/js/fusionAuth/fusionauth/fusionauth-app/web/WEB-INF/lib/fusionauth-plugin-api-1.3.0.jar (No such file or directory)

I have this error when upgrade the fusionAuth app, apparently some .jar file is missing because the system is asking for the 1.3.0 and in the libs I have the 1.3.1

Please if you know how to fix the issue let me know

**Comment by robotdan** [comment]
Hi @ERPG , I'll plan to close out this issue. Let me know if you need further assistance.
