### ISSUE TITLE
Allow Elasticsearch index name(s) to be configured

### ISSUE THREAD

**Issue by chrishare08** [FusionAuth/fusionauth-issues#631]
### Problem
Currently, the ES index name is hardcoded as `fusionauth_user`. This means there is a 1:1 ratio of FusionAuth  servers to ES clusters. This is an inefficient use of resources, and means if you have have multiple FA installations for regional performance  or other requirements, you have a  separate  ES cluster fo each.

### Solution
Expose an Index name variable in the configuration file and as an environment variable.  This would allow a single, large ES cluster to handle multiple indexes.

The index name could be allowed to be free form, or FusionAuth could support prefix or suffix to allow the index names to be name spaced.  

Example using a configured suffix. 

```
FusionAuth instance A: fusionauth_user_A
FusionAuth instance B: fusionauth_user_B
```

### Alternatives/workarounds
After FA 1.16, use the Database search instead of ES, although there is some loss of functionality.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the issue @chrishare08 . 

I think what you're after is the index name rather than the cluster name? 

The only time FusionAuth sets the Elasticsearch cluster name is when you start with our search package instead of a vanilla version. But we do set the index name and it is hard coded to `fusionauth_user`.

**Comment by chrishare08** [comment]
yes yes - index name, not cluster name
