### ISSUE TITLE
Cannot deploy reliably with kickstart

### ISSUE THREAD

**Issue by zadigus** [FusionAuth/fusionauth-issues#636]
### Description 

I have the following kickstart:
```
{
              "variables": {
                "adminEmail":"admin@shopozor.ch",
                "adminPassword":"password",
              },
              "apiKeys": [
                  {
                    "key":"my-core-api-key",
                    "description":"Core API Key"
                  }
              ],
              "requests": [
                {
                  "method":"POST",
                  "url":"/api/user/registration",
                  "body":{
                    "user":{
                      "email":"#{adminEmail}",
                      "password":"#{adminPassword}"
                    },
                    "registration":{
                      "applicationId":"#{FUSIONAUTH_APPLICATION_ID}",
                      "roles":[
                          "admin"
                      ]
                    }
                  }
                }
              ]
            }
```

I have the following problem: sometimes it happens that for some reason the deployment does not work the first time I run it. Then, the server restarts, the kickstart is performed one more time, and I get the warning or error message that "could not kickstart", because there was already an API key set. Then, anything coming after the `apiKeys` section in the kickstart seems to be ignored (except the admin user registration; in my real kickstart, I have plenty of stuff following the api keys section; nothing seems to be applied except the admin credentials). The deployment is successful, but the initial setup is completely wrong. How can I fix that? How can I make sure that all the kickstart will be applied whenever I deploy my server (be it on docker, k8s, or whatever bare metal server)?

### Steps to reproduce

1. Follow any installation instruction and use the above kickstart
2. Redo step 1. until your deployment fails some reason 

Then, when it tries again to start up the server, you get the error or warning that the server was not able to kickstart because there was already an API key set.

### Expected behavior

The data set in the database from the previous failed deployment have been rolled back and the new deployment can happen flawlessly, or trying to reset the same API key with the kickstart works flawlessly.

### Platform
(Please complete the following information)
 - Device: doesn't matter
 - OS: doesn't matter
 - Browser + version : doesn't matter

**Comment by robotdan** [comment]
Are you in Docker / k8s? If so, how many FusionAuth nodes, and what version of FusionAuth are you using? 

A bug was fixed in 1.16.0 that could have caused an issue when running Kickstart in a multi-node, or even in a single node in some cases.

**Comment by zadigus** [comment]
I am deploying to a k8s cluster and also to a docker node, both currently for the sake of experimentation. Also, I am currently deploying to one single node. I am aware of the issue with version 1.16.0. I fixed on my side by creating the database myself before deploying fusionauth. The issue I am talking about is not related to that (in my newbie's opinion on your software).

**Comment by robotdan** [comment]
There is a separate issue that was resolved in 1.16.0 where the kickstart may try to start more than once causing it to fail all together. 

> I have the following problem: sometimes it happens that for some reason the deployment does not work the first time I run it. 

How does it fail when this occurs?

**Comment by mooreds** [comment]
So I tried to replicate and saw this:

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
 at [Source: (String)"{
              "variables": {
                "adminEmail":"admin@shopozor.ch",
                "adminPassword":"password",
              },
              "apiKeys": [
                  {
                    "key":"my-core-api-key",
                    "description":"Core API Key"
                  }
              ],
              "requests": [
                {
                  "method":"POST",
                  "url":"/api/user/registration",
                  "body":{
                    "u"[truncated 417 chars]; line: 5, column: 16]

```

When I paste the JSON above into https://jsoncompare.com/#!/simple/ it isn't valid JSON.

**Comment by mooreds** [comment]
It looks like there is a extra comma after the `adminPassword` variable definition. I removed that and was able to kickstart using that JSON file.

Please confirm if that works for you, @zadigus

**Comment by zadigus** [comment]
My mistake, @mooreds, it's a copy/paste error. That's not what is producing the error. Here's my full kickstart (and valid):
```
{
  "variables": {
	"defaultTenantId":"d7d09513-a3f5-401c-9685-34ab6c552453",
	"adminEmail":"admin@shopozor.ch",
	"adminPassword":"password",
	"accessTokenSigningKeyId":"#{UUID()}",
	"idTokenSigningKeyId":"#{UUID()}"
  },
  "apiKeys": [
	  {
		"key":"my-core-api-key",
		"description":"Core API Key"
	  }
  ],
  "requests": [
	{
	  "method":"POST",
	  "url":"/api/user/registration",
	  "body":{
		"user":{
		  "email":"#{adminEmail}",
		  "password":"#{adminPassword}"
		},
		"registration":{
		  "applicationId":"#{FUSIONAUTH_APPLICATION_ID}",
		  "roles":[
			  "admin"
		  ]
		}
	  }
	},
	{
	  "method":"PATCH",
	  "url":"/api/tenant/#{defaultTenantId}",
	  "body":{
		"tenant":{
		  "name":"Default",
		  "issuer":"shopozor.com"
		}
	  }
	},
	{
	  "method":"PATCH",
	  "url":"/api/system-configuration",
	  "body":{
		"systemConfiguration":{
		  "corsConfiguration":{
			"allowedMethods":[
			  "GET",
			  "POST",
			  "PUT",
			  "DELETE",
			  "HEAD",
			  "OPTIONS",
			  "PATCH"
			],
			"allowedOrigins":[
			  "*"
			]
		  }
		}
	  }
	},
	{
	  "method":"POST",
	  "url":"/api/key/import/#{accessTokenSigningKeyId}",
	  "body":{
		"key":{
		  "algorithm":"HS256",
		  "name":"HS256 Access token signing key",
		  "secret":"access-token-signing-key-secret",
		  "type":"HMAC"
		}
	  }
	},
	{
	  "method":"POST",
	  "url":"/api/key/import/#{idTokenSigningKeyId}",
	  "body":{
		"key":{
		  "algorithm":"HS256",
		  "name":"HS256 Id token signing key",
		  "secret":"id-token-signing-secret",
		  "type":"HMAC"
		}
	  }
	},
	{
	  "method":"POST",
	  "url":"/api/application",
	  "body":{
		"application":{
		  "jwtConfiguration":{
			"accessTokenKeyId":"#{accessTokenSigningKeyId}",
			"enabled":true,
			"idTokenKeyId":"#{idTokenSigningKeyId}",
			"refreshTokenTimeToLiveInMinutes":43201,
			"timeToLiveInSeconds":3601
		  },
		  "loginConfiguration":{
			"allowTokenRefresh":true,
			"generateRefreshTokens":true,
			"requireAuthentication":true
		  },
		  "name":"consumer-ui",
		  "oauthConfiguration":{
			"clientSecret":"the-consumer-client-secret",
			"generateRefreshTokens":true,
			"requireClientAuthentication":true
		  },
		  "roles":[
			{
			  "name":"consumer",
			  "isSuperRole":false,
			  "isDefault":false
			}
		  ]
		}
	  }
	},
	{
	  "method":"POST",
	  "url":"/api/application",
	  "body":{
		"application":{
		  "jwtConfiguration":{
			"accessTokenKeyId":"#{accessTokenSigningKeyId}",
			"enabled":true,
			"idTokenKeyId":"#{idTokenSigningKeyId}",
			"refreshTokenTimeToLiveInMinutes":43201,
			"timeToLiveInSeconds":3601
		  },
		  "loginConfiguration":{
			"allowTokenRefresh":true,
			"generateRefreshTokens":true,
			"requireAuthentication":true
		  },
		  "name":"admin-ui",
		  "oauthConfiguration":{
			"clientSecret":"the-admin-client-secret",
			"generateRefreshTokens":true,
			"requireClientAuthentication":true
		  },
		  "roles":[
			{
			  "name":"producer",
			  "isSuperRole":false,
			  "isDefault":true
			},
			{
			  "name":"manager",
			  "isSuperRole":false,
			  "isDefault":false
			},
			{
			  "name":"rex",
			  "isSuperRole":false,
			  "isDefault":false
			}
		  ]
		}
	  }
	}
  ]
}
```
I'll attach the fusionauth logs that I get upon failure. It's happening randomly, so I hope to get it soon.

**Comment by zadigus** [comment]
Voilà, here's the server log upon failure to kickstart.

[fusionauth.log](https://github.com/FusionAuth/fusionauth-issues/files/4655206/fusionauth.log)

It does not happen all the time. That time, the admin account was not created. Sometimes it is, sometimes not. Sometimes the kickstart can be done, sometimes not, it's strange.

**Comment by robotdan** [comment]
In this recreate attempt, you have a single node of FusionAuth running version 1.16.0, with an empty database?

**Comment by zadigus** [comment]
@robotdan I am installing [this chart](https://gitlab.hidora.com/softozor/shopozor/services/tree/273-implement-auth-to-access-the-basket-admin-panel/backend%2Fauth-service%2Fchart) with the [following values](https://gitlab.hidora.com/softozor/shopozor/services/blob/273-implement-auth-to-access-the-basket-admin-panel/devspace.yaml#L231):
```
replicaCount: 1
      image:
        tag: 1.16.0
      database:
        setupInitialState: true
        user: fusionauth
        password: fusionauth
        host: ${DATABASE_HOSTNAME}
        port: ${DATABASE_PORT}
        name: fusionauth
        root:
          user: ${DATABASE_USERNAME}
          password: ${DATABASE_PASSWORD}
      search:
        engine: database
      ingress:
        enabled: true
        paths:
          - /
        hosts:
        - auth.shopozor
      environment:
        FUSIONAUTH_API_KEY: test
        FUSIONAUTH_KICKSTART: /kickstart/kickstart.json
```
and the above mentioned kickstart. Such a deployment [sets up the database](https://gitlab.hidora.com/softozor/shopozor/services/blob/273-implement-auth-to-access-the-basket-admin-panel/backend/auth-service/chart/templates/deployment.yaml#L38) the way described in your documentation, as you can see in [this script](https://gitlab.hidora.com/softozor/shopozor/services/-/blob/273-implement-auth-to-access-the-basket-admin-panel/jelastic/postgres/reset_auth_db.sh).

**Comment by zadigus** [comment]
Hmmmm, copy / pasting my code here, I notice that I have on the one hand
```
FUSIONAUTH_API_KEY: test
```
in my helm configuration and 
```
"apiKeys": [
	  {
		"key":"my-core-api-key",
		"description":"Core API Key"
	  }
  ],
```
in my kickstart. Can that be an issue?

**Comment by mooreds** [comment]
Heya, I have been unable to replicate this issue when running without k8s. I don't think that `FUSIONAUTH_API_KEY` matters since that'll just be one more envt var available to the kickstart.

Question: does the postgresql server you are connecting to in the logs have a fresh FusionAuth database (I typically drop mine to test kickstart)?

**Comment by zadigus** [comment]
@mooreds yes, my database is destroyed and recreated everytime. The issue seems to come from the fact that sometimes (on a random basis), the master node seems to be unreachable (that's what I understand from the logs).

Now, what I guess might be the problem is that I am doing all that on the k8s cluster provided by Docker for Desktop under Windows. There are sometimes some strange effects happening there. And maybe deploying / undeploying several times within little time might be problematic in that environment. I don't know. I might try that on my production cluster. It's no big deal, in the end, because such issues on a dev environment are ok. They are annoying, but ok. And in production, I do only deploy once and for all, so the issue should not pop up at all.

**Comment by mooreds** [comment]
Okay, thanks for explaining. Makes sense.

If you feel like this is an intermittent error that just appears on the dev envt, is it okay to close this?

**Comment by zadigus** [comment]
yes
