### ISSUE TITLE
Cannot access the fusionauth installed in a remote windows server 2012

### ISSUE THREAD

**Issue by tmnrp** [FusionAuth/fusionauth-issues#637]
Cannot access the fusionauth installed in a remote windows server 2012

I have a remote windows server in which i have installed fusionauth.
from the remote i am able to hit localhost:9011
But i am not able to access it from my local machine <ip_address:9011>.

//The access to port 9011 is open.

Is there some additional setting required with in fusionauth configuration ?
Did I miss something from my side ?
Any help will be greate.
Thank you

**Comment by mooreds** [comment]
There should be no changes in FusionAuth required to allow it to serve up content. Have you opened up port 9011 in the Windows Server Firewall?

**Comment by tmnrp** [comment]
Yes, have opened the port for 9011 from windows firewall. Hence was in wondering if there is something to be done from fusionauth settings or...

anyways thanks for the reply. will try to look into the system to identify whats blocking the access.

**Comment by mooreds** [comment]
Sure thing. Nope, FusionAuth should be good to go, especially since you can get to it from localhost.

**Comment by mooreds** [comment]
Please do let us know what the solution is when you find it, @tmnrp !

**Comment by tmnrp** [comment]
sure will add the solution here when i figure it out.
m closing the ticket now.

**Comment by tmnrp** [comment]
Solution:
Turned out to be port. It was not open from firewall.
