### ISSUE TITLE
device_authorize endpoint requires client_id as URL Param?

### ISSUE THREAD

**Issue by Gowiem** [FusionAuth/fusionauth-issues#639]
### Description 
Banged my head against this one for a while... seems the Device Authorize endpoint @ `/oauth2/device_authorize` requires a valid `client_id` in the URL as a param and it does not accept the `client_id` provided via JSON post body. 

### Steps to reproduce
1. [Download this Postman Collection](https://drive.google.com/file/d/1d-otLTjLP6tKW470ICV6R6TZ5wBApO4p/view?usp=sharing)
1. Create an Application that supports the Device Code grant. Copy its Client ID. 
1. Open the Postman Collection. Update the requests to use your new Client ID.
1. Try both requests. See that the one with the URL param returns a 200 + valid response. The one with only the post body returns that it requires a `client_id` param. 

### Expected behavior
I would expect the request to not require a client_id URL param. 

### Screenshots
![image](https://user-images.githubusercontent.com/1392040/82604532-b6e08a80-9b71-11ea-99a2-67c35ed0aa13.png)
![image](https://user-images.githubusercontent.com/1392040/82604539-b811b780-9b71-11ea-8d5e-83f8adc95584.png)

### Platform
 - Device: MacBook Pro
 - OS: MacOSX

### Additional context
I'm able to reproduce this issue in code using go. Oddly enough, I am not able to reproduce this via the [example-device-grant repo](https://github.com/FusionAuth/fusionauth-example-device-grant). I have not looked into that deeply, but that is a head scratcher.

**Comment by mooreds** [comment]
Hmmm. According to the [docs](https://fusionauth.io/docs/v1/tech/oauth/endpoints#device), or actually the linked RFC, you need to use 

> application/x-www-form-urlencoded" format

not JSON. 

Is that perhaps the issue?

**Comment by Gowiem** [comment]
@mooreds Ah seems legit -- I definitely missed that. What led me astray is the [example-device-grant repo does this ajax call](https://github.com/FusionAuth/fusionauth-example-device-grant/blob/df68fc2e0597459f5ba3fd5e2a6df05914386b42/main.js#L34-L40) and uses `datatype: 'json',`. I haven't written JS or an ajax call in a long time so maybe that is only referring to the input data type and not the request's `Content-type`? If so... then I just misread the example and it sent me down a bad rabbit hole.

**Comment by mooreds** [comment]
Ah, it looks like `datatype` is what you are expecting back, and that `application/x-www-form-urlencoded; charset=UTF-8` is the default `contentType`: https://stackoverflow.com/questions/18701282/what-is-content-type-and-datatype-in-an-ajax-request

Confusing, but it appears the example does use form parameters.

**Comment by Gowiem** [comment]
Yeah, found the same after posting my answer. What a fun rabbit hole. 😭 

I'll close this one out. I will likely put a PR up against the example-device-grant repo to explicitly call out that the content-type is form in the AJAX request so no other poor soul needs to get confused like I did. 

Thanks for pointing me in the right direction @mooreds!
