### ISSUE TITLE
Can we get all the uses from application ?

### ISSUE THREAD

**Issue by tmnrp** [FusionAuth/fusionauth-issues#640]
### Description
I am not able to file api where i can get all the users from an application.
Is it possible? Is there a workaround ?

Thanks

**Comment by robotdan** [comment]
You can use the Search API to find all users that have a registration for a particular Application. 

In the UI you can do this by using the advanced search controls. Once you use the select boxes to query by registration, you can expand the "show search query" to see the query and use that on the API. 

The API search query would be something like this, where `c53a95bc-c082-4243-b5df-d4408d5dd92b` is the Id of the application you're looking for. 

```
{
  "bool" : {
    "must" : [ [ {
      "nested" : {
        "path" : "registrations",
        "query" : {
          "bool" : {
            "must" : [ {
              "match" : {
                "registrations.applicationId" : "c53a95bc-c082-4243-b5df-d4408d5dd92b"
              }
            } ]
          }
        }
      }
    } ] ]
  }
}
```

**Comment by tmnrp** [comment]
Thank you for the quick reply.
It is great help. :)

**Comment by mooreds** [comment]
Moved over to the forum: https://fusionauth.io/community/forum/topic/110/how-can-i-get-all-users-for-an-application-using-the-api
