### ISSUE TITLE
403 when using SAML IDP

### ISSUE THREAD

**Issue by asabolansky** [FusionAuth/fusionauth-issues#641]
403 when using SAML IDP

Hello I have configured an external IDP to use with FusionAuth following the guide https://fusionauth.io/docs/v1/tech/identity-providers/samlv2/

When the callback returns and the client browser do the POST to the ACS URL, I receive an empty HTTP response with 403 code from FusionAuth.

**Comment by robotdan** [comment]
This is a CORS error. You'll need to ensure `POST` is an allowed HTTP method, and the origin of your SAML IdP is configured as an allowed origin.  

https://fusionauth.io/docs/v1/tech/reference/cors

In the next release of FusionAuth, we'll add some warning messages in the IdP configuration to alert you to this needed configuration.

**Comment by mooreds** [comment]
https://fusionauth.io/community/forum/topic/111/403-when-using-saml-idp

**Comment by robotdan** [comment]
@asabolansky can you confirm this has resolved your issue?

**Comment by asabolansky** [comment]
I disabled CORS and the callback has worked, however I still have not been able to detect all the necessary headers or options to make it work without disabling CORS.

**Comment by asabolansky** [comment]
Yes. I enabled the origin in the CORS configuration in addition to the POST method but it still returns 403.

**Comment by asabolansky** [comment]
Hi, I think I have resolved the CORS issue. Now when I try to authenticate with the external SAML provider, I get the following message "The SAML AuthnResponse object could not be parsed or verified. The authentication request has failed. The login request failed."

**Comment by robotdan** [comment]
To clarify, if you disable the CORS filter the callback works, and if you enable CORS, allowing `POST` and the necessary `origin` configuration you still get a `403` but it says `The SAML AuthnResponse object could not be parsed or verified. The authentication request has failed. The login request failed.`? 

Or, is it that the CORS is now configured properly, but you are just getting this new error?

**Comment by asabolansky** [comment]
Hello, I have been able to solve the problem related to CORS and SAML

**Comment by mooreds** [comment]
@asabolansky would love if you could share the solution. That's help future folks encountering the same issue and/or let us know if we need to update the docs.

Also, please close this issue if you consider it resolved.

**Comment by asabolansky** [comment]
Hello,
I have only configured the origin correctly. Maybe it was a browser cache problem.

Thank yo
