### ISSUE TITLE
Allow end users to log into the admin front-end and manage their own profile

### ISSUE THREAD

**Issue by yrammos** [FusionAuth/fusionauth-issues#647]
### Problem
No front-end is available for users to manage their record after initial registration. Users lacking the superuser role are unable to log into the FusionAuth admin front-end in the first place.

### Suggested solution
Provide an "end user" role granting read/write access to the particular user's data only (minus the unique UID). This would also facilitate the adoption of 2FA, which is currently cumbersome, as documented also in #51.

### Related
https://github.com/FusionAuth/fusionauth-issues/issues/682
https://github.com/FusionAuth/fusionauth-issues/issues/753

### Alternative solution
Provide a bare-bones customizable webapp template for us to fork and build on.

Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by voidmain** [comment]
Anyone mind if I close this out and track this entirely with #682 ?

**Comment by robotdan** [comment]
Ok with me.
