### ISSUE TITLE
Custom login page, bypass Fusionauth's login UI

### ISSUE THREAD

**Issue by broodfusion** [FusionAuth/fusionauth-issues#650]
### Description
I have my own custom login UI created and was wondering how can I utilize the [endpoints](https://fusionauth.io/docs/v1/tech/oauth/endpoints) to implement the login flow without using Fusionauth's own login ui?

If possible, can someone please tell me what the steps are and which endpoints I should use?
Thank you!!

**Comment by robotdan** [comment]
There is a lot of upside to using our login UI, there are a lot of use cases and workflows you'll have to code yourself when building your own login page. But if you select to use your own, the following links will be helpful.

https://fusionauth.io/learn/expert-advice/authentication/login-authentication-workflows

Here are two of the preferred methods to use if you will not be using the FusionAuth login UI. 

https://fusionauth.io/learn/expert-advice/authentication/login-authentication-workflows
https://fusionauth.io/learn/expert-advice/authentication/webapp/oauth-authorization-code-grant-sessions

**Comment by broodfusion** [comment]
Thanks @robotdan 
I'm a bit stuck at the moment, and I've gone through the above links a couple of times. 
Using the authorization code flow, in my custom login form, after the user inputs `username` and `password`, which endpoint should I hit to kickoff the authentication?

It looks like I wouldn't be able to use the [`/authorize`](https://fusionauth.io/docs/v1/tech/oauth/endpoints#authorize) endpoint because a 200 response would have the HTML form?

I read [here](https://fusionauth.io/community/forum/topic/93/can-i-replace-the-fa-login-forms-with-my-own) (option 3) that I should use the [login](https://fusionauth.io/docs/v1/tech/apis/login) API, but I don't see how that uses oauth2

Appreciate the help, thanks!

**Comment by robotdan** [comment]
If you have your own login form, you'll either be using the Login API or the OAuth Password grant. You will use one or the other, not both, each option will provide you roughly the same functionality. Totally up to you, the Login API is our own creation, the Password grant is defined by the OAuth RFC. 

High level:
1. Collect email and password
2. Call the Login API or the Token endpoint using the Password grant
3. Collect the JSON response which will contain an access token (JWT)

Login API: 
https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user

Password Grant: 
https://fusionauth.io/docs/v1/tech/oauth/endpoints#resource-owner-password-credentials-grant-request
https://fusionauth.io/docs/v1/tech/oauth/#example-resource-owner-password-credentials-grant

**Comment by broodfusion** [comment]
Thank you, I will give this a shot

**Comment by mooreds** [comment]
I added this to the forum: https://fusionauth.io/community/forum/topic/124/i-want-to-create-my-own-login-form

@broodfusion, please ask further questions there.
