### ISSUE TITLE
Using Google Identity Provider gives error with missing_redirect_uri 

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#651]
### Description 

I've configured FA with Google as an Identity Provider and when I try to log in using Google sign-in button I get the following error in FusionAuth: "`The request is missing a required parameter: redirect_uri".`

It seems the issue is with the query string parameters being encoded in some strange way. I've found a SO topic: https://stackoverflow.com/questions/57817229/callback-after-google-login-throwing-error-in-fusionauth but it is not clear to me why it happens and what to do.

### Steps to reproduce

* Configure an app and FusionAuth to live at a local address, via /etc/hosts
* Follow instructions here: https://fusionauth.io/docs/v1/tech/identity-providers/google 
* User visits the application: `https://company.local`
* User is redirected to FusionAuth at `https://auth.company.local` with the following URL: `https://auth.company.local/oauth2/authorize?response_type=code&client_id=3400cdea-a571-47f1-8ddb-53cd97dca0c7&redirect_uri=https%3A%2F%2Fcompany.local%2Faccount%2Floggedin%2F&scope=openid+profile+email&state=eCKswp4Ey9QlP6IKSO9yx489RSZL5B`
* User clicks Login with Google button - popup with the following URL opens: `https://accounts.google.com/signin/oauth/identifier?redirect_uri=storagerelay%3A%2F%2Fhttps%2Fauth.company.local%3Fid%3Dauth79207&response_type=permission id_token&scope=email profile openid&openid.realm&client_id=893947843790-082nmgu907c7ff4de6sis3aqbj9pvs52.apps.googleusercontent.com&ss_domain=https%3A%2F%2Fauth.company.local&fetch_basic_profile=true&gsiwebsdk=2&o2v=1&as=2sT8ucIey-_EVmp3SOvNTw&flowName=GeneralOAuthFlow`
* User logs in with Google and is redirected back to FusionAuth using the following URL: `https://auth.company.local/oauth2/callback?token=<TOKEN_CUT_HERE>&identityProviderId=82339786-3dff-42a6-aac6-1f1ceecb6c46&state=client_id%3D3400cdea-a571-47f1-8ddb-53cd97dca0c7%26code_challenge%3D%26code_challenge_method%3D%26metaData.device.name%3DLinux%2520Chrome%26metaData.device.type%3DBROWSER%26nonce%3D%26redirect_uri%3Dhttps%253A%252F%252Fcompany.local%252Faccount%252Floggedin%252F%26response_mode%3D%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520email%26state%3DeCKswp4Ey9QlP6IKSO9yx489RSZL5B%26tenantId%3Dd617561c-0946-b874-f878-b3433552bce4%26timezone%3DEurope%252FWarsaw%26user_code%3D`

This gives the error in FA:
```
{
"error" : "invalid_request",
"error_description" : "The request is missing a required parameter: redirect_uri",
"error_reason" : "missing_redirect_uri"
}
```

Seems clear that something strange happens after: &state=client_id but why is that? What is wrong?

### Expected behavior
User can login with google as the identity provider. 

### Platform

FusionAuth 1.15.7

### Additional context

Originally raised in the forum: https://fusionauth.io/community/forum/topic/117/google-identity-provider-and-missing_redirect_uri

Per comments on https://stackoverflow.com/questions/57817229/callback-after-google-login-throwing-error-in-fusionauth a similar issue was fixed by @robotdan around v1.10

As I'm switching from the old solution to Fusion Auth I already have a Google sign-in button implemented (JavaScript) and it works correctly with company.local domain there.

**Comment by robotdan** [comment]
I think this is a duplicate of Issue https://github.com/FusionAuth/fusionauth-issues/issues/553. Solution is to upgrade to >= 1.15.8. 

https://fusionauth.io/docs/v1/tech/release-notes#version-1-15-8

**Comment by mooreds** [comment]
Ah, thanks!
