### ISSUE TITLE
inaccurate tooltip or option name in OAuth settings

### ISSUE THREAD

**Issue by JuliusPC** [FusionAuth/fusionauth-issues#654]
### Description

The tooltip states that this only applies to Authorization via HTTP header but the option name itself implies that this option disables entire authentication (credentials can be supplied via header or parameter in response body) of relying parties and FusionAuth.

![FusionAuth](https://user-images.githubusercontent.com/15018932/83144662-f9671180-a0f3-11ea-98c2-8ac487bd569b.png)

**Comment by mooreds** [comment]
Looks like the tooltip needs to be updated. As you say, the auth credentials can be supplied to the token endpoint by either the authorization header or POST parameters.

https://fusionauth.io/docs/v1/tech/oauth/endpoints#token 

We should change the tooltip to be something like: 

"Controls if the token endpoint requires authentication, either in the request or in the header."

Thanks!

**Comment by robotdan** [comment]
I think this text is mostly correct. We do publish both options in our OpenID Connect discovery document, but the "default" is `client_secret_basic` which then looks for the Basic Authorization header.

```
 "token_endpoint_auth_methods_supported" : [
    "client_secret_basic",
    "client_secret_post",
    "none"
  ],
```

We could update the tooltip to say something like :

> When authentication is required, the token endpoint will require the client_secret to be provided. 

Both options are documented in the Token endpoint.
https://fusionauth.io/docs/v1/tech/oauth/endpoints#token
