### ISSUE TITLE
Can't set roles in SAMLv2 lambda reconcile function 

### ISSUE THREAD

**Issue by asabolansky** [FusionAuth/fusionauth-issues#657]
Hi ,
I received from my SAML IDP an attribute called permissions that I need to assign as roles in FusionAuth and then return them in a JWT token.

```javascript
function reconcile(user, registration, samlResponse) {
  // Assign the roles to the user from the SAML attribute named 'roles'
  registration.roles = samlResponse.assertion.attributes.permissions || [];
  console.debug('----- permissions -----');
  console.debug(samlResponse.assertion.attributes.permissions);

  // Create an event log of type 'Debug' when the lambda has Debug enabled
  console.debug('FusionAuth reconciled a User from a SAML v2 IdP and I helped!');
  console.info(JSON.stringify(samlResponse, null, 2));

}
```
Analyzing the FusionAuth log, I notice that the roles attribute is empty. Do roles need to be defined in FusionAuth or can they be created on the fly?

Thanks 
Alejandro

**Comment by mooreds** [comment]
Are you asking if you need to define the roles in the FusionAuth `application` before they can be populated in the JWT by this lambda?

It looks like you confirmed the permissions are coming back from SAML, correct?

What version of FusionAuth are you running? Versions before 1.14 considered the `roles` claim reserved and won't allow modification of them: https://fusionauth.io/docs/v1/tech/lambdas/jwt-populate

**Comment by robotdan** [comment]
>  console.debug('FusionAuth reconciled a User from a SAML v2 IdP and I helped!');

Ha ha! Love it.

**Comment by asabolansky** [comment]
> Are you asking if you need to define the roles in the FusionAuth `application` before they can be populated in the JWT by this lambda?

Yes. That is my question. I wish I didn't have to define them in FusionAuth.

Here

**Comment by mooreds** [comment]
Ah, thanks.

What version of FusionAuth are you running?

And what is the output from

```
  console.debug('----- permissions -----');
  console.debug(samlResponse.assertion.attributes.permissions)
```

**Comment by asabolansky** [comment]
----- permissions -----
{"unlp.teacher":["33"],"unlp.personnel":["26"],"unlp.student":["33"]}

**Comment by mooreds** [comment]
Ah, thanks. I see you are on the latest version of FA too, sorry I missed that earlier.

So I don't have SAML set up, but I was able to use a "populate JWT" lambda to set the roles variable to that you provided (and my roles didn't exist). I looked through the code and there doesn't appear to be any special handling of SAML reconciliation responses (but I could have missed something). 

```
{
  "aud": "0ef466ba-0505-4150-9b34-da0895a98cae",
  "exp": 1590784041,
  "iat": 1590780441,
  "iss": "acme.com",
  "sub": "0756bfdd-d0f0-4c27-a24a-14f809013cb5",
  "authenticationType": "PASSWORD",
  "email": "redacted",
  "email_verified": true,
  "roles": [
    "33",
    "26",
    "33"
  ]
}
```

Two things. 

1. Can you try setting your role to an existing FA role and see if that appears in your JWT?
2. The SAML permissions you show aren't actually a JSON array, but rather an object. Is that intended? 

Here's the lambda code I used:

```
  var samlroles = {"unlp.teacher":["33"],"unlp.personnel":["26"],"unlp.student":["33"]};

  // pick out the values
  var samlrolesarray = Object.keys(samlroles).map(function(e) {
    return samlroles[e];
  });
  // flatten the array
  jwt.roles = [].concat.apply([], samlrolesarray);
```

**Comment by robotdan** [comment]
> Yes. That is my question. I wish I didn't have to define them in FusionAuth.

@asabolansky I think you're saying you don't want to have to pre-define the roles by name in the Application before trying to assign them in the Lambda? 

This would allow the role in your example such as `unlp.teacher` to come through in the SAML response, and then FusionAuth would create that role in the Application if it did not yet exist, and then assign that role to the user. 

Is that what you're after?

**Comment by asabolansky** [comment]
I have not been able to prove what you have sent me. I hope this afternoon I can do it and send you a feedback

Regards
Alejandro

**Comment by robotdan** [comment]
@asabolansky if this is still an issue, can you please re-open and we'll attempt to recreate on the latest version of FusionAuth.
