### ISSUE TITLE
Unable to connect to Elastic on custom ports

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#658]
### Description
I am hosting Fusionauth on AKS. Fusion and Search are hosted on single node. I'm using custom ports for transport (9300) and http (9200).  Elastic search is up and running on 9200 perfectly. 

Below are the environment variables of fusionauth deployment.

```
       - name: fusionauth-app.search-engine-type
              value: elasticsearch
            - name: fusionauth.runtime-mode
              value: development
            - name: FUSIONAUTH_MEMORY
              value: 1024M
            - name: fusionauth-search.transport-port
              value: '9300'
            - name: fusionauth-search.http-port
              value: '9200'
            - name: fusionauth-search.servers
              value: 'localhost:9300'
            - name: fusionauth-app.search-servers
              value: 'http://user:password@localhost:9200'
```

But still Fusion is unable to connect to Elastic. I don't see maintenance screen or Reindex menu item. 
I can see below error in the logs.

`Determine search status : SERVER_DOWN [http://localhost:9021]`

No sure why fusion is trying to access elastic on default port even after forcing it to use custom ports.

**Comment by robotdan** [comment]
I think your mixing environment variable names and property names. 

All of the env names are uppercase. 
https://fusionauth.io/docs/v1/tech/reference/configuration

**Comment by prabhakarreddy1234** [comment]
Thanks. Fusion and Elastic are on different pods so can't use `localhost`. Elastic needs credentials. Adding below url is halting the process while connecting to elastic search and throws exception.
```

   - name: FUSIONAUTH_SEARCH_SERVERS
              value: 'http://user:password@fusionauth-search:9200'
```
Is this the correct way of passing credentials or do i need to set some environment variables with username and password ? I can't find any ENV variables to serve the purpose.

**Comment by prabhakarreddy1234** [comment]
Please ignore above comment. It worked with `FUSIONAUTH_RUNTIME_MODE:Production`. 

Thanks
