### ISSUE TITLE
unable to access fusion auth app

### ISSUE THREAD

**Issue by arunkumar413** [FusionAuth/fusionauth-issues#66]
### Description
I had installed the fusionauth search and app on my linux mint system and started the services. However I'm not able to access the app on the web using the the URL http://localhost:9011/.

Here is the log of the app

https://paste.ubuntu.com/p/ZD2y959sGD/

`

**Comment by robotdan** [comment]
From the log, it looks like the `fusionauth-app` services starts up, enters maintenance mode and then shuts down.  This would explain why you cannot access the web UI at `http://localhost:9011`.

```
19-Jan-2019 11:22:37.211 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 24697 ms
19-Jan-2019 11:41:45.401 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
```

The shutdown log statements indicates it received a shutdown command `19` seconds after it started up. This could mean the service received the `stop` command, or perhaps it received the `shutdown` command on the Tomcat shutdown port. 

By default the shutdown port is set to `9010`, but it can be modified in the configuration file with this key `fusionauth-app.management-port`.
`/usr/local/fusionauth/config/fusionauth.properties`

Is it possible you have another service running on port `9010` or another services or user initiated the shutdown via `service fusionauth-app stop` or the shutdown port? 

A couple of questions:
1. Are you running any other services on port `9010`?
2. How are you starting FusionAuth? 
   -  `sudo service fusionauth-app start`
   - `/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh`
   - `/usr/local/fusionauth/bin/startup.sh`
3. Depending on your answer to 2, can you try starting up in different modes to see if the same symptom occurs?

**Comment by arunkumar413** [comment]
@robotdan,

I had started the app using the command `sudo service fusionauth-app start`

This [documentation](https://fusionauth.io/docs/v1/tech/tutorials/setup-wizard) mentioned that the port is 9011.  I tried visiting both 9010 abd 9011 ports but it didn't work. 

Also, in the log I noticed below line about database. Do you think this is also one of the contributing factor for the issue. 

**_Jan 19, 2019 11:22:36.837 AM INFO  io.fusionauth.app.maintenance.FusionAuthMaintenanceModeWorkflow - Determine database status : ORDINARY_USER_CANNOT_CONNECT [FATAL: password authentication failed for user "fusionauth"]_**

**Comment by robotdan** [comment]
Yes, the port you'll access the service is `9011`, but Tomcat will also bind to `9010` as the shutdown port. This is where Tomcat will receive the `shutdown` command, this was the reason for my question. 

The log statement regarding the database is part of our maintenance mode, it indicates the use configured to be the FusionAuth user ( `database.username=fusionauth` ) does not yet exist. This will cause us to enter maintenance mode so that we can configure the schema. This is normal. 

Have you been able to try the other two startup commands to see if they result in the same symptom? 

- `/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh`
- `/usr/local/fusionauth/bin/startup.s`

What version of Linux are you running?

**Comment by arunkumar413** [comment]
The command _/usr/local/fusionauth/bin/startup.s_ worked. But it's throwing the below error. Seems like the issue is with the superuser credentials of the database.  Any idea on how to configure the superuser credentials 

_Unable to connect to your database using the superuser username and password, verify your connection information. If it is correct, make sure the database is running before continuing._

**Comment by robotdan** [comment]
Is that in the log or during maintenance mode in the UI?

That is all normal generally speaking if it is in the log, it should enter maintenance mode and them when you bring up the UI it will prompt you for configuration. 

You'll have to refer to the Ubuntu defaults for PostgreSQL for the suer user creds. 

I would still not expect tomcat to shutdown automatically.

**Comment by robotdan** [comment]
Ok, yeah, getting the DB running will be a prerequisite to getting FusionAuth configured.



You'll need to review the Ubuntu PostgreSQL doc to get the super user creds and ensure the service is running. Once you can connect to a SQL shell with super user creds, them you should be able to return to the FusionAuth maintenance mode to complete the setup.

**Comment by arunkumar413** [comment]
@robotdan ,

I was somehow able to bring up the database. 

I tried the command `sudo service fusionauth-search start` but the fusionauth search isn't working and throwing the below message in the maintenance UI. 
 **The configured server address appears to be down, it is not accepting connections.**

**Comment by robotdan** [comment]
Hi @arunkumar413 I'll plan to close out this issue, let me know if you're still having trouble.

**Comment by arunkumar413** [comment]
I was somehow able to access. Please feel free to close this issue. 

@on a side note, could you create a gitter chat channel for discussing fusion auth?

**Comment by robotdan** [comment]
Thanks for the update @arunkumar413 , we have considered adding some sort of community chat , I'll add gitter to our list of options to explore. Thanks!

**Comment by kevinadhiguna** [comment]
```
The database and schema exist, but for some reason the ordinary user you specified cannot connect to it. Perhaps the user already existed and you provided the wrong password. The error from the database was [FATAL: password authentication failed for user "fusionauth"].
```

I got this error and I do not remember the password of user `fusionauth`. How can I reset password ?
![Can not get in](https://user-images.githubusercontent.com/43397636/111113845-f65ee400-8594-11eb-9507-cbc5eadd0692.png)

![password wrong](https://user-images.githubusercontent.com/43397636/111114000-3756f880-8595-11eb-83b0-3ee60f5dd39f.png)

Any help will be appreciated.

**Comment by mooreds** [comment]
Hiya @kevinadhiguna 

This appears to be a support issue. If you have a support contract, please [open a ticket](https://account.fusionauth.io/account/support/). If you don't, please [post in the forum for community support](https://fusionauth.io/community/forum/). 

We also don't typically reply to messages on closed issues (except to let people know about the support options.)

**Comment by kevinadhiguna** [comment]
Somehow I had to enter the password of my local PostgreSQL and it worked...
This happened when I run FusionAuth either locally or with Docker. Thanks for your response !
