### ISSUE TITLE
Support generating elliptic curve keys within FA

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#664]
### Problem
Right now you can import elliptic curve keys into FA, but you can't generate them. From what I've read, RSA is problematic and we should encourage people to use elliptic curve keys.

### Solution
The same way you can generate HMAC or RSA keys from the `Key Master` screen, you can generate EC keys.

### Alternatives/workarounds

Generate an EC key outside of FA, import it.

### Additional context

https://www.thesslstore.com/blog/bleichenbachers-cat-rsa-key-exchange/

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
You can generate EC keys. 

API: https://fusionauth.io/docs/v1/tech/apis/keys#generate-a-key
UI: 
![image](https://user-images.githubusercontent.com/1148709/83583240-0bd0b900-a501-11ea-86c9-816624595d3b.png)

**Comment by mooreds** [comment]
I can't believe I missed it! Doh!

**Comment by robotdan** [comment]
Is this one of the items that you open just so we don't suspect you're a robot?

**Comment by mooreds** [comment]
![dancingrobot](https://user-images.githubusercontent.com/91825/83590507-2744bf80-a513-11ea-8699-6bc38998f3da.gif)
