### ISSUE TITLE
Add a link to return to login from the register page

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#666]
### Problem

As a user, I'm redirected for an oauth connection:

1. I click on "register" (self-register)
2. I fill some field with invalid data and submit
3. I go away for some days
4. When I go back to the app, I'm directly redirected to the register page.

But there is no link to go back to the logic base, which is quite a basic in my opinion.

Because of that, the user is "stuck" on the registration form unless he empty his cookies.

### Solution

A a "return to login" link, like this:

![image](https://user-images.githubusercontent.com/1698357/83662706-2d48a800-a5c8-11ea-91af-11af8f16415f.png)

Here is the additional code I added on `oauth2/register.ftl`:

```
<div class="form-row">
  [@helpers.button icon="key" text=theme.message('register')/]
  [#-- OVERRIDE_BEGIN --]
  [@helpers.link url="/oauth2/authorize"]${theme.message('return-to-login')}[/@helpers.link]
  [#-- OVERRIDE_END --]
</div>
```

This should be added by default IMO.

### Alternatives/workarounds

Template override as describe before.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by soullivaneuh** [comment]
Note: Sorry for the hell issue. :trollface:

**Comment by robotdan** [comment]
666, yikes. I guess it had to happen eventually.
