### ISSUE TITLE
[1.3.1] Login is not displayed in the tab

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#67]
### Description 
I just tried a login from POSTMAN and I do not see any login in "Recent logins"

### Steps to reproduce
- send a login from POSTMAN
- go to the user profile

### Expected behavior
The login should be displayed in the tab

### Screenshots
<img width="984" alt="screen shot 2019-01-29 at 11 11 53 am" src="https://user-images.githubusercontent.com/1580512/51891361-44fe9380-23b8-11e9-929f-9403b67a6769.png">
<img width="985" alt="screen shot 2019-01-29 at 11 12 09 am" src="https://user-images.githubusercontent.com/1580512/51891364-462fc080-23b8-11e9-9705-ba97c7c5a74f.png">

**Comment by blanchonvincent** [comment]
By the way, the field "Last login" in the user profile is correctly updated:

<img width="639" alt="screen shot 2019-01-29 at 11 45 33 am" src="https://user-images.githubusercontent.com/1580512/51892496-88a6cc80-23bb-11e9-9bca-6cc9087dc82a.png">

**Comment by blanchonvincent** [comment]
It works only if you use `applicationId` as parameter in the `login` endpoint. I guess that is the expected behavior,

**Comment by robotdan** [comment]
Hi @blanchonvincent - it is the designed behavior. The recent logins only show "application" logins. In general we do not expect anyone to login w/out an application Id. 

However - we have seen users get confused here before, so perhaps it warrants another look. I'll bring this up with the team. 

Thanks for all of the feedback! Thanks for using FusionAuth.

**Comment by robotdan** [comment]
Re-open to review if we should show "global" logins on the recent logins tab.
