### ISSUE TITLE
Shutdown.bat missing

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#672]
### Description 

When you download the windows zip installer using https://fusionauth.io/download you have a startup batch file but not a shutdown batch file.

It's unclear how you should cleanly shut down FA.

### Steps to reproduce
1. Go to https://fusionauth.io/download
2. Click 'windows'
3. Follow instructions
4. run `ls fusionauth\bin` in powershell

### Expected behavior
Would like a shutdown.bat

### Platform

Windows10, FA 1.17.0

**Comment by robotdan** [comment]
This is intentional, there is no `shutdown.bat` for the Windows Fast Path install.
