### ISSUE TITLE
Logs not written to log directory for windows zip file install

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#673]
### Description 

When you download the windows zip installer using https://fusionauth.io/download and start things up you don't have a logs directory.

### Steps to reproduce
1. Go to https://fusionauth.io/download
2. Click 'windows'
3. Follow instructions to download
4. run .\fusionauth\bin\startup.bat
5. Wait
6. Logs don't appear in the logs directory

Instead, they are in the output of the batch file terminal.

### Expected behavior

Logs should be stored in the `logs` directory. 

### Platform

Windows10, FA 1.17.0

**Comment by robotdan** [comment]
Related : https://github.com/FusionAuth/fusionauth-issues/issues/672

This is because the services are running interactively and the logging is written to to `stdout`.

**Comment by mooreds** [comment]
Ah, if this is intentional I'll just close.
