### ISSUE TITLE
Use password forget flow api without mail template when send mail is false

### ISSUE THREAD

**Issue by nulian** [FusionAuth/fusionauth-issues#674]
We use the password forgotten flow without sending the mail from fusionauth. 
But it is mandatory to set a password forgotten mail template even though we never send mail from fusionauth.
Would be nice if it's possible to use it without having to set a fake template.

Had issue on fusionauth 1.15.8

**Comment by nulian** [comment]
Yes because we don't use that template and use our own forgot password flow.
With the sendForgotPasswordEmail flag always set too false.

It is a bit weird we need to set the mail template to make it work.

**Comment by mooreds** [comment]
Gotcha, thanks for the explanation.

**Comment by andrewpai** [comment]
Closing, as this is now a supported behavior.
