### ISSUE TITLE
Unrestricted verification emails sending via /email/verify endpoint

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#675]
### Description
I've been playing around with `/email/verify` endpoint and stumbled upon one aspect of its behaviour that raised my doubts. Namely, it is possible for unauthenticated user to send an unlimited number of verification messages. Malicious user may try to annoy legitimate user of our service with verification emails flood. I suppose that preventing the service from sending a verification message to users who have already verified their email address is not a big problem. Also in my opinion, if such request appear, the response for the verification email request form should not be changed to prevent user enumeration attacks.

There is also scenario where malicious user creates an account on someone's others email address, and then floods his inbox. This one is not so easy to address. It is dangerous, because one may want to annoy somebody, which is bad, because we don't want to annoy anybody with emails from our domain. But more importantly, one can attempt to flood [spamtrap](https://en.wikipedia.org/wiki/Spamtrap) addresses and effectively decrease our domain reputation.

If someone contacts our support with an issue about _verification email flood_, it would be nice if we could prevent such emails delivery by, for example, locking the unwanted account. For the spamtrap scenario, I have no experience in email campaigns, and thus I have no solution to propose. Maybe someone from the community or dev team will have more knowledge in that matter. Maybe some rate limiting is enough? IDK

Update: Also, It would be nice if the reset password emails would be sent only to active, verified accounts. This change might be _breaking_ in some installations since email verification is not mandatory in the FusionAuth. So maybe configuration option in tenant or system settings?

**Comment by mooreds** [comment]
Just to confirm, is this the endpoint you're referring to?

https://fusionauth.io/docs/v1/tech/apis/users#verify-a-users-email

**Comment by mgetka** [comment]
No, I'm not referring to the API, but to public views available at `/email/verify` (eg. https://login.fusionauth.io/email/verify) and `/password/forgot` (eg. https://login.fusionauth.io/password/forgot).

**Comment by mgetka** [comment]
Insights on _reset password_ functionality mentioned in an update to the original post, are also applicable to passwordless login via _magic link_.

**Comment by robotdan** [comment]
I think this will be resolved under https://github.com/FusionAuth/fusionauth-issues/issues/905, we will be adding rate limiting for this workflow.
