### ISSUE TITLE
Registration with Identity Providers

### ISSUE THREAD

**Issue by ashokgelal** [FusionAuth/fusionauth-issues#678]
## Registration using Identity Providers buttons is missing

I believe I have seen the buttons before but somehow they got disappeared. I've enabled `Create Registration` setting as well. Am I missing something to enable something?

![image](https://user-images.githubusercontent.com/401055/84443293-89c94a00-abfc-11ea-9ade-0eaa4011fbc6.png)

![image](https://user-images.githubusercontent.com/401055/84443199-5b4b6f00-abfc-11ea-8a32-d83731e93ebe.png)

![image](https://user-images.githubusercontent.com/401055/84443256-761de380-abfc-11ea-9566-a0c0095edb6f.png)

**Comment by mooreds** [comment]
I'm sorry, I'm not sure exactly what you're trying to accomplish. The `create registration` setting in the application form just lets FusionAuth create a registration (associating a user with an application) once the identity provider (google, for example) tells FA the user exists. 

Can you explain a bit more about what you want to do?

**Comment by ashokgelal** [comment]
Basically, I'm trying to let user see the `Login with Google` button on the register page as well. I understand that if they use Login with Google button on the login page, it will let you register as well. But I need the button on the register page as well. Here is an example from DigitalOcean: 
![image](https://user-images.githubusercontent.com/401055/84444605-681d9200-abff-11ea-958a-3bbce5b5e55c.png)

I hope that makes sense.

**Comment by mooreds** [comment]
Ah, thank you for clearing that up.

I believe this issue is the same one: https://github.com/FusionAuth/fusionauth-issues/issues/554

If so, this functionality can be achieved by modifying your template, as outlined in #554, but isn't something that comes out of the box. (Though it is a bit confusing because they reference sign in in the template.)

**Comment by ashokgelal** [comment]
That's what I figured. So, I created a new theme based on FusionAuth template, made some tiny adjustments just to play with it and for last 10 minutes I'm struggling on how to actually apply the theme. I watched the video too but I don't see anyway to enable/apply this new theme 😥

**Comment by ashokgelal** [comment]
Ok. Just found this: https://fusionauth.io/community/forum/topic/42/how-do-you-assign-a-theme-to-an-application?_=1591915213809
I think the [Theme documentation](https://fusionauth.io/docs/v1/tech/themes/) needs to be updated to mention that a theme can be applied by going to the Tenant page.

**Comment by mooreds** [comment]
Ah, glad you figured it out. I filed an issue about the theme docs being a bit out of date.

https://github.com/FusionAuth/fusionauth-issues/issues/679

If your question is answered, please feel free to close this issue.

**Comment by ashokgelal** [comment]
Thank you!
