### ISSUE TITLE
Taking a user directly to the registration page

### ISSUE THREAD

**Issue by ashokgelal** [FusionAuth/fusionauth-issues#686]
Continuing the discussion from [here](https://fusionauth.io/community/forum/topic/165/taking-a-user-directly-to-the-registration-page/3):

> What's a good way to generate a URL that would take a user directly to the registration page (bypassing the login page) and with a redirect URL? It's an ASP .NET Core app. Do I need to use an API or is there a more "direct" way?

My use case is that we'd like to add a `Register` button on the marketing site that would take a user directly to the registration page and after completing the registration, it would take the user back to the main app (as determined by a redirect URL set in the query parameter). There are other use cases where we'd need to directly send a user to the Registration/Signup page.

> I assume you want to use the FusionAuth provided registration page?

That's correct.

**Comment by mooreds** [comment]
So what you'd like is a way to provide an application id and get back a valid registration link, the same way you can get back `application.oauthConfiguration.logoutURL` from an application. 

Is that a correct summation, @ashokgelal ? Or are you looking for something else?

**Comment by voidmain** [comment]
I'm going to guess that @ashokgelal is looking for a pattern that can be used to create a URL directly to FusionAuth's registration form. If that's the case, then the form of the URL is this:

```
<FusionAuth_BaseURL>/oauth2/register?client_id=<Configured_client_id>&redirect_uri=<Configured_redirect_uri>&response_type=code&state=<Your_CSRF_Token>
```

Here's a reified version:

```
https://fusionauth.example.com/oauth2/register?client_id=132a81a4-55be-9332-aa34-ec605e27f308&redirect_uri=https%3A%2F%app.example.com%2Flogin&response_type=code&state=RGRlKSP4SzUYLNsiF9ri4DJ9GjxACU6Fo3lrDYUbnWA
```

This will drop you directly into the registration process and it will complete the OAuth process correctly. I've verified that the above pattern works on a local copy.

**Comment by mooreds** [comment]
@voidmain do we make any guarantees about the future proofing of that URL?

**Comment by voidmain** [comment]
@mooreds yes for anything inside an OAuth workflow. The reason we keep these URLs consistent is that we are inside OAuth and eventually have to complete the OAuth grant we are in. 

There might be new parameters in the future but likely they wouldn’t be required. 

We are also planning on adding the registration URL to the ”View” dialog for Applications in the Integration section so that it makes it easier to find and use.

We can use this ticket to track that feature.

**Comment by robotdan** [comment]
As @voidmain mentioned we can just add this link to the integration details in the View dialog to make it easier to find and integrate.
