### ISSUE TITLE
Ok, so the lambda looks correct. This "hack" used to work, I think a change we made in 1.17.0 may have broken that.

### ISSUE THREAD

**Issue by joydeb28** [FusionAuth/fusionauth-issues#689]
Ok, so the lambda looks correct. This "hack" used to work, I think a change we made in 1.17.0 may have broken that. 

If I am correct, it will work on 1.16.0, but not 1.17.0. 

We'd either have to fully support a LinkedIn login option, or add another configuration option to allow a reconcile lambda to override the `user.email` field.

_Originally posted by @robotdan in https://github.com/FusionAuth/fusionauth-issues/issues/34#issuecomment-644952497_

**Comment by robotdan** [comment]
Is this an request for something?

**Comment by voidmain** [comment]
Looks like a duplicate of #34
