### ISSUE TITLE
Lambda not used

### ISSUE THREAD

**Issue by TanguyGiton** [FusionAuth/fusionauth-issues#690]
### Description 
I've just updated to 1.17.1.

I use Azure AD as an Identity Provider with a custom lambda to reconcile the user:

```js
function reconcile(user, registration, jwt) {
  console.info(JSON.stringify(jwt, null, ' '));
  user.email = jwt.upn;
} 
```
Since the update, I can't use Azure AD to connect. This is what I get when I active the Identity Provider Debug mode:

```
OpenID Connect IdP Response Debug Log for [Office 365] with Id [1d8e48a5-a612-47cd-8495-6961e0ce4c0e]

6/17/2020 03:42:25 PM GMT Call the configured Token endpoint [https://login.microsoftonline.com/f7a9a205-b15a-47dc-b871-a0ba939b9790/oauth2/token]
6/17/2020 03:42:25 PM GMT Endpoint returned status code [200]
6/17/2020 03:42:25 PM GMT Access Token Response:
{
  "token_type" : "Bearer",
  "expires_in" : "3599",
  "ext_expires_in" : "3599",
  "expires_on" : "1592412145",
  "access_token" : "PAQABAAAAAAAm...",
  "refresh_token" : "0.AQwABaKp9...",
  "id_token" : "eyJ0eXAi..."
}
6/17/2020 03:42:25 PM GMT Call the configured Userinfo endpoint [https://login.microsoftonline.com/2e9567eb-dcc5-49d7-aa29-ce4d76e3cc94/openid/userinfo]
6/17/2020 03:42:26 PM GMT Endpoint returned status code [200]
6/17/2020 03:42:26 PM GMT Build a new user object from the returned Userinfo response:
{
  "amr" : "[\"pwd\",\"mfa\"]",
  "family_name" : "",
  "given_name" : "Tanguy",
  "ipaddr" : "xxx",
  "name" : "",
  "oid" : "2e9567eb-dcc5-49d7-aa29-ce4d76e3cc94",
  "rh" : "0.AQw....",
  "sub" : "8uNe...",
  "tid" : "2e9567eb-dcc5-49d7-aa29-ce4d76e3cc94",
  "unique_name" : "tg@email.com",
  "upn" : "tg@email.com",
  "uti" : "xH8wPs-VX...",
  "ver" : "1.0"
}
6/17/2020 03:42:26 PM GMT The identity provider was unable to reconcile the email address. An email address is required to complete this request.
```
I have also activated the debug mode for the lambda, but there is nothing in the Event log.

It seems that the lambda is not used during the process.

**Comment by mooreds** [comment]
Can you tell me what you see in the event log with this code?

```
function reconcile(user, registration, jwt) {
  console.error("lambda executing");
  console.error(JSON.stringify(jwt, null, ' '));
} 
```

**Comment by TanguyGiton** [comment]
Still nothing in the event log. I tried twice: with lambda debug enabled and not.

**Comment by mooreds** [comment]
Great, thanks.

What version of Azure AD are you using? Per https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/azure-ad we only support 1.0 at this time.

**Comment by TanguyGiton** [comment]
I use Azure AD for Office 365 only for Office 365 users. I don't know which version it is, but I assume it is v.2.

However I don't think this is a compatibility problem for two reasons:
- it was working with FusionAuth v.1.15.8, and
- the `OpenID Connect IdP Response Debug Log` show that I receive the correct information from the IdP. 

I think the problem is at the reconcile step.

**Comment by robotdan** [comment]
This is an issue with the latest release of FusionAuth. We sort of closed a loop hole, that I think was allowing some existing integrations to work. 

We have opened an issue to potentially repeal this decision and just ensure we adequately describe the risks.  https://github.com/FusionAuth/fusionauth-issues/issues/691

**Comment by robotdan** [comment]
Planning to reverse this in a patch.

**Comment by robotdan** [comment]
This should work for you again in version 1.17.2

**Comment by TanguyGiton** [comment]
I upgraded Fusion Auth to v.17.1.2 and I still have the same problem.

Here's the IdP log:

```
OpenID Connect IdP Response Debug Log for [Office 365] with Id [1d8e48a5-a612-47cd-8495-6961e0ce4c0e]

6/18/2020 09:27:57 AM GMT Call the configured Token endpoint [https://login.microsoftonline.com/7ac96444-4e1c-4489-b3b0-ceedb260bc49/oauth2/token]
6/18/2020 09:27:57 AM GMT Endpoint returned status code [200]
6/18/2020 09:27:57 AM GMT Access Token Response:
{
  "token_type" : "Bearer",
  "expires_in" : "3599",
  "ext_expires_in" : "3599",
  "expires_on" : "1592476077",
  "access_token" : "PAQAB....",
  "id_token" : "eyJ0eX....."
}
6/18/2020 09:27:57 AM GMT Call the configured Userinfo endpoint [https://login.microsoftonline.com/7ac96444-4e1c-4489-b3b0-ceedb260bc49/openid/userinfo]
6/18/2020 09:27:58 AM GMT Endpoint returned status code [200]
6/18/2020 09:27:58 AM GMT Build a new user object from the returned Userinfo response:
{
  "amr" : "[\"pwd\",\"mfa\"]",
  "family_name" : "Giton",
  "given_name" : "Tanguy",
  "ipaddr" : "xxx.xxx.xxx.xxx",
  "name" : "Tanguy Giton",
  "oid" : "7ac96444-4e1c-4489-b3b0-ceedb260bc49",
  "rh" : "0.A.....",
  "sub" : "8uNe.....",
  "tid" : "7ac96444-4e1c-4489-b3b0-ceedb260bc49",
  "unique_name" : "tg@ikno.fr",
  "upn" : "tg@ikno.fr",
  "uti" : "JGr5p.....",
  "ver" : "1.0"
}
6/18/2020 09:27:58 AM GMT The identity provider was unable to reconcile the email address. An email address is required to complete this request.
```

And still no log for the lambda.

I also tried to recreate another OpenId IdP with the same configuration, but the same thing is happening. 

Do you have an idea of another OpenId IdP other than Azure AD that I can easily test?

**Comment by TanguyGiton** [comment]
In version 1.15.8, the logs looked like this:

```
OpenID Connect IdP Response Debug Log for [Office 365] with Id [1d8e48a5-a612-47cd-8495-6961e0ce4c0e]

4/6/2020 02:27:52 AM UTC Call the configured Token endpoint [https://login.microsoftonline.com/1d8e48a5-a612-47cd-8495-6961e0ce4c0e/oauth2/token]
4/6/2020 02:27:52 AM UTC Endpoint returned status code [200]
4/6/2020 02:27:52 AM UTC Access Token Response:
{
  "token_type" : "Bearer",
  "expires_in" : "3599",
  "ext_expires_in" : "3599",
  "expires_on" : "1586143672",
  "access_token" : "PAQ...",
  "refresh_token" : "0.AQw...",
  "id_token" : "eyJ0e...."
}
4/6/2020 02:27:52 AM UTC Call the configured Userinfo endpoint [https://login.microsoftonline.com/1d8e48a5-a612-47cd-8495-6961e0ce4c0eopenid/userinfo]
4/6/2020 02:27:52 AM UTC Endpoint returned status code [200]
4/6/2020 02:27:52 AM UTC Build a new user object from the returned Userinfo response:
{
  "aud" : null,
  "exp" : null,
  "iat" : null,
  "iss" : null,
  "nbf" : null,
  "sub" : "qsxc...",
  "jti" : null,
  "amr" : "[\"pwd\"]",
  "family_name" : "Doe",
  "given_name" : "John",
  "ipaddr" : "xxx.xxx.xxx.xxx",
  "name" : "John Doe",
  "oid" : "1d8e48a5-a612-47cd-8495-6961e0ce4c0e",
  "tid" : "1d8e48a5-a612-47cd-8495-6961e0ce4c0e",
  "unique_name" : "jd@email.fr",
  "upn" : "jd@email.fr",
  "uti" : "gKx...",
  "ver" : "1.0"
}
4/6/2020 02:27:52 AM UTC Invoke configured lambda with Id [1f910891-04a3-4635-a2f9-fe2c582453cf]
4/6/2020 02:27:52 AM UTC User to reconcile: 
{
  "breachedPasswordLastCheckedInstant" : null,
  "breachedPasswordStatus" : null,
  "encryptionScheme" : null,
  "factor" : null,
  "id" : null,
  "password" : null,
  "passwordChangeReason" : null,
  "passwordChangeRequired" : false,
  "passwordLastUpdateInstant" : null,
  "salt" : null,
  "verified" : false,
  "preferredLanguages" : [ ],
  "memberships" : [ ],
  "registrations" : [ {
    "data" : { },
    "preferredLanguages" : [ ],
    "tokens" : {
      "1d8e48a5-a612-47cd-8495-6961e0ce4c0e" : "0.AQ..."
    },
    "applicationId" : "1d8e48a5-a612-47cd-8495-6961e0ce4c0e",
    "authenticationToken" : null,
    "cleanSpeakId" : null,
    "id" : null,
    "insertInstant" : null,
    "lastLoginInstant" : null,
    "roles" : [ ],
    "timezone" : null,
    "username" : null,
    "usernameStatus" : null,
    "verified" : false
  } ],
  "active" : false,
  "birthDate" : null,
  "cleanSpeakId" : null,
  "data" : { },
  "email" : "jd@email.com",
  "expiry" : null,
  "firstName" : "John",
  "fullName" : "John Doe",
  "imageUrl" : null,
  "insertInstant" : null,
  "lastLoginInstant" : null,
  "lastName" : "Doe",
  "middleName" : null,
  "mobilePhone" : null,
  "parentEmail" : null,
  "tenantId" : null,
  "timezone" : null,
  "twoFactorDelivery" : null,
  "twoFactorEnabled" : false,
  "twoFactorSecret" : null,
  "username" : null,
  "usernameStatus" : null
}
4/6/2020 02:27:52 AM UTC The user with the email address [jd@email.com] already exists.
4/6/2020 02:27:52 AM UTC Merge the reconciled user from the Identity Provider into the FusionAuth user.
4/6/2020 02:27:52 AM UTC User is already registered for application with Id [1d8e48a5-a612-47cd-8495-6961e0ce4c0e].
4/6/2020 02:27:52 AM UTC User has successfully been reconciled and logged into FusionAuth.
4/6/2020 02:27:52 AM UTC Authentication type: OPENID_CONNECT
4/6/2020 02:27:52 AM UTC Authentication state: Authenticated
```

Now, it looks like the lambda is skipped.

**Comment by TanguyGiton** [comment]
Yes, I can confirm that.

For information, I changed some uuid in the log for confidentiality reasons. So don't be surprised if there are inconsistencies.

The last log I sent corresponds to the case where it was working, i.e. with version 1.15.8 (see date).

I tried 3 different lambda: my original function, the function proposed by @mooreds and the default function for OpenId. None of them works.

My hypothesis is that the order of execution has been changed: it seems that now the lambda is called after the user is reconciled, whereas before, the lambda was called before, allowing to reconcile the email before searching the user in FusionAuth.

**Comment by TanguyGiton** [comment]
I set up Google as IdP and it's working. And in the logs, you can see that the two steps have been reversed, hence the current problem :

```
Google IdP Response Debug Log

6/18/2020 11:01:12 AM GMT Call the [https://www.googleapis.com/oauth2/v3/tokeninfo] endpoint.
6/18/2020 11:01:12 AM GMT Endpoint returned status code [200]
6/18/2020 11:01:12 AM GMT Endpoint response:
{
  "iss" : "accounts.google.com",
  "azp" : "8527",
  "aud" : "852",
  "sub" : "1122",
  "hd" : "",
  "email" : "tg@email.com",
  "email_verified" : "true",
  "at_hash" : "yMc",
  "name" : "Tanguy",
  "picture" : "",
  "given_name" : "Tanguy",
  "family_name" : "",
  "locale" : "fr",
  "iat" : "1592478072",
  "exp" : "1592481672",
  "jti" : "309c74...",
  "alg" : "RS256",
  "kid" : "b16de...",
  "typ" : "JWT"
}
```
```
6/18/2020 11:01:12 AM GMT The user with the email address [tg@email.com] already exists.
6/18/2020 11:01:12 AM GMT Invoke configured lambda with Id [df650ec5-236b-1953-5415-24aafc7c4079]
```
6/18/2020 11:01:12 AM GMT Updating user: 
{
  "breachedPasswordLastCheckedInstant" : null,
  "breachedPasswordStatus" : null,
  "encryptionScheme" : null,
  "factor" : null,
  "id" : "1d8e48a5-a612-47cd-8495-6961e0ce4c0e",
  "password" : null,
  "passwordChangeReason" : null,
  "passwordChangeRequired" : false,
  "passwordLastUpdateInstant" : 1589366451324,
  "salt" : null,
  "verified" : true,
  "preferredLanguages" : [ "fr_FR" ],
  "memberships" : [ ],
  "registrations" : [ ],
  "active" : true,
  "birthDate" : "",
  "cleanSpeakId" : null,
  "data" : { },
  "email" : "tg@email.com",
  "expiry" : null,
  "firstName" : "Tanguy",
  "fullName" : "Tanguy",
  "imageUrl" : "",
  "insertInstant" : 1576078315423,
  "lastLoginInstant" : 1592478007816,
  "lastName" : "GITON",
  "middleName" : null,
  "mobilePhone" : null,
  "parentEmail" : null,
  "tenantId" : "1d8e48a5-a612-47cd-8495-6961e0ce4c0e",
  "timezone" : null,
  "twoFactorDelivery" : "None",
  "twoFactorEnabled" : true,
  "twoFactorSecret" : null,
  "username" : null,
  "usernameStatus" : "ACTIVE"
}
6/18/2020 11:01:12 AM GMT User is already registered for application with Id [1d8e48a5-a612-47cd-8495-6961e0ce4c0e].
6/18/2020 11:01:12 AM GMT User has successfully been reconciled and logged into FusionAuth.
6/18/2020 11:01:12 AM GMT Authentication type: GOOGLE
6/18/2020 11:01:12 AM GMT Authentication state: Authenticated
```

**Comment by robotdan** [comment]
Yes, you are correct. We changed the order of operation.

The reason for this is that it allows the lambda to operate on the actual user when the user exists, and it allowed us to remove a bunch of gnarly merging logic. 

I'll think about this one more, one option may be to run the lambda a second time if we detect the email changed. 

For example, currently it does this:

1. Assume `email` claim is returned by the OpenID Connect provider since this is a registered claim
2. Retrieve the user based upon that `email` address, user may exist, or they may not
3. Call the lambda with the user
4. Complete our reconcile / login procedures

In theory we could do something like this:

1. Assume `email` claim is returned by the OpenID Connect provider since this is a registered claim
2. Retrieve the user based upon that `email` address, user may exist, or they may not
3. Call the lambda with the user
4. If the email changed during the lambda invocation, start over at step 2 with the updated `email` claim.

The downside is we are calling the lambda twice - which is currently ok because we know the lambda is not making external requests, but this could change in the future.

**Comment by TanguyGiton** [comment]
Okay, I get it. It's a shame that Azure AD is not OpenId compliant.
 Unfortunately, it's a must-have Identity Provider.

How about two hooks in the process?

A first lambda, before reconciling the user that would only allow to manipulate the JWT.

A second lambda, after having reconciled the user allowing to manipulate the user (like the lambda already present).

Thus, these two lambda are explicit and would avoid side effects.

**Comment by robotdan** [comment]
@TanguyGiton yes, this is an option for sure. While, perhaps not as flexible, if we wanted to keep these steps discrete, we could also add a parameter to the OpenID Connect config to identify the name of the claim. 

It would default to `email`, and it could be modified to find the email under a different claim such as `upn` with Azure. 

This would work as long as we can find a claim using a JSON pointer.  ( https://tools.ietf.org/html/rfc6901 )

**Comment by robotdan** [comment]
@TanguyGiton Once version 1.17.3 is available you should be able to make this work again. There will be a new configuration option for OpenID Connect called Email claim. This will default to `email`, but for Azure you'll be able to change it to `upn`, `unique_name` or whatever claim the email happens to be under.

**Comment by TanguyGiton** [comment]
Thank you !

I had also thought about that but I found it interesting to use a lambda for more flexibility. Especially concerning Azure AD which is inconsistent depending on whether it is a personal or professional account.

**Comment by TanguyGiton** [comment]
Confirming that it's functional again. Thank you again.
