### ISSUE TITLE
OIDC with GitHub and Discord: impossible to set user.username

### ISSUE THREAD

**Issue by sycured** [FusionAuth/fusionauth-issues#698]
Hello,
In addition to Microsoft Azure AD (we're still investigating on it…), I'm working on GitHub and I've a little problem with username.

On my GitHub, I set my email to private so the jwt has ```"email": null```

So I try to set the ```user.username = jwt.login``` but I just see it inside registration and not the "parent":

<img width="1366" alt="Screen Shot 2020-06-20 at 00 22 18" src="https://user-images.githubusercontent.com/60801403/85193243-45891a00-b28c-11ea-957e-96d4ec17dd0c.png">

The lambda used:

```
function reconcile(user, registration, jwt) {
  if ((jwt.email === null) || (jwt.email == 'null')) {
    delete delete jwt.email;
    delete jwt.email;
    delete delete user.email;
    delete user.email;
  }
  user.username = jwt.login;
  user.usernameStatus = "ACTIVE";
  user.imageUrl = jwt.avatar_url;
  registration.username = jwt.login;
  user.data = user.data || {};
  user.data.company = jwt.company;
  user.data.location = jwt.location;
  user.data.hireable = jwt.hireable;
  user.data.twitter = jwt.twitter_username;
  console.debug(JSON.stringify(user, null, 2));
}
```

The debug:

```
Lambda invocation result.

Id: 26577e74-5a9e-4d2e-b355-f80009293112
Name: GitHub

{
  "active": false,
  "data": {
    "company": null,
    "location": "LATAM & USA & ASIA",
    "hireable": true
  },
  "memberships": [],
  "passwordChangeRequired": false,
  "preferredLanguages": [],
  "registrations": [],
  "twoFactorEnabled": false,
  "verified": false,
  "username": "sycured",
  "usernameStatus": "ACTIVE",
  "imageUrl": "https://avatars1.githubusercontent.com/u/60801403?v=4"
}
```

Have you an idea or fix to set the user correctly?
I try to have the cleanest setup possible and setting the username on profile is what I try to obtain.

If I can't remove the null at email, it's okay if it's not blocking…

Regards

FusionAuth 1.17.2 (rpm package) on Oracle Linux 8.2

edit: Same problem with Discord, registration.username has the value from jwt.username but it's impossible to set user.username… It's not very good because we've few applications and prefer to have only 1 place with the username to avoid duplicate or that one user take the username of another for a different app.

**Comment by mooreds** [comment]
This is working as designed, we don't allow the username field to be modified in a JWT when reconciling the user account from an OIDC provider.

From https://fusionauth.io/docs/v1/tech/lambdas/openid-connect-response-reconcile

>  The user.username field on the user will be ignored if modified by the lambda function. This is to mitigate the risks of an account takeover due to a non globally unique identifier. 

We have an open feature request to change this behavior: https://github.com/FusionAuth/fusionauth-issues/issues/691 

Please feel free to either vote for that issue, add your use case to it, or both.

**Comment by robotdan** [comment]
If you only want the username from GitHub or Discord for display purposes, you can set it on the registration. 

```
function reconcile(user, registration, jwt) {
  registration.username = jwt. login;
} 
```

Or you could set it anywhere else in user or registration data. But the `user.username` which can be used to authenticate cannot currently be set by the lambda as mentioned by @mooreds .

**Comment by sycured** [comment]
Ok thank you and I'll work on server side (micro service) to know which user has what fusionauth id.

For example, when GitHub's user without email (because set at private) and he comes back with for example LinkedIn or Google, it's different because I've the email and username so I'll look how I can do to reconcile correctly.

Maybe adding another provider connection inside it's profile, I'll look at fusionauth API otherwise, I'll do something at another level.
