### ISSUE TITLE
Can we add Identity Provider sign in/ login buttons to custom registration / login page built with Vue.js?

### ISSUE THREAD

**Issue by godguide1** [FusionAuth/fusionauth-issues#699]
### Description
Kudos to you guys for the wonderful job you've done. I must confess that FusionAuth is sweet!

Is it possible we add Identity Provider sign in and login buttons to our custom registration and Login page (Vuejs) respectively, just as we call register and login API?

**Comment by robotdan** [comment]
Great request @godguide1 - this has been requested previously as well under Issue https://github.com/FusionAuth/fusionauth-issues/issues/554

I'll close this one out as a duplicate. If you have any details not covered by issue #554 feel free to add additional comments. Thanks!
