### ISSUE TITLE
Feature: Swift Client Library for iOS

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#7]
### Problem

Developers building applications natively in iOS will likely be using Objective-C or Swift. Currently because there is not a native library for Swift or Objective-C, developers will need to use a third party REST client or use `NSURLSession` from the iOS SDK.

### Solution

Provide a FusionAuth client library written in Swift to provide native bindings for iOS developers. 

### Bounty
This issue qualifies for the FusionAuth bounty program. If you can get the Swift client library working, provide a stub and we can build the rest with out template system, see comment below.
https://fusionauth.io/write-for-fusionauth

If you are interested, please contact us using the link provided above and let us know.

### How to vote

Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Stub started. https://github.com/FusionAuth/fusionauth-swift-client

**Comment by f0rever-johnson** [comment]
Thank You Thank You

**Comment by robotdan** [comment]
Thanks to @f0rever-johnson , there is a working version on his repo. 
https://github.com/f0rever-johnson/fusionauth-swift-client

Next steps are to integrate this into our template and get the build working. 
https://github.com/FusionAuth/fusionauth-client-builder
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/swift.client.ftl

**Comment by f0rever-johnson** [comment]
The official repo is archived. 
Release v1.0 @ https://github.com/f0rever-johnson/fusionauth-swift-client

**Comment by robotdan** [comment]
If anyone is interested in submitting a PR to build a Swift client either from scratch, or using the work that @f0rever-johnson has already completed, that would be great!

https://github.com/FusionAuth/fusionauth-client-builder
