### ISSUE TITLE
Does FusionAuth support SAML requests with embedded signatures when FusionAuth is the SP?

### ISSUE THREAD

**Issue by patrickvalle** [FusionAuth/fusionauth-issues#700]
### Description
SAML newbie here, so I'll apologize in advance for any confusion. I'm wondering if FusionAuth supports SAML requests with embedded signatures (HTTP-POST binding), similar to what's outlined @ https://www.samltool.com/generic_sso_req.php. I'm trying to figure out how to sign the SAML requests coming from FusionAuth.

**Comment by mooreds** [comment]
Yes, it should. For example, Zendesk uses the HTTP POST binding: https://support.zendesk.com/hc/en-us/articles/203663676-Enabling-SAML-single-sign-on

And we've implemented FusionAuth as an IdP for Zendesk: https://fusionauth.io/docs/v1/tech/samlv2/zendesk

Which SP are you trying to integrate with?

**Comment by robotdan** [comment]
Possibly related to issue https://github.com/FusionAuth/fusionauth-issues/issues/365.

**Comment by patrickvalle** [comment]
@mooreds Sorry, I should have been more clear- I'm using FusionAuth as the SP and wondering if I can make HTTP-POST binded AuthnRequests to an IdP.

**Comment by mooreds** [comment]
So I imagine you've seen this doc, but if not it's worth a read: https://fusionauth.io/docs/v1/tech/identity-providers/samlv2/

I haven't implemented this myself, but I think the process of signing a SAML request when FusionAuth is the SP goes like this:
* find the public key
* import it into the FusionAuth keymaster
* select that as the `verification key`
* FusionAuth should sign the request with that public key. 

I'm not sure I'm totally addressing your question, though. Is that what you've attempted and ran into issues?

**Comment by patrickvalle** [comment]
@mooreds My understanding of the `verification key` field you're referencing is that it's used to verify the **response** coming _back_ from the IdP. What I'm trying to do (I think) is to encrypt my **request** going _to_ the IdP.

**Comment by mooreds** [comment]
Ah, you are correct, that is the role of the `verification key`.

I don't believe FusionAuth supports signing our SAML response when we are acting as the SP.

I didn't see anything in /admin/identity-provider/add/SAMLv2 config screens nor in the API docs: https://fusionauth.io/docs/v1/tech/apis/identity-providers/samlv2 

Can share which SAML IdP requires this?

**Comment by mooreds** [comment]
Here's the forum post: https://fusionauth.io/community/forum/topic/188/does-fusionauth-support-saml-requests-with-embedded-signatures-when-fusionauth-is-the-sp

**Comment by mooreds** [comment]
@patrickvalle happy to convert this to a feature request if you can provide more details about the use case.

Cheers!

**Comment by mooreds** [comment]
@patrickvalle should I convert this to a feature request? If so, would love as many details as you can provide. 

Or should I close this?

Thanks!

**Comment by robotdan** [comment]
This feature was added in 1.20.0. You can now configure the SAML v2 IdP to sign the AuthN request, and select to use HTTP Post or HTTP Redirect bindings. 

Please re-open if it still does not work after version 1.20.0.

Thanks!

**Comment by yogendratamang48** [comment]
Version: 1.22.2
There is "**sign request**" toggle button as well as "**Request signing key**"  in the UI, However when I see **meta data** url for SP, we don't see those signing request key.

Metadata looks like this:

```xml
<ns2:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
```

**Comment by robotdan** [comment]
@yogendratamang48 I think that issue will be resolved by https://github.com/FusionAuth/fusionauth-issues/issues/1067.
