### ISSUE TITLE
[Enhance] Support Pagination on the Retrieve a User’s Comments API

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#71]
### Problem
First of all, the link "Retrieve a User’s Comments" on https://fusionauth.io/docs/v1/tech/apis/user-comments does not work, it does not scroll down.

This endpoint returns comments sorted by the ones added first. So I guess it becomes quickly not manageable if the user has 200 or 300 comments.

### Solution
If we could have a paginated endpoint sorted the new ones, like `/api/report/user-login` (by the way I do not see this endpoint in the documentation), it could be perfect.

**Comment by robotdan** [comment]
Thanks @blanchonvincent for the feedback. 

> First of all, the link "Retrieve a User’s Comments" on https://fusionauth.io/docs/v1/tech/apis/user-comments does not work, it does not scroll down.

Thanks, fixed. 

> This endpoint returns comments sorted by the ones added first. So I guess it becomes quickly not manageable if the user has 200 or 300 comments.

Agreed, I'll update this issue to be a feature request to paginate this API. Do you expect to have many comments ( > 100) any time soon?

> /api/report/user-login

Regarding this API, this is how we retrieve the recent logins in the UI under the manage user panel. This API will be documented in the upcoming release as `/api/user/recent-logins`.  

And the `/api/report/login` will be enhanced to take a `userId` or `loginId` to return a login report for an individual user. 

Thanks!

**Comment by robotdan** [comment]
Ok, thanks for the additional information on your use case. I don't know that this will make it out in the next release, but it is a fairly easy fix. We'll get it into the queue. 

Thanks

**Comment by robotdan** [comment]
Added User Comments to this issue https://github.com/FusionAuth/fusionauth-issues/issues/374

**Comment by robotdan** [comment]
Closing, will fix under #374
