### ISSUE TITLE
`aud` claim is provided for a non registered user during the authorization code grant

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#713]
### Description 

The login and oauth APIs should return the same JWTs for a user who is authenticated. But this doesn't seem to be the case when a user is not registered for an application. In this case, the login API doesn't return the `aud` claim, but the oauth code flow does.

### Steps to reproduce
1. Create an application
1. Create a user, but do not register them for the application.
1. Run the following curl command: `curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/login' -d '{"loginId": "<EMAIL>", "password": "<PASSWORD>", "applicationId" : "APPLICATION_ID" }'`
1. View the JWT ( https://fusionauth.io/learn/expert-advice/dev-tools/jwt-debugger )

I saw this: 

```
{
  "exp": 1593532064,
  "iat": 1593528464,
  "iss": "acme.com",
  "sub": "2df13f18-01cc-48a4-b97a-2ab04f98d006",
  "authenticationType": "PASSWORD",
  "email": "parent2@example.com",
  "email_verified": true
}
```

Now, do the same thing with the authorization code grant.
1. Set up the node example application: https://github.com/FusionAuth/fusionauth-example-node
1. Look in stdout and see examine the JWT.

Here's what I saw (same user, same application):

```
{
  "aud": "a5d84462-193d-4c0d-9f20-d05a8a584710",
  "exp": 1593532641,
  "iat": 1593529041,
  "iss": "acme.com",
  "sub": "2df13f18-01cc-48a4-b97a-2ab04f98d006",
  "authenticationType": "PASSWORD",
  "email": "parent2@example.com",
  "email_verified": true
}
```

Note that this has the `aud` claim.

### Expected behavior

Preferred: the `aud` claim would be absent from both JWTs. 

Also acceptable: `aud` present in both JWTs.

### Platform

FusionAuth 1.17.0 is what I tested this on.

### Additional context

This arose from this forum issue: https://fusionauth.io/community/forum/topic/184/recommended-approach-for-validation/5 . 

Thanks to @mgetka for reporting!

**Comment by mgetka** [comment]
TBH, I don't not exactly understand why `aud` claim should not be present in such JWTs. In the JWT, there are FusionAuth specific fields, like `roles` and `applicationId`, which presence or absence determines whether the user is registered in the application or not. For me, it is a clear solution - registrations are a concept specific for the FusionAuth domain, and thus they have influence on FusionAuth specific claims. Contrary to the claims mentioned above, claim `aud` is part of the JWT specification and the specification imposes its meaning. See [RFC 7519 4.1.3](https://tools.ietf.org/html/rfc7519#section-4.1.3):

> 4.1.3.  "aud" (Audience) Claim
>
> The "aud" (audience) claim identifies the recipients that the JWT is intended for.  Each principal intended to process the JWT MUST identify itself with a value in the audience claim.  If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected.  In the general case, the "aud" value is an array of case- sensitive strings, each containing a StringOrURI value.  In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value.  The interpretation of audience values is generally application specific. Use of this claim is OPTIONAL.

So, specific application requested the token and received it. It can therefore be said that the token was intended for the application, regardless of whether the user was registered in it or not. From the specification perspective, assigning `aud` claim for registered user's tokens and omitting the claim for unregistered ones, may suggests that the latter are some kind of _unbound tokens_ intented for use in _any_ application.

Anyway, fixing this issue can lead to breakage in some integrations. In the case of the second solution, if an application rely on the `aud` claim presence in the JWT generated via API to determine registration status - it will break. In the first solution - if an application rely on the `aud` claim in the OAuth2 provided token regardless the registration status - it will break. The latter is something what I did, and seeing how exotic my use case is, I need to admit that removing the `aud` from unregistered user' JWTs seems more safe in general. While writing this, my internal, RFC obsessed Richard is in agony :weary:

**Comment by mooreds** [comment]
Thanks for the further insight. I raised this as an issue because of the forum post but also because of this Slack message: https://fusionauth.slack.com/archives/CG00HG935/p1593525399189800?thread_ts=1593102805.170300&cid=CG00HG935 :

> I did some digging with the JWT token and aud issues, im having same issues with mgetka in post below where aud is generated on both Authorization_code or Password grant_types when user is not registered to applications. And I am not using Login API, using the Oauth2 grants.

This user is having issues with the [ambassador](https://www.getambassador.io/docs/latest/topics/using/filters/jwt/) proxy, and having a hard time distinguishing between a user who is authenticated for an application and one who is authorized.

I agree that backward compatibility issues should definitely be considered, but I'm also concerned about consistency between multiple ways to authenticate the user.

Also, I re-read your quote of the RFC and it doesn't say anything about when an `aud` claim should be presented, just how it should be consumed. Unless I missed something, which is entirely possible. :)

**Comment by mgetka** [comment]
RFC states that the field is optional, so implementer is free to decide when and if at all the claim should be present. So yes, mentioned _possible interpretation_, is just me, with my head in the clouds, wondering how one could interpret situation where some abstract service, sometimes include the claim and sometimes not :grinning:

**Comment by robotdan** [comment]
We may have an inconsistency with the Login API and the OAuth2 workflow. In the Login API (`/api/login`) the `aud` claim is not returned unless the user is registered. In the OAuth2 workflow, the `aud` claim is always returned as indicated here. 

In both cases, the `applicationId` and `roles` claims only exist if registered. 

At a minimum we should make these consistent. I kind of like having the `aud` claim in the JWT regardless if the user is registered because it still indicates the intended consumer.

**Comment by mooreds** [comment]
> I kind of like having the aud claim in the JWT regardless if the user is registered because it still indicates the intended consumer.

One reason to do the opposite is so that people filtering on only standard claims can have a way to differentiate between authenticated and authorized users. (See https://github.com/FusionAuth/fusionauth-issues/issues/713#issuecomment-651890429 for an example.)

**Comment by robotdan** [comment]
Internal note: We currently expect the `aud` claim to be present when using the `id_token_hint` on the OAuth2 logout endpoint even when the user is not registered. If we remove the `aud` claim for non-registered users in the OAuth2 flows, we'll need to account for this use case.

**Comment by robotdan** [comment]
Related https://github.com/FusionAuth/fusionauth-issues/issues/832

**Comment by robotdan** [comment]
Fixing under https://github.com/FusionAuth/fusionauth-issues/issues/832 to be consistent across all usages. Login API, Issue API, OAuth2.
