### ISSUE TITLE
Warning in log from mybatis: "An illegal reflective access operation has occurred"

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#721]
### Description 

When you first create a user after FusionAuth has started up, you see this message in the logs:

```
fusionauth_1  | WARNING: An illegal reflective access operation has occurred
fusionauth_1  | WARNING: Illegal reflective access by org.apache.ibatis.ognl.OgnlRuntime (file:/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/mybatis-3.4.6.jar) to method java.util.Collections$EmptyList.size()
fusionauth_1  | WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.ognl.OgnlRuntime
fusionauth_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
fusionauth_1  | WARNING: All illegal access operations will be denied in a future release
```

### Steps to reproduce
1. Install FusionAuth via Docker
1. Start it up
1. Create a user via the API (this also happens if you add a user via the admin ui )
```
API_KEY=...

curl -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/user/registration/' -d '{"registration": {"applicationId": "78bd26e9-51de-4af8-baf4-914ea5825355"}, "user" : { "parentEmail" : "email2@example.com", "birthDate": "2019-01-01", "email" : "email@example.com", "password": "password" }}'
```

You'll see the warning message.

Note that this doesn't happen if you add a consent to an existing user, or if you create a second user.

### Expected behavior

No warning message.

### Platform

FusionAuth 1.17.4, installed via Docker.

### Additional context

This doesn't appear to affect functionality in any way.

**Comment by robotdan** [comment]
This is just an issue with JDK 14 and MyBatis. Just a warning that this usage may not be allowed in a future version. Not much we can do until MyBatis fixes it.

**Comment by mooreds** [comment]
Looks like they fixed it in 3.5.3. We could upgrade mybatis to 3.5.5 (the latest version).

https://github.com/mybatis/mybatis-3/issues/1156#issuecomment-537478388

Looks like mybatis 3.5.x requires java8 or later. Not sure if that is a deal breaker: https://github.com/mybatis/mybatis-3/releases

**Comment by robotdan** [comment]
Ok, great. I'll take a look. We can use this issue to upgrade that dep.

**Comment by robotdan** [comment]
The guice dep required slf4j 2 alpha which seems to break logging based upon our version of logback. Needs some investigation before we ship it.
