### ISSUE TITLE
Entering incorrect credentials removes the query parameters leads to locale change issues

### ISSUE THREAD

**Issue by HamzaMoiyadi** [FusionAuth/fusionauth-issues#723]
### Description
When a user navigates to the `oauth/authorize` endpoint,  enters incorrect credentials and submits, upon error the refreshed page removes the query parameters. While this does not prevent the user from signing in if he/she enters the correct credentials, If I change the language/locale, I encounter an error page in the default fusionauth theme. 

### Steps to Reproduce

- Navigate to the login page
- Enter wrong credentials
- (Page reloads with no query params, and shows error notif)
- Change language
- Page reloads again, but this time the default fusionauth error screen saying `no_redirect_uri_found`

**Comment by robotdan** [comment]
This looks to be a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/623 which is fixed in version 1.17.0. Can you confirm you are on version 1.17.0 or later?

**Comment by HamzaMoiyadi** [comment]
Ah, my bad. We are on 1.16. 

Apologies for the inconvinience!
