### ISSUE TITLE
Passwordless login/magic links with O365 email addresses not working/invalid

### ISSUE THREAD

**Issue by shortstack** [FusionAuth/fusionauth-issues#725]
### Description 
User has an O365 or other email account with O365 underneath
Requests magic link and all links report back as invalid/expired despite not being expired
Can't log in via magic link / passwordless option :(

### Affects versions
Any

### Steps to reproduce
1. Go to website behind FusionAuth
2. Request magic link
3. Receive email with link
4. Click link and get "Your link has expired or is invalid. Please retry your request." despite expiry being set to 2 hours and not actually being expired

### Expected behavior
User is logged in and passes through to the application

### Platform
 - Device: Any device
 - OS: Any OS
 - Any browser

### Additional context
Is only an issue with users that have an email address registered with an O365 or an O365 backed account

**Comment by mooreds** [comment]
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/629 ? It seems to similar.

**Comment by shortstack** [comment]
sweet didn't see that one!

**Comment by mooreds** [comment]
Great, if it is a dupl, please feel free to close this one.

**Comment by shortstack** [comment]
yep, will continue to track the above
