### ISSUE TITLE
Passing an invalid or expired refresh token to /api/jwt/refresh returns 400 instead of 401

### ISSUE THREAD

**Issue by satazor** [FusionAuth/fusionauth-issues#729]
### Description

Passing an invalid or expired jwt/refresh responds with 400. The documentation states that a 401 response status code should be returned instead, see https://fusionauth.io/docs/v1/tech/apis/jwt#refresh-a-jwt

> 401 | The provided Refresh Token is either expired or has been revoked.

### Affects versions

- 1.17.5
- Possibly older ones

### Steps to reproduce

1. Call the `/api/jwt/refresh` with an invalid refresh token
2. See response status code

### Expected behavior

Expected 401 status code.

### Screenshots

N/A.

### Platform

 - Device: Desktop
 - OS: macOS

### Additional context

N/A

**Comment by robotdan** [comment]
Thanks @satazor we'll take a look. Either the doc is wrong, or the code is wrong. Not sure which yet. :-)

**Comment by robotdan** [comment]
May be fixed under this doc issue -> https://github.com/FusionAuth/fusionauth-site/pull/456

**Comment by mooreds** [comment]
Closing as the doc was updated.
