### ISSUE TITLE
Getting started in dev/staging - Fusionauth eating up all database connections

### ISSUE THREAD

**Issue by saul-gush** [FusionAuth/fusionauth-issues#733]
### Description
We just got going with Fusionauth. I love Fusionauth btw - Ive been testing out a few auth solutions, particularly Golang (our stack) and although I think Fusionauth is a bit of a resource hog, I think on the balance of things, its the best. I am running it in a Kubernetes pod. We are busy implementing the introspection through an NGINX ingress/caching and this is fantastic.  I learnt that I needed to reserve a fair amount request memory/cpu and set affinity to one node to keep the performance up. Otherwise I saw very large IO, eating up all the CPU/memory on the cluster and it seemed to have happened in cycles. This is just a dev/staging environment. Starting small with Fusionauth is a bit tough. I hope thats not going to be a cost problem when scaling upwards, not sure how many users can be hosted on say 1GB memory. 

Last night all our micro services stopped working and we worked out that Fusionauth was eating up all the database connections - this is a managed database using Postgresql. We have tried a few things like using the connection pooling using the session method. We ended up having to up the size of the postgresql database to accept all the connections. There are only 3 of us using it...

I started looking into maybe using Mysql as an alternative as Digitalocean allows 75 connections on the smallest instance. The problem is they have enforced that all tables must have a primary key so when I ran the Mysql scripts to load in the tables, some failed because they didn't have primary keys. 

I am not sure if maybe one performs better than the other or how the number of connections differ.

I'd prefer to use a managed database as it will have all the back up plans etc. 

What is your thoughts here? Is there a way to manage the number of connections or what is best practice? Is it worth looking into Mysql but then how would we make that work on Digitalocean?

**Comment by mooreds** [comment]
Heya,

Thanks for using FusionAuth! 

I moved this discussion to the forum, which is a better place for open ended questions like this: https://fusionauth.io/community/forum/topic/212/question-about-dev-staging-and-databases

We offer integration assistance through our paid editions. If you encounter a bug please open an issue with recreate steps and other relevant system information.
