### ISSUE TITLE
Email Verification Failed

### ISSUE THREAD

**Issue by kejvi-doko** [FusionAuth/fusionauth-issues#734]
### Description
I have deployed an instance of FusionAuth to AWS ECS service.

I configured FusionAuth Application. OAuth and Email template for registration verification and also configured the SMTP. When I try to register a user I get the following email that I have configured.

```Thank you for registering for gyo.gg. You have registered with the following information:

 User Name: Kejvi Doko

 Before you can log in, you will need to confirm your email address. You may do so by clicking the link below. If the link does not 
 show in your email client, please copy the link exactly as you see is below and paste it into your browser.

 http://www.auth.esportsinabox.com/email/verify/v78woWCxhPZDwCKVriXNpPaxswxTPHUZ4wTNyh2iJco?tenantId=31663633- 
 6534-6466-3833-656437393037

 You are receiving this email from gyo.gg because you signed up for an account at https://gyo.gg/. If you believe you were added 
 to this list in error, please email mailer@gyo.gg and you will be removed from the list.
```

When I click the link to confirm my account I get an error as described on the image link [https://prnt.sc/tdz661](https://prnt.sc/tdz661)

I didn't got any error on the Event Log or AWS cloud watch. Other email templates work fine e.g Forgot Password.

**Comment by mooreds** [comment]
Hiya,

What version of FusionAuth?

What happens if you copy the link? Same message?

If you request another email verification to be sent, do you see the same issue?

Is the account this email is sent to an Office 365 account? If so, https://github.com/FusionAuth/fusionauth-issues/issues/629 may be the root issue.

If that is not the case, can you share your email verification duration, under Tenant / Default / Advanced / External identifier durations?

**Comment by kejvi-doko** [comment]
- I have fusion auth 1.17.3 
- Configuration under External Identifier Duration https://prnt.sc/te5su9
- Client email is Google (Gmail) account
- Even if you copy-paste the confirmation link the problem still persists.
- Is my External Identifier generation too complex? https://prnt.sc/te5u1j

**Comment by voidmain** [comment]
Can you test this by changing your email template to not include the URL or even an anchor tag? Instead, can you just print out the ID into your email template? Then you'll copy that ID and manually type the URL into your browser's address bar by hand while appending the ID from the email to the end of the URL? You'll also need to ensure that you manually copy and paste over the `tenantId`.

This will help determine if the browser is traversing the URL or pre-loading it.

**Comment by kejvi-doko** [comment]
I tried to copy-paste the verification code but still, the problem persists. https://prnt.sc/teofco

The full url: http://www.auth.esportsinabox.com/email/verify/4aq6-nQYc8Drb7xkEBl_avRsyuWzp1PoLfFRXEY39CE?tenantId=31663633-6534-6466-3833-656437393037

**Comment by voidmain** [comment]
@kejvi-doko - it looks like you still have a URL and an anchor tag in your email. You will need to remove those complete and **ONLY** put the code in the email. Then you will have to manually build the URL.

An example email template might look like this:

```
This email is to test if the browser is pre-fetching. The code is ${verificationId}
```

As you can see, this template has no links, URLs or Anchor tags. Then I would copy the code from the email and manually build the URL in the browser's address bar.

Hopefully that clarifies the steps required to test this.

**Comment by kejvi-doko** [comment]
The problem occurred when you were logged in with another account and tried to verify the email on the current browser session.
If you logout from the browser and retry to verify the email everything works ok.  Thanks 👍
