### ISSUE TITLE
Email template needs support for dynamic subject 

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#735]
### Problem
Some email clients including Gmail and Gmail mobile will group inbound emails sharing FROM address and subject into conversations. Gmail by default shows the most recent emails at the bottom of the stack, rather than the top, and is reluctant to show the email subject and email body on the most recent email, while showing a couple lines of older emails.  Screen shot from mobile:
![Screen Shot 2020-07-08 at 4 32 40 pm](https://user-images.githubusercontent.com/3413901/86909721-dcdee000-c15b-11ea-819f-77e5d0747084.png)

Web UI:
![Screen Shot 2020-07-08 at 8 45 35 pm](https://user-images.githubusercontent.com/3413901/86909897-2a5b4d00-c15c-11ea-9ea2-bc8fcb3f057e.png)

Body opened on newest version of the email (clicked on ... button):
![Screen Shot 2020-07-08 at 8 46 04 pm](https://user-images.githubusercontent.com/3413901/86909949-3e9f4a00-c15c-11ea-98b7-3bfc589cead9.png)

We have kids requesting passwordless links repeatedly (to establish one session), or multiple times per day (morning and afternoon sessions).  GMail is hiding the most recent passwordless email in plain sight while the key phrase 'Login with Magic Link' subject is only visible on the older emails which steal the spotlight from where it needs to be.

We can certainly make suggestions on improving schools gmail configuration but probably won't be successful with that. Plus the Mobile version doesn't appear to have sufficient configuration options to solve the problem.

### Solution
If FusionAuth varies the email subject for Passwordless and Password Reset messages with each attempt it will keep the messages from stacking under one conversation.  In this example I sent two emails with '9:12:00' appended to the subject and then varied that append on the next email to confirm that it is seen as a new conversation.

![Screen Shot 2020-07-08 at 9 00 16 pm](https://user-images.githubusercontent.com/3413901/86911965-7d82cf00-c15f-11ea-94e4-dcc7beb3173b.png)

My suggestion is that the email template's subject field should support variables. For Passwordless I'd want to insert the link's computed expiration time. Maybe the same variable would be useful for password reset, or the request time stamp might be used there. The entire point of this exercise is to generate a unique and useful email subject to improve visibility of the messages in the email client and reduce the failure rate / frustration rate of people using the features.

**Comment by voidmain** [comment]
@davidmw - The subject does actually support variables. I looks like we just don't have the icon indicating that it does in the UI, but the docs are correctly stating that the subject field is FreeMarker capable. 

Have you tried using a variable in the subject field? It could be tricky to get an expression that spits out unique text each time, but FreeMarker has a lot of features that could help with this. You should check out the FreeMarker documentation and see if their built-in functions will help here.

**Comment by mooreds** [comment]
https://freemarker.apache.org/docs/ref_builtins_date.html looks useful:

```
<#assign aDateTime = .now>
${aDateTime?iso("UTC")}
${aDateTime?iso("GMT-02:30")}
${aDateTime?iso("Europe/Rome")}

The usual variations are supported:
${aDateTime?iso_m("GMT+02")}
${aDateTime?iso_m_nz("GMT+02")}
${aDateTime?iso_nz("GMT+02")}
```

**Comment by robotdan** [comment]
@voidmain the UI does show the subject field as FreeMarker compatible.

**Comment by voidmain** [comment]
You are correct. It's on the right side as an add-on. We should change that so that all the fields have the same indicator. The Text areas have it in the label. Probably best to move it there for the other fields as well.

**Comment by davidmw** [comment]
Ah, I didn't pay attention to the field add-on since I'm expecting controls there. But great news that Name and Subject can take Freemarker - thanks!

**Comment by davidmw** [comment]
This is basically working:

`  [#assign timeToLive = (tenant.externalIdentifierConfiguration.passwordlessLoginTimeToLiveInSeconds)!300]
    [#setting time_zone = (user.timezone)!"NZ/Auckland"]
    [#setting time_format = "h:mm a"]
    Expires at: ${((.now?date?long + timeToLive * 1000)?number_to_time)?string}`

passwordlessLoginTimeToLiveInSeconds doesn't seem to be available and it looks like we need to set user.timezone for each user.

**Comment by robotdan** [comment]
Re: TTL values in the template, I think that is covered under issue https://github.com/FusionAuth/fusionauth-issues/issues/612.

**Comment by mooreds** [comment]
I copied some of this discussion to the forum: https://fusionauth.io/community/forum/topic/220/can-i-customize-the-passwordless-link-email-subject-with-the-time-the-link-expires/2

**Comment by robotdan** [comment]
@davidmw from reading this thread, I think we all we are missing to complete this use case is to provide the TTL `passwordlessLoginTimeToLiveInSeconds` for example?

**Comment by davidmw** [comment]
@robotdan I've updated the template to use the TTL value which is working well. Only thing missing is the local TZ so created #886 if you'd like to close this one.

**Comment by robotdan** [comment]
Great. I'll close this one out.
