### ISSUE TITLE
forgot password on a custom theme doesn't send

### ISSUE THREAD

**Issue by kejvi-doko** [FusionAuth/fusionauth-issues#739]
### Description

I have configured a FusionAuth instance and configured 1 tenant and 1 application. I have linked this tenant with a custom theme.
I have also configured the email SMTP for this tenant. If I perform forgot password from the default tenant and default theme the forgot password link is sent, if I perform forgot password from custom theme with the other tenant the email doesn't send. For both cases, there are no errors in the UI or in the browser console.

Request logs for the default theme and custom theme https://drive.google.com/drive/folders/1y9vSracwXrVT_TkntJJMMscbT8OnT9pD?usp=sharing

Fusion Auth Version: 1.17.3

**Comment by mooreds** [comment]
Hiya,

Thanks for the logs!

A few additional troubleshooting steps:

* Did you modify the custom theme at all? If so, can you share the "Forgot password" .ftl file as well as the helpers.ftl file?
* Can you verify that your SMTP settings for the new tenant work? (Try to send a test email from the "General" tab of the "Tenant" details page.)

Thanks!

**Comment by robotdan** [comment]
Closing this one out. @kejvi-doko if you can still recreate, please re-open the ticket based upon @mooreds's suggestion. 
Thanks!
