### ISSUE TITLE
Add Caisson ID check for account recovery

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#740]
### Problem
Currently, if a use has lost their phone with their MFA key and is locked out of their account, it requires that they call support in order to have their account unlocked. In many cases, this requires that they do a screen share with support and show them a government issued ID (driver's license, passport, etc). The support agent then needs to verify the user and their government issued ID in order to remove their MFA key.

This process is similar if the user is locked out of their account because they forgot their password and no longer have access to their email address (even without MFA enabled).

### Solution
Caisson is a solution that provides an automated process to verify government issued IDs. They have a hosted web application where users can upload pictures of their government issued ID and Caisson will verify that they are real using machine learning models.

The goal of an integration with Caisson would be to reduce the number of support agents required to managed account recovery issues. This is particularly interesting for applications with millions of users (1Ms, 10Ms or 100Ms) since their support costs are often very high.

### Alternatives/workarounds
Rely on support agents to validate identities and update or reset accounts.

### Additional context
<img width="1272" alt="Screen Shot 2020-07-10 at 9 02 55 AM" src="https://user-images.githubusercontent.com/377102/87168722-27f81080-c28c-11ea-8621-6e7cbc9e1145.png">

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
How do they differentiate a selfie from a high res photo either in print or on my monitor? Maybe they make you blink before it will take the photo?  🤔

**Comment by derekg** [comment]
> How do they differentiate a selfie from a high res photo either in print or on my monitor? Maybe they make you blink before it will take the photo? 🤔

Great question! We’ve seen a few of these, and have a number of ways to protect against spoofing. We have built a special purpose tensorflow model to protect against basic fake selfie attempts on every ID Check, and we have an upgrade module that can do “liveliness” tests for our customers that benefit from stronger assurances.  We offer a bunch of flexibility depending on each customer's needs.  As people are always coming up with new ways to test these boundaries, it's area of the product that we are focused on continually evolving.

**Comment by robotdan** [comment]
Thanks for the explanation @derekg

**Comment by mooreds** [comment]
Caisson appears to be defunct (at least, https://www.caisson.com/ doesn't work and their Auth0 marketplace entry 404s: https://auth0.com/blog/introducing-auth0-marketplace/ )

**Comment by andrewpai** [comment]
Closing based on @mooreds's last comment (plus confirmation today)
