### ISSUE TITLE
How to open idp directly?

### ISSUE THREAD

**Issue by dakkafex** [FusionAuth/fusionauth-issues#742]
### Description
How do i let my user go directly to an identity providers login when they press the button "login with..."
 on my app. I dont want to send them to my servers login form first (kind of annoying for the user to be redirected twice from my app and just increases the chance they will walk away)

I have tried to hardcode a url but that doesnt work, there has to be someway to do this?! how is the "log in with..." button getting its link to go to the provider in the first place?

**Comment by mooreds** [comment]
I think this forum post may be of interest to you.

https://fusionauth.io/community/forum/topic/229/how-to-open-identity-provider-directly

> I would use the lookup API to get an authorization_endpoint for the relevant identity provider. Then I'd have the button point directly to the authorization_endpoint rather than the FusionAuth login page.

Let's continue this discussion on the forum, please.
