### ISSUE TITLE
JSON Web Key Set (JWKS) always come back empty?

### ISSUE THREAD

**Issue by saul-gush** [FusionAuth/fusionauth-issues#744]
## JWKS keys always come back empty

https://fusionauth.io/docs/v1/tech/oauth/endpoints#json-web-key-set-jwks

### Description
https://<fusionauth url>/.well-known/jwks.json

Response I am getting - not sure what I am doing that is wrong. 
{   "keys" : [ ] }

I also tried using tenantid and with Authorization header.

**Comment by robotdan** [comment]
Do you have any eligible keys configured in Key Master that would be returned?

**Comment by saul-gush** [comment]
I am not sure if these are eligible or not:

![image](https://user-images.githubusercontent.com/63714857/87579806-6e0b0500-c6ce-11ea-93b3-ee5fae4bb959.png)

**Comment by robotdan** [comment]
Symmetric keys are not returned on the JWKS endpoint. If you create an RSA or EC key which is an asymmetric key pair - the public key will be returned on the JWKS endpoint.

**Comment by saul-gush** [comment]
OK Thanks :)
