### ISSUE TITLE
Custom Password Plugin fails to generate correct hash

### ISSUE THREAD

**Issue by harenadata** [FusionAuth/fusionauth-issues#746]
### Description
I have deployed a fusion auth instance on AWS ECS. Fusion auth version 1.17.5. I create a python script that imported all my users from the current database to fusion auth using python client. I imported also the password hash and the salt. 
I created a plugin in java and installed it on fusion auth. 

``` java
public class GyoPasswordEncryptor implements PasswordEncryptor {
  @Override
  public int defaultFactor() {
    return 1;
  }

  @Override
  public String encrypt(String password, String salt, int factor) {

    System.out.println("1. Enter Encrypt Method");

    System.out.printf("Password: %s  Salt: %s", password,salt);

    MessageDigest digest1;
    MessageDigest digest2;
    try {
      digest1 = MessageDigest.getInstance("SHA-256");
      digest2 = MessageDigest.getInstance("SHA-256");
    } catch (NoSuchAlgorithmException ex) {
      return null;
    }

    byte[] passwordBytes = password.getBytes(StandardCharsets.UTF_8);

    digest1.update(passwordBytes);

    byte[] passwordHash = digest1.digest();

    StringBuilder sb = new StringBuilder();
    for(int i=0; i< passwordHash.length ;i++)
    {
      sb.append(Integer.toString((passwordHash[i] & 0xff) + 0x100, 16).substring(1));
    }

    String saltAndPasswordHash = salt+sb.toString();
    digest2.update(saltAndPasswordHash.getBytes(StandardCharsets.UTF_8));

    byte[] hashedPassword = digest2.digest();

    sb = new StringBuilder();
    for(int i=0; i< hashedPassword.length ;i++)
    {
      sb.append(Integer.toString((hashedPassword[i] & 0xff) + 0x100, 16).substring(1));
    }

    String finalHash = sb.toString();

    System.out.printf("Password Hash: %s",finalHash);

    return finalHash;

  }
}

```
The password for one of the test users is: `HtZX28CECnaL` and the salt is: `18f`. The generated hash from the script is `df6cb6dad23e6f5d98e3edfe7f3492a137f53041093ca6adb39bca588abfb6dd` and the password hash imported from the previous database is the same 'df6cb6dad23e6f5d98e3edfe7f3492a137f53041093ca6adb39bca588abfb6dd'.

When I try to login with this user the logs that are printed from the password plugin are: 

```
1. Enter Encrypt Method
Password: enumerate  Salt: dGhpcw==
Password Hash: adbc8778a3de37e8912616006d9eb2ab2507fc3d1d1b189bf2b635e11a4690a2
```

If I change the password from  `HtZX28CECnaL`  to `Admin@123+` using the admin panel and try to login I get the following logs

```
1. Enter Encrypt Method
Password: Admin@123+  Salt: kud+SSpxm1PQHNxzNihLcJ8EiQPiwe0mSGiJpUKjTT0=
Password Hash: 1185fe9808d625dac019eb4c5662d83d0fb39d129349a3a30906c99dd5914983
```
But even in the second time that the password is passed successfully on the encrypt method and the hash generated is the same as the database the fusion auth fails to perform the login, it is still stuck in the login page, it doesn't redirect me to the redirect url.

**Comment by robotdan** [comment]
For your existing hashes, are they produced by a well known library or system where the hash is documented, do you know the factor used to calculate the hash?

If I understand correctly, you're saying your control data is a user with a plain text password of `HtZX28CECnaL` and a salt of `18f` (that salt looks really short)  and you expect the hash (according to your existing system) to be `df6cb6dad23e6f5d98e3edfe7f3492a137f53041093ca6adb39bca588abfb6dd`? What is the factor used to generate this hash?

**Comment by harenadata** [comment]
The hashes are generated by another system (PHP), but I have replicated the logic in the script above in JAVA. If you refer with factor to the number of iterations I think is 1. Yes, the salt is short but is inherited from the previous system and I can't change that. 

I have tested the java plugin locally and with the combination of plain text password of `HtZX28CECnaL` and salt of `18f` it generates the correct hash.

I am not concerned about the logic of generating hashes since the logic is replicated based on the previous system and I have tested (locally) the logic with many users and the hashes are generated correctly, what concerns me is the fact that fission auth sends as clean password the word `enumerate` instead of `HtZX28CECnaL`. Does fusion auth validate the salt format or any other validation?

**Comment by robotdan** [comment]
I apologize, I'm not really clear on the problem yet. 

If I can clarify, here is what I understand. 

1. You are confident the hashing logic is ok, so this is not a concern. 
2. You have imported users using the Import API `/api/user/import`.
3. On the import request:
  - a) You specified the `encryptionScheme` equal to the value you have bound your encryptor. 
  - b) You specified `1` for the `factor` field.
  - c) You specified the password hash from your PHP application for the `password` field.
  - d) You specified the salt from your PHP application for the `salt` field. 

So in your example user, the equivalent JSON used for the import request would something like:

```
{
  "users": [
    {
        "email": "someuser@example.com",
        "encryptionScheme": "your_encryption_scheme_name",
        "factor": 1,
        "password": "df6cb6dad23e6f5d98e3edfe7f3492a137f53041093ca6adb39bca588abfb6dd", 
        "salt": "18f"
    }    
  ]
}
```

Then you subsequently attempt to login with the `someuser@example.com` and a password of `HtZX28CECnaL` and you see the following printed to the console? 

```
1. Enter Encrypt Method
Password: enumerate  Salt: dGhpcw==
Password Hash: adbc8778a3de37e8912616006d9eb2ab2507fc3d1d1b189bf2b635e11a4690a2
```

I don't see how this would be possible, the value printed here for `password` - in this case `enumerate` is the plain text password provided by the user on the Login API. 

If any of my assumptions above are incorrect, please be specific in which step I am mistaken.

**Comment by harenadata** [comment]
@robotdan yes all your assumptions are correct

**Comment by kejvi-doko** [comment]
@robotdan I finally managed to find the fix, it was related to the password expiry field being an expired date and the factor number had to be 1 for the imported user. Thanks a lot for your support.

**Comment by robotdan** [comment]
That is great news @kejvi-doko can we close this issue out?
