### ISSUE TITLE
Verification Email not sent when user created with null email then subsequently changed

### ISSUE THREAD

**Issue by EddieWhi** [FusionAuth/fusionauth-issues#749]
### Description

Verification emails are not sent to users when their email address is changed from null to a value even though the tenant is configured to send verification emails on email address change.

### Affects versions
Hosted v 1.15.8

### Steps to reproduce
1. Configure tenant to verify user email and verify email on change. 

2. Create a user with no email:
```
 POST api/user
{
	"sendSetPasswordEmail": false,
	"user": {
		"password": "pass",
		"username": "uniqueName"
	}
}
```
3. Update the users email:
```
PATCH api/user/{id}
{
	"user": {
		"email": "me@example.com"
	}
}
```

The response comes back showing the user as verified (and no email is received):

```
{
    "user": {
        "active": true,
        ...
        "verified": true
    }
}
```

If the users email is changed again then the subsequent PATCH triggers the email and sets `verified` to false.

### Expected behavior
When a tenant is configured to verify email on change then the email should be sent whenever it changes, regardless of whether the email was initially set of not.

### Screenshots
None

### Platform
Hosted

### Additional context
Originally reported on forum: https://fusionauth.io/community/forum/topic/195/no-email-verification-if-user-created-without-an-email

**Comment by robotdan** [comment]
Thanks for the excellent recreate steps! I've recreated the issue, if the previous email was not defined we were not going through the verification process again.
