### ISSUE TITLE
Login Theme bypassTheme not working

### ISSUE THREAD

**Issue by sjswami** [FusionAuth/fusionauth-issues#75]
### Description 
Did some customization in the login theme. Accidently did mistake. So now I am unable to do the login.
To revert back to original theme I am trying to append &bypassTheme=true, but not working
http://localhost:9011/oauth2/authorize?bypassTheme=true

### Steps to reproduce
1. Do customization
2. open /oauth2/authorize
3. Check customization is shown
4. Now try /oauth2/authorize?bypassTheme=true
5. Page loaded with customization

### Expected behavior
Default login page should be displayed

### Screenshots
![image](https://user-images.githubusercontent.com/47114533/52032137-be77bc80-2545-11e9-88b8-13012c814346.png)

### Platform

 - Device: Deskop
 - OS: Windows 10
 - Chrome 71.0.3578.98

**Comment by sjswami** [comment]
I think there was an error in the Helper macro (i.e. custom).

The problem might in the exception handling

**Comment by sjswami** [comment]
Yes, I also tried with all the other parameter also.

I was unable to login in any manner. So need to do the setup again.

**Comment by robotdan** [comment]
Hmm.. strange, are you seeing an exceptions in the `fusionauth-app.log`? 

If you know your API key, you could also disable the theme by using the System Configuration API using the `systemConfiguration.uiConfiguration.loginTheme.enabled` property.
https://fusionauth.io/docs/v1/tech/apis/system#update-the-system-configuration

**Comment by sjswami** [comment]
You may try reproducing attached settings 
css and helper are attached



[Settings.zip](https://github.com/FusionAuth/fusionauth-issues/files/2816966/Settings.zip)

**Comment by robotdan** [comment]
Thanks for the .zip @sjswami  -- I'll try too reproduce.

**Comment by robotdan** [comment]
Let me know if you're still having issues with this one.

**Comment by satsangswami** [comment]
The issue is after Update many forms do not work! seems like there are keys it is looking for... the question is, "is it safe to remove the user custom theme and recreate one? also what is there a way to disable theme?

**Comment by robotdan** [comment]
Each tenant can set a theme, to disable a theme, you can change the tenant configuration to use the default theme called FusionAuth. 

To bypass a theme during login you can pass the `bypassTheme=true` on the URL. 
https://fusionauth.io/docs/v1/tech/themes/#handling-failures

> is it safe to remove the user custom theme and recreate one

Yes, you can always create a new theme and then assign it to a tenant.

**Comment by konvergence** [comment]
Hi
This is an hacking feature.
Is it possible to ignore this parameter PRODUCTION mode ?

**Comment by mooreds** [comment]
This seems like a support request @konvergence . Please post in the forum: https://fusionauth.io/community/forum/ or open a ticket if you have paid support: https://account.fusionauth.io/account/support
