### ISSUE TITLE
Querying Users by Application ID Reflects Stale Data

### ISSUE THREAD

**Issue by brennan-karrer** [FusionAuth/fusionauth-issues#750]
### Description 
After removing a user's registration to a specific application, searching by that application ID on the user list page is still returning that user as if he is still registered to the application. It would appear that there is some issue with keeping the database and Elasticsearch in sync when removing a user's registration to an application.

### Affects versions
FusionAuth 1.17.5 on Red Hat Enterprise Linux Server 7.7 (Maipo)

Previously I was running FusionAuth 1.16.1 which resulted in the same error.

### Steps to reproduce
1. Create two users within FusionAuth tied to whatever tenant you would like.
2. Create a new application under the same tenant for which the users were created.
3. Register the first user to the new application.
4. Register the second user to the new application.
5. Navigate to the user list page and search for users by the newly created application ID and see both users visible in the list of users.
6. Navigate to either user's detail page and remove the registration. You will be able to see how that user no longer has anymore registrations on their details page.
7. Navigate back to the user list page and search for users by the application ID.
8. The user who was just removed from the application is still visible in the list of users.

### Expected behavior
The user who was removed from the application would not be returned when searching for users by that application ID.

### Screenshots
1. The initial search for users by application ID results in no users being returned.
![Initial-Search-Users-by-Application-ID](https://user-images.githubusercontent.com/10541750/87823926-2ea4fb80-c829-11ea-89f7-11e2fda78fed.png)

2. Test user one has no registrations associated to him.
![Test-User-One-No-Registration](https://user-images.githubusercontent.com/10541750/87823958-3cf31780-c829-11ea-9a46-e6d178c04357.png)

3. Addition of the registration for test user one.
![Test-User-One-Added-Registration](https://user-images.githubusercontent.com/10541750/87823978-48464300-c829-11ea-8778-acb3b2a4021a.png)

4. Test user two has no registrations associated to him.
![Test-User-Two-No-Registrations](https://user-images.githubusercontent.com/10541750/87823998-51371480-c829-11ea-9247-283fa1e142a7.png)

5. Addition of the registration for test user two.
![Test-User-Two-Added-Registration](https://user-images.githubusercontent.com/10541750/87824017-58f6b900-c829-11ea-8d48-258814a64ec8.png)

6. Searching for users by application ID now shows test user one and test user two.
![Search-Users-by-Applicaton-ID](https://user-images.githubusercontent.com/10541750/87824059-6ca21f80-c829-11ea-9c76-6e41d848399d.png)

7. Confirmation to delete the registration for test user one.
![Test-User-One-Delete-Registration](https://user-images.githubusercontent.com/10541750/87824094-7cb9ff00-c829-11ea-89cd-e6f4f7001bad.png)

8. After the registration for test user one has been deleted.
![Test-User-One-Registration-Deleted](https://user-images.githubusercontent.com/10541750/87824125-8a6f8480-c829-11ea-8e64-3ecffb2dd916.png)

9. Searching for users by application ID after the remove of test user one from the application still display both test user one and test user two in the list.
![After-Removal-Search-Users-by-Application-ID](https://user-images.githubusercontent.com/10541750/87824166-9b1ffa80-c829-11ea-82d1-5ba52ae09fae.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: MacOS Catalina
 - Browser + Version: Chrome Version 84.0.4147.89
 - Database: PostgreSQL 11.6

### Additional context
There are no logs being output with any error messages. After querying the database, I've noticed that the registration is indeed deleted from that user; however, when querying Elasticsearch by the application ID, that user's record is still returned within the payload.

**Comment by robotdan** [comment]
Thanks for reporting @brennan-karrer . This is a bug. The issue will resolve once the user is indexed again, such as during a login event, or other update operation.
