### ISSUE TITLE
Allow an application to require two factor authentication

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#763]
### Problem

Currently there's no way to enforce two factor authentication without coding your own login page. This is a great 'default secure' option for many applications.

### Solution
It'd be great to be able to configure an application to require two factor authentication for all users logging into  and then have the standard FusionAuth login pages display the 2fa prompt.

The decision to show a MFA prompt should be performed at:
- Login
- Change password 

This will affect the Login API and subsequently the OAuth2 grants when using SSO.

### Use case 1

I have two applications, one application named "Web" provides general access to my application and to reduce friction I do not want to require 2FA during login. 

The second application named "Account" provides secure access to the user's account and enables a user to manage payment methods, and other regulated financial capabilities. For this application, I want to require 2FA during the login experience both for security and to meet regulatory requirements. 

Additionally, at certain points in either application I want the option to perform a step-up authentication request and prompt the user for a 2FA challenge. In order to do this, the user has to have previously configured at least one 2FA method on their account. 

Even with 2FA enabled, I want to bypass 2FA during login based upon the `applicationId` in the login request. 

### Use case 2

I have four applications, one named "Strong app", the next "Stronger app", the third is named "Strongest app", and the last is named "Weak app". 

All three Strong app require requires 2FA, Weak app does not require 2FA to complete login. Each of the strong applications have configured a different level of trust. Any app, This app, and Zero respectively.

- Strong app can utilize a two factor trust established by logging into Strong app or Stronger app. (Any app)
- Stronger app can only utilize a two factor trust established by logging into Stronger app. (This app)
- Strongest app never utilizes a trust and will be required to complete a 2FA challenge on each login (Zero)

#### Example workflows
For example, SSO between "Web" and "Account" with application specific MFA configuration.

1. User logs into "Web" application using FusionAuth SSO (hosted login pages), enters credentials, and is not prompted to complete 2FA. 
2. User then navigates to "Account" and is redirected to the FusionAuth SSO and while the SSO session exists, because this application requires 2FA, the user is prompted to complete 2FA to complete the login workflow. 
3. The user has now completed SSO login for "Account" and was required to complete 2FA. 

#### Example workflows
For example, login to "Web" and at a later point in time 2FA w/out ever logging into "Account".

1. User logs into "Web" application using FusionAuth SSO (hosted login pages), enters credentials, and is not prompted to complete 2FA. 
2. User then attempts to access a secured feature that requires a step-up authentication.
3. User is prompted to complete a 2FA challenge that has been custom built in the "Web" application using the FusionAuth Two-Factor Step Up API.

#### New Configuration
- [ ] Default Tenant policy. MFA on login: `[Enabled | Disabled]`
- [ ] Application policy. MFA on login: `[Use tenant policy | Enabled | Disabled]`
- [ ] Application policy. MFA Trust: `[Any application | This application | Zero]`
- [ ] MFA trust TTL per app that can optionally override the Tenant configuration to allow you to optionally have a shorter TTL on MFA trust for a more sensitive application.

### Alternatives/workarounds

Code your own 2fa compatible login pages.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/51
- https://github.com/FusionAuth/fusionauth-issues/issues/197
- https://github.com/FusionAuth/fusionauth-issues/issues/647
- https://github.com/FusionAuth/fusionauth-issues/issues/960

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Similar or duplicates of
https://github.com/FusionAuth/fusionauth-issues/issues/51
https://github.com/FusionAuth/fusionauth-issues/issues/197
https://github.com/FusionAuth/fusionauth-issues/issues/647

**Comment by yinzara** [comment]
I'm interested in helping to implement this feature.  Do we have any ideas how we might like this to work?  Maybe just a simple boolean configuration that can be enabled/disabled on an application that says that app requires 2fa?  Do we need a tenant level config of the same value that could be overwritten by the application (so the application really need a tri-state, yes/no/undefined)?

Would you think there would be a new Theme page (maybe "oauth2RegisterTwoFactor") that you would be brought to if you do not have 2fa enabled? or should this be done through the existing "oauth2TwoFactor" template?

**Comment by robotdan** [comment]
This will likely be delivered through issue https://github.com/FusionAuth/fusionauth-issues/issues/960.

**Comment by awoodsprim** [comment]
I don't see this particular issue mentioned in issue #960.  Is it still slated for release in that issue?

**Comment by mooreds** [comment]
@robotdan I wanted to confirm that this configuration option will apply even to the `FusionAuth` admin UI application. Is that correct?

**Comment by awoodobvio** [comment]
@robotdan I'd also like to ask if this option can take into account federated MFA.

If I set a user up with "requires MFA" and they log in with a federated system with MFA, I'd prefer that they NOT be prompted for a second MFA.  

I know some systems do this (see Atlassian's!) and it is annoying.

Perhaps as an option?  (Require MFA -> "No", "Yes", "Yes, but trust federation"

**Comment by awoodobvio** [comment]
Alternatively, can we have a hook where we can "force" MFA to occur?  Not sure if the JWT reconcile hook is right, but a "login occurred" hook could return a "please ask for MFA" response?

**Comment by robotdan** [comment]
@awoodobvio The problem with federated MFA is that we don’t have a way to understand if this occurred. So from the FusionAuth perspective what we happens while federating login is opaque. 


@mooreds I believe the answer is yes. All applications with have the ability.

**Comment by robotdan** [comment]
Documentation
- [ ] Tenant API updates
- [ ] Application API updates
- [ ] New Two Factor Status API
- [ ] UI updates for Tenant and Application screen shots?
