### ISSUE TITLE
Cannot connect to any SMTP server

### ISSUE THREAD

**Issue by LukeHallett** [FusionAuth/fusionauth-issues#764]
### Description 
I am trying to send a test email, however any SMTP server I have tried, FusionAuth refuses to connect to.

### Affects versions
1.17.5

### Steps to reproduce
1. Go to 'Tenants'
2. Click on a tenant
3. Click on 'Email'
4. Enter SMTP details
5. Click on 'Send test email'
6. Click on 'Send'
7. Wait until error

### Expected behavior
A test email should be sent to the specified email.

### Screenshots
![Screenshot 1](https://i.imgur.com/atnOLoX.png)
![Screenshot 2](https://i.imgur.com/MCVCEYk.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 10
 - Browser + version: Microsoft Edge (Chromium) 84.0.522.40
 - Database: MySQL 8.0.20

**Comment by voidmain** [comment]
Are you certain that you can connect to that DNS name on that port from the server you are running FusionAuth on? I tested it with Telnet like this and it worked fine making the connection:

```
$ telnet smtp.eu.mailgun.org 465
```

I'm just wondering if your server has egress blocked, DNS issues, or something like that.

**Comment by LukeHallett** [comment]
I have tried that, with no successful response. Must be something that something is blocked.

**Comment by robotdan** [comment]
If you are certain that is the correct port for SSL, I would suggest you try SWAKS to debug the issue. 

https://www.jetmore.org/john/code/swaks/

If you can connect with Swaks using your creds, etc - then we can look into FusionAuth further. It is usually an SMTP config or network issue.

**Comment by LukeHallett** [comment]
I have just figured out the issue, my provider blocks all SMTP ports by default.

**Comment by robotdan** [comment]
Thanks for the update, glad you got it figured out @LukeHallett !
