### ISSUE TITLE
/api/identity-provider/login doesn't return refreshToken

### ISSUE THREAD

**Issue by ulybu** [FusionAuth/fusionauth-issues#771]
### Description 

I'm using my own login form (iOS) for login with Google and Sign in with Apple, and want to reconcile/register the user with FA right after that with the `/api/identity-provider/login` endpoint

The call succeeds but we get no refreshToken in the return payload. 
The [documentation](https://fusionauth.io/docs/v1/tech/apis/identity-providers/google#complete-the-google-login)  says I should be able to get one as long as I provide an `applicationId`, which I did

I initially posted that in the forum, so in the OP you can find payloads and application configs screenshots. 
Dan suggested to file a bug
https://fusionauth.io/community/forum/topic/235/complete-idp-login-doesn-t-return-refreshtoken?_=1595523107575

### Affects versions
version: `1.17.4`, instance: `swift-tech.fusionauth.io`

### Steps to reproduce
1. Do a oauth2 auth flow with google on your own, get an `id_token`
2. Do a call to `/api/identity-provider/login` with that `id_token` from step 1 and provide the applicationId of an application which has a google idp enabled. Leave `noJWT` falsy
3. See that the return payload only contains an AccessToken but no refreshToken

### Expected behavior
The return payload should contain a refreshToken

### Screenshots
See more info in the OP: https://fusionauth.io/community/forum/topic/235/complete-idp-login-doesn-t-return-refreshtoken?_=1595523107575

### Additional context

This is preventing us to use FA at all with this login form, as we can't have the iOS app having only the short life AccessToken and logout every hour or so

**Comment by mooreds** [comment]
As mentioned in the forum post, this is at the least a documentation bug, because the docs referenced clearly mention that a refresh token is returned.

Note also that if you use the normal google login flow (with a button provided by the fusionauth UI) you get a refresh token if you provide the correct scope (`offline_access`).

**Comment by ulybu** [comment]
> Note also that if you use the normal google login flow (with a button provided by the fusionauth UI) you get a refresh token if you provide the correct scope (offline_access).

Yes I can confirm that, we had no issues until we moved to building our own login form

**Comment by ulybu** [comment]
Hi guys, could you confirm if it's a documentation bug or the expected behavior ?

**Comment by ulybu** [comment]
Additional information:

1. Also don't get `token` nor `refreshToken` when GET `/api/user/registration/{userId}/{applicationId}` unlike the [documentation](https://fusionauth.io/docs/v1/tech/apis/registrations#retrieve-a-user-registration) says it should 

1. getting 0 refreshTokens when trying GET `/api/jwt/refresh/:userId` for that newly created user

1. Here is what I see in the `Event Log` page

```
Google IdP Response Debug Log

7/28/2020 01:28:35 PM MDT Call the [https://www.googleapis.com/oauth2/v3/tokeninfo] endpoint.
7/28/2020 01:28:36 PM MDT Endpoint returned status code [200]
7/28/2020 01:28:36 PM MDT Endpoint response:
{
  "iss" : "accounts.google.com",
  "azp" : "XXX.apps.googleusercontent.com",
  "aud" : "XXX.apps.googleusercontent.com",
  "sub" : "xxxx",
  "email" : "xx@gmail.com",
  "email_verified" : "true",
  "at_hash" : "xx",
  "name" : "ulysse",
  "picture" : "https://lh6.googleusercontent.com/--ulyCgrOYeo/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucm1T6nK2SV8vyAmPT6ANUKu_Sf-cg/s96-c/photo.jpg",
  "given_name" : "ulysse",
  "family_name" : "xx",
  "locale" : "fr",
  "iat" : "1595964244",
  "exp" : "1595967844",
  "jti" : "bc06c12e56869067de6e518d26d91dedca05926e",
  "alg" : "RS256",
  "kid" : "b63ee0be093d9bc312d958c9966d21f0c8f6bbbb",
  "typ" : "JWT"
}
7/28/2020 01:28:36 PM MDT The user with the email address [xxx@gmail.com] does not exist.
7/28/2020 01:28:36 PM MDT Invoke configured lambda with Id [d7cfcc45-0058-233e-ae42-098852c90a55]
7/28/2020 01:28:36 PM MDT Creating user:
{
  "breachedPasswordLastCheckedInstant" : null,
  "breachedPasswordStatus" : null,
  "encryptionScheme" : null,
  "factor" : null,
  "id" : null,
  "password" : null,
  "passwordChangeReason" : null,
  "passwordChangeRequired" : false,
  "passwordLastUpdateInstant" : null,
  "salt" : null,
  "verified" : false,
  "preferredLanguages" : [ ],
  "memberships" : [ ],
  "registrations" : [ ],
  "active" : false,
  "birthDate" : null,
  "cleanSpeakId" : null,
  "data" : { },
  "email" : "xxx@gmail.com",
  "expiry" : null,
  "firstName" : "ulysse",
  "fullName" : "ulysse xx",
  "imageUrl" : "https://lh6.googleusercontent.com/--ulyCgrOYeo/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucm1T6nK2SV8vyAmPT6ANUKu_Sf-cg/s96-c/photo.jpg",
  "insertInstant" : null,
  "lastLoginInstant" : null,
  "lastName" : "xx",
  "middleName" : null,
  "mobilePhone" : null,
  "parentEmail" : null,
  "tenantId" : null,
  "timezone" : null,
  "twoFactorDelivery" : null,
  "twoFactorEnabled" : false,
  "twoFactorSecret" : null,
  "username" : null,
  "usernameStatus" : null
}
7/28/2020 01:28:36 PM MDT User is not registered for application with Id [1e85ab7d-7e27-4729-b61f-fdb9f9ce6d6e]
7/28/2020 01:28:36 PM MDT User has successfully been reconciled and logged into FusionAuth.
7/28/2020 01:28:36 PM MDT Authentication type: GOOGLE
7/28/2020 01:28:36 PM MDT Authentication state: Authenticated
```

**Comment by ulybu** [comment]
Found the issue. 
the `/identity-provider/login` uses the "Login API" and therefore I need to allow JWT refresh for the "Login API", even if that app use to properly deliver when used with oauth previously.

![image](https://user-images.githubusercontent.com/2479249/88794395-b7635600-d19e-11ea-81d7-ddd4c2e88877.png)


I'm not closing because I'll let you guys decide whether or not this should have been in the doc or not

**Comment by robotdan** [comment]
Thanks for the update @ulybu. We can take a look at the documentation, perhaps we need to add some additional clarifications on the API response for the User and Registration APIs to indicate that the `refreshToken` is returned if enabled by the Application security configuration.
