### ISSUE TITLE
identity-provider/login broken json validation of `appleUser`

### ISSUE THREAD

**Issue by ulybu** [FusionAuth/fusionauth-issues#779]
### Description 
When using `identity-provider/login` with Apple, FusionAuth reject the call with the following 400 error

```js
{
    "fieldErrors": {
        "data.appleUser": [
            {
                "code": "[invalidJSON]",
                "message": "Invalid JSON in the request body. The property was [data.appleUser]. The error was [Possible conversion error]. The detailed exception was [Cannot deserialize instance of `java.lang.String` out of START_OBJECT token\n at [Source: (org.apache.catalina.connector.CoyoteInputStream); line: 7, column: 22] (through reference chain: io.fusionauth.domain.api.identityProvider.IdentityProviderLoginRequest[\"data\"]->java.util.HashMap[\"appleUser\"])]."
            }
        ]
    }
}
```

It's seems that FA is expecting `data.appleUser` to be a String, but the [documentation](https://fusionauth.io/docs/v1/tech/apis/identity-providers/apple#request-body-3) says it should be an object:
![image](https://user-images.githubusercontent.com/2479249/88816677-ef799180-d1bc-11ea-8f92-ad9ecd3ced6d.png)

This is the request payload I'm using (very similar to the one in the doc 🔝 ) that got me the _invalidJSON_ error: 

```js
{
  "applicationId": "1e85ab7d-7e27-4729-b61f-fdb9f9ce6d6e",
  "identityProviderId": "13d2a5db-7ef9-4d62-b909-0df58612e775",
  "data": {
    "id_token": "valid-jwt",
    "redirect_uri": "",
    "appleUser":  { // <= FA expect this to be a string
      "name": {
          "firstName": "Stefan",
          "lastName": "xxx"
      }
    },
  },
  "code": "xxcodexx"
}
```

### Additional Scneario:
I tried supplying a String at `data.appleUser` as the JSOn error seems to want, and this time it passes JSON validation but fails later (the call last 1s longer before failing)

request payload:
```js
{
  "applicationId": "1e85ab7d-7e27-4729-b61f-fdb9f9ce6d6e",
  "identityProviderId": "13d2a5db-7ef9-4d62-b909-0df58612e775",
  "data": {
    "id_token": "valid-jwt",
    "redirect_uri": "",
    "appleUser": "dummy string" // <= passes validation
  },
  "code": "xxcodexx"
}
```
which gets me this response error payload:
```js
{
    "generalErrors": [
        {
            "code": "[ExternalAuthenticationException]AppleUserObject",
            "message": "Failed to read the user details provided by Apple. Unable to complete this login request."
        }
    ]
}
``` 

My conclusion is that this is not a documentation bug. The business code expects an object like the doc says, but some payload validator expects a string

### Affects versions
1.17.4

### Steps to reproduce
1. signin with apple on a native form, with an email **that doesn't exists yet on Fusionauth**, grab the `code` , `id_token` and apple user object
2. Do a identity-provider/login POST with an application id that has Sign in with Apple configured
3. Get the 400 error mentioned above

### Platform
1.17.4

**Comment by robotdan** [comment]
Currently the `data.appleUser` needs to be a string. If you escape the JSON returned from Apple and set it as a string into the `data` object, it should work for you. 

I can review this path to see if we can optionally handle this value as an object or a string.

**Comment by ulybu** [comment]
Oh! Giving it a try right now, thanks for your answer!

I'm absolutly fine with serializing the object, not a big painpoint. 
The doc is clearly wrong though as it shows an object (cf my screenshot in the OP)

**Comment by robotdan** [comment]
Yes, good point, at a minimum we need to fix the doc. Thanks for opening the issue.
