### ISSUE TITLE
Unable to view system logs when using symlink to /var/log

### ISSUE THREAD

**Issue by sw-waterford** [FusionAuth/fusionauth-issues#784]
### Description 
We are currently running a 2 server cluster I can see both nodes exist but I am unable to view the logging from either node the system indicates that there are no log files available. When I SSH into the host I am able to view the log information. 

### Affects versions
FusionAuth™ version 1.17.0

### Steps to reproduce
1. Install FusionAuth app
3. Create /var/log/fusionauth
2. ln -s from /usr/local/fusionauth/logs to /var/log/fusionauth
3. Set permissions on /var/log/fusionauth to root:fusionauth
4. Start service open fusionauth web console

### Expected behavior
Expect to see system log data

### Actual behavior 
No system logs were found on this server in the configured log directory. If you are running FusionAuth in a Docker container the logs are generally not written to the file system and instead managed by the Docker environment.

### Platform
 - OS: amazon linux 2

### Additional context
Docker is not being used.

**Comment by robotdan** [comment]
This works for me:

```
ls -lah /usr/local/fusionauth/logs/
-rw-rw-r-- 1 fusionauth root 75M Aug  2 11:14 /usr/local/fusionauth/logs/fusionauth-app.log

sudo ln -s /usr/local/fusionauth/logs /var/log/fusionauth

ls -lah /var/log/fusionauth/
-rw-rw-r-- 1 fusionauth root 75M Aug  2 11:14 /var/log/fusionauth/fusionauth-app.log

```

**Comment by robotdan** [comment]
Please re-open if this is still an issue.
