### ISSUE TITLE
Long indexing times for new users

### ISSUE THREAD

**Issue by mam1101** [FusionAuth/fusionauth-issues#789]
### Description
We had a user created on July 30th who was not showing up in our Elasticsearch searches in the UI until August 2nd. I would prefer not to reindex every time I require finding a new user. Are there any current solutions to resolve this or is this a symptom of having many users?

**Comment by robotdan** [comment]
The user should be available in the ES index within milliseconds. If this is not the case you likely are having some issues with your Elasticsearch configuration.

If you are running more than one instance of Elasticsearch in a cluster configuration, you'll want to ensure that the cluster is in the `green` status and all nodes are communicating correctly.

**Comment by markschmid** [comment]
I just wanted to open an issue, then I found this one. We're using the FusionAuth API and are experiencing the following:
Right after we've created a new user, we're searching for all users (via query, in ES), yet the newly created user is not part of the result set. If we delay by let's say 500ms, we're fine.
Seems to me that once the API responds with success to the creation of a new user, that user should be in a search result set. It's not a big problem, but somehow it does not feel correct. I might be mistaken 😇.

**Comment by robotdan** [comment]
@markschmid this is likely working as design, Elasticsearch is async, so there will be some delay in consistency. 

We could delay the response on the API until the search index is consistent, this tradeoff in latency and performance is generally not idea. 

If you need to immediately query the index after an update, you could try calling the Search Engine Flush API. Generally this is not required, but depending upon your workflow it may help. 

https://fusionauth.io/docs/v1/tech/apis/users#flush-the-search-engine

**Comment by markschmid** [comment]
@robotdan OK, it's what I was expecting. Thanks for the hint with the Flush API, I'll look into it.
It's actually all documented, very specific to my use case: 😊
```In practice it is unlikely you’ll find a need for this API in production unless you are performing search requests immediately following an operation that modifies the index and expecting to see the results immediately.```

**Comment by robotdan** [comment]
Closing this out. If you are still experiencing this issue, please provide as much detail as possible and we'll try to recreate.
