### ISSUE TITLE
Connection with MySQL RDS 

### ISSUE THREAD

**Issue by myfingersarebroken** [FusionAuth/fusionauth-issues#790]
### Description 
I've attempted to deploy Fusionauth in Kubernetes with minimum setup and without Maintenance Mode but it can't connect to my database with root user and password. I'm using Rancher 2 to orchestrate my kube cluster.

### Affects versions
- 1.18.4

### Steps to reproduce
- View the screenshots below

### Expected behavior
- View the login screen of Fusionauth

### Screenshots
<img width="1325" alt="Captura de Tela 2020-08-03 às 22 16 45" src="https://user-images.githubusercontent.com/4641737/89242731-a0769680-d5d8-11ea-8a20-249336199cfd.png">
<img width="1554" alt="Captura de Tela 2020-08-03 às 22 30 49" src="https://user-images.githubusercontent.com/4641737/89242907-05ca8780-d5d9-11ea-81d5-a0f56ef22132.png">

### Platform
 - Docker / Kubernetes

**Comment by myfingersarebroken** [comment]
I've logged into container and in the fusionauth.properties the database is not updated to correspond with the value in the env DATABASE_URL
<img width="1585" alt="Captura de Tela 2020-08-04 às 14 02 05" src="https://user-images.githubusercontent.com/4641737/89322938-639fb380-d65b-11ea-8370-09cf3722b771.png">

**Comment by robotdan** [comment]
If you're using silent mode which is indicated by your first screenshot, you're using environment variables. 

The environment variables take precedence over the values found in the `fusionauth.properties` file. 
https://fusionauth.io/docs/v1/tech/reference/configuration#environment-variables

**Comment by myfingersarebroken** [comment]
Ok. But do you have some clue on why Fusionauth can't connect with MySQL?

**Comment by myfingersarebroken** [comment]
Why Fusionauth forces the database to use utf8mb4 as the default character_set_server and why not set this char set on database creation???
<img width="900" alt="Captura de Tela 2020-08-05 às 01 24 36" src="https://user-images.githubusercontent.com/4641737/89371812-c83e2b00-d6ba-11ea-8c27-e60dbf4a59ed.png">

**Comment by robotdan** [comment]
https://fusionauth.io/docs/v1/tech/installation-guide/database#mysql-and-unicode

https://fusionauth.io/docs/v1/tech/reference/configuration

>database.mysql.enforce-utf8mb4 [String] Defaults to true
>When set to true and using MySQL, a 4 byte UTF compatible character set configuration is enforced at startup.
>
>If this validation is not desired or not it is not possible to modify your MySQL configuration to satisfy the validation, disable this check by setting this value to false. If this is false, any attempt to store a 4 byte unicode character will cause the INSERT or UPDATE request to fail. The initial MySQL UTF-8 implementation only supported up to characters up to 3 bytes in length; utf8mb4 extends this to 4 byte characters.

**Comment by myfingersarebroken** [comment]
Ok. So, how can I override this configuration in docker setup? I've searched in this docs and I don't found it.
https://fusionauth.io/docs/v1/tech/installation-guide/docker

**Comment by mooreds** [comment]
I don't see a way to do that with an environment variable at present. 

I'm not super familiar with k8s, but can you mount a directory containing the fusionauth.properties (with the `database.mysql.enforce-utf8mb4` value set to false)? 

Alternatively, can you try using postgresql, which doesn't have this limitation?

**Comment by robotdan** [comment]
We do have an overhaul coming in the next release or two for configuration values so they can be modified using environment, properties or Java system properties. 

In the current version, one option is for you to mount your own version of the `fusionauth.properties` file in your container to turn off this validation. 

As a side note, I would highly discourage turning off this validation. You do not have control over what user's enter for their email, username, or name fields (as an example). If any of these values container 4 byte unicode, MySQL explodes. I would not run it that way in production. 

PostgreSQL is a better choice in general, but if you have to use MySQL, using `utf8mb4` is almost a must if you have any sort of user generated content.

**Comment by myfingersarebroken** [comment]
I've created a custom image from fusionauth/fusionauth-app:1.18.5 where I copy a custom fusionauth.properties to the /usr/local/fusionauth/config container folder. It resolved my problem and now we can control updates with git.
For MySQL the problem is that I'm not the database administrator and I think it's been running like this since It's deployment. The responsible for the database said that they have many legacy applications and must analyze the impact of my request, which I agree.
Thanks! =D

**Comment by robotdan** [comment]
Glad you found a working solution @myfingersarebroken !
