### ISSUE TITLE
Linking social with accounts with different email

### ISSUE THREAD

**Issue by saul-gush** [FusionAuth/fusionauth-issues#792]
## Linking social with accounts with different email

I have often come across different email addresses across social identity/account with other projects I've been involved with. Particularly Facebook where personal/business email addresses are different. I want to see what is the best way to handle this scenario with Fusionauth. 

### Description

Scenario: Register with social e.g. Facebook

The user signs up with Facebook. I usually send them to a register page after that to confirm email address and set a password. Lets say the user changes the email from what was provided from Facebook, what is the best way to link the the two? Is it simply changing the email address of the signed up user and then verify email address. If so, if the user comes back and logs in again with their Facebook, I am assuming it wont conflict if the email of the Facebook is different to what is on Fusionauth?

Scenario: Register with email and password but need to link social (e.g. Facebook) to the existing account

1. The user registers with email and password
2. They either login with their social account but the email address is not the same or we provide a section in their profile to link a social account to their existing account.

What is the best way to go about this? It is a pretty common scenario and makes a world of a difference for the user experience.

**Comment by robotdan** [comment]
Is this the same as https://github.com/FusionAuth/fusionauth-issues/issues/751 ?

**Comment by saul-gush** [comment]
Yes I think it is - its super important and very common. I used to deal with support tickets where the user logged in via Facebook and then wasnt receiving the verify email because they didnt realise that it was going to another email address. Thats when we asked the user to confirm their email address on the second step. They often changed it to something else.

For scenario one - that should be straight forward, I think it should work with current setup?

For scenario two - maybe if the user is oauth logged in already (on Fusionauth), you can then do a do you want to link this Facebook/Google/etc account to your username/email address kind of flow.

That should cover your edge cases. As the Fusionauth ID should then have links to each identity provider ID.

Happy to follow up on the other ticket btw :)

**Comment by mooreds** [comment]
@saul-gush please upvote number #751. Since it's a duplicate, I'm going to close.
