### ISSUE TITLE
Adding an OpenID Connect identity provider with invalid urls hides the error messages

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#794]
### Description 

If you add an OpenID Connect identity provider and choose not to 'Discover endpoints' and provide an invalid url (perhaps missing the `https://` section), you don't see any error messages when you click save. You just are taken back to the same page, and the 'Discover endpoints' checkbox is set to true. If you set it to false, you do see the error messages, but most users won't know to do that.

### Affects versions

1.18.5, running in docker.

### Steps to reproduce
1. Go to http://localhost:9011/admin/identity-provider/
1. Create an open id connect identity provider
1. Click on 'Discover endpoints' so it is set to false.
1. Enter `abc.com` in the 'authorization endpoint' field.
1. Fill out the rest of the required fields.
1. Click 'save'

You are shown the same screen, the identity provider is not added, no error message is shown, 'Discover endpoints' is set to true.

### Expected behavior
'Discover endpoints' should remain false and the errors should be displayed.

### Platform

Saw in Safari and Firefox, with FA running in docker.

**Comment by amans330** [comment]
The errors are being displayed correctly on version 1.21.1. The 'Discover endpoints' however does becomes true which needs to be corrected.

**Comment by amans330** [comment]
PR --> https://github.com/FusionAuth/fusionauth-app/pull/27

**Comment by robotdan** [comment]
Accepted https://github.com/FusionAuth/fusionauth-app/pull/27
