### ISSUE TITLE
Ability to customize SMS messages

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#796]
### Problem

We’re in the middle of implementing 2FA [using Twilio](https://fusionauth.io/docs/v1/tech/integrations/twilio). I’ve been searching but can’t find where I would go to change the message for the SMS from ‘Two Factor Code..’ (We call it Two-Step Verification as per Google’s standards). and would also like to brand it so that our users know it’s actually coming from us. 

### Solution

Allow for customization of any SMS templates that are sent. I believe there is only one, but if there are any more, allow those to be customized too. 

Additionally, I'd like them to be able to be localized and documented in the same way that the email templates are.

### Alternatives/workarounds

Implement 2fa outside of the Twilio integration using the APIs. https://fusionauth.io/docs/v1/tech/apis/two-factor

### Additional context
https://fusionauth.io/community/forum/topic/14/is-there-a-way-to-customize-the-two-factor-code-message-that-comes-when-the-twilio-integration-is-enabled indicates this is on the roadmap.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Delivered as message templates in 1.26.0. See doc for Messenger API and Message templates API and in the UI under customizations.
