### ISSUE TITLE
Webhook test json is reset each time you test from the admin UI

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#797]
### Description 

If you are using the webhook test button from the admin ui, you can edit the sample json and then press the test button. The edited json is sent.

However, the textarea is reset to the default json. This is annoying.

### Affects versions
I see this with version 1.18.1

### Steps to reproduce
1. Login to the admin ui
1. Go to settings
1. Go to webhooks
1. Add a new webhook. Whether it actually exists doesn't matter (I don't think), but mine did.
1. Click the 'test' link on the index page by your new webhook.
1. Modify the JSON. I changed 'favorite ship' under `data` to be `xwing`.
1. Click the test button.

The JSON is reset back.

### Expected behavior

The JSON is maintained across submissions.

### Platform

Tested on FF and Safari on the mac.

### Additional context

Workaround: save off your webhook json and just copy and paste it in each time.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/793

### Release Notes
When using the Webhook test action in the UI, changes to the example request body were not preserved. Changes will now be preserved across send requests for the browser session. This means a test can be run repeatedly without having to perform the same edits to the default event request body.

**Comment by robotdan** [comment]
We could write the example JSON to local storage so your modifications would be preserved, or just preserve it between requests with an action cookie.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/308
