### ISSUE TITLE
Can't turn off database.mysql.enforce-utf8mb4 via environment variable

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#798]
### Description 

One can't turn off `database.mysql.enforce-utf8mb4` via environment variable. This makes turning it off in docker difficult because you have to mount a directory and set up a `fusionauth.properties` file.

### Affects versions

Per the docs, all of them. https://fusionauth.io/docs/v1/tech/reference/configuration is the doc I'm checking.

### Steps to reproduce
1. Try to turn off the `database.mysql.enforce-utf8mb4` setting when running in Docker.

You can't. :)

### Expected behavior

You can disable the utf8mb4 check via an environment variable

### Platform

n/a

### Related
https://github.com/FusionAuth/fusionauth-issues/issues/752

### Additional context

There are implications of turning this off: https://fusionauth.io/community/forum/topic/109/what-are-the-implications-of-turning-off-enforce-utf8mb4-for-mysql

**Comment by voidmain** [comment]
FYI - this is coming in 1.19.0. It will allow all configuration properties to be set via environment variable, `-D` Java property, or in the configuration file. It's gonna be awesome! ;)

**Comment by robotdan** [comment]
Also, for the record in case se anyone else sees this issue. It is highly discouraged to turn off this enforcement in production. 

The work around is to either create your own docker image with this value set in the `fusionauth.properties` file, or to mount this config file in your image and modify it as you like.

**Comment by LohithBlaze** [comment]
+1

**Comment by robotdan** [comment]
This will be resolved under issue https://github.com/FusionAuth/fusionauth-issues/issues/752.
