### ISSUE TITLE
Negative user count in dashboard

### ISSUE THREAD

**Issue by gurupras** [FusionAuth/fusionauth-issues#799]
### Description 
While deleting users, I decided to start two concurrent processes that were both doing the same thing:
```
const query = {
  search: {
    queryString: `email:*`,
    numberOfResults
  }
}

while (...) {
    const result = await fusionAuthClient.searchUsersByQueryString(query)
    const { response } = result
    const userIds = result.response.users.map(x => x.id)
    await fusionAuthClient.deleteUsers({
      hardDelete: true,
      userIds
    })
}
```

After a while, I ended up with negative user counts:

### Affects versions
v1.18.1

### Steps to reproduce
Run multiple processes with similar code as shown above

### Expected behavior
Total user count should never be negative

### Screenshots
![image](https://user-images.githubusercontent.com/2933207/89713303-e5962200-d964-11ea-8c05-7f46ebd1a7bf.png)

### Platform
(Please complete the following information)
 - OS: Ubuntu 20.04.1
 - Database PostgresSQL 12.2 (Ubuntu 12.2-4)

**Comment by robotdan** [comment]
I saw this on a customer system recently as well. We'll have to attempt to recreate.

**Comment by robotdan** [comment]
Recreated.
