### ISSUE TITLE
Stuck while installing for first time

### ISSUE THREAD

**Issue by Patrick-Spiegel** [FusionAuth/fusionauth-issues#8]
![image](https://user-images.githubusercontent.com/35311793/47158113-3568ac80-d2eb-11e8-855b-d67e82f10bb1.png)

I am already stuck...
```mysql> CREATE USER 'fusionauth'@'%' IDENTIFIED BY 'CMuIi_Fp2ub4Aqpk4r6I6vuRMmCTvbFBbwObHrHjEwg';
Query OK, 0 rows affected (0.00 sec)

mysql> drop database fusionauth;
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT ALL PRIVILEGES ON *.* TO 'fusionauth'@'%' WITH GRANT OPTION;
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;

```mysql> CREATE USER 'fusionauth'@'localhost' IDENTIFIED BY 'CMuIi_Fp2ub4Aqpk4r6I6vuRMmCTvbFBbwObHrHjEwg';
Query OK, 0 rows affected (0.00 sec)

mysql> drop database fusionauth;
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT ALL PRIVILEGES ON *.* TO 'fusionauth'@'localhost' WITH GRANT OPTION;
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)```

**Comment by robotdan** [comment]
Hi Patrick, 

Sorry you're having this issue. 

It looks like your `Super User credentials` are incorrect. For MySQL, the super user is likely `root`, and then you'll need to provide the root password. 

In your screenshot, you're entering `fusionauth` and `CMuIi_Fp2ub4Aqpk4r6I6vuRMmCTvbFBbwObHrHjEwg` for the `Super User credentials`.

Review the following for additional information:
https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app#maintenance-mode

If you will be using maintenance mode to create the schema, you do not need to create the `fusionauth` user in MySQL, we will create it on your behalf once you provide the super user credentials. 

The credentials you used to connect to the MySQL shell should be used in the `Super User credentials` section. The `FusionAuth credentials` section is the user and password that we will create to own the FusionAuth schema. 

Let me know how this goes. 
Daniel

**Comment by robotdan** [comment]
Hi @Patrick-Spiegel did you still need assistance? I'll plan to close out this issue unless I hear otherwise. 

Thanks,
Daniel

**Comment by Patrick-Spiegel** [comment]
Is there a hard check for the root username? I attached the whole log of my actions, including `mysql> GRANT ALL PRIVILEGES ON *.* TO 'fusionauth'@'%' WITH GRANT OPTION;`

So there should all permissions be available, should there?

**Comment by robotdan** [comment]
If you are in maintenance mode, we do require you to provide the database root credentials. 

The root credentials will be used to create the schema and ensure the configured user and password in the `FusionAuth credentials` section exist and can connect to the configured database. 

We do not store the root credentials. The credentials configured in the `FusionAuth credentials` section are persisted in the `fusionauth.properties` file. If you're on Linux this file is located here `/usr/local/fusionauth/config/fusionauth.properties`.

The ideal installation path is to allow FusionAuth to configure the schema on your behalf. This means you do not need to run any SQL commands yourself as you have done. 

If you want to keep your current configuration, and you have already created a MySQL user named `fusionauth` with a password of `CMuIi_Fp2ub4Aqpk4r6I6vuRMmCTvbFBbwObHrHjEwg` then just ensure you enter those two values in the section labeled `FusionAuth credentials`. 

In the section labeled `Super User credentials` enter the root credentials for MySQL. Doing this will allow FusionAuth to verify the user `fusionauth` exists and can connect to the schema. 

Does that answer your question?

**Comment by robotdan** [comment]
@Patrick-Spiegel If you're still having problems let me know otherwise I'll plan to close out this issue.

**Comment by Patrick-Spiegel** [comment]
@robotdan yeah, this can be closed for now. I have currently not the time to re-evaluate it.
