### ISSUE TITLE
 Detect if the user is already logged in and store the user object

### ISSUE THREAD

**Issue by arunkumar413** [FusionAuth/fusionauth-issues#80]
### Description
Hi Team,

I was able to successfully get the authorization code from futionauth and would like the retrieve the logged in user info.

Is there any best way/best practice that fusionauth recommend to detect if the the user is logged in and also store the logged in user info in cookie/local storage,  vue/react state management.

Thanks,
Arun

**Comment by robotdan** [comment]
> ... and would like the retrieve the logged in user info.

A typical workflow to retrieve the user details in an OAuth2 / OpenID Connect style would be to use the access token to call the Userinfo endpoint.
https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo

You could also use the access token (jwt) to call the User API. (see  Retrieve a User using a JWT)
https://fusionauth.io/docs/v1/tech/apis/users#retrieve-a-user

> Is there any best way/best practice that fusionauth recommend to detect if the the user is logged in and also store the logged in user info in cookie/local storage, vue/react state management.

There are many existing patterns to solve this problem. If you're using vue/react, a common way would be to use `express-session` if you're using a node backend. 

If you're building a true single page web application w/out any backend, you could store the JWT (access token) in local storage or a cookie. This has some security implications that you should fully understand before taking this approach.

**Comment by arunkumar413** [comment]
Thanks for the info, @robotdan.  In my  usecase, I'd like to detect if the user is logged in even before the auth code is returned by the fusionauth (eg: user directly trying to visit the restricted page). I found this (https://auth.nuxtjs.org/api) module. Is it possible to integrate this with the fusionauth to simplify the process?

**Comment by robotdan** [comment]
Yes, it looks like the `auth.nuxtjs` module supports a generic OAuth2 strategy scheme.
https://auth.nuxtjs.org/reference/schemes/oauth2

From reading the documentation it looks like it supports the Implicit Grant out of the box, this is when you set the `response_type` to `token`. If you want to the Authorization grant, you set the `response_type` to `code`, and in this mode you'd have to handle the token exchange yourself, it does not appear as though this library handles that grant. To do the token exchange yourself, you'd want to use a backend and not make this request from a front end webapp. 

The implicit grant is not currently supported, but it should be out shortly. If you can wait for that, then this module should work for you. 

We could also look at building a custom strategy / schema for the Nuxt.js Auth module.

**Comment by arunkumar413** [comment]
Hi @robotdan,

Thanks for looking into this and for all you help. I would be happy if you can build a strategy for nuxtjs and react's nextjs as well.

However, I would suggest building fusionauth's own generic module and components  for react, nextjs, nuxtjs and vue so that you it would be very easy to streamline the entire the login, authorization and user access control management.

**Comment by arunkumar413** [comment]
Instead of building separate components various frameworks, you may consider building framework agnostic web components  (https://www.webcomponents.org/introduction).

**Comment by robotdan** [comment]
> The implicit grant is not currently supported, but it should be out shortly. If you can wait for that, then this module should work for you.

The Implicit Grant was added in version 1.5.0.  https://fusionauth.io/docs/v1/tech/release-notes/
