### ISSUE TITLE
Cannot import users via API with encrypted password salt

### ISSUE THREAD

**Issue by virginijus-servicebridge** [FusionAuth/fusionauth-issues#811]
Cannot import users via API with encrypted password salt

When trying to import users via REST API with encryption scheme, salt and password I get error
```
{
    "fieldErrors": {
        "user.salt": [
            {
                "code": "[invalid]user.salt",
                "message": "The [user.salt] is expected to be a Base64 encoded string. Invalid salt(s) [ dGhpcy5pcy5teS5zYWx0]."
            }
        ]
    }
}

```
Using FusionAuth™ version 1.18.5 on Docker

### Steps to reproduce
From Postman do POST to http://localhost:9011/api/user/import
with sample request
```
{ 
    "users":[
        {
            "username": "user001",
            "active": true,
            "salt": " dGhpcy5pcy5teS5zYWx0",
            "password": "CXF3o/b5zM3r174frU8keg==",            
            "encryptionScheme": "salted-pbkdf2-hmac-sha256",
            "factor": 500
        }
    ]
}
```
Is it something I do wrong or is it a bug or an issue?

**Comment by robotdan** [comment]
I think you have a leading space in your salt, try removing the leading space.

**Comment by virginijus-servicebridge** [comment]
OMG, cannot believe I've missed that leading space... 
It works now, thanks.

**Comment by robotdan** [comment]
Ha.. happens to the best of us.
