### ISSUE TITLE
Authentication by applicationId and token doesn't work

### ISSUE THREAD

**Issue by mkoszutowski** [FusionAuth/fusionauth-issues#812]
### Description

I have a problem with Application Authentication Tokens. I've generated token but using this token I can't authenticate a user. I've followed this manual https://fusionauth.io/docs/v1/tech/tutorials/application-authentication-tokens but without success.

### Affects versions
Tested on 1.15.8 and 1.18.7

### Steps to reproduce
1. Enable authentication tokens for application
2. Generate authentication token for existing user

On my local env, it was exactly that request
```
curl -k -X POST -H 'Content-Type: application/json' -H "Authorization: lXMaXmHA2sqeQL3QnEmtXgwOhtIRGr9o2WY4dwKnC9o" https://sso.local/api/user/registration/fcdd8d0c-8813-4121-9733-65ee1a191125 -d'
{
  "generateAuthenticationToken": true,
  "registration": {
    "applicationId": "ae1d0d86-7132-4ff6-9685-7861b5e220ac",
    "data": {
      "instances": [
        "mkoszut"
      ]
    },
    "preferredLanguages": [
      "en",
      "fr"
    ],
    "roles": [
      "Instance Admin"
    ],
    "timezone": "America/Chicago",
    "username": "github"
  }
}
'
```
and response

```
{"registration":{"applicationId":"ae1d0d86-7132-4ff6-9685-7861b5e220ac","authenticationToken":"qUi7wYNIo8_cJ9OcJGnW-zZ789RllNlXhdGBVcXopaA","data":{"instances":["mkoszut"]},"id":"9779f8fd-4e7f-4198-81f5-ee3d2c52b9ca","insertInstant":1597318646758,"lastLoginInstant":1597318646767,"lastUpdateInstant":1597318646758,"preferredLanguages":["en","fr"],"roles":["Instance Admin"],"timezone":"America/Chicago","username":"github","usernameStatus":"ACTIVE","verified":true},"token":"..."}
```

3. Login using a token 

I've tested with those requests
```
curl -k -X POST -H 'Content-Type: application/json' -H 'X-FusionAuth-TenantId: 37646665-3737-6661-3866-616231323233' https://sso.local/api/login -d'
{
  "loginId": "github",
  "password": "qUi7wYNIo8_cJ9OcJGnW-zZ789RllNlXhdGBVcXopaA",
  "applicationId": "ae1d0d86-7132-4ff6-9685-7861b5e220ac"
}
' -vvv
```
and
```
curl -k -X POST -H 'Content-Type: application/json' -H 'X-FusionAuth-TenantId: 37646665-3737-6661-3866-616231323233' https://sso.local/api/login -d'
{
  "loginId": "created_user@emai.com",
  "password": "qUi7wYNIo8_cJ9OcJGnW-zZ789RllNlXhdGBVcXopaA",
  "applicationId": "ae1d0d86-7132-4ff6-9685-7861b5e220ac"
}
' -vvv
```
and in both cases, I've given response 401

```
...
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fdabe808200)
> POST /api/login HTTP/2
> Host: sso.local
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 147
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 401 
< server: openresty/1.15.8.2
< date: Thu, 13 Aug 2020 12:24:21 GMT
< content-length: 0

```

### Expected behavior
A user should be authenticated.

I'm not sure if it is really an issue or some lack of info in the documentation but I don't have any idea how I can force that kind of authentication to work.

**Comment by robotdan** [comment]
The `username` in the registration cannot be used for login. So I would not expect the `loginId` of `github` to work. Can I assume that your email address set on the `user` object is `created_user@emai.com` ?

**Comment by mkoszutowski** [comment]
@robotdan yes, in my case `created_user@emai.com` is user object email address

**Comment by robertminer1** [comment]
I seem to be having a similar issue when passing the applicationId to the login endpoint.  

```
{
  "loginId": "{{login_email}}",
  "password":"{{password}}",
  "applicationId" : "04d94ef9-f21c-464b-9207-bb9c1d7ecacb"
  }
```

**Comment by mooreds** [comment]
I replicated this.

Note that if you provide an API key to the login call, it works. But if you don't, you get the 401 error.

```
# works
#curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/login' -d '{"loginId": "user@example.com", "password": "l1PB2I9yFhL0dk-TY7_Ch_YqvDPei2daxNqfaG7v2Q4", "applicationId": "aacd7b19-bbea-447a-a6c5-806745c99be1" }'

# 401
curl -vvv -XPOST -H 'Content-type: application/json' 'http://localhost:9011/api/login' -d '{"loginId": "user@example.com", "password": "l1PB2I9yFhL0dk-TY7_Ch_YqvDPei2daxNqfaG7v2Q4", "applicationId": "aacd7b19-bbea-447a-a6c5-806745c99be1" }'
```

So the workaround right now would be to use an API key for the login, if possible.

**Comment by robertminer1** [comment]
> I replicated this on 1.19.8.
> 
> Note that if you provide an API key to the login call, it works. But if you don't, you get the 401 error.
> 
> ```
> # works
> #curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/login' -d '{"loginId": "user@example.com", "password": "l1PB2I9yFhL0dk-TY7_Ch_YqvDPei2daxNqfaG7v2Q4", "applicationId": "aacd7b19-bbea-447a-a6c5-806745c99be1" }'
> 
> # 401
> curl -vvv -XPOST -H 'Content-type: application/json' 'http://localhost:9011/api/login' -d '{"loginId": "user@example.com", "password": "l1PB2I9yFhL0dk-TY7_Ch_YqvDPei2daxNqfaG7v2Q4", "applicationId": "aacd7b19-bbea-447a-a6c5-806745c99be1" }'
> ```
> 
> So the workaround right now would be to use an API key for the login, if possible.

Thank you for the reply.  Unfortunately, in my use case we're using Fusion Auth from a react frontend to then pass the token to our backend.  Unless theres a secure way to pass the api key exposed?

**Comment by robotdan** [comment]
In the UI , can you navigate to `Application > Edit Security` and review the login API security setting?

https://fusionauth.io/docs/v1/tech/core-concepts/applications#security

By default the login API requires an API key. This is secured by default so that it behaves similar to a confidential oauth2 grant which would require a client Id and client secret. 

If you want to use the login API from a SPA where you cannot secure an API key you can disable this security constraint.

You could also optionally create an API key with access only to the login API and use this in react. This is not very secure, but perhaps more so than allowing open access to the login API endpoint.

**Comment by robotdan** [comment]
I opened feature request #933 that may be able to help with this type of usage.

**Comment by mooreds** [comment]
Ah, yes, looks like disabling the 'api key required' definitely solves this issue for me. @robertminer1 can you try that?

<img width="2032" alt="Screen Shot 2020-10-11 at 7 58 16 AM" src="https://user-images.githubusercontent.com/91825/95680539-bdf74c00-0b97-11eb-84a4-9d36115e382c.png">

If so, please comment but leave this issue open so I can update the doco.

**Comment by robertminer1** [comment]
Thank you!  Trying this out today!

**Comment by robertminer1** [comment]
It seems to be there now!  Fantastic! Thanks for your help!

**Comment by mooreds** [comment]
I updated and deployed the documentation, closing this bug: https://fusionauth.io/docs/v1/tech/tutorials/application-authentication-tokens/
