### ISSUE TITLE
Setting forgotPasswordEmailTemplateId using API and/or Kickstart does not work

### ISSUE THREAD

**Issue by pigletto** [FusionAuth/fusionauth-issues#817]
### Description 
I have a Kickstart script that creates new template for the "Forgot password e-mail" and then it sets the new template to be used by the default tenant. No errors are reported, template is created, but it is not changed for the tenant object.

I've also tried to update the tenant setting "forgotPasswordEmailTemplateId" using direct API call, but it does nothing too. Request is successful but no changes are done.

### Affects versions
1.18.6

### Steps to reproduce
1. Create new email template or choose one of the existing templates and store it's uid
2. Update tenant using API:

```python
res = client.patch_tenant('ac1ac975-7e5c-bea3-cdab-71ec395b1e13', 
                            {'tenant': {'issuer':'blah', 'emailConfigutation': 
                              {'forgotPasswordEmailTemplateId': '383b8787-7efc-4e8a-a00a-544ede4dfff1'}}})
```

3. Tenant setting for the issuer is updated but forgot email template remains unchanged

Kickstart sample code:

```json
{
      "method": "POST",
      "url": "/api/email/template/#{forgot_password_email_id}",
      "body": {
        "emailTemplate": {
          "defaultHtmlTemplate": "@{theme/email_templates/forgot_password/email_en.html}",
          "defaultTextTemplate": "@{theme/email_templates/forgot_password/email_en.txt}",
          "name": "New Forgot password",
          "fromEmail": "noreply@example.com",
          "defaultFromName": "Blah",
          "defaultSubject": "Password reset",
          "localizedFromNames": {
            "pl": "Blah PL",
            "ja": "Blah JA"
          },
          "localizedHtmlTemplates": {
            "pl": "@{theme/email_templates/forgot_password/email_pl.html}",
            "ja": "@{theme/email_templates/forgot_password/email_ja.html}"
          },
          "localizedTextTemplates": {
            "pl": "@{theme/email_templates/forgot_password/email_pl.txt}",
            "ja": "@{theme/email_templates/forgot_password/email_ja.txt}"
          },
          "localizedSubjects": {
            "pl": "Reset hasła",
            "ja": "Password reset"
          }
        }
      }
    },
    {
      "method": "PATCH",
      "url": "/api/tenant/#{FUSIONAUTH_TENANT_ID}",
      "body": {
        "tenant": {
          "issuer": "example.com",
          "themeId": "#{custom_theme_uid}",
          "emailConfiguration": {
            "defaultFromEmail": "no-reply@example.com",
            "defaultFromName": "Blah",
            "host": "mailhog",
            "password": "",
            "port": "1025",
            "security": "TLS",
            "username": "",
            "forgotPasswordEmailTemplateId": "#{forgot_password_email_id}"
          }
        }
      }
    }
```

### Expected behavior
I expect Forgot Password email template to be changed for the tenant

### Platform
Docker + PostgreSQL + Elasticsearch

**Comment by robotdan** [comment]
Can you post the JSON response from the Get Tenant API after kickstart has completed?

**Comment by pigletto** [comment]
Seems that API returns the correct value for the forgot password email template but in the UI it is not reflected. It only fails with the Default tenant. With a custom tenant, it works properly.

Kickstart part used:
{
      "method": "PATCH",
      "url": "/api/tenant/#{FUSIONAUTH_TENANT_ID}",
      "body": {
        "tenant": {
          "issuer": "someissuer",
          "themeId": "#{custom_theme_uid}",
          "emailConfiguration": {
            "defaultFromEmail": "no-reply@example.com",
            "defaultFromName": "Example",
            "host": "mailhog",
            "password": "",
            "port": "1025",
            "security": "TLS",
            "username": "",
            "forgotPasswordEmailTemplateId": "97119c4a-ba77-4bad-a3e5-fc9303bcdd2c"
          }
        }
      }
    },


Response for the default tenant:

{'configured': True,
 'connectorPolicies': [{'connectorId': 'e3306678-a53a-4964-9040-1c96f36dda72',
   'domains': ['*'],
   'migrate': False}],
 'emailConfiguration': {'defaultFromEmail': 'no-reply@example.com',
  'defaultFromName': 'Example',
  'forgotPasswordEmailTemplateId': '97119c4a-ba77-4bad-a3e5-fc9303bcdd2c',
  'host': 'mailhog',
  'password': '',
  'port': 1025,
  'security': 'TLS',
  'username': '',
  'verifyEmail': False,
  'verifyEmailWhenChanged': False},
 'eventConfiguration': {},
 'externalIdentifierConfiguration': {'authorizationGrantIdTimeToLiveInSeconds': 30,
  'changePasswordIdGenerator': {'length': 32, 'type': 'randomBytes'},
  'changePasswordIdTimeToLiveInSeconds': 600,
  'deviceCodeTimeToLiveInSeconds': 1800,
  'deviceUserCodeIdGenerator': {'length': 6, 'type': 'randomAlphaNumeric'},
  'emailVerificationIdGenerator': {'length': 32, 'type': 'randomBytes'},
  'emailVerificationIdTimeToLiveInSeconds': 86400,
  'externalAuthenticationIdTimeToLiveInSeconds': 300,
  'oneTimePasswordTimeToLiveInSeconds': 60,
  'passwordlessLoginGenerator': {'length': 32, 'type': 'randomBytes'},
  'passwordlessLoginTimeToLiveInSeconds': 180,
  'registrationVerificationIdGenerator': {'length': 32, 'type': 'randomBytes'},
  'registrationVerificationIdTimeToLiveInSeconds': 86400,
  'samlv2AuthNRequestIdTimeToLiveInSeconds': 30,
  'setupPasswordIdGenerator': {'length': 32, 'type': 'randomBytes'},
  'setupPasswordIdTimeToLiveInSeconds': 86400,
  'twoFactorIdTimeToLiveInSeconds': 300,
  'twoFactorTrustIdTimeToLiveInSeconds': 2592000},
 'failedAuthenticationConfiguration': {'actionDuration': 3,
  'actionDurationUnit': 'MINUTES',
  'resetCountInSeconds': 60,
  'tooManyAttempts': 5},
 'familyConfiguration': {'allowChildRegistrations': True,
  'deleteOrphanedAccounts': False,
  'deleteOrphanedAccountsDays': 30,
  'enabled': False,
  'maximumChildAge': 12,
  'minimumOwnerAge': 21,
  'parentEmailRequired': False},
 'httpSessionMaxInactiveInterval': 3600,
 'id': 'a8393aa9-13fd-bc45-7c99-6914acd7d74b',
 'insertInstant': 1600761677090,
 'issuer': 'someissuer',
 'jwtConfiguration': {'accessTokenKeyId': '53b7fa79-9a1b-c1fe-6c4f-b222bd6f64aa',
  'enabled': True,
  'idTokenKeyId': '092dbedc-30af-4149-9c61-b578f2c72f59',
  'refreshTokenExpirationPolicy': 'Fixed',
  'refreshTokenRevocationPolicy': {'onLoginPrevented': True,
   'onPasswordChanged': True},
  'refreshTokenTimeToLiveInMinutes': 43200,
  'refreshTokenUsagePolicy': 'Reusable',
  'timeToLiveInSeconds': 3600},
 'lastUpdateInstant': 1600761712618,
 'maximumPasswordAge': {'days': 180, 'enabled': False},
 'minimumPasswordAge': {'enabled': False, 'seconds': 30},
 'name': 'Default',
 'passwordEncryptionConfiguration': {'encryptionScheme': 'salted-pbkdf2-hmac-sha256',
  'encryptionSchemeFactor': 24000,
  'modifyEncryptionSchemeOnLogin': False},
 'passwordValidationRules': {'breachDetection': {'enabled': False},
  'maxLength': 256,
  'minLength': 8,
  'rememberPreviousPasswords': {'count': 0, 'enabled': False},
  'requireMixedCase': False,
  'requireNonAlpha': False,
  'requireNumber': False,
  'validateOnLogin': False},
 'themeId': '91f8b91f-c541-4f4b-8cc7-b341c155d926',
 'userDeletePolicy': {'unverified': {'enabled': False,
   'numberOfDaysToRetain': 0}}}

**Comment by robotdan** [comment]
> No errors are reported, template is created, but it is not changed for the tenant object.

I don't know if I follow, the email template Id you created in kickstart is `97119c4a-ba77-4bad-a3e5-fc9303bcdd2c` and that shows returned on the tenant API response. 

Where are you seeing that the template Id is not set?

**Comment by pigletto** [comment]
The change is not visible in the FusionAuth's user interface. It is returned correctly by the API.

**Comment by robotdan** [comment]
Ok, that is helpful. So does the email get sent? In other words, is this only a UI issue, but a not a functional one? 

If the API returns the correct template, I would assume it will get sent, and then it also has nothing to do with kickstart because the tenant is being updated correctly.

**Comment by pigletto** [comment]
I've tested this again with FA 1.20.1 and using the kickstart below, even though the API call returns valid response (forgot_password_email_id seems to be changed), the e-mail sent is **not changed**. Also the UI shows unchanged template. 

Kickstart script:
```
{
  "variables": {
    "my_theme_uid": "91f8b91f-c541-4f4b-8cc7-b341c144d926",
    "forgot_password_email_id": "97119c4a-ba77-4bad-a3e5-fc9303bcdd2c"
  },
  "apiKeys": [
    {
      "key": "473343d3afasdaf305882342bc1123c0d394857202484745670f11b1bd"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "/api/theme/#{my_theme_uid}",
      "body": {
        "sourceThemeId": "75a068fd-e94b-451a-9aeb-3ddb9a3b5987",
        "theme": {
          "name": "My theme"
        }
      }
    },
    {
      "method": "POST",
      "url": "/api/email/template/#{forgot_password_email_id}",
      "body": {
        "emailTemplate": {
          "defaultHtmlTemplate": "@{theme/email_templates/forgot_password/email_en.html}",
          "defaultTextTemplate": "@{theme/email_templates/forgot_password/email_en.txt}",
          "name": "OV Forgot password",
          "fromEmail": "noreply@example.com",
          "defaultFromName": "Example",
          "defaultSubject": "Password reset"
        }
      }
    },
    {
      "method": "PATCH",
      "url": "/api/tenant/#{FUSIONAUTH_TENANT_ID}",
      "body": {
        "tenant": {
          "issuer": "examp.le",
          "themeId": "#{my_theme_uid}",
          "emailConfiguration": {
            "defaultFromEmail": "no-reply@example.com",
            "defaultFromName": "Example",
            "host": "mailhog",
            "password": "",
            "port": "1025",
            "security": "TLS",
            "username": "",
            "forgotPasswordEmailTemplateId": "#{forgot_password_email_id}"
          }
        }
      }
    }
  ]
}

```


Kickstart output:

```
fusionauth_1            | ---------------------------------------------------------------------------------------------------------
fusionauth_1            | -------------------------------------------- Kickstarting ? --------------------------------------------
fusionauth_1            | ---------------------------------------------------------------------------------------------------------
fusionauth_1            | 
fusionauth_1            | 2020-11-13 9:47:16.748 AM INFO  io.fusionauth.api.service.system.kickstart.KickstartRunner - Summary:
fusionauth_1            |   - Created API key ending in [...b1bd]
fusionauth_1            |   - Completed [POST] request to [/api/theme/91f8b91f-c541-4f4b-8cc7-b341c144d926]
fusionauth_1            |   - Completed [POST] request to [/api/email/template/97119c4a-ba77-4bad-a3e5-fc9303bcdd2c]
fusionauth_1            |   - Completed [PATCH] request to [/api/tenant/d1bb8d16-ce84-9e96-eab4-f38a7c30c70a]
```

API call output:
```
In [1]: from fusionauth.fusionauth_client import FusionAuthClient
In [2]: client = FusionAuthClient('473343d3afasdaf305882342bc1123c0d394857202484745670f11b1bd', 'https://auth.examp.le')
In [3]: res = client.retrieve_tenants()
In [4]: res.success_response['tenants'][0]['emailConfiguration']
Out[4]: 
{'defaultFromEmail': 'no-reply@example.com',
 'defaultFromName': 'Example',
 'forgotPasswordEmailTemplateId': '97119c4a-ba77-4bad-a3e5-fc9303bcdd2c',
 'host': 'mailhog',
 'password': '',
 'port': 1025,
 'security': 'TLS',
 'username': '',
 'verifyEmail': False,
 'verifyEmailWhenChanged': False}
```

**Comment by amans330** [comment]
Hi @pigletto We were unable to recreate the issue on version 1.21.0 using the same post and patch requests you provided. We found that the changes were made correctly and are visible in the UI in the Tenants section. Please let us know if you are still facing the this issue with the latest version (1.21.0).

**Comment by robotdan** [comment]
@pigletto let us know if you can still recreate, if so, please let provide any additional details that may help us reproduce. Thanks!
