### ISSUE TITLE
New user registration

### ISSUE THREAD

**Issue by jsissom** [FusionAuth/fusionauth-issues#82]
### Description
I would like to register a new user but allow the user decide if they want to provide an email address & password or login via google or facebook.  I see the API for a new user registration but it looks like it only handles email/password authentication.  Can you let me know if it is possible to register a user allowing them to pick authentication types?

Thanks

**Comment by robotdan** [comment]
Hi @jsissom - I think this should work for you out of the box with version >= 1.4.0 

If you enable a third party Identity Provider such as Facebook, you can enable Registration by ensuring the `Create registration` toggle is enabled. 

Doing this will cause the following will occur when a user logs in with Facebook:

1. The user does not yet exist? User is created. 
2. The user is not yet registered for the application, the user is registered and assigned any roles marked as default.

This will allow users to self register for your application by logging in via Facebook. 

If the user wishes to login / register directly w/out using a social login provider such as Facebook, starting in version 1.4.0, you may enable self service registration on the application by navigating to the Application configuration `Settings --> Applications` and clicking on the `Registration` tab. Here you will find a toggle for `Self Service Registration`. If you enable this for the application, an additional button will be made available on the login screen to allow users to register for your application. 

A tutorial for this second option is forthcoming. In the mean time let me know if you need further assistance.

**Comment by jsissom** [comment]
Thank you, I will try this out.

**Comment by robotdan** [comment]
Excellent, thanks for the update @jsissom let me know how it goes!

**Comment by jsissom** [comment]
This feature works for me.
