### ISSUE TITLE
Allow to set an email as verified

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#821]
### Problem

As we are facing a SPAM issue (#820), some customer are not able to authenticate to our platform anymore.

We currently have no alternative to unlock our customer situation.

### Solution
Having a "Mark email as verified" action button or give the option on the edit form.

### Alternatives/workarounds

Direct database change:

```SQL
update identities set verified='t' where users_id='xxx';
```

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
Related: 

https://github.com/FusionAuth/fusionauth-issues/issues/801
https://github.com/FusionAuth/fusionauth-issues/issues/285

**Comment by soullivaneuh** [comment]
@mooreds Of course! I didn't find this one, sorry about that.
