### ISSUE TITLE
PATCHing a user without providing an email address or username returns 200

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#824]
### Description 

The docs state that a username or password is required when updating a user: https://fusionauth.io/docs/v1/tech/apis/users#update-a-user

However, running a PATCH command without either returns a 200.

```
curl -vvv -XPATCH -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/user/89c55bf9-410a-4171-b5b6-e13ec7c38a53 ' -d '{"user": {"verified" : false } }'
```

```
* upload completely sent off: 32 out of 32 bytes
< HTTP/1.1 200 
< Content-Type: application/json;charset=UTF-8
< Content-Length: 474
< Date: Thu, 20 Aug 2020 15:39:43 GMT
< 
* Connection #0 to host localhost left intact
{"user":{"active":true,"connectorId":"e3306678-a53a-4964-9040-1c96f36dda72","email":"testverification@example.com","id":"89c55bf9-410a-4171-b5b6-e13ec7c38a53","insertInstant":1597937815305,"lastLoginInstant":1597937815336,"lastUpdateInstant":1597937983781,"passwordChangeRequired":false,"passwordLastUpdateInstant":1597937815332,"tenantId":"30663132-6464-6665-3032-326466613934","twoFactorDelivery":"None","twoFactorEnabled":false,"usernameStatus":"ACTIVE","verified":true}}* Closing connection 0
```

### Affects versions
1.18.6

### Steps to reproduce
1. Create a user.
2. Update the curl script with your API key and the user's id
3. Run the curl script

You get back a 200.

### Expected behavior

I'd expect a 400, since the request is malformed.

### Platform

curl

**Comment by mgetka** [comment]
I believe it's ok because
> When using the PATCH method, use the same request body documentation that is provided for the PUT request. The PATCH method will merge the provided request parameters into the existing object, __this means all parameters are optional__ when using the PATCH method and you only provide the values you want changed.

**Comment by robotdan** [comment]
@mgetka is correct. I believe this is working as designed. 

@mooreds Can you expand upon your expectations? Perhaps we need to add additional clarifications to the documentation.

**Comment by robotdan** [comment]
@mooreds I think this is working as designed. Planning to close - but please re-open if I am missing something or you think we need to make a change somewhere.
