### ISSUE TITLE
Optional number fields can't be left blank

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#827]
### Description 
When creating an advanced registration form, if you set a field to be a number and optional, when you try to register, you are shown an 'invalid' message.

### Affects versions
1.18.7

### Steps to reproduce
1. Create a new form field, specify it as optional, a number for the control and a number for the data type.
1. Add it to a form, along with username and password
1. Make that new form your application's registration form
1. Add a redirect_uri to the application, if needed
1. View the application and note the registration url.
1. Open up an incognito window and go to that url
1. Put in a username and pw, but not a number.
1. Submit the form.

You are prevented from submitting the form and shown a red 'invalid' message by the number.

### Expected behavior
An optional number field should submit with no value in it.

### Screenshots

![Screen Shot 2020-08-24 at 2 56 36 PM](https://user-images.githubusercontent.com/91825/91097518-117bfd80-e61d-11ea-8a84-f1b1d0da2fe1.png)
![Screen Shot 2020-08-24 at 2 57 51 PM](https://user-images.githubusercontent.com/91825/91097525-1345c100-e61d-11ea-944f-0ea35aaef35f.png)

### Platform
Firefox

**Comment by robotdan** [comment]
Release notes need to update that it is possible that a previously configured custom field validation error such as `[missing]user.data.foo` may now be `[blank].user.data.foo`. Validation errors should be tested after upgrade to ensure the custom validation errors are properly resolved.
