### ISSUE TITLE
Form control not shown on view screen of form field

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#828]
### Description 

You don't see the form control of an existing form field.

### Affects versions

1.18.7

### Steps to reproduce
1. Create a custom form field
1. Save it, noting the form control
1. Click the green magnifying glass to view it.

You don't see the form control (text, textarea, etc)

### Expected behavior
You'd see the form control.

### Screenshots
![Screen Shot 2020-08-24 at 3 21 26 PM](https://user-images.githubusercontent.com/91825/91098012-efcf4600-e61d-11ea-81ce-b2f2288152b7.png)

### Platform
Firefox, if it matters :)

**Comment by robotdan** [comment]
> Firefox, if it matters :)



Ah, yes. This is a known Firefox issue. WAD.


Ha.. kidding, it's a bug.
