### ISSUE TITLE
Token issued by JWT API does not contains aud claim if user is not registered for application

### ISSUE THREAD

**Issue by motzel** [FusionAuth/fusionauth-issues#832]
### Description 
If the user is not registered, the JWT API (/api/jwt/issue) returns a token that does not contain an aud claim.

### Affects versions
1.18.5

### Steps to reproduce
1. Create and application with self-registration DISABLED.
2. Try to issue a new access token (JWT) using an existing access token from other application. [GET /api/jwt/issue?applicationId={applicationId}]
3. Check new token claims - there are no applicationId and **aud** claim. 

### Expected behavior
No applicationId claim is expected because the user is not registered in the new application, but the token **should contain the aud claim**.  This behavior **should be consistent** with the Authorization Code Flow. Token issued for the same application in AC Flow **includes aud claim**, but does not include applicationId claim ,what is expected (see screenshots below).

### Screenshots
Token issued in Authorization Code Flow:
![image](https://user-images.githubusercontent.com/1758707/91301320-005df880-e7a5-11ea-83a9-35fbd95a721e.png)

Token issued by JWT API:
![image](https://user-images.githubusercontent.com/1758707/91301350-0d7ae780-e7a5-11ea-872d-613f8a2cb44a.png)

### Platform
Not applicable.

**Comment by robotdan** [comment]
Thanks for the report @motzel . 

There are a few places where we may issue a JWT:

1. Login API (in various forms), omits `aud`, `applicationId` and `roles` based upon registration status.
2. JWT Issue API,  omits `aud`, `applicationId` and `roles` based upon registration status.
3. OAuth grants, always returns `aud` claim, omits `applicationId` and `roles` based upon registration status.

The docs indicate that the `aud` should always be returned and that we only omit `applicationId` and `roles` if the user is not registered. This would indicate that 1 and 2 are wrong. 

https://fusionauth.io/docs/v1/tech/oauth/tokens

We'll take a look!
