### ISSUE TITLE
404s when attempting to start passwordless logins "after the first"

### ISSUE THREAD

**Issue by atrauzzi** [FusionAuth/fusionauth-issues#833]
Following up on the [recent mention of being able to leverage partially initiated/completed oauth grants](https://fusionauth.io/community/forum/topic/333/passwordless-oauth), one thing I've discovered is that the tenant ID must be provided:

```php
$this->client
    // note: Without the next line, repeated calls after the first will fail.
    ->withTenantId($fusionAuthTenantId)
    ->startPasswordlessLogin([
// ...
```

The symptom we observe when the tenant is not provided is that the first call to `startPasswordlessLogin` will succeed, but any subequent ones will fail. There is some way where if I restart my local development API server, the problem is reset, but I'm still only able to perform one `startPasswordlessLogin`, after which the 404s happen again.

> note: It's been speculated on the FusionAuth slack that this may be happening as a result of us using multiple tenants in our project?

**Comment by robotdan** [comment]
When more than one tenant exists, the `tenantId` is optional on this request in theory because we can resolve the tenant by `applicationId`. 

The fix will allow the `tenantId` to be optional as was the intention.
