### ISSUE TITLE
More email templates per application

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#834]
### Problem
The following workflows aren't application specific, and may occur outside of an application (with the exception of passwordless). However in a white label scenario, it may be helpful to customize these templates per application. 

* Passwordles login
* Email verification
* Setup password
* Forgot password

### Solution
Allow these templates to optionally be configured at the application level so a more customized user experience can be delivered. 

1. Passwordless login
    - New configuration per application to specify a more specific template. 
2. Email verification
    - New configuration per application to specify a more specific template. 
    - If you create a user + registration this template will be used. (Combo Registration API)
    - If you create a user w/out a registration, the tenant specified template will be used. (User API)
3. Setup password
    - New configuration per application to specify a more specific template. 
    - If you create a user + registration this template will be used.  (Combo Registration API)
    - If you create a user w/out a registration, the tenant specified template will be used. (User API)
4. Forgot password
    - New configuration per application to specify a more specific template. 
    - If this workflow is initiated from our login pages, the application specific template will be used. 
    - If initiated from the API with a new `applicationId` parameter, the application specific template will be used.  

### Alternatives/workarounds
Use template variables to use a single template defined at the Tenant level but provide customizations within the template itself. 

### Duplicated or Related
https://github.com/FusionAuth/fusionauth-issues/issues/768

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
I may have duplicated https://github.com/FusionAuth/fusionauth-issues/issues/768

**Comment by TanguyGiton** [comment]
Hello, 

I don't see the new `applicationId` parameter in the Forgot Password API documentation. Is it set up?

**Comment by mooreds** [comment]
@TanguyGiton github issues is best for bug reports and feature requests. General questions or support queries are better posted to the forum: https://fusionauth.io/community/forum/
