### ISSUE TITLE
Facebook login doesnt request for first name and last name of the user.

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#837]
## 

### Description 
when we do facebook login with the fields as email and permissions as email,public_profile,  fusionauth is not requesting for user's first name and last_name from facebook.

### Affects versions
all

### Steps to reproduce
1. Create the facebook identity provider with fields as email and permissions as email, public_profile
2. pass the token obtained from facebook
3. fusionauth doesnt have any first name and last name created  for the facebook user

### Expected behavior
First name and last name from facebook should be stored

### Platform
(Please complete the following information)
fusionauth 1.18.3
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

**Comment by robotdan** [comment]
This configuration should be available to you already using the IdP configuration. 
https://fusionauth.io/docs/v1/tech/identity-providers/facebook#create-a-facebook-identity-provider

Using the `fields` and `permissions` values, can you get the user's first and last name?

**Comment by LohithBlaze** [comment]
thank you,  didnt know we can set them.
