### ISSUE TITLE
Only allow login with a verified email address

### ISSUE THREAD

**Issue by sigalor** [FusionAuth/fusionauth-issues#844]
### Problem
I general, I want users to verify their email address before they can login at all, because storing sensitive data with unverified accounts is a major security risk (also see [this](https://krebsonsecurity.com/2020/09/the-joys-of-owning-an-og-email-account/) article just recently featured on Hacker News).

### Solution
As I currently see it, the solution should consider the following points:

- Add an option to the FusionAuth UI to turn this capability on and off.
- If a user with an unverified email address tries to log in, an "email not verified" error should be shown.
- After a new user has been registered via the `/oauth2/register` endpoint (i.e. self-service registration), it should not redirect via HTTP 302 to the return_uri, but to the login page, possibly with a note like "Registration successful. Please verify your email before logging in."
- The link the user needs to click in the "Email verification" email template should not only contain the tenantId, but also the client_id and the original return_uri (and possible more parameters?). These are needed in order to be able to add a functional, convenient "Go to login" link to the "Email verification complete" theme page.

### Alternatives/workarounds
As long as I have not completely overlooked something in the FusionAuth UI, I don't really see any workarounds right now that would work directly on the FusionAuth level. Of course it would be possible for any application that uses the FusionAuth login to repeatedly check if the user's email address has been verified using the FusionAuth API before the user is allowed to continue at all, but I'd say that this is really not something that should be done by such applications.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
The current intended solution to this is to restrict login or other privileges in your application by examining the user claims returned in the token by FusionAuth. 

The JWT will contain the `email_verified` claim which can be used to identify this state. 
https://fusionauth.io/docs/v1/tech/oauth/tokens

**Comment by robotdan** [comment]
Will email verification gating satisfy this requirement? Email verification gating was delivered in 1.27.0 under GH issue https://github.com/FusionAuth/fusionauth-issues/issues/1191.

**Comment by andrewpai** [comment]
Closing this, as it was addressed with email verification gating in 1.27.0.
