### ISSUE TITLE
SAML POST bindings

### ISSUE THREAD

**Issue by bradleykite** [FusionAuth/fusionauth-issues#845]
### Description 
I have a SAML Application which unfortunatley only supports SAML POST bindings (not REDIRECT / GET Bindings). We require the ability to integrate this application with FusionAuth.

### Affects versions
All, FusionAuth has never supported POST bindings for the Authentication request from the SAML SP. 

### Solution Description

- Add support for POST bindings to SAML v2 Login endpoint
- Add support for POST bindings to SAML v2 Logout endpoint
- Add options to the SAML IdP configuration to select allowed bindings
  - HTTP Redirect 
  - HTTP POST
  - API and UI updates
- Update IdP Metadata to describe additional binding support

### Steps to reproduce
Details are available at this forum post:

https://fusionauth.io/community/forum/topic/336/saml-v2-post-method

### Additional Context
> Section 3.4 HTTP Redirect Binding
> https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf

> Section 3.5 HTTP POST Binding
> https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf

### Expected behavior
SAML POST bindings should be supported for applications that require them.

**Comment by robotdan** [comment]
Thanks for the issue @bradleykite . Are you using a particular SAML library with your integration, a third party app, or a home grown application?

**Comment by bradleykite** [comment]
It's a 3rd party app. Unfortunately we have no control over the app, it
only supports POST bindings.

Regards
--
Brad

**Comment by robotdan** [comment]
Ok, thanks for the update @bguyza , good to know.

**Comment by pigletto** [comment]
I have the same issue when trying to integrate FusionAuth with the TargetProcess: https://www.targetprocess.com/

**Comment by cfogg-axcient** [comment]
Excited to see this being worked on.  We are running into the same issue with 4 different 3rd party products.  Should be able to move forward with switching over to fusionauth entirely once this comes out.

**Comment by robotdan** [comment]
Should be out shortly. 

We'll be adding support for POST bindings and optionally requiring the SP to sign requests (redirect or post).

We are also adding support for POST bindings for SAML and OIDC when FusionAuth is the SP by adding additional config options in the IdP configurations.

**Comment by robotdan** [comment]
Available in 1.20.0. 

@bradleykite @pigletto @cfogg-axcient let us know if you find any SP that is not working with this version.

Thanks!

**Comment by bradleykite** [comment]
Thank you, we will hopefully be able to test later this week.

Regards
--
Brad

**Comment by atabakhafeez** [comment]
Hi, we are trying to use the AuthnRequests signed using redirect but facing an issue with XML metadata files returned by FusionAuth which is sent forward to IdP. We are currently using the version 1.22.1.

As per my understanding, the XML provided by the "Metadata URL" should contain the X.509 signature, and AuthnRequestsSigned should be set to "true".

Below is a snippet from the XML metadata when "Sign Requests" is set to true.

```xml
<ns2:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
```

Would be great if we can get some input on this! Thanks.

**Comment by robotdan** [comment]
@atabakhafeez See https://github.com/FusionAuth/fusionauth-issues/issues/1067
