### ISSUE TITLE
Draft "The Definitive Guide to OAuth version 2.0"?

### ISSUE THREAD

**Issue by JuliusPC** [FusionAuth/fusionauth-issues#854]
### Description
The expert advice article [The Definitive Guide to OAuth version 2.0](https://fusionauth.io/learn/expert-advice/oauth/definitive-guide-to-oauth-2) seems to be some kind of draft as it includes comments...

![grafik](https://user-images.githubusercontent.com/15018932/92391325-ba961e00-f11c-11ea-9ae6-e434a2aebb56.png)

**Comment by robotdan** [comment]
Thanks @JuliusPC . We'll take a look, perhaps this accidentally was moved out of `_drafts`. 

@mooreds can you take a look at this, is this supposed to be a draft yet, or did we just leave a few review comments in by accident?

**Comment by mooreds** [comment]
This is a WIP. @voidmain is going to take another crack at it sometime soon. @JuliusPC we'd love your feedback!

**Comment by robotdan** [comment]
@mooreds If this is WIP, should probably move it back to the `_drafts` folder so it is not live on the blog?

**Comment by voidmain** [comment]
It's in expert advice (not a blog post) and not public or linked to yet. I'll be working on this sucker later this week and next after my `Silent Mode` guide is written. :)

**Comment by JuliusPC** [comment]
@voidmain 

> It's in expert advice (not a blog post) and not public or linked to yet.

I found the article by doing a google search which included the term "fusionauth". So google somehow gained knowledge of this page...

**Comment by voidmain** [comment]
Interesting. I've moved it to a branch for now so that Google can't find it until it is ready. Thanks @JuliusPC for the heads up.

**Comment by mooreds** [comment]
This is now published here: https://fusionauth.io/learn/expert-advice/oauth/modern-guide-to-oauth/

Closing.
