### ISSUE TITLE
ActiveDirectory OpenID Connect docs need to be updated

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#855]
### Description

https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/azure-ad has a note specifying that "FusionAuth’s OpenID Connect flow currently only supports Azure Active Directory v1.0." because of https://github.com/MicrosoftDocs/azure-docs/issues/28317

As of Aug 3, https://github.com/MicrosoftDocs/azure-docs/issues/28317 is fixed.

We should test Azure Active Directory 2.0 and update the docs if it works.

**Comment by robotdan** [comment]
Is this the same issue? If so, we can leave both open, but just so we close them both out together. 
https://github.com/FusionAuth/fusionauth-site/issues/156

**Comment by mooreds** [comment]
It is the same issue, thanks.

**Comment by mooreds** [comment]
Fixed in https://github.com/FusionAuth/fusionauth-site/pull/325

**Comment by mooreds** [comment]
Fixed in https://github.com/FusionAuth/fusionauth-site/pull/325
