### ISSUE TITLE
FusionAuth client for C# .net core

### ISSUE THREAD

**Issue by sjswami** [FusionAuth/fusionauth-issues#86]
### Problem
We are developing .net core application. And it would be great if you have client library for .net core

Currently, the C# client targets the .Net framework and is not compatible with .Net core. 

### Solution
A library for .net core

Need to build `Inversoft.Restify` (REST Client), and the test and prod projects for the C# client targeting .Net core. 

For example, adding this to the `.csproj` file :

```
<TargetFramework>netcoreapp2.1</TargetFramework>
```

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @sjswami. We do have a C# client, will this one work for you?  

https://fusionauth.io/docs/v1/tech/client-libraries/csharp
https://github.com/FusionAuth/fusionauth-csharp-client
https://www.nuget.org/packages/FusionAuth.Client/

If this will not work, can you add some details to the `Solution` section to specify what we could add or what .net version we would need to target to make it work for you? 

Thanks!

**Comment by sjswami** [comment]
Thanks, @robotdan for suggesting an option. I have tried that but the client library is dependent on .net framework so it won't work.

From the source code, I tried to port to .net core framework but one library Inversoft.Restify that is not supporting .net core so porting failed.

**Comment by robotdan** [comment]
So the C# client library can be ported, but the `Inversoft.Restify` cannot? I could release an upgrade to `Inversoft.Restify` that targets a different version if that would be helpful.

**Comment by sjswami** [comment]
We need the change the restful service call api itself to native or some third party like Restify which support .net core. Upgrading version will also not help.

**Comment by robotdan** [comment]
Ok, thanks for that info @sjswami , I'll look into this a bit further. Perhaps we can just change the build target and tweak a few things to make the library .Net core compatible. 

More to come...

**Comment by robotdan** [comment]
I think this is coded, waiting release and testing. It is currently on a branch, but we'll be separating it out into a separate project. 

https://github.com/FusionAuth/fusionauth-csharp-client/tree/ClientLibsWithDomain

@tyduptyler13 can you update this issue once we've published the .NET core version in a new repo?

**Comment by robotdan** [comment]
Beginning with version 1.7.2, the FusionAuth client will be using .NET Core
https://www.nuget.org/packages/FusionAuth.Client
