### ISSUE TITLE
Docs: Wrong explanation of OAuth Implicit grant

### ISSUE THREAD

**Issue by JuliusPC** [FusionAuth/fusionauth-issues#860]
### Description
The definition of the Implicit Grant provided in [OpenID Connect & OAuth 2.0 (Subheading "Example Implicit Grant")](https://fusionauth.io/docs/v1/tech/oauth/#example-implicit-grant) does not at all correspond to [RFC 6749, Section 4.2](https://tools.ietf.org/html/rfc6749#section-4.2).  
(Or it is at least very misleading: The client doesn't need to know the user's credentials. The access token is handed over to the client via redirect, not a direct response to a client's request to the token endpoint.)

**Comment by mooreds** [comment]
Hiya,

I agree it could be made clearer in the FusionAuth documentation that the client can send the user to the authorization server, where the username/password would be entered, and then the token would be sent back.

**Comment by robotdan** [comment]
Thanks @JuliusPC maybe some copy paste issues. We'll correct this shortly.

**Comment by mooreds** [comment]
This doc fix has been deployed. Thanks again @JuliusPC  for reporting.
