### ISSUE TITLE
When fusionauth reactor deactivated, can still register using advanced form, but no data collected

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#861]
### Description 

If you deactivate fusionauth reactor, any applications configured with an existing advanced registration form will still present it to registering users. The user will still be registered in the application correctly, but none of the custom field data will be stored.

### Affects versions
1.18.7

### Steps to reproduce
1. Create an advanced registration form with a custom field being saved on the registration data
1. Associate it with an application.
1. Deactivate reactor
1. Register a new user
1. View user's user data

You see nothing was saved.

### Expected behavior

I'd expect to see an error message if users tried to register with an advanced registration form which would no longer collect the required info.

**Comment by robotdan** [comment]
The current thought is that we fix this so it continues to work, and then add some warnings about the feature being in use w/out a license.

**Comment by mooreds** [comment]
Sure. If possible, I might give people a time window beyond which it will cease to work and a downgrade path.

**Comment by robotdan** [comment]
For now, giving the customer the benefit of the doubt. You will not be able to modify the form, or modify the application, but the end user portion of the workflow will not be interrupted. 

We could think about adding a service that performs periodic auditing of features that require a license and starting sending emails and then add a grace period after which we shut down the features.

**Comment by mooreds** [comment]
Always a good idea to give the customer the benefit of the doubt!
