### ISSUE TITLE
Dropdown values not validated on serverside with advanced registration forms

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#863]
### Description 

If you have a dropdown in an advanced registration form, the value is not checked to be one of the allowed values on the server.

### Affects versions
1.19.4

### Steps to reproduce

1.    Create an advanced registration form with a custom field being saved on the registration data. Make sure one of the custom fields is a dropdown.
1.    Associate it with an application.
1.    Register a new user
1.    Edit the dropdown value (I used 'inspect element' and changed it to a non valid value) before submitting the step where the dropdown is submitted
1. Complete registration.
1.    View user's user data

### Expected behavior

The value of the dropdown submission would be validated server side and would display an 'invalid' error.

### Additional context

I see the same issue with radio buttons.

**Comment by iveelsm** [comment]
I am unable to reproduce this with an `Admin Registration Form` using the following steps:

1. Create new Form Field with `Select` Control Type
2. Enter values `foo,bar,baz` (separated by new lines)
3. Create a new Form of `Admin Registration` type
4. Add the new test field
5. Associate the form with the admin registration process on an application
6. Create a new user
7. Add user registration for application
8. Edit values in dropdown during registration process
9. Submit a malformed value
10. Check user registration data

**Comment by robotdan** [comment]
I think this is the one we discussed, and you were able to recreate? I could not find the commit for this one, can you link it here when you get a chance? Thanks.

**Comment by iveelsm** [comment]
This ended up being a quick fix (although the test is likely going to be pretty complicated). Here it is: https://github.com/FusionAuth/fusionauth-app/commit/64950865f4e136671ad9a235463b7bc9eca728b6

**Comment by robotdan** [comment]
I re-worked this a bit to get tests passing. 
https://github.com/FusionAuth/fusionauth-app/commit/a34bdda1725eac7514f0d65c4be41c1d554a52d5

We can work together on some additional tests for this use case.

**Comment by robotdan** [comment]
Fixed up the test, and fixed some of the business logic, we can review tomorrow. 
https://github.com/FusionAuth/fusionauth-app/commit/b250bffce945a67019885dcf8e4947499e376123
