### ISSUE TITLE
Consider moving from Tomcat to Jetty

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#864]
### Description
We could consider moving from Tomcat to Jetty so we can control the entire startup process and not have to manage `server.xml`, and bootstrap using `setenv`. 

This may allow for a smaller package, and for FusionAuth to run Jetty embedded instead of our app running in Tomcat. 

There is not much of a end user benefit here, however it may allow FusionAuth to expose more configuration that is currently tied up in `server.xml` etc and expose it more easily through APIs or configuration. 

Example:
https://www.eclipse.org/jetty/documentation/current/embedding-jetty.html#_embedding_web_applications

**Comment by andrewpai** [comment]
@robotdan can I close this?

**Comment by andrewpai** [comment]
Closing this, as FusionAuth was moved off of Tomcat in version 1.37.0.
