### ISSUE TITLE
Can't remove one field and add another in advanced registration forms

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#866]
### Description 

If you remove a field and then add a new one to an existing registration form, you get an error when you try to save.

I only tried with dropdown and radio form fields, fwiw.

### Affects versions

1.19.4

### Steps to reproduce

1. Have an existing form.
1. Edit it.
1. Remove a form field.
1. Add a form field.
1. Try to save

You will end up with an error message (see screenshots)

### Expected behavior

You can save the modified form.

### Screenshots

Form before starting:
<img width="1192" alt="Screen Shot 2020-09-15 at 10 49 14 AM" src="https://user-images.githubusercontent.com/91825/93240703-b338cb00-f741-11ea-9ed5-2c53a57a8148.png">

Removing one form field:
<img width="1192" alt="Screen Shot 2020-09-15 at 10 49 20 AM" src="https://user-images.githubusercontent.com/91825/93240688-ae741700-f741-11ea-9d53-da717fba7c00.png">

Adding another form field:
<img width="1192" alt="Screen Shot 2020-09-15 at 10 49 25 AM" src="https://user-images.githubusercontent.com/91825/93240710-b59b2500-f741-11ea-92de-0c80fccb9a18.png">

Error message when saving:
<img width="1192" alt="Screen Shot 2020-09-15 at 10 49 30 AM" src="https://user-images.githubusercontent.com/91825/93240708-b469f800-f741-11ea-88e6-0c2f697d4b3d.png">

### Platform

Saw this on safari and firefox.

### Additional context

Here's the stacktrace from the logs
[freemarker-log-error.txt](https://github.com/FusionAuth/fusionauth-issues/files/5226533/freemark-log-error.txt)

**Comment by robotdan** [comment]
@iveelsm is this one code complete, or did you have any other outstanding items for this bug? If so, please move it to code complete. thanks!

**Comment by iveelsm** [comment]
@robotdan It was complete. I forgot to move it. :)
