### ISSUE TITLE
Can add an empty radio button form field

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#867]
### Description 

Can add an empty radio button form field, even though that doesn't make sense.

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Steps to reproduce
1. Create a new form element
1. Choose it as a radio control
1. Save the element

You are allowed to save this. When you add it to a form, it's invisible, except for spacing.

### Expected behavior

A radio button element with zero options is not valid and should never be created.

### Platform
n/a

### Additional context

Discovered it from while seeing this bug: https://github.com/FusionAuth/fusionauth-issues/issues/865

**Comment by robotdan** [comment]
@iveelsm I don't see any commits for this one, is this fixed under another issue?

**Comment by iveelsm** [comment]
@robotdan I unfortunately didn't link the commits. Here are the SHAs associated with this one:

*  c7bbf32f6aa3a164ee6a4e48273428a82ce0efdc
* 720adb8c2500d811d057c7523eaf1278e436e3a4
* a24b0441fae0846788d88ef852711cb5623279de
