### ISSUE TITLE
POST Request to /api/identity-provider/login failed from browser with [missing]identityProviderId Error

### ISSUE THREAD

**Issue by ShehabSN** [FusionAuth/fusionauth-issues#875]
### Description
So I was implementing a custom google login flow following along with the Docs (https://fusionauth.io/docs/v1/tech/apis/identity-providers/google). So my client app has a google auth button and it basically triggers the pop up and the user signs up/logs in. This is not related to FusionAuth yet until I send the id_token from that successful login , which I successfully received and logged, to the /api/identity-provider/login endpoint as stated in the docs. In my POST request, I include all the required information including the id_token, applicationId, and the identityProviderId for Google straight from the docs and my provider instance in my FusionAuth dashboard as you can see below.
```
fetch("http://localhost:9011/api/identity-provider/login", {
  method: "POST",
  body: JSON.stringify({
    data: {
      token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    },
    identityProviderId: "82339786-3dff-42a6-aac6-1f1ceecb6c46",
    applicationId: "XXXXXXXXXXXXXXXX",
  }),
})
  .then((res) => res.json())
  .then((result) => console.log(result))
  .catch((err) => {
    console.log(err);
  });

```
For some reason when I run this from my browser which is CORS enabled and my Fusion Auth application also has Google Provider enabled I get the below error. I have no idea what the actual problem is since I clearly have the identityProviderId listed exactly as how it was stated in the docs. If i remove all the other information from the request I still get the same error. What is very weird is that when I make this exact same request from Postman desktop, it works perfectly and I get back the expected response. What could be the problem here, and why am I getting such an unrelated error which makes it virtually impossible to debug?
```
{
	"fieldErrors": {
		"identityProviderId": [
			{
				"code": "[missing]identityProviderId",
				"message": "You must specify the [identityProviderId] property."
			}
		]
	}
}
```

**Comment by robotdan** [comment]
You can try adding `mode: 'no-cors'` to your request to see if that changes your result. 

If that doesn't help, you can generate a HAR file of the request, this will likely tell you what is happening. 
https://www.medianova.com/en-blog/2019/07/15/a-step-by-step-guide-to-generating-a-har-file

You can also make sure you have allowed your request origin in the FusionAuth CORS configuration if you have not yet done so. https://fusionauth.io/docs/v1/tech/reference/cors

**Comment by ShehabSN** [comment]
I tried adding the `mode: 'no-cors` to the request and I got the same result. 

I checked the HAR file it, unfortunately, doesn't show me anything new, the same 400 Code and same missing identityproviderid error.

I had the wildcard * set for allowed origins from the cors configuration in fusion auth and it still wont work. I even tried just writing the frontend url instead of the wildcard and still no luck. Am i missing any request headers enabled or something? The allowed request headers are the same as default. Not sure what is going on and I have no clue how to debug, seems like a bug since the error message is completely unrelated.

**Comment by abdullah-K** [comment]
I am facing the same issue. Trying to issue a POST to the `/api/identity-provider/login` after successfully signing in with Google. My request includes the required parameters as defined in : [https://fusionauth.io/docs/v1/tech/apis/identity-providers/google#complete-the-google-login](https://fusionauth.io/docs/v1/tech/apis/identity-providers/google#complete-the-google-login) but the response is still a 400 Bad Request with the same error as @ShehabSN.

**Comment by robotdan** [comment]
@ShehabSN can you post your HAR file?

**Comment by ShehabSN** [comment]
> @ShehabSN can you post your HAR file?

I can email you a redacted one

**Comment by robotdan** [comment]
Sent you a LinkedIn message w/ my email.

**Comment by robotdan** [comment]
I looked your HAR file, the `Content-Type` HTTP header on the POST request is `text/plain;charset=utf-8` instead of `application/json`.  Try adding this header explicitly to your request.

**Comment by ShehabSN** [comment]
Added that as a header and it works now, thanks!

**Comment by mooreds** [comment]
https://fusionauth.io/community/forum/topic/407/missing-identityproviderid-error
