### ISSUE TITLE
Forward email or username to identity providers with query parameter (login_hint)

### ISSUE THREAD

**Issue by Jank1310** [FusionAuth/fusionauth-issues#876]
### Problem
We want to prefill the email field of identity providers like okta or office so that our users don't have to type their email address again. Current flow: App Login Page with username/email -> FusionAuth -> Input email again at the idp.

### Solution
New flow: App Login Page with username/email -> Redirect to FusionAuth (use hint or input email) -> Redirect to idp with `&login_hint=user@acme.com` appended to the oauth url

The query parameter name should be configurable to support different identity providers. Default could be "login_hint".

**Comment by robotdan** [comment]
This is available in version 1.19.0.
https://github.com/FusionAuth/fusionauth-issues/issues/178

**Comment by Jank1310** [comment]
Yes, you can pass the login_hint/idp_hint to FusionAuth. But FusionAuth won't pass a login_hint parameter to e.g. google or office (https://docs.microsoft.com/de-de/azure/active-directory/develop/v2-protocols-oidc#send-the-sign-in-request) to pre-fill the email input field.

**Comment by robotdan** [comment]
Hmm.. we should. 

If the IdP type is SAML v2 or OpenID Connect, and you provide a `login_hint` on the FusionAuth URL we should be passing it along on the redirect. 

Can you provide an example config, and the actual redirect you see in the network requests in your browser dev tools?

**Comment by Jank1310** [comment]
You're right. FusionAuth appends login_hint correctly to the redirects. I've only tested it with a SAML App added to GSuite and it seems that the "error" is on the google saml side and not related to FusionAuth.
