### ISSUE TITLE
Add a remember me checkbox on the hosted login pages

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#878]
### Problem

Sometimes you may want a session to last beyond when the browser closes. Right now there's no easy way to do that.

### Solution

An option in the login configuration (maybe on the application -> security tab) which if checked, would render a checkbox on the login pages. You'd probably need to add a 'remember me session duration' setting as well. If a user logging in were to check the checkbox, their session would be persisted for the 'remember me session duration'.

### Alternatives/workarounds

I outlined one workaround here: https://fusionauth.io/community/forum/topic/392/does-fusionauth-support-a-remember-me-functionality/4

### Additional context

See forum post that raised this feature possibility: https://fusionauth.io/community/forum/topic/392/does-fusionauth-support-a-remember-me-functionality 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Is this just SSO?

**Comment by mooreds** [comment]
Does SSO work if you close the browser? Is it a session cookie or a persistent cookie?

**Comment by robotdan** [comment]
We write the SSO cookie as an HTTP Only Secure Persistent cookie. It should survive a browser / tab close.

**Comment by mooreds** [comment]
Ah, then, is there a way to turn SSO on or off at the user level? (So the use can choose to have their session remembered, if they are on their private machine, or not, if they are at the library.)

That may be the root issue: the ability to change if a persistent cookie is dropped on a login by login basis, not across an application or tenant.

**Comment by robotdan** [comment]
No, not really. You could "hack it" and set the SSO TTL to 1 second. This would effectively turn it off for everyone. 

The feature we don't have is a checkbox that says "this is a public / shared computer" - which should then not drop an SSO cookie. But I think that is the opposite of this feature request. From how I read this request, this is what SSO does - so perhaps we are missing a feature request for "do not remember me" because I'm on a shared computer.

**Comment by mooreds** [comment]
I may have been imprecise in my bug filing, but it seems like the SSO settings (under the OAuth tab in the Tenant setting) is equivalent to 'Remember me' for everyone. Which is useful, but a bit different than the typical 'Remember me' checkbox in on a login page, which lets people choose either way, again on a per login basis.

I agree you could think of this as a "do not remember me" button, but I wouldn't implement it that way, just because very few applications, if any, do so (I can't think of any). Instead, I'd let people turn SSO off at the tenant level and then let people enable 'remember me' functionality at the application level. But that wouldn't drop a persistent cookie, it'd instead let a user choose whether to do so.

**Comment by robotdan** [comment]
Ok, got it. I think I understand what you mean. 

The way I understood the question posted in https://fusionauth.io/community/forum/topic/392/does-fusionauth-support-a-remember-me-functionality/4 is what SSO offers today. 

But to describe this feature request in the context of the current behavior, it would be a checkbox that is checked by default which says "remember this computer". And this "checked" behavior would be the current SSO capability - which means we would drop a persistent cookie. 

If the user then would un-check this box, we would not drop a cookie - which essentially turns off SSO for this login request. The user would then still be redirected back to their app to complete login, but the next request to the login page would require them to enter their credentials.

**Comment by mooreds** [comment]
> The way I understood the question posted in https://fusionauth.io/community/forum/topic/392/does-fusionauth-support-a-remember-me-functionality/4 is what SSO offers today.

You are correct. I didn't realize that SSO solves this problem for all users when configured correctly at the tenant level.

> If the user then would un-check this box, we would not drop a cookie - which essentially turns off SSO for this login request. The user would then still be redirected back to their app to complete login, but the next request to the login page would require them to enter their credentials.

I would say that you'd drop a session cookie if the box is unchecked. That means that if they visit the login page within the same browser session, they'd still be logged in. But if they close the browser, they'd be 'logged out' because the session cookie would be deleted.

**Comment by nerfpops** [comment]
This is an essential feature. I don't know of any sites that doesn't allow some sort of remember me functionality, and I'm surprised it's not ootb in FusionAuth. Microsoft, Facebook, Twitter, Google - they all have ways to help users login without their password all the time. I will look like a fool to my boss when he asks for a remember me checkbox, and I say it's not something provided by our super expensive IAM software. Please don't put me in this situation!

**Comment by robotdan** [comment]
@nerfpops 

Can you add some clarity to the use case you are looking for? 

Today we support the following:

1. Configure an SSO TTL, this keeps you logged into to SSO for the configured amount of time. No user interaction required with a checkbox or anything like that, it just works based upon the configuration. 
2. If MFA is enabled, you can "remember this computer" and not be prompted for MFA for the configured life of the Trust MFA token. 


A couple of options we plan to support:

1. Checkbox that says "this is a public computer" or "this is a shared computer". I think this would mean, don't drop an SSO cookie. 
2. Remember this computer. This would functionally allow you to remain logged into SSO beyond a configured SSO TTL. 
   - This still needs to be revokable
   - Ideally still has a TTL, even if it is quite long by default, months or years perhaps?
   
Are you looking for option 1 or 2 in the second list?

**Comment by nerfpops** [comment]
Option 2 is great. It resembles a kind of 'secure by default', in other words, users actively choose to remove one layer of security for convenience, and those who prefer MFA may postpone the need for entering a password on their primary machine.

**Comment by robotdan** [comment]
We can do some additional research, I don't know if anyone out there is doing option 2 - where there is an SSO configured, and the "remember me" allows you to prolong your SSO for either a separately configured TTL or an indefinite time. 

Some of the implementations out there simply allow you to check the box to "remember me" which allows the SSO to function. Without selecting "remember me" the user is simply not given an SSO session. This is mostly option 1 in reverse. 


If you have a particular implementation (vendor) in mind, we can do some testing to see if they are using option 1, 2 or something else.

**Comment by nerfpops** [comment]
Microsoft does it pretty well. They've changed the remember me checkbox to a step in the login flow, asking if you want to stay signed in. I hadn't put much thought into MFA, but I think that's the reason it's not a checkbox - the remember me step is always last, after the password, or after password+mfa if it's activated. But I see that this issue is not as simple as one would think!

**Comment by robotdan** [comment]
Thanks for those details @nerfpops  - appreciate it. We can take a look at how Microsoft is doing it and see if that can give us any additional insight into how we could add additional configuration around opting out of SSO, or possibly an additional token that allows for prolonged sessions.

**Comment by bostjan** [comment]
@robotdan, Okta has a different implementation behind their `Remember me` checkbox - it simply remembers the username that was last used (by that browser, on that tenant subdomain).

Personally, I think their implementation strikes a good balance between corporate security requirements (forced SSO session timeout in ~30-120 minutes or so) and convenience - the idea being that when the session timeout kicks in, I get redirected to the SSO login page automatically (by the app), and on the SSO login page, the username is already filled in.

(Granted, I would not mind if they went all the way and made that remembered username be auto-accepted and just prompt me for my password, with the password input field already in focus, but hey - we can't have our users _that_ "convenienced" by stuff! :) )

Just FYI.

PS: Is there an existing feature request lurking somewhere around here for what I described above? If so, I apologize in advance.

**Comment by robotdan** [comment]
This was delivered in `1.30.0`.
