### ISSUE TITLE
Need browser TZ passed to passwordless login

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#886]
### Problem
In an effort to provide a useful email subject on the passwordless email containing the expiring magic link, and to improve the email visibility in mail clients like gmail, we'd like to put actual local expiration time on the email subject as discussed in #735 . 

The user record has an optional timezone field that is very often blank so can't be relied on. Additionally this value tends to be static and doesn't necessarily represent the local TZ during login (vs TZ at time of registration).

### Solution
When user submits email address to the FusionAuth passwordless / magic link request screen - pass the browser TZ to the passwordless call so that it will be available to the email template.

### Alternatives/workarounds
The workaround isn't very friendly - hard code the TZ used in the template expiration time and show the user what timezone we are utilising. 

### Additional context
https://fusionauth.io/community/forum/topic/220/can-i-customize-the-passwordless-link-email-subject-with-the-time-the-link-expires/4

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This should be available in the template if you started from a normal login and clicked password less. 

In the template, it should be `state.timezone`.

**Comment by andrewpai** [comment]
Closing this issue, as browser timezone is available to email templates as noted in an earlier comment.
