### ISSUE TITLE
Automating the API Key creation

### ISSUE THREAD

**Issue by Tintwo** [FusionAuth/fusionauth-issues#887]
### Problem
We use the API to automate configurations in FusionAuth (actual running production environment). But, according to the api documentation, there is no way to create scoped api keys. So, a part of automation is not possible to do, we have to do manually with the UI.

### Solution
An available route on the API to be able to create tenant scoped api keys (eg. `POST /api/apikey`)

### Alternatives/workarounds
- Use the [UI to create an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#manage-api-keys) 
- Use [Kickstart](https://fusionauth.io/docs/v1/tech/installation-guide/kickstart) to seed one to many API keys that can then be used to programmatically bootstrap the system. 

### Additional context
Similar to #819 

Don't forget to update the limitations doc when this is complete: https://fusionauth.io/docs/v1/tech/reference/limitations/#api-keys 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by jeff-jk** [comment]
Please implement this feature, it is crucial for automated environment setup and testing.

**Comment by voidmain** [comment]
Originally, we discussed this at length and decided that the threat surface for allowing an API to create API Keys was too significant to justify.

However, after giving this some thought, here is what I propose: **We allow an API key can create another API key with the same or less access.**

Here are a few examples:

`API key #1 {all permissions}` - can create a new `{all permission}` key
`API key #2 {POST /api/user only}` - can create a new `{POST /api/user}` key only

This seems to be a viable solution that will not introduce any significant additional threat vectors. The justification is that if an attacker has already stolen a key, they cannot create an `{all permissions}` key. They can only create a new key that has the same permissions as the key they stole. Therefore, it does not make sense for them to create this new key.

The only remaining threat for this solution is that the attacker could create thousands of keys making it challenging to clean them up, even if an admin notices that a key has been stolen. To mitigate this situation, we could implement a `DELETE all keys` feature in the UI only that allows a super admin to completely lock a running instance of FusionAuth.

Everyone that is following this issue, I'd love to hear your thoughts on this solution.

**Comment by jeff-jk** [comment]
Thank you for the quick response @voidmain, appreciate you and happy Friday!! I’ll muse over your thoughts and respond more completely after the weekend but I wanted to get my initial thoughts out there.

From a cursory glance at your proposal, these concerns make a lot of sense from a security perspective. The attack surface is not expanded with your proposal and I like it a lot rather than blocking this functionality entirely. I really like the idea of being to delete all keys from operations and security perspectives if the ability for keys of same or lesser permissions to be created. 

I do understand & respect that security for authentication should come before ease of development and operations.

However, I think this still leaves something to be desired from a development and operations perspective from automation and configuration management perspectives. 

With fusion auth application’s attack surface mind, is there potentially a way we could create API keys and insert into the database externally or at install time as a “seed”? Then configure the fusion auth application as code from there? Could database imports or migrations be leveraged to mitigate security concerns since compromised database access is effectively out of scope of the fusion auth application? I know this feels gross but if external development may solve issues with automation this would share responsibility. 

I’ll reconsider Monday but these are my initial thoughts without deeper context and research.

**Comment by robotdan** [comment]
I updated the work around section in the description as well in case these options were not clear to all. 

@jeff-jk in case you are not aware, you can use [kickstart](https://fusionauth.io/docs/v1/tech/installation-guide/kickstart) to seed the system with one or more API keys during the initial setup. This option will work for an initial deployment of FusionAuth, but will not help you if you have existing running instances. 

It is also worth bringing JWTs into this discussion. (see https://github.com/FusionAuth/fusionauth-issues/issues/528) 

Once we support this - perhaps this issue becomes moot - at least for some use cases. 

Once a JWT is accepted for all APIs, then the API key becomes a JWT issued to a user as a result of an authentication to the FusionAuth "app".

**Comment by jeff-jk** [comment]
Thank you yes kickstart is used extensively for initial install @voidmain. However, solving for config drift and getting many environments in sync after kickstart, after upgrading fusion auth, etc for existing instances is part of the issue and use case from my end. We need lesser privileged API keys to initialize and automate other things. So if a “super” API key can generate “lesser” API keys that would solve for the additional existing fusion auth instances use case.

**Comment by robotdan** [comment]
To add to @voidmain 's proposal, I think it likely also makes sense to be able to restrict an API key from being used to make other API keys. 

We could do this through the existing configuration by omitting the API endpoint necessary to make API key, however this would mean you'd have to manually select all endpoints except for the API key endpoint. 

If we just add another flag on the key to indicate if it can be used to make other API keys this may allow the end user to easily restrict the proliferation of god keys so to speak. 

This means that an API key can only create a key of equal or lesser capability as @voidmain suggested. **Additionally**, it would need an explicit configuration option to allow the key to "procreate" so to speak. This way not all keys that have access to all APIs can also create an API keys. 

Then the process would look something like this:

1. Create a super key
   - Use Kickstart to create the initial key(s) on a **new** system. 
   - Use the UI to create the initial key(s) on a **new** or **existing** system.
2. Now these super keys can be used to create, modify or delete all other keys.
3. And [there was much rejoicing](https://youtu.be/yciX2meIkXI)

**Comment by voidmain** [comment]
@jeff-jk in terms of config drift and migrating that to new instances, have you taken a look at issue #526? That one might do what you need in terms of extracting a Kickstart file from a current instance of FusionAuth.

**Comment by Tintwo** [comment]
@voidmain I think the solution you propose (https://github.com/FusionAuth/fusionauth-issues/issues/887#issuecomment-710713187) is fine, according to the possible threats.

I have to admit that I can't wait an implementation of this. I'm available to help for testing this feature also ;)

**Comment by robotdan** [comment]
It's happening....

**Comment by robotdan** [comment]
Available in 1.26.0 doc forthcoming

**Comment by mooreds** [comment]
Delivered under 1.26, docs here: https://fusionauth.io/docs/v1/tech/apis/api-keys/

Closing.
