### ISSUE TITLE
[Not An Issue] Bravo

### ISSUE THREAD

**Issue by DarkBlaez** [FusionAuth/fusionauth-issues#889]
This is not an issue, just wanted to state after having reviewed and started to exercise the APIs and FusionAuth platform that you all did a great job in a cohesive package. Very complete, full featured, covers all of the main use cases as well as additional edge case. Feel free to close this, just wanted to send Kudos

DB

**Comment by mooreds** [comment]
Thanks so much for the feedback @DarkBlaez ! We love to hear it!

FYI, if/when you feel comfortable providing a review (you might want to wait until you use it on a project or two), we love to get them on Capterra. Helps provide other people with the information they need to make a decision about FusionAuth.

You can start a review here: https://reviews.capterra.com/new/182987

**Comment by jobannon** [comment]
Closing issue, as it is "resolved" 🙂
