### ISSUE TITLE
The role of username

### ISSUE THREAD

**Issue by fabiosimeoni** [FusionAuth/fusionauth-issues#89]
Hi, 
is there any documentation on the rationale for your choice of user model? In particular, I am wondering what's the role you expect applications to make of the `username`. 

Your logins use `email`, right? And your `JWT`s carry opaque user `id`s. As an identifier, what's the `username` for then? I suspect I might be missing something here.

In my applications, `username` is unique and plays the role of a domain identifier chosen by clients. It'd be great if I could retrieve it from the `userinfo` endpoint and avoid other calls to `api/user`. This would also keep my dance in the scope of `OpenID Connect`, which is a standard.

thanks!

**Comment by robotdan** [comment]
Hi @fabiosimeoni thanks for the question. 

We included `username` to support many legacy products such as forums that rely upon the username as the unique login identifier. 

In general we would recommend you use `email` instead as it is globally unique, and not just unique within a product or identity provider. 

FusionAuth takes a `loginId` parameter which can be `username` or `email`.

In your case if `username` is unique you could add that to the user object and authenticate using this value or the email address. 

We could add it to the claims returned by the UserInfo API, or perhaps add it directly to the access token or id token returned from the completion of the OAuth grant workflow. OpenID does not have a well known claim for username, but it does have `preferred_username` which is probably close enough. 

The current strategy is to keep the tokens a bit lighter if possible and add as many claims as possible to the Userinfo result. Would you have a preference if we added the `preferred_username` claim if it came back in the token, or just from the `Userinfo` endpoint?  We could also just invent our own claim even though it is not directly specified called `username`. 

Let me know if you have any additional thoughts or preferences here. Thanks for the feedback!

**Comment by fabiosimeoni** [comment]
thanks @robotdan,

we're relying on username to let users reconfigure emails if they so desire.

we'd be perfectly happy if you returned it from `userinfo`, which we'd be invoking anyway to validate the `id_token`. Since you classify it as an alternative identifier to email, however, it might make more sense to treat them "equally" in your tokens as you do in your logins ? And if you were to include it in tokens,  any json "key" will do, so please align it to the specs as you suggest. 

And perhaps, to pre-empt further requests based on custom claims, it might be useful to return the "user data" from `userinfo` ? Of course, the ultimate solution would be to let users 'design' tokens and `userinfo` responses on a per-app basis, picking from your user model and/or its extensions. But this might well be overkill to contemplate for your roadmap.

For the time being, we generate our own tokens for consumption upstream, after the auth dance with fusion completes. If one could control the shape of tokens from your UI on a per-app basis, we'd scrape that and push your tokens directly to our services. We wouldn't need this 'transformation layer' because the transformation would be specified directly in your UI. 

thanks a lot, looking forward to this.

**Comment by robotdan** [comment]
Thanks for the additional info and feedback. I think this would be a good addition, so I'll get this into plan to at a minimum return the username on the `Userinfo` endpoint. 

I'll have to think more about the "user data" on the `Userinfo` - that is a good idea. We'll review this to identify if we have any concerns over doing this, or if it would be a configuration option. 

Regarding token design - we do have a feature in plan to allow additional control over how the JWT is built per application. Or current thinking is to provide some simple configuration such as toggles to enable or disable non required claims.  Then to support more advanced or custom configurations, we are designing a system that will allow you to implement a JavaScript method that will be provided the User object and a claim map and allow you to build the map from anything in the User, User data, Registration or Registration data. 

If we don't yet have a feature request open for this I'll open one and describe the proposed solution and you can add any additional details that you would have to ensure we adequately cover your use case so you can potentially yank your additional transformation.

**Comment by robotdan** [comment]
Existing feature for custom claims https://github.com/FusionAuth/fusionauth-issues/issues/61

Feel free to add comments here if you have any specific requirements.

**Comment by robotdan** [comment]
`preferred_username` is now returned if the User has define a username, this is available in version 1.5.0. https://fusionauth.io/docs/v1/tech/release-notes/

We are working on lambda support for the next version of FusionAuth, once this work is complete, we will likely add the ability to utilize a lambda during token creation. Watch #61 for that effort. 

Thanks.

**Comment by fabiosimeoni** [comment]
thank you, that works.

f

**Comment by scopendo** [comment]
I note that preferred username is returned, but if the user has an application-specific username, then this is not returned.

**Comment by robotdan** [comment]
> I note that preferred username is returned, but if the user has an application-specific username, then this is not returned.

You're correct, this is the current designed behavior. 

The `username` field at the top level of the user may be used to authenticate to FusionAuth, the `username` on the User Registration cannot. This was the rationale for the design decision. 

But you point is well taken, perhaps it would be better if we used the application specific `username` (the one found in the User Registration) if available.  I'll review this with the team, if this is a real use case for you, please open a feature request so we can track it. 

Another option will be in version `1.6.0`, you'll be able to assign a Lambda to an application in order to modify or augment claims in the JWT. So you could add a new claim such as `app_preferred_username` with that of the User Registration.

**Comment by scopendo** [comment]
Cheers, it's not a real use case for me, just something that I observed
whilst exploring how FusionAuth works.
