### ISSUE TITLE
Support SessionIndex for in SAMLv2 AuthnStatement

### ISSUE THREAD

**Issue by ruckc** [FusionAuth/fusionauth-issues#896]
### Problem
Artifactory expects (and breaks when not present) SessionIndex to exist on the AuthnStatement element of an AuthnResponse.

### Solution
Fusionauth should provide SessionIndex for logout tracking to SAML Service Providers like Artifactory.

### Alternatives/workarounds
An alternative would be to have Artifactory conditionally support SessionIndex existing, but given [JetBrains added a checkbox](https://youtrack.jetbrains.com/issue/JPS-3658) to their IdP to support this with Artifactory it is unlikely JFrog would implement this in the closed source portion of their software.

### Additional Context
> Section 2.7.2 Element <AuthnStatement>
> https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

> &lt;AuthnContext&gt; [Required]
> The context used by the authenticating authority up to and including the authentication event that
yielded this statement. Contains an authentication context class reference, an authentication context
declaration or declaration reference, or both. See the Authentication Context specification
[SAMLAuthnCxt] for a full description of authentication context information.
> 
> In general, any string value MAY be used as a `SessionIndex` value. However, when privacy is a
consideration, care must be taken to ensure that the `SessionIndex` value does not invalidate other
privacy mechanisms. Accordingly, the value SHOULD NOT be usable to correlate activity by a principal
across different session participants. Two solutions that achieve this goal are provided below and are
RECOMMENDED:
> 
> • Use small positive integers (or reoccurring constants in a list) for the `SessionIndex`. The SAML
authority SHOULD choose the range of values such that the cardinality of any one integer will be
sufficiently high to prevent a particular principal's actions from being correlated across multiple session
participants. The SAML authority SHOULD choose values for `SessionIndex` randomly from within
this range (except when required to ensure unique values for subsequent statements given to the
same session participant but as part of a distinct session).
> • Use the enclosing assertion's `ID` value in the `SessionIndex`
>
> The following schema fragment defines the <AuthnStatement> element and its AuthnStatementType
complex type:
> 
```xml
<element name="AuthnStatement" type="saml:AuthnStatementType"/>
<complexType name="AuthnStatementType">
  <complexContent>
    <extension base="saml:StatementAbstractType">
      <sequence>
        <element ref="saml:SubjectLocality" minOccurs="0"/>
        <element ref="saml:AuthnContext"/>
      </sequence>
      <attribute name="AuthnInstant" type="dateTime" use="required"/>
      <attribute name="SessionIndex" type="string" use="optional"/>
      <attribute name="SessionNotOnOrAfter" type="dateTime" use="optional"/>
    </extension>
  </complexContent>
</complexType>
```

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for opening the issue @ruckc !

**Comment by ruckc** [comment]
For more reading, JFrog "[won't fix](https://www.jfrog.com/jira/browse/RTFACT-14481)" the issue on their side by making SessionIndex optional.

**Comment by robotdan** [comment]
Thanks for the update @ruckc we'll see if we can get this into plan.

**Comment by mooreds** [comment]
Came up in this forum post too: https://fusionauth.io/community/forum/topic/457/how-can-i-add-sessionindex-as-part-of-the-authenstatement-provided-is-there-a-way-to-add-this-using-a-lamba-function

**Comment by robotdan** [comment]
Depending upon how involved this one is, we may be able to fold it into the SAML POST bindings work. 
https://github.com/FusionAuth/fusionauth-issues/issues/845

**Comment by robotdan** [comment]
@ruckc this is available in version 1.20.0, let us know how it goes with JFrog.

**Comment by ruckc** [comment]
@robotdan - confirmed it works perfectly.  I really appreciate it.

**Comment by robotdan** [comment]
Awesome! Thanks for the update!!
