### ISSUE TITLE
HttpOnly cookies not being set on subdomain

### ISSUE THREAD

**Issue by abdullah-K** [FusionAuth/fusionauth-issues#898]
### Description
Our FusionAuth instance is hosted on `auth.example.com` using an Nginx reverse proxy. When we try to send API requests from `development.example.com` to `auth.example.com/api/login`, the HttpOnly cookies are sent back as response cookies (e.g. `Set-Cookie access_token=` headers) but they are not being set on the development subdomain. The `Domain` attribute in the response cookies is set to `auth.example.com` by default, which may be the cause of this issue. Is there a way we can modify this behavior? Perhaps using some Nginx configuration? Is there any configuration available on the FusionAuth dashboard to modify this?

We have tried setting an `add_header Set-Cookie Domain=https://development.example.com` directive in the Nginx server block but this did not solve the issue.

The `development` subdomain is hosted on Netlify whereas the `auth` subdomain is pointed to a DigitalOcean VPS.

**Comment by robotdan** [comment]
This is working as designed. We do not explicitly set the domain in the `Set-Cookie` HTTP response header. This means the cookie will be written for the immediate domain, but not sub-domains. 

If you want to specify a specific domain, or domains for the cookie, you can optionally re-write the cookie using one of the strategies outlined in the authentication flows. 

https://fusionauth.io/learn/expert-advice/authentication/login-authentication-workflows

We could optionally leave this issue open as a feature request to investigate what type of configuration we'd have to expose to allow the cookie to be made accessible to sub-domains.

**Comment by abdullah-K** [comment]
Thanks for the reply, @robotdan 

I looked over the link you sent but I couldn't find an applicable authentication flow that fits our needs; is there a specific one you were thinking of? 
We're using Hasura so we don't technically have a dedicated back-end that we can  modify. 
The ideal way to fix this would be to set the domain explicitly or allow the developer to input a domain in the dashboard. If the domain was set explicitly, Nginx's [proxy_cookie_domain](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_domain) would be able to replace it with any domain. We were successfully able to add a domain to the response cookie using the Nginx [proxy_cookie_path](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path) directive ([using this solution](https://stackoverflow.com/a/44239109/12955797)) and this is the result: 
![COOKIES](https://user-images.githubusercontent.com/21252681/94642165-a15a3a80-02a0-11eb-951d-bf6fcd0e4b11.png)

As you can see, the domain attribute of the cookie was set and all other attributes are correct.  However, the actual cookies are not being stored (they aren't showing up in the browser developer tools). Therefore, the requests to `/api/jwt/refresh` do not succeed. We would like to only use response/request cookies to refresh the tokens without having to provide them in the request body (for persistence and security reasons). 

Do you know why this could possibly be happening? Any help is greatly appreciated!

**Comment by abdullah-K** [comment]
It turns out, setting `withCredentials` to `true` in the request as well as enabling "Allow credentials" on the FusionAuth dashboard solved this problem. 

Now, it works and the `/api/jwt/refresh` API route receives the correct request cookies and sets the correct response cookies. However, we're still confused as to why the cookies aren't showing up in the developer tools for the `development` subdomain (but they are somehow being sent in the request to refresh). Is it because both subdomains share the same "base" domain (even though that qualifies as being a cross-domain request)?

**Comment by robotdan** [comment]
This is just how cookies work. 

For example, the cookie has a domain of `auth.example.com`, and your app has a domain of `development.example.com`. 

When a user-agent (browser, postman, etc) makes a request to `auth.example.com` it will bring along cookies with that domain. 

When a user-agent (browser, postman, etc) makes a request to `development.example.com` it will bring along cookies with that domain. 

So when you view the cookies in the browser dev tools, you will only see cookies for the domain that you're on, if you're on `development.example.com` when you view the cookies, you will not see cookies for `auth.example.com`. 

Then when you make a request to `http://auth.example.com/api/jwt/refresh` the cookies for this domain will be added to the request and they can be utilized by FusionAuth.  In this context, it is not a cross domain request, you are making a request to `auth.example.com` and the corresponding cookies get picked up.

**Comment by abdullah-K** [comment]
Thanks for the explanation @robotdan! You definitely cleared up some of the confusion we had.
This issue can be closed now, at your discretion.
