### ISSUE TITLE
Token from Login API failed in validate API

### ISSUE THREAD

**Issue by SigitArif** [FusionAuth/fusionauth-issues#899]
### Description
Hi,
I'm using fusionauth version 1.7.4. 
I have a problem when I 
1. Login a user using Login API
2. I get the encoded access_token response
3. I try to validate the token in /api/jwt/validate API and it always return 401
4. I try to refresh token using /api/jwt/refresh and try to use the token response in the same API /api/jwt/validate and itu success returning the decoded JWT

Is there any help why it always return 401 when I'm validating token from Login API and why it works well in token from refresh JWT API?

Thanks

**Comment by mooreds** [comment]
Hmmm. Can you share how you are calling `/api/jwt/validate`? The `401` response indicates that the token is not valid, per the docs:https://fusionauth.io/docs/v1/tech/apis/jwt#validate-a-jwt but it'd be helpful to see the exact call you are making.

Also, can you confirm you are using 1.7.4? That's quite an old version of FusionAuth.

**Comment by SigitArif** [comment]
Sorry this is my own developers fault because we override the login manually decode and encode the jwt to add new param. I closed this issu
