### ISSUE TITLE
Api integration modules

### ISSUE THREAD

**Issue by kaigouthro** [FusionAuth/fusionauth-issues#9]
if there was the option alongside every auth, to have a pre-translated and cleaned up and stripped simple API for the app that's being authed... that would be fantastic.

instead of just logging into all the sites easily
also, have for every site .. component... let's call it.
a wrapped package containing all the important API calls from the auth'd service
that we could one-click download similar to an NPM package,
except that it goes with your software, and we could basically have an app store with a list of all the sites that are auth'd, and we click on that site, can read a brief description, and with one click, add the auth, as well as a cleaned up standardized API set to our collection.

I'm sure community members would love that and contribute "modules" that you standardized the format of.... to all their favorite sites .. I know I would pack up and make all the boilerplate API calls entered and translated to shortcode for what I use..   and if you made the packages extendable and adaptable, so that there would be the absolute shortcodes for the absolute APIs at most sites, but also, leave room for co9nsumers to add in their own translations easily for cases of R.A.D. platforms, like Zoho creator, caspio, etc... where there are possibilities ..  

so, have full components for the rigid sites that are going to have the same API calls for 10 years... like Gmail... but also leave the room so people can download components and have them be extensible...

each component being made up of an auth package for the site in one partition of the component, the solidified permanent API translation to fusionspeak, and the freedom to add extra shortcode that would generate the API call for that site based on criteria fed to it (IE: Zoho creator..... need an app name, a form name, a field name, then your generator makes the API call and links it to the shortcode)..

then you'd end up being THE site to go to for developers.. I know this because it's what I'm trying to find... and I've been looking and researching for that simple solution for 2 months now.

1 sign on, all the sites logged in, and all the sites APIs in one standard. open source and community driven..   

give people a free 10 users/year free for each module they build that you approve and add to the system.

you just need to build the modular framework and set the guidelines and build a couple templates, a basic app gallery profile page with a list of what apps are included (community would contribute the documentation of each shortcode)... and bam...we can all integrate sites login as well as their apps with just one module pick from your catalogue, and it goes in our collection to use and share with our tenants based on their access levels... .. throw on a Redis cache for our app to hold the non-sensitive data, use fusion to hold encrypted user data like their names, etc.. and all that fusion does provide  us with the modules, I'm sure we'd pay to rent or buy certain modules, take them and put them on our own self-hosted servers...

there's a lot of fantastic that could come of this.

**Comment by robotdan** [comment]
Thank you for the suggestion and insight @kaigouthro.
