### ISSUE TITLE
Provide additional doc for FusionAuth roles and how they affect the UI

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#90]
## Document FusionAuth roles

The FusionAuth roles affect the actions available to the user when logged into the FusionAuth admin interface. Provide a section in the FusionAuth docs to indicate what actions or privileges each of these roles allow the user. 

Thanks to [Jesper We](https://stackoverflow.com/users/2846463/jesper-we) for the request.

### Description
There may be some confusion as to what the roles do and how they affect FusionAuth admins. 

```
- Global admin (admin)
- API key manager (api_key_manager)
- Application deleter (application_deleter)
- Application manager (application_manager)
- Audit log viewer (audit_log_viewer)
- Email template manager (email_template_manager)
- Group deleter (group_deleter)
- Group manager (group_manager)
- Report viewer (report_viewer)
- System configuration manager (system_manager)
- Tenant deleter (tenant_deleter)
- Tenant manager (tenant_manager)
- User action deleter (user_action_deleter)
- User action manager (user_action_manager)
- User deleter (user_deleter)
- User manager (user_manager)
- Webhook manager (webhook_manager)
```

### Related Information
https://stackoverflow.com/questions/55118726/can-a-user-manager-be-limited-to-manage-only-users-of-certain-groups

**Comment by mooreds** [comment]
I believe this is done: https://fusionauth.io/docs/v1/tech/core-concepts/roles/#fusionauth-application-roles
