### ISSUE TITLE
Email column length too short for standard

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#900]
### Description 

Per https://www.ietf.org/rfc/rfc2821.txt it looks like the maximum length of an email address is 320 characters (64 for the local part, 255 for the domain, 1 for the `@`). Or maybe it is 254, see https://blog.moonmail.io/what-is-the-maximum-length-of-a-valid-email-address-f712c6c4bc93 / https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address for more.

But if you look at the schema files, you can see that the email address (in the `identities` table) is only a `varchar(191)`.

### Affects versions

1.19.8 (but I expect others, since the column length has been the same for 8 months.

### Steps to reproduce

This appeared during an import of a user with a 255 character email address. A 400 error was thrown.

### Expected behavior

Users can have emails up to what the standards allow.

**Comment by mooreds** [comment]
This is not a bug. That column is indexed, and in MySQL when using a utf8mb4 (4 byte character set) on an indexed column, MySQL limits the usable characters to 191 to account for the overhead of the 4 byte addressing.

I believe newer versions of MySQL may support some additional extensions to be able to use 255 for an indexed column when using utf8mb4 but we sort of support the lowest common denominator to support older versions.

**Comment by robotdan** [comment]
If we want to use this issue to validate the length so we can give developers better feedback that would be ok.

**Comment by amans330** [comment]
https://github.com/FusionAuth/fusionauth-api/pull/10
https://github.com/FusionAuth/fusionauth-app/pull/29
