### ISSUE TITLE
Send Test Email timeout modal - no close or cancel button

### ISSUE THREAD

**Issue by corepay** [FusionAuth/fusionauth-issues#901]
### Description 
Sending test email with a gateway timeout shows the timeout page but no way to close the modal

### Affects versions
Fresh Install - docker-compose

### Steps to reproduce
1. Go to Settings -> Email and enter smtp credentials
2. Enter SMTP and try to send email to server

### Screenshots

![image](https://user-images.githubusercontent.com/48992923/94781904-7c48f300-0398-11eb-9dce-eccabc35369b.png)

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/901
- https://github.com/FusionAuth/fusionauth-issues/issues/1326
- https://github.com/FusionAuth/fusionauth-issues/issues/1922
- https://github.com/FusionAuth/fusionauth-issues/issues/2008
- https://github.com/FusionAuth/fusionauth-issues/issues/2011

### Platform

New install Ubuntu 18.04 -> Docker-compose up

**Comment by robotdan** [comment]
Do you see this when opening the dialog, or after you try to send a test email?

**Comment by corepay** [comment]
Hello Dan - as always on top it.

This comes up after trying to send test email to my outgoing smtp service.  Had ports or something wrong cant remember as I moved to gmail smtp server and all working now.

**Comment by robotdan** [comment]
Ok, so perhaps the SMTP test is failing and not returning to the AJAX handler. Perhaps we can enhance this to handle this SMTP connection failure better.

**Comment by robotdan** [comment]
Assuming this is fixed by https://github.com/FusionAuth/fusionauth-issues/issues/2373.
