### ISSUE TITLE
Have escape key close all modals

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#903]
### Problem

You have to move the mouse to close a modal in the administrative UX.

### Solution

I'd like to be able to press the escape key and close whatever modal I'm on. I don't think there are any 2 or 3 level modals, but if so, I'd like to close just the top one on the first key press, then have subsequent modals closed as I pressed each additional key.

### Alternatives/workarounds

Use the mouse :( 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Release Notes
Modal dialogs in the FusionAuth admin UI can now be closed by using the escape key or by clicking outside of the modal.

**Comment by robotdan** [comment]
I actually have this prototyped in `prime-js` just haven't shipped it yet. This would be nice. 

When we visited this last, we initially decided it would be a good idea to only allow the `ESCAPE` key to close a dialog if it wasn't a form. 

Thoughts on that? The thinking was that if you are in a form, filling it out and you hit escape, do you want it to close and possibly lose what you are working on?

**Comment by mooreds** [comment]
I think that it is a safe assumption that we should require more intention from a user when there is data entered, so I'm ok with escape closing a window with no data. 

I'd actually prefer if I could close a form with no data entered using escape, too.

**Comment by robotdan** [comment]
Yes, perhaps we just wait for the first key down and then assume the form has been modified. Or we could get fancy and hash the form data on render and then if it has changed ignore the escape key. 

I'm sure we can figure something out.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/315
