### ISSUE TITLE
What are these cookies?

### ISSUE THREAD

**Issue by vhflat** [FusionAuth/fusionauth-issues#910]
## What is this?

```
 'fusionauth.locale': 'nb',
 'fusionauth.timezone': 'Europe/Oslo',
 'fusionauth.sso': 'AaT_89k0HikwVdmlgRcpsMsANnVBSjY3TEM2anlrUTFQMUd3SFFYSXdfb2ZtZVh2SGUyWFg4Y3hVcnNEdzlEVEg3Z0dlYXRKdw',
  sid: 'dj7QsoffQ79-QeUy1kioN'

```
### Description
I've just started working with fusion auth and I'm new to auth in general. I've tried to implement oauth following the [react example 
](https://github.com/FusionAuth/fusionauth-example-react). 

So i've added the `access_token` to the `req.session`. But then I found these cookies that was created by fusionauth. What its the `fusionauth.sso` and `sid`, and what can I use it for. Can't find any info about it anywhere.

**Comment by robotdan** [comment]
Those cookies aren't really meant for external consumption, they are generated by the FusionAuth SSO. 

`locale` -> Locale, either selected by the user or guessed.
`timezone` - > timezone, guessed in JavaScript or set in the UI
`sso` - Our SSO token

`sid` is not ours.

**Comment by vhflat** [comment]
Thanks for the clarification!
