### ISSUE TITLE
Creating a new tenant copies the connector policy of the default tenant

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#916]
### Description 

If you create a new tenant via the admin UI, the connector policy of the default tenant is copied, whatever it is.

### Affects versions

1.19.8

### Steps to reproduce

1. Have a licensed version of FusionAuth
1. Create a connector 
1. Add the connector to the default tenant as a policy (precise settings don't appear to matter)
1. Create a new tenant (tenantA)
1. Observe that tenantA has the same connector policies as the default tenant.
1. Remove or modify the connector policy of the default tenant (add a different domain, for example)
1. Create a new tenant (tenantB)
1. Observe that tenantB has the same connector policies as the default tenant currently does.

### Expected behavior

The connector policy of a new tenant should be the default value; just the fusionauth connector.

### Platform

n/a

**Comment by robotdan** [comment]
Currently each "new tenant" is sort of a copy, we can review this behavior in the UI and fix this one, and see if other values should have a different default as well. 

We should also add a copy button.

**Comment by robotdan** [comment]
This is working as designed. Not sure I see much of a problem with it. Do you have a strong opinion on this one?

**Comment by andrewpai** [comment]
Closing, as this is no longer the default behavior when creating a tenant - the connector policy list only contains the default connector for new tenants now.
