### ISSUE TITLE
Updating a tenant with two connector policies pointing to the same connector causes an exception

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#917]
### Description 

If you update a tenant, via the API, with a connector policy containing the same connector twice, you get an exception in the logs

### Affects versions
1.19.8

### Steps to reproduce

1. Make sure you have a licensed version of fusionauth
1. Add a generic connector 
1. Add the connector to the default tenant
1. Pull down the tenant info using this curl script: `curl -XGET -H "Authorization: $API_KEY" 'http://localhost:9011/api/tenant/30663132-6464-6665-3032-326466613934' > out.json`
1. Edit out.json and copy any of the connectors to make sure there are two connectors with the same id in the connector policy list
1. Update the tenant by running `curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://localhost:9011/api/tenant/30663132-6464-6665-3032-326466613934' -d@out.json`

You will see this error in the response:

```
{"generalErrors":[{"code":"[Exception]","message":"FusionAuth encountered an unexpected error. Please contact support for assistance."}]}
```

and if you look in the logs, you will see: 

```
2020-10-06 7:31:00.963 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandle
d exception was thrown
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '\xE30
fx\xA5:Id\x90@\x1C\x96\xF3m\xDAr-@!\x07\x86g\x16MK\xB8Q\xD1' for key 'connectors_tenants.PRIMARY'
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO connectors_tenants (tenants_id, connectors_id, data, sequence) VALUES              (?, ?,
 ?, ?)      ,        (?, ?, ?, ?)      ,        (?, ?, ?, ?)      ,        (?, ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '\xE30fx\xA5:Id\x90@\x1C\x96\xF3
m\xDAr-@!\x07\x86g\x16MK\xB8Q\xD1' for key 'connectors_tenants.PRIMARY'
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
        at jdk.internal.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Dele
...
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '\xE30fx\xA5:Id\x90@\x1C\x96\xF3m\xDAr-@!\x07\x86g\x16MK\xB8Q\xD1' for key 'connectors_tenants.PRIMARY'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
```

### Expected behavior

A nice error message stating each connector can be listed at most one time in the connector policy for a tenant.

### Additional context

This exception also happens if you PATCH the tenant, probably because of https://github.com/FusionAuth/fusionauth-issues/issues/441

**Comment by iveelsm** [comment]
Thoughts on this error message @mooreds ?

```
{
  "fieldErrors": {
    "tenant.connectorPolicies": [
      {
        "code": "[duplicate]tenant.connectorPolicies",
        "message": "Duplicate connector policies were specified on the request. Please ensure there is one ID per connector on a request."
      }
    ]
  }
}
```

**Comment by robotdan** [comment]
@iveelsm You can also review all other existing API errors for `[duplicate]` for examples of our existing error wording.

**Comment by mooreds** [comment]
This error message is a bit confusing to me: `Duplicate connector policies were specified on the request. Please ensure there is one ID per connector on a request.`

You are never allowed to have more than one connector policy pointing at given connector (whether on a single request or not). So I might use wording something like this:

`Connectors may only have one policy, but a connector id with an existing policy was provided for this policy. Please ensure that any connector id provided for a policy is not associated with any other policy.`

**Comment by robotdan** [comment]
@mooreds Updated error message:

```json
{
  "fieldErrors" : {
    "tenant.connectorPolicies[1].connectorId" : [ {
      "code" : "[duplicate]tenant.connectorPolicies",
      "message" : "The [tenant.connectorPolicies] contains a duplicate connector Id. The duplicate connector Id is [b259d2ce-1c14-4562-9abc-05903a52bed0], a connector Id can only be specified once in the tenant connector policy."
    } ]
  }
}
```

**Comment by mooreds** [comment]
I'd go with "The [tenant.connectorPolicies] contains more than one policy for the same connector Id. Each connector Id can be specified at most once in a tenant connector policy. The duplicate connector Id is [d28e01e6-302d-45bb-8373-f20c98bff49d]."

The other way felt a bit weird to say.
