### ISSUE TITLE
Cannot run on Docker (after recent release?) AGAIN

### ISSUE THREAD

**Issue by virginijus-servicebridge** [FusionAuth/fusionauth-issues#920]
Hi,

looks like we have same issue again as it was in https://github.com/FusionAuth/fusionauth-issues/issues/870

**Comment by voidmain** [comment]
Just to confirm, what version of FusionAuth docker container are you using? And did you pull to the latest tag of 1.19.8?

**Comment by virginijus-servicebridge** [comment]
We are using this: curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml && curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env && docker-compose up

**Comment by voidmain** [comment]
I'm not well versed in Compose, but I believe you need to pull the latest tag for each of the Docker containers inside the Compose file if the machine you are on has cached versions of the containers. Can you try that and see if it fixes the issue?

**Comment by virginijus-servicebridge** [comment]
looks like cache clearing helped, at least we see wizard for initial setup now.
Consider this issue solved.

**Comment by robotdan** [comment]
For reference, or anyone else that finds this ticket, the `:latest` tag is not dynamic, it is only the latest at a point in time. 

To ensure you have the "latest" `:latest` tag - you can always run this command: `docker pull fusionauth/fusionauth-app:latest`

This is a common point of confusion, and there are lots of opinions on it as you might imagine. For your reading pleasure:

https://vsupalov.com/docker-latest-tag/
https://blog.container-solutions.com/docker-latest-confusion
