### ISSUE TITLE
Number of Docs in elasticsearch > actual number of users.

### ISSUE THREAD

**Issue by ChakshuGautam** [FusionAuth/fusionauth-issues#926]
### Description 
I have 45k users in an instance but the number of docs in elastic search = 85k. It was 92k earlier but after reindex they reduced to 85k. The search results are okay. 

### Affects versions
FusionAuth™ version 1.16.0-RC.1

### Expected behavior
Not sure if they should be equal.

### Screenshots
![Screenshot 2020-10-08 at 9 30 14 PM](https://user-images.githubusercontent.com/7413816/95483679-2c2beb00-09ad-11eb-845e-685641b35f0f.png)
![Screenshot 2020-10-08 at 9 29 54 PM](https://user-images.githubusercontent.com/7413816/95483690-2fbf7200-09ad-11eb-8570-46e69e565ccc.png)

### Platform
Docker

**Comment by ChakshuGautam** [comment]
Follow up question: Is `"_source": ["username", "mobilePhone", ...]` disabled in elastic search? I am not able to get anything using this query except the `id`.

**Comment by robotdan** [comment]
What is the total user count listed under `Reports > Totals` ? And if I understand, after you ran a re-index, the document count from Elasticsearch matches the search results page?

**Comment by ChakshuGautam** [comment]
This is the output of users. 

Registered Users: | 46,209
-- | --
Total Registrations: | 46,744

Even after the re-index, the total didn't match. ~40k more docs in elasticsearch. This is not impacting the search in any way though.

**Comment by robotdan** [comment]
This may have been the same issued under https://github.com/FusionAuth/fusionauth-issues/issues/799.

**Comment by robotdan** [comment]
I think was resolved in #799, please re-open if you see this again or can recreate after version 1.20.0.
