### ISSUE TITLE
application.data not working.

### ISSUE THREAD

**Issue by michailduzhanski** [FusionAuth/fusionauth-issues#927]
### Description
I try hold custom information about the Application in block application.data. But in user registrations block the current application data is empty. Some like this:
[ { "data": {}, "preferredLanguages": [], "tokens": {}, "applicationId": "f26861b6-88cb-44a8-b42a-29919b4ff91f", "id": "127965a6-7c24-4641-906a-1c391499b80e", "insertInstant": "2020-10-08T15:16:30.554Z", "lastLoginInstant": "2020-10-09T08:38:44.405Z", "lastUpdateInstant": "2020-10-08T15:16:30.554Z", "roles": [ "owner" ], "usernameStatus": "ACTIVE", "verified": true } ]

**Comment by mooreds** [comment]
I'm not sure I understand the issue.

If you add anything to `application.data`, then it will be readable when you retrieve the application. This is useful for custom data about an application which is common to all users. An example of this might be application pricing tiers.

If you want to capture custom data about an application which is tied to a user, you want to add to the `registration.data` field. An example of this might be which application pricing tier this user is subscribed to.

Can you explain a bit more about that you are trying to accomplish? Code snippets, if available, are helpful too.

**Comment by robotdan** [comment]
Closing. Please re-open if this is still and issue, and provide as much detail as possible. Thanks!
