### ISSUE TITLE
Add GDPR compatible account export and removal self service pages

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#931]
### Enhancement

The GDPR and similar legislation requires a service to provide access and the ability to delete a user's data.

https://gdpr.eu/article-17-right-to-be-forgotten/

https://gdpr.eu/article-15-right-of-access/

You can implement this with the FusionAuth APIs and webhooks, but it would be nice to go further.

### Solution

Add a themeable profile page to allow a user to download all their personal data (everything attached to the user object) and to delete it.

Add a setting in the tenant to enable/disable this page.

### Alternatives/workarounds

Use the APIs, roll your own page.

### Additional context

This needn't be complete, and probably can't be, since an application could extract user data from FusionAuth via APIs and store it elsewhere.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by voidmain** [comment]
I'm actually going to close this one our and add additional wording to #682 since that issue is already tracking the self-service edit page and has 7 up-votes currently.

**Comment by mooreds** [comment]
I'm going to re-open this since we didn't actually build out this functionality and I could see it being useful.
