### ISSUE TITLE
Removing a Group Membership doesn't update the search index

### ISSUE THREAD

**Issue by wasdennnoch** [FusionAuth/fusionauth-issues#932]
### Description 
When removing a Group Membership from a user, it seems that the Elasticsearch index isn't updating accordingly. The user isn't a member of the Group anymore, and the Group isn't listed in its profile anymore, but when searching for members of that Group (both via the UI and API) the user is returned in the search results.

### Affects versions
1.19.8

### Steps to reproduce
```json
# Add User to Group
POST /api/group/member
{
  "members": {
    "group-id": [{
      "id": "xyz",
      "userId": "user-id"
    }]
  }
}

# Actual Issue Cause - Remove Mmeber again
DELETE /api/group/member
{
  "memberIds": ["xyz"]
}
```

### Expected behavior
The user is not a member of `group-id` anymore, and as such it should not appear in the results when searching for members based on group membership.

### Platform
 - PostgresSQL 12.1, Elasticsearch 6.8.6

**Comment by wasdennnoch** [comment]
FYI - This does _not_ happen when removing a Group membership using the Group ID and User ID like so:
```json
DELETE /api/group/member
{
  "members": {
    "group-id": ["user-id"]
  }
}
```
This seems to update the search index accordingly and the user does not appear in the group member search results anymore.
Removing a member based on the membership ID alone however does cause the desync, as reported above.

**Comment by robotdan** [comment]
Thanks for reporting @wasdennnoch. 

We do re-index the users after each of these type of membership changes, perhaps there is a bug in one of these paths. We will try to recreate your results.

**Comment by robotdan** [comment]
I have been unable to recreate. Please re-open if you can reproduce. Thanks!
