### ISSUE TITLE
the webhook user.registration.create doesnt have the twitter tokens to identify the twitter login.

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#937]
### Description 
When a user is created with twitter, we have a webhook listening on the `user.registration.create`, webhook post data doesnt contain any tokens for twitter.

```json
{
  "event": {
    "applicationId": "2ea97e39-dc5c-4207-af1a-ccdb1f7bf819",
    "createInstant": 1602598988286,
    "id": "765ae2d2-1570-4eee-8964-e267cb972875",
    "registration": {
      "applicationId": "2ea97e39-dc5c-4207-af1a-ccdb1f7bf819",
      "id": "75219301-f693-49ea-a0d6-97fa00af539b",
      "insertInstant": 1602598988283,
      "lastUpdateInstant": 1602598988283,
      "username": "lohithblaze",
      "usernameStatus": "ACTIVE",
      "verified": true
    },
    "tenantId": "33366366-3338-6662-3761-326634663261",
    "type": "user.registration.create",
    "user": {
      "active": true,
      "connectorId": "e3306678-a53a-4964-9040-1c96f36dda72",
      "email": "lohith.venkatesh1@gmail.com",
      "fullName": "Lohith Venkatesh",
      "id": "a98b6b64-7db0-4a7e-8552-2a9624cc0b00",
      "imageUrl": "https://pbs.twimg.com/profile_images/515506312650575874/drxCtY8o_normal.jpeg",
      "insertInstant": 1602598988243,
      "lastUpdateInstant": 1602598988243,
      "passwordChangeRequired": false,
      "passwordLastUpdateInstant": 1602598988279,
      "tenantId": "33366366-3338-6662-3761-326634663261",
      "twoFactorDelivery": "None",
      "twoFactorEnabled": false,
      "usernameStatus": "ACTIVE",
      "verified": true
    }
  }
}
```

### Affects versions
1.18.3

### Steps to reproduce
1. Create twitter Identity provider
2. Login with twitter
3. Have a webhook listeniing to user.registration.create
4. the data sent from user.registration.create  from fusionauth doesnt have any tokens information.

### Expected behavior
The tokens information should be provided in the request.

**Comment by LohithBlaze** [comment]
Hi @robotdan,  did you get a chance to look at this....

**Comment by robotdan** [comment]
What API are you looking to call using the tokens returned in the FusionAuth user? 

The Twitter Login API uses OAuth v1, so all we will have to provide are the OAuth v1 `oauth_token` and the `oauth_token_secret`. I think this means, you'd have to make an OAuth v1 API request using these values. 

https://developer.twitter.com/en/docs/authentication/oauth-1-0a

**Comment by LohithBlaze** [comment]
I need a way to identity that this user is logged in from twitter. For google and facebook, we would know through the tokens field from the json data posted to the provided webhook url, but for twitter there is no way to know.

**Comment by robotdan** [comment]
Is this an issue with FusionAuth or the Twitter API? If FusionAuth, can you open a separate issue?

**Comment by LohithBlaze** [comment]
its issue with fusionauth, the webhook json data received from twitter doesnt have any information in order for me to recognize that this was from twitter.

**Comment by robotdan** [comment]
@LohithBlaze Please open a new issue to describe your use case, and what you would like returned by FusionAuth and what Twitter API you want to call. This will help us understand if this is a something we can support.
