### ISSUE TITLE
Unable to see Events in Event Log in Firefox

### ISSUE THREAD

**Issue by iveelsm** [FusionAuth/fusionauth-issues#938]
### Description 

In Firefox Version 81.X, when attempting to get more details on an event in the event log, you are unable to see the window that results. 

### Affects versions

1.19.X

### Steps to reproduce

1. Create an event in the event log
   NOTE: Recommendation might be an invalid license ID
   Steps in order to create an invalid license ID
   a. Go to Reactor in the Dashboard
   b. Enter a series of invalid characters in the License Box
2. Go to System -> Event Log
3. Find an Event and click the green magnifying glass

### Expected behavior

The pop-up modal should display some more information about the event.

### Screenshots

Before clicking the magnifying glass:

![2020-10-13-121103_1898x938_scrot](https://user-images.githubusercontent.com/9967497/95899044-2d626c80-0d4d-11eb-8691-2e8814cdfe82.png)

After clicking the magnifying glass:

![2020-10-13-121036_1896x944_scrot](https://user-images.githubusercontent.com/9967497/95899014-1face700-0d4d-11eb-892d-39be8ad319f9.png)

### Platform
 - Device: Desktop
 - OS: Arch Linux, MacOS
 - Browser + version: Firefox
 - Database: N/A

**Comment by robotdan** [comment]
Can you verify you don't have any pop up blocker, ad blocker, etc running? And is there anything on the JavaScript console?
