### ISSUE TITLE
On multi step forms, the delete icon obscures the second step title row

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#939]
### Description 

On multi step forms, the delete icon obscures the second step title row. See attached screenshot. Only happens at certain widths.

### Affects versions

1.19.8

### Steps to reproduce
1. Create a multi step form
1. Edit the form, look at the second step title row.

### Expected behavior

No obscuring. This appears to be handled correctly for the first row.

### Screenshots
![Screen Shot 2020-10-13 at 1 45 15 PM](https://user-images.githubusercontent.com/91825/95908989-06ab3280-0d5b-11eb-894f-c4a387629e99.png)

### Platform
- mac
- firefox 81.0.1 and safari Version 14.0 (15610.1.28.1.9, 15610)

Appears to happen at certain widths on firefox and safari, but not all. I was configured to use the docs screen width (as documented here: https://github.com/FusionAuth/fusionauth-site/blob/master/DocsDevREADME.md ) so a width of 1080.

**Comment by andrewpai** [comment]
Closing - this has been fixed since being reported.
