### ISSUE TITLE
Verification email is not sent to the specific user

### ISSUE THREAD

**Issue by ishuvalov** [FusionAuth/fusionauth-issues#941]
### Description 
The tenant's SMTP setting are correct and test emails are successfully delivered. I'm evaluating the FusionAuth right now and often delete/re-create users with the same emails. Verification emails are delivered to all users but one. The only thing that distinguishes the problem user from the others is the fact I initially registered him via Facebook identity provider, so his email was automatically verified. After that I deleted the user via admin GUI and trying to register it with just an email (not Facebook). And emails are not delivered. Manually sent test emails from the SMTP setup page to that address also delivered successfully.
On the Source tab in the raw data for the user it has {verified: false}, but in the registration data it shows as verified `{registrations: [{applicationId: '...', verified: true}]}`
Like If the registration has been cached between user deletion/creation attempts. 

### Affects versions
1.19.8

### Steps to reproduce
1. Set up the FusionAuth application
2. Set up end enable the Facebook identity provider. Make sure that Enable Registration switcher is on for the app above
3. Go to application login URL
4. Click Facebook login button on the login form and log in with you Facebook account
5. Make sure that user was created in FusionAuth admin and it has email verified
6. Mange the newly created user and select Delete User from the menu dropdown
7. Enter the word DELETE below the warning text. Press Enter. Make sure that user was deleted.
8. Go to app *registration* form (not the login form).
9. Register with the same email from the Facebook account you registered with for the first time. (Do not use Facebook login this time!)
10. Newly created user has unconfirmed email. Confirmation email was not sent.

### Expected behavior
Verification email was sent

### Screenshots
![Screenshot 2020-10-14 at 18 14 33](https://user-images.githubusercontent.com/2211978/96009665-9a5b2c80-0e49-11eb-8372-1cb75afa56b1.png)

### Platform
 - Device: Desktop
 - OS: macOS Catalina 10.15.6
 - Browser: Chrome 86
 - Database: PostgresSQL

### Additional context
My test FusionAuth instance is run in Docker using the compose file from installation guide.

**Comment by robotdan** [comment]
> After that I deleted the user via admin GUI and trying to register it with just an email (not Facebook). 

When you recreate the user after deleting the initial user that was created with FB - are you using the API or the FusionAuth admin UI?

**Comment by ishuvalov** [comment]
@robotdan I created the new user using FusionAuth OAuth registration form. 
I think this can be closed. I have double checked and now verification emails are delivered to the new registered user all the time. Seems that the email address I used had some very weird problems when I tested previously.
Thank you for your time!
