### ISSUE TITLE
metadata device on token api

### ISSUE THREAD

**Issue by ShayMoshe** [FusionAuth/fusionauth-issues#947]
### Problem
I want to set `metaData.device.name`, `metaData.device.type`, and `metaData.device.description` when i'm using `oauth2/token`. I can't use the login API, I need to use the OAuth flow.

### Solution

I'd like the ability to set these values when I call the `/oauth2/token` endpoint.

### Alternatives/workarounds

Can't think of any.

### Additional context

Original issue description:

Hi, I'm trying to create new session with type and name, i want to set `metaData.device.name`, `metaData.device.type`, and `metaData.device.description` when i'm using `oauth2/token`. following  issue[OAuth refresh tokens](https://github.com/FusionAuth/fusionauth-issues/issues/81) you can do it by code on Authorization request. can i do something similar in token api?

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@ShayMoshe The short answer is no, you can't. 

Can you explain a bit more about what you are trying to do?

**Comment by robotdan** [comment]
@mooreds is correct. When using the Authorization code grant (OAuth2) these values are set in the browser or provided on the redirect URL to the Authorize endpoint. 
https://fusionauth.io/docs/v1/tech/oauth/endpoints/#authorization-code-grant-request

If you do not need to use OAuth2, you can use the Login API directly which can return you a Refresh Token as well. 
https://fusionauth.io/docs/v1/tech/apis/login/#authenticate-a-user

**Comment by ShayMoshe** [comment]
Thanks @mooreds and @robotdan, I can't use Login API, as I'm creating some custom device flow, so I need to pass the user code in the /token api. but I want to know which device is every session.

maybe you have an idea?

**Comment by mooreds** [comment]
I don't think there's a way at present, unfortunately.

We can use this issue as a feature request tracker and if the community votes it up, it'll move up the implementation roadmap. I'll rework the description a bit to make that clearer.

Alternative if you'd like to pay for us to implement this feature, we can have a discussion about professional services. Please contact us https://fusionauth.io/contact/ and we can start the discussion if that's of interest.

Here's general roadmap guidance: https://fusionauth.io/community/forum/topic/172/the-fusionauth-roadmap

**Comment by ShayMoshe** [comment]
thanks @mooreds let’s hope this feature will be implanted

**Comment by robotdan** [comment]
This almost seems like a bug - in the sense that we don't even allow the option to set these values when using the Password Grant.

**Comment by robotdan** [comment]
Perhaps I misunderatnd the issue. 

From the initial description

> I want to set metaData.device.name, metaData.device.type, and metaData.device.description when i'm using oauth2/token. I can't use the login API, I need to use the OAuth flow.

It sounds like we are using the Password Grant (Resource Owner Credentials Grant). In this code path, we do not accept any of the meta data options to name the refresh token. 

In the Authorization Code grant, these values can be set, some are provided by JavaScript in our theme, but this is all modifiable by an end user of FusionAuth.

**Comment by robotdan** [comment]
https://fusionauth.io/docs/v1/tech/oauth/endpoints/#resource-owner-password-credentials-grant-request

**Comment by robotdan** [comment]
@ShayMoshe In 1.20.1 you can specify these fields on the Password Grant.

**Comment by ShayMoshe** [comment]
Wow! Thanks a lot!
