### ISSUE TITLE
With no reactor license and self service reg disabled, see error when saving an application

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#951]
### Description 

You can end up in a weird error state if you enable self service registration, then choose advanced forms, then disable self service reg.

### Affects versions

1.19.8

### Steps to reproduce
1. Make sure you don't have a reactor license. Decommission if needed.
1. Create a new application.
1. Enable self service registration on the app
1. Choose 'advanced reg form'. You don't need to create one.
1. Disable self service registration.
1. Try to save the app.

You are unable to see the app. The 'registration' tab is highlighted red, but no error message is visible.

### Expected behavior

I would think that once you disable the self service registration, all subsequent validation is turned off/not in force, so I could save the app with the above config.

Barring that, I think showing a more intelligent error that is visible to the end user would be a better experience.

**Comment by amans330** [comment]
The application should validate and display errors only when the self service registration is enabled. On the disabled mode, no validations should take place. The validations will take place eventually when the user decides to edit the application and enable the self service registration. I modified the test cases to test these scenarios in the add and edit action test.

**Comment by amans330** [comment]
https://github.com/FusionAuth/fusionauth-app/pull/26
https://github.com/FusionAuth/fusionauth-api/pull/8
