### ISSUE TITLE
Allow debug setting for SMTP

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#959]
### Problem

I'd like more granularity into the SMTP logging.

### Solution

It looks like you can set the mail session to have debug true, and also can configure logging properties: https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html

https://community.oracle.com/tech/developers/discussion/3996764/how-to-set-the-debug-log-level-in-javamail

I'd like a single switch on the tenants email tab to turn on max debugging (no need for granularity, give it all to the user). This would help with debugging smtp issues.

### Alternatives/workarounds

Change smtp providers. 

Test with SWAKS.

### Additional context

This issue came out of a client having trouble with delays in their email delivery and having a hard time troubleshooting.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
There is currently a test button in the UI to send a test email, and this will return any errors from the SMTP connection. All runtime SMTP errors are logged in the Event Log. 

Are there some additional use cases we would be able to cover by turning on additional debug and dumping it to an event log?

**Comment by dkiser** [comment]
@robotdan - We'd like to be able to turn on logging that allows us to see an outbound relay request with a timestamp so we can troubleshoot items such as "slow email receipt" by customers.  This can help troubleshooting paths between the Fusion Auth Platform itself, a 3rd party mailer, or an actual customer's mail server.

**Comment by robotdan** [comment]
The current behavior is that messages are always sent, and if any type of error occurs, an event log will be recorded. So the lack of an event log means it was sent ok.

I think you are asking for FusionAuth to optionally cut a debug event log each time a message is sent through SMTP so you can confirm that FusionAuth has sent a message to the SMTP service at a particular timestamp to prove that FusionAuth attempted a delivery, and then correlate that with a third party SMTP provider to see when the messages was delivered? 

This would potentially create thousands of event logs in a very brief amount of time.

**Comment by dkiser** [comment]
This is exactly the use case.  Having the logs on both the mailer and FA side would be nice for correlation, but understand if you feel this is too risky to expose as a feature for users on the FA side.

**Comment by robotdan** [comment]
Ok, thanks @dkiser I think I understand the use case. I'lll have to ponder this one, anything we can do to help debug external services like SMTP is a good thing. 

I suppose the volume of event logs is sort of buyer beware, so we could just warn the user before enabling this feature. 

Another thought would be to allow a configuration such as this to be enabled and specify one or more emails addresses that would produce a debug event log. 

This would allow you to trace a specific user or users email deliverability w/out exposing yourself a wave of SMTP debug event logs. 

However... I suppose this is not any different than enabling debug on a lambda which can be fired on each login event, this could have a similar affect.

**Comment by mooreds** [comment]
Definitely agree this is a buyer beware kind of setting that won't be used often, but will save headaches when it is needed.

**Comment by robotdan** [comment]
It could be that all we can do is turn on more verbose (java) logging which would just go through our normal logger. If that is the case, this could be done today using the Logger API (that isn't documented). 

I'll test it out, if it works we could document the way to enable this using an API.

**Comment by robotdan** [comment]
This turned out to be easy and available today.

Step 1. Enable debug

`Tenants > Edit > Advanced > SMTP Settings > Additional properties` Add `mail.debug=true`. 
![image](https://user-images.githubusercontent.com/1148709/97723650-a540ce80-1a91-11eb-9db7-5cd51f482d54.png)

2. Send an email, and view the system logs `System > Logs` and select `fusionauth-app.log`.

**Comment by robotdan** [comment]
@mooreds where should we put this, a debug section in the docs, or mail troubleshooting guide?

**Comment by mooreds** [comment]
I am adding a section to the troubleshooting page in the docs.

**Comment by mooreds** [comment]
This is now deployed: https://fusionauth.io/docs/v1/tech/troubleshooting/

Going to close this; please re-open @dkiser if this doesn't meet your needs.
