### ISSUE TITLE
Cannot register new users

### ISSUE THREAD

**Issue by jsmwoolf** [FusionAuth/fusionauth-issues#96]
### Description
I'm currently helping someone develop a web app/server and I took an interest in FusionAuth to handle authentication/authorization.  I'm implementing this via Node.JS.  I'm also using the Koa framework, Koa router, and Koa body parser.

I'm currently test registering new users against the software and I keep getting the following error:

```
Error: non-error thrown 
{
    "statusCode":401,
    "errorResponse":null,
    "successResponse":null,
    "exception":null
}
```

I'm passing the following:

```node 
auth.post('/register', koaBody(), (ctx, next) => {
    console.log("Registering user with " + ctx.request.body)
    var client = new fusionAuthClient('4093173d-5d70-4f73-9284-e308f0a2f4ba', 'http://localhost:9011');
    console.log(client)
    return client.register(null, {
        registration:{
            applicationId:'4093173d-5d70-4f73-9284-e308f0a2f4ba'
        },
        user:{
            email: ctx.request.body.email,
            firstName: ctx.request.body.firstName,
            lastName: ctx.request.body.lastName,
            mobilePhone: ctx.request.body.phone,
            password: ctx.request.body.password
        }
    }).then((clientResponse) => {
        console.log(clientResponse)
    });
})
```

I'm passing the following values into the call:
```
{ 
  firstName: 'John',
  'lastName:': 'Doe',
  email: 'test@example.com',
  phone: '1234567890',
  username: 'johndoe',
  password: 'password' 
}
```
I also set Authorization to Bear with the Application ID, as specified in the documentation.

Without a further lead, I'm not sure how to proceed to fix this problem.

**Comment by robotdan** [comment]
A 401 means the request is not authorized. Are you setting an `Authorization` header as documented here? https://fusionauth.io/docs/v1/tech/apis/authentication 

Ensure you've created an API key and using that in the `Authorization` header.

https://fusionauth.io/docs/v1/tech/tutorials/create-an-api-key

**Comment by jsmwoolf** [comment]
Ahh...  That's where the problem was.  

When I was looking at the tests for the NodeJS client and the documentation, the key looked like the application id.  Why isn't it using a key the resembles the API key?
