### ISSUE TITLE
Auto login at registration

### ISSUE THREAD

**Issue by bboure** [FusionAuth/fusionauth-issues#962]
### Problem
It would be useful to allow authenticating the user automatically after a successful registration.

### Solution
The `POST /api/user` and `POST /api/user/registration` APIs endpoints should accept a parameter for automatic login when the registration is successful. 
When set to `true`, the api would return the created user AND a `token` + `refreshToken`.

### Alternatives/workarounds
Right now, the alternative is to call `/api/login` manually with the same password.

### Additional context
This is useful to avoid users having to enter their password again after registering, allowing for a better user experience.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This should work already, have you tried it? 

See API response body for:

https://fusionauth.io/docs/v1/tech/apis/users/#create-a-user
https://fusionauth.io/docs/v1/tech/apis/registrations/#create-a-user-and-registration-combined

**Comment by bboure** [comment]
Thanks for your feedback @robotdan 
You are right. I somehow missed that 😕 
Sorry for the inconvenience
