### ISSUE TITLE
the webhook user.registration.create doesnt have any information in order to recognize that this is from twitter user.

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#965]
### Description 
When a user is created with twitter, we have a webhook listening on the user.registration.create, webhook post data doesnt contain any information in the json body that this is from twitter.
```
{
  "event": {
    "applicationId": "2ea97e39-dc5c-4207-af1a-ccdb1f7bf819",
    "createInstant": 1602598988286,
    "id": "765ae2d2-1570-4eee-8964-e267cb972875",
    "registration": {
      "applicationId": "2ea97e39-dc5c-4207-af1a-ccdb1f7bf819",
      "id": "75219301-f693-49ea-a0d6-97fa00af539b",
      "insertInstant": 1602598988283,
      "lastUpdateInstant": 1602598988283,
      "username": "lohithblaze",
      "usernameStatus": "ACTIVE",
      "verified": true
    },
    "tenantId": "33366366-3338-6662-3761-326634663261",
    "type": "user.registration.create",
    "user": {
      "active": true,
      "connectorId": "e3306678-a53a-4964-9040-1c96f36dda72",
      "email": "lohith.venkatesh1@gmail.com",
      "fullName": "Lohith Venkatesh",
      "id": "a98b6b64-7db0-4a7e-8552-2a9624cc0b00",
      "imageUrl": "https://pbs.twimg.com/profile_images/515506312650575874/drxCtY8o_normal.jpeg",
      "insertInstant": 1602598988243,
      "lastUpdateInstant": 1602598988243,
      "passwordChangeRequired": false,
      "passwordLastUpdateInstant": 1602598988279,
      "tenantId": "33366366-3338-6662-3761-326634663261",
      "twoFactorDelivery": "None",
      "twoFactorEnabled": false,
      "usernameStatus": "ACTIVE",
      "verified": true
    }
  }
}
```
### Affects versions
1.18.3

### Steps to reproduce

1.Create twitter Identity provider
2. Login with twitter
3. Have a webhook listeniing to user.registration.create
4. the data sent from user.registration.create from fusionauth doesnt have any information to identify that it is twitter login.
### Expected behavior
The json data should contain atleast an indication that this is from twitter or provide the identity provider lambda id in a way to recognize that this user was from twitter.

**Comment by robotdan** [comment]
I'm confused, this issue resolved the tokens not being returned by FusionAuth. https://github.com/FusionAuth/fusionauth-issues/issues/937 


If you are using version 1.20.1, and you do not see the tokens in the registration object, then FusionAuth still has a bug. 

If you do have something in return, and it is just not what you want, then please explain further for what token you need.

**Comment by LohithBlaze** [comment]
Apologies, the description added was wrong. I have updated the description. When a user is created from twitter login,  the webhook should have atleast some indication that this user was from twitter.

**Comment by robotdan** [comment]
With the fix from #937 you should have a token in the Registration object that contains the Twitter token. The token will be in the format it was provided to us from Twitter. This format is `oauth_token&oauth_token_secret&user_id&screen_name`.

Are you looking for something in addition to this, or is this token not coming back for you in the latest version of FusionAuth?

**Comment by robotdan** [comment]
@LohithBlaze was this resolved?

**Comment by LohithBlaze** [comment]
I havent checked it in the latest version, need to check it once.
