### ISSUE TITLE
Connecting FusionAuth against AWS RDS

### ISSUE THREAD

**Issue by jsmwoolf** [FusionAuth/fusionauth-issues#97]
### Description
I'm trying to use an RDS MySQL instance to act as the database for FusionAuth.  However, FusionAuth is unable to connect to RDS.  Does FusionAuth support this functionality?

If so, would I end up using RDS provided endpoint as the host?

If not, would I just use an EC2 instance?  Docker image?

**Comment by jsmwoolf** [comment]
Nevermind.  It mainly involves messing with the security groups.

**Comment by whiskerch** [comment]
In case it helps anyone else, I am using AWS RDS to store the database for FusionAuth

In my case, making sure they are in the same VPC subnets & setting the correct inbound source is set up (in my case the ip of my kubernetes cluster)
