### ISSUE TITLE
data property on consent entity

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#970]
### Problem
A number of data entities in FusionAuth have `data` property _that can hold any information about the entity that should be persisted_. Consent data entity misses such property.

### Solution
Allow to store arbitrary data on `consent.data` property.

### Alternatives/workarounds
Store consent related data in the external services.

### Additional context
If such functionality were introduced, one might be tempted to store lengthy consents related documents in there. I'am not entirely familiar with the way in which `data` properties are stored in the RDBMS, but I suppose that storing of large amounts of data in there may have influence on the system performance. If it is so, a note on that could be introduced in the documentation.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
This should actually work already. Perhaps we chose not to document until we knew if we wanted to support this - but we have other internal reasons for this field, so it is available already. 

The size will depend on the db type. For the consent specifically, in MySQL we use a `MEDIUMTEXT` field, and in PostgreSQL we use `TEXT`.  


`MEDIUMTEXT` supports up to 2^24 bytes, ~ 16 MB.
https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html

The PostgreSQL `TEXT` is "unlimited" - I'm sure it will exploded eventually, but should be plenty large for anything you need. 
https://www.postgresql.org/docs/9.1/datatype-character.html

If this works for you, we can document the field on the API.

**Comment by mgetka** [comment]
Woah, I didn't imagine this feature would be _covered_ so soon! :sweat_smile: For my case, I need to store only one boolean variable so it's definitely enough space. I believe it is worth mentioning this feature in the documentation. Knowing this in the beginning would have saved me some time trying to solve my problem in a different way.

As for me, this issue can be closed.

**Comment by robotdan** [comment]
I'll keep this open and use it to ensure we get the doc updated accordingly.

**Comment by robotdan** [comment]
Leaving the enhancement tag so we can be sure to add the option to view any custom data on this object in the view dialog in the UI.

**Comment by robotdan** [comment]
Heads up @mgetka if you do use this in the current version, you'll lose the custom data if you edit the consent in the UI. This will be fixed under this issue.
