### ISSUE TITLE
Windows startup script fails with spaces in install directory path

### ISSUE THREAD

**Issue by pamcpd** [FusionAuth/fusionauth-issues#971]
### Description 
In multiple places in the Windows startup.bat script, the files and directories referenced by "%~dp0" are not quoted, meaning it gets set to "C:\Program" if the base install directory is "C:\Program Files". 

### Affects versions
1.20.1

### Steps to reproduce
Ran the install script on Windows Server 2019 to "C:\Program Files". Subsequently, startup.bat failed with message about invalid directory.
**Note: even after adding quotes to the startup script, something within the fusionauth-app still appears to have a directory reference issue also.**

### Expected behavior
Expect Windows startup process to work with standard Windows install locations (e.g., "C:\Program Files").

### Screenshots
n/a

### Platform
Windows Server 2019

### Additional context
Workaround is to install to a directory path without any spaces.
 [Ref forum post](https://fusionauth.io/community/forum/topic/524/windows-install-directory-problem)

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/124
- https://github.com/FusionAuth/fusionauth-search/pull/4

**Comment by robotdan** [comment]
Delivering in 1.37.0, however the Windows install script for `fusionauth-app` will be missing at release. The current plan is support FusionAuth on Windows using WSL v2, and if that doesn't work, then we'll be re-writing the startup script in PowerShell.
