### ISSUE TITLE
Checkboxes in fusionauth admin screen aren't tabbable

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#972]
### Description 

If you are using an edit/add screen in the admin UI, you can't reach the checkboxes via tabbing.

### Affects versions

1.20.1

### Steps to reproduce
1. Go to applications
1. Add a new application
1. Click on the 'OAuth' tab
1. Put your cursor in the name field
1. Hit the tab key

You are sent to the 'Authorized redirect URLs' field, not the 'Require authentication' field.

It also appears that you can't reach the 'Enabled grants' field via tabbing.

This affects the user screen as well, haven't tested any others.

### Expected behavior

Any form field should be accessible to a user via the tab key.

### Platform
(Please complete the following information)
 - Device: macbook pro
 - OS: macos 10.15.7
 - Safari v 14.0
 - Database: mysql (if it matters :) )

**Comment by andrewpai** [comment]
Closing - this has been fixed.
