### ISSUE TITLE
Elixir SDK

### ISSUE THREAD

**Issue by brennan-karrer** [FusionAuth/fusionauth-issues#974]
We're recently interfaced with FusionAuth; however, we noticed that there was no Elixir SDK. As a result, we've been actively developing our own Elixir SDK and have published it on hex.pm here: https://hex.pm/packages/fusion_auth. 

We still have several APIs that we need to continue building out; however, we were hoping to request for official support and to be listed on your website as the official SDK of the Elixir community for FusionAuth.

If there's additional work necessary in order to be officially supported, please let me know what needs to be done and I'll be sure to address any outstanding issues.

Thanks!

**Comment by robotdan** [comment]
This is great! 

If you want to help us directly support and publish this library, there are a few ways you can help. 

We start with a JSON DSL to define each API ( https://github.com/FusionAuth/fusionauth-client-builder/tree/master/src/main/api ). 

We then build the code using a template, for example, here is the  ruby template : https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/ruby.client.ftl

This ruby template then produces the ruby client. 
https://github.com/FusionAuth/fusionauth-ruby-client
https://github.com/FusionAuth/fusionauth-ruby-client/blob/master/lib/fusionauth/fusionauth_client.rb

So if you want to give this a shot, you will basically copy the ruby client template (https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/ruby.client.ftl) to `elxir.client.ftl` and then start hacking on it. With that template we can then build the Elxir client each time we release.

**Comment by brennan-karrer** [comment]
Sweet @robotdan. I'll start playing around with the Ruby template and see how it goes. Is there anyway I can test it out to make sure I'm on the right path and the Elixir client will build properly?

**Comment by mooreds** [comment]
@brennan-karrer I'll add that if you all are supporting Elixir via an OpenAPI spec, it is something we've actively been discussing over here and I'd love to take a look.

**Comment by brennan-karrer** [comment]
@mooreds the package is a pretty straightforward and simply a passthrough to the Fusion APIs. We do not enforce any type of API specification and leave it up to the application consuming the package to format however they see fit. For example, we consume this package and format as JSON API to return the data to our UI. We did add a formatting module [here](https://github.com/Cogility/fusion_auth/blob/master/lib/fusion_auth/response.ex#L3) that optionally allows the user to pass in the type of entity so that it can be extracted from the nested response returned from FusionAuth; however, it doesn't enforce any type of API specification. We wanted to make it pretty flexible to allow the end users to format however they see fit. We could always add in some modules or additional formatters for different API specifications pretty easily.

I'd be more than happy to hop on a call to discuss the package and what you had in mind for the Elixir SDK. Cogility, the company I work for, is pretty eager to contribute back to open source and we're leveraging FusionAuth pretty heavily, so we'd be more than happy to add whatever functionality or API specifications you had in mind in order to get the package officially supported by FusionAuth.

**Comment by robotdan** [comment]
> Is there anyway I can test it out to make sure I'm on the right path and the Elixir client will build properly?

@brennan-karrer there are some instructions here https://github.com/FusionAuth/fusionauth-client-builder as it relates to building. 

Once you get the build working, you can view `build.savant` to see how it is building each template. I'd be happy to stub out the repo in FusionAuth if you want to work on it. We are also happy to assist if you can do the "smart" parts of getting the Elixr syntax correct.

**Comment by mooreds** [comment]
@brennan-karrer , sounds like the best path forward is the fusionauth-client-builder path that @robotdan recommended. I was just curious if you'd looked at OpenAPI, but it's no big deal.

**Comment by brennan-karrer** [comment]
> > Is there anyway I can test it out to make sure I'm on the right path and the Elixir client will build properly?
> 
> @brennan-karrer there are some instructions here https://github.com/FusionAuth/fusionauth-client-builder as it relates to building.
> 
> Once you get the build working, you can view `build.savant` to see how it is building each template.
> 
> I'd be happy to stub out the repo in FusionAuth if you want to work on it. We are also happy to assist if you can do the "smart" parts of getting the Elixr syntax correct.

Thanks for the info. I'll play around with it a bit once I get some free time and if I run into any major roadblocks I'll reach out and see if you can assist. I'm sure you have a full plate and don't want to sidetrack you too much so I'll see where I can get. I've never worked with freemarker before so I'll have to get up-to-speed a bit but shouldn't be a big deal.

> @brennan-karrer , sounds like the best path forward is the fusionauth-client-builder path that @robotdan recommended. I was just curious if you'd looked at OpenAPI, but it's no big deal.

No problem at all, sounds like I'll proceed with the path that @robotdan recommended.

**Comment by brennan-karrer** [comment]
@robotdan I've played around with the client builder and have been able to get everything successfully building; however, I have a few questions on the best path forward at this point:

1. What's the best way to put up a PR to the client-builder repository for the changes to handle the Elixir client? At the moment I've forked the repository and am working off of that.
2. Obviously there is not currently a `fusionauth/fusionauth-elixir-client` repository to work off of. That being said, how would you like me to proceed with pushing code for that repository? Or is this process all automated based off of the client-builder repository and changes?
3. I have a little confusion on what exactly I can add to the `fusionauth-elixir-client` repository. Obviously the main module for communicating with the APIs is auto-generated based on the `/client/elixir.client.ftl` file; however, am I allowed to add custom modules or packages to this repository or do I need to solely rely on the `ftl` file for generating all of that code that will live within the client repository? For example, I wanted to add tests, a custom utility module, and add in a dependency package for executing HTTP requests to the API. Am I ok to add in anything custom to that repository except the main `fusionauth_client.ex` file which is generated from the `ftl` file?
4. I've noticed a pretty standard pattern across a lot of the client packages with functions that follow the same type of pattern as this with functions such as `url_segment`, `url_parameter`, `post`, `go`, etc.:
```
      start.uri('/api/user/change-password')
          .url_segment(change_password_id)
          .body_handler(FusionAuth::JSONBodyHandler.new(request))
          .post()
          .go()
```
Is this a pattern you would like me to abide by and follow for the elixir client?

Also, this client builder is pretty awesome how you guys set it up so nice work!

**Comment by mooreds** [comment]
re #1, I think a fork is fine.

re #2, here you are: https://github.com/FusionAuth/fusionauth-elixir-client (I granted you write access on the repo).

re #3 the domain objects should all be driven off the objects in the client builder library (that way, when a new attribute is added to tenant, it is available to all the client libs at once). But, as you say, tests and dependency management are important, but not part of the client builder. For example, the python lib has `setuptool` code in the lib: https://github.com/fusionauth/fusionauth-python-client 

> Am I ok to add in anything custom to that repository except the main fusionauth_client.ex file which is generated from the ftl file?

You can add custom files to that repo. I think that for static languages we build out a number of artifacts (not just the client, but the domain objects and the client response)

re #4: probably a good idea to keep it as similar as possible. Of course, if one of these flies in the face of "the elixir way", we'd love to discuss it. There's a line to be walked between being idiomatic and maintainable. We'd prefer to be idiomatic in interface and maintainable (perhaps by someone like me with only a passing knowledge of elixir) in implementation.

**Comment by brennan-karrer** [comment]
@mooreds thanks for the quick reply and access to the elixir client repository. That answers all of my questions. I'll create some custom functions to mimic the same approach with function naming that you guys have implemented with the rest of the clients. I have to juggle a few other things at work this week but hopefully I can have enough time to finalize everything before the end of the week. Thanks again!

**Comment by brennan-karrer** [comment]
Sorry to bug you again @mooreds, but it looks like I might not have proper permissions for the repository?
```
Username for 'https://github.com': brennan.karrer@gmail.com
Password for 'https://brennan.karrer@gmail.com@github.com':
remote: Permission to FusionAuth/fusionauth-elixir-client.git denied to brennan-karrer.
fatal: unable to access 'https://github.com/FusionAuth/fusionauth-elixir-client.git/': The requested URL returned error: 403
```

**Comment by mooreds** [comment]
@brennan-karrer it looks like you haven't accepted the invite yet. I think you need to go to https://github.com/FusionAuth/fusionauth-elixir-client/invitations and accept it.

**Comment by brennan-karrer** [comment]
> @brennan-karrer it looks like you haven't accepted the invite yet. I think you need to go to https://github.com/FusionAuth/fusionauth-elixir-client/invitations and accept it.

🤦‍♂️ my apologies. Thanks!

**Comment by robotdan** [comment]
I think we should close this - assuming you can build this with OpenAPI now? 
https://github.com/FusionAuth/fusionauth-openapi

**Comment by mooreds** [comment]
That would be the recommended solution at present.
