### ISSUE TITLE
Required attribute of custom form field incorrect when added to an admin reg form

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#975]
### Description 

If I create a form field using the select form control, I can choose to make this required or not.

But when I add this field to an admin registration form, it shows me that it is required.

### Affects versions

1.20.1

### Steps to reproduce
1. Make sure you have reactor enabled
1. Add a custom form field. Make the form control a select box. The data type I used was 'string'.
1. Make sure this form field is not required.
1. Save it
1. Create a new admin reg form.
1. Add this form field to it.

It looks like it is required (see screen shots). But only when it is first added. If I save the form and then return to edit it a second later, the correct value of `No` is shown for the required column.

### Expected behavior

Would prefer for the form field definition to be the same when first added and when edited, to avoid user confusion.

### Screenshots
<img width="1288" alt="Adding a not required form field" src="https://user-images.githubusercontent.com/91825/98417936-1e669580-203f-11eb-8a9f-e74715eb264c.png">
<img width="1332" alt="Wait, look it is required?" src="https://user-images.githubusercontent.com/91825/98417944-232b4980-203f-11eb-949d-69567f21ad92.png">

**Comment by amans330** [comment]
PR --> https://github.com/FusionAuth/fusionauth-app/pull/24

**Comment by robotdan** [comment]
Accepted PR. https://github.com/FusionAuth/fusionauth-app/pull/24
