### ISSUE TITLE
After calling logout api with refresh token, the issued JWT is still valid until expiry time

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#979]
### Description 
When a user logins, the fusionauth returns access token and refresh token. Currently the logout api only receives the refresh token as a query param and not the access token. When we call the logout api with the refresh token, the fusionauth revokes the refresh token, but the access token issued is still valid even after the logout api is called.

### Affects versions
1.18.3

### Steps to reproduce
1. Call the login api
2. response returned from fusionauth contains the access token and the refresh token
3. call the logout api with the refresh token
4. logout returns 200 OK
5. use the access token issued before logout to validate-jwt api, the token is still valid.

### Expected behavior
After logout, the access token should be revoked as well and should not be valid.

**Comment by robotdan** [comment]
This is the designed behavior. 

These articles may be helpful for you. 
https://fusionauth.io/learn/expert-advice/tokens/pros-and-cons-of-jwts/
https://fusionauth.io/learn/expert-advice/tokens/revoking-jwts/
