### ISSUE TITLE
Implicit flow user registration returns invalid email verification url

### ISSUE THREAD

**Issue by whiskerch** [FusionAuth/fusionauth-issues#98]
### Description 
When creating a new user through an application with self service registration enabled (and using oauth implicit flow) - the verification email sent to the user comes as: 

http://localhost:9011/email/verify/xxxx-xxxxxxxxxxxxxx

FusionAuth is running in a kubernetes cluster, behind an Istio gateway/proxy. 

### Steps to reproduce
1. Create client that uses the OAuth implicit authentication flow (in my case angular app using angular-oauth2-oidc)
2. Call the login flow
3. Select to register the user
4. Complete registration and wait for validation email. 

### Expected behavior
I would expect the url to match the domain it is registered on. e.g if the fusion auth url is: 

https://identity.xxxxx.io then a registration email would like to https://identity.xxxxx.io/email/verify/xxxx-xxxxxxxxxxxxxx

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: OSX
 - Browser + version Chrome

### Additional context

I am using version 1.5

**Comment by whiskerch** [comment]
I have just checked, and manually creating a user from the UI also results in the incorrect link in the verification email - When I was running 1.4.0 this worked correctly, but in 1.5.0 it doesn't

**Comment by robotdan** [comment]
Each email template will default to `http://localhost:9011`.  You will need to modify the email template to update the URL to point to your DNS name. 

This tutorial should help. 
https://fusionauth.io/docs/v1/tech/email-templates/email-templates

**Comment by whiskerch** [comment]
Great! thanks

**Comment by robotdan** [comment]
@whiskerch  I'll leave this open until I know you've been able to get past this issue but feel free to close it out once you've been able to get past this. 

Thanks !

**Comment by gjdass** [comment]
Hello guys.

Just wondering if something like a variable could be created to set this URL into email templates ?
If for some reason we have 30 templates and we want to change a letter in the URL of the SSO, we must do the changes 60 times (30 html,. 30 text).

I understood that the templates are computed and you don't have the real URL at that moment so it cannot be easily done.
What about a button in the GUI triggering a front-only JS function that will update all those URL in template with the current address (window.location stuff) ? Then we can save that updating all addresses at once !

Bad idea ?

**Comment by mooreds** [comment]
@gjdass Please open a new issue for this. It sounds like a feature request. Changing 60 templates sounds like a real pain, though I guess you could use the API to automate it. 

Feature requests tend to get lost when they aren't separate issues. Totally makes sense to references issue #98 in that new one, however.

**Comment by gjdass** [comment]
I will open a feature request thanks.
