### ISSUE TITLE
Unable to complete MFA flow after requesting another code

### ISSUE THREAD

**Issue by DaviddH** [FusionAuth/fusionauth-issues#980]
### Description 
When you login into FusionAuth with MFA enabled using TextMessage, and request another code, you can't get past the screen anymore

![image](https://user-images.githubusercontent.com/1622972/98843104-cbc81780-244a-11eb-865e-af8acdad5acc.png)
![image](https://user-images.githubusercontent.com/1622972/98843122-d1256200-244a-11eb-9286-fe5c813e475a.png)

### Affects versions
1.21.0

### Steps to reproduce
1. Login into FusionAuth with an MFA enabled account using textmessage
2. Click on the 'send another code' option
3. Fill in the newly send code
4. Screen refreshes and you get a new sms code everytime you hit verify

### Expected behavior
To be able to authenticate with the newly SMS code and that the 'send another code' option doesnt disappear after the first time

### Screenshots
![image](https://user-images.githubusercontent.com/1622972/98843104-cbc81780-244a-11eb-865e-af8acdad5acc.png)
![image](https://user-images.githubusercontent.com/1622972/98843122-d1256200-244a-11eb-9286-fe5c813e475a.png)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 10
 - Browser + version: Firefox 82, Chrome 86
 - Database : Postgres 11.5

**Comment by robotdan** [comment]
Thanks for the report @DaviddH we'll take a look.

**Comment by robotdan** [comment]
Workaround:

In your theme, edit the Two Factor template. 

Change this:
```
    <script>
      Prime.Document.onReady(function() {
        new FusionAuth.OAuth2.TwoFactor();
      });
    </script>
```

to this:


```
    <script>
      Prime.Document.onReady(function() {
        new FusionAuth.OAuth2.TwoFactor();
       // Added this next line as a work around.
        Prime.Document.queryById('2fa-form').queryFirst('input[name="resendCode"]').setValue(false);
      });
    </script>
```

This will ensure the field gets reset on page load.

**Comment by DaviddH** [comment]
Thankls for the quick response, just implemented it and works correctly now!

**Comment by robotdan** [comment]
Great, we will correct this in the upcoming release.
