### ISSUE TITLE
Incorrect empty state message for admin registration forms

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#983]
### Description 

When no sections have been added to an admin registration form, you see the error message:

"No steps have been added, click Add step to begin."

which should be "No sections have been added, click Add section to begin."

I see the same issues with the Admin User forms as well.

### Affects versions
1.20.1

### Steps to reproduce
1. Create a new form
1. Select a type of 'admin registration'

### Expected behavior
Have correct message.

### Screenshots
<img width="1192" alt="Empty admin reg form" src="https://user-images.githubusercontent.com/91825/98865901-4ed87600-2429-11eb-869d-c7f76b233de4.png">

**Comment by robotdan** [comment]
Accepted PR https://github.com/FusionAuth/fusionauth-app/pull/23
