### ISSUE TITLE
Get all users with specific role from tenant and application

### ISSUE THREAD

**Issue by DaviddH** [FusionAuth/fusionauth-issues#984]
### Problem
There is no way to directly get all users that have a specific role on an application

### Solution
A way to get all users that have role x on a application

### Alternatives/workarounds
Currently we enumerate all users on an application to get the ones with roles x but this very inefficiënt

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment]
@DaviddH you can do this already. Here's an example API call:

```
API_KEY=...

curl -H "Content-type: application/json" -H "Authorization: $API_KEY" https://demo.fusionauth.io/api/user/search -d '{
  "search": {
    "numberOfResults": 50,
    "query": "{\"bool\":{\"must\":[{\"nested\":{\"path\":\"registrations\",\"query\":{\"bool\":{\"must\":[{\"match\":{\"registrations.roles\":\"ADMIN\"}},{\"match\":{\"registrations.verified\":false}}]}}}}]}}",
    "startRow": 0
  }
}
'
```

This is documented here: https://fusionauth.io/docs/v1/tech/apis/users/#search-for-users

Or am I misunderstanding what you are trying to accomplish?

**Comment by DaviddH** [comment]
We where using the database search engine which doesn't offer this possibility, we will switch to elasticsearch so that we can do this more efficiently. Although an api call like getUsersByApplicationRole would be a great addition since now this requires an extra external service.

Thanks for the quick response!

**Comment by mooreds** [comment]
I think it's pretty unlikely we'd start to build more search functionality into the database search engine. If you have complex searching needs, we recommend you leverage ElasticSearch, which has rich search functionality.

Can we consider this issue closed, @DaviddH ?
