### ISSUE TITLE
Default domains for connector policy not set

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#985]
### Description 
If you add a connector policy for a tenant, the documentation states the default is `[*]`.

https://fusionauth.io/docs/v1/tech/apis/tenants/

But it apparently isn't.

### Affects versions

Unclear, haven't replicated this yet.

### Steps to reproduce
1. Create a tenant
1. Create a connector
1. Create an API key
1. Update the tenant with the connector, don't specify the domains the connector applies to.

### Expected behavior

If you update a tenant with a connector policy but no domains array, it would default to `[*]`.

Alternatively, make the domains field required in the documentation would suffice.

### Additional context

Split off from this issue: https://github.com/FusionAuth/fusionauth-issues/issues/982

They found it happened with kickstart, unsure if that is part of the issue.

**Comment by robotdan** [comment]
This may have been solved under https://github.com/FusionAuth/fusionauth-issues/issues/1367. Does this still occur?

**Comment by andrewpai** [comment]
Confirmed - this has been fixed. Closing issue.
