### ISSUE TITLE
Searching for 'twoFactorEnabled' and 'twoFactorDelivery' using elasticsearch

### ISSUE THREAD

**Issue by DaviddH** [FusionAuth/fusionauth-issues#987]
### Problem
We want to easily retrieve all users from fusionAuth where two factor authentication is not enabled, but the fields 'twoFactorEnabled' and 'twoFactorDelivery' aren't included in the search index

### Solution
Add 'twoFactorEnabled' and 'twoFactorDelivery' as searchable fields in the search index

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Added this to the list of related items that we can review as part of the delivery of https://github.com/FusionAuth/fusionauth-issues/issues/960.

**Comment by robotdan** [comment]
This was added in 1.30.1 
https://fusionauth.io/docs/v1/tech/release-notes#version-1-30-1
